// Canonical Source evidence requirements - per-stage operational catalog.
//
// This catalog is intentionally practical. It tells a client which system of
// record usually owns each extract, which fields AbarVa should parse/persist,
// and which upload filename tokens reconcile a filled template back to the
// right requirement. Source stages consume this as a product contract; tenant
// adapters can vary, but they must normalize into these shared evidence classes.

import type { SourceDataReadinessState, SourceStageKey } from "../types";

export type EvidenceMinimumState = Extract<
  SourceDataReadinessState,
  "Loaded" | "Parsed" | "Available" | "Usable Evidence"
>;

export type SourceEvidenceClass =
  | "approved_agreement"
  | "benchmark"
  | "change_order"
  | "cloud_consumption"
  | "contract_term"
  | "finance_value_confirmation"
  | "invoice"
  | "payment"
  | "rate_card"
  | "renewal"
  | "risk_control"
  | "scope"
  | "service_credit"
  | "sla"
  | "supplier_offer"
  | "usage"
  | "workforce";

export interface SourceEvidenceRequirement {
  /** Stable id, e.g. `EVID-SRC-SCOPE-TICKET-HISTORY`. */
  requirementId: string;
  stage: SourceStageKey;
  /** Human label for the readiness panel. */
  label: string;
  /** Shared semantic class used by Source, Door 1, Tower handoff, and aVa. */
  evidenceClass: SourceEvidenceClass;
  /** Where this evidence comes from in the source system. */
  sourceLabel: string;
  /** Concrete systems or repositories a real client can export from. */
  sourceSystems: readonly string[];
  /** Accepted source file families for the first controlled extract. */
  acceptedFileTypes: readonly string[];
  /** Record grain AbarVa expects after parse/persist. */
  recordGrain: string;
  /** Fields we should parse/persist when present. */
  criticalFields: readonly string[];
  /** Filename tokens that auto-link an upload/template to this requirement. */
  filenameTokens: readonly string[];
  /** Quality checks applied before treating the upload as usable evidence. */
  qualityChecks: readonly string[];
  /** Lowest readiness state that satisfies the requirement. */
  minimumState: EvidenceMinimumState;
  /** required = blocks gate; recommended = surfaces but does not block. */
  level: "required" | "recommended";
  /** Description for the data-readiness drawer. */
  description: string;
  /** What the evidence unlocks if it reaches minimum state. */
  unlocks: string;
}

function req(requirement: SourceEvidenceRequirement): SourceEvidenceRequirement {
  return requirement;
}

// Stage 1 - Strategy
const STRATEGY: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-STR-TRIGGER",
    stage: "strategy",
    label: "Sourcing trigger and business case",
    evidenceClass: "scope",
    sourceLabel: "Portfolio governance, renewal calendar, incident or budget trigger",
    sourceSystems: ["ServiceNow SPM", "Planview", "Clarity", "Coupa Intake", "SharePoint"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "pdf", "txt"],
    recordGrain: "one trigger per sourcing event",
    criticalFields: ["trigger_type", "trigger_date", "business_owner", "affected_scope", "urgency", "expected_decision_date"],
    filenameTokens: ["trigger", "business_case", "intake", "mandate"],
    qualityChecks: ["Trigger names the business reason and date", "Owner is a role or group, not an employee name"],
    minimumState: "Parsed",
    level: "required",
    description: "The reason the event exists: renewal, cost pressure, service issue, merger, risk, or strategic change.",
    unlocks: "Event archetype, urgency, and Door 1 versus competitive sourcing path.",
  }),
  req({
    requirementId: "EVID-SRC-STR-INCUMBENT",
    stage: "strategy",
    label: "Incumbent contract package",
    evidenceClass: "contract_term",
    sourceLabel: "CLM and contract repository",
    sourceSystems: ["Icertis", "DocuSign CLM", "Agiloft", "Ironclad", "SharePoint", "Box"],
    acceptedFileTypes: ["pdf", "docx", "xlsx"],
    recordGrain: "one agreement, SOW, order form, amendment, or renewal notice per row/document",
    criticalFields: ["contract_id", "vendor_id", "agreement_type", "effective_date", "end_date", "notice_period_days", "annual_value", "auto_renewal", "benchmarking_clause"],
    filenameTokens: ["incumbent", "contract", "msa", "sow", "agreement", "renewal"],
    qualityChecks: ["Contract id and vendor align to Source contract 360", "Dates and values are extracted with source page or row lineage"],
    minimumState: "Available",
    level: "required",
    description: "Executed incumbent documents and commercial metadata for baseline, renewal, rights, and leverage.",
    unlocks: "Optimization path, renewal gates, commercial levers, and contract evidence trace.",
  }),
  req({
    requirementId: "EVID-SRC-STR-SPEND-BASELINE",
    stage: "strategy",
    label: "Spend baseline",
    evidenceClass: "invoice",
    sourceLabel: "ERP/AP, procurement spend cube, or TBM system",
    sourceSystems: ["SAP S/4HANA AP", "Oracle Fusion AP", "Coupa", "Ariba", "Apptio", "Power BI spend mart"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one invoice line, PO line, GL line, or vendor-month total per row",
    criticalFields: ["vendor_id", "contract_id", "po_number", "invoice_number", "invoice_date", "cost_center", "gl_account", "amount", "currency", "period"],
    filenameTokens: ["spend", "invoice", "ap", "po", "baseline", "gl_export"],
    qualityChecks: ["Period coverage is stated", "Total reconciles to finance extract within tolerance", "Currency is explicit"],
    minimumState: "Available",
    level: "required",
    description: "Actual spend baseline used to size the opportunity and detect off-contract or duplicate leakage later.",
    unlocks: "Value-at-stake sizing, concentration view, and finance-backed comparison.",
  }),
  req({
    requirementId: "EVID-SRC-STR-SPONSOR-COMMIT",
    stage: "strategy",
    label: "Sponsor commitment",
    evidenceClass: "approved_agreement",
    sourceLabel: "Governance log, approval workflow, or email record",
    sourceSystems: ["ServiceNow SPM", "Jira Align", "Coupa Intake", "Teams export", "SharePoint"],
    acceptedFileTypes: ["pdf", "docx", "txt", "eml", "xlsx", "csv"],
    recordGrain: "one approval or commitment per row/document",
    criticalFields: ["sponsor_role", "decision_owner_role", "approval_date", "approved_scope", "decision_needed", "constraints"],
    filenameTokens: ["sponsor", "commitment", "governance", "authoriz", "approval"],
    qualityChecks: ["Named owner is a role/title reference", "Approval scope matches event scope"],
    minimumState: "Loaded",
    level: "required",
    description: "Evidence that the business sponsor authorizes work to proceed and owns the decision.",
    unlocks: "Strategy memo signing and approval workflow creation.",
  }),
  req({
    requirementId: "EVID-SRC-STR-MARKET-BENCHMARK",
    stage: "strategy",
    label: "Market and benchmark scan",
    evidenceClass: "benchmark",
    sourceLabel: "Analyst, sourcing benchmark, or prior event archive",
    sourceSystems: ["Gartner", "Forrester", "ISG", "GEP", "Coupa Sourcing", "Ariba Sourcing", "SharePoint"],
    acceptedFileTypes: ["pdf", "pptx", "xlsx", "csv"],
    recordGrain: "one benchmark, peer reference, or market option per row/section",
    criticalFields: ["category", "service_line", "benchmark_source", "percentile_or_range", "effective_date", "geography", "limitations"],
    filenameTokens: ["benchmark", "market", "intel", "landscape", "peer"],
    qualityChecks: ["Benchmark date and scope are visible", "Limitations are captured instead of overgeneralized"],
    minimumState: "Parsed",
    level: "recommended",
    description: "External or internal market evidence that explains whether a reprice, renewal, or recompete is plausible.",
    unlocks: "Archetype selection and first-pass commercial lever list.",
  }),
];

// Stage 2 - Scope
const SCOPE: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-SCOPE-APP-INV",
    stage: "scope",
    label: "Application and service inventory",
    evidenceClass: "scope",
    sourceLabel: "CMDB, application portfolio, or service catalog",
    sourceSystems: ["ServiceNow CMDB", "LeanIX", "Mega HOPEX", "Apptio", "Excel portfolio inventory"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one application, service, or platform per row",
    criticalFields: ["application_id", "application_name", "business_function", "criticality", "hosting_model", "lifecycle_state", "support_vendor", "annual_run_cost"],
    filenameTokens: ["application", "app_inventory", "cmdb", "portfolio", "service_catalog"],
    qualityChecks: ["Every row has a stable application or service id", "Criticality and lifecycle are explicit where known"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "The operational scope being sourced, including applications, platforms, services, cost, and criticality.",
    unlocks: "Scope memo economics, exclusion logic, retained-cost model, and application/vendor dependency map.",
  }),
  req({
    requirementId: "EVID-SRC-SCOPE-TICKET-HISTORY",
    stage: "scope",
    label: "L2/L3 ticket history and service volumetrics",
    evidenceClass: "usage",
    sourceLabel: "ITSM and operational reporting",
    sourceSystems: ["ServiceNow ITSM", "Jira Service Management", "BMC Remedy", "Splunk dashboards", "Power BI ops mart"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one service tower, queue, month, severity, or ticket class per row",
    criticalFields: ["service_tower", "period", "ticket_count", "severity", "sla_met", "backlog", "automation_eligible", "resolver_group"],
    filenameTokens: ["ticket", "incident", "itsm", "volume", "servicenow", "queue"],
    qualityChecks: ["Period coverage is stated", "Severity and service tower definitions are included", "Ticket counts reconcile to source dashboard total where provided"],
    minimumState: "Available",
    level: "required",
    description: "Demand profile by service tower, severity, and volume so scope and pricing are grounded in real workload.",
    unlocks: "Volume bands, productivity levers, retained-cost sizing, and SLA pressure points.",
  }),
  req({
    requirementId: "EVID-SRC-SCOPE-WORKFORCE",
    stage: "scope",
    label: "Workforce and role baseline",
    evidenceClass: "workforce",
    sourceLabel: "HRIS, VMS, and contractor roster",
    sourceSystems: ["Workday", "SAP SuccessFactors", "Fieldglass", "Beeline", "Excel roster"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one role, team, location, or contractor worker class per row",
    criticalFields: ["role_ref", "role_title", "team", "location", "fte_count", "contractor_count", "loaded_cost", "in_scope_flag", "retained_or_transition"],
    filenameTokens: ["org", "roster", "headcount", "workforce", "staffing", "fte"],
    qualityChecks: ["No employee names, emails, phone numbers, or employee IDs", "Role and team references are sufficient to size impact"],
    minimumState: "Available",
    level: "required",
    description: "Role-level baseline for retained work, transition planning, and supplier staffing assumptions.",
    unlocks: "KT planning, retained organization sizing, and labor arbitrage checks.",
  }),
  req({
    requirementId: "EVID-SRC-SCOPE-CURRENT-SOW",
    stage: "scope",
    label: "Current SOW and change-order scope",
    evidenceClass: "change_order",
    sourceLabel: "CLM, SOW repository, and change-order tracker",
    sourceSystems: ["Icertis", "DocuSign CLM", "SharePoint", "Coupa Contracts", "Ariba Contracts"],
    acceptedFileTypes: ["pdf", "docx", "xlsx", "csv"],
    recordGrain: "one SOW, work order, amendment, change order, or scope line per row/document",
    criticalFields: ["sow_id", "contract_id", "change_order_id", "effective_date", "scope_summary", "value", "cumulative_value", "approver_role", "reason_category"],
    filenameTokens: ["sow", "work_order", "change_order", "scope", "amendment"],
    qualityChecks: ["Change orders retain sequence and cumulative position", "Scope additions are not collapsed into a single count"],
    minimumState: "Available",
    level: "required",
    description: "Current contractual scope and scope-change history, including work orders and cumulative change-order exposure.",
    unlocks: "Scope boundary, leakage diagnosis, and incumbent optimization story.",
  }),
  req({
    requirementId: "EVID-SRC-SCOPE-FY-CONTRACT",
    stage: "scope",
    label: "Prior fiscal contract and run-cost baseline",
    evidenceClass: "contract_term",
    sourceLabel: "Procurement, CLM, finance baseline, and prior-year spend archive",
    sourceSystems: ["Icertis", "DocuSign CLM", "SAP S/4HANA AP", "Oracle Fusion AP", "Apptio", "SharePoint"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one prior agreement, fiscal period, budget line, spend line, or commercial baseline per row/document",
    criticalFields: ["contract_id", "vendor_id", "fiscal_year", "baseline_amount", "actual_amount", "currency", "cost_center", "source_ref"],
    filenameTokens: ["fy_contract", "prior_contract", "support_contract", "contract_spend", "run_cost", "budget", "spend", "baseline_spend"],
    qualityChecks: ["Fiscal period and currency are explicit", "Prior contract and actual spend are not mixed without a basis"],
    minimumState: "Available",
    level: "required",
    description: "Prior fiscal contract and run-cost evidence used as the baseline for scope and pricing assumptions.",
    unlocks: "Scope economics, pricing assumptions, and value-at-stake baseline.",
  }),
  req({
    requirementId: "EVID-SRC-SCOPE-SLA-BASELINE",
    stage: "scope",
    label: "SLA and service-credit baseline",
    evidenceClass: "sla",
    sourceLabel: "ServiceNow SLA reporting, contract SLA schedules, and credit logs",
    sourceSystems: ["ServiceNow ITSM", "Splunk", "Datadog", "CLM SLA schedule", "Excel credit register"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one SLA metric, month, service tower, or credit event per row",
    criticalFields: ["contract_id", "sla_name", "period", "target", "actual", "breach_count", "credit_earned", "credit_claimed", "credit_received"],
    filenameTokens: ["sla", "service_credit", "credit", "performance", "breach"],
    qualityChecks: ["Credits earned, claimed, and received remain separate", "Metric definitions and periods are visible"],
    minimumState: "Parsed",
    level: "required",
    description: "Operational performance baseline and service-credit evidence for recoverable leakage analysis.",
    unlocks: "Service-credit leakage, performance carve-outs, and contract remedies.",
  }),
  req({
    requirementId: "EVID-SRC-SCOPE-DATA-ACCESS",
    stage: "scope",
    label: "Source data access and owner map",
    evidenceClass: "risk_control",
    sourceLabel: "Data owner list and system access inventory",
    sourceSystems: ["ServiceNow Catalog", "SailPoint", "Okta", "Azure AD", "SharePoint"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "txt"],
    recordGrain: "one source system, owner role, access method, or extract per row",
    criticalFields: ["source_system", "owner_role", "extract_method", "refresh_frequency", "approval_needed", "restriction_reason", "target_due_date"],
    filenameTokens: ["data_access", "source_owner", "extract_plan", "access"],
    qualityChecks: ["Restricted data is explicitly marked", "Each critical source has an owner role and extract path"],
    minimumState: "Loaded",
    level: "recommended",
    description: "Practical source-owner map for the extracts the event needs before supplier engagement.",
    unlocks: "Evidence request plan and data-readiness operating cadence.",
  }),
];

// Stage 3 - RFP
const RFP: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-RFP-REQUIREMENTS",
    stage: "rfp",
    label: "Requirements and service levels",
    evidenceClass: "scope",
    sourceLabel: "Business requirements workbook, service catalog, and current SLA schedule",
    sourceSystems: ["ServiceNow Catalog", "Confluence", "SharePoint", "CLM SLA schedule", "Excel workbook"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "pdf"],
    recordGrain: "one requirement, service level, exhibit item, or acceptance criterion per row",
    criticalFields: ["requirement_id", "service_area", "priority", "current_state", "target_state", "acceptance_criterion", "owner_role"],
    filenameTokens: ["requirement", "service_level", "rfx_scope", "exhibit"],
    qualityChecks: ["Must/should/could priority is explicit", "Each requirement has a business owner role"],
    minimumState: "Available",
    level: "required",
    description: "Structured requirements and service levels that the RFP will ask suppliers to commit to.",
    unlocks: "RFP package, scorecard criteria, and response coverage checks.",
  }),
  req({
    requirementId: "EVID-SRC-RFP-LEGAL-TEMPLATE",
    stage: "rfp",
    label: "Approved legal and commercial template",
    evidenceClass: "contract_term",
    sourceLabel: "Legal playbook and procurement template library",
    sourceSystems: ["Icertis", "DocuSign CLM", "Ironclad", "SharePoint legal library"],
    acceptedFileTypes: ["docx", "pdf"],
    recordGrain: "one template, clause fallback, or required term per section",
    criticalFields: ["template_version", "clause_name", "fallback_position", "owner_role", "required_flag", "last_approved_date"],
    filenameTokens: ["legal", "terms", "template", "dpa", "liability"],
    qualityChecks: ["Template version and approval date are visible", "Required clauses are distinguishable from fallback positions"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Legal-approved baseline terms, data protection terms, liability positions, and commercial guardrails.",
    unlocks: "RFP release, redline evaluation, and risk exception tracking.",
  }),
  req({
    requirementId: "EVID-SRC-RFP-VENDOR-INTEL",
    stage: "rfp",
    label: "Supplier market intelligence",
    evidenceClass: "benchmark",
    sourceLabel: "Analyst reports, supplier database, and prior sourcing events",
    sourceSystems: ["Gartner", "Forrester", "ISG", "Dun & Bradstreet", "Ariba Supplier Risk", "Coupa"],
    acceptedFileTypes: ["pdf", "pptx", "xlsx", "csv"],
    recordGrain: "one supplier option, capability, reference, risk, or benchmark per row/section",
    criticalFields: ["vendor_id", "category", "capability", "reference_type", "risk_signal", "benchmark_source", "geography"],
    filenameTokens: ["vendor", "supplier", "market", "intel", "landscape", "shortlist"],
    qualityChecks: ["Market source and date are captured", "Known conflicts or limitations are preserved"],
    minimumState: "Available",
    level: "recommended",
    description: "Supplier landscape and comparable market options used to justify shortlist and negotiation alternatives.",
    unlocks: "Shortlist rationale, leverage analysis, and benchmark-backed negotiation paths.",
  }),
  req({
    requirementId: "EVID-SRC-RFP-SECURITY-PRIVACY",
    stage: "rfp",
    label: "Security, privacy, and AI obligations",
    evidenceClass: "risk_control",
    sourceLabel: "Security questionnaire, privacy/DPA library, and AI governance register",
    sourceSystems: ["OneTrust", "Archer", "ServiceNow GRC", "Vanta", "SecurityScorecard", "CLM DPA library"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one obligation, control, data type, subprocessor, or questionnaire item per row",
    criticalFields: ["control_id", "obligation", "data_type", "subprocessor", "residency", "audit_right", "ai_use_restriction", "owner_role"],
    filenameTokens: ["security", "privacy", "dpa", "ai_obligation", "risk_control"],
    qualityChecks: ["Subprocessors and data types are explicit", "Mandatory controls are distinguishable from informational controls"],
    minimumState: "Available",
    level: "required",
    description: "Security, privacy, data, AI, and control requirements that must be carried into supplier response and contract terms.",
    unlocks: "Security exhibit, risk review, and redline exception tracking.",
  }),
  req({
    requirementId: "EVID-SRC-RFP-SOURCING-RULES",
    stage: "rfp",
    label: "Sourcing rules and evaluation process",
    evidenceClass: "risk_control",
    sourceLabel: "Procurement policy, event rules, and communications plan",
    sourceSystems: ["Coupa Sourcing", "Ariba Sourcing", "Jaggaer", "SharePoint procurement playbook"],
    acceptedFileTypes: ["docx", "pdf", "xlsx"],
    recordGrain: "one event rule, timeline, communication rule, or scoring protocol per row/section",
    criticalFields: ["rule_name", "applies_to", "deadline", "communication_channel", "disqualification_condition", "owner_role"],
    filenameTokens: ["sourcing_rules", "process", "timeline", "communications"],
    qualityChecks: ["Dates and decision rights are stated", "Vendor communication constraints are captured"],
    minimumState: "Parsed",
    level: "required",
    description: "Procurement operating rules for fair supplier engagement and defensible evaluation.",
    unlocks: "RFP governance, supplier Q&A control, and audit trail.",
  }),
];

// Stage 4 - Responses
const RESPONSES: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-RESP-PROPOSALS",
    stage: "responses",
    label: "Supplier proposal responses",
    evidenceClass: "supplier_offer",
    sourceLabel: "Sourcing portal, supplier emails, and response folders",
    sourceSystems: ["Ariba Sourcing", "Coupa Sourcing", "Jaggaer", "SharePoint", "Box"],
    acceptedFileTypes: ["pdf", "docx", "xlsx", "pptx"],
    recordGrain: "one supplier response, requirement answer, exhibit, or attachment per row/document",
    criticalFields: ["vendor_id", "requirement_id", "response_status", "response_text", "exception_flag", "attachment_ref"],
    filenameTokens: ["proposal", "response", "bid", "submission", "supplier_response"],
    qualityChecks: ["Every response maps to a supplier and requirement where applicable", "Exceptions are not lost inside narrative"],
    minimumState: "Available",
    level: "required",
    description: "Supplier response coverage and content for the requirements, commercials, transition, and risk exhibits.",
    unlocks: "Completeness checks, evaluation scoring, and response comparison.",
  }),
  req({
    requirementId: "EVID-SRC-RESP-PRICING-SHEETS",
    stage: "responses",
    label: "Supplier pricing sheets",
    evidenceClass: "supplier_offer",
    sourceLabel: "Supplier pricing workbook uploads",
    sourceSystems: ["Ariba Sourcing", "Coupa Sourcing", "Jaggaer", "Excel pricing workbook"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one supplier, rate, volume tier, service line, or price element per row",
    criticalFields: ["vendor_id", "price_element", "service_line", "unit", "volume_band", "unit_price", "currency", "assumption_ref"],
    filenameTokens: ["pricing", "price", "rate", "commercial", "cost_model"],
    qualityChecks: ["Currency and unit are explicit", "Assumption deviations are retained", "Totals can be recomputed from detail"],
    minimumState: "Available",
    level: "required",
    description: "Detailed supplier pricing and rate-card responses, not just a headline number.",
    unlocks: "Normalized TCO, price variance, volume-tier comparison, and BAFO levers.",
  }),
  req({
    requirementId: "EVID-SRC-RESP-CLARIFICATIONS",
    stage: "responses",
    label: "Q&A and clarifications",
    evidenceClass: "supplier_offer",
    sourceLabel: "Sourcing portal Q&A log",
    sourceSystems: ["Ariba Sourcing", "Coupa Sourcing", "Jaggaer", "Teams export", "Excel Q&A log"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "txt"],
    recordGrain: "one supplier question, client answer, clarification, or addendum per row",
    criticalFields: ["question_id", "vendor_id", "question_text", "answer_text", "published_to_all_flag", "answered_date", "impact_area"],
    filenameTokens: ["clarification", "q&a", "qa_", "question", "answer", "addendum"],
    qualityChecks: ["Published-to-all flag is captured", "Question and answer dates are visible"],
    minimumState: "Loaded",
    level: "required",
    description: "Supplier questions and client answers that may alter scope, assumptions, or evaluation.",
    unlocks: "Response completeness and defensible supplier communication trail.",
  }),
  req({
    requirementId: "EVID-SRC-RESP-EXCEPTIONS",
    stage: "responses",
    label: "Legal and commercial exceptions",
    evidenceClass: "contract_term",
    sourceLabel: "Supplier redlines and exception matrices",
    sourceSystems: ["Icertis", "DocuSign CLM", "Ironclad", "SharePoint", "Excel exception matrix"],
    acceptedFileTypes: ["docx", "pdf", "xlsx", "csv"],
    recordGrain: "one clause exception, redline, fallback, or unresolved term per row/section",
    criticalFields: ["vendor_id", "clause_name", "client_position", "supplier_position", "risk_level", "fallback_accepted", "owner_role"],
    filenameTokens: ["exception", "redline", "clause", "deviation"],
    qualityChecks: ["Supplier position remains separate from client fallback", "Risk levels are reviewable by Legal/Procurement"],
    minimumState: "Parsed",
    level: "recommended",
    description: "Supplier deviations from legal, commercial, security, and operational requirements.",
    unlocks: "Risk scoring, negotiation issue log, and executive trade-off pack.",
  }),
  req({
    requirementId: "EVID-SRC-RESP-REFERENCE-CHECKS",
    stage: "responses",
    label: "Supplier references and proof points",
    evidenceClass: "benchmark",
    sourceLabel: "Reference calls, analyst notes, and client case evidence",
    sourceSystems: ["Gartner Peer Insights", "Reference call notes", "SharePoint", "CRM reference library"],
    acceptedFileTypes: ["docx", "pdf", "txt", "xlsx"],
    recordGrain: "one reference, proof point, caution, or capability claim per row/section",
    criticalFields: ["vendor_id", "reference_type", "industry", "scope_similarity", "proof_point", "concern", "validated_by_role"],
    filenameTokens: ["reference", "proof_point", "case_study", "call_notes"],
    qualityChecks: ["Claims distinguish supplier assertion from client-validated reference", "Relevance to scope is captured"],
    minimumState: "Parsed",
    level: "recommended",
    description: "External and internal proof points that validate supplier capability beyond proposal language.",
    unlocks: "Qualitative differentiation, risk review, and executive narrative.",
  }),
];

// Stage 5 - Evaluation
const EVALUATE: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-EVAL-RATER-SCORES",
    stage: "evaluation",
    label: "Rater scores and rationales",
    evidenceClass: "supplier_offer",
    sourceLabel: "Scorecard tool or evaluation workbook",
    sourceSystems: ["Ariba Sourcing", "Coupa Sourcing", "Excel scorecard", "Smartsheet", "Airtable"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one rater, vendor, criterion, score, and rationale per row",
    criticalFields: ["vendor_id", "criterion_id", "rater_role", "score", "rationale", "confidence", "review_date"],
    filenameTokens: ["score", "rating", "evaluation", "rater", "scorecard"],
    qualityChecks: ["At least two raters where required", "Rationale exists for outlier or low-confidence scores"],
    minimumState: "Available",
    level: "required",
    description: "Structured scores and rater rationale for supplier comparison and auditability.",
    unlocks: "Governance sign-off, deviation analysis, and selection evidence.",
  }),
  req({
    requirementId: "EVID-SRC-EVAL-WEIGHT-RATIONALE",
    stage: "evaluation",
    label: "Weighting rationale",
    evidenceClass: "risk_control",
    sourceLabel: "Evaluation design notes and sponsor governance minutes",
    sourceSystems: ["SharePoint", "Teams meeting notes", "Confluence", "ServiceNow SPM"],
    acceptedFileTypes: ["docx", "pdf", "txt", "xlsx"],
    recordGrain: "one criterion, weight, owner, and rationale per row/section",
    criticalFields: ["criterion_id", "weight", "rationale", "approved_by_role", "approval_date", "change_reason"],
    filenameTokens: ["weight", "criteria", "rationale", "governance_minutes"],
    qualityChecks: ["Weights total to 100 where applicable", "Approval and change rationale are captured"],
    minimumState: "Available",
    level: "required",
    description: "Why criteria weights are what they are, approved before scoring is locked.",
    unlocks: "Weight-set lock and defensible scoring.",
  }),
  req({
    requirementId: "EVID-SRC-EVAL-RISK-ASSESSMENT",
    stage: "evaluation",
    label: "Supplier risk assessment",
    evidenceClass: "risk_control",
    sourceLabel: "Third-party risk, security, privacy, and resilience assessments",
    sourceSystems: ["Archer", "ServiceNow GRC", "OneTrust", "SecurityScorecard", "BitSight", "RiskRecon"],
    acceptedFileTypes: ["xlsx", "csv", "pdf"],
    recordGrain: "one vendor, risk domain, control, finding, or exception per row",
    criticalFields: ["vendor_id", "risk_domain", "finding", "severity", "remediation", "due_date", "approval_required"],
    filenameTokens: ["risk", "security_assessment", "tprm", "privacy_assessment"],
    qualityChecks: ["Critical findings have remediation owner and due date", "Waivers remain explicit"],
    minimumState: "Available",
    level: "required",
    description: "Supplier risk facts that may change the evaluation decision or negotiation conditions.",
    unlocks: "Risk-adjusted scoring and executive trade-off memo.",
  }),
  req({
    requirementId: "EVID-SRC-EVAL-TCO-NORMALIZATION",
    stage: "evaluation",
    label: "TCO normalization model",
    evidenceClass: "supplier_offer",
    sourceLabel: "Finance model and supplier pricing normalization",
    sourceSystems: ["Excel pricing model", "Anaplan", "Adaptive Planning", "Apptio"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one vendor, scenario, year, cost component, or assumption per row",
    criticalFields: ["vendor_id", "scenario", "year", "cost_component", "amount", "assumption_ref", "retained_cost", "one_time_cost"],
    filenameTokens: ["tco", "normalization", "comparison", "financial_model"],
    qualityChecks: ["One-time and recurring costs are separated", "Assumptions are linked to source evidence"],
    minimumState: "Available",
    level: "required",
    description: "Normalized total-cost view across supplier offers, retained costs, transition, and risk adjustments.",
    unlocks: "Comparable economics and executive decision pack.",
  }),
  req({
    requirementId: "EVID-SRC-EVAL-STAKEHOLDER-FEEDBACK",
    stage: "evaluation",
    label: "Stakeholder feedback and demos",
    evidenceClass: "supplier_offer",
    sourceLabel: "Demo notes, workshop output, and business feedback",
    sourceSystems: ["Teams notes", "Miro", "Confluence", "SharePoint", "Survey tool"],
    acceptedFileTypes: ["docx", "pdf", "txt", "xlsx", "csv"],
    recordGrain: "one stakeholder role, vendor, demo, concern, or endorsement per row/section",
    criticalFields: ["vendor_id", "stakeholder_role", "feedback_theme", "sentiment", "evidence_note", "decision_impact"],
    filenameTokens: ["demo", "stakeholder", "feedback", "workshop"],
    qualityChecks: ["Feedback is tied to stakeholder role, not personal identity", "Decision impact is distinguishable from raw opinion"],
    minimumState: "Parsed",
    level: "recommended",
    description: "Business and technical feedback from demos, orals, and workshops.",
    unlocks: "Qualitative context, decision risks, and adoption-readiness narrative.",
  }),
];

// Stage 6 - Pricing
const PRICING: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-PRICE-VENDOR-PRICING",
    stage: "pricing",
    label: "Normalized supplier pricing",
    evidenceClass: "supplier_offer",
    sourceLabel: "Supplier pricing submissions and normalization workbook",
    sourceSystems: ["Ariba Sourcing", "Coupa Sourcing", "Excel pricing workbook", "Anaplan"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one vendor, price element, volume band, service line, or year per row",
    criticalFields: ["vendor_id", "service_line", "price_element", "unit", "volume_band", "year", "unit_price", "extended_price", "currency"],
    filenameTokens: ["vendor_pricing", "pricing", "price", "commercial", "rate"],
    qualityChecks: ["Detail recomputes to supplier headline total", "Currency, volume bands, and assumptions are visible"],
    minimumState: "Available",
    level: "required",
    description: "Supplier pricing normalized to a comparable commercial structure.",
    unlocks: "Should-cost view, TCO matrix, and BAFO negotiation levers.",
  }),
  req({
    requirementId: "EVID-SRC-PRICE-RATE-CARD",
    stage: "pricing",
    label: "Current and proposed rate cards",
    evidenceClass: "rate_card",
    sourceLabel: "Contract rate-card schedules, supplier submissions, and VMS rates",
    sourceSystems: ["CLM schedules", "Fieldglass", "Beeline", "Ariba Sourcing", "Excel rate card"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one role, level, location, rate period, or discount tier per row",
    criticalFields: ["vendor_id", "role_ref", "rate_type", "location", "level", "current_rate", "proposed_rate", "currency", "effective_date"],
    filenameTokens: ["rate_card", "rates", "role_rates", "labor_rates"],
    qualityChecks: ["Current and proposed rates are not mixed in one field", "Effective date and currency are explicit"],
    minimumState: "Available",
    level: "required",
    description: "Current and proposed rates used to detect rate variance and quantify negotiated improvement.",
    unlocks: "Rate-card variance, price-lever story, and contract schedule update.",
  }),
  req({
    requirementId: "EVID-SRC-PRICE-INVOICE-DETAIL",
    stage: "pricing",
    label: "Invoice, PO, and payment detail",
    evidenceClass: "invoice",
    sourceLabel: "ERP/AP, PO system, and payment history",
    sourceSystems: ["SAP S/4HANA AP", "Oracle Fusion AP", "Coupa P2P", "Ariba Buying", "PeopleSoft Financials"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one invoice line, PO line, payment, or vendor-period per row",
    criticalFields: ["vendor_id", "contract_id", "po_number", "invoice_number", "line_description", "quantity", "unit_price", "amount", "payment_date"],
    filenameTokens: ["invoice", "payment", "po_line", "ap_detail", "actual_spend"],
    qualityChecks: ["Invoices tie to PO or contract where available", "Duplicate invoice candidates are detectable"],
    minimumState: "Available",
    level: "recommended",
    description: "Actual payable detail for validating the baseline and finding off-contract or duplicate spend.",
    unlocks: "Recoverable leakage, avoided cost, and spend-to-contract reconciliation.",
  }),
  req({
    requirementId: "EVID-SRC-PRICE-ASSUMPTIONS",
    stage: "pricing",
    label: "Commercial assumptions and escalators",
    evidenceClass: "contract_term",
    sourceLabel: "Finance assumptions log and commercial term sheet",
    sourceSystems: ["Excel pricing model", "Anaplan", "Adaptive Planning", "CLM term sheet", "SharePoint"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "pdf"],
    recordGrain: "one assumption, escalator, index cap, FX rule, or scenario per row",
    criticalFields: ["assumption_id", "scenario", "term", "value", "unit", "owner_role", "approval_date", "source_ref"],
    filenameTokens: ["assumption", "basis", "escalator", "index_cap", "scenario"],
    qualityChecks: ["Assumptions are approved or explicitly pending", "Escalators and caps are represented separately"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Approved assumptions for pricing normalization, index caps, FX, volumes, and term length.",
    unlocks: "Pricing normalization and negotiation target setting.",
  }),
  req({
    requirementId: "EVID-SRC-PRICE-CLOUD-USAGE",
    stage: "pricing",
    label: "Cloud and SaaS consumption detail",
    evidenceClass: "cloud_consumption",
    sourceLabel: "Cloud billing, SaaS admin, and usage telemetry",
    sourceSystems: ["AWS Cost Explorer", "Azure Cost Management", "GCP Billing", "Snowflake", "Salesforce Admin", "Microsoft 365 Admin"],
    acceptedFileTypes: ["xlsx", "csv", "json"],
    recordGrain: "one account, subscription, SKU, user, workload, month, or consumption line per row",
    criticalFields: ["vendor_id", "product", "sku", "period", "account_or_subscription", "usage_quantity", "unit", "cost", "active_users"],
    filenameTokens: ["usage", "consumption", "seat", "sku", "cloud_bill", "saas_admin"],
    qualityChecks: ["Period and SKU are explicit", "Seat/usage and cost remain separate measures"],
    minimumState: "Parsed",
    level: "recommended",
    description: "Consumption detail for SaaS/cloud contracts where optimization depends on usage, seats, or SKU mix.",
    unlocks: "Shelfware, volume-tier, and consumption-based savings analysis.",
  }),
];

// Stage 7 - BAFO
const BAFO: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-BAFO-ISSUE-LOG",
    stage: "bafo",
    label: "Negotiation issue and trap log",
    evidenceClass: "contract_term",
    sourceLabel: "Pricing trap log, redline tracker, and negotiation worksheet",
    sourceSystems: ["Excel issue log", "Icertis", "DocuSign CLM", "SharePoint", "Coupa Sourcing"],
    acceptedFileTypes: ["xlsx", "csv", "docx"],
    recordGrain: "one issue, trap, clause, concession, or ask per row",
    criticalFields: ["issue_id", "vendor_id", "issue_type", "severity", "client_ask", "vendor_position", "owner_role", "status"],
    filenameTokens: ["trap", "issue_log", "bafo", "open_item", "negotiation"],
    qualityChecks: ["P0/P1 issues are tied to a BAFO ask", "Owner and status are explicit"],
    minimumState: "Available",
    level: "required",
    description: "Open commercial, legal, risk, and scope issues that must be converted into BAFO asks.",
    unlocks: "BAFO question pack and negotiation plan.",
  }),
  req({
    requirementId: "EVID-SRC-BAFO-OFFERS",
    stage: "bafo",
    label: "BAFO offers and concessions",
    evidenceClass: "supplier_offer",
    sourceLabel: "Final supplier offers and concession register",
    sourceSystems: ["Ariba Sourcing", "Coupa Sourcing", "Jaggaer", "Excel concession tracker"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one vendor, concession, price change, term change, or condition per row",
    criticalFields: ["vendor_id", "concession_id", "concession_type", "baseline_value", "bafo_value", "condition", "expiry_date", "accepted_flag"],
    filenameTokens: ["bafo_offer", "final_offer", "concession", "best_final"],
    qualityChecks: ["Concessions retain conditions and expiry", "Price and term concessions are not blended"],
    minimumState: "Available",
    level: "required",
    description: "Supplier BAFO responses, concessions, price changes, and conditions.",
    unlocks: "Final economics, negotiated improvement ledger, and decision trade-offs.",
  }),
  req({
    requirementId: "EVID-SRC-BAFO-BENCHMARK-EVIDENCE",
    stage: "bafo",
    label: "Benchmark-backed negotiation evidence",
    evidenceClass: "benchmark",
    sourceLabel: "Market benchmark, peer deal, and should-cost references",
    sourceSystems: ["ISG", "Gartner", "Forrester", "GEP", "Prior event archive", "Finance model"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "pptx"],
    recordGrain: "one benchmark point, should-cost range, peer deal, or market reference per row/section",
    criticalFields: ["category", "service_line", "benchmark_source", "low", "median", "high", "basis", "effective_date"],
    filenameTokens: ["benchmark", "should_cost", "market_rate", "peer_deal"],
    qualityChecks: ["Benchmark basis is visible", "Date and applicability caveat are preserved"],
    minimumState: "Parsed",
    level: "recommended",
    description: "External and internal evidence used to support pricing and term asks.",
    unlocks: "Negotiation rationale and executive confidence.",
  }),
  req({
    requirementId: "EVID-SRC-BAFO-RISK-ACCEPTANCE",
    stage: "bafo",
    label: "Risk acceptance and unresolved exceptions",
    evidenceClass: "risk_control",
    sourceLabel: "Risk waiver, Legal exception tracker, and security acceptance record",
    sourceSystems: ["Archer", "ServiceNow GRC", "OneTrust", "Icertis", "SharePoint"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one unresolved risk, exception, waiver, or acceptance per row",
    criticalFields: ["risk_id", "vendor_id", "exception", "severity", "accepted_by_role", "acceptance_date", "mitigation", "expiry_date"],
    filenameTokens: ["risk_acceptance", "waiver", "exception", "unresolved"],
    qualityChecks: ["Acceptance role and date are explicit", "Expiry or revisit date is captured where applicable"],
    minimumState: "Available",
    level: "required",
    description: "Risks or exceptions left open after BAFO, with the named role that accepted them.",
    unlocks: "Executive risk disclosure and selection guardrails.",
  }),
];

// Stage 8 - Executive Decision
const DECISION: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-DEC-FINALIST-PRICING",
    stage: "executive_decision",
    label: "Finalist post-BAFO pricing",
    evidenceClass: "supplier_offer",
    sourceLabel: "BAFO round log and normalized pricing model",
    sourceSystems: ["Excel pricing model", "Ariba Sourcing", "Coupa Sourcing", "Anaplan"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one finalist, scenario, year, price element, or concession per row",
    criticalFields: ["vendor_id", "scenario", "year", "total_value", "annual_value", "one_time_cost", "concession_ref", "confidence"],
    filenameTokens: ["finalist", "post_bafo", "final_pricing", "decision_pricing"],
    qualityChecks: ["Final pricing ties to BAFO offer", "Decision assumptions are versioned"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Final-round pricing, signed concessions, and normalized economics for the executive decision.",
    unlocks: "Decision brief economics and negotiated improvement evidence.",
  }),
  req({
    requirementId: "EVID-SRC-DEC-RISK-REGISTER",
    stage: "executive_decision",
    label: "Decision risk register",
    evidenceClass: "risk_control",
    sourceLabel: "Risk register and control attestations",
    sourceSystems: ["Archer", "ServiceNow GRC", "OneTrust", "SharePoint", "Excel risk register"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one decision risk, control gap, mitigation, or acceptance per row",
    criticalFields: ["risk_id", "vendor_id", "risk_domain", "severity", "mitigation", "owner_role", "decision_required", "acceptance_status"],
    filenameTokens: ["risk_register", "decision_risk", "attestation", "control"],
    qualityChecks: ["High risks have owner and mitigation", "Accepted risks have approver role"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Aggregated risks across financial, security, concentration, transition, and supplier execution domains.",
    unlocks: "Executive risk trade-off and approval conditions.",
  }),
  req({
    requirementId: "EVID-SRC-DEC-VALUE-LEDGER",
    stage: "executive_decision",
    label: "Value hypothesis ledger",
    evidenceClass: "finance_value_confirmation",
    sourceLabel: "Finance model, Tower claims, and value-line assumptions",
    sourceSystems: ["Anaplan", "Adaptive Planning", "Apptio", "Tower value claim view", "Excel value model"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one value line, scenario, owner, evidence class, or confidence status per row",
    criticalFields: ["value_line_id", "ledger_type", "amount", "currency", "basis", "owner_role", "evidence_status", "tower_claim_ref"],
    filenameTokens: ["value_ledger", "value_hypothesis", "benefit_case", "savings_target"],
    qualityChecks: ["Estimated, avoided, negotiated, and realized value remain separate", "Unknown value is not converted to zero"],
    minimumState: "Available",
    level: "required",
    description: "Value hypothesis split across recoverable leakage, avoided cost, negotiated improvement, and realized value.",
    unlocks: "Executive decision, Tower handoff, and post-award measurement plan.",
  }),
  req({
    requirementId: "EVID-SRC-DEC-STAKEHOLDER-ENDORSEMENT",
    stage: "executive_decision",
    label: "Stakeholder endorsement and dissent",
    evidenceClass: "approved_agreement",
    sourceLabel: "Decision meeting minutes and approval workflow",
    sourceSystems: ["ServiceNow SPM", "Teams notes", "SharePoint", "DocuSign approvals"],
    acceptedFileTypes: ["docx", "pdf", "txt", "xlsx"],
    recordGrain: "one role endorsement, concern, dissent, or condition per row/section",
    criticalFields: ["role_ref", "decision_position", "condition", "rationale", "approval_date", "follow_up_owner_role"],
    filenameTokens: ["endorsement", "dissent", "decision_minutes", "approval"],
    qualityChecks: ["Dissent is preserved, not overwritten by consensus language", "Conditions are actionable"],
    minimumState: "Loaded",
    level: "required",
    description: "Human decision record showing endorsements, dissent, and conditions before final selection.",
    unlocks: "Approval gate and audit trail.",
  }),
  req({
    requirementId: "EVID-SRC-DEC-IMPLEMENTATION-READINESS",
    stage: "executive_decision",
    label: "Implementation readiness assessment",
    evidenceClass: "risk_control",
    sourceLabel: "Transition, architecture, security, and operations readiness notes",
    sourceSystems: ["ServiceNow SPM", "Jira", "Confluence", "CMDB", "Security GRC"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "pdf"],
    recordGrain: "one readiness domain, dependency, constraint, or mitigation per row",
    criticalFields: ["readiness_domain", "status", "dependency", "owner_role", "due_date", "risk_level", "mitigation"],
    filenameTokens: ["readiness", "implementation", "dependency", "transition_ready"],
    qualityChecks: ["Critical dependencies have owners and due dates", "Readiness status is not inferred from vendor preference"],
    minimumState: "Parsed",
    level: "recommended",
    description: "Readiness evidence that determines whether the decision is executable, not just attractive.",
    unlocks: "Selection conditions and transition planning.",
  }),
];

// Stage 9 - Selection
const SELECTION: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-SEL-CONTRACT",
    stage: "selection",
    label: "Executed agreement and signature packet",
    evidenceClass: "approved_agreement",
    sourceLabel: "Legal repository and e-signature system",
    sourceSystems: ["DocuSign", "Adobe Sign", "Icertis", "DocuSign CLM", "Ironclad", "SharePoint"],
    acceptedFileTypes: ["pdf", "docx"],
    recordGrain: "one executed agreement, amendment, order form, or signature packet per document",
    criticalFields: ["contract_id", "vendor_id", "agreement_type", "effective_date", "end_date", "signature_date", "signatory_role", "annual_value"],
    filenameTokens: ["executed", "signature", "signed", "contract", "agreement"],
    qualityChecks: ["Signature status and effective date are visible", "Commercial values reconcile to final decision record"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Signed agreement and approval evidence that turns the sourcing decision into a legal commitment.",
    unlocks: "Selection memo lock, contract 360 update, and transition kickoff.",
  }),
  req({
    requirementId: "EVID-SRC-SEL-FINAL-SOW",
    stage: "selection",
    label: "Final SOW, order forms, and schedules",
    evidenceClass: "contract_term",
    sourceLabel: "CLM schedules and final commercial packet",
    sourceSystems: ["Icertis", "DocuSign CLM", "SharePoint", "Coupa Contracts"],
    acceptedFileTypes: ["pdf", "docx", "xlsx"],
    recordGrain: "one SOW, order form, schedule, rate card, or exhibit per document/row",
    criticalFields: ["sow_id", "contract_id", "schedule_name", "scope_summary", "start_date", "end_date", "value", "owner_role"],
    filenameTokens: ["final_sow", "order_form", "schedule", "exhibit"],
    qualityChecks: ["Final schedules match selected commercial terms", "Scope exclusions are preserved"],
    minimumState: "Available",
    level: "required",
    description: "Final work scope, order forms, and schedules that operations and finance will manage against.",
    unlocks: "Contract metadata, delivery obligations, and transition scope.",
  }),
  req({
    requirementId: "EVID-SRC-SEL-OBLIGATION-REGISTER",
    stage: "selection",
    label: "Obligation and deliverable register",
    evidenceClass: "contract_term",
    sourceLabel: "CLM obligation extraction and implementation tracker",
    sourceSystems: ["Icertis", "DocuSign CLM", "Ironclad", "ServiceNow SPM", "Excel tracker"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx"],
    recordGrain: "one obligation, deliverable, date, owner, or remedy per row",
    criticalFields: ["obligation_id", "contract_id", "obligation_type", "owner_role", "due_date", "frequency", "remedy", "source_section"],
    filenameTokens: ["obligation", "deliverable", "commitment", "remedy"],
    qualityChecks: ["Obligations retain owner and date/frequency", "Remedies are separate from obligations"],
    minimumState: "Parsed",
    level: "required",
    description: "Contract obligations, deliverables, dates, remedies, and owners for post-award management.",
    unlocks: "Transition checklist, contract management plan, and Tower proof gates.",
  }),
  req({
    requirementId: "EVID-SRC-SEL-FINANCE-SETUP",
    stage: "selection",
    label: "Finance and procurement setup",
    evidenceClass: "payment",
    sourceLabel: "Vendor master, PO setup, budget coding, and invoice instructions",
    sourceSystems: ["SAP S/4HANA", "Oracle Fusion", "Coupa P2P", "Ariba Buying", "Vendor master"],
    acceptedFileTypes: ["xlsx", "csv", "pdf"],
    recordGrain: "one vendor master, PO, cost center, tax, or payment setup record per row",
    criticalFields: ["vendor_id", "po_number", "cost_center", "gl_account", "payment_terms", "invoice_route", "effective_date", "owner_role"],
    filenameTokens: ["vendor_master", "po_setup", "finance_setup", "payment_terms"],
    qualityChecks: ["Payment terms match executed agreement", "Cost center and GL coding are visible"],
    minimumState: "Loaded",
    level: "recommended",
    description: "Finance and procurement setup needed to avoid post-award leakage and invoice mismatches.",
    unlocks: "Invoice controls and value realization tracking.",
  }),
];

// Stage 10 - Transition
const TRANSITION: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-TRAN-MILESTONES",
    stage: "transition",
    label: "Transition milestones and plan",
    evidenceClass: "scope",
    sourceLabel: "Project plan and transition tracker",
    sourceSystems: ["Jira", "ServiceNow SPM", "MS Project", "Smartsheet", "Planview"],
    acceptedFileTypes: ["xlsx", "csv", "mpp", "pdf", "docx"],
    recordGrain: "one milestone, dependency, owner, status, or go/no-go checkpoint per row",
    criticalFields: ["milestone_id", "milestone_name", "target_date", "owner_role", "dependency", "status", "go_no_go_decision"],
    filenameTokens: [
      "milestone",
      "transition_plan",
      "timeline",
      "cutover",
      "plan",
      "readiness",
      "go_live",
      "go-live",
      "checkpoint",
    ],
    qualityChecks: ["Critical path milestones have owners and dates", "Go/no-go decisions remain distinct from status updates"],
    minimumState: "Available",
    level: "required",
    description: "Transition plan and milestone checkpoints that govern mobilization and cutover.",
    unlocks: "Stage promotion, transition governance, and risk monitoring.",
  }),
  req({
    requirementId: "EVID-SRC-TRAN-KT-EVIDENCE",
    stage: "transition",
    label: "Knowledge transfer evidence",
    evidenceClass: "scope",
    sourceLabel: "KT session logs, runbooks, and sign-off records",
    sourceSystems: ["Confluence", "SharePoint", "Teams recordings index", "ServiceNow Knowledge", "Jira"],
    acceptedFileTypes: ["xlsx", "csv", "docx", "pdf", "txt"],
    recordGrain: "one KT session, topic, runbook, sign-off, or receiving team per row",
    criticalFields: ["kt_session_id", "topic", "source_team_role", "receiving_team_role", "date", "artifact_ref", "signoff_status"],
    filenameTokens: ["kt", "knowledge", "handover", "runbook", "training"],
    qualityChecks: ["Receiving-team signoff is captured", "Runbook or artifact references are visible"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Knowledge transfer, runbook, and sign-off evidence for receiving teams.",
    unlocks: "Transition close, support readiness, and retained-risk disclosure.",
  }),
  req({
    requirementId: "EVID-SRC-TRAN-ASSET-ACCESS",
    stage: "transition",
    label: "Access, assets, and CMDB handover",
    evidenceClass: "risk_control",
    sourceLabel: "IAM, CMDB, asset register, and access request trackers",
    sourceSystems: ["ServiceNow CMDB", "SailPoint", "Okta", "Azure AD", "Jira", "Asset inventory"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one access group, asset, app, CI, credential handoff, or account per row",
    criticalFields: ["asset_or_ci_id", "application_id", "access_group", "owner_role", "handover_status", "risk_level", "target_date"],
    filenameTokens: ["asset", "access", "cmdb_handover", "credential", "handover"],
    qualityChecks: ["No secrets or personal credentials", "Access ownership and status are explicit"],
    minimumState: "Available",
    level: "required",
    description: "Operational access, CMDB, and asset handover evidence needed to avoid transition failure.",
    unlocks: "Cutover readiness and control attestation.",
  }),
  req({
    requirementId: "EVID-SRC-TRAN-INCUMBENT-EXIT",
    stage: "transition",
    label: "Incumbent exit and cooperation plan",
    evidenceClass: "contract_term",
    sourceLabel: "Exit plan, termination rights, and cooperation obligations",
    sourceSystems: ["Icertis", "DocuSign CLM", "SharePoint", "ServiceNow SPM"],
    acceptedFileTypes: ["docx", "pdf", "xlsx"],
    recordGrain: "one exit obligation, support period, dependency, or termination condition per row/section",
    criticalFields: ["contract_id", "exit_obligation", "notice_date", "support_period", "owner_role", "risk", "mitigation"],
    filenameTokens: ["exit", "termination", "incumbent", "cooperation", "disentanglement"],
    qualityChecks: ["Exit rights are tied to contract sections", "Dependencies and support windows are visible"],
    minimumState: "Parsed",
    level: "recommended",
    description: "Incumbent cooperation, exit rights, and disentanglement obligations.",
    unlocks: "Transition risk mitigation and fallback plan.",
  }),
  req({
    requirementId: "EVID-SRC-TRAN-SERVICE-ACCEPTANCE",
    stage: "transition",
    label: "Service acceptance and go-live proof",
    evidenceClass: "approved_agreement",
    sourceLabel: "Acceptance checklist, go-live sign-off, and operational readiness review",
    sourceSystems: ["ServiceNow Change", "Jira", "SharePoint", "Confluence", "Teams notes"],
    acceptedFileTypes: ["xlsx", "csv", "pdf", "docx", "txt"],
    recordGrain: "one acceptance criterion, test, sign-off, defect, or readiness item per row",
    criticalFields: ["acceptance_id", "criterion", "test_result", "defect_count", "owner_role", "signoff_status", "go_live_date"],
    filenameTokens: ["acceptance", "go_live", "readiness", "orr", "cutover_signoff"],
    qualityChecks: ["Open defects are visible", "Signoff status is not inferred from plan status"],
    minimumState: "Available",
    level: "required",
    description: "Acceptance and go-live proof that transition outcomes have been reviewed.",
    unlocks: "Transition close and value measurement start.",
  }),
];

// Stage 11 - Value
const VALUE: SourceEvidenceRequirement[] = [
  req({
    requirementId: "EVID-SRC-VAL-FINANCE-CONFIRMATION",
    stage: "value",
    label: "Finance-confirmed realized value",
    evidenceClass: "finance_value_confirmation",
    sourceLabel: "Finance value ledger and actuals confirmation",
    sourceSystems: ["Anaplan", "Adaptive Planning", "SAP/Oracle actuals", "Apptio", "Tower value ledger"],
    acceptedFileTypes: ["xlsx", "csv", "pdf"],
    recordGrain: "one value line, period, finance confirmation, or actual result per row",
    criticalFields: ["value_line_id", "period", "realized_amount", "currency", "finance_owner_role", "confirmation_date", "basis", "tower_claim_ref"],
    filenameTokens: ["finance_confirmation", "realized_value", "actual_value", "value_confirmation"],
    qualityChecks: ["Finance confirmation date and owner role are present", "Realized value is not inferred from estimate"],
    minimumState: "Usable Evidence",
    level: "required",
    description: "Finance-confirmed value only. Estimates, usage, and commitments are not realized value.",
    unlocks: "Realized value claim and Tower finance gate.",
  }),
  req({
    requirementId: "EVID-SRC-VAL-INVOICE-TRACKING",
    stage: "value",
    label: "Invoice realization tracking",
    evidenceClass: "invoice",
    sourceLabel: "AP actuals, PO burn, and contract invoice controls",
    sourceSystems: ["SAP S/4HANA AP", "Oracle Fusion AP", "Coupa P2P", "Ariba Buying", "Power BI spend mart"],
    acceptedFileTypes: ["xlsx", "csv"],
    recordGrain: "one invoice line, PO line, credit memo, or vendor-period actual per row",
    criticalFields: ["contract_id", "vendor_id", "invoice_number", "period", "amount", "credit_memo", "po_number", "expected_rate", "actual_rate"],
    filenameTokens: ["invoice_tracking", "ap_actuals", "credit_memo", "po_burn"],
    qualityChecks: ["Actuals tie to contract or PO", "Credits and charges remain separate"],
    minimumState: "Available",
    level: "required",
    description: "Post-award spend actuals that prove negotiated terms or avoided costs show up in finance systems.",
    unlocks: "Avoided cost and recoverable leakage measurement.",
  }),
  req({
    requirementId: "EVID-SRC-VAL-SLA-CREDITS",
    stage: "value",
    label: "SLA credits and service performance",
    evidenceClass: "service_credit",
    sourceLabel: "Service performance history and credit claim log",
    sourceSystems: ["ServiceNow ITSM", "Splunk", "Datadog", "Excel credit register", "CLM SLA schedule"],
    acceptedFileTypes: ["xlsx", "csv", "pdf"],
    recordGrain: "one SLA metric, service month, credit earned, claim, or receipt per row",
    criticalFields: ["contract_id", "period", "sla_name", "target", "actual", "credit_earned", "credit_claimed", "credit_received", "claim_status"],
    filenameTokens: ["sla_credit", "service_credit", "credit_claim", "performance_history"],
    qualityChecks: ["Earned, claimed, and received values are not collapsed", "Credit status and period are explicit"],
    minimumState: "Available",
    level: "recommended",
    description: "SLA and service-credit tracking for recoverable leakage and supplier accountability.",
    unlocks: "Recoverable leakage ledger and post-award contract management.",
  }),
  req({
    requirementId: "EVID-SRC-VAL-USAGE-OUTCOMES",
    stage: "value",
    label: "Usage and operational outcome metrics",
    evidenceClass: "usage",
    sourceLabel: "Operational telemetry, adoption analytics, and outcome dashboards",
    sourceSystems: ["ServiceNow", "Jira", "GitHub", "Azure DevOps", "Microsoft 365 Admin", "Salesforce Admin", "Power BI"],
    acceptedFileTypes: ["xlsx", "csv", "json"],
    recordGrain: "one metric, subject, period, product, team, or outcome observation per row",
    criticalFields: ["metric_id", "subject_ref", "period", "usage_quantity", "outcome_metric", "baseline_value", "current_value", "source_system"],
    filenameTokens: ["usage_outcome", "telemetry", "adoption", "operational_metric", "dora"],
    qualityChecks: ["Baseline and current value are distinguishable", "Usage is not treated as value without outcome confirmation"],
    minimumState: "Available",
    level: "recommended",
    description: "Usage and operational outcomes for adoption, productivity, or service improvement claims.",
    unlocks: "Tower observation support and outcome proof gap closure.",
  }),
  req({
    requirementId: "EVID-SRC-VAL-OWNER-ATTESTATION",
    stage: "value",
    label: "Benefit owner attestation",
    evidenceClass: "approved_agreement",
    sourceLabel: "Business owner sign-off and value governance record",
    sourceSystems: ["ServiceNow SPM", "Anaplan workflow", "Teams notes", "SharePoint", "DocuSign approvals"],
    acceptedFileTypes: ["pdf", "docx", "txt", "xlsx"],
    recordGrain: "one owner attestation, caveat, rejection, or follow-up action per row/section",
    criticalFields: ["value_line_id", "owner_role", "attestation_status", "attestation_date", "basis", "caveat", "follow_up_action"],
    filenameTokens: ["attestation", "benefit_owner", "signoff", "value_governance"],
    qualityChecks: ["Attestation is role-based and dated", "Caveats and rejections remain visible"],
    minimumState: "Loaded",
    level: "required",
    description: "Business or finance owner attestation for value lines, including caveats and unresolved proof gaps.",
    unlocks: "Value governance closeout and next evidence request.",
  }),
];

export const SOURCE_EVIDENCE_REQUIREMENTS: readonly SourceEvidenceRequirement[] = [
  ...STRATEGY,
  ...SCOPE,
  ...RFP,
  ...RESPONSES,
  ...EVALUATE,
  ...PRICING,
  ...BAFO,
  ...DECISION,
  ...SELECTION,
  ...TRANSITION,
  ...VALUE,
] as const;

export function evidenceForStage(stage: SourceStageKey): SourceEvidenceRequirement[] {
  return SOURCE_EVIDENCE_REQUIREMENTS.filter((e) => e.stage === stage);
}

export function requiredEvidenceForStage(stage: SourceStageKey): SourceEvidenceRequirement[] {
  return SOURCE_EVIDENCE_REQUIREMENTS.filter(
    (e) => e.stage === stage && e.level === "required",
  );
}

export function evidenceById(id: string): SourceEvidenceRequirement | undefined {
  return SOURCE_EVIDENCE_REQUIREMENTS.find((e) => e.requirementId === id);
}
