// BoardArtifactsPanel — board-grade artifact decks for a Move.
//
// Board-grade artifact decks (costed business case, discover brief, solution
// architecture) are deliverables generated by the Moves Expert Kernel. They
// live at raw `/api/v1/moves/*` routes; this panel is the in-product surface
// that links a user — on the Move they are actually working — straight to the
// decks anchored to that Move.
//
// Presentational and generic by construction. It asks the board-artifacts
// registry which decks a Move has and renders them. It knows NOTHING about any
// specific tenant or Move — the registry data carries all of that.
//
//   • Artifacts present → a "Board artifacts" panel listing each deck with a
//     primary View link and, when one exists, a Download PowerPoint link.
//   • No artifacts → renders nothing. A Move without anchored decks shows no
//     empty-state clutter.
//
// Styling matches the Documents tab (PhaseDocumentsPanel): #1B2B5C navy,
// #e5e5e5 borders, JetBrains Mono labels, Fraunces section title. No new
// visual language.

import {
  boardArtifactsForMove,
  type BoardArtifact,
} from "@/lib/programs/board-artifacts/board-artifacts-registry";
import type { StrategicMove } from "@/lib/programs/types.ui";

interface Props {
  move: StrategicMove;
}

function linkStyle(variant: "primary" | "ghost"): React.CSSProperties {
  const base: React.CSSProperties = {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    padding: "4px 10px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 600,
    textDecoration: "none",
    whiteSpace: "nowrap",
  };
  return variant === "primary"
    ? {
        ...base,
        backgroundColor: "#1B2B5C",
        border: "1px solid #1B2B5C",
        color: "#FFFFFF",
      }
    : {
        ...base,
        backgroundColor: "#ffffff",
        border: "1px solid #e5e5e5",
        color: "#1A1A18",
      };
}

function presentationBlurb(blurb: string): string {
  return blurb
    .replace(/\bboard-grade\b/gi, "executive-ready")
    .replace(/\bBoard-grade\b/g, "Executive-ready");
}

function ArtifactRow({ artifact }: { artifact: BoardArtifact }) {
  return (
    <div
      data-testid="board-artifact-row"
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "10px 12px",
        background: "#FFFFFF",
        border: "1px solid #e5e5e5",
        borderLeft: "3px solid #1B2B5C",
        borderRadius: 6,
        flexWrap: "wrap",
      }}
    >
      {/* Left: label + phase + blurb */}
      <div style={{ flex: "1 1 220px", minWidth: 0 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 5,
            marginBottom: 2,
            flexWrap: "wrap",
          }}
        >
          <span style={{ fontSize: 10, color: "#6B7280" }}>
            {artifact.phase}
          </span>
        </div>
        <div
          style={{
            fontSize: 13,
            fontWeight: 600,
            color: "#1A1A18",
            lineHeight: 1.3,
          }}
        >
          {artifact.label}
        </div>
        <div style={{ fontSize: 10, color: "#9AA3B2", marginTop: 1 }}>
          {presentationBlurb(artifact.blurb)}
        </div>
      </div>

      {/* Right: actions */}
      <div
        style={{
          display: "flex",
          gap: 6,
          alignItems: "center",
          flexShrink: 0,
          flexWrap: "wrap",
        }}
      >
        <a
          href={artifact.htmlHref}
          target="_blank"
          rel="noopener noreferrer"
          style={linkStyle("primary")}
        >
          View →
        </a>
        {artifact.pptxHref && (
          <a href={artifact.pptxHref} style={linkStyle("ghost")}>
            ↓ PowerPoint
          </a>
        )}
      </div>
    </div>
  );
}

/**
 * Renders the board-grade artifact decks for a Move, or nothing when the Move
 * has no anchored decks.
 */
export function BoardArtifactsPanel({ move }: Props) {
  const artifacts = boardArtifactsForMove(move);
  if (artifacts.length === 0) return null;

  return (
    <div data-testid="board-artifacts-panel" style={{ marginBottom: 24 }}>
      {/* Section header — mirrors the Documents-tab phase headers */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          paddingBottom: 8,
          marginBottom: 8,
          borderBottom: "2px solid #1B2B5C",
        }}
      >
        <span
          style={{
            fontFamily: "Fraunces, Georgia, serif",
            fontSize: 15,
            fontWeight: 650,
            color: "#1A1A18",
          }}
        >
          Executive artifacts
        </span>
        <span style={{ fontSize: 10, color: "#9AA3B2" }}>
          {artifacts.length} {artifacts.length === 1 ? "deck" : "decks"}
        </span>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {artifacts.map((artifact) => (
          <ArtifactRow key={artifact.id} artifact={artifact} />
        ))}
      </div>
    </div>
  );
}
