import "server-only";

import {
  getLatestGeneratedArtifact,
  type GeneratedArtifactRecord,
} from "@/lib/artifacts/repository";
import { runOrchestratedMoveDeliverable } from "@/lib/programs/deliverables/orchestrated/run-orchestrated-move-deliverable";
import type { RunOrchestratedMoveDeliverableResult } from "@/lib/programs/deliverables/orchestrated/run-orchestrated-move-deliverable";
import { loadMoveBusinessCaseInput } from "@/lib/programs/board-artifacts/load-move-business-case-input";
import { persistBoardGradeMoveArtifact } from "@/lib/programs/board-artifacts/board-grade-persistence";

const DISCOVERY_PLAN_ARTIFACT_ID = "discovery_plan";
const DISCOVERY_PLAN_TITLE = "Discovery Plan";

export type DiscoveryPlanAutoGenerationStatus =
  | {
      status: "skipped";
      reason: string;
    }
  | {
      status: "already_exists";
      artifactId: string;
      sourceArtifactRef: string;
    }
  | {
      status: "blocked";
      reason: string;
      evidenceCount: number;
      citedInputCount: number;
    }
  | {
      status: "generated";
      artifactId: string;
      sourceArtifactRef: string;
      evidenceCount: number;
      citedInputCount: number;
    }
  | {
      status: "failed";
      reason: string;
    };

interface AutoGenerateDiscoveryPlanArgs {
  tenantKey: string;
  moveId: string | null;
  renderedBy: string;
  generatedOn?: string;
}

interface AutoGenerateDiscoveryPlanDeps {
  loadMoveInput?: typeof loadMoveBusinessCaseInput;
  run?: typeof runOrchestratedMoveDeliverable;
  persist?: typeof persistBoardGradeMoveArtifact;
  latest?: typeof getLatestGeneratedArtifact;
}

function qualityScore(
  quality: RunOrchestratedMoveDeliverableResult["quality"],
): number | null {
  if (!quality) return null;
  const blockerPenalty = quality.blockers.length * 20;
  const warningPenalty = quality.warnings.length * 5;
  return Math.max(0, Math.min(100, 100 - blockerPenalty - warningPenalty));
}

function egressAudit(
  passTrace: RunOrchestratedMoveDeliverableResult["passTrace"],
): string | null {
  const ids = (passTrace ?? [])
    .map((trace) => trace.responseId)
    .filter((id): id is string => typeof id === "string" && id.length > 0);
  return ids.length > 0 ? ids.join(",") : null;
}

export function discoveryPlanSourceArtifactRef(moveId: string): string {
  return `move:${moveId}:${DISCOVERY_PLAN_ARTIFACT_ID}`;
}

export async function autoGenerateDiscoveryPlanOnCharterApproval(
  args: AutoGenerateDiscoveryPlanArgs,
  deps: AutoGenerateDiscoveryPlanDeps = {},
): Promise<DiscoveryPlanAutoGenerationStatus> {
  const moveId = args.moveId?.trim() ?? "";
  if (!moveId) return { status: "skipped", reason: "move id unavailable" };

  const tenantKey = args.tenantKey.trim();
  if (!tenantKey) {
    return { status: "skipped", reason: "tenant key unavailable" };
  }

  const sourceArtifactRef = discoveryPlanSourceArtifactRef(moveId);
  const latest = deps.latest ?? getLatestGeneratedArtifact;
  const existing = await latest({
    clientId: tenantKey,
    artifactType: "move_board_pack",
    sourceArtifactRef,
    outputFormat: "html",
  }).catch((error) => {
    console.warn("[discovery-plan-auto] existing lookup failed", {
      moveId,
      message: error instanceof Error ? error.message : String(error),
    });
    return null as GeneratedArtifactRecord | null;
  });
  if (existing) {
    return {
      status: "already_exists",
      artifactId: existing.id,
      sourceArtifactRef,
    };
  }

  const loadMoveInput = deps.loadMoveInput ?? loadMoveBusinessCaseInput;
  const moveInput = await loadMoveInput(moveId).catch((error) => {
    console.warn("[discovery-plan-auto] move input load failed", {
      moveId,
      message: error instanceof Error ? error.message : String(error),
    });
    return null;
  });
  if (!moveInput) {
    return { status: "skipped", reason: "move input unavailable" };
  }

  const run = deps.run ?? runOrchestratedMoveDeliverable;
  const generatedOn = args.generatedOn ?? new Date().toISOString();
  const result = await run({
    moveInput,
    moveId,
    tenantId: tenantKey,
    userId: args.renderedBy,
    generatedOn,
    deliverableType: DISCOVERY_PLAN_ARTIFACT_ID,
    phaseOrStage: "P2_discovery",
    artifactStandard: "moves.board_grade.discovery_plan",
    decisionContext:
      "Charter has been approved. Create the P2 discovery plan: evidence request list, interview guide, readiness gaps, and client-to-complete checklist before diagnosis proceeds.",
    audience: ["cio", "cto", "program_leadership", "steering_committee"],
    minEvidence: 1,
  });

  if (!result.ok || !result.html) {
    return {
      status: "blocked",
      reason: result.blockedReason ?? "orchestrator produced no document",
      evidenceCount: result.evidenceCount,
      citedInputCount: result.citedInputIds.length,
    };
  }

  const persist = deps.persist ?? persistBoardGradeMoveArtifact;
  const record = await persist({
    clientId: tenantKey,
    moveId,
    artifactId: DISCOVERY_PLAN_ARTIFACT_ID,
    title: DISCOVERY_PLAN_TITLE,
    html: result.html,
    renderedBy: args.renderedBy,
    routePath: "/api/programs/phase-gate",
    generatedOn,
    citedInputIds: result.citedInputIds,
    qualityScore: qualityScore(result.quality),
    generationEgressAudit: egressAudit(result.passTrace),
  }).catch((error) => {
    console.error("[discovery-plan-auto] persistence failed", {
      moveId,
      message: error instanceof Error ? error.message : String(error),
    });
    return null;
  });

  if (!record) {
    return {
      status: "failed",
      reason: "generated artifact persistence failed",
    };
  }

  return {
    status: "generated",
    artifactId: record.id,
    sourceArtifactRef,
    evidenceCount: result.evidenceCount,
    citedInputCount: result.citedInputIds.length,
  };
}
