import type { FindingsCycleBundle } from './schema';

export const SAMPLE_CYCLES: FindingsCycleBundle[] = [
  {
    cycle_id: 'cycle-2026-04-23-1',
    turn_events: [
      {
        cycle_id: 'cycle-2026-04-23-1',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T09:00:00.000Z',
        url: '/tenant/apexretail/programs',
        action: 'Click + New program from Programs index',
        expected: 'Phase 0 intake opens immediately inside the scoped Apex tenant.',
        actual: 'Route errors and returns to the list without opening intake.',
        mismatch_severity: 'high',
        category: 'A',
        notes: 'Creation path breaks before intake starts.',
      },
      {
        cycle_id: 'cycle-2026-04-23-1',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T09:07:00.000Z',
        url: '/tenant/apexretail/programs/store-associate-productivity/phase/2',
        action: 'Advance from Phase 1 to Phase 2',
        expected: 'Phase summary persists and the next phase rail becomes active.',
        actual: 'The screen returns to Phase 1 state after a refresh.',
        mismatch_severity: 'medium',
        category: 'B',
        notes: 'Progression loses state between refreshes.',
      },
      {
        cycle_id: 'cycle-2026-04-23-1',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T09:12:00.000Z',
        url: '/tenant/apexretail/programs/store-associate-productivity',
        action: 'Ask Nexus for a sponsor-ready recommendation',
        expected: 'Context-aware guidance tied to the active program and phase.',
        actual: 'Nexus repeats a generic prompt and does not cite program context.',
        mismatch_severity: 'medium',
        category: 'D',
        notes: 'Response feels template-based, not phase-aware.',
      },
      {
        cycle_id: 'cycle-2026-04-23-1',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T09:18:00.000Z',
        url: '/tenant/apexretail/tower',
        action: 'Verify active tenant in Tower',
        expected: 'Apex-only pressures and spend views remain scoped after navigation.',
        actual: 'Apex-only pressures and spend views remain scoped after navigation.',
        mismatch_severity: 'none',
        category: 'E',
        notes: 'Baseline state check passed in cycle 1.',
      },
    ],
    session_assessment: {
      cycle_id: 'cycle-2026-04-23-1',
      persona: 'Marcus T · Apex CFO',
      session_start: '2026-04-23T09:00:00.000Z',
      session_end: '2026-04-23T09:25:00.000Z',
      narrative:
        'The core surfaces load, but the creation path and state persistence still create visible trust debt for a finance-oriented operator.',
      criteria_results: [
        {
          criterion_key: 'creation_flow',
          label: 'Creation flow opens cleanly',
          status: 'fail',
          category: 'A',
          notes: 'New program CTA does not open an intake surface.',
        },
        {
          criterion_key: 'phase_progression',
          label: 'Phase progression persists',
          status: 'fail',
          category: 'B',
          notes: 'Phase state resets after refresh.',
        },
        {
          criterion_key: 'nexus_quality',
          label: 'Nexus answers with program context',
          status: 'watch',
          category: 'D',
          notes: 'Answers are coherent but not context-rich enough yet.',
        },
      ],
      overall_recommendation: 'hold',
      top_blockers: [
        'Creation flow drops the user back to the list.',
        'Phase progression does not persist on refresh.',
      ],
    },
  },
  {
    cycle_id: 'cycle-2026-04-23-2',
    turn_events: [
      {
        cycle_id: 'cycle-2026-04-23-2',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T14:00:00.000Z',
        url: '/tenant/apexretail/programs',
        action: 'Click + New program from Programs index',
        expected: 'Phase 0 intake opens immediately inside the scoped Apex tenant.',
        actual: 'Phase 0 intake opens immediately inside the scoped Apex tenant.',
        mismatch_severity: 'none',
        category: 'A',
        notes: 'Creation flow fixed in cycle 2.',
      },
      {
        cycle_id: 'cycle-2026-04-23-2',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T14:07:00.000Z',
        url: '/tenant/apexretail/programs/store-associate-productivity/phase/2',
        action: 'Advance from Phase 1 to Phase 2',
        expected: 'Phase summary persists and the next phase rail becomes active.',
        actual: 'The screen returns to Phase 1 state after a refresh.',
        mismatch_severity: 'medium',
        category: 'B',
        notes: 'Persistence defect still open.',
      },
      {
        cycle_id: 'cycle-2026-04-23-2',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T14:12:00.000Z',
        url: '/tenant/apexretail/programs/store-associate-productivity',
        action: 'Ask Nexus for a sponsor-ready recommendation',
        expected: 'Context-aware guidance tied to the active program and phase.',
        actual: 'Nexus cites the wrong tenant and repeats prior language.',
        mismatch_severity: 'high',
        category: 'D',
        notes: 'Response regressed from generic to actively wrong.',
      },
      {
        cycle_id: 'cycle-2026-04-23-2',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T14:18:00.000Z',
        url: '/tenant/apexretail/tower',
        action: 'Verify active tenant in Tower',
        expected: 'Apex-only pressures and spend views remain scoped after navigation.',
        actual: 'Meridian pressure card appears after tenant switching.',
        mismatch_severity: 'high',
        category: 'E',
        notes: 'Tenant state leak introduced during cross-surface navigation.',
      },
      {
        cycle_id: 'cycle-2026-04-23-2',
        persona: 'Marcus T · Apex CFO',
        timestamp: '2026-04-23T14:22:00.000Z',
        url: '/tenant/apexretail/intelligence',
        action: 'Open the pattern grid and drill into benchmarks',
        expected: 'Every section card opens populated benchmark content.',
        actual: 'Benchmark panel opens with empty copy and no linked evidence.',
        mismatch_severity: 'high',
        category: 'C',
        notes: 'Content exists structurally but does not support the navigation.',
      },
    ],
    session_assessment: {
      cycle_id: 'cycle-2026-04-23-2',
      persona: 'Marcus T · Apex CFO',
      session_start: '2026-04-23T14:00:00.000Z',
      session_end: '2026-04-23T14:30:00.000Z',
      narrative:
        'The creation path is fixed, but the session still cannot be recommended because state integrity and content depth regressions remain visible.',
      criteria_results: [
        {
          criterion_key: 'creation_flow',
          label: 'Creation flow opens cleanly',
          status: 'pass',
          category: 'A',
          notes: 'Creation path now opens correctly.',
        },
        {
          criterion_key: 'phase_progression',
          label: 'Phase progression persists',
          status: 'fail',
          category: 'B',
          notes: 'Phase refresh issue still unresolved.',
        },
        {
          criterion_key: 'nexus_quality',
          label: 'Nexus answers with program context',
          status: 'fail',
          category: 'D',
          notes: 'Answers now cite the wrong tenant.',
        },
        {
          criterion_key: 'state_isolation',
          label: 'Tenant state remains isolated',
          status: 'fail',
          category: 'E',
          notes: 'Meridian pressure leaked into the Apex Tower view.',
        },
      ],
      overall_recommendation: 'hold',
      top_blockers: [
        'Cross-tenant state leak in Tower view.',
        'Benchmark drilldown opens without supporting content.',
      ],
    },
  },
];
