import { NextRequest, NextResponse } from "next/server";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";
import {
  checkTenantAccessByKey,
  tenantKeyForProgramCode,
} from "@/lib/auth/tenant-access";
import { requireTenancy } from "@/lib/auth/tenancy";
import { getLatestSponsorCommitment } from "@/lib/workflow/sponsorCommitmentLedger";
import {
  getProgramTensionRecords,
  getStakeholderSuccessRecords,
} from "@/lib/workflow/stakeholderSuccessLedger";
import { dataReadinessGateMet } from "@/lib/workflow/dataReadinessLedger";
import { azureRead } from "@/lib/data-plane/azureRead";
import { getSeedPlan } from "@/lib/deliverables/seed-route-resolver";
import { writeProgramAuditLog } from "@/lib/programs/audit-log";
import { selectProgramsWriteAdapter } from "@/lib/data-plane/write-adapters/programsWriteAdapter";
import { getAzureWriteFluentClient } from "@/lib/data-plane/postgresCompat";
import { loadUserProgramAccessPolicy } from "@/lib/auth/program-access-policy";
import {
  isGateApprovalStrictMode,
  isStrictModeApprovalRole,
} from "@/lib/auth/gate-approval-strict-mode";
import {
  buildMovesPhaseDecisionAuditRefs,
  buildMovesPhaseDecisionEvidencePacket,
  coerceDecisionSupportList,
  normalizeMovesHumanRationale,
  validateMovesHumanRationale,
  type MovesPhaseDecisionInput,
} from "@/lib/programs/moves-ai-liability";
import {
  autoGenerateDiscoveryPlanOnCharterApproval,
  type DiscoveryPlanAutoGenerationStatus,
} from "@/lib/programs/discovery/auto-generate-discovery-plan";
import { loadDiscoveryEvidenceReadiness } from "@/lib/programs/discovery/evidence-readiness";
import type { AiDecisionEvidencePacket } from "@/lib/ai-liability/human-decision-controls";

// Priority 2 item 2 · phase-gate advancement that moves a program forward.
//
// POST /api/programs/phase-gate
// body: { programCode: string, fromPhase: number, toPhase: number, gateCriterion?: string }
//
// Persists to `.approvals/phase-gates.json` · separate ledger from
// approvals to keep event kinds cleanly split. Records approver identity +
// timestamp so the assigned-to-me queue + notifications layers can read it.

interface PhaseGateEntry {
  id: string;
  programCode: string;
  fromPhase: number;
  toPhase: number;
  gateCriterion: string;
  humanRationale: string;
  aiDecisionEvidencePacket: AiDecisionEvidencePacket;
  advancedById: string;
  advancedByEmail: string | null;
  advancedByName: string | null;
  advancedByRole: string | null;
  timestamp: string;
}

interface PhaseGateLedger {
  schemaVersion: "1.0";
  entries: PhaseGateEntry[];
}

type PhaseGateEngagementRow = {
  id: string;
  current_phase: number | null;
  gates_passed: unknown[] | null;
};

type PhaseGateRequestBody = Partial<PhaseGateEntry> & {
  rationale?: unknown;
  humanRationale?: unknown;
  evidenceIds?: unknown;
  missingInputs?: unknown;
  assumptions?: unknown;
  alternativesConsidered?: unknown;
};

const LEDGER_DIR = join(process.cwd(), ".approvals");
const LEDGER_PATH = join(LEDGER_DIR, "phase-gates.json");

function readLedger(): PhaseGateLedger {
  if (!existsSync(LEDGER_PATH)) return { schemaVersion: "1.0", entries: [] };
  try {
    return JSON.parse(readFileSync(LEDGER_PATH, "utf8")) as PhaseGateLedger;
  } catch {
    return { schemaVersion: "1.0", entries: [] };
  }
}

function writeLedger(ledger: PhaseGateLedger): void {
  mkdirSync(LEDGER_DIR, { recursive: true });
  writeFileSync(LEDGER_PATH, `${JSON.stringify(ledger, null, 2)}\n`);
}

async function resolvePhaseGateEngagement(
  programCode: string,
): Promise<PhaseGateEngagementRow | null> {
  const plan = getSeedPlan();
  const seedProgram = plan.programs.find(
    (p) => p.code.trim().toLowerCase() === programCode.trim().toLowerCase(),
  );
  const graphNodeId = seedProgram?.graphNodeId ?? null;
  if (!graphNodeId) {
    console.warn("[phase-gate] no graphNodeId resolved for programCode", {
      programCode,
    });
    return null;
  }
  const engRow = await azureRead.maybeSingle<PhaseGateEngagementRow>({
    table: "engagements",
    columns: ["id", "current_phase", "gates_passed"],
    where: { graph_node_id: graphNodeId },
  });
  if (!engRow) {
    console.warn("[phase-gate] no engagement row found for graph_node_id", {
      programCode,
      graphNodeId,
    });
  }
  return engRow;
}

export async function POST(request: NextRequest) {
  const session = await auth();
  if (!session.userId) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  let body: PhaseGateRequestBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }

  const programCode =
    typeof body.programCode === "string" ? body.programCode.trim() : "";
  const fromPhase = typeof body.fromPhase === "number" ? body.fromPhase : null;
  const toPhase = typeof body.toPhase === "number" ? body.toPhase : null;
  const gateCriterion =
    typeof body.gateCriterion === "string"
      ? body.gateCriterion.trim()
      : "Phase gate advance";
  if (!programCode || fromPhase === null || toPhase === null) {
    return NextResponse.json(
      { error: "programCode, fromPhase, toPhase required" },
      { status: 400 },
    );
  }
  if (toPhase !== fromPhase + 1) {
    return NextResponse.json(
      { error: "toPhase must be fromPhase + 1" },
      { status: 400 },
    );
  }
  const humanRationale = normalizeMovesHumanRationale(
    body.humanRationale ?? body.rationale,
  );
  const rationaleError = validateMovesHumanRationale(humanRationale);
  if (rationaleError) {
    return NextResponse.json(
      { error: "human_rationale_required", detail: rationaleError },
      { status: 400 },
    );
  }

  // Tenant gate · same shape as /api/programs/approve. A phase-gate
  // advance is a stateful write on a tenant-owned program; cross-tenant
  // requests must fail here too.
  const ownerKey = tenantKeyForProgramCode(programCode);
  if (!ownerKey) {
    return NextResponse.json({ error: "unknown programCode" }, { status: 404 });
  }
  const access = await checkTenantAccessByKey(ownerKey);
  if (!access.ok) {
    const status = access.reason === "unauthenticated" ? 401 : 403;
    return NextResponse.json({ error: access.reason }, { status });
  }

  // SECURITY (audit 2026-05-22, P0-2a): a phase-gate advance is a
  // gate-feeding write. The route previously checked tenant membership
  // but never a role — any tenant member could advance any program
  // across a phase gate. Require the gate-approval capability from the
  // server-computed UserProgramAccessPolicy.
  let advancerRole: string | null = null;
  let policyCtx: Awaited<ReturnType<typeof requireTenancy>> | null = null;
  try {
    policyCtx = await requireTenancy();
    const accessPolicy = await loadUserProgramAccessPolicy(policyCtx);
    advancerRole = policyCtx.role ?? null;
    if (!accessPolicy.canApproveGates) {
      return NextResponse.json(
        {
          error: "forbidden",
          detail:
            "Advancing a program across a phase gate requires gate-approval permission. Ask a sponsor or client admin to advance, or to grant can_approve_gates.",
        },
        { status: 403 },
      );
    }
    // P1-4 · GATE_APPROVAL_STRICT_MODE — when on, the gate advance
    // additionally requires an admin / maestro role.
    if (isGateApprovalStrictMode() && !isStrictModeApprovalRole(advancerRole)) {
      return NextResponse.json(
        {
          error: "forbidden",
          detail:
            "GATE_APPROVAL_STRICT_MODE is enabled — phase-gate advance requires an admin or maestro role.",
        },
        { status: 403 },
      );
    }
  } catch (err) {
    // requireTenancy throwing here means the session/client could not be
    // resolved even though the tenant-key check passed — fail closed.
    console.error("[phase-gate] access-policy resolution failed", err);
    return NextResponse.json(
      {
        error: "forbidden",
        detail: "Could not verify gate-approval permission.",
      },
      { status: 403 },
    );
  }

  // FM-03 · Phase 1 → 2 gate requires a sponsor commitment record. Other
  // phase transitions have their own preconditions (Phase 2→3 needs the
  // tension-capture fields per FM-04, etc.) — those land in follow-up
  // items. For now, enforce only the FM-03 precondition.
  if (fromPhase === 1 && toPhase === 2) {
    const commitment = getLatestSponsorCommitment(programCode);
    if (!commitment) {
      return NextResponse.json(
        {
          error: "precondition_failed",
          precondition: "sponsor_commitment",
          message:
            "Phase 1 → Phase 2 requires a sponsor commitment record. Submit the commitment form on D01 Charter first.",
        },
        { status: 412 },
      );
    }
    // FM-04 · require at least one success record (D02) and one tension
    // record (D04). Full per-stakeholder enforcement needs Codex's
    // stakeholder resolver; this floor catches "empty D02/D04" gates.
    const successRecords = getStakeholderSuccessRecords(programCode);
    if (successRecords.length === 0) {
      return NextResponse.json(
        {
          error: "precondition_failed",
          precondition: "stakeholder_success",
          message:
            "Phase 1 → Phase 2 requires at least one stakeholder success definition. Capture on D02 Stakeholder Map first.",
        },
        { status: 412 },
      );
    }
    const tensionRecords = getProgramTensionRecords(programCode);
    if (tensionRecords.length === 0) {
      return NextResponse.json(
        {
          error: "precondition_failed",
          precondition: "program_tension",
          message:
            "Phase 1 → Phase 2 requires at least one program tension with named owner. Capture on D04 Intake Synthesis first.",
        },
        { status: 412 },
      );
    }
    // FM-02 · require a data-readiness record with no blocked dimensions.
    // Gaps are allowed (the tenant has acknowledged them); blocks are hard
    // stops until resolved.
    const readinessGate = dataReadinessGateMet(programCode);
    if (!readinessGate.met) {
      return NextResponse.json(
        {
          error: "precondition_failed",
          precondition: "data_readiness",
          reason: readinessGate.reason,
          blockedDimensions: readinessGate.blockedDimensions,
          message:
            readinessGate.reason === "no_record"
              ? "Phase 1 → Phase 2 requires a data-readiness assessment. Submit the five-dimension form on D03 Success Metric Tree first."
              : `Phase 1 → Phase 2 is blocked by ${readinessGate.blockedDimensions.length} data dimension${readinessGate.blockedDimensions.length === 1 ? "" : "s"} (${readinessGate.blockedDimensions.join(", ")}). Resolve or reclassify before advancing.`,
        },
        { status: 412 },
      );
    }
  }

  if (fromPhase === 2 && toPhase === 3) {
    const engRow = await resolvePhaseGateEngagement(programCode).catch(
      (err) => {
        console.error("[phase-gate] discovery readiness lookup failed", {
          programCode,
          message: err instanceof Error ? err.message : String(err),
        });
        return null;
      },
    );
    if (!engRow) {
      return NextResponse.json(
        {
          error: "precondition_failed",
          precondition: "discovery_evidence_readiness",
          message:
            "Phase 2 → Phase 3 requires a resolvable Move row so discovery evidence readiness can be checked.",
        },
        { status: 412 },
      );
    }
    const readiness = await loadDiscoveryEvidenceReadiness(
      policyCtx ?? (await requireTenancy()),
      engRow.id,
    );
    if (!readiness.readyForP3) {
      return NextResponse.json(
        {
          error: "precondition_failed",
          precondition: "discovery_evidence_readiness",
          readiness,
          message: `Phase 2 → Phase 3 is blocked by ${readiness.requiredMissing} missing required discovery evidence family${readiness.requiredMissing === 1 ? "" : "ies"}. Upload the missing evidence or record a human waiver before advancing.`,
        },
        { status: 412 },
      );
    }
  }

  const clerk = await clerkClient();
  const user = await clerk.users.getUser(session.userId);
  const role = (user.publicMetadata?.role as string | undefined) ?? null;
  const email = user.emailAddresses[0]?.emailAddress ?? null;
  const name =
    [user.firstName, user.lastName].filter(Boolean).join(" ") || email;
  const evidencePacket = buildMovesPhaseDecisionEvidencePacket({
    programId: programCode,
    tenantName: ownerKey,
    fromPhase,
    toPhase,
    gateCriterion,
    humanRationale,
    decisionOwner: {
      name: name ?? "Unknown approver",
      title: role ?? advancerRole ?? "Gate approver",
      tenantName: ownerKey,
      userId: session.userId,
    },
    evidenceIds: coerceDecisionSupportList(body.evidenceIds),
    missingInputs: coerceDecisionSupportList(body.missingInputs),
    assumptions: coerceDecisionSupportList(body.assumptions),
    alternativesConsidered: coerceDecisionSupportList(
      body.alternativesConsidered,
    ),
    overrideDisposition: "accepted",
  } satisfies MovesPhaseDecisionInput);

  const entry: PhaseGateEntry = {
    id: `${programCode}:P${fromPhase}->P${toPhase}:${Date.now()}`,
    programCode,
    fromPhase,
    toPhase,
    gateCriterion,
    humanRationale,
    aiDecisionEvidencePacket: evidencePacket,
    advancedById: session.userId,
    advancedByEmail: email,
    advancedByName: name,
    advancedByRole: role,
    timestamp: new Date().toISOString(),
  };

  // SECURITY (audit 2026-05-22, P1-6): the filesystem ledger at
  // `.approvals/phase-gates.json` is NOT durable — it is lost on redeploy
  // and inconsistent across serverless instances. The authoritative
  // record of a phase-gate advance is the Supabase `program_audit_log`
  // write below. The filesystem write is kept only as a best-effort
  // local cache for the assigned-to-me queue and never gates the
  // response; a filesystem failure must not block a successful advance.
  let engagementId: string | null = null;
  try {
    const engRow = await resolvePhaseGateEngagement(programCode);
    if (engRow) {
      engagementId = engRow.id;

      // 2. Build the deduplicated gates_passed array with the new phase appended.
      const existingGates: number[] = Array.isArray(engRow.gates_passed)
        ? (engRow.gates_passed as number[])
        : [];
      const updatedGates = Array.from(
        new Set([...existingGates, toPhase]),
      ).sort((a, b) => a - b);

      // 3. UPDATE engagements.current_phase and gates_passed — routed through
      // the data-plane write seam (Slice 3a). The engagement-row lookup above
      // is read-only and now uses the Packet 30 read plane.
      const ok = await selectProgramsWriteAdapter().advanceEngagementPhase({
        engagementId,
        toPhase,
        gatesPassed: updatedGates,
        tenantKey: ownerKey,
      });
      if (!ok) {
        console.error("[phase-gate] engagement phase update failed", {
          programCode,
          engagementId,
        });
      }

      // State reconciliation: keep the canonical gate signals in lockstep with
      // current_phase. advanceEngagementPhase moved current_phase + gates_passed
      // above; now record the approved gate as a phase_snapshot and clear any
      // pending lifecycle so getMoveStatus (Overview) and the snapshot history
      // don't read a stale "awaiting decision" after the advance. Best-effort —
      // the authoritative record is the audit-log write below, so a failure here
      // is logged, never fatal.
      try {
        const writeSb = getAzureWriteFluentClient();
        await writeSb.from("phase_snapshots").insert({
          engagement_id: engagementId,
          phase_number: toPhase,
          approval_status: "approved",
        });
        await writeSb
          .from("engagements")
          .update({ lifecycle_state: "approved" })
          .eq("id", engagementId);
      } catch (snapErr) {
        console.warn(
          "[phase-gate] snapshot/lifecycle reconciliation write failed",
          {
            programCode,
            engagementId,
            message:
              snapErr instanceof Error ? snapErr.message : String(snapErr),
          },
        );
      }
    }
  } catch (err) {
    console.error("[phase-gate] supabase write threw", {
      programCode,
      message: err instanceof Error ? err.message : String(err),
    });
  }

  // 4. AUTHORITATIVE audit-log write. This is the durable record of the
  // phase-gate advance. If it fails, the request fails — we do NOT report
  // success on an advance that left no audit trail.
  try {
    await writeProgramAuditLog(
      {
        clientId: ownerKey,
        userId: session.userId,
        role: role ?? advancerRole ?? undefined,
      },
      {
        tenantKey: ownerKey,
        programId: programCode,
        engagementId: engagementId ?? undefined,
        action: "PHASE_GATE_ADVANCED",
        fromState: `P${fromPhase}`,
        toState: `P${toPhase}`,
        rationale: humanRationale,
        evidenceRefs: buildMovesPhaseDecisionAuditRefs(evidencePacket),
      },
    );
  } catch (err) {
    console.error("[phase-gate] authoritative audit-log write failed", {
      programCode,
      message: err instanceof Error ? err.message : String(err),
    });
    return NextResponse.json(
      {
        error: "audit_log_write_failed",
        detail:
          "The phase-gate advance could not be recorded to the durable audit log. The advance was not committed as confirmed — retry.",
      },
      { status: 500 },
    );
  }

  // 5. Best-effort filesystem cache — non-authoritative. A failure here is
  // logged and swallowed; the durable record already landed above.
  try {
    const ledger = readLedger();
    ledger.entries.push(entry);
    writeLedger(ledger);
  } catch (err) {
    console.warn(
      "[phase-gate] non-authoritative filesystem ledger write failed (ignored)",
      {
        programCode,
        message: err instanceof Error ? err.message : String(err),
      },
    );
  }

  let discoveryPlanGeneration: DiscoveryPlanAutoGenerationStatus = {
    status: "skipped",
    reason: "not a Charter to Discover phase advance",
  };
  if (fromPhase === 1 && toPhase === 2) {
    discoveryPlanGeneration = await autoGenerateDiscoveryPlanOnCharterApproval({
      tenantKey: ownerKey,
      moveId: engagementId,
      renderedBy: session.userId,
      generatedOn: entry.timestamp,
    }).catch((err) => {
      console.error("[phase-gate] discovery-plan auto-generation failed", {
        programCode,
        engagementId,
        message: err instanceof Error ? err.message : String(err),
      });
      return {
        status: "failed",
        reason:
          err instanceof Error
            ? err.message
            : "discovery-plan auto-generation failed",
      } satisfies DiscoveryPlanAutoGenerationStatus;
    });
  }

  return NextResponse.json({
    ok: true,
    entry,
    evidencePacket,
    discoveryPlanGeneration,
  });
}

export async function GET(request: NextRequest) {
  const session = await auth();
  if (!session.userId) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }
  const programCode = request.nextUrl.searchParams.get("programCode");

  if (programCode) {
    const ownerKey = tenantKeyForProgramCode(programCode);
    if (!ownerKey) {
      return NextResponse.json({ ok: true, entries: [] });
    }
    const access = await checkTenantAccessByKey(ownerKey);
    if (!access.ok) {
      const status = access.reason === "unauthenticated" ? 401 : 403;
      return NextResponse.json({ error: access.reason }, { status });
    }
  } else {
    return NextResponse.json({ ok: true, entries: [] });
  }

  const ledger = readLedger();
  const filtered = ledger.entries
    .filter((e) => (programCode ? e.programCode === programCode : true))
    .sort((a, b) => (a.timestamp < b.timestamp ? 1 : -1));
  return NextResponse.json({ ok: true, entries: filtered });
}
