/**
 * C-639 · the crawl must say WHICH of two causes stopped it, because they have
 * opposite owners.
 *
 * The signed-in crawl has failed on every `main` SHA with the same line —
 * `crawl_auth_bootstrap_failed … This ticket is invalid. Make sure you're using
 * a valid ticket generated by Clerk` — thrown inside the browser's
 * `signIn.create({ strategy: "ticket" })`. That single line is consistent with
 * two different defects whose remedies point at different people:
 *
 *   (1) the minting secret belongs to a different or rotated Clerk instance
 *       than the one the browser loads — an operator provisions a secret, and
 *       an agent must stop at that boundary rather than edit the crawl;
 *   (2) the crawl mints or redeems the ticket wrongly — ordinary code, this
 *       lane's to fix.
 *
 * The strings asserted below are not invented. The redemption error is quoted
 * from run 37150673373's own log; the issuer/publishable-key pairs are the two
 * shapes a Clerk instance actually presents (a production vanity Frontend API
 * host, and a `*.clerk.accounts.dev` development instance).
 *
 * The classifier must distinguish them WITHOUT the secret's value, and must
 * answer `undetermined` rather than guessing when an identity is unreadable —
 * naming the wrong owner is worse than naming neither.
 */
import {
  classifyCrawlAuthFailure,
  clerkTicketIssuerHost,
  formatCrawlAuthVerdictLine,
  type CrawlAuthObservation,
} from "@/lib/crawl/clerk-auth-cause";

const REDEEM_ERROR =
  "page.evaluate: e: This ticket is invalid. Make sure you're using a valid ticket generated by Clerk.";

/** A Clerk sign-in ticket is an unverified-readable JWT; only `iss` is read. */
function ticketIssuedBy(issuer: string): string {
  const b64 = (value: object) =>
    Buffer.from(JSON.stringify(value))
      .toString("base64")
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");
  return [
    b64({ alg: "RS256", typ: "JWT" }),
    b64({ iss: issuer, sid: "sit_2abcDEF" }),
    "signature-not-verified-here",
  ].join(".");
}

/** `pk_test_<base64 of "<frontend-api-host>$">`, the real publishable-key shape. */
function publishableKeyFor(host: string): string {
  return `pk_test_${Buffer.from(`${host}$`).toString("base64")}`;
}

function observation(
  overrides: Partial<CrawlAuthObservation> = {},
): CrawlAuthObservation {
  return {
    mint: {
      ok: true,
      ticket: ticketIssuedBy("https://clerk.abarva.ai"),
      expiresInSeconds: 300,
    },
    redeem: { ok: false, error: REDEEM_ERROR, elapsedMsSinceMint: 2_500 },
    publishableKey: publishableKeyFor("clerk.abarva.ai"),
    ...overrides,
  };
}

describe("C-639 · crawl auth failure cause", () => {
  it("reads the minting instance out of the ticket without verifying it", () => {
    expect(
      clerkTicketIssuerHost(ticketIssuedBy("https://clerk.abarva.ai")),
    ).toBe("clerk.abarva.ai");
    expect(
      clerkTicketIssuerHost(
        ticketIssuedBy("https://sample-app-42.clerk.accounts.dev"),
      ),
    ).toBe("sample-app-42.clerk.accounts.dev");
  });

  it("returns null for anything that is not a readable ticket", () => {
    expect(clerkTicketIssuerHost(undefined)).toBeNull();
    expect(clerkTicketIssuerHost("")).toBeNull();
    expect(clerkTicketIssuerHost("not-a-jwt")).toBeNull();
    expect(clerkTicketIssuerHost("a.b.c")).toBeNull();
  });

  it("names the OPERATOR when the ticket was minted by a different instance than the browser loads", () => {
    const verdict = classifyCrawlAuthFailure(
      observation({
        mint: {
          ok: true,
          ticket: ticketIssuedBy("https://sample-app-42.clerk.accounts.dev"),
          expiresInSeconds: 300,
        },
      }),
    );

    expect(verdict.cause).toBe("instance_mismatch");
    expect(verdict.owner).toBe("operator-secret");
    expect(verdict.mintInstance).toBe("sample-app-42.clerk.accounts.dev");
    expect(verdict.redeemInstance).toBe("clerk.abarva.ai");
    // The statement has to carry both hosts, or an operator cannot act on it.
    expect(verdict.statement).toContain("sample-app-42.clerk.accounts.dev");
    expect(verdict.statement).toContain("clerk.abarva.ai");
  });

  it("names THIS LANE when the instances agree and the ticket was still rejected", () => {
    const verdict = classifyCrawlAuthFailure(observation());

    expect(verdict.cause).toBe("redemption_defect");
    expect(verdict.owner).toBe("this-lane");
    expect(verdict.mintInstance).toBe("clerk.abarva.ai");
    expect(verdict.redeemInstance).toBe("clerk.abarva.ai");
  });

  it("names THIS LANE when the ticket expired before the browser redeemed it", () => {
    const verdict = classifyCrawlAuthFailure(
      observation({
        redeem: {
          ok: false,
          error: REDEEM_ERROR,
          elapsedMsSinceMint: 301_000,
        },
      }),
    );

    expect(verdict.cause).toBe("ticket_expired_before_redemption");
    expect(verdict.owner).toBe("this-lane");
  });

  it("separates a refused MINT from a refused redemption, and stages it upstream", () => {
    const verdict = classifyCrawlAuthFailure(
      observation({
        mint: {
          ok: false,
          error: "crawl_clerk_ticket_user_not_found:a@b.test",
        },
        redeem: { ok: false, error: "not attempted" },
      }),
    );

    expect(verdict.cause).toBe("mint_rejected");
    expect(verdict.stage).toBe("mint");
    expect(verdict.statement).toContain("crawl_clerk_ticket_user_not_found");
  });

  it("answers UNDETERMINED rather than guessing an owner when an identity is unreadable", () => {
    const noIssuer = classifyCrawlAuthFailure(
      observation({
        mint: { ok: true, ticket: "opaque-not-a-jwt", expiresInSeconds: 300 },
      }),
    );
    expect(noIssuer.cause).toBe("undetermined");
    expect(noIssuer.owner).toBe("undetermined");
    expect(noIssuer.mintInstance).toBeNull();

    const noPublishableKey = classifyCrawlAuthFailure(
      observation({ publishableKey: undefined }),
    );
    expect(noPublishableKey.cause).toBe("undetermined");
    expect(noPublishableKey.owner).toBe("undetermined");
    expect(noPublishableKey.redeemInstance).toBeNull();
    // It must say which side it could not read, not merely that it failed.
    expect(noPublishableKey.statement).toMatch(/publishable key/i);
  });

  it("does not report a failure when neither stage failed", () => {
    const verdict = classifyCrawlAuthFailure(
      observation({ redeem: { ok: true, elapsedMsSinceMint: 900 } }),
    );
    expect(verdict.cause).toBe("no_failure");
  });

  it("every verdict carries a one-line statement that names an owner in words", () => {
    const observations: CrawlAuthObservation[] = [
      observation(),
      observation({
        mint: {
          ok: true,
          ticket: ticketIssuedBy("https://other.clerk.accounts.dev"),
          expiresInSeconds: 300,
        },
      }),
      observation({
        mint: { ok: false, error: "boom" },
        redeem: { ok: false },
      }),
      observation({
        mint: { ok: true, ticket: "opaque", expiresInSeconds: 300 },
      }),
    ];

    for (const candidate of observations) {
      const verdict = classifyCrawlAuthFailure(candidate);
      expect(verdict.statement.trim().length).toBeGreaterThan(40);
      expect(verdict.statement).not.toContain("\n");
      expect(verdict.statement).toMatch(
        /operator provisions|this lane|cannot be determined/i,
      );
    }
  });

  it("formats one grep-able line that carries the cause, the owner and both instances", () => {
    const verdict = classifyCrawlAuthFailure(
      observation({
        mint: {
          ok: true,
          ticket: ticketIssuedBy("https://sample-app-42.clerk.accounts.dev"),
          expiresInSeconds: 300,
        },
      }),
    );
    const line = formatCrawlAuthVerdictLine("agent-meridian", verdict);

    expect(line.startsWith("crawl_auth_cause:agent-meridian:")).toBe(true);
    expect(line).toContain(":instance_mismatch:");
    expect(line).toContain("owner=operator-secret");
    expect(line).toContain("mint_instance=sample-app-42.clerk.accounts.dev");
    expect(line).toContain("redeem_instance=clerk.abarva.ai");
    expect(line).toContain(verdict.statement);
    expect(line.split("\n")).toHaveLength(1);
  });

  it("says `unreadable` in the line rather than printing an empty field", () => {
    const line = formatCrawlAuthVerdictLine(
      "agent-skyharbor",
      classifyCrawlAuthFailure(observation({ publishableKey: undefined })),
    );

    expect(line).toContain("redeem_instance=unreadable");
    expect(line).not.toContain("redeem_instance=:");
    expect(line).not.toContain("redeem_instance= ");
  });
});
