// Architecture HTML blobs — generated by AbarVa Intelligence Platform

export const ARCTURUS_TARGET_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Arcturus — Target State Architecture</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#27AE60;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#818CF8}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#0a1120 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:8px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
.lw{border:1px solid var(--border);border-radius:8px;padding:10px 14px;margin-bottom:6px;background:var(--surface)}
.lh{display:flex;justify-content:space-between;align-items:center;margin-bottom:4px}
.ln{font-family:var(--mono);font-size:11px;font-weight:600;color:var(--text)}
.lt{font-size:10px;color:var(--t3)}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}.bad{color:var(--red);background:rgba(239,68,68,0.1)}.info{color:var(--blue);background:rgba(77,163,255,0.1)}.accent-tag{color:var(--accent);background:rgba(129,140,248,0.12)}
.arrow{text-align:center;font-size:18px;color:var(--t3);padding:2px 0}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.highlight{border-color:var(--accent);color:var(--accent)}
.metric{font-family:var(--mono);font-size:22px;font-weight:600;color:var(--accent)}
.mlabel{font-size:10px;color:var(--t3);margin-top:2px}
.sub{font-size:10px;color:var(--t3);margin-top:4px;line-height:1.4}
.resolve{display:flex;align-items:center;gap:6px;padding:6px 0;border-bottom:1px solid var(--border);font-size:11px}
.resolve:last-child{border-bottom:none}
.dot-ok{width:8px;height:8px;border-radius:50%;background:var(--glt);flex-shrink:0}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Intelligence Platform · Arcturus Financial Group</div><div class="ct">Target State Architecture — Post-Engagement</div><div class="csub">Wave 1 + Wave 2 complete · All root causes resolved · <span>$292M annual value unlocked</span></div></div>
  <div class="cmeta"><strong>CLIENT</strong> Arcturus Financial Group<br><strong>STATUS</strong> Target State<br><strong>DATE</strong> Q2 2026</div>
</div>
<div class="wrap">
  <h3>Root Cause Resolution</h3>
  <div class="grid2" style="margin-bottom:16px">
    <div class="card">
      <div class="resolve"><div class="dot-ok"></div><strong>CDO Appointed</strong> — Data governance framework live, CoE staffed</div>
      <div class="resolve"><div class="dot-ok"></div><strong>Golden Record Deployed</strong> — 14 silos unified, master data active</div>
    </div>
    <div class="card">
      <div class="resolve"><div class="dot-ok"></div><strong>CRO Freeze Lifted</strong> — Model validation framework, SR 11-7 compliant</div>
      <div class="resolve"><div class="dot-ok"></div><strong>FSC AI Activated</strong> — Einstein live, 44%→91% adoption, advisors onboarded</div>
    </div>
  </div>
  <h3>Golden Record — Unified Data Mesh</h3>
  <div class="boundary">
    <div class="blabel">Azure AI Foundry · Data Mesh Layer</div>
    <div class="flow" style="margin-bottom:10px">
      <div class="box">Bloomberg API<br><span style="color:var(--glt);font-size:9px">Real-time ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Aladdin<br><span style="color:var(--glt);font-size:9px">Connected ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box highlight">Golden Record<br><span style="font-size:9px">Client + Portfolio</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Salesforce FSC<br><span style="color:var(--glt);font-size:9px">Einstein ON ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Charles River<br><span style="color:var(--glt);font-size:9px">OMS Live ✓</span></div>
    </div>
    <div class="flow">
      <div class="box">Geneva → Vermilion<br><span style="color:var(--glt);font-size:9px">Real-time ✓ (3d lag eliminated)</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Workday<br><span style="color:var(--glt);font-size:9px">HR/Finance synced</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box highlight">Claude Orchestrator<br><span style="font-size:9px">Azure AI Foundry</span></div>
    </div>
  </div>
  <h3>Live AI Initiatives — Value Delivery</h3>
  <div class="grid2">
    <div class="card" style="border-left:3px solid var(--accent)">
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <div><div style="font-family:var(--mono);font-size:11px;font-weight:600">Advisor AI Assistant</div><div class="sub">NLP query engine on golden record<br>Churn signals · Next-best-action</div></div>
        <div style="text-align:right"><div class="metric">$29M</div><div class="mlabel">annual value</div></div>
      </div>
      <div style="margin-top:8px"><span class="tag ok">LIVE</span><span class="tag info">Claude 3.7</span></div>
    </div>
    <div class="card" style="border-left:3px solid var(--teal)">
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <div><div style="font-family:var(--mono);font-size:11px;font-weight:600">Real-time Reporting</div><div class="sub">Bloomberg API + Vermilion replace Geneva<br>3-day lag → sub-minute latency</div></div>
        <div style="text-align:right"><div class="metric">$18M</div><div class="mlabel">annual value</div></div>
      </div>
      <div style="margin-top:8px"><span class="tag ok">LIVE</span><span class="tag info">Synapse Analytics</span></div>
    </div>
    <div class="card" style="border-left:3px solid var(--purple)">
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <div><div style="font-family:var(--mono);font-size:11px;font-weight:600">Credit Risk AI</div><div class="sub">Regulatory-validated ML models<br>SR 11-7 framework · Champion/Challenger</div></div>
        <div style="text-align:right"><div class="metric">$34M</div><div class="mlabel">annual value</div></div>
      </div>
      <div style="margin-top:8px"><span class="tag ok">LIVE</span><span class="tag info">Azure ML</span></div>
    </div>
    <div class="card" style="border-left:3px solid var(--amber)">
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <div><div style="font-family:var(--mono);font-size:11px;font-weight:600">FSC AI — Einstein</div><div class="sub">CRM AI activated · Advisor productivity<br>44% → 91% platform adoption</div></div>
        <div style="text-align:right"><div class="metric">$11M</div><div class="mlabel">annual value</div></div>
      </div>
      <div style="margin-top:8px"><span class="tag ok">LIVE</span><span class="tag info">Salesforce Einstein</span></div>
    </div>
  </div>
  <div class="card" style="margin-top:12px;border-color:var(--accent);display:flex;justify-content:space-around;align-items:center;padding:18px">
    <div style="text-align:center"><div class="metric" style="font-size:28px">$292M</div><div class="mlabel">Total Annual Value</div></div>
    <div style="text-align:center"><div class="metric" style="color:var(--glt)">4/4</div><div class="mlabel">Root Causes Resolved</div></div>
    <div style="text-align:center"><div class="metric" style="color:var(--teal)">91%</div><div class="mlabel">FSC Adoption</div></div>
    <div style="text-align:center"><div class="metric" style="color:var(--amber)">&lt;1min</div><div class="mlabel">Reporting Latency</div></div>
  </div>
</div></body></html>`

export const MERIDIAN_TARGET_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Meridian — Target State Architecture</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#27AE60;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#4DA3FF}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#061020 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:8px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
.lw{border:1px solid var(--border);border-radius:8px;padding:10px 14px;margin-bottom:6px;background:var(--surface)}
.lh{display:flex;justify-content:space-between;align-items:center;margin-bottom:4px}
.ln{font-family:var(--mono);font-size:11px;font-weight:600;color:var(--text)}
.lt{font-size:10px;color:var(--t3)}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}.bad{color:var(--red);background:rgba(239,68,68,0.1)}.info{color:var(--blue);background:rgba(77,163,255,0.1)}
.metric{font-family:var(--mono);font-size:22px;font-weight:600}
.mlabel{font-size:10px;color:var(--t3);margin-top:2px}
.sub{font-size:10px;color:var(--t3);margin-top:4px;line-height:1.4}
.resolve{display:flex;align-items:center;gap:6px;padding:6px 0;border-bottom:1px solid var(--border);font-size:11px}
.resolve:last-child{border-bottom:none}
.dot-ok{width:8px;height:8px;border-radius:50%;background:var(--glt);flex-shrink:0}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.rvt{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center;margin:20px 0 8px}
.rbox{border-radius:8px;padding:14px 16px}
.rt{font-family:var(--mono);font-size:10px;font-weight:700;margin-bottom:5px}
.rb{font-size:11px;line-height:1.5}
.rarr{font-size:28px;color:var(--t3);text-align:center}
.foot{font-family:var(--mono);font-size:8px;color:var(--t3);padding:14px 40px;border-top:1px solid var(--border);margin-top:20px}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Intelligence Platform · Meridian Health System</div><div class="ct">Target State Architecture — Post-Engagement</div><div class="csub">Wave 1 + Wave 2 complete · All root causes resolved · <span>$180–220M annual gap closed</span></div></div>
  <div class="cmeta"><strong>CLIENT</strong> Meridian Health System<br><strong>STATUS</strong> Target State<br><strong>DATE</strong> Q2 2026</div>
</div>
<div class="wrap">
  <h3>Root Cause Resolution</h3>
  <div class="grid2" style="margin-bottom:16px">
    <div class="card">
      <div class="resolve"><div class="dot-ok"></div><strong>CDO Appointed</strong> — Data governance live, unified data platform across all 23 hospitals</div>
      <div class="resolve"><div class="dot-ok"></div><strong>Epic Fully Deployed</strong> — All 47 Cogito dashboards live, MyChart 60%+ adoption</div>
      <div class="resolve"><div class="dot-ok"></div><strong>Prior Auth AI Active</strong> — Epic module 100% deployed, AI overturn rate 85%+</div>
    </div>
    <div class="card">
      <div class="resolve"><div class="dot-ok"></div><strong>Ensemble SLAs Enforced</strong> — $8M penalty clause activated, denial rate 8.4% vs 18.2%</div>
      <div class="resolve"><div class="dot-ok"></div><strong>Blue Ridge Integration Complete</strong> — All facilities on unified Epic, reporting unified</div>
      <div class="resolve"><div class="dot-ok"></div><strong>MA Star 4.0 Achieved</strong> — Quality bonus unlocked, $34M annual benefit</div>
    </div>
  </div>

  <h3>Unified Clinical Data Platform — Databricks on Azure</h3>
  <div class="boundary">
    <div class="blabel">Azure Health Data Services · HIPAA BAA Active · All 23 Hospitals</div>
    <div class="flow" style="margin-bottom:10px">
      <div class="box">Epic EHR<br><span style="color:var(--glt);font-size:9px">All 23 sites ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Workday HR<br><span style="color:var(--glt);font-size:9px">42,000 staff ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Ensemble RCM<br><span style="color:var(--glt);font-size:9px">SLAs enforced ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Claims &amp; Payers<br><span style="color:var(--glt);font-size:9px">Real-time ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box" style="border-color:var(--accent);color:var(--accent)">Databricks Lakehouse<br><span style="font-size:9px">Medallion · PHI-safe</span></div>
    </div>
    <div class="grid3">
      <div class="card" style="border-color:rgba(77,163,255,0.3)">
        <div style="font-family:var(--mono);font-size:10px;font-weight:700;color:var(--blue);margin-bottom:6px">Clinical AI — Epic Cogito</div>
        <div style="font-size:11px;color:var(--t3)">All 47 dashboards live. Nurse scheduling, OR utilization, length-of-stay prediction. Physicians interact via Epic — no separate tool.</div>
        <div style="margin-top:8px"><span class="tag ok">47/47 live</span></div>
      </div>
      <div class="card" style="border-color:rgba(168,85,247,0.3)">
        <div style="font-family:var(--mono);font-size:10px;font-weight:700;color:var(--purple);margin-bottom:6px">Prior Auth AI — Claude on Azure</div>
        <div style="font-size:11px;color:var(--t3)">Claude Sonnet processes prior auth requests. 85%+ auto-approval rate. All payer rules embedded. Human review at &lt;90% confidence. PHI stays in Azure tenant.</div>
        <div style="margin-top:8px"><span class="tag ok">85%+ auto-approval</span></div>
      </div>
      <div class="card" style="border-color:rgba(110,231,183,0.3)">
        <div style="font-family:var(--mono);font-size:10px;font-weight:700;color:var(--glt);margin-bottom:6px">RCM Recovery — Denial AI</div>
        <div style="font-size:11px;color:var(--t3)">Ensemble denial feed into Databricks. AI predicts denials before submission, auto-generates appeals. Denial rate 8.4% — from 18.2% baseline.</div>
        <div style="margin-top:8px"><span class="tag ok">8.4% denial rate</span></div>
      </div>
    </div>
  </div>

  <h3>Outcome Metrics — Post-Engagement</h3>
  <div class="grid4" style="margin-bottom:16px">
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--glt)">8.4%</div>
      <div class="mlabel">Denial rate (from 18.2%)</div>
    </div>
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--blue)">47/47</div>
      <div class="mlabel">Cogito dashboards live</div>
    </div>
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--purple)">4.0★</div>
      <div class="mlabel">MA Star rating</div>
    </div>
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--amber)">3.8%</div>
      <div class="mlabel">Operating margin (from 1.8%)</div>
    </div>
  </div>

  <div class="rvt">
    <div class="rbox" style="background:rgba(239,68,68,0.06);border:1px solid rgba(239,68,68,0.2)">
      <div class="rt" style="color:#EF4444">Current state — without this architecture</div>
      <div class="rb" style="color:#9CA3AF">18.2% denial rate · $94M write-offs · 12 of 47 Cogito live · Prior auth AI 23% deployed · Blue Ridge overdue · MA Star 3.5 · MyChart 34% adoption · CDO vacant · 1.8% operating margin</div>
    </div>
    <div class="rarr">→</div>
    <div class="rbox" style="background:rgba(45,212,200,0.06);border:1px solid rgba(45,212,200,0.2)">
      <div class="rt" style="color:#2DD4C8">Target state — with this architecture</div>
      <div class="rb" style="color:#9CA3AF">Denial rate 8.4% · $94M recovered · All 47 Cogito live · Prior auth AI 85%+ auto-approval · Blue Ridge integrated · MA Star 4.0 · MyChart 60%+ · CDO in seat · 3.8%+ operating margin</div>
    </div>
  </div>
</div>
<div class="foot">AbarVa Intelligence Platform · Meridian Health System · Azure Architecture Intelligence · April 2026 · Confidential · Built from actual technology inventory and clinical operations data</div>
</div></body></html>`

export const APEX_RETAIL_TARGET_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Apex Retail — Target State Architecture</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#34A853;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#34A853}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#060e0a 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:8px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
.lw{border:1px solid var(--border);border-radius:8px;padding:10px 14px;margin-bottom:6px;background:var(--surface)}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}.bad{color:var(--red);background:rgba(239,68,68,0.1)}
.metric{font-family:var(--mono);font-size:22px;font-weight:600}
.mlabel{font-size:10px;color:var(--t3);margin-top:2px}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.resolve{display:flex;align-items:center;gap:6px;padding:6px 0;border-bottom:1px solid var(--border);font-size:11px}
.resolve:last-child{border-bottom:none}
.dot-ok{width:8px;height:8px;border-radius:50%;background:var(--glt);flex-shrink:0}
.rvt{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center;margin:20px 0 8px}
.rbox{border-radius:8px;padding:14px 16px}
.rt{font-family:var(--mono);font-size:10px;font-weight:700;margin-bottom:5px}
.rb{font-size:11px;line-height:1.5}
.rarr{font-size:28px;color:var(--t3);text-align:center}
.foot{font-family:var(--mono);font-size:8px;color:var(--t3);padding:14px 40px;border-top:1px solid var(--border);margin-top:20px}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Intelligence Platform · Apex Retail Group</div><div class="ct">Target State Architecture — Post-Engagement</div><div class="csub">Wave 1 + Wave 2 complete · Omnichannel unified · <span>3.8% → 5.8% operating margin</span></div></div>
  <div class="cmeta"><strong>CLIENT</strong> Apex Retail Group<br><strong>STATUS</strong> Target State<br><strong>DATE</strong> Q2 2026</div>
</div>
<div class="wrap">
  <h3>Root Cause Resolution</h3>
  <div class="grid2" style="margin-bottom:16px">
    <div class="card">
      <div class="resolve"><div class="dot-ok"></div><strong>SAP S/4HANA Migrated</strong> — ECC 6.0 retired before 2027 support end, 8,400 customizations rationalized to 2,100</div>
      <div class="resolve"><div class="dot-ok"></div><strong>o9 Fully Deployed</strong> — Demand planning 100% live, forecast accuracy 62% → 84%, $180M excess inventory released</div>
      <div class="resolve"><div class="dot-ok"></div><strong>Inventory Accuracy 98%</strong> — RFID across 800 stores, unified inventory visible to commerce and stores</div>
    </div>
    <div class="card">
      <div class="resolve"><div class="dot-ok"></div><strong>Omnichannel Unified</strong> — Salesforce CC connected to S/4HANA, BOPIS live, conversion 2.8% → 4.1%</div>
      <div class="resolve"><div class="dot-ok"></div><strong>AI Demand Sensing</strong> — GCP Vertex AI on unified data, markdown optimization, shrinkage prediction live</div>
      <div class="resolve"><div class="dot-ok"></div><strong>China Sourcing Diversified</strong> — 48% → 30%, Vietnam/Mexico corridors live, tariff exposure reduced</div>
    </div>
  </div>

  <h3>Unified Commerce &amp; Supply Chain Platform — GCP</h3>
  <div class="boundary">
    <div class="blabel">Google Cloud Platform · Unified Retail Data Mesh · 800 Stores + Digital</div>
    <div class="flow" style="margin-bottom:10px">
      <div class="box">SAP S/4HANA<br><span style="color:var(--glt);font-size:9px">Migrated ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">o9 Demand<br><span style="color:var(--glt);font-size:9px">100% live ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">Salesforce CC<br><span style="color:var(--glt);font-size:9px">Conversion 4.1% ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box">800 Stores<br><span style="color:var(--glt);font-size:9px">RFID · BOPIS ✓</span></div>
      <div style="color:var(--t3)">→</div>
      <div class="box" style="border-color:var(--accent);color:var(--accent)">GCP BigQuery<br><span style="font-size:9px">Unified data mesh</span></div>
    </div>
    <div class="grid3">
      <div class="card" style="border-color:rgba(52,168,83,0.3)">
        <div style="font-family:var(--mono);font-size:10px;font-weight:700;color:var(--green);margin-bottom:6px">Supply Chain AI — Vertex AI</div>
        <div style="font-size:11px;color:var(--t3)">Demand sensing on unified store+digital+supplier data. Markdown optimization. Shrinkage prediction by store/SKU. Forecast accuracy 84%.</div>
        <div style="margin-top:8px"><span class="tag ok">84% forecast accuracy</span></div>
      </div>
      <div class="card" style="border-color:rgba(77,163,255,0.3)">
        <div style="font-family:var(--mono);font-size:10px;font-weight:700;color:var(--blue);margin-bottom:6px">Commerce AI — Salesforce + Claude</div>
        <div style="font-size:11px;color:var(--t3)">Personalization engine on GCP. Cart abandonment down from 72% to 54%. Real-time inventory available to digital. BOPIS live in all 800 stores.</div>
        <div style="margin-top:8px"><span class="tag ok">4.1% conversion</span></div>
      </div>
      <div class="card" style="border-color:rgba(245,158,11,0.3)">
        <div style="font-family:var(--mono);font-size:10px;font-weight:700;color:var(--amber);margin-bottom:6px">Loyalty &amp; Pricing AI</div>
        <div style="font-size:11px;color:var(--t3)">42% → 58% loyalty enrollment. Dynamic pricing on seasonal and perishable SKUs. Loyalty data feeds demand signal. Churn prediction live.</div>
        <div style="margin-top:8px"><span class="tag ok">58% loyalty</span></div>
      </div>
    </div>
  </div>

  <h3>Outcome Metrics — Post-Engagement</h3>
  <div class="grid4" style="margin-bottom:16px">
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--glt)">5.8%</div>
      <div class="mlabel">Operating margin (from 3.8%)</div>
    </div>
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--blue)">4.1%</div>
      <div class="mlabel">eCommerce conversion (from 2.8%)</div>
    </div>
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--green)">84%</div>
      <div class="mlabel">Forecast accuracy (from 62%)</div>
    </div>
    <div class="card" style="text-align:center">
      <div class="metric" style="color:var(--amber)">$180M</div>
      <div class="mlabel">Excess inventory released</div>
    </div>
  </div>

  <div class="rvt">
    <div class="rbox" style="background:rgba(239,68,68,0.06);border:1px solid rgba(239,68,68,0.2)">
      <div class="rt" style="color:#EF4444">Current state — without this architecture</div>
      <div class="rb" style="color:#9CA3AF">SAP ECC 6.0 support ending 2027 · o9 40% live · 62% forecast accuracy · $180M excess inventory · 2.8% conversion · 72% cart abandonment · 84% store inventory accuracy · 48% China sourcing · 3.8% operating margin</div>
    </div>
    <div class="rarr">→</div>
    <div class="rbox" style="background:rgba(45,212,200,0.06);border:1px solid rgba(45,212,200,0.2)">
      <div class="rt" style="color:#2DD4C8">Target state — with this architecture</div>
      <div class="rb" style="color:#9CA3AF">SAP S/4HANA live · o9 100% deployed · 84% forecast accuracy · $180M released · 4.1% conversion · 54% cart abandonment · 98% inventory accuracy · 30% China sourcing · 5.8% operating margin</div>
    </div>
  </div>
</div>
<div class="foot">AbarVa Intelligence Platform · Apex Retail Group · GCP Architecture Intelligence · April 2026 · Confidential · Built from actual technology inventory and supply chain data</div>
</div></body></html>`

export const PATTERN_LANDING_ZONE_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Azure Landing Zone Pattern</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#27AE60;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#4DA3FF}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#0a1120 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:12px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.info{color:var(--blue);background:rgba(77,163,255,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.highlight{border-color:var(--accent);color:var(--accent)}
.sub{font-size:10px;color:var(--t3);margin-top:4px;line-height:1.4}
.svc{background:var(--s2);border:1px solid var(--border);border-radius:5px;padding:5px 10px;font-family:var(--mono);font-size:9px;margin:3px 2px;display:inline-block}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Reference Patterns · Infrastructure</div><div class="ct">Azure Landing Zone → Production</div><div class="csub">Hub-spoke topology · Zero-trust identity · AI/ML workload zone · <span>Enterprise-grade governance</span></div></div>
  <div class="cmeta"><strong>PATTERN</strong> Landing Zone<br><strong>CLOUD</strong> Microsoft Azure<br><strong>VERSION</strong> CAF 2026</div>
</div>
<div class="wrap">
  <h3>Network Topology — Hub-Spoke</h3>
  <div class="boundary">
    <div class="blabel">Connectivity Subscription — Hub VNet</div>
    <div class="flow" style="margin-bottom:10px">
      <div class="box highlight">ExpressRoute GW<br><span style="font-size:9px;color:var(--t3)">10Gbps · ER Direct</span></div>
      <div style="color:var(--t3)">↔</div>
      <div class="box highlight">Azure Firewall<br><span style="font-size:9px;color:var(--t3)">Premium · IDPS</span></div>
      <div style="color:var(--t3)">↔</div>
      <div class="box">VPN Gateway<br><span style="font-size:9px;color:var(--t3)">S2S + P2S</span></div>
      <div style="color:var(--t3)">↔</div>
      <div class="box">DDoS Protection<br><span style="font-size:9px;color:var(--t3)">Standard</span></div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px">
      <div class="card" style="border-color:var(--accent)"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent);margin-bottom:6px">AI/ML Spoke</div><div class="svc">Azure AI Foundry</div><div class="svc">Azure ML</div><div class="svc">Private Endpoints</div><div class="svc">GPU Compute</div></div>
      <div class="card" style="border-color:rgba(77,163,255,0.3)"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--teal);margin-bottom:6px">Data Spoke</div><div class="svc">ADLS Gen2</div><div class="svc">Synapse Analytics</div><div class="svc">Databricks</div><div class="svc">Event Hub</div></div>
      <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--t2);margin-bottom:6px">App Spoke</div><div class="svc">AKS Cluster</div><div class="svc">App Gateway</div><div class="svc">API Management</div><div class="svc">Container Apps</div></div>
    </div>
  </div>
  <h3>Identity &amp; Access — Zero Trust</h3>
  <div class="grid2" style="margin-bottom:16px">
    <div class="card">
      <div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent);margin-bottom:8px">Microsoft Entra ID</div>
      <div class="flow"><div class="svc">PIM — JIT Access</div><div class="svc">Conditional Access</div><div class="svc">MFA Enforced</div></div>
      <div class="flow" style="margin-top:4px"><div class="svc">Managed Identities</div><div class="svc">App Registrations</div></div>
    </div>
    <div class="card">
      <div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--amber);margin-bottom:8px">Governance &amp; Compliance</div>
      <div class="flow"><div class="svc">Azure Policy</div><div class="svc">Defender for Cloud</div></div>
      <div class="flow" style="margin-top:4px"><div class="svc">Microsoft Purview</div><div class="svc">Cost Mgmt</div><div class="svc">Blueprints</div></div>
    </div>
  </div>
  <h3>Security Operations</h3>
  <div class="grid3">
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--red);margin-bottom:6px">Microsoft Sentinel</div><div class="sub">SIEM/SOAR · Threat detection · Automated playbooks · KQL analytics rules</div><div style="margin-top:8px"><span class="tag ok">Active</span></div></div>
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--amber);margin-bottom:6px">Azure Key Vault</div><div class="sub">Secrets · Certificates · HSM keys · RBAC-scoped access · Rotation policy</div><div style="margin-top:8px"><span class="tag ok">Active</span></div></div>
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--blue);margin-bottom:6px">Defender for Cloud</div><div class="sub">Secure Score · CSPM · CWPP · Regulatory compliance dashboard</div><div style="margin-top:8px"><span class="tag ok">Active</span></div></div>
  </div>
  <h3>Deployment Flow</h3>
  <div class="flow" style="margin-top:4px">
    <div class="box">Bicep / Terraform<br><span style="font-size:9px;color:var(--t3)">IaC</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">GitHub Actions<br><span style="font-size:9px;color:var(--t3)">CI/CD</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">Policy Gate<br><span style="font-size:9px;color:var(--t3)">Compliance check</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box highlight">Landing Zone<br><span style="font-size:9px">Production</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">Sentinel Alert<br><span style="font-size:9px;color:var(--t3)">Monitor</span></div>
  </div>
</div></body></html>`

export const PATTERN_AGENTIC_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Agentic AI Architecture Pattern</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#27AE60;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#A855F7}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#0a1120 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:12px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.grid4{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.info{color:var(--blue);background:rgba(77,163,255,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}.purple-tag{color:var(--accent);background:rgba(168,85,247,0.12)}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.highlight{border-color:var(--accent);color:var(--accent)}
.sub{font-size:10px;color:var(--t3);margin-top:4px;line-height:1.4}
.svc{background:var(--s2);border:1px solid var(--border);border-radius:5px;padding:5px 10px;font-family:var(--mono);font-size:9px;margin:3px 2px;display:inline-block}
.human-gate{background:rgba(245,158,11,0.08);border:2px solid var(--amber);border-radius:8px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--amber)}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Reference Patterns · AI</div><div class="ct">Agentic AI Architecture</div><div class="csub">Claude orchestrator · Specialized sub-agents · Human-in-the-loop · <span>Tool-augmented reasoning</span></div></div>
  <div class="cmeta"><strong>PATTERN</strong> Agentic AI<br><strong>ORCHESTRATOR</strong> Claude 3.7<br><strong>PLATFORM</strong> Azure AI Foundry</div>
</div>
<div class="wrap">
  <h3>Orchestration Layer</h3>
  <div class="boundary">
    <div class="blabel">Agentic Core — Azure AI Foundry</div>
    <div style="text-align:center;margin-bottom:12px">
      <div class="box highlight" style="display:inline-block;padding:12px 24px;font-size:12px">Claude Orchestrator Agent<br><span style="font-size:9px;color:var(--t3);font-weight:400">Task decomposition · Sub-agent routing · Context management · Tool selection</span></div>
    </div>
    <div class="grid4">
      <div class="card" style="border-color:rgba(168,85,247,0.4);text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent)">Data Agent</div><div class="sub">Query databases · Fetch schemas · Validate data</div></div>
      <div class="card" style="border-color:rgba(168,85,247,0.4);text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent)">Analysis Agent</div><div class="sub">Statistical analysis · ML inference · Pattern detection</div></div>
      <div class="card" style="border-color:rgba(168,85,247,0.4);text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent)">Reporting Agent</div><div class="sub">Narrative generation · Chart data · Document creation</div></div>
      <div class="card" style="border-color:rgba(168,85,247,0.4);text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent)">Action Agent</div><div class="sub">API calls · Workflow triggers · System updates</div></div>
    </div>
  </div>
  <h3>Tool Layer</h3>
  <div class="grid3" style="margin-bottom:16px">
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--blue);margin-bottom:6px">Data &amp; Storage</div><div class="svc">SQL / NoSQL Query</div><div class="svc">Vector DB (pgvector)</div><div class="svc">ADLS Gen2</div><div class="svc">Redis Cache</div></div>
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--teal);margin-bottom:6px">External APIs</div><div class="svc">REST / GraphQL</div><div class="svc">Bloomberg Market Data</div><div class="svc">Salesforce FSC</div><div class="svc">Web Search</div></div>
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--amber);margin-bottom:6px">Compute &amp; Runtime</div><div class="svc">Code Interpreter</div><div class="svc">Python Sandbox</div><div class="svc">Azure Functions</div><div class="svc">Container Jobs</div></div>
  </div>
  <h3>Memory &amp; Context Store</h3>
  <div class="flow" style="margin-bottom:16px">
    <div class="box">Short-term<br><span style="font-size:9px;color:var(--t3)">200k token context</span></div>
    <div style="color:var(--t3)">+</div>
    <div class="box">Episodic Memory<br><span style="font-size:9px;color:var(--t3)">Session summaries</span></div>
    <div style="color:var(--t3)">+</div>
    <div class="box">Semantic Store<br><span style="font-size:9px;color:var(--t3)">Vector embeddings</span></div>
    <div style="color:var(--t3)">+</div>
    <div class="box">Procedural Memory<br><span style="font-size:9px;color:var(--t3)">Tool use patterns</span></div>
  </div>
  <h3>Human-in-the-Loop Gates</h3>
  <div class="flow" style="margin-bottom:16px">
    <div class="box">Agent Task Start</div>
    <div style="color:var(--t3)">→</div>
    <div class="box">Sub-agent Execution</div>
    <div style="color:var(--t3)">→</div>
    <div class="human-gate">⚠ Approval Gate<br><span style="font-size:9px;font-weight:400">High-impact actions require human sign-off</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">Action Agent</div>
    <div style="color:var(--t3)">→</div>
    <div class="box highlight">Output Delivered</div>
  </div>
  <h3>Output Channels</h3>
  <div class="grid4">
    <div class="card" style="text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600">Chat UI</div><div class="sub">Streaming response</div><div style="margin-top:6px"><span class="tag ok">Live</span></div></div>
    <div class="card" style="text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600">API Webhook</div><div class="sub">JSON / Structured</div><div style="margin-top:6px"><span class="tag ok">Live</span></div></div>
    <div class="card" style="text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600">Report PDF</div><div class="sub">Automated docs</div><div style="margin-top:6px"><span class="tag ok">Live</span></div></div>
    <div class="card" style="text-align:center"><div style="font-family:var(--mono);font-size:10px;font-weight:600">Workflow Trigger</div><div class="sub">Power Automate</div><div style="margin-top:6px"><span class="tag ok">Live</span></div></div>
  </div>
</div></body></html>`

export const PATTERN_DATA_PLATFORM_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Modern Data Platform — Medallion</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#27AE60;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#F59E0B}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#0a1120 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:12px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.grid4{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.info{color:var(--blue);background:rgba(77,163,255,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.highlight{border-color:var(--accent);color:var(--accent)}
.sub{font-size:10px;color:var(--t3);margin-top:4px;line-height:1.4}
.svc{background:var(--s2);border:1px solid var(--border);border-radius:5px;padding:5px 10px;font-family:var(--mono);font-size:9px;margin:3px 2px;display:inline-block}
.layer{border-radius:8px;padding:12px;margin-bottom:8px}
.bronze{background:rgba(120,80,40,0.12);border:1px solid rgba(180,120,60,0.3)}
.silver{background:rgba(80,100,120,0.12);border:1px solid rgba(140,160,180,0.3)}
.gold{background:rgba(180,140,20,0.12);border:1px solid rgba(245,158,11,0.4)}
.serve{background:rgba(45,212,200,0.07);border:1px solid rgba(45,212,200,0.3)}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Reference Patterns · Data</div><div class="ct">Modern Data Platform — Medallion Architecture</div><div class="csub">Bronze → Silver → Gold · Lakehouse · Governance · <span>AI-ready serving layer</span></div></div>
  <div class="cmeta"><strong>PATTERN</strong> Data Platform<br><strong>STORAGE</strong> ADLS Gen2 / Delta Lake<br><strong>COMPUTE</strong> Databricks + Synapse</div>
</div>
<div class="wrap">
  <h3>Ingestion Sources</h3>
  <div class="flow" style="margin-bottom:16px">
    <div class="box">ERP<br><span style="font-size:9px;color:var(--t3)">SAP / D365</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">CRM<br><span style="font-size:9px;color:var(--t3)">Salesforce</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">REST APIs<br><span style="font-size:9px;color:var(--t3)">3rd party</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">Files / Feeds<br><span style="font-size:9px;color:var(--t3)">CSV, Parquet, JSON</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box">Streaming<br><span style="font-size:9px;color:var(--t3)">Event Hub / Kafka</span></div>
    <div style="color:var(--t3)">→</div>
    <div class="box highlight">ADF / Fabric<br><span style="font-size:9px">Ingestion Engine</span></div>
  </div>
  <h3>Medallion Layers</h3>
  <div class="layer bronze"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:#C87941;margin-bottom:8px">BRONZE — Raw Zone (Immutable)</div><div class="flow"><div class="svc">Raw Parquet files</div><div class="svc">Schema-on-read</div><div class="svc">Full history retained</div><div class="svc">Partitioned by date</div><div class="svc">Auto-ingest pipelines</div></div></div>
  <div style="text-align:center;font-size:18px;color:var(--t3);margin:4px 0">↓ Cleanse · Validate · Deduplicate</div>
  <div class="layer silver"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:#A0B8CC;margin-bottom:8px">SILVER — Curated Zone (Trusted)</div><div class="flow"><div class="svc">Delta Lake format</div><div class="svc">Type enforcement</div><div class="svc">Null / outlier handling</div><div class="svc">Golden Record merge</div><div class="svc">DQ rules (Great Expectations)</div><div class="svc">PII masking</div></div></div>
  <div style="text-align:center;font-size:18px;color:var(--t3);margin:4px 0">↓ Aggregate · Enrich · Feature Engineer</div>
  <div class="layer gold"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--amber);margin-bottom:8px">GOLD — Business Zone (Analytics-ready)</div><div class="flow"><div class="svc">Star / Wide schemas</div><div class="svc">Pre-aggregated marts</div><div class="svc">ML feature store</div><div class="svc">Semantic layer (dbt)</div><div class="svc">SLA: &lt;15 min refresh</div></div></div>
  <div style="text-align:center;font-size:18px;color:var(--t3);margin:4px 0">↓ Serve</div>
  <div class="layer serve"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--teal);margin-bottom:8px">SERVING — Consumption Layer</div><div class="grid4">
    <div class="card" style="background:transparent;border-color:rgba(45,212,200,0.2)"><div style="font-family:var(--mono);font-size:9px;font-weight:600">BI &amp; Reports</div><div class="sub">Power BI · Tableau · Synapse Serverless</div></div>
    <div class="card" style="background:transparent;border-color:rgba(45,212,200,0.2)"><div style="font-family:var(--mono);font-size:9px;font-weight:600">ML Models</div><div class="sub">Azure ML · Feature retrieval · Batch scoring</div></div>
    <div class="card" style="background:transparent;border-color:rgba(45,212,200,0.2)"><div style="font-family:var(--mono);font-size:9px;font-weight:600">AI Applications</div><div class="sub">Agentic agents · RAG pipelines · LLM context</div></div>
    <div class="card" style="background:transparent;border-color:rgba(45,212,200,0.2)"><div style="font-family:var(--mono);font-size:9px;font-weight:600">APIs</div><div class="sub">APIM · GraphQL · Materialized views</div></div>
  </div></div>
  <h3>Governance — Microsoft Purview</h3>
  <div class="flow">
    <div class="box">Data Catalog<br><span style="font-size:9px;color:var(--t3)">Auto-discovery</span></div>
    <div style="color:var(--t3)">+</div>
    <div class="box">Lineage Graph<br><span style="font-size:9px;color:var(--t3)">End-to-end tracking</span></div>
    <div style="color:var(--t3)">+</div>
    <div class="box">Access Policies<br><span style="font-size:9px;color:var(--t3)">Attribute-based</span></div>
    <div style="color:var(--t3)">+</div>
    <div class="box highlight">Data Quality<br><span style="font-size:9px">SLA dashboards</span></div>
  </div>
</div></body></html>`

export const PATTERN_MLOPS_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>MLOps Pipeline Pattern</title><style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600;700&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0D1117;--surface:#161B22;--s2:#1C2128;--border:#21262D;--b2:#30363D;--blue:#4DA3FF;--teal:#2DD4C8;--green:#27AE60;--glt:#6EE7B7;--purple:#A855F7;--amber:#F59E0B;--red:#EF4444;--gray:#9CA3AF;--text:#E6EDF3;--t2:#C9D1D9;--t3:#8B949E;--mono:'IBM Plex Mono',monospace;--sans:'IBM Plex Sans',sans-serif;--accent:#6EE7B7}
body{background:var(--bg);color:var(--text);font-family:var(--sans);font-size:13px;line-height:1.6;padding:0;min-width:900px}
.cover{border-bottom:3px solid var(--accent);padding:28px 40px 22px;display:flex;justify-content:space-between;align-items:flex-end;background:linear-gradient(135deg,#0a1120 0%,#0D1117 70%)}
.ey{font-family:var(--mono);font-size:9px;font-weight:600;letter-spacing:2px;color:var(--accent);text-transform:uppercase;margin-bottom:6px}
.ct{font-family:var(--mono);font-size:16px;font-weight:600;color:var(--text);line-height:1.2;margin-bottom:3px}
.csub{font-size:11px;color:var(--t3);margin-top:3px}.csub span{color:var(--glt)}
.cmeta{text-align:right;font-family:var(--mono);font-size:9.5px;color:var(--t3);line-height:2}.cmeta strong{color:var(--t2)}
.wrap{padding:16px 40px 40px}
.boundary{border:2px dashed var(--accent);border-radius:10px;padding:12px;margin-bottom:12px}
.blabel{font-family:var(--mono);font-size:8.5px;font-weight:600;color:var(--accent);letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px}
h3{font-family:var(--mono);font-size:11px;font-weight:600;letter-spacing:1px;color:var(--t2);text-transform:uppercase;margin:18px 0 8px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px}
.tag{display:inline-block;font-family:var(--mono);font-size:8px;font-weight:700;padding:2px 7px;border-radius:3px;text-transform:uppercase;letter-spacing:1px;margin-right:4px}
.ok{color:var(--glt);background:rgba(110,231,183,0.1)}.info{color:var(--blue);background:rgba(77,163,255,0.1)}.warn{color:var(--amber);background:rgba(245,158,11,0.1)}.bad{color:var(--red);background:rgba(239,68,68,0.1)}
.flow{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.box{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:8px 14px;font-family:var(--mono);font-size:10px;font-weight:600;color:var(--text)}
.highlight{border-color:var(--accent);color:var(--accent)}
.sub{font-size:10px;color:var(--t3);margin-top:4px;line-height:1.4}
.svc{background:var(--s2);border:1px solid var(--border);border-radius:5px;padding:5px 10px;font-family:var(--mono);font-size:9px;margin:3px 2px;display:inline-block}
.stage{border-radius:8px;padding:12px;margin-bottom:8px;border-left:3px solid var(--accent)}
.stage-bg{background:rgba(110,231,183,0.05);border:1px solid rgba(110,231,183,0.15)}
.metric{font-family:var(--mono);font-size:18px;font-weight:600;color:var(--accent)}
.mlabel{font-size:10px;color:var(--t3);margin-top:2px}
</style></head><body>
<div class="cover">
  <div><div class="ey">AbarVa Reference Patterns · ML Engineering</div><div class="ct">MLOps Pipeline</div><div class="csub">Experiment → Train → Validate → Staging → Production → <span>Feedback Loop</span></div></div>
  <div class="cmeta"><strong>PATTERN</strong> MLOps<br><strong>PLATFORM</strong> Azure ML + MLflow<br><strong>STANDARD</strong> SR 11-7 compliant</div>
</div>
<div class="wrap">
  <h3>Pipeline Stages</h3>
  <div class="stage stage-bg">
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div><div style="font-family:var(--mono);font-size:11px;font-weight:600;color:var(--accent);margin-bottom:4px">1 — Experiment</div><div class="flow"><div class="svc">JupyterLab</div><div class="svc">MLflow Tracking</div><div class="svc">Optuna HPO</div><div class="svc">Feature Store pull</div><div class="svc">Data versioning (DVC)</div></div></div>
      <span class="tag ok">Dev</span>
    </div>
  </div>
  <div style="text-align:center;font-size:16px;color:var(--t3)">↓</div>
  <div class="stage stage-bg">
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div><div style="font-family:var(--mono);font-size:11px;font-weight:600;color:var(--accent);margin-bottom:4px">2 — Training</div><div class="flow"><div class="svc">Azure ML Compute Clusters</div><div class="svc">Distributed training (Ray)</div><div class="svc">GPU/CPU auto-scale</div><div class="svc">Artifact logging</div></div></div>
      <span class="tag info">Automated</span>
    </div>
  </div>
  <div style="text-align:center;font-size:16px;color:var(--t3)">↓</div>
  <div class="stage stage-bg">
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div><div style="font-family:var(--mono);font-size:11px;font-weight:600;color:var(--accent);margin-bottom:4px">3 — Validation &amp; Model Registry</div><div class="flow"><div class="svc">Holdout eval</div><div class="svc">Champion / Challenger</div><div class="svc">Bias &amp; fairness checks</div><div class="svc">MLflow Model Registry</div><div class="svc">SR 11-7 documentation</div></div></div>
      <span class="tag warn">Gate</span>
    </div>
  </div>
  <div style="text-align:center;font-size:16px;color:var(--t3)">↓</div>
  <div class="stage stage-bg">
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div><div style="font-family:var(--mono);font-size:11px;font-weight:600;color:var(--accent);margin-bottom:4px">4 — Staging</div><div class="flow"><div class="svc">Shadow mode scoring</div><div class="svc">A/B traffic split (5%)</div><div class="svc">Latency SLA check</div><div class="svc">Canary deployment</div></div></div>
      <span class="tag warn">Gate</span>
    </div>
  </div>
  <div style="text-align:center;font-size:16px;color:var(--t3)">↓</div>
  <div class="stage" style="background:rgba(110,231,183,0.08);border:1px solid rgba(110,231,183,0.3);border-left:3px solid var(--glt)">
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div><div style="font-family:var(--mono);font-size:11px;font-weight:600;color:var(--glt);margin-bottom:4px">5 — Production</div><div class="flow"><div class="svc">Managed Online Endpoints</div><div class="svc">Batch Inference Jobs</div><div class="svc">Auto-scaling (KEDA)</div><div class="svc">Blue-green deployment</div></div></div>
      <span class="tag ok">Live</span>
    </div>
  </div>
  <h3>Monitoring &amp; Feedback Loop</h3>
  <div class="grid3">
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--red);margin-bottom:6px">Drift Detection</div><div class="sub">PSI / KS test · Feature drift · Prediction drift · Azure ML monitor jobs</div><div style="margin-top:8px"><span class="tag warn">Auto-alert</span></div></div>
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--amber);margin-bottom:6px">Performance Tracking</div><div class="sub">Accuracy · AUC · Latency p99 · Business KPIs · Power BI dashboards</div><div style="margin-top:8px"><span class="tag ok">Tracked</span></div></div>
    <div class="card"><div style="font-family:var(--mono);font-size:10px;font-weight:600;color:var(--accent);margin-bottom:6px">Retraining Trigger</div><div class="sub">Drift threshold breach → ADF pipeline → back to Stage 2 automatically</div><div style="margin-top:8px"><span class="tag info">Automated</span></div></div>
  </div>
  <div class="card" style="margin-top:12px;display:flex;justify-content:space-around;align-items:center;padding:16px;border-color:rgba(110,231,183,0.3)">
    <div style="text-align:center"><div class="metric">&lt;2h</div><div class="mlabel">Train → Prod</div></div>
    <div style="text-align:center"><div class="metric">99.9%</div><div class="mlabel">Endpoint Uptime</div></div>
    <div style="text-align:center"><div class="metric">&lt;50ms</div><div class="mlabel">Inference p99</div></div>
    <div style="text-align:center"><div class="metric">Auto</div><div class="mlabel">Retrain on Drift</div></div>
  </div>
</div></body></html>`
