import {
  CATEGORY_DEFAULT_SENSITIVITY,
  FOUNDATIONAL_CONTRADICTION_RULES,
  legacySeverityFromLabel,
  severityLabelFromStakes,
} from '@/lib/contradictions/foundation';
import type {
  ContradictionCategory,
  ContradictionConfidence,
  ContradictionCreatedBy,
  ContradictionRecord,
  ContradictionSensitivity,
  ContradictionTemporalState,
  FoundationalRuleId,
} from '@/lib/contradictions/types';
import type { TenantKey } from './seed-wave-lib';

export interface SeededContradictionEvidence {
  title: string;
  summary: string;
  evidenceType: string;
  observedAt: string;
  methodologyNotes: string;
  evidenceRole: 'supporting' | 'contextualizing' | 'refuting' | 'resolving';
  temporalRelevance: string;
  sourceDiversity: 'same_source' | 'cross_source' | 'independent_sources';
}

export interface SeededContradictionExample
  extends Omit<ContradictionRecord, 'id' | 'clientId' | 'severity' | 'severityLabel' | 'sensitivity' | 'stakesComponents'> {
  tenant: TenantKey;
  contradictionType: string;
  stakesScore: number;
  confidence: ContradictionConfidence;
  temporalState: ContradictionTemporalState;
  createdBy: ContradictionCreatedBy;
  subcategory: string;
  sensitivity?: ContradictionSensitivity;
  evidence: SeededContradictionEvidence[];
}

function stakeComponentsFor(category: ContradictionCategory, score: number) {
  const base = Math.min(25, Math.max(6, Math.round(score / 4)));
  if (category === 'A_strategy_allocation') {
    return { strategic: base, financial: Math.max(8, base - 6), reputational: Math.max(6, base - 9), regulatory: 6 };
  }
  if (category === 'B_commitment_pace') {
    return { strategic: Math.max(10, base - 2), financial: Math.max(10, base - 1), reputational: Math.max(8, base - 2), regulatory: 8 };
  }
  if (category === 'C_sponsor_behavior') {
    return { strategic: Math.max(8, base - 3), financial: Math.max(6, base - 6), reputational: Math.max(12, base), regulatory: 6 };
  }
  if (category === 'D_budget_priority') {
    return { strategic: Math.max(8, base - 2), financial: Math.max(10, base), reputational: Math.max(6, base - 7), regulatory: 6 };
  }
  return { strategic: Math.max(8, base - 4), financial: Math.max(8, base - 5), reputational: Math.max(10, base - 1), regulatory: Math.max(8, base - 3) };
}

function example(input: SeededContradictionExample): SeededContradictionExample & {
  severityLabel: ReturnType<typeof severityLabelFromStakes>;
  severity: ReturnType<typeof legacySeverityFromLabel>;
  sensitivity: ContradictionSensitivity;
  stakesComponents: ContradictionRecord['stakesComponents'];
} {
  const severityLabel = severityLabelFromStakes(input.stakesScore);
  return {
    ...input,
    severityLabel,
    severity: legacySeverityFromLabel(severityLabel),
    sensitivity: input.sensitivity ?? CATEGORY_DEFAULT_SENSITIVITY[input.category],
    stakesComponents: stakeComponentsFor(input.category, input.stakesScore),
  };
}

export const SEEDED_CONTRADICTION_EXAMPLES = [
  example({
    tenant: 'apex',
    contradictionType: 'strategy_allocation',
    category: 'A_strategy_allocation',
    subcategory: 'capital_inversion',
    temporalState: 'persistent',
    confidence: 'high',
    stakesScore: 72,
    shortTitle: 'Digital commerce is still underfunded relative to lower-ranked efficiency work',
    longDescription:
      'Apex continues to describe digital commerce modernization as a top strategic priority, but the capital envelope still favors lower-ranked operational efficiency work. The pattern has now persisted across four quarters and is constraining fulfillment, conversion, and customer-data progress.',
    sourceCount: 4,
    implicatedPriorityRefs: ['Digital commerce modernization', 'Operational efficiency'],
    implicatedInitiativeRefs: ['Unified Customer Data Platform', 'Contact Center AI Transformation'],
    implicatedPersonNames: ['Daniel Kovač', 'Karel Jensen', 'Evan Soriano'],
    implicatedKpiIds: ['apex_digital_penetration_pct', 'apex_conversion_rate', 'apex_same_day_fulfillment_pct'],
    implicatedExternalEventIds: ['apex_event_analyst_day_2026_q1'],
    relatedPatternIds: ['apex_pattern_customer_data_platform_consolidation', 'apex_pattern_omnichannel_fulfillment_decisioning_gap'],
    recommendedConversationContext:
      'This belongs in a CFO plus customer-and-digital conversation. Either digital modernization is aspirational and should be reset, or capital needs to move with the declared priority.',
    firstDetectedAt: '2026-01-15T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'A-R1',
    createdBy: 'automated',
    surfacingPriority: 91,
    evidence: [
      {
        title: 'FY26 discretionary capital review',
        summary: 'Digital initiatives hold 18% of discretionary capital while operational efficiency work holds 28%.',
        evidenceType: 'budget_review',
        observedAt: '2026-03-31',
        methodologyNotes: 'Finance planning pack reviewed against quarterly allocation summary.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
      {
        title: 'Apex strategic plan 2025-2027',
        summary: 'Digital commerce modernization is named priority #2 with conversion and basket-size targets.',
        evidenceType: 'strategy_document',
        observedAt: '2026-01-12',
        methodologyNotes: 'Board-approved strategic plan artifact.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current plan cycle',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Analyst day transcript',
        summary: 'Leadership reaffirmed digital growth and omnichannel differentiation as a top agenda item.',
        evidenceType: 'external_statement',
        observedAt: '2026-03-12',
        methodologyNotes: 'Public transcript reconciled to internal plan.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'apex',
    contradictionType: 'commitment_pace',
    category: 'B_commitment_pace',
    subcategory: 'promise_vs_trajectory',
    temporalState: 'widening',
    confidence: 'high',
    stakesScore: 76,
    shortTitle: 'Apex reaffirmed digital growth promises that current conversion and loyalty trajectories do not support',
    longDescription:
      'Analyst-day messaging continues to promise meaningful digital and customer-experience gains, but conversion, basket size, and loyalty progression are tracking below the path needed to land those commitments without acceleration.',
    sourceCount: 3,
    implicatedPriorityRefs: ['Digital commerce modernization', 'Loyalty and customer-data modernization'],
    implicatedInitiativeRefs: ['Unified Customer Data Platform'],
    implicatedPersonNames: ['Karel Jensen', 'Daniel Kovač'],
    implicatedKpiIds: ['apex_conversion_rate', 'apex_loyalty_member_spend_premium', 'apex_digital_penetration_pct'],
    implicatedExternalEventIds: ['apex_event_analyst_day_2026_q1'],
    relatedPatternIds: ['apex_pattern_customer_data_platform_consolidation'],
    recommendedConversationContext:
      'This should be raised before the next external milestone. The choice is to accelerate the operating plan, soften the promise, or explicitly acknowledge the ramp profile.',
    firstDetectedAt: '2026-03-15T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'B-R3',
    createdBy: 'automated',
    surfacingPriority: 88,
    evidence: [
      {
        title: 'Digital commerce KPI tracker',
        summary: 'Digital penetration sits at 14% against a 22% target and conversion remains below peer median.',
        evidenceType: 'kpi_tracker',
        observedAt: '2026-04-15',
        methodologyNotes: 'Quarterly digital dashboard snapshot.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Loyalty economics review',
        summary: 'Loyalty uplift is positive but too small to support the promised customer-lifetime-value step change.',
        evidenceType: 'finance_review',
        observedAt: '2026-04-08',
        methodologyNotes: 'Finance + customer analytics workpaper.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
      {
        title: 'Analyst day commitments',
        summary: 'Management framed 2027 digital growth and customer-value gains as already on track.',
        evidenceType: 'external_statement',
        observedAt: '2026-03-12',
        methodologyNotes: 'Public transcript reviewed for quantified commitments.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'apex',
    contradictionType: 'sponsor_behavior',
    category: 'C_sponsor_behavior',
    subcategory: 'calendar_time_decline',
    temporalState: 'widening',
    confidence: 'medium',
    stakesScore: 54,
    shortTitle: 'Customer-data sponsorship energy has faded after the initial Apex launch burst',
    longDescription:
      'The Unified Customer Data Platform remains strategically important, but sponsor time and visible advocacy from the customer organization have tapered relative to the launch quarter. The program team is compensating with more work landing on digital and data leaders.',
    sourceCount: 2,
    implicatedPriorityRefs: ['Loyalty and customer-data modernization'],
    implicatedInitiativeRefs: ['Unified Customer Data Platform'],
    implicatedPersonNames: ['Karel Jensen', 'Evan Soriano'],
    implicatedKpiIds: ['apex_loyalty_member_spend_premium', 'apex_conversion_rate'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['apex_pattern_customer_data_platform_consolidation'],
    recommendedConversationContext:
      'This is a quiet sponsor-alignment conversation, not a broad escalation. Clarify whether Karel still wants to be the named executive face of the platform or whether sponsorship should be explicitly rebalanced.',
    firstDetectedAt: '2026-04-02T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'C-R2',
    createdBy: 'automated',
    surfacingPriority: 63,
    evidence: [
      {
        title: 'Program staffing and escalation log',
        summary: 'Escalations increasingly route through Evan Soriano and the data office rather than the customer organization.',
        evidenceType: 'program_log',
        observedAt: '2026-04-11',
        methodologyNotes: 'Weekly PMO escalation digest.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current month',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Sponsor cadence tracker',
        summary: 'Customer-organization meeting time tagged to the program is down roughly 45% versus the prior 90-day baseline.',
        evidenceType: 'calendar_analytics',
        observedAt: '2026-04-16',
        methodologyNotes: 'Meeting-tag analytics exported by PMO assistant.',
        evidenceRole: 'supporting',
        temporalRelevance: '90-day trend',
        sourceDiversity: 'same_source',
      },
    ],
  }),
  example({
    tenant: 'apex',
    contradictionType: 'budget_priority',
    category: 'D_budget_priority',
    subcategory: 'emerging_priority_capital_gap',
    temporalState: 'persistent',
    confidence: 'medium',
    stakesScore: 49,
    shortTitle: 'Store-associate productivity is being described as an emerging priority without real capital following it',
    longDescription:
      'Apex leadership continues to point to frontline productivity and labor flexibility as the next wave of value creation, yet spend remains concentrated in legacy workflow fixes and small pilots rather than the scaled capability build required for 40K associates.',
    sourceCount: 3,
    implicatedPriorityRefs: ['Store workforce productivity'],
    implicatedInitiativeRefs: ['Store Associate Productivity'],
    implicatedPersonNames: ['Rebecca Tanaka', 'Priya Patel'],
    implicatedKpiIds: ['apex_store_associate_engagement_pct'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['apex_pattern_store_workforce_productivity_and_engagement_gap'],
    recommendedConversationContext:
      'Frame this as a sequencing decision. If frontline productivity is truly a top-three emerging priority, the capital and operating model need to say so.',
    firstDetectedAt: '2026-03-25T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'D-R3',
    createdBy: 'automated',
    surfacingPriority: 58,
    evidence: [
      {
        title: 'Frontline productivity investment tracker',
        summary: 'Only small-pilot funds have moved despite the declared 40K-associate ambition.',
        evidenceType: 'portfolio_tracker',
        observedAt: '2026-04-03',
        methodologyNotes: 'Transformation finance review.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Operating review notes',
        summary: 'COO forum positioned frontline productivity as a material 2026 agenda item.',
        evidenceType: 'meeting_notes',
        observedAt: '2026-03-20',
        methodologyNotes: 'Executive operating review readout.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'apex',
    contradictionType: 'external_internal_messaging',
    category: 'E_external_internal_messaging',
    subcategory: 'performance_claim_gap',
    temporalState: 'persistent',
    confidence: 'high',
    stakesScore: 68,
    shortTitle: 'Frictionless omnichannel messaging overstates the current fulfillment reality',
    longDescription:
      'Apex keeps marketing its omnichannel convenience story aggressively, but internal fulfillment, same-day capacity, and inventory visibility metrics still show a material service gap relative to the claim.',
    sourceCount: 3,
    implicatedPriorityRefs: ['Omnichannel customer experience'],
    implicatedInitiativeRefs: ['Contact Center AI Transformation', 'Unified Customer Data Platform'],
    implicatedPersonNames: ['Karel Jensen', 'Rebecca Tanaka'],
    implicatedKpiIds: ['apex_same_day_fulfillment_pct', 'apex_customer_satisfaction_pct'],
    implicatedExternalEventIds: ['apex_event_analyst_day_2026_q1'],
    relatedPatternIds: ['apex_pattern_omnichannel_fulfillment_decisioning_gap'],
    recommendedConversationContext:
      'Best raised with the customer and operations leads together. The likely paths are to tighten the message, accelerate fulfillment fixes, or explicitly position the capability as in-flight.',
    firstDetectedAt: '2026-02-20T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'E-R2',
    createdBy: 'automated',
    surfacingPriority: 84,
    evidence: [
      {
        title: 'Omnichannel fulfillment dashboard',
        summary: 'Same-day fulfillment remains at 42% versus a peer target above 70%, with inventory visibility lag still unresolved.',
        evidenceType: 'operational_dashboard',
        observedAt: '2026-04-14',
        methodologyNotes: 'Customer operations performance dashboard.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Customer complaint themes',
        summary: 'Fulfillment and pickup issues remain the highest-volume digital complaint category.',
        evidenceType: 'voice_of_customer',
        observedAt: '2026-04-10',
        methodologyNotes: 'Quarterly complaint taxonomy rollup.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
      {
        title: 'Spring omnichannel campaign positioning',
        summary: 'Campaign language describes the experience as seamless and always-on across channels.',
        evidenceType: 'external_statement',
        observedAt: '2026-03-28',
        methodologyNotes: 'Campaign copy audit.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'meridian',
    contradictionType: 'strategy_allocation',
    category: 'A_strategy_allocation',
    subcategory: 'priority_program_orphan',
    temporalState: 'persistent',
    confidence: 'medium',
    stakesScore: 57,
    shortTitle: 'Several Meridian value-based care priorities still lack a single operating program spine',
    longDescription:
      'Meridian continues to name value-based care and specialty-bundle expansion as core strategic priorities, but the work remains split across multiple workstreams with no shared program spine or accountable orchestration model.',
    sourceCount: 2,
    implicatedPriorityRefs: ['Value-based specialty bundles', 'Provider incentive alignment'],
    implicatedInitiativeRefs: ['Value-Based Care 2030'],
    implicatedPersonNames: ['Linda Chen-Winters', 'Dr. Rashid Khoury'],
    implicatedKpiIds: ['meridian_vbc_revenue_pct'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['meridian_pattern_value_based_care_operating_model_fragmentation'],
    recommendedConversationContext:
      'This is a design-for-execution discussion. Meridian may already have the right strategic idea, but the absence of a single operating spine is slowing it down.',
    firstDetectedAt: '2026-02-09T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'A-R3',
    createdBy: 'automated',
    surfacingPriority: 70,
    evidence: [
      {
        title: 'Value-based care workstream map',
        summary: 'Multiple interdependent workstreams exist without a single orchestration office and phase plan.',
        evidenceType: 'program_map',
        observedAt: '2026-04-05',
        methodologyNotes: 'Portfolio review artifact.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Meridian strategic priorities',
        summary: 'Value-based expansion remains named as a high-priority enterprise agenda.',
        evidenceType: 'strategy_document',
        observedAt: '2026-01-18',
        methodologyNotes: 'Annual strategy refresh.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current year',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'meridian',
    contradictionType: 'commitment_pace',
    category: 'B_commitment_pace',
    subcategory: 'public_commitment_gap',
    temporalState: 'widening',
    confidence: 'high',
    stakesScore: 84,
    shortTitle: "Meridian's value-based care commitment is materially ahead of the internal delivery path",
    longDescription:
      'Meridian leadership committed externally to 68% value-based revenue by the end of FY26, while the current internal plan still points closer to 52%. The gap is too large to close without a programmatic acceleration or an explicit reforecast.',
    sourceCount: 4,
    implicatedPriorityRefs: ['Downside risk contract expansion', 'Commercial ACO expansion'],
    implicatedInitiativeRefs: ['Value-Based Care 2030'],
    implicatedPersonNames: ['Linda Chen-Winters', 'Daniel Okeke-Reid', 'Dr. Elena Vasquez'],
    implicatedKpiIds: ['meridian_vbc_revenue_pct'],
    implicatedExternalEventIds: ['meridian_event_q2_earnings_vbc_commitment'],
    relatedPatternIds: ['meridian_pattern_value_based_care_operating_model_fragmentation'],
    recommendedConversationContext:
      'This is a CEO-level choice before the next market-facing milestone: accelerate the plan, reforecast the commitment, or explicitly describe the dependency chain.',
    firstDetectedAt: '2026-03-01T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'B-R1',
    createdBy: 'automated',
    surfacingPriority: 96,
    evidence: [
      {
        title: 'Q2 earnings call transcript',
        summary: 'Leadership committed to 68% value-based revenue by the end of FY26.',
        evidenceType: 'external_statement',
        observedAt: '2026-02-21',
        methodologyNotes: 'Public transcript with quantified commitment.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
      {
        title: 'Internal VBC milestone plan',
        summary: 'Current workstream sequencing supports only 52% by the same deadline.',
        evidenceType: 'program_plan',
        observedAt: '2026-04-02',
        methodologyNotes: 'PMO milestone plan and payer-provider dependency map.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Resource capacity review',
        summary: 'Care management, actuarial, and provider-enablement capacity is not staffed to close the remaining gap.',
        evidenceType: 'staffing_review',
        observedAt: '2026-04-09',
        methodologyNotes: 'Transformation staffing review.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'meridian',
    contradictionType: 'sponsor_behavior',
    category: 'C_sponsor_behavior',
    subcategory: 'communication_absence',
    temporalState: 'persistent',
    confidence: 'medium',
    stakesScore: 52,
    shortTitle: 'Meridian Health Plans is critical to the agenda but not consistently visible as the sponsor voice',
    longDescription:
      "The payer arm is central to Meridian's value-based agenda, yet Linda Chen-Winters has not been the visible sponsor in several recent communications and governance moments, creating ambiguity about who owns the cross-system push.",
    sourceCount: 2,
    implicatedPriorityRefs: ['Commercial ACO expansion', 'Provider incentive alignment'],
    implicatedInitiativeRefs: ['Value-Based Care 2030'],
    implicatedPersonNames: ['Linda Chen-Winters', 'Dr. Rashid Khoury'],
    implicatedKpiIds: ['meridian_vbc_revenue_pct'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['meridian_pattern_value_based_care_operating_model_fragmentation'],
    recommendedConversationContext:
      'Handle this as sponsor-clarity work, not as a public critique. The key question is whether the payer side wants to remain visibly co-equal in the steering narrative.',
    firstDetectedAt: '2026-03-12T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'C-R3',
    createdBy: 'automated',
    surfacingPriority: 60,
    evidence: [
      {
        title: 'Recent steering-pack approvals',
        summary: 'Recent steering artifacts were approved without a payer-side sponsor message or explicit signoff note.',
        evidenceType: 'governance_artifact',
        observedAt: '2026-04-07',
        methodologyNotes: 'Steering committee packet audit.',
        evidenceRole: 'supporting',
        temporalRelevance: 'last 60 days',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Program communications tracker',
        summary: 'No sponsor-signed communication from Meridian Health Plans has gone out in the trailing 120 days.',
        evidenceType: 'communications_log',
        observedAt: '2026-04-15',
        methodologyNotes: 'Communications calendar audit.',
        evidenceRole: 'supporting',
        temporalRelevance: '120 days',
        sourceDiversity: 'same_source',
      },
    ],
  }),
  example({
    tenant: 'meridian',
    contradictionType: 'budget_priority',
    category: 'D_budget_priority',
    subcategory: 'budget_decay',
    temporalState: 'narrowing',
    confidence: 'medium',
    stakesScore: 45,
    shortTitle: 'Digital access remains strategically important but budget share has quietly decayed',
    longDescription:
      'Meridian continues to describe consumer access and portal modernization as a strategic access lever, yet budget share has trended down as clinical initiatives consumed more capital, slowing the digital-access experience improvements the system still talks about.',
    sourceCount: 2,
    implicatedPriorityRefs: ['Unified patient portal evolution', 'Access transformation'],
    implicatedInitiativeRefs: ['Patient access modernization'],
    implicatedPersonNames: ['Katherine Oshima', 'Dr. Marcus Halberstam'],
    implicatedKpiIds: ['meridian_patient_portal_adoption_pct'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['meridian_pattern_access_and_navigation_fragmentation'],
    recommendedConversationContext:
      'This is probably an acknowledged trade-off, but it should be made explicit so the access narrative matches the actual funding posture.',
    firstDetectedAt: '2026-02-27T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'acknowledged',
    detectionRuleId: 'D-R2',
    createdBy: 'automated',
    surfacingPriority: 47,
    evidence: [
      {
        title: 'FY26 portfolio rebalance',
        summary: 'Digital access budget share is down more than 20% from the prior period as clinical AI and VBC work expanded.',
        evidenceType: 'budget_review',
        observedAt: '2026-04-04',
        methodologyNotes: 'CIO capital planning review.',
        evidenceRole: 'supporting',
        temporalRelevance: 'two plan periods',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Access strategy memo',
        summary: 'Portal modernization remains explicitly named in the consumer-access narrative despite the budget compression.',
        evidenceType: 'strategy_document',
        observedAt: '2026-02-01',
        methodologyNotes: 'Consumer access strategy memo.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current year',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'meridian',
    contradictionType: 'external_internal_messaging',
    category: 'E_external_internal_messaging',
    subcategory: 'public_commitment_vs_risk_register',
    temporalState: 'widening',
    confidence: 'high',
    stakesScore: 66,
    shortTitle: 'Access and navigation messaging is ahead of the internal operational risk picture',
    longDescription:
      'Meridian speaks publicly about seamless patient navigation, but internal access work continues to show referral leakage, fragmented scheduling flows, and staffing risks that challenge that promise.',
    sourceCount: 3,
    implicatedPriorityRefs: ['Unified patient portal evolution', 'Access transformation'],
    implicatedInitiativeRefs: ['Patient access modernization'],
    implicatedPersonNames: ['Dr. Marcus Halberstam', 'Katherine Oshima'],
    implicatedKpiIds: ['meridian_referral_leakage_pct', 'meridian_patient_portal_adoption_pct'],
    implicatedExternalEventIds: ['meridian_event_consumer_access_campaign'],
    relatedPatternIds: ['meridian_pattern_access_and_navigation_fragmentation'],
    recommendedConversationContext:
      'Raise this as a trust-and-operating-reality alignment issue. The cleanest path may be to position the access story as a journey rather than an already-solved capability.',
    firstDetectedAt: '2026-03-03T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'E-R3',
    createdBy: 'automated',
    surfacingPriority: 73,
    evidence: [
      {
        title: 'Access risk register',
        summary: 'Referral leakage and ambulatory capacity remain high-probability risks to the access promise.',
        evidenceType: 'risk_register',
        observedAt: '2026-04-12',
        methodologyNotes: 'Access transformation risk log.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Consumer campaign messaging',
        summary: 'Marketing copy frames the Meridian navigation experience as already coordinated and simple.',
        evidenceType: 'external_statement',
        observedAt: '2026-03-17',
        methodologyNotes: 'Campaign review.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'first_capital',
    contradictionType: 'strategy_allocation',
    category: 'A_strategy_allocation',
    subcategory: 'leadership_time_gap',
    temporalState: 'persistent',
    confidence: 'medium',
    stakesScore: 51,
    shortTitle: 'AI productivity is named as a strategic priority without sustained senior time behind it',
    longDescription:
      'First Capital continues to describe AI-enabled productivity as a board-level agenda, but visible senior time still clusters around remediation, branch optimization, and core modernization. The result is a declared priority without enough leadership oxygen.',
    sourceCount: 2,
    implicatedPriorityRefs: ['AI-enabled productivity'],
    implicatedInitiativeRefs: ['AI Platform and Governance Build'],
    implicatedPersonNames: ['Angela Okafor-Hill', 'Ravi Deshmukh', 'Elaine Burakovsky-Park'],
    implicatedKpiIds: ['first_capital_ai_productivity_savings_usd'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['first_capital_pattern_ai_governance_and_platform_fragmentation'],
    recommendedConversationContext:
      'This is less about ambition and more about attention allocation. If AI productivity is top-tier, the calendar should show it.',
    firstDetectedAt: '2026-03-07T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'A-R2',
    createdBy: 'automated',
    surfacingPriority: 55,
    evidence: [
      {
        title: 'Executive calendar tagging',
        summary: 'Leadership time tagged to AI productivity remained under 5% across the trailing 90 days.',
        evidenceType: 'calendar_analytics',
        observedAt: '2026-04-13',
        methodologyNotes: 'Program-office calendar tagging experiment.',
        evidenceRole: 'supporting',
        temporalRelevance: '90 days',
        sourceDiversity: 'same_source',
      },
      {
        title: 'Board technology committee framing',
        summary: 'AI productivity remains named as a growth and efficiency priority in board materials.',
        evidenceType: 'board_material',
        observedAt: '2026-02-22',
        methodologyNotes: 'Committee packet review.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'first_capital',
    contradictionType: 'commitment_pace',
    category: 'B_commitment_pace',
    subcategory: 'board_timeline_slip',
    temporalState: 'widening',
    confidence: 'high',
    stakesScore: 79,
    shortTitle: 'Board expectations on AML remediation remain ahead of the actual program pace',
    longDescription:
      'The BSA/AML remediation program remains the defining operating risk at First Capital. Board commitments and regulator-facing timelines still imply a cleaner trajectory than the current platform, case-management, and staffing plan support.',
    sourceCount: 3,
    implicatedPriorityRefs: ['BSA/AML remediation and infrastructure upgrade'],
    implicatedInitiativeRefs: ['BSA/AML Remediation Program'],
    implicatedPersonNames: ['Marcus Blythe', 'Dr. Vikram Shah', 'Elaine Burakovsky-Park'],
    implicatedKpiIds: ['first_capital_aml_alert_backlog'],
    implicatedExternalEventIds: ['first_capital_event_regulatory_update_q1'],
    relatedPatternIds: ['first_capital_pattern_bsa_aml_operating_model_fragmentation'],
    recommendedConversationContext:
      'This is a board-and-regulator narrative issue. The program either needs more pace and operating muscle or a more candid timeline reset.',
    firstDetectedAt: '2026-03-14T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'B-R2',
    createdBy: 'automated',
    surfacingPriority: 90,
    evidence: [
      {
        title: 'Board risk committee materials',
        summary: 'The board-facing plan still implies a faster trajectory than the PMO schedule shows.',
        evidenceType: 'board_material',
        observedAt: '2026-03-26',
        methodologyNotes: 'Committee packet versus PMO plan comparison.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'PMO dependency tracker',
        summary: 'Case-management, data-quality, and staffing dependencies are still slipping the remediation path past the committed window.',
        evidenceType: 'program_plan',
        observedAt: '2026-04-11',
        methodologyNotes: 'PMO dependency log.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'first_capital',
    contradictionType: 'sponsor_behavior',
    category: 'C_sponsor_behavior',
    subcategory: 'steering_absence',
    temporalState: 'widening',
    confidence: 'medium',
    stakesScore: 58,
    shortTitle: 'Declared AML sponsor attendance is too thin for the risk profile of the program',
    longDescription:
      'Marcus Blythe remains the named executive sponsor for BSA/AML modernization, but attendance and visible leadership cadence have fallen below what the program risk profile now requires. The team is increasingly orienting around legal and risk leaders instead.',
    sourceCount: 3,
    implicatedPriorityRefs: ['BSA/AML remediation and infrastructure upgrade'],
    implicatedInitiativeRefs: ['BSA/AML Remediation Program'],
    implicatedPersonNames: ['Marcus Blythe', 'Dr. Vikram Shah', 'Diana Aguilar-Reyes'],
    implicatedKpiIds: ['first_capital_aml_alert_backlog'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['first_capital_pattern_bsa_aml_operating_model_fragmentation'],
    recommendedConversationContext:
      'This is a direct sponsor-structure conversation. Options are recommit, formally reassign, or create a more explicit dual-sponsor operating model.',
    firstDetectedAt: '2026-04-04T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'C-R1',
    createdBy: 'automated',
    surfacingPriority: 72,
    evidence: [
      {
        title: 'Steering attendance log',
        summary: 'The declared sponsor attended only 2 of the last 6 scheduled steering committee meetings.',
        evidenceType: 'governance_artifact',
        observedAt: '2026-04-18',
        methodologyNotes: 'Steering calendar plus minutes reconciliation.',
        evidenceRole: 'supporting',
        temporalRelevance: 'last 6 meetings',
        sourceDiversity: 'same_source',
      },
      {
        title: 'Program escalation routing',
        summary: 'Escalations are increasingly routed through legal and enterprise risk rather than compliance.',
        evidenceType: 'program_log',
        observedAt: '2026-04-15',
        methodologyNotes: 'Escalation tracker review.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current month',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Sponsor communications review',
        summary: 'No recent signed communication from the declared sponsor exists for the program.',
        evidenceType: 'communications_log',
        observedAt: '2026-04-15',
        methodologyNotes: 'Program communications audit.',
        evidenceRole: 'contextualizing',
        temporalRelevance: '120 days',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'first_capital',
    contradictionType: 'budget_priority',
    category: 'D_budget_priority',
    subcategory: 'top_priority_budget_inversion',
    temporalState: 'persistent',
    confidence: 'high',
    stakesScore: 67,
    shortTitle: 'Remediation remains top-two in rhetoric but not in how capital is actually allocated',
    longDescription:
      'First Capital continues to describe BSA/AML remediation as one of its highest-stakes enterprise priorities, yet some lower-ranked growth and experience initiatives still have a cleaner funding path. That inversion is becoming visible to the program teams.',
    sourceCount: 3,
    implicatedPriorityRefs: ['BSA/AML remediation and infrastructure upgrade', 'Integrated digital banking platform'],
    implicatedInitiativeRefs: ['BSA/AML Remediation Program', 'Digital onboarding modernization'],
    implicatedPersonNames: ['Elaine Burakovsky-Park', 'Marcus Blythe', 'Angela Okafor-Hill'],
    implicatedKpiIds: ['first_capital_aml_alert_backlog'],
    implicatedExternalEventIds: [],
    relatedPatternIds: ['first_capital_pattern_bsa_aml_operating_model_fragmentation'],
    recommendedConversationContext:
      'This is a finance + compliance alignment conversation. If remediation is truly top-tier, funding should stop signaling a different reality.',
    firstDetectedAt: '2026-03-19T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'D-R1',
    createdBy: 'automated',
    surfacingPriority: 77,
    evidence: [
      {
        title: 'FY26 capital allocation review',
        summary: 'Some growth-focused digital work remains better funded than the highest-risk remediation priorities.',
        evidenceType: 'budget_review',
        observedAt: '2026-04-02',
        methodologyNotes: 'Capital committee review.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current plan year',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'Risk committee chartering notes',
        summary: 'AML remediation is still framed as a top enterprise obligation in leadership materials.',
        evidenceType: 'board_material',
        observedAt: '2026-02-28',
        methodologyNotes: 'Risk committee packet review.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current year',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
  example({
    tenant: 'first_capital',
    contradictionType: 'external_internal_messaging',
    category: 'E_external_internal_messaging',
    subcategory: 'commitment_vs_risk_register',
    temporalState: 'persistent',
    confidence: 'high',
    stakesScore: 71,
    shortTitle: 'Public confidence language on compliance modernization is ahead of the internal risk register',
    longDescription:
      "First Capital's external language suggests compliance modernization is steadily moving toward normalization, but the internal risk register still shows several high-probability blockers across data quality, tuning, and case operations.",
    sourceCount: 3,
    implicatedPriorityRefs: ['BSA/AML remediation and infrastructure upgrade'],
    implicatedInitiativeRefs: ['BSA/AML Remediation Program'],
    implicatedPersonNames: ['Marcus Blythe', 'Dr. Vikram Shah', 'Elaine Burakovsky-Park'],
    implicatedKpiIds: ['first_capital_aml_alert_backlog'],
    implicatedExternalEventIds: ['first_capital_event_regulatory_update_q1'],
    relatedPatternIds: ['first_capital_pattern_bsa_aml_operating_model_fragmentation'],
    recommendedConversationContext:
      'Use careful framing here. The issue is not whether progress exists, but whether the external message implies a steadiness the current risk register does not support.',
    firstDetectedAt: '2026-03-10T00:00:00Z',
    lastRefreshedAt: '2026-04-21T00:00:00Z',
    resolutionState: 'open',
    detectionRuleId: 'E-R3',
    createdBy: 'automated',
    surfacingPriority: 82,
    evidence: [
      {
        title: 'Internal remediation risk register',
        summary: 'High-probability risks remain open across customer risk rating, tuning quality, and staffing continuity.',
        evidenceType: 'risk_register',
        observedAt: '2026-04-17',
        methodologyNotes: 'Remediation PMO risk log.',
        evidenceRole: 'supporting',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'cross_source',
      },
      {
        title: 'External compliance update',
        summary: 'Public messaging describes the modernization trajectory as steadily de-risking.',
        evidenceType: 'external_statement',
        observedAt: '2026-03-29',
        methodologyNotes: 'Investor and regulator-facing summary review.',
        evidenceRole: 'contextualizing',
        temporalRelevance: 'current quarter',
        sourceDiversity: 'independent_sources',
      },
    ],
  }),
] as const;

export function getSeededExamplesForTenant(tenant: TenantKey) {
  return SEEDED_CONTRADICTION_EXAMPLES.filter((example) => example.tenant === tenant);
}

export function getSeededExamplesForRule(ruleId: FoundationalRuleId) {
  return SEEDED_CONTRADICTION_EXAMPLES.filter((example) => example.detectionRuleId === ruleId);
}

export function getFoundationalRuleDefinition(ruleId: FoundationalRuleId) {
  return FOUNDATIONAL_CONTRADICTION_RULES.find((rule) => rule.id === ruleId) ?? null;
}
