interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const MEDTECH_DOM02_EU_MDR_PART5_PATTERNS: PatternSeed[] = [

  // ── mdr-conformity-assessment (M470–M481) ──────────────────────────────────

  {
    code: 'M470',
    name: 'Class IIb Device Conformity Assessment Route Selected Without Notified Body Review of Clinical Evaluation',
    description: 'NorthStar Clinical selects the Article 52 quality management system route for a Class IIb active implantable device without requiring the notified body to review the clinical evaluation report, violating the Annex IX Chapter II requirement that the NB assess clinical evaluation documentation for Class IIb devices.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['conformity-assessment', 'class-iib', 'notified-body', 'article-52', 'annex-ix', 'clinical-evaluation'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'Conformity assessment route selected without notified body clinical evaluation review for Class IIb device',
      regulatoryHook: 'EU MDR Article 52(4); Annex IX Chapter II Section 5.1; MDCG 2020-1 clinical evaluation guidance',
      detectionMethod: 'Technical documentation audit comparing assessment route against device classification and NB scope of designation',
      remediationPath: 'Re-engage notified body to conduct clinical evaluation review; update QMS records; reissue CE certificate with correct route documentation',
      estimatedCost: '€180K–€520K',
      timeToRemediate: '8–14 months',
      industryBenchmark: '47% of Class IIb manufacturers have documentation gaps in NB clinical evaluation review records',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M471',
    name: 'Class III Device Assessed Under Annex X Type Examination Without Complete Design Dossier',
    description: 'NorthStar Clinical submits an incomplete design dossier for EU Type Examination under Annex X, omitting risk management documentation and software lifecycle records, causing the notified body to issue a deficiency notice that suspends the certification timeline.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['annex-x', 'type-examination', 'class-iii', 'design-dossier', 'article-52'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'Incomplete design dossier submitted for Annex X type examination, missing risk management and software records',
      regulatoryHook: 'EU MDR Article 52(3); Annex X Section 3; Annex II technical documentation requirements',
      detectionMethod: 'Pre-submission dossier completeness checklist against Annex X Section 3 and Annex II minimum content requirements',
      remediationPath: 'Compile complete risk management file and software lifecycle documentation; resubmit to notified body; assign dedicated regulatory lead',
      estimatedCost: '€90K–€310K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '39% of Class III submissions receive design dossier deficiency notices on first review',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M472',
    name: 'Legacy Device Transitioned to MDR Without Selecting a Compliant Conformity Assessment Route Under Article 52',
    description: 'NorthStar Clinical transitions a legacy Class IIa device from MDD to MDR by continuing the existing QMS certification without formally selecting and documenting the applicable Article 52 conformity assessment route, creating a compliance gap that competent authorities identify during post-market surveillance inspections.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['mdd-to-mdr', 'legacy-device', 'article-52', 'conformity-assessment-route', 'class-iia'],
    failure_rate_pct: 55.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'MDR conformity assessment route not formally documented during MDD-to-MDR transition for Class IIa device',
      regulatoryHook: 'EU MDR Article 52; Article 120 transitional provisions; MDCG 2022-4 transition guidance',
      detectionMethod: 'Regulatory file review confirming explicit Article 52 route selection and NB certificate validity under MDR',
      remediationPath: 'Document Article 52 route selection rationale; update QMS certificates with NB; notify competent authority if required',
      estimatedCost: '€40K–€150K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '52% of legacy device transitions lack explicit Article 52 route selection documentation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M473',
    name: 'Notified Body Certificate Scope Does Not Cover Device Intended Purpose Leading to Assessment Gap',
    description: 'NorthStar Clinical expands a device\'s intended purpose to include a new clinical indication without verifying that the notified body\'s designation scope covers the new indication, resulting in an out-of-scope certification that invalidates CE marking for the expanded use.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['nb-designation-scope', 'intended-purpose', 'article-52', 'ce-marking', 'class-iii'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'NB designation scope does not cover expanded intended purpose, invalidating CE certificate for new indication',
      regulatoryHook: 'EU MDR Article 52; Article 42 NB designation; Annex VII NB designation criteria',
      detectionMethod: 'Cross-reference NB NANDO designation codes against device intended purpose classification on each label revision',
      remediationPath: 'Identify NB with correct designation scope; transfer certification or restrict intended purpose on label; update technical documentation',
      estimatedCost: '€120K–€380K',
      timeToRemediate: '6–18 months',
      industryBenchmark: '29% of CE certificates are presented to competent authorities with scope-intention mismatches',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M474',
    name: 'Software as a Medical Device Classified Below Intended Risk Class Avoiding Article 52 NB Involvement',
    description: 'NorthStar Clinical classifies a SaMD clinical decision support tool as Class I using Rule 11 without applying the MDR software classification criteria correctly, thereby avoiding required notified body involvement under Article 52 and placing a higher-risk device on the market without conformity assessment.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['samd', 'rule-11', 'software-classification', 'article-52', 'class-i-self-declaration'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'SaMD under-classified as Class I to avoid NB conformity assessment, violating Rule 11 classification criteria',
      regulatoryHook: 'EU MDR Annex VIII Rule 11; Article 52(7) Class I self-declaration limits; MDCG 2019-11 SaMD guidance',
      detectionMethod: 'Independent Rule 11 classification review by regulatory counsel against MDCG 2019-11 decision tree',
      remediationPath: 'Reclassify SaMD; engage notified body for Annex IX or Annex X assessment; withdraw self-declaration; update EUDAMED registration',
      estimatedCost: '€200K–€650K',
      timeToRemediate: '10–20 months',
      industryBenchmark: '33% of SaMD products placed on EU market are classified at lower risk class than MDCG guidance supports',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-driven clinical decision support SaMD under-classified avoiding NB scrutiny of AI model validation',
    },
  },
  {
    code: 'M475',
    name: 'Conformity Assessment Procedure Changed Without Notifying Notified Body of Significant Design Change',
    description: 'NorthStar Clinical modifies a certified device\'s core component material without notifying the notified body, circumventing the Annex IX Chapter II change notification obligation and continuing to market the device under an invalidated certificate.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['significant-change', 'nb-notification', 'annex-ix', 'design-change', 'article-52'],
    failure_rate_pct: 71.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'Significant design change implemented without NB notification, invalidating conformity assessment certificate',
      regulatoryHook: 'EU MDR Annex IX Chapter II Section 4.10; MDCG 2020-3 significant change guidance; Article 55',
      detectionMethod: 'Change control log audit mapping design changes against MDCG 2020-3 significance criteria and NB notification records',
      remediationPath: 'Notify NB retroactively; submit change assessment dossier; suspend distribution if NB determines certificate invalid pending review',
      estimatedCost: '€150K–€480K',
      timeToRemediate: '5–12 months',
      industryBenchmark: '44% of manufacturers have undocumented significant changes not submitted to NBs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M476',
    name: 'Annex XI Part A Production Quality Assurance Certificate Applied to Device Requiring Annex IX Full QMS',
    description: 'NorthStar Clinical applies a production quality assurance certificate under Annex XI Part A to a Class IIb implantable device that requires a full quality management system assessment under Annex IX, using a lower-scope conformity assessment route that does not satisfy Article 52(4) requirements.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['annex-xi', 'annex-ix', 'production-qas', 'class-iib-implantable', 'article-52'],
    failure_rate_pct: 43.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'Annex XI Part A production QAS applied to Class IIb implantable requiring full Annex IX QMS assessment',
      regulatoryHook: 'EU MDR Article 52(4); Annex IX; Annex XI Part A scope limitations; Article 1(6) implantable device definition',
      detectionMethod: 'Certificate and device classification matrix review confirming route eligibility for each device and class combination',
      remediationPath: 'Engage NB for full Annex IX QMS assessment; surrender Annex XI certificate; update DoC route reference',
      estimatedCost: '€80K–€280K',
      timeToRemediate: '6–15 months',
      industryBenchmark: '18% of implantable device manufacturers have certificate-route mismatches',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M477',
    name: 'Conformity Assessment Technical Documentation Does Not Map GSPRs to Objective Evidence',
    description: 'NorthStar Clinical\'s technical documentation lists General Safety and Performance Requirements from Annex I without mapping each GSPR to specific verification and validation evidence, creating a documentation gap that notified bodies cite as a critical finding during Annex IX audits.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['gspr', 'annex-i', 'technical-documentation', 'annex-ix', 'conformity-assessment'],
    failure_rate_pct: 74.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'GSPR checklist present in technical documentation but not mapped to objective verification and validation evidence',
      regulatoryHook: 'EU MDR Annex I GSPRs; Annex II Section 4 technical documentation; Annex IX Chapter II Section 5',
      detectionMethod: 'Technical documentation traceability matrix audit linking each GSPR to test reports, clinical data, and risk management outputs',
      remediationPath: 'Build GSPR traceability matrix; compile evidence for each requirement; update technical documentation before next NB audit',
      estimatedCost: '€60K–€220K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '68% of first-time MDR technical documentation submissions have incomplete GSPR traceability',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M478',
    name: 'Multiple Devices Covered Under a Single Conformity Assessment Certificate Without Device-Specific Technical Files',
    description: 'NorthStar Clinical groups a device family under one NB certificate without maintaining device-specific technical documentation for each variant, failing the Annex II requirement that each device covered by a certificate have its own complete technical documentation.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['device-family', 'certificate-coverage', 'annex-ii', 'technical-documentation', 'article-52'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'Device family grouped under single certificate without device-specific technical files for each variant',
      regulatoryHook: 'EU MDR Annex II technical documentation per device; Annex IX Chapter II Section 2; Article 10(4)',
      detectionMethod: 'Certificate scope versus technical documentation inventory cross-check confirming per-variant files exist',
      remediationPath: 'Create individual technical documentation packages for each device variant; align with NB on certificate amendment',
      estimatedCost: '€70K–€240K',
      timeToRemediate: '4–10 months',
      industryBenchmark: '35% of device families have at least one variant without a complete standalone technical file',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M479',
    name: 'Conformity Assessment Completed Before Clinical Evaluation Report Updated to MDR Annex XIV Standard',
    description: 'NorthStar Clinical completes a conformity assessment procedure with a clinical evaluation report written to the superseded MEDDEV 2.7.1 Rev 3 standard rather than MDR Annex XIV, resulting in a technically deficient CER that does not meet the NB\'s assessment criteria.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['clinical-evaluation-report', 'annex-xiv', 'meddev-2.7.1', 'conformity-assessment', 'nb-audit'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'CER written to obsolete MEDDEV 2.7.1 Rev 3 standard, not meeting MDR Annex XIV requirements for NB assessment',
      regulatoryHook: 'EU MDR Annex XIV clinical evaluation; MDCG 2020-1; Article 61 clinical evaluation obligations',
      detectionMethod: 'CER template and content review against Annex XIV Part A checklist and MDCG 2020-1 guidance requirements',
      remediationPath: 'Rewrite CER to Annex XIV and MDCG 2020-1 requirements; commission independent clinical evaluation review; resubmit to NB',
      estimatedCost: '€80K–€300K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '55% of clinical evaluation reports submitted in 2024 require major revision for Annex XIV compliance',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M480',
    name: 'Notified Body Certification Suspended Due to QMS Non-Conformity Found During Unannounced Audit',
    description: 'NorthStar Clinical\'s notified body conducts an unannounced factory audit and finds that complaint handling procedures do not meet Annex IX QMS requirements, triggering certificate suspension and requiring remediation before device distribution can continue.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['unannounced-audit', 'certificate-suspension', 'qms', 'annex-ix', 'complaint-handling'],
    failure_rate_pct: 38.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'QMS complaint handling non-conformity found in unannounced NB audit triggering certificate suspension',
      regulatoryHook: 'EU MDR Annex IX Chapter I; Annex VII Section 3.4 unannounced audit obligations; Article 44',
      detectionMethod: 'Internal mock unannounced audit programme against Annex IX QMS criteria and complaint handling SOPs',
      remediationPath: 'Issue CAPA for complaint handling SOP gaps; implement corrective measures; request NB certificate reinstatement audit',
      estimatedCost: '€100K–€400K',
      timeToRemediate: '3–9 months',
      industryBenchmark: '22% of NBs issued certificate suspensions following unannounced audits in 2023–2024',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M481',
    name: 'Custom Device Exemption Claimed for Device That Meets Serial Production Threshold Under Article 52',
    description: 'NorthStar Clinical uses the custom device exemption to avoid conformity assessment for an orthopedic implant produced in batches exceeding the custom device volume threshold, misapplying Article 52(7)(b) and placing a device on the market without required NB involvement.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['custom-device-exemption', 'article-52', 'serial-production', 'class-iii-implant', 'nb-involvement'],
    failure_rate_pct: 45.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'mdr-conformity-assessment',
    data: {
      failureMode: 'Custom device exemption applied to device in serial production, invalidating Article 52(7)(b) basis for avoiding NB assessment',
      regulatoryHook: 'EU MDR Article 52(7)(b); Article 1(7) custom device definition; Annex XIII custom device requirements',
      detectionMethod: 'Production volume audit comparing actual batch sizes against custom device definition thresholds in MDR Article 1(7)',
      remediationPath: 'Withdraw custom device designation; engage NB for retrospective conformity assessment; update EUDAMED registration',
      estimatedCost: '€130K–€420K',
      timeToRemediate: '7–16 months',
      industryBenchmark: '14% of devices registered as custom devices exceed the production volume consistent with custom device status',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── declaration-of-conformity (M482–M493) ──────────────────────────────────

  {
    code: 'M482',
    name: 'Declaration of Conformity Omits Mandatory Article 19 Content Including All Applicable Directives',
    description: 'NorthStar Clinical issues a DoC that references EU MDR 2017/745 but omits the device\'s applicable harmonised standards, the name and address of the notified body, and the certificate number, violating all mandatory content requirements under Article 19 and Annex IV.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['declaration-of-conformity', 'article-19', 'annex-iv', 'harmonised-standards', 'nb-certificate'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC missing NB name, certificate number, and harmonised standard references required by Article 19 and Annex IV',
      regulatoryHook: 'EU MDR Article 19; Annex IV Declaration of Conformity content requirements; Article 10(8)',
      detectionMethod: 'DoC template audit against Annex IV checklist for all 17 mandatory content elements',
      remediationPath: 'Reissue DoC with all Annex IV mandatory elements; update QMS document control; communicate revised DoC to economic operators',
      estimatedCost: '€15K–€60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '63% of MDR DoCs reviewed in market surveillance contain at least one Annex IV content omission',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M483',
    name: 'Declaration of Conformity Signed by Person Without Delegated Authority Under Article 15',
    description: 'NorthStar Clinical\'s DoC is signed by a quality manager rather than the Person Responsible for Regulatory Compliance or a person with delegated authority under Article 15, creating a documentation deficiency that competent authorities flag during market surveillance.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-signatory', 'article-15', 'prrc', 'declaration-of-conformity', 'delegation'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC signed by quality manager without PRRC delegation, not meeting Article 15 signatory authority requirements',
      regulatoryHook: 'EU MDR Article 15 PRRC obligations; Article 19(2) DoC signatory; Annex IV Section 11',
      detectionMethod: 'DoC signatory verification against PRRC appointment records and delegation of authority matrix',
      remediationPath: 'Reissue DoC with PRRC signature or documented delegation; update signatory authority procedure; retrain QMS team',
      estimatedCost: '€10K–€40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '38% of SME medical device manufacturers have DoC signatory gaps relative to Article 15 requirements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M484',
    name: 'Single Declaration of Conformity Covering Multiple Devices of Different Risk Classes Without Separate NB Certificates',
    description: 'NorthStar Clinical issues one DoC covering both Class I and Class IIa devices in a product family, but the Class IIa devices require NB-certified conformity routes while the DoC references only a self-declaration, misrepresenting the conformity assessment basis for higher-class devices.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-multi-device', 'class-iia', 'self-declaration', 'nb-certificate', 'article-19'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'Single DoC covers mixed-class devices with self-declaration basis incorrectly applied to Class IIa variants requiring NB certification',
      regulatoryHook: 'EU MDR Article 19; Article 52 route requirements by class; Annex IV Section 4 certificate references',
      detectionMethod: 'DoC-to-certificate mapping audit for each device variant confirming correct conformity assessment route cited',
      remediationPath: 'Issue separate DoCs per conformity assessment route; obtain NB certificates for Class IIa variants; update EUDAMED records',
      estimatedCost: '€50K–€180K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '27% of device family DoCs incorrectly consolidate mixed-class devices under a single certificate reference',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M485',
    name: 'Declaration of Conformity Not Updated Following Significant Change That Alters Conformity Assessment Basis',
    description: 'NorthStar Clinical modifies a device\'s manufacturing process in a way the notified body confirms is significant, but the DoC continues to reference the pre-change certificate and conformity assessment route without reflecting the updated certification status.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-update', 'significant-change', 'certificate-update', 'article-19', 'annex-iv'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC not updated after significant manufacturing change alters NB certificate scope and assessment basis',
      regulatoryHook: 'EU MDR Article 19; Annex IV; Annex IX Chapter II Section 4.10 change management; MDCG 2020-3',
      detectionMethod: 'Change control log cross-reference with DoC version history confirming document update after each significant change',
      remediationPath: 'Reissue DoC reflecting updated NB certificate; update EUDAMED; communicate new DoC version to distributors and importers',
      estimatedCost: '€20K–€80K',
      timeToRemediate: '1–4 months',
      industryBenchmark: '49% of DoCs reviewed post-significant-change do not reflect updated certificate references',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M486',
    name: 'Declaration of Conformity References Withdrawn Harmonised Standard Without Alternative Compliance Demonstration',
    description: 'NorthStar Clinical\'s DoC continues to cite a harmonised standard whose publication in the Official Journal has been withdrawn, without providing an alternative means of demonstrating conformity to the relevant GSPR, undermining the presumption of conformity basis for the declaration.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['harmonised-standards', 'oj-withdrawal', 'gspr', 'doc-currency', 'annex-iv'],
    failure_rate_pct: 46.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC cites withdrawn harmonised standard without alternative GSPR compliance demonstration',
      regulatoryHook: 'EU MDR Article 8 harmonised standards; Annex IV; Commission implementing regulations on standard publication',
      detectionMethod: 'Annual harmonised standard currency review comparing DoC-cited standards against current OJ list',
      remediationPath: 'Identify successor standard or alternative test method; update technical documentation; reissue DoC with current standard references',
      estimatedCost: '€25K–€90K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '31% of DoCs reference at least one harmonised standard no longer listed in the current OJ',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M487',
    name: 'DoC Issued for Device Placed on Market Before NB Certificate Effective Date',
    description: 'NorthStar Clinical distributes devices and issues DoCs bearing dates prior to the effective date of the notified body certificate, creating a period during which devices were placed on the EU market without a valid conformity assessment under Article 52.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-date', 'nb-certificate-date', 'placement-on-market', 'article-52', 'article-19'],
    failure_rate_pct: 40.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'Device placed on market with DoC predating NB certificate effective date, indicating market placement without valid conformity assessment',
      regulatoryHook: 'EU MDR Article 52; Article 19; Annex IV Section 9 certificate reference; Article 10(1) obligations',
      detectionMethod: 'DoC date versus NB certificate issuance date audit for each device batch and lot release record',
      remediationPath: 'Identify affected lots; assess recall necessity with legal counsel; reissue DoCs with correct dates; notify competent authority',
      estimatedCost: '€60K–€250K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '16% of market surveillance investigations involving DoCs identify date discrepancies relative to NB certificate validity',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M488',
    name: 'DoC Does Not List All Applicable EU Regulations and Directives Including IVDR Where Co-Indicated',
    description: 'NorthStar Clinical issues a DoC for a combination product that has both a medical device component and an in vitro diagnostic component, citing only EU MDR without referencing applicable EU IVDR requirements, creating a declaration that does not accurately represent the full regulatory framework governing the product.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['combination-product', 'ivdr', 'annex-iv', 'doc-completeness', 'article-19'],
    failure_rate_pct: 44.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC omits IVDR citation for combination product with IVD component, creating incomplete regulatory declaration',
      regulatoryHook: 'EU MDR Article 19; EU IVDR 2017/746 Article 17; Annex IV applicable legislation scope',
      detectionMethod: 'Product classification review identifying combination products requiring dual-regulation DoC references',
      remediationPath: 'Reissue DoC citing both MDR and IVDR; confirm notified body scope covers both regulations; update EUDAMED registration',
      estimatedCost: '€30K–€110K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '22% of combination device DoCs omit one applicable regulation from the declaration',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M489',
    name: 'Authorised Representative Issues DoC Instead of Manufacturer in Violation of Article 19',
    description: 'NorthStar Clinical\'s EU Authorised Representative issues the Declaration of Conformity on the manufacturer\'s behalf without a specific written mandate, misrepresenting the signatory authority and violating Article 19 which requires the manufacturer to draw up and sign the DoC.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['authorised-representative', 'doc-signatory', 'article-19', 'article-11', 'manufacturer-obligation'],
    failure_rate_pct: 38.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'AR issues DoC without written manufacturer mandate, misrepresenting signatory authority under Article 19',
      regulatoryHook: 'EU MDR Article 19(1) manufacturer obligation; Article 11 AR obligations; Annex IV Section 11',
      detectionMethod: 'DoC signatory chain review confirming manufacturer signature and AR mandate documentation where applicable',
      remediationPath: 'Reissue DoC signed by manufacturer; document AR mandate clearly; update AR agreement with signatory authority scope',
      estimatedCost: '€10K–€35K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '19% of non-EU manufacturers have AR-signed DoCs without adequate written manufacturer delegation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M490',
    name: 'DoC Retained for Less Than MDR-Required 10 Years Following Last Device Manufacture Date',
    description: 'NorthStar Clinical\'s document retention policy specifies a 7-year retention period for Declarations of Conformity, below the 10-year minimum required by Article 10(8), creating a compliance gap when competent authorities request historical DoCs for market surveillance investigations.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-retention', 'article-10', 'record-keeping', '10-year-retention', 'market-surveillance'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC retention policy specifies 7 years, below Article 10(8) minimum 10-year retention requirement',
      regulatoryHook: 'EU MDR Article 10(8) document retention; Article 19 DoC; Annex IV',
      detectionMethod: 'QMS document retention policy audit comparing specified retention periods against Article 10(8) requirements for each document type',
      remediationPath: 'Update document retention policy to 10 years minimum for DoCs and technical documentation; archive affected records; retrain QMS team',
      estimatedCost: '€15K–€50K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of SME medical device manufacturers have DoC retention policies below the MDR 10-year minimum',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M491',
    name: 'DoC Issued in Language Not Accepted by Member State Where Device Is Placed on Market',
    description: 'NorthStar Clinical distributes a DoC only in English to a Member State that requires a national language translation, violating the labelling and documentation language requirements that several EU competent authorities enforce under national implementing measures.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-language', 'member-state-requirements', 'translation', 'article-10', 'national-language'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'DoC not translated into required member state language, blocking competent authority review and market access',
      regulatoryHook: 'EU MDR Article 10(11) language requirements; Article 19; national law implementing EU language requirements',
      detectionMethod: 'Market-by-market language requirement matrix cross-referenced against DoC language version availability',
      remediationPath: 'Commission certified DoC translations for each target member state; implement language requirement tracking in QMS',
      estimatedCost: '€5K–€30K per language',
      timeToRemediate: '1–2 months',
      industryBenchmark: '48% of non-EU manufacturers distributing in multiple EU markets have DoC language gaps for at least one member state',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M492',
    name: 'DoC for Class I Sterile Device Does Not Reference Annex IX or Annex XI Sterility Conformity Route',
    description: 'NorthStar Clinical issues a Class I sterile device DoC citing only a self-declaration without referencing the Annex IX or Annex XI conformity assessment route required for the sterility aspect of Class I sterile devices under Article 52(7)(a), creating a documentation gap that invalidates CE marking for the sterility characteristic.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['class-i-sterile', 'article-52', 'annex-xi', 'doc-sterility', 'conformity-assessment'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'Class I sterile device DoC omits NB certificate reference for sterility aspect required under Article 52(7)(a)',
      regulatoryHook: 'EU MDR Article 52(7)(a); Annex IX or Annex XI sterility route; Annex IV Section 4',
      detectionMethod: 'Class I sterile device DoC audit confirming Annex IX/XI certificate reference for sterility alongside self-declaration for other aspects',
      remediationPath: 'Engage NB for Annex XI sterility assessment; obtain certificate; reissue DoC with dual conformity route references',
      estimatedCost: '€40K–€160K',
      timeToRemediate: '4–10 months',
      industryBenchmark: '34% of Class I sterile device DoCs lack the required NB certificate reference for sterility conformity',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M493',
    name: 'Economic Operator Alters DoC Content Without Manufacturer Authorization in Violation of Article 16',
    description: 'NorthStar Clinical\'s EU distributor modifies the Declaration of Conformity to add their own company name as a co-manufacturer without written authorization from the manufacturer, violating Article 16 obligations and creating an invalid DoC in circulation.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['doc-alteration', 'article-16', 'distributor-obligation', 'economic-operator', 'article-19'],
    failure_rate_pct: 39.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'declaration-of-conformity',
    data: {
      failureMode: 'Distributor alters DoC without manufacturer written authorization, violating Article 16 and invalidating the declaration',
      regulatoryHook: 'EU MDR Article 16; Article 14 distributor obligations; Article 19; Annex IV',
      detectionMethod: 'Periodic market surveillance sampling of DoCs in circulation to detect unauthorized alterations or additions',
      remediationPath: 'Recall altered DoCs from distribution chain; issue written manufacturer authorization where relabelling is legitimate; take corrective action against distributor',
      estimatedCost: '€20K–€75K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '12% of market surveillance DoC reviews identify unauthorized distributor modifications to manufacturer DoCs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── unique-device-identification (M494–M505) ───────────────────────────────

  {
    code: 'M494',
    name: 'UDI-DI Not Registered in EUDAMED Before Device Placed on EU Market',
    description: 'NorthStar Clinical places devices on the EU market without first registering the UDI-DI in EUDAMED as required by Article 29, violating the core UDI registration obligation that enables regulators and healthcare providers to trace devices through the supply chain.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-di', 'eudamed', 'article-29', 'market-placement', 'udi-registration'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'Device placed on EU market before UDI-DI registered in EUDAMED, violating Article 29 registration obligation',
      regulatoryHook: 'EU MDR Article 29; Article 26 UDI system; Commission Implementing Regulation 2021/2226 EUDAMED',
      detectionMethod: 'Pre-launch regulatory checklist confirming EUDAMED UDI-DI registration confirmation before first shipment',
      remediationPath: 'Register UDI-DI in EUDAMED immediately; conduct retrospective review of all devices in market; notify competent authority if required',
      estimatedCost: '€30K–€120K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '43% of new product launches experience UDI-DI EUDAMED registration delays relative to market placement date',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M495',
    name: 'UDI Carrier on Device Label Does Not Meet Annex VI Part C Symbology Requirements',
    description: 'NorthStar Clinical applies a UDI carrier that does not conform to the AIDC symbology or HRI format requirements specified in Annex VI Part C, producing a label that scanners in hospital supply chain systems cannot reliably read, undermining post-market traceability.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-carrier', 'annex-vi', 'aidc', 'hri', 'label-symbology'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'UDI carrier uses non-compliant AIDC symbology or HRI format, failing Annex VI Part C requirements for scanner readability',
      regulatoryHook: 'EU MDR Annex VI Part C; Article 27; ISO/IEC 15418 GS1 symbology standards; ICCBBA standards',
      detectionMethod: 'UDI carrier scan-quality verification using GS1 verifiers; HRI format check against Annex VI Part C specifications',
      remediationPath: 'Update label artwork to compliant AIDC symbology and HRI format; validate with GS1 verifier before reprint; re-register updated label in EUDAMED',
      estimatedCost: '€20K–€80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '29% of UDI carriers fail initial scan quality verification against GS1 standards',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M496',
    name: 'Production Identifier (UDI-PI) Not Included on Label of Implantable Device Requiring UDI-PI Under Article 27',
    description: 'NorthStar Clinical labels implantable devices with only the UDI-DI, omitting the UDI-PI components including lot or batch number, serial number, and manufacture date required by Article 27(3) for implantable devices, preventing accurate device-specific tracing in patient implant cards.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-pi', 'implantable-device', 'article-27', 'lot-number', 'patient-implant-card'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'UDI-PI components absent from implantable device label, preventing device-level tracing required by Article 27(3)',
      regulatoryHook: 'EU MDR Article 27(3); Annex VI Part C UDI-PI requirements; Article 18 patient implant card',
      detectionMethod: 'Label content audit verifying presence of lot/batch number, serial number, and manufacture date on implantable device labels',
      remediationPath: 'Redesign label artwork to include UDI-PI; validate label change; update patient implant card template; reprint affected inventory',
      estimatedCost: '€25K–€100K',
      timeToRemediate: '2–6 months',
      industryBenchmark: '38% of implantable device label audits identify missing or incomplete UDI-PI elements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M497',
    name: 'EUDAMED UDI-DI Data Elements Contain Inaccurate Intended Purpose or Clinical Size Attributes',
    description: 'NorthStar Clinical registers UDI-DI data in EUDAMED with inaccurate clinical size attributes and a truncated intended purpose description, causing downstream discrepancies in hospital procurement systems that rely on EUDAMED data for device purchasing and inventory management.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['eudamed', 'udi-di-data', 'article-29', 'data-accuracy', 'intended-purpose'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'EUDAMED UDI-DI data elements contain inaccurate intended purpose and clinical size, creating supply chain discrepancies',
      regulatoryHook: 'EU MDR Article 29; Commission Implementing Regulation 2021/2226 EUDAMED data elements; Article 26',
      detectionMethod: 'EUDAMED data quality audit comparing registered UDI-DI attributes against master label and technical documentation',
      remediationPath: 'Update EUDAMED UDI-DI records with accurate data elements; implement data verification step in product registration workflow',
      estimatedCost: '€15K–€60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '57% of EUDAMED UDI-DI registrations contain at least one data element discrepancy relative to the physical label',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M498',
    name: 'UDI Not Applied Directly on Device Where Packaging Is Not Present During Clinical Use',
    description: 'NorthStar Clinical applies the UDI carrier only to the outer packaging of a reusable surgical instrument, without applying the UDI directly to the device body as required by Annex VI when the device is used or reprocessed without its original packaging.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['direct-marking', 'annex-vi', 'reusable-device', 'udi-carrier', 'article-27'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'UDI absent from device body of reusable instrument used without packaging, violating Annex VI direct marking requirements',
      regulatoryHook: 'EU MDR Annex VI Part C direct marking requirements; Article 27(4); ISO 11135 sterilization compatibility',
      detectionMethod: 'Reusable device audit confirming direct UDI marking present and readable after reprocessing cycles',
      remediationPath: 'Apply direct UDI marking using laser engraving or permanent ink compliant with reprocessing cycles; validate readability post-reprocessing',
      estimatedCost: '€30K–€140K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '36% of reusable instrument manufacturers have UDI direct marking gaps for at least part of their product range',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M499',
    name: 'UDI-DI Changes Not Issued for New Versions Requiring New UDI-DI Under MDCG 2018-5',
    description: 'NorthStar Clinical releases a new device version with a changed intended purpose without assigning a new UDI-DI, violating MDCG 2018-5 guidance that requires a new UDI-DI when intended purpose changes, leaving the changed device indistinguishable from its predecessor in EUDAMED and traceability systems.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-di-new-version', 'mdcg-2018-5', 'intended-purpose-change', 'eudamed', 'article-29'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'Changed intended purpose device released without new UDI-DI, conflating versions in EUDAMED and supply chain traceability',
      regulatoryHook: 'EU MDR Article 27; MDCG 2018-5 UDI guidance; Commission Implementing Regulation 2021/2226',
      detectionMethod: 'Product change review process audit confirming MDCG 2018-5 UDI-DI new assignment decision tree applied on each design change',
      remediationPath: 'Assign new UDI-DI to changed device version; register in EUDAMED; update labels; communicate to supply chain partners',
      estimatedCost: '€20K–€70K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '44% of device version updates requiring new UDI-DI under MDCG 2018-5 are released without new assignment',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M500',
    name: 'Healthcare Institution UDI Storage Obligation Not Met Because Manufacturer Did Not Provide Structured UDI Data',
    description: 'NorthStar Clinical does not provide structured UDI data in machine-readable format to healthcare institutions upon delivery, preventing hospitals from fulfilling their Article 27(9) UDI storage obligations in electronic health records and impeding adverse event investigation traceability.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-data-provision', 'article-27', 'healthcare-institution', 'eud-udi', 'traceability'],
    failure_rate_pct: 55.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'Manufacturer fails to provide structured UDI data to healthcare institutions, blocking Article 27(9) storage compliance downstream',
      regulatoryHook: 'EU MDR Article 27(9); EUDAMED UDI-DI data availability; GS1 GTIN data sharing standards',
      detectionMethod: 'Customer delivery documentation audit confirming structured UDI data is transmitted with each device shipment',
      remediationPath: 'Implement UDI data exchange format (GS1 GDSN or equivalent) in order fulfillment system; train customer service on UDI data delivery',
      estimatedCost: '€30K–€120K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '52% of device manufacturers do not proactively provide structured UDI data in machine-readable format to hospital customers',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M501',
    name: 'System or Procedure Pack UDI Not Assigned to Assembly as Required by Article 22',
    description: 'NorthStar Clinical assembles a system combining two MDR-certified devices and places it on the market without assigning a separate UDI to the system, violating Article 22 which requires the system assembler to assign a UDI to the system and register it in EUDAMED.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['system-udi', 'article-22', 'system-assembler', 'procedure-pack', 'eudamed'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'System assembled from certified devices placed on market without Article 22 system-level UDI assignment and EUDAMED registration',
      regulatoryHook: 'EU MDR Article 22; Article 27; Commission Implementing Regulation 2021/2226 EUDAMED system registration',
      detectionMethod: 'Product portfolio review identifying all systems and procedure packs, confirming system-level UDI assignment and EUDAMED records',
      remediationPath: 'Assign UDI-DI to each system; register system in EUDAMED; apply UDI carrier to system packaging; issue system DoC',
      estimatedCost: '€20K–€80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '33% of system assemblers have at least one system without a properly registered system-level UDI',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M502',
    name: 'UDI Issuing Entity Not Designated for Assigned UDI-DI Creating Non-Resolvable Identifiers',
    description: 'NorthStar Clinical assigns UDI-DIs using a prefix from a UDI issuing entity whose EU MDR designation has lapsed, creating identifiers that cannot be resolved against the issuing entity\'s database and that EUDAMED rejects during registration.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-issuing-entity', 'gs1', 'hibcc', 'iccbba', 'eudamed-registration'],
    failure_rate_pct: 38.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'UDI-DI assigned using non-designated issuing entity prefix, producing non-resolvable identifiers rejected by EUDAMED',
      regulatoryHook: 'EU MDR Article 27(6); Commission Regulation (EU) 2022/123 issuing entity designation; EUDAMED technical guidance',
      detectionMethod: 'UDI issuing entity designation status verification against Commission-maintained list before assigning new UDI-DIs',
      remediationPath: 'Re-assign UDI-DIs under designated issuing entity; update EUDAMED; relabel affected device inventory',
      estimatedCost: '€25K–€90K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '8% of manufacturers have at least one UDI-DI assigned under an entity whose designation has lapsed or was never granted',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M503',
    name: 'UDI Labelling Implementation Does Not Meet Article 27 Phased Timeline for Applicable Device Class',
    description: 'NorthStar Clinical implements UDI labelling on Class IIb devices after the Article 27 statutory deadline for that class, continuing to place non-UDI-labelled devices on the market during the non-compliance window and creating enforcement risk with competent authorities.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-timeline', 'article-27', 'class-iib-deadline', 'labelling-compliance', 'enforcement'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'UDI labelling applied after Article 27 class deadline, resulting in non-compliant devices in supply chain during transition period',
      regulatoryHook: 'EU MDR Article 27 UDI obligation timelines; Article 123 transitional provisions; Commission guidance on UDI implementation dates',
      detectionMethod: 'UDI implementation date audit confirming first-labelled lot date against Article 27 class-specific statutory deadline',
      remediationPath: 'Complete UDI implementation immediately; identify affected inventory; assess competent authority notification obligations; document CAPA',
      estimatedCost: '€40K–€160K',
      timeToRemediate: '2–6 months',
      industryBenchmark: '28% of Class IIb manufacturers missed the initial Article 27 UDI labelling deadline for at least one SKU',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M504',
    name: 'UDI-DI Deactivated in EUDAMED Without Confirming No Devices With That UDI-DI Remain in Distribution',
    description: 'NorthStar Clinical deactivates a UDI-DI in EUDAMED following product discontinuation without confirming that all devices bearing that UDI-DI have cleared the supply chain, creating a traceability break for devices still in hospital inventory that can no longer be resolved against EUDAMED.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['udi-deactivation', 'eudamed', 'product-discontinuation', 'supply-chain-clearance', 'article-29'],
    failure_rate_pct: 42.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'UDI-DI deactivated in EUDAMED before supply chain clearance confirmation, breaking traceability for devices still in hospital stock',
      regulatoryHook: 'EU MDR Article 29; EUDAMED UDI-DI lifecycle management guidance; Article 27 traceability obligations',
      detectionMethod: 'Discontinuation SOP audit confirming supply chain clearance verification step before EUDAMED UDI-DI deactivation',
      remediationPath: 'Reactivate UDI-DI in EUDAMED; conduct distribution channel clearance survey; update deactivation SOP to require clearance confirmation',
      estimatedCost: '€10K–€40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '23% of UDI-DI deactivations in EUDAMED are executed before confirmed supply chain clearance',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M505',
    name: 'Combination UDI Label Not Applied to Higher-Level Packaging Where Required by Annex VI',
    description: 'NorthStar Clinical applies UDI carriers only at the unit-of-use packaging level for a device sold in cases and pallets, omitting required higher-level packaging UDI carriers specified in Annex VI Part C, preventing logistics-level traceability in hospital receiving and storage systems.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['higher-level-packaging', 'annex-vi', 'logistics-udi', 'case-label', 'supply-chain'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'unique-device-identification',
    data: {
      failureMode: 'Higher-level packaging UDI carriers absent, preventing logistics-level traceability required by Annex VI Part C',
      regulatoryHook: 'EU MDR Annex VI Part C higher-level packaging UDI; Article 27; MDCG 2018-5 packaging hierarchy guidance',
      detectionMethod: 'Packaging hierarchy audit confirming UDI carriers at all levels (unit, case, pallet) against Annex VI requirements',
      remediationPath: 'Apply UDI carriers to case and pallet packaging levels; update packaging specifications in QMS; validate with GS1 scan verification',
      estimatedCost: '€15K–€55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '40% of device manufacturers have UDI labelling only at unit level, missing higher-level packaging requirements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── economic-operator-obligations (M506–M517) ──────────────────────────────

  {
    code: 'M506',
    name: 'Importer Does Not Verify Manufacturer Has EUDAMED Registration Before Importing Device Into EU',
    description: 'NorthStar Clinical\'s EU importer begins importing devices from a third-country manufacturer without verifying that the manufacturer is registered in EUDAMED as required by Article 13(2)(a), placing devices on the market without confirming the manufacturer\'s basic regulatory standing.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['importer-obligation', 'article-13', 'eudamed-registration', 'manufacturer-verification', 'economic-operator'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Importer places devices on EU market without verifying manufacturer EUDAMED registration, violating Article 13(2)(a)',
      regulatoryHook: 'EU MDR Article 13(2)(a) importer obligations; Article 31 EUDAMED registration; Article 10(2)',
      detectionMethod: 'Importer onboarding SOP audit confirming EUDAMED manufacturer registration check before first shipment',
      remediationPath: 'Verify all current suppliers in EUDAMED; update importer SOP; suspend imports from unregistered manufacturers pending registration',
      estimatedCost: '€20K–€80K',
      timeToRemediate: '1–4 months',
      industryBenchmark: '51% of EU importers do not systematically verify manufacturer EUDAMED registration status before commencing imports',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M507',
    name: 'Distributor Supplies Device Without Verifying CE Marking and DoC Are Present as Required by Article 14',
    description: 'NorthStar Clinical\'s distributor supplies devices to hospitals without confirming that CE marking is affixed and a DoC is available, violating the Article 14(2)(a) obligation to verify CE marking presence before making a device available on the market.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['distributor-obligation', 'article-14', 'ce-marking-verification', 'doc-availability', 'economic-operator'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Distributor supplies devices without verifying CE marking and DoC presence, violating Article 14(2)(a)',
      regulatoryHook: 'EU MDR Article 14(2)(a); Article 19 DoC; Article 20 CE marking; Article 13(2) importer parallel obligations',
      detectionMethod: 'Distributor receiving inspection SOP audit confirming CE marking and DoC verification step before release to supply',
      remediationPath: 'Implement CE/DoC verification checklist in distributor receiving procedure; train warehouse staff; conduct retrospective stock audit',
      estimatedCost: '€15K–€60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '47% of EU distributors do not perform formal CE marking and DoC verification at goods receipt',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M508',
    name: 'Importer Contact Details Not Affixed to Device or Packaging as Required by Article 13(4)',
    description: 'NorthStar Clinical\'s importer distributes devices with only the non-EU manufacturer\'s contact details on the label, omitting the importer\'s name, registered trade name, registered address, and EU contact point required by Article 13(4), making it impossible for end users to contact the responsible EU economic operator.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['importer-labelling', 'article-13', 'contact-details', 'label-requirement', 'economic-operator'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Importer contact details absent from device label, violating Article 13(4) obligation to affix importer identity to device or packaging',
      regulatoryHook: 'EU MDR Article 13(4); Annex I Section 23.2(b) labelling requirements; Article 10(8)',
      detectionMethod: 'Label audit confirming importer name, address, and contact information present on device and/or packaging per Article 13(4)',
      remediationPath: 'Redesign labels or add supplementary importer label to packaging; validate label change; communicate updated labelling to supply chain',
      estimatedCost: '€10K–€45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '66% of non-EU manufacturers distributing through EU importers have importer labelling gaps on at least some SKUs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M509',
    name: 'Economic Operator Does Not Maintain Register of Complaints and Non-Conforming Devices as Required by Article 14',
    description: 'NorthStar Clinical\'s distributor does not maintain a register of complaints or non-conforming devices received from healthcare facilities, failing the Article 14(5) obligation that requires distributors to keep and forward this information to the manufacturer and importers.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['distributor-complaint-register', 'article-14', 'non-conforming-device', 'economic-operator', 'complaint-handling'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Distributor has no complaint or non-conforming device register, violating Article 14(5) and fragmenting manufacturer feedback loop',
      regulatoryHook: 'EU MDR Article 14(5); Article 83 post-market surveillance; Article 87 vigilance; Annex IX Chapter II',
      detectionMethod: 'Distributor quality system audit confirming existence and maintenance of complaint and non-conforming device register with manufacturer forwarding procedure',
      remediationPath: 'Implement complaint and NCR register for distributor; establish forwarding procedure to manufacturer; integrate with manufacturer PMS system',
      estimatedCost: '€15K–€55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '58% of EU distributors lack a formal complaint register meeting Article 14(5) requirements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M510',
    name: 'Authorised Representative Agreement Does Not Specify All Article 11 Obligations',
    description: 'NorthStar Clinical\'s written agreement with its EU Authorised Representative omits the AR\'s obligation to maintain the registration dossier, to cooperate with competent authorities, and to take corrective actions, leaving Article 11(3) mandatory obligations without contractual coverage.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['authorised-representative', 'article-11', 'ar-agreement', 'article-11-obligations', 'economic-operator'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'AR agreement omits Article 11(3) mandatory obligations including registration maintenance and competent authority cooperation',
      regulatoryHook: 'EU MDR Article 11; Article 11(3) specific AR obligations; MDCG 2019-6 AR guidance',
      detectionMethod: 'AR agreement content audit mapping each Article 11(3) obligation against contract clauses',
      remediationPath: 'Amend AR agreement to include all Article 11(3) obligations explicitly; obtain signed amendment; update QMS contract management register',
      estimatedCost: '€10K–€40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '43% of AR agreements reviewed by competent authorities have at least one Article 11(3) obligation gap',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M511',
    name: 'Importer Does Not Inform Manufacturer of Serious Incidents Reported by Healthcare Facilities Without Delay',
    description: 'NorthStar Clinical\'s importer receives serious incident reports from hospital customers but delays forwarding them to the manufacturer by more than 30 days, undermining the Article 13(2)(b) obligation to inform the manufacturer without delay and delaying the manufacturer\'s Article 87 vigilance reporting timeline.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['importer-incident-forwarding', 'article-13', 'article-87', 'vigilance', 'serious-incident'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Importer delays forwarding serious incident reports to manufacturer by more than 30 days, violating Article 13(2)(b) and delaying Article 87 vigilance reporting',
      regulatoryHook: 'EU MDR Article 13(2)(b) importer incident forwarding; Article 87 vigilance reporting timelines; MDCG 2023-3',
      detectionMethod: 'Incident log review measuring time from importer receipt to manufacturer notification against Article 87 reporting deadlines',
      remediationPath: 'Implement 24-hour incident escalation procedure for importer; establish direct serious incident hotline to manufacturer vigilance team',
      estimatedCost: '€15K–€55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '44% of importers report delays of more than 7 days in forwarding serious incident information to manufacturers',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M512',
    name: 'Distributor Makes Device Available on Market in Member State Without Ensuring Language Requirements Met',
    description: 'NorthStar Clinical\'s distributor distributes devices in a Member State without verifying that the instructions for use and labelling are in the required official language, violating Article 14(2)(b) and creating patient safety risk from non-readable instructions.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['distributor-language', 'article-14', 'ifu-language', 'labelling-language', 'member-state'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Distributor supplies devices to member state without verifying IFU and label language compliance, violating Article 14(2)(b)',
      regulatoryHook: 'EU MDR Article 14(2)(b); Annex I Section 23.1(f) language requirements; national language implementing measures',
      detectionMethod: 'Distributor market-by-market language compliance checklist audit against national IFU language requirements before distribution',
      remediationPath: 'Withdraw non-compliant language devices from member state; commission translations; update distributor pre-distribution checklist',
      estimatedCost: '€20K–€80K per market',
      timeToRemediate: '2–5 months',
      industryBenchmark: '53% of EU distributors have distributed devices without confirming IFU language compliance in at least one member state',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M513',
    name: 'Authorised Representative Terminated Without 30-Day Advance Notice Leaving MDR Coverage Gap',
    description: 'NorthStar Clinical terminates its EU Authorised Representative agreement without the MDCG-recommended 30-day minimum notice, creating a period during which devices remain on the EU market without an active AR, violating Article 11 obligations for non-EU manufacturers.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['ar-termination', 'article-11', 'coverage-gap', 'non-eu-manufacturer', 'mdcg-2019-6'],
    failure_rate_pct: 38.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'AR terminated without advance notice period, creating market presence without active EU AR in violation of Article 11',
      regulatoryHook: 'EU MDR Article 11; MDCG 2019-6 AR guidance; Article 120(5) transitional provisions',
      detectionMethod: 'AR agreement termination clause review confirming minimum notice period aligned with MDCG 2019-6 recommendations',
      remediationPath: 'Designate new AR before terminating existing AR; update EUDAMED AR registration; notify competent authorities in member states where distributed',
      estimatedCost: '€30K–€100K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '17% of AR terminations create a market presence gap of more than 7 days without an active AR',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M514',
    name: 'Importer Does Not Register Own Identity in EUDAMED Separately From Manufacturer',
    description: 'NorthStar Clinical\'s importer operates under the manufacturer\'s EUDAMED registration rather than registering its own entity as required by Article 31, creating a compliance gap where the importer\'s legal obligations under Article 13 cannot be attributed to an independently registered economic operator.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['importer-eudamed', 'article-31', 'economic-operator-registration', 'article-13', 'eudamed'],
    failure_rate_pct: 44.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Importer not independently registered in EUDAMED, making Article 13 obligations unattributable to a registered entity',
      regulatoryHook: 'EU MDR Article 31 EUDAMED registration; Article 13(2)(f); Commission Implementing Regulation 2021/2226',
      detectionMethod: 'EUDAMED actor search confirming importer entity independently registered with own SRN distinct from manufacturer registration',
      remediationPath: 'Complete importer EUDAMED registration; obtain SRN; update QMS supplier agreements to reference importer SRN',
      estimatedCost: '€5K–€25K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '36% of EU importers are not independently registered in EUDAMED as a distinct actor from the manufacturer',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M515',
    name: 'Distributor Stores Devices Outside Manufacturer-Specified Conditions Voiding Conformity',
    description: 'NorthStar Clinical\'s distributor stores temperature-sensitive devices in a warehouse that does not maintain the temperature range specified in the IFU, violating Article 14(3) obligations to maintain storage conditions and potentially voiding device conformity through degraded performance.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['distributor-storage', 'article-14', 'storage-conditions', 'ifu-requirements', 'conformity-voiding'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'Distributor warehouse temperature outside IFU-specified range, voiding device conformity and violating Article 14(3)',
      regulatoryHook: 'EU MDR Article 14(3) distributor storage obligations; Annex I Section 23 IFU content; Article 83 PMS',
      detectionMethod: 'Distributor warehouse temperature monitoring log audit confirming conditions meet IFU specifications throughout storage period',
      remediationPath: 'Immediate corrective action on warehouse temperature control; assess affected stock for conformity; recall if conformity cannot be confirmed',
      estimatedCost: '€40K–€200K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '31% of distributor warehouse temperature deviation incidents are not reported to manufacturers as required',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M516',
    name: 'Authorised Representative Does Not Cooperate With Competent Authority During Vigilance Investigation',
    description: 'NorthStar Clinical\'s Authorised Representative does not respond to a competent authority information request within the required timeframe during a serious incident investigation, violating the Article 11(3)(c) obligation to cooperate with authorities on all actions taken to eliminate or reduce risks.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['ar-cooperation', 'article-11', 'competent-authority', 'vigilance-investigation', 'serious-incident'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'AR fails to respond to competent authority information request during vigilance investigation, violating Article 11(3)(c)',
      regulatoryHook: 'EU MDR Article 11(3)(c) AR cooperation obligation; Article 93 competent authority powers; MDCG 2023-3 vigilance',
      detectionMethod: 'AR competent authority correspondence log audit confirming response times against request deadlines',
      remediationPath: 'Establish AR-manufacturer escalation protocol for competent authority requests; assign AR regulatory contact with 24-hour response obligation',
      estimatedCost: '€15K–€60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '26% of competent authority information requests during vigilance investigations receive delayed responses from ARs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M517',
    name: 'Person Responsible for Regulatory Compliance Not Designated or Does Not Meet Article 15 Qualification Requirements',
    description: 'NorthStar Clinical designates a PRRC who does not hold the required degree in law, medicine, pharmacy, engineering or a natural science discipline, or has fewer than one year of professional experience in regulatory affairs or quality management, failing Article 15(1) minimum qualification requirements.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['prrc', 'article-15', 'qualification', 'regulatory-compliance', 'economic-operator'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'economic-operator-obligations',
    data: {
      failureMode: 'PRRC designated without meeting Article 15(1) degree or professional experience qualification requirements',
      regulatoryHook: 'EU MDR Article 15(1) PRRC qualification requirements; MDCG 2019-7 PRRC guidance; Article 10(14)',
      detectionMethod: 'PRRC CV and credential audit against Article 15(1) degree requirement and one-year experience minimum',
      remediationPath: 'Designate qualified PRRC meeting Article 15(1); document qualifications in EUDAMED; update DoC signatory if applicable',
      estimatedCost: '€20K–€80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '24% of designated PRRCs at SME manufacturers do not meet all Article 15(1) qualification criteria',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── mdr-vigilance-advanced (M518–M529) ─────────────────────────────────────

  {
    code: 'M518',
    name: 'Serious Incident Report Not Submitted to Competent Authority Within 15-Day Article 87 Deadline',
    description: 'NorthStar Clinical receives a serious incident report from a hospital and internal triage determines reportability but the report is not submitted to the competent authority within the 15-day timeline required by Article 87(2), creating a regulatory violation regardless of the device\'s causal role.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['serious-incident', 'article-87', '15-day-reporting', 'competent-authority', 'vigilance'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Serious incident report not submitted within 15 days of becoming aware, violating Article 87(2) reporting deadline',
      regulatoryHook: 'EU MDR Article 87(2); MDCG 2023-3 vigilance guidance; Article 87(6) periodic summary reports',
      detectionMethod: 'Vigilance report log audit measuring days from incident awareness to competent authority submission for each reportable event',
      remediationPath: 'Implement vigilance triage SOP with 5-day internal deadline; assign vigilance owner; submit overdue reports with explanation to competent authority',
      estimatedCost: '€30K–€120K',
      timeToRemediate: '1–4 months',
      industryBenchmark: '38% of serious incident reports are submitted after the Article 87 deadline for at least one competent authority',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M519',
    name: 'Manufacturer Does Not Report Trend of Non-Serious Incidents Exceeding Threshold Under Article 88',
    description: 'NorthStar Clinical identifies a statistically significant increase in a non-serious adverse event rate exceeding its own predetermined threshold but does not submit an Article 88 trend report to the competent authority, failing to trigger the regulatory oversight mechanism for emerging risk patterns.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['trend-reporting', 'article-88', 'non-serious-incident', 'threshold', 'vigilance'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Article 88 trend report not filed despite non-serious incident rate exceeding predetermined manufacturer threshold',
      regulatoryHook: 'EU MDR Article 88 trend reporting; MDCG 2023-3 trend reporting section; Article 83 PMS integration',
      detectionMethod: 'PMS complaint rate monitoring against predetermined thresholds with automated escalation trigger for Article 88 assessment',
      remediationPath: 'Submit retrospective Article 88 trend report; recalibrate monitoring thresholds; implement automated threshold breach alert',
      estimatedCost: '€20K–€80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '55% of manufacturers with identified adverse event rate increases do not file Article 88 trend reports within required periods',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M520',
    name: 'Field Safety Corrective Action Not Reported as Safety Field Notice to All Affected Member States Under Article 87',
    description: 'NorthStar Clinical issues a Field Safety Corrective Action and communicates directly with hospitals that received the affected devices but does not file a Field Safety Notice with all competent authorities in the member states where the device was distributed, violating Article 87(3) FSCA reporting obligations.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['fsca', 'fsn', 'article-87', 'competent-authority', 'field-safety-notice'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'FSCA executed without FSN filed to all member state competent authorities where device distributed, violating Article 87(3)',
      regulatoryHook: 'EU MDR Article 87(3) FSCA reporting; MDCG 2023-3 FSN requirements; Article 89 CA powers',
      detectionMethod: 'FSCA file audit confirming FSN submission records for each member state in device distribution footprint',
      remediationPath: 'File retroactive FSN with missing competent authorities; update FSCA distribution list procedure; implement EUDAMED FSCA module reporting',
      estimatedCost: '€25K–€100K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '42% of FSCAs are reported to fewer competent authorities than device distribution footprint requires',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M521',
    name: 'Vigilance Report Root Cause Analysis Does Not Meet MDCG 2023-3 Depth Requirements',
    description: 'NorthStar Clinical submits serious incident reports with superficial root cause analysis citing only proximate causes without investigating underlying design or manufacturing system factors, producing vigilance reports that competent authorities reject as inadequate under MDCG 2023-3 investigation requirements.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['root-cause-analysis', 'mdcg-2023-3', 'vigilance', 'article-87', 'serious-incident'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Serious incident RCA addresses only proximate causes without systemic design or manufacturing investigation required by MDCG 2023-3',
      regulatoryHook: 'EU MDR Article 87; MDCG 2023-3 vigilance investigation depth requirements; ISO 14971 risk management integration',
      detectionMethod: 'Vigilance report quality audit using MDCG 2023-3 investigation checklist for depth and systemic cause identification',
      remediationPath: 'Retrain vigilance team on MDCG 2023-3 RCA methodology; implement structured 5-why and fishbone analysis in investigation SOP; resubmit deficient reports',
      estimatedCost: '€25K–€95K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '61% of serious incident reports require supplementary information requests from competent authorities due to insufficient RCA depth',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-generated RCA summaries in vigilance reports cite surface-level causes without systemic investigation depth',
    },
  },
  {
    code: 'M522',
    name: 'Implantovigilance Not Integrated With MDR Article 87 Vigilance Programme for Implantable Device',
    description: 'NorthStar Clinical operates a separate implantovigilance registry for long-term implant follow-up that is not integrated with the Article 87 vigilance reporting system, creating a data silo where implant-related complications captured in registry follow-up are not evaluated for serious incident reportability.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['implantovigilance', 'article-87', 'implant-registry', 'pmsf', 'vigilance'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Implantovigilance registry operates as separate data silo not feeding Article 87 serious incident assessment workflow',
      regulatoryHook: 'EU MDR Article 87; Article 88; Annex XIV Part B PMCF implant follow-up; Article 83 PMS data integration',
      detectionMethod: 'Data flow audit tracing implant registry adverse event data to vigilance reportability assessment process',
      remediationPath: 'Integrate implantovigilance registry into PMS complaint management system; define escalation rules for registry events to vigilance triage',
      estimatedCost: '€50K–€180K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '46% of implantable device manufacturers have implant registry data not systematically assessed for Article 87 reportability',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M523',
    name: 'Serious Incident Determined Non-Reportable Without Documentation of Article 87 Seriousness Criteria Assessment',
    description: 'NorthStar Clinical\'s vigilance team determines that incidents do not meet Article 87 reporting thresholds without documenting the Article 87(1) seriousness criteria assessment for each incident, creating an audit trail gap that competent authorities identify as a sign of underreporting during surveillance inspections.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['non-reportable-determination', 'article-87', 'seriousness-criteria', 'underreporting', 'vigilance'],
    failure_rate_pct: 74.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Non-reportable incident determinations made without documented Article 87(1) seriousness criteria assessment, creating underreporting audit trail gap',
      regulatoryHook: 'EU MDR Article 87(1) seriousness criteria; MDCG 2023-3 reportability assessment documentation; Article 93 competent authority audit rights',
      detectionMethod: 'Vigilance triage record audit confirming seriousness criteria assessment documentation for each incident determined non-reportable',
      remediationPath: 'Implement mandatory Article 87 seriousness criteria assessment form for all incidents; archive triage decisions; retroactive documentation for recent incidents',
      estimatedCost: '€15K–€60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '70% of manufacturers lack documented seriousness criteria assessments for incidents determined non-reportable',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-assisted incident triage tools that auto-classify incidents as non-reportable without generating auditable seriousness criteria assessment records',
    },
  },
  {
    code: 'M524',
    name: 'Periodic Summary Report Under Article 87(6) Not Submitted for Device With High Volume of Similar Incidents',
    description: 'NorthStar Clinical has a device with a high volume of similar and expected serious incidents qualifying for periodic summary reporting under Article 87(6) but continues to submit individual reports for each incident rather than negotiating a periodic summary report schedule with the competent authority.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['periodic-summary-report', 'article-87', 'psr', 'high-volume-incidents', 'vigilance'],
    failure_rate_pct: 48.0,
    is_active: false,
    demoRelevant: false,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Individual reports submitted for high-volume similar incidents instead of Article 87(6) periodic summary report, creating unnecessary regulatory burden',
      regulatoryHook: 'EU MDR Article 87(6) periodic summary reporting; MDCG 2023-3 PSR eligibility criteria; Article 87(4)',
      detectionMethod: 'Incident database analysis identifying device-specific incident clusters meeting Article 87(6) PSR eligibility criteria',
      remediationPath: 'Apply to competent authority for Article 87(6) periodic summary report arrangement; prepare PSR template; agree reporting frequency',
      estimatedCost: '€10K–€40K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '37% of devices with qualifying incident volumes do not use Article 87(6) PSR arrangements, creating avoidable reporting inefficiency',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M525',
    name: 'FSCA Not Initiated Within Required Timeline After Causal Link Between Device and Death Established',
    description: 'NorthStar Clinical confirms a causal link between a device malfunction and a patient death but delays initiating a Field Safety Corrective Action beyond the 2-day immediate action window required for life-threatening incidents under MDCG 2023-3, with the delayed response resulting in additional patient exposures.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['fsca-timeline', '2-day-reporting', 'article-87', 'mdcg-2023-3', 'life-threatening'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'FSCA not initiated within MDCG 2023-3 2-day life-threatening incident timeline, extending patient exposure during investigation',
      regulatoryHook: 'EU MDR Article 87(2) immediate action; MDCG 2023-3 timeline table; Article 89 competent authority corrective action powers',
      detectionMethod: 'FSCA initiation date audit versus date of causal link establishment for life-threatening incident classification events',
      remediationPath: 'Implement immediate FSCA decision protocol for life-threatening events; designate 24/7 vigilance escalation contact; conduct retrospective CA notification',
      estimatedCost: '€50K–€200K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '28% of life-threatening incident FSCAs are initiated after the MDCG 2023-3 recommended 2-day window',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M526',
    name: 'Post-Market Surveillance Report Does Not Reference and Incorporate Vigilance Data as Required by Article 85',
    description: 'NorthStar Clinical produces PMSR documents under Article 85 that do not systematically reference or analyse vigilance data including serious incident reports and FSCAs, treating PMS and vigilance as parallel systems rather than the integrated programme required by Articles 83 and 87.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['pmsr', 'article-85', 'article-83', 'vigilance-integration', 'pms'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'PMSR produced without systematic integration of vigilance data, treating PMS and vigilance as separate non-communicating programmes',
      regulatoryHook: 'EU MDR Article 85 PMSR requirements; Article 83 PMS plan; Article 87 vigilance; MDCG 2022-21 PMSR guidance',
      detectionMethod: 'PMSR content audit against MDCG 2022-21 checklist confirming vigilance data sources are cited and analysed within the PMSR narrative',
      remediationPath: 'Integrate vigilance database query into annual PMSR preparation process; update PMSR template to include vigilance data section; reissue current PMSR',
      estimatedCost: '€20K–€75K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '59% of PMSRs reviewed by competent authorities are cited for insufficient integration of vigilance data',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-generated PMSR summaries omit vigilance cross-references, creating appearance of integrated PMS without substantive vigilance data analysis',
    },
  },
  {
    code: 'M527',
    name: 'Vigilance System Does Not Include Ecovigilance Data From Online and Social Media Sources',
    description: 'NorthStar Clinical\'s vigilance data collection programme covers direct healthcare facility reports and distributor complaints but does not systematically monitor online sources, social media, or published literature for signals of device-related adverse events, missing information sources that MDCG 2022-21 identifies as part of a comprehensive PMS programme.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['signal-detection', 'online-monitoring', 'pms', 'mdcg-2022-21', 'vigilance'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Vigilance system does not include online, social media, or literature monitoring, missing MDCG 2022-21 signal sources',
      regulatoryHook: 'EU MDR Article 83 PMS data sources; MDCG 2022-21 PMS guidance on data sources; Article 88 trend reporting trigger data',
      detectionMethod: 'PMS data source inventory audit against MDCG 2022-21 recommended vigilance signal source list',
      remediationPath: 'Implement structured literature review and online monitoring programme; integrate findings into PMS complaint management system; update PMSF',
      estimatedCost: '€25K–€90K per year',
      timeToRemediate: '3–7 months',
      industryBenchmark: '64% of manufacturers do not have formalised online or social media monitoring as part of their PMS vigilance signal detection programme',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M528',
    name: 'Serious Incident Report Correction Not Submitted After New Information Changes Causal Assessment',
    description: 'NorthStar Clinical submits an initial serious incident report concluding the device was not the cause, then receives post-market clinical data establishing probable device causality, but does not submit a corrected or updated report to the competent authority as required by Article 87 ongoing reporting obligations.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['incident-report-update', 'article-87', 'causal-reassessment', 'corrected-report', 'vigilance'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'Serious incident report not updated after new information changes causal assessment, leaving incorrect assessment on record with competent authority',
      regulatoryHook: 'EU MDR Article 87 ongoing reporting obligation; MDCG 2023-3 report update requirements; Article 87(4)',
      detectionMethod: 'Open incident file review process confirming causal assessment update triggers are linked to new clinical data inputs from PMCF and literature review',
      remediationPath: 'Submit corrected report with updated causal assessment to competent authority; implement causal reassessment trigger in vigilance case management',
      estimatedCost: '€15K–€55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '48% of serious incident files are closed without a causal reassessment update when subsequent data changes the original conclusion',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M529',
    name: 'Field Safety Notice Does Not Include All Annex I-Required Safety Information for Healthcare Professional Action',
    description: 'NorthStar Clinical\'s Field Safety Notice for an FSCA omits the specific action required by healthcare professionals, the timeline for action, and the contact point for returns or replacements, providing an incomplete FSN that delays hospital response and prolongs patient risk exposure.',
    vertical: 'medtech',
    office_category: 'EU Regulatory',
    keywords: ['field-safety-notice', 'fsn-content', 'article-87', 'mdcg-2023-3', 'healthcare-professional-action'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdr-vigilance-advanced',
    data: {
      failureMode: 'FSN omits required action steps, timeline, and contact point, delaying hospital response and prolonging patient exposure',
      regulatoryHook: 'EU MDR Article 87(3); MDCG 2023-3 FSN content requirements; Annex I GSPR safety communication obligations',
      detectionMethod: 'FSN content review against MDCG 2023-3 FSN template checklist before distribution to competent authorities and healthcare facilities',
      remediationPath: 'Reissue corrected FSN with all required content; re-distribute to hospitals and competent authorities; implement FSN review gate before release',
      estimatedCost: '€10K–€45K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '43% of FSNs distributed in the EU market are missing at least one MDCG 2023-3 required content element',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

];
