interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const MEDTECH_DOM09_MANUFACTURING_PART4_PATTERNS: PatternSeed[] = [

  // ── process-validation-lifecycle (M1480–M1491) ───────────────────────────

  {
    code: 'M1480',
    name: 'PPQ Protocol Missing Worst-Case Parameter Justification',
    description: 'Process performance qualification protocols omit documented scientific rationale for worst-case parameter selection, leaving FDA reviewers unable to confirm that challenged conditions bound the full commercial manufacturing space.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['ppq', 'process-validation', 'worst-case', '21-cfr-820', 'fda-guidance'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'PPQ protocols lack worst-case scientific justification required by FDA process validation guidance.',
      regulatoryHook: 'FDA Process Validation Guidance 2011 Stage 2; 21 CFR 820.75',
      detectionMethod: 'Protocol gap analysis comparing parameter selection rationale against FDA guidance requirements.',
      remediationPath: 'Retroactively document worst-case justification and amend PPQ protocol before next lot release.',
      estimatedCost: '$80K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '51% of device manufacturers have PPQ protocols with inadequate worst-case documentation.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1481',
    name: 'Stage 3 Continued Process Verification Program Not Statistically Designed',
    description: 'Continued process verification programs rely on arbitrary sample sizes and informal trend reviews rather than statistically designed sampling plans, failing to detect process drift within the number of lots required by FDA guidance.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['cpv', 'stage-3-validation', 'statistical-process-control', 'fda-guidance', '21-cfr-820'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'CPV sampling plans are not statistically designed, missing drift signals before OOS events occur.',
      regulatoryHook: 'FDA Process Validation Guidance 2011 Stage 3; ICH Q10 Pharmaceutical Quality System',
      detectionMethod: 'Statistical audit comparing CPV sampling frequency and power against lot volume and historical variability.',
      remediationPath: 'Engage a biostatistician to redesign CPV sampling plan with documented AQL and power calculations.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '44% of Class II/III manufacturers operate Stage 3 programs without formal statistical design.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1482',
    name: 'Validation Master Plan Out of Currency with Current Product Portfolio',
    description: 'The site validation master plan references legacy products and retired equipment configurations, creating a gap between the documented validation approach and actual manufacturing processes under quality system control.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['validation-master-plan', 'vmp-currency', 'quality-system', '21-cfr-820', 'iso-13485'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'VMP does not reflect current product portfolio, leaving new processes outside the governed validation framework.',
      regulatoryHook: '21 CFR 820.75 process validation; ISO 13485:2016 §7.5.6 validation of processes',
      detectionMethod: 'Cross-reference VMP product and equipment index against the current device master record register.',
      remediationPath: 'Revise VMP to include all active products and define a biennial review cycle with QA ownership.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '38% of sites have VMPs not updated within 24 months of a significant product line change.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1483',
    name: 'Revalidation Trigger Criteria Not Defined in Quality System',
    description: 'The site quality system lacks documented criteria specifying which process changes, deviations, or equipment events automatically trigger revalidation, resulting in ad hoc revalidation decisions that are inconsistent across product lines.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['revalidation', 'change-control', 'validation-trigger', '21-cfr-820', 'iso-13485'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Absent revalidation trigger criteria allow process changes to go unvalidated until regulatory inspection.',
      regulatoryHook: '21 CFR 820.75(b); FDA Process Validation Guidance 2011; ISO 13485:2016 §7.5.6',
      detectionMethod: 'Review change control records for the past 24 months against revalidation decisions to identify uncontrolled gaps.',
      remediationPath: 'Define revalidation trigger matrix in SOP and back-apply review to all open change records within 90 days.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '47% of FDA warning letters citing validation include missing or inadequate revalidation trigger definitions.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1484',
    name: 'PPQ Acceptance Criteria Set Post-Execution Without Prospective Rationale',
    description: 'Acceptance criteria for PPQ studies are documented after lot execution, allowing criteria to be written to passing data rather than derived from product performance requirements and historical process knowledge.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['ppq', 'acceptance-criteria', 'prospective-validation', 'fda-483', '21-cfr-820'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Post-execution acceptance criteria inflate PPQ pass rates and mask process capability gaps.',
      regulatoryHook: 'FDA Process Validation Guidance 2011; 21 CFR 820.75; ICH Q8 Design Space',
      detectionMethod: 'Audit PPQ protocol approval timestamps against lot execution dates to detect retroactive criteria setting.',
      remediationPath: 'Require protocol approval with criteria sign-off before lot initiation; investigate and document all historical gaps.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '29% of FDA 483 validation observations involve retrospectively defined acceptance criteria.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1485',
    name: 'Process Validation Scope Excludes Ancillary Processes Affecting Product Quality',
    description: 'Validation scope documents cover primary assembly and packaging but exclude ancillary processes such as cleaning, sterilization load configuration, and label application that directly affect finished device safety and efficacy.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['validation-scope', 'ancillary-process', 'cleaning-validation', 'sterilization', '21-cfr-820'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Unvalidated ancillary processes create uncontrolled quality risk pathways not visible in the validation master plan.',
      regulatoryHook: '21 CFR 820.75; FDA Guidance on Validation of Cleaning Processes; ISO 13485:2016 §7.5.6',
      detectionMethod: 'Map all manufacturing steps to validation register and identify processes with quality impact lacking approved validation.',
      remediationPath: 'Perform gap analysis to add missing ancillary process validations to VMP with risk-prioritized execution schedule.',
      estimatedCost: '$100K–$300K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '33% of device sites have at least one ancillary process with quality impact outside their validation program.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1486',
    name: 'Process Capability Index Not Calculated for Critical Quality Attributes',
    description: 'PPQ summary reports present pass/fail lot results without calculating Cpk or Ppk for critical quality attributes, preventing the site from demonstrating statistical process capability to FDA reviewers during premarket submissions.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['process-capability', 'cpk', 'ppk', 'critical-quality-attributes', 'ppq'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Missing process capability indices prevent the site from demonstrating a state of control to regulatory reviewers.',
      regulatoryHook: 'FDA Process Validation Guidance 2011 Stage 2; ICH Q8; FDA PMA submission statistical requirements',
      detectionMethod: 'Review PPQ reports for presence of Cpk/Ppk calculations on each critical quality attribute.',
      remediationPath: 'Retroactively compute capability indices from PPQ data and establish prospective Cpk thresholds for future batches.',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of small-to-mid-size device manufacturers omit process capability indices from PPQ documentation.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1487',
    name: 'Validation Protocol Approval Obtained from Non-Qualified Personnel',
    description: 'PPQ and IQ/OQ/PQ protocols are approved by production supervisors without documented quality engineering qualifications, violating internal SOPs requiring independent QA review and approval before validation execution.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['validation-approval', 'qualified-personnel', 'qa-independence', '21-cfr-820', 'training-records'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Unqualified approvers undermine QA independence and leave validation records vulnerable to FDA objection.',
      regulatoryHook: '21 CFR 820.25 personnel qualifications; 21 CFR 820.75; ISO 13485:2016 §6.2',
      detectionMethod: 'Audit validation protocol approver training records against defined qualification criteria in applicable SOPs.',
      remediationPath: 'Correct approval records with qualified QA co-signature and revise SOP to require electronic qualification gating.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '22% of FDA 483 observations cite approval records by personnel without documented qualifications.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1488',
    name: 'IQ OQ PQ Phases Compressed Without Risk-Based Justification',
    description: 'Sites combine installation qualification, operational qualification, and performance qualification phases into a single compressed protocol without documented risk-based rationale, eliminating sequential gating that catches equipment faults before process performance testing.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['iq-oq-pq', 'validation-phases', 'risk-based-approach', '21-cfr-820', 'gamp5'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Phase compression masks equipment installation deficiencies that cascade into process performance failures.',
      regulatoryHook: '21 CFR 820.75; GAMP 5 risk-based approach; FDA Process Validation Guidance 2011',
      detectionMethod: 'Review validation protocols for documented phase separation and gating review sign-offs between IQ, OQ, and PQ.',
      remediationPath: 'Establish phase-gated validation SOP and perform retrospective impact assessment on all compressed validations.',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '27% of validation audit findings at device sites involve unjustified protocol phase compression.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1489',
    name: 'Validation Data Integrity Gaps Due to Manual Transcription from Equipment Logs',
    description: 'Critical validation data is manually transcribed from paper equipment logs into electronic validation reports, introducing transcription error risk and lacking the raw data traceability required to withstand FDA data integrity scrutiny.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['data-integrity', 'manual-transcription', 'alcoa-plus', '21-cfr-820', 'validation-records'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Manual transcription from paper logs to electronic records creates undetected data integrity vulnerabilities in validation evidence.',
      regulatoryHook: `21 CFR Part 11; FDA Data Integrity Guidance 2018; ALCOA+ principles; 21 CFR 820.75`,
      detectionMethod: 'Compare raw equipment log values against validation report transcriptions for a statistical sample of PPQ lots.',
      remediationPath: 'Implement direct electronic data capture from equipment to validation system and eliminate manual transcription.',
      estimatedCost: '$120K–$350K',
      timeToRemediate: '6–18 months',
      industryBenchmark: '36% of FDA data integrity observations at device sites trace to manual transcription from paper equipment records.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1490',
    name: 'Process Validation Reports Not Reviewed Before Commercial Distribution',
    description: `Finished device lots are released for commercial distribution before the process validation summary report receives quality management review and approval, violating the site's lot release procedure and 21 CFR 820.80 acceptance requirements.`,
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['lot-release', 'validation-report', '21-cfr-820-80', 'quality-release', 'ppq'],
    failure_rate_pct: 40.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Pre-approval lot distribution circumvents the validation-to-release gate required by the device quality system.',
      regulatoryHook: '21 CFR 820.80 receiving, in-process, and finished device acceptance; 21 CFR 820.75',
      detectionMethod: 'Audit lot release records for validation report approval dates relative to distribution dates across a 12-month window.',
      remediationPath: 'Implement validation report approval as a mandatory lot release checkpoint with system-enforced sequencing.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '19% of device sites have documented instances of commercial lot release occurring before validation report approval.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1491',
    name: 'Validation Master Plan Lacks Equipment Re-qualification Schedule',
    description: 'The validation master plan defines initial qualification requirements but contains no periodic re-qualification schedule for critical manufacturing equipment, allowing qualification status to lapse undetected after maintenance or age-related drift.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['requalification', 'equipment-qualification', 'vmp', 'preventive-maintenance', 'iso-13485'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'process-validation-lifecycle',
    data: {
      failureMode: 'Absent re-qualification schedule allows critical equipment to operate beyond demonstrated performance parameters.',
      regulatoryHook: '21 CFR 820.70 production and process controls; ISO 13485:2016 §7.5.6; 21 CFR 820.75',
      detectionMethod: 'Review VMP for re-qualification frequency definitions and cross-check against equipment qualification record dates.',
      remediationPath: 'Add re-qualification frequency table to VMP and integrate triggers into the preventive maintenance system.',
      estimatedCost: '$35K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '42% of device sites lack a defined periodic re-qualification schedule in their validation master plan.',
      aiInsertionRisk: false,
    },
  },

  // ── microbiological-control (M1492–M1503) ────────────────────────────────

  {
    code: 'M1492',
    name: 'Bioburden Specification Lacks Scientific Basis Linking to Sterilization Validation',
    description: `Product bioburden specifications are set by historical convention rather than derived from sterilization validation data, creating a disconnect between the bioburden control limit and the sterilization dose required to achieve SAL 10-6.`,
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['bioburden', 'sterilization-validation', 'sal', 'iso-11135', 'iso-11137'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Bioburden specification not linked to sterilization validation creates uncontrolled sterility assurance level risk.',
      regulatoryHook: 'ISO 11135:2014 EO sterilization; ISO 11137 radiation sterilization; 21 CFR 820.75',
      detectionMethod: `Review bioburden specification derivation documentation against sterilization validation dose-setting study reports.`,
      remediationPath: `Conduct dose-setting bioburden characterization study and re-derive specification with documented SAL linkage.`,
      estimatedCost: '$90K–$250K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '39% of device manufacturers have bioburden specifications not formally linked to sterilization validation data.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1493',
    name: 'Environmental Monitoring Excursion Investigation Closed Without Root Cause',
    description: 'Environmental monitoring excursions in critical and controlled cleanroom zones are closed on the CAPA system with corrective actions but without identified root cause, allowing repeat contamination events from the same unresolved source.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['environmental-monitoring', 'cleanroom', 'capa', 'root-cause', 'microbial-excursion'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'EM excursions closed without root cause enable recurring contamination from unresolved environmental sources.',
      regulatoryHook: '21 CFR 820.100 CAPA; ISO 13485:2016 §8.5.2; FDA Aseptic Processing Guidance 2004',
      detectionMethod: 'Review EM excursion CAPA records for root cause field completeness and trend repeat events by zone and organism.',
      remediationPath: `Re-open all closed excursion CAPAs lacking root cause and require QA director sign-off on cause determination.`,
      estimatedCost: '$40K–$110K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '48% of cleanroom environmental excursion CAPAs at device sites are closed without documented root cause.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1494',
    name: 'Media Fill Failure Investigation Does Not Include Aseptic Technique Review',
    description: 'Media fill failure investigations focus exclusively on equipment and environmental factors while omitting systematic review of aseptic gowning, personnel behavior, and aseptic technique as potential root cause contributors.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['media-fill', 'aseptic-technique', 'process-simulation', 'investigation', 'iso-13408'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Media fill investigations omitting aseptic technique leave human-factor contamination routes unexamined and uncontrolled.',
      regulatoryHook: 'FDA Aseptic Processing Guidance 2004; ISO 13408-1 aseptic processing; 21 CFR 820.100',
      detectionMethod: 'Audit media fill investigation reports for evidence of aseptic technique and personnel behavior review.',
      remediationPath: 'Revise media fill investigation SOP to mandate aseptic technique assessment and video review where cameras are installed.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '53% of media fill investigations at device sites lack a documented aseptic technique review component.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1495',
    name: 'Cleanroom Classification Maintenance Monitoring Not Performed at Defined Frequency',
    description: 'ISO 13485 and ISO 14644 require periodic re-classification particle count testing; site records show testing performed at irregular intervals exceeding the documented schedule, allowing cleanroom classification to lapse without detection.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['cleanroom-classification', 'iso-14644', 'particle-counting', 'iso-13485', 'environmental-monitoring'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Irregular re-classification testing intervals allow cleanroom performance degradation to persist undetected.',
      regulatoryHook: 'ISO 14644-2:2015 cleanroom monitoring; ISO 13485:2016 §6.3; 21 CFR 820.70',
      detectionMethod: 'Pull classification test date records and compare actual intervals against SOP-defined frequency for all zones.',
      remediationPath: 'Implement calendar-based scheduling system with automated overdue alerts and QA escalation for missed classifications.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '31% of device cleanroom facilities have documented instances of classification testing interval overruns.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1496',
    name: 'Contamination Control Strategy Document Not Aligned with Risk Assessment',
    description: `The site contamination control strategy document lists control measures but is not traceable to a formal risk assessment, leaving gaps between identified contamination hazards and the control measures nominally assigned to mitigate them.`,
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['contamination-control-strategy', 'risk-assessment', 'annex-1', 'iso-13485', 'fda-guidance'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'microbiological-control',
    data: {
      failureMode: `Contamination control strategy not linked to risk assessment allows hazard-to-control traceability gaps to go undetected.`,
      regulatoryHook: 'EU Annex 1 2022 Contamination Control Strategy; ISO 13485:2016 §7.1; FDA Aseptic Processing Guidance 2004',
      detectionMethod: 'Map each CCS control measure to a corresponding risk assessment hazard entry and flag unlinked controls.',
      remediationPath: 'Rebuild CCS with explicit bidirectional traceability to formal risk assessment and assign QA owner for annual review.',
      estimatedCost: '$55K–$150K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '46% of device sites operating aseptic processes lack a risk-traceable contamination control strategy document.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1497',
    name: 'Personnel Bioburden Contribution Not Assessed in Environmental Monitoring Program',
    description: 'The environmental monitoring program samples surfaces and air but does not include fingertip, glove, or garment contact plates to characterize personnel-sourced bioburden contribution in critical manufacturing zones.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['personnel-monitoring', 'fingertip-testing', 'bioburden', 'environmental-monitoring', 'aseptic-processing'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Absent personnel contact monitoring leaves human-sourced contamination as an unquantified EM program gap.',
      regulatoryHook: 'FDA Aseptic Processing Guidance 2004 Annex 1; ISO 13408-1; 21 CFR 820.70',
      detectionMethod: 'Review EM program sampling plan for presence of personnel contact monitoring types and frequency definitions.',
      remediationPath: 'Add fingertip and gown contact plates to EM program with alert and action limits, and train personnel on compliance.',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '35% of Class II/III device manufacturers omit personnel contact monitoring from their EM programs.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1498',
    name: 'Microbial Identification Not Performed on Environmental Monitoring Isolates',
    description: 'Environmental monitoring excursion isolates are counted and reported but not identified to genus and species level, preventing trend analysis by organism type and limiting investigation ability to trace contamination sources.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['microbial-identification', 'environmental-monitoring', 'maldi-tof', 'organism-trending', 'contamination-investigation'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Unidentified EM isolates prevent organism-level trending and source attribution in contamination investigations.',
      regulatoryHook: 'FDA Aseptic Processing Guidance 2004; USP <1116>; ISO 13408-1',
      detectionMethod: 'Audit EM excursion records for organism identification data and calculate proportion of excursions without species ID.',
      remediationPath: 'Establish microbial identification procedure using MALDI-TOF or equivalent and apply retroactively to stored isolates.',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '43% of device EM programs do not perform routine organism identification on excursion isolates.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1499',
    name: 'Cleanroom Gowning Qualification Not Periodically Re-evaluated for Operators',
    description: 'Operator cleanroom gowning qualification is performed once at onboarding and never re-evaluated, allowing gowning technique to degrade over time without detection by the quality system.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['gowning-qualification', 'cleanroom-personnel', 'requalification', 'training', 'aseptic-technique'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'One-time gowning qualification without re-evaluation allows aseptic technique degradation to go undetected and uncorrected.',
      regulatoryHook: 'FDA Aseptic Processing Guidance 2004; ISO 13485:2016 §6.2; 21 CFR 820.25',
      detectionMethod: 'Pull gowning qualification records for all active cleanroom operators and identify those lacking re-evaluation within 12 months.',
      remediationPath: 'Establish annual gowning re-qualification program with pass/fail criteria and link to personnel EM trend review.',
      estimatedCost: '$20K–$50K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '37% of device facilities have no defined periodic re-qualification requirement for cleanroom gowning.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1500',
    name: 'Water System Bioburden Alert Limits Not Action-Linked in SOP',
    description: 'Purified water system bioburden monitoring produces alert limit excursions that are logged but not tied to defined actions in the applicable SOP, leaving the response to individual operator discretion rather than a consistent quality system response.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['water-system', 'bioburden-alert', 'purified-water', 'alert-action-limits', 'iso-13485'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Alert limits without defined SOP actions allow water system bioburden drift to progress to action level before response.',
      regulatoryHook: 'USP <1231> water for pharmaceutical purposes; ISO 13485:2016 §7.5; 21 CFR 820.70',
      detectionMethod: 'Review water system SOP for alert limit response instructions and audit historical excursions for response documentation.',
      remediationPath: `Define tiered alert and action limit response procedures in water system SOP with mandatory QA notification at alert level.`,
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '28% of device facilities have water system monitoring programs with alert limits lacking defined response procedures.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1501',
    name: 'Endotoxin Testing Not Included in Environmental Monitoring for Injectable-Adjacent Processes',
    description: 'Manufacturing processes for devices with blood-contacting or injectable-adjacent characteristics rely on bioburden testing alone, omitting endotoxin monitoring that would detect gram-negative contamination not visible in standard colony count methods.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['endotoxin', 'lal-testing', 'injectable-device', 'environmental-monitoring', 'iso-11135'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Omitting endotoxin testing from EM for injectable-adjacent devices leaves pyrogen contamination risk uncontrolled.',
      regulatoryHook: 'FDA Guidance on Bacterial Endotoxins; USP <85>; 21 CFR 820.70; ISO 11135',
      detectionMethod: 'Review device classification and intended use against EM program scope to identify missing endotoxin monitoring requirements.',
      remediationPath: 'Add LAL or recombinant factor C endotoxin testing to EM program for all injectable-adjacent product families.',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '34% of injectable-adjacent device manufacturers lack endotoxin monitoring in their environmental monitoring program.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1502',
    name: 'Disinfectant Efficacy Qualification Not Re-performed After Formulation Change',
    description: 'Cleanroom disinfectants are re-sourced from a new supplier with a reformulated product; the site continues using previous efficacy qualification data without re-qualifying the new formulation against the site organism library.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['disinfectant-qualification', 'cleanroom-disinfection', 'supplier-change', 'efficacy-testing', 'contamination-control'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Unqualified disinfectant reformulation may inadequately control site-resident organisms, creating undetected contamination risk.',
      regulatoryHook: 'FDA Aseptic Processing Guidance 2004; PDA Technical Report No. 70; ISO 13485:2016 §7.5.6',
      detectionMethod: 'Audit disinfectant qualification records for re-qualification following supplier or formulation changes in the past 36 months.',
      remediationPath: 'Re-qualify the new disinfectant formulation against all site EM isolate organisms before resuming routine use.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '26% of device sites fail to re-qualify disinfectants after a supplier change introduces a reformulated product.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1503',
    name: 'Positive Environmental Monitoring Results Not Trended for Seasonal Patterns',
    description: 'Environmental monitoring positive results are reviewed individually at the time of excursion but are not analyzed for seasonal or cyclical patterns that could indicate HVAC, humidity, or personnel headcount-related contamination drivers.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['em-trending', 'seasonal-analysis', 'hvac', 'contamination-trending', 'product-quality-review'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'microbiological-control',
    data: {
      failureMode: 'Absence of seasonal EM trending delays recognition of HVAC or environmental contributors to recurring contamination.',
      regulatoryHook: '21 CFR 820.100; ISO 13485:2016 §8.2.6 product quality review; FDA Aseptic Processing Guidance 2004',
      detectionMethod: 'Request 24 months of EM data and perform time-series analysis to test for seasonal excursion clustering.',
      remediationPath: 'Add seasonal pattern analysis to annual product quality review and investigate any statistically significant temporal clusters.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '56% of device EM programs do not include seasonal trend analysis in their routine data review.',
      aiInsertionRisk: false,
    },
  },

  // ── component-incoming-quality (M1504–M1515) ─────────────────────────────

  {
    code: 'M1504',
    name: 'Critical Component Qualification Relies Solely on Supplier Quality Agreement',
    description: 'Critical component qualification files contain a supplier quality agreement and a single initial lot acceptance test but lack on-site qualification testing, design-of-experiments data, or independent performance verification for components with direct patient contact.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['component-qualification', 'supplier-quality-agreement', 'incoming-quality', '21-cfr-820', 'critical-component'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Relying on supplier agreements without independent qualification testing leaves critical component performance unverified.',
      regulatoryHook: '21 CFR 820.50 purchasing controls; 21 CFR 820.80; ISO 13485:2016 §7.4',
      detectionMethod: 'Audit critical component qualification files for independent on-site performance verification testing records.',
      remediationPath: 'Establish risk-tiered component qualification protocol requiring on-site testing for all critical patient-contact components.',
      estimatedCost: '$80K–$220K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '43% of device manufacturers have critical components qualified solely through supplier documentation without on-site verification.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1505',
    name: 'Certificate of Analysis Verification Limited to Visual Inspection of Header Fields',
    description: 'Incoming quality inspection verifies that the Certificate of Analysis is present and correctly addressed but does not compare reported test values against specification limits, allowing out-of-specification components to enter the manufacturing floor.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['coa-verification', 'incoming-inspection', 'acceptance-testing', '21-cfr-820-80', 'supplier-quality'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Superficial CoA review allows out-of-specification component values to pass incoming inspection undetected.',
      regulatoryHook: '21 CFR 820.80 receiving acceptance activities; ISO 13485:2016 §7.4.3',
      detectionMethod: 'Re-inspect a sample of accepted CoAs and verify each reported test value was checked against its corresponding specification.',
      remediationPath: 'Require value-level CoA verification against specifications with documented acceptance in IQC records.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '38% of incoming quality inspection procedures require presence verification only, not value-level CoA review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1506',
    name: 'Supplier Change Notification Not Triggering Impact Assessment for Critical Components',
    description: 'Approved suppliers submit change notifications for critical components but the site quality team lacks a documented impact assessment procedure, resulting in changes being acknowledged without formal evaluation of effect on device performance or required re-qualification.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['supplier-change-notification', 'impact-assessment', 'critical-component', '21-cfr-820-50', 'change-control'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Unassessed supplier changes allow component specification or material shifts to enter the supply chain without re-qualification.',
      regulatoryHook: '21 CFR 820.50 purchasing controls; ISO 13485:2016 §7.4.1; FDA Guidance on Supplier Controls',
      detectionMethod: 'Review supplier change notification log against change control records to identify notifications lacking formal impact assessment.',
      remediationPath: 'Implement risk-tiered supplier change notification SOP with mandatory impact assessment and re-qualification thresholds.',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '52% of device manufacturers lack a formal procedure for evaluating incoming supplier change notifications.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1507',
    name: 'Component Material Traceability Broken at Sub-Tier Supplier Level',
    description: 'Device manufacturers maintain traceability to their direct component suppliers but have no visibility into sub-tier raw material sourcing, creating a gap that prevents complete material traceability required under 21 CFR 820 and UDI regulations.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['material-traceability', 'sub-tier-supplier', 'supply-chain', '21-cfr-820', 'udi'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Sub-tier traceability gaps prevent complete supply chain visibility and complicate adverse event investigations.',
      regulatoryHook: '21 CFR 820.50; 21 CFR 820.184 device history record; FDA UDI regulations 21 CFR 830',
      detectionMethod: 'Request sub-tier supplier and raw material certificates from critical component suppliers and assess traceability completeness.',
      remediationPath: 'Extend supplier quality agreements to require sub-tier raw material certificates and integrate into device history records.',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '6–18 months',
      industryBenchmark: '61% of device manufacturers report incomplete sub-tier material traceability for at least one critical component family.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1508',
    name: 'FDA 21 CFR 820.80 Incoming Acceptance Records Incomplete for Externally Manufactured Components',
    description: 'Incoming acceptance activity records for externally manufactured subassemblies contain inspection results but lack the lot number, quantity, date received, and identified person fields required by 21 CFR 820.80(e), creating incomplete device history records.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['21-cfr-820-80', 'incoming-acceptance-records', 'device-history-record', 'subassembly', 'documentation'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Incomplete incoming acceptance records create device history record gaps that fail 21 CFR 820.80(e) requirements.',
      regulatoryHook: '21 CFR 820.80(e) incoming acceptance activity records; 21 CFR 820.184 device history record',
      detectionMethod: 'Audit a random sample of incoming acceptance records for completeness against all required 820.80(e) data fields.',
      remediationPath: 'Update incoming inspection forms and ERP receiving screens to enforce all 820.80(e) mandatory fields before record closure.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '33% of device incoming inspection records contain at least one missing 21 CFR 820.80(e) required field.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1509',
    name: 'Approved Supplier List Not Reviewed After Supplier Quality System Certification Expiry',
    description: 'Suppliers on the Approved Supplier List (ASL) have allowed their ISO 13485 or ISO 9001 certifications to expire without triggering an ASL re-evaluation, and the quality system lacks an automated alert for certification expiry.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['approved-supplier-list', 'supplier-certification', 'iso-13485', '21-cfr-820-50', 'supplier-qualification'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Expired supplier certifications on the ASL undermine the quality basis for supplier approval without triggering review.',
      regulatoryHook: '21 CFR 820.50 purchasing controls; ISO 13485:2016 §7.4.1',
      detectionMethod: 'Pull ASL certification expiry dates and identify all suppliers where certification lapsed without documented re-evaluation.',
      remediationPath: 'Implement 90-day automated expiry alert in QMS and suspend ASL status for suppliers with lapsed certification pending review.',
      estimatedCost: '$25K–$65K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '29% of device manufacturer ASLs contain at least one supplier with an expired quality system certification.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1510',
    name: 'Skip-Lot Testing Program Not Supported by Statistical Performance Data',
    description: 'The incoming quality control program uses skip-lot testing for several critical component families without documented supplier performance data meeting the statistical reliability threshold required to justify reduced inspection frequency.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['skip-lot-testing', 'incoming-inspection', 'statistical-basis', '21-cfr-820-80', 'supplier-performance'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Statistically unjustified skip-lot testing exposes the manufacturer to undetected component defects entering production.',
      regulatoryHook: '21 CFR 820.80; ANSI/ASQ Z1.4 sampling procedures; ISO 13485:2016 §7.4.3',
      detectionMethod: 'Review skip-lot justification files for statistical performance data meeting defined reliability thresholds.',
      remediationPath: 'Require documented statistical justification for all skip-lot programs and revert to full inspection where data is absent.',
      estimatedCost: '$35K–$90K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '44% of device manufacturers using skip-lot programs lack statistical performance data supporting reduced inspection frequency.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1511',
    name: 'Incoming Inspection Sampling Plan AQL Not Risk-Stratified by Component Criticality',
    description: 'All incoming components regardless of criticality are inspected at the same AQL level, applying the same statistical rigor to commodity packaging as to patient-contact critical components, undersampling the latter relative to risk.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['aql-sampling', 'risk-stratification', 'incoming-inspection', 'critical-component', 'ansi-z1-4'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Uniform AQL regardless of criticality under-inspects high-risk components relative to their patient safety impact.',
      regulatoryHook: '21 CFR 820.80; ANSI/ASQ Z1.4; ISO 13485:2016 §7.4.3 risk-based approach',
      detectionMethod: 'Map component risk classifications to current AQL assignments and identify misalignments between risk and inspection intensity.',
      remediationPath: 'Implement risk-tiered AQL matrix assigning tighter acceptance levels to critical and patient-contact components.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '48% of device incoming inspection programs apply uniform AQL across all component risk tiers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1512',
    name: 'Component Shelf Life Verification Not Performed at Incoming Inspection',
    description: 'Incoming inspection accepts components and raw materials without verifying remaining shelf life against the minimum required for the production cycle, resulting in short-dated materials entering controlled storage and potentially expiring before use.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['shelf-life', 'expiry-verification', 'incoming-inspection', 'controlled-storage', '21-cfr-820'],
    failure_rate_pct: 45.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Omitting shelf life checks at receiving allows short-dated components to enter storage and risk expiry-in-use.',
      regulatoryHook: '21 CFR 820.80; 21 CFR 820.150 storage; ISO 13485:2016 §6.4.2',
      detectionMethod: 'Review incoming inspection records for shelf life verification steps and audit recently accepted lots for remaining life.',
      remediationPath: 'Add minimum remaining shelf life verification as a mandatory incoming inspection step with hold for non-conforming materials.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '27% of device manufacturers omit remaining shelf life verification from their incoming inspection procedures.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1513',
    name: 'Supplier Corrective Action Requests Not Tracked to Verified Closure',
    description: 'Supplier corrective action requests (SCARs) are issued following component quality failures but the quality system does not track SCAR responses to verified closure, allowing suppliers to submit responses that are acknowledged but never verified effective.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['scar', 'supplier-corrective-action', 'supplier-quality', 'capa', '21-cfr-820-50'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'SCARs closed without verified effectiveness allow recurrence of supplier-origin component defects.',
      regulatoryHook: '21 CFR 820.50 purchasing controls; 21 CFR 820.100 CAPA; ISO 13485:2016 §8.5.2',
      detectionMethod: 'Pull open and recently closed SCAR register and identify records closed without documented verification of effectiveness.',
      remediationPath: 'Implement SCAR closure gate requiring QA review of verification lot data before the SCAR status updates to verified closed.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '49% of device SCAR programs lack a defined and documented effectiveness verification step before closure.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1514',
    name: 'Non-Conforming Component Disposition Not Performed by Authorized Personnel',
    description: 'Incoming non-conforming component disposition decisions including use-as-is, rework, and rejection are made by production supervisors without documented quality engineering authority delegation, violating the independence requirement of 21 CFR 820.80(b).',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['non-conforming-material', 'disposition', '21-cfr-820-80', 'mrb', 'authorized-personnel'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Unauthorized disposition decisions undermine QA independence and create accountability gaps in non-conforming material control.',
      regulatoryHook: '21 CFR 820.80(b) procedures; 21 CFR 820.86 acceptance status; ISO 13485:2016 §8.3',
      detectionMethod: 'Audit non-conforming material records for dispositioner identity against the approved MRB authority delegation list.',
      remediationPath: 'Publish and enforce a formal MRB authority matrix restricting disposition decisions to QA-authorized personnel.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '31% of device quality audits identify disposition decisions made outside the authorized MRB authority matrix.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1515',
    name: 'Incoming Inspection Results Not Fed Back Into Supplier Performance Scorecard',
    description: 'Incoming inspection rejection data is captured in the quality management system but is not systematically summarized and communicated to suppliers through a performance scorecard, depriving suppliers of quality feedback and removing accountability incentives.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['supplier-scorecard', 'supplier-performance', 'incoming-inspection', '21-cfr-820-50', 'supplier-quality'],
    failure_rate_pct: 51.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'component-incoming-quality',
    data: {
      failureMode: 'Failure to feed inspection results into supplier scorecards removes the performance accountability loop from the supply chain.',
      regulatoryHook: '21 CFR 820.50; ISO 13485:2016 §7.4.1 supplier evaluation; FDA Guidance on Supplier Controls',
      detectionMethod: 'Request supplier scorecard records for the top 10 critical component suppliers and verify incoming rejection data is reflected.',
      remediationPath: 'Automate monthly scorecard generation from incoming inspection QMS data and formalize quarterly supplier performance reviews.',
      estimatedCost: '$25K–$65K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '45% of device manufacturers do not systematically share incoming inspection data with their critical component suppliers.',
      aiInsertionRisk: false,
    },
  },

  // ── change-control-manufacturing (M1516–M1527) ───────────────────────────

  {
    code: 'M1516',
    name: 'Manufacturing Change Risk Assessment Excludes Process Failure Mode Analysis',
    description: 'Change control risk assessments evaluate design impact and regulatory submission triggers but omit process FMEA review, leaving unassessed whether the change introduces new process failure modes or degrades existing process controls.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['change-control', 'risk-assessment', 'pfmea', '21-cfr-820-30', 'iso-14971'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Change control risk assessments missing process FMEA review allow new manufacturing failure modes to go unmitigated.',
      regulatoryHook: '21 CFR 820.30 design controls; ISO 14971:2019 risk management; ISO 13485:2016 §7.3.9',
      detectionMethod: 'Audit manufacturing change records for evidence of process FMEA review and cross-reference against the pFMEA document.',
      remediationPath: 'Add mandatory pFMEA impact review step to change control form with QE sign-off before implementation approval.',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '55% of device change control programs do not require process FMEA review as part of the risk assessment.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1517',
    name: 'Post-Change Validation Scope Determined Without Risk Justification',
    description: 'Post-change validation scope decisions are made informally by production engineers without documented risk rationale, resulting in inconsistent validation scope assignments that range from full revalidation to no validation for similar change magnitudes.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['post-change-validation', 'change-control', 'risk-justification', '21-cfr-820-75', 'validation-scope'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Inconsistent validation scope decisions create unexplained variation in post-change quality evidence across similar changes.',
      regulatoryHook: '21 CFR 820.75; FDA Process Validation Guidance 2011; ISO 13485:2016 §7.5.6',
      detectionMethod: 'Compare validation scope assignments across 12 months of change records for comparable change types and document variance.',
      remediationPath: 'Implement a risk-tiered validation scope decision tree in the change control SOP with QA rationale documentation requirement.',
      estimatedCost: '$35K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '47% of device change control programs lack a defined algorithm for determining post-change validation scope.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1518',
    name: 'Regulatory Submission Trigger Determination Not Documented in Change Record',
    description: 'Manufacturing change records contain implementation approval but no documented determination of whether the change triggers a PMA supplement, 510(k) submission, or device listing update, leaving regulatory submission obligations to individual judgment.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['regulatory-submission', 'pma-supplement', '510k', 'change-control', '21-cfr-814-39'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Undocumented submission trigger determination risks manufacturing changes being implemented without required FDA notifications.',
      regulatoryHook: '21 CFR 814.39 PMA supplements; 21 CFR 807 510(k) requirements; FDA Guidance on Modifications to 510(k) Devices',
      detectionMethod: 'Audit change control records for submission determination field completion and flag records with blank or N/A entries.',
      remediationPath: 'Add mandatory regulatory submission determination step with RA sign-off to change control form for all manufacturing changes.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '58% of device change control records reviewed in FDA inspections lack a documented regulatory submission determination.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1519',
    name: 'Temporary Change Controls Converted to Permanent Without Revalidation',
    description: 'Temporary manufacturing changes issued to address material shortages or equipment downtime are converted to permanent status at expiry without performing the revalidation required for permanent process changes, circumventing the validation requirement.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['temporary-change-control', 'change-abuse', 'revalidation', '21-cfr-820-75', 'process-validation'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: `Temporary-to-permanent change conversion without revalidation bypasses the quality system's validation requirements.`,
      regulatoryHook: '21 CFR 820.75; 21 CFR 820.40 document controls; FDA Process Validation Guidance 2011',
      detectionMethod: 'Identify change records converted from temporary to permanent in the past 24 months and verify revalidation evidence.',
      remediationPath: 'Require full change control review including revalidation assessment upon any temporary change conversion to permanent.',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '34% of device change control systems allow temporary-to-permanent conversions without mandatory revalidation review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1520',
    name: 'Legacy Process Grandfather Status Not Reviewed After Design Change',
    description: 'Legacy manufacturing processes operating under grandfather status are not re-evaluated when design changes to the device affect the scope of processes they govern, leaving unreviewed processes potentially misaligned with current device design.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['legacy-process', 'grandfather-status', 'design-change', 'change-control', '21-cfr-820-75'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Unreviewed grandfather processes after design changes allow legacy process parameters to remain unaligned with current device design.',
      regulatoryHook: '21 CFR 820.75; 21 CFR 820.30(i) design changes; ISO 13485:2016 §7.3.9',
      detectionMethod: 'Cross-reference design change records against legacy process register to identify unreviewed scope intersections.',
      remediationPath: 'Add legacy process scope review as a required step in design change control with QE and QA sign-off.',
      estimatedCost: '$45K–$120K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '39% of device manufacturers have legacy processes that have not been reviewed following post-approval design changes.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1521',
    name: 'Manufacturing Change Implementation Without Updated Operator Training',
    description: 'Process changes are implemented and production resumes before affected operators complete updated SOP training, creating a window during which products are manufactured by personnel using outdated process knowledge.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['change-control', 'operator-training', 'sop-training', '21-cfr-820-25', 'change-implementation'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Production before change-related training completion exposes manufactured lots to operator knowledge gaps during the transition window.',
      regulatoryHook: '21 CFR 820.25 personnel requirements; 21 CFR 820.40; ISO 13485:2016 §6.2',
      detectionMethod: 'Compare change implementation dates against operator training completion records for post-change SOP versions.',
      remediationPath: 'Enforce production hold until all affected operators have completed and documented training on updated procedures.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of device change control implementations proceed to production before all affected operators complete updated training.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1522',
    name: 'Change Control Board Quorum Insufficient for Manufacturing Process Changes',
    description: 'Change control board meetings for manufacturing process changes proceed and approve changes with fewer attendees than specified in the CCB charter, recording minutes without the required quorum of quality, engineering, and regulatory representation.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['change-control-board', 'ccb-quorum', 'change-governance', '21-cfr-820-40', 'quality-management'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Below-quorum CCB approvals undermine cross-functional review integrity required by the change control governance charter.',
      regulatoryHook: '21 CFR 820.40 document controls; ISO 13485:2016 §7.3.9; internal CCB charter requirements',
      detectionMethod: 'Review CCB meeting minutes for the past 18 months and flag sessions where attendee records fall below charter quorum.',
      remediationPath: 'Invalidate below-quorum approvals and re-convene with required representation; revise scheduling to enforce quorum.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '24% of device CCB meeting records show changes approved without the quorum defined in the CCB governance charter.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1523',
    name: 'Emergency Change Escape Clause Used for Non-Emergency Process Modifications',
    description: 'The change control system includes an emergency change pathway with abbreviated review timelines; audit of the past 12 months reveals that routine process optimizations are regularly routed through the emergency pathway to avoid standard review cycles.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['emergency-change', 'change-control-bypass', 'change-governance', '21-cfr-820-40', 'audit-finding'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Overuse of emergency change pathways routes routine changes through abbreviated review, undermining standard quality gates.',
      regulatoryHook: '21 CFR 820.40 change controls; ISO 13485:2016 §4.2.4; internal SOP governance requirements',
      detectionMethod: 'Classify all emergency change records by stated justification and identify changes where urgency criteria are not met.',
      remediationPath: 'Define objective emergency change criteria and require QA director pre-authorization for any emergency change routing.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '31% of device change control audits find at least 20% of emergency changes lack genuine emergency justification.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1524',
    name: 'Process Change Effectiveness Review Not Scheduled Post-Implementation',
    description: 'Manufacturing process changes receive implementation approval and closure but no scheduled effectiveness review is triggered to verify the change achieved its intended outcome and did not introduce unintended quality effects.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['change-effectiveness', 'post-change-review', 'change-control', '21-cfr-820-100', 'capa'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Missing post-implementation effectiveness reviews leave the quality system unable to verify change outcomes or detect unintended effects.',
      regulatoryHook: '21 CFR 820.100 CAPA effectiveness; ISO 13485:2016 §8.5.2; internal change control SOP requirements',
      detectionMethod: 'Audit change control records for scheduled effectiveness review dates and completed review documentation.',
      remediationPath: 'Add mandatory effectiveness review scheduling to change control closure form with 90-day default review window.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '48% of device change control programs close changes without a scheduled post-implementation effectiveness review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1525',
    name: 'Concurrent Changes Assessed Independently Without Cumulative Risk Evaluation',
    description: 'Multiple simultaneous manufacturing process changes are each individually assessed as low risk without evaluating the cumulative or interactive risk of implementing several changes concurrently within the same product manufacturing line.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['concurrent-changes', 'cumulative-risk', 'change-control', 'iso-14971', 'risk-management'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Independent low-risk assessments for concurrent changes allow cumulative interactive risks to go unidentified and unmitigated.',
      regulatoryHook: 'ISO 14971:2019 §10 combined risk assessment; 21 CFR 820.30; ISO 13485:2016 §7.1',
      detectionMethod: 'Identify periods where multiple changes were implemented concurrently and audit for cumulative risk analysis documentation.',
      remediationPath: 'Implement a change portfolio review process requiring cumulative risk assessment when two or more changes affect the same product line.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '51% of device manufacturers do not perform cumulative risk evaluation for concurrent process changes on the same product line.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1526',
    name: 'Document Change Approval Obtained Before Impact Assessment Completion',
    description: 'Change records show document approval dates preceding the completion of engineering and quality impact assessments, indicating that document changes are signed off administratively before substantive review has occurred.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['document-change', 'impact-assessment', 'change-control-sequence', '21-cfr-820-40', 'document-management'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Out-of-sequence document approvals mean substantive change review is occurring after the change is administratively authorized.',
      regulatoryHook: '21 CFR 820.40 document controls; ISO 13485:2016 §4.2.4',
      detectionMethod: 'Compare impact assessment completion timestamps against document approval timestamps in change records.',
      remediationPath: 'Reconfigure the QMS workflow to enforce sequential approval gating that prevents document approval before assessment completion.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '27% of device document change control records show approval dates preceding impact assessment completion.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1527',
    name: 'Manufacturing Site Transfer Change Control Does Not Include Full Re-Qualification',
    description: 'Site transfer of a manufacturing process is managed through the standard change control procedure without invoking the full process re-qualification program required when a process transfers to a facility with different equipment, utilities, and environmental conditions.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['site-transfer', 'process-transfer', 'change-control', 're-qualification', '21-cfr-820-75'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'change-control-manufacturing',
    data: {
      failureMode: 'Treating site transfer as a routine change without full re-qualification leaves the transferred process without demonstrated equivalence at the new site.',
      regulatoryHook: '21 CFR 820.75; FDA Process Validation Guidance 2011; ISPE Technology Transfer Guide',
      detectionMethod: 'Identify site transfer change records and verify each was supported by a full PPQ at the receiving facility.',
      remediationPath: 'Classify site transfers as Level 3 changes requiring full IQ/OQ/PQ re-qualification with explicit regulatory submission assessment.',
      estimatedCost: '$200K–$600K',
      timeToRemediate: '12–24 months',
      industryBenchmark: '28% of device site transfer change records lack a full process re-qualification at the receiving facility.',
      aiInsertionRisk: false,
    },
  },

  // ── serialization-track-trace (M1528–M1539) ──────────────────────────────

  {
    code: 'M1528',
    name: 'UDI Device Identifier Assignment Error Rate Exceeds Acceptable Threshold',
    description: 'UDI-DI assignment at the production line produces mislabeled units at a rate that exceeds the acceptable error threshold defined in the labeling quality plan, with errors detected only at final inspection rather than at the point of assignment.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['udi', 'udi-di', 'labeling-errors', '21-cfr-830', 'udi-rule'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'UDI-DI mislabeling above threshold with late-stage detection increases the risk of mislabeled devices reaching the market.',
      regulatoryHook: '21 CFR 830.50 UDI assignment; 21 CFR 801 labeling requirements; FDA UDI Rule Final Rule 2013',
      detectionMethod: 'Analyze production labeling error logs for UDI-DI assignment error rate and compare against labeling quality plan threshold.',
      remediationPath: 'Implement in-line barcode verification at point of UDI-DI assignment with automatic rejection of mislabeled units.',
      estimatedCost: '$80K–$220K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '26% of device manufacturers report UDI-DI assignment error rates above their internal labeling quality plan threshold.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1529',
    name: 'Production Records Do Not Capture UDI at Unit Level for Implantable Devices',
    description: 'Device history records for implantable devices capture lot-level UDI but do not link individual unit serial numbers to production records, preventing complete unit-level traceability required for post-market surveillance and adverse event investigation.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['udi-pi', 'unit-level-traceability', 'implantable-device', 'device-history-record', '21-cfr-830'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Lot-level-only UDI capture prevents unit-level traceability for implantables, compromising recall and adverse event investigation capability.',
      regulatoryHook: '21 CFR 830.50(c) implantable device UDI requirements; 21 CFR 820.184; FDA UDI Rule',
      detectionMethod: 'Review device history record structure for implantable devices and verify individual unit serial UDI-PI linkage.',
      remediationPath: 'Upgrade production tracking system to capture and link UDI-PI serial numbers to individual device history records.',
      estimatedCost: '$150K–$400K',
      timeToRemediate: '9–18 months',
      industryBenchmark: '39% of implantable device manufacturers have device history records that do not capture UDI at unit level.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1530',
    name: 'Serialization System Validation Does Not Cover All Label Format Configurations',
    description: 'The serialization system validation covers the primary label format but does not include all label format variants used across different device sizes, regulatory markets, and language versions, leaving unvalidated configurations in production use.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['serialization-validation', 'label-format', 'udi', '21-cfr-820-75', 'csv-validation'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Unvalidated label format configurations operate in production without quality evidence of serialization system performance.',
      regulatoryHook: '21 CFR 820.75; GAMP 5 computerized system validation; 21 CFR Part 11',
      detectionMethod: 'Enumerate all active label format configurations and cross-reference against serialization validation coverage scope.',
      remediationPath: 'Extend serialization validation to cover all active label format variants and establish format change validation trigger criteria.',
      estimatedCost: '$60K–$160K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '33% of device serialization system validations do not encompass all label format variants in production use.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1531',
    name: 'UDI Label Placement on Device Packaging Does Not Meet 21 CFR 801 Positioning Requirements',
    description: 'UDI labels on secondary packaging are positioned on a fold or in a location that becomes obscured when packaging is stacked in standard clinical storage configurations, failing the readability and accessibility requirements of 21 CFR 801.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['udi-label-placement', '21-cfr-801', 'label-readability', 'packaging', 'udi-rule'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Inaccessible UDI label placement in clinical storage configurations impairs point-of-care scanning and traceability.',
      regulatoryHook: '21 CFR 801.20 UDI on label; 21 CFR 801.45 readable label requirements; FDA UDI Rule',
      detectionMethod: 'Perform stacking and storage simulation tests for all packaging configurations and assess UDI label visibility.',
      remediationPath: 'Redesign secondary packaging to relocate UDI label to a face that remains visible in standard clinical stacking orientations.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '21% of device UDI labeling audits identify placement issues that reduce readability in real-world clinical storage.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1532',
    name: 'GUDID Submission Contains Stale Device Identifier Attributes After Label Update',
    description: 'Following a label update that changed device size and configuration attributes, the GUDID record was not updated within the required 30 days, causing the public-facing database to reflect outdated device characteristics inconsistent with the currently marketed label.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['gudid', 'udi-database', '21-cfr-830-300', 'label-update', 'fda-udi-rule'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Stale GUDID attributes after label change create a discrepancy between the marketed device and the public-access UDI database.',
      regulatoryHook: '21 CFR 830.300 GUDID submission requirements; FDA UDI Rule; 21 CFR 830.370 update obligations',
      detectionMethod: 'Compare current label attributes against GUDID database entries for all devices with label changes in the past 24 months.',
      remediationPath: `Implement label change SOP step requiring GUDID update within 5 business days and add GUDID verification to label change closure checklist.`,
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '44% of device manufacturers have at least one GUDID record that was not updated within 30 days of a label change.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1533',
    name: 'Serialization Data Not Backed Up With Sufficient Recovery Point Objective',
    description: 'The serialization system backup schedule provides a 48-hour recovery point objective, but a production serialization data loss event could require voiding and reissuing up to two days of serial numbers, creating traceability gaps in already-shipped product.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['serialization-backup', 'data-recovery', 'business-continuity', '21-cfr-820-70', 'csv-validation'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Insufficient backup RPO for serialization data creates a window where shipped device serial records could be irrecoverably lost.',
      regulatoryHook: '21 CFR 820.70 production controls; 21 CFR Part 11 electronic records; ISO 13485:2016 §4.2.5',
      detectionMethod: 'Review serialization system backup schedule, RPO definition, and most recent recovery test documentation.',
      remediationPath: 'Increase backup frequency to achieve an RPO of four hours or less and perform quarterly recovery testing.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '22% of device serialization systems operate with backup schedules providing greater than 12-hour recovery point objectives.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1534',
    name: 'Barcode Print Quality Verification Not Performed Inline for Every Unit',
    description: 'Linear and 2D barcode print quality verification is performed on a sampled basis rather than on every unit at the point of printing, allowing barcode quality degradation to produce non-scannable UDI labels on un-inspected units that reach distribution.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['barcode-verification', 'print-quality', 'udi-label', 'inline-inspection', 'iso-15415'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Sampled barcode quality verification allows non-scannable UDI labels on unverified units to pass through to distribution.',
      regulatoryHook: '21 CFR 801 UDI label readability; ISO 15415 2D barcode print quality; FDA UDI Rule',
      detectionMethod: 'Review barcode quality verification procedure for unit coverage rate and audit records for sample-based versus 100% inspection.',
      remediationPath: 'Install inline barcode readers at every labeling station to provide 100% print quality verification before packaging.',
      estimatedCost: '$90K–$250K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '38% of device labeling lines use sample-based rather than 100% inline barcode quality verification.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1535',
    name: 'UDI Carrier Not Readable After Sterilization Cycle in Validated Studies',
    description: 'Validation studies for UDI labels subject to EO or gamma sterilization show barcode grade degradation after the maximum validated sterilization cycle count, but the label specification has not been updated to require a sterilization-robust carrier.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['udi-sterilization', 'label-validation', 'barcode-durability', '21-cfr-801', 'iso-11135'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'UDI barcode grade failure post-sterilization creates unreadable traceability identifiers on sterilized finished devices.',
      regulatoryHook: '21 CFR 801.45 UDI readability; ISO 15223-1 symbols; ISO 11607 packaging for sterilization',
      detectionMethod: 'Review sterilization validation label readability data for barcode grade at maximum cycle count against acceptance criteria.',
      remediationPath: 'Qualify a sterilization-resistant label carrier material and update the label specification to require its use.',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '29% of sterilized device products have UDI label validation data showing barcode grade degradation at maximum cycle exposure.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1536',
    name: 'Recalled Lot Serialization Data Not Available to Support Unit-Level Recall Scope Determination',
    description: `Recall events require unit-level serialization data to narrow the affected population, but the traceability system can only confirm lot-level distribution, forcing the manufacturer to execute a full lot recall rather than a targeted unit-level action.`,
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['recall', 'serialization', 'unit-level-traceability', '21-cfr-806', 'udi-pi'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Lot-level-only traceability forces overly broad recalls that impose unnecessary device shortages and patient access impacts.',
      regulatoryHook: '21 CFR 806 medical device reports; 21 CFR 830.50 UDI-PI; FDA Recall Guidance',
      detectionMethod: 'Simulate a unit-level recall scenario and assess whether the traceability system can identify individual affected units.',
      remediationPath: 'Implement UDI-PI unit-level serial tracking through distribution and link serialization data to distribution records.',
      estimatedCost: '$200K–$550K',
      timeToRemediate: '12–24 months',
      industryBenchmark: '53% of device manufacturers cannot execute a unit-level targeted recall without escalating to a full lot-level action.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1537',
    name: 'Serialization System Integration Gap Between ERP and Labeling System Creates Duplicate Serials',
    description: 'The interface between the ERP production order system and the labeling serialization engine has a synchronization fault that allows serial numbers to be re-issued when production orders are cancelled and re-opened, producing duplicate serial numbers in the field.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['serialization-integration', 'erp', 'duplicate-serial', 'labeling-system', '21-cfr-830'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'ERP–labeling system synchronization faults create duplicate serial numbers that corrupt device traceability records.',
      regulatoryHook: '21 CFR 830.50 UDI uniqueness; FDA UDI Rule; GAMP 5 interface validation',
      detectionMethod: 'Query serialization database for duplicate UDI-PI serial numbers and correlate with cancelled and reopened production orders.',
      remediationPath: 'Fix the ERP–labeling interface to flag cancelled order serial pools as retired and prevent re-issuance on any subsequent order.',
      estimatedCost: '$80K–$220K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '18% of device manufacturers using ERP-integrated serialization have documented instances of duplicate serial number generation.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1538',
    name: 'Aggregate UDI-DI Assignment for Device Kits Does Not Reflect Current Kit Contents',
    description: 'Device kits with an aggregate UDI-DI have had component contents revised through the change control process, but the aggregate UDI-DI GUDID record and labeling have not been updated to reflect the current kit configuration.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['aggregate-udi', 'device-kit', 'gudid', '21-cfr-830', 'kit-labeling'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'Stale aggregate UDI-DI records for modified kits create mismatches between marketed kit contents and GUDID database descriptions.',
      regulatoryHook: '21 CFR 830.50(b) aggregate UDI-DI; 21 CFR 830.300; FDA UDI Rule kit guidance',
      detectionMethod: 'Compare current kit bill of materials against aggregate UDI-DI GUDID records for all kit configurations changed in the past 36 months.',
      remediationPath: 'Update GUDID aggregate records and labeling to reflect current kit contents and add UDI update to kit change control checklist.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '32% of device kit manufacturers have aggregate UDI-DI records that no longer accurately reflect current kit configuration.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M1539',
    name: 'Traceability From UDI to Manufacturing Lot Not Bidirectional in QMS',
    description: 'The quality management system supports forward traceability from lot to UDI but does not support reverse lookup from a UDI-PI scan back to the originating manufacturing lot, production record, and component lot genealogy, impairing adverse event investigation speed.',
    vertical: 'medtech',
    office_category: 'Manufacturing Operations',
    keywords: ['bidirectional-traceability', 'udi-to-lot', 'device-history-record', '21-cfr-820-184', 'adverse-event'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'serialization-track-trace',
    data: {
      failureMode: 'One-directional traceability from UDI prevents rapid adverse event investigation lookups from field-reported serial numbers to manufacturing data.',
      regulatoryHook: '21 CFR 820.184 device history record; 21 CFR 803 MDR requirements; FDA UDI Rule traceability expectations',
      detectionMethod: 'Perform a reverse UDI-PI lookup test and measure time-to-complete manufacturing genealogy retrieval against the adverse event response SLA.',
      remediationPath: 'Implement reverse UDI-PI lookup capability in QMS linking serialized units to full manufacturing lot and component genealogy.',
      estimatedCost: '$100K–$280K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '47% of device QMS platforms do not support reverse UDI-PI to manufacturing genealogy lookup in under 30 minutes.',
      aiInsertionRisk: false,
    },
  },

];
