interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const BANKING_DOM10_KYC_ONBOARDING_PART7_PATTERNS: PatternSeed[] = [

  // ── transaction-monitoring-model-risk (B3160–B3171) ───────────────────────

  {
    code: 'B3160',
    name: 'Transaction Monitoring Scenario Coverage Gap Leaving High-Risk Typologies Undetected',
    description: `First Capital's transaction monitoring programme lacks scenarios covering structuring via cash-intensive businesses, leaving an entire category of placement-stage laundering undetected.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['transaction-monitoring', 'scenario-coverage', 'bsa-aml', 'typologies', 'fincen'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'TM scenario library omits cash-intensive business structuring, leaving a high-risk typology outside automated detection.',
      regulatoryHook: 'BSA 31 U.S.C. § 5318(h); FinCEN SAR guidance; FFIEC BSA/AML Examination Manual TM chapter',
      detectionMethod: 'Annual scenario coverage assessment mapped against FinCEN SAR typology library and FATF money laundering methods.',
      remediationPath: 'Design and deploy additional TM scenarios for missing typologies; validate with parallel back-testing before production activation.',
      estimatedCost: '$150K–$400K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '41% of mid-tier banks have at least one high-risk typology without a corresponding TM scenario.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3161',
    name: 'Threshold Calibration Documentation Absent for Core Transaction Monitoring Rules',
    description: 'First Capital cannot produce written rationale for the dollar thresholds set in its wire-transfer monitoring rules, failing examiners who require documented statistical or risk-based justification.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['threshold-calibration', 'transaction-monitoring', 'bsa-aml', 'model-documentation', 'examiner-readiness'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'TM alert thresholds were set historically without documented statistical rationale, creating an examiner-facing documentation gap.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual; OCC Bulletin 2011-12 model risk; SR 11-7 ongoing monitoring',
      detectionMethod: 'Model inventory audit cross-referencing TM rule parameters against threshold justification documentation in the model repository.',
      remediationPath: 'Conduct quantitative threshold analysis for all TM rules; document rationale in model cards; submit to MRC for approval.',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '49% of banks lack documented threshold calibration rationale for at least half of their TM rule set.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3162',
    name: 'SR 11-7 Model Validation Not Performed on Core Transaction Monitoring System',
    description: 'First Capital treats its vendor-supplied transaction monitoring platform as an off-the-shelf tool rather than a model, so no SR 11-7-compliant independent validation has ever been conducted.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['sr-11-7', 'model-validation', 'transaction-monitoring', 'model-risk-management', 'bsa-aml'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'TM system classified as "off-the-shelf software" in model inventory, bypassing SR 11-7 independent validation requirements.',
      regulatoryHook: 'SR 11-7 Model Risk Management Guidance; OCC Bulletin 2011-12; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'Model inventory classification review comparing TM system against SR 11-7 definition of model and validation history.',
      remediationPath: 'Reclassify TM system as a model; commission independent SR 11-7 validation including conceptual soundness and outcome analysis.',
      estimatedCost: '$200K–$600K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '37% of community and mid-tier banks have not performed SR 11-7 validation on their primary TM system.',
      aiInsertionRisk: true,
      aiRiskDescription: 'Unvalidated TM model increases risk of systematic miss as AI-enhanced typologies emerge.',
    },
  },
  {
    code: 'B3163',
    name: 'Alert Disposition Documentation Insufficient to Support SAR Declination Decisions',
    description: 'First Capital analysts close TM alerts with single-line notes that do not record the facts considered, leaving no defensible audit trail for regulators reviewing SAR declinations.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['alert-disposition', 'sar-declination', 'audit-trail', 'transaction-monitoring', 'bsa-aml'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'Alert closure notes lack the factual basis, sources consulted, and reasoning required to justify SAR non-filing decisions.',
      regulatoryHook: '31 U.S.C. § 5318(g); FinCEN SAR guidance; FFIEC BSA/AML Examination Manual alert management chapter',
      detectionMethod: 'Quality assurance review of closed alert documentation measuring completeness against a regulatory-defensibility scoring rubric.',
      remediationPath: 'Implement structured alert disposition form with mandatory fields; retrain analysts; conduct retrospective QA on prior-period closures.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '53% of banks receive examiner criticism for insufficient TM alert disposition documentation during BSA exams.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3164',
    name: 'Population Stability Testing Not Conducted After Core Banking System Migration',
    description: 'Following a core banking platform migration, First Capital did not re-run population stability index testing on its TM model, risking undetected drift in the monitored transaction population.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['population-stability-index', 'model-drift', 'transaction-monitoring', 'core-migration', 'model-risk'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'PSI testing was not triggered by the core system migration event, leaving TM model performance on the new data population unvalidated.',
      regulatoryHook: 'SR 11-7 ongoing monitoring and outcomes analysis; FFIEC BSA/AML Examination Manual model change management',
      detectionMethod: 'Change management log review confirming whether PSI testing was performed within 90 days of core system go-live.',
      remediationPath: 'Perform immediate PSI testing; assess whether threshold recalibration is required; document findings in model performance report.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '44% of banks do not trigger formal PSI testing after significant data infrastructure changes affecting the TM population.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3165',
    name: 'TM Scenario Tuning Process Lacks Independent Challenge Function',
    description: 'First Capital allows the same BSA operations team that runs daily TM alerts to approve scenario tuning changes without an independent model risk or compliance challenge step.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['scenario-tuning', 'independent-challenge', 'model-governance', 'transaction-monitoring', 'sr-11-7'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'Scenario tuning approvals are controlled entirely by BSA operations, violating SR 11-7 independence requirements for model changes.',
      regulatoryHook: 'SR 11-7 model validation independence; OCC Bulletin 2011-12; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'Model change governance log review confirming whether an independent validation or MRC sign-off was obtained for each tuning event.',
      remediationPath: 'Establish a formal model change process requiring independent review and MRC approval before any TM scenario parameter modification.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '38% of banks allow BSA operations personnel to approve TM tuning changes without independent oversight.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3166',
    name: 'False Positive Rate Benchmarking Not Performed Against Peer Institutions',
    description: 'First Capital has never benchmarked its TM false positive rate against peer bank data, so management cannot assess whether alert volumes indicate over-alerting or under-coverage.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['false-positive-rate', 'benchmarking', 'transaction-monitoring', 'model-performance', 'bsa-aml'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'Absence of peer benchmarking prevents management from identifying whether TM alert volumes reflect calibration failure or population characteristics.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual TM effectiveness; SR 11-7 outcome analysis and benchmarking',
      detectionMethod: 'BSA programme assessment comparing documented false positive rates and alert volumes against published FinCEN and industry survey data.',
      remediationPath: 'Engage industry consortia data or third-party benchmarking provider; document findings; use results to inform next threshold calibration cycle.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '60% of community banks have not formally benchmarked TM false positive rates against peer institutions.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3167',
    name: 'TM Model Risk Appetite Not Defined in Board-Approved BSA Policy',
    description: `First Capital's board-approved BSA policy is silent on TM model risk appetite, leaving the threshold between acceptable alert suppression and unacceptable coverage reduction undefined.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['model-risk-appetite', 'bsa-policy', 'board-governance', 'transaction-monitoring', 'sr-11-7'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'BSA policy contains no model risk appetite statement, making it impossible to evaluate whether TM tuning decisions remain within sanctioned bounds.',
      regulatoryHook: 'SR 11-7 model risk governance; OCC Heightened Standards 12 C.F.R. Part 30; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'BSA policy gap analysis confirming absence of quantified TM model risk appetite thresholds and escalation triggers.',
      remediationPath: 'Draft and obtain board approval for TM model risk appetite statement including false negative tolerance, tuning approval matrix, and escalation protocols.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '55% of banks lack an explicit board-approved TM model risk appetite statement in their BSA policy.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3168',
    name: 'Segmentation Model for TM Customer Risk Scoring Not Independently Validated',
    description: 'First Capital uses a proprietary customer risk segmentation model to assign TM monitoring intensity tiers, but this model has never received SR 11-7-compliant independent validation.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['customer-risk-segmentation', 'model-validation', 'sr-11-7', 'transaction-monitoring', 'bsa-aml'],
    failure_rate_pct: 69.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'Customer risk segmentation model driving TM tier assignment has never been independently validated, creating systemic blind spots for misclassified high-risk customers.',
      regulatoryHook: 'SR 11-7 Model Risk Management; FFIEC BSA/AML Examination Manual customer risk rating; FinCEN CDD Rule',
      detectionMethod: 'Model inventory reconciliation confirming validation status of all models feeding TM monitoring intensity decisions.',
      remediationPath: 'Commission independent SR 11-7 validation of segmentation model; remediate findings; re-score affected customer population.',
      estimatedCost: '$180K–$500K',
      timeToRemediate: '5–10 months',
      industryBenchmark: '43% of banks using proprietary customer risk segmentation models lack SR 11-7 validation for those models.',
      aiInsertionRisk: true,
      aiRiskDescription: 'Unvalidated segmentation model amplifies TM blind spots as AI-derived risk scores feed into monitoring tier logic.',
    },
  },
  {
    code: 'B3169',
    name: 'TM Alert Aging Exceeding 30-Day SLA Without Escalation Documentation',
    description: 'First Capital has unresolved TM alerts aged beyond 30 days with no documented escalation, creating an examiner-visible backlog that signals programme resource inadequacy.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['alert-aging', 'sla-breach', 'bsa-operations', 'transaction-monitoring', 'examiner-readiness'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'TM alert queue contains cases aged beyond the 30-day SLA with no escalation memo, signalling insufficient analyst capacity or triage failure.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual alert management; FinCEN SAR timing requirements (30 days from awareness); 12 C.F.R. § 21.11',
      detectionMethod: 'Case management system report extracting open alerts by age band and confirming presence or absence of escalation documentation.',
      remediationPath: 'Clear aged backlog with supervisor-level review; implement automated SLA breach escalation; assess staffing adequacy.',
      estimatedCost: '$50K–$160K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '34% of mid-tier banks have TM alert backlogs with cases exceeding 30-day resolution SLAs at any given time.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3170',
    name: 'Correspondent Banking Channels Excluded from TM Scenario Coverage',
    description: 'First Capital operates correspondent banking relationships but its TM scenario library does not include correspondent-specific typologies such as payable-through account misuse.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['correspondent-banking', 'transaction-monitoring', 'scenario-coverage', 'payable-through', 'bsa-aml'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'TM scenario library lacks correspondent banking-specific detection rules, leaving payable-through account abuse and nested correspondent risk unmonitored.',
      regulatoryHook: 'BSA 31 U.S.C. § 5318(i) correspondent accounts; FFIEC BSA/AML Examination Manual correspondent banking chapter; FinCEN guidance FIN-2006-G009',
      detectionMethod: 'Scenario-to-product mapping exercise confirming TM coverage for all products including correspondent and payable-through accounts.',
      remediationPath: 'Develop correspondent banking-specific TM scenarios; validate with back-testing; document in model change log.',
      estimatedCost: '$100K–$300K',
      timeToRemediate: '4–7 months',
      industryBenchmark: '29% of correspondent banking institutions lack dedicated TM scenarios for payable-through account typologies.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3171',
    name: 'Outcomes Analysis Not Linking TM Alerts to Confirmed SAR Filings for Effectiveness Measurement',
    description: 'First Capital does not systematically link TM alert outcomes to confirmed SAR filings, making it impossible to measure the detection effectiveness of individual monitoring scenarios.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['outcomes-analysis', 'sar-linkage', 'scenario-effectiveness', 'transaction-monitoring', 'sr-11-7'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'transaction-monitoring-model-risk',
    data: {
      failureMode: 'No data linkage exists between TM alerts and downstream SAR filings, preventing scenario-level effectiveness measurement required by SR 11-7.',
      regulatoryHook: 'SR 11-7 ongoing monitoring and outcome analysis; FFIEC BSA/AML Examination Manual TM effectiveness metrics',
      detectionMethod: 'Data lineage review confirming presence of a closed-loop reporting system tracing TM alert origin through SAR filing disposition.',
      remediationPath: 'Implement alert-to-SAR data linkage in case management system; produce quarterly effectiveness report by scenario; present to MRC.',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '47% of banks cannot produce a scenario-level SAR conversion rate report due to absent alert-to-SAR data linkage.',
      aiInsertionRisk: false,
    },
  },

  // ── ctr-sar-advanced (B3172–B3183) ────────────────────────────────────────

  {
    code: 'B3172',
    name: 'CTR Structuring Detection Scenario Does Not Cover Aggregation Across Multiple Branch Locations',
    description: 'First Capital detects single-location cash structuring but its CTR programme does not aggregate cash transactions across branches for the same customer on the same business day.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['ctr', 'structuring', 'aggregation', 'bsa-aml', 'fincen'],
    failure_rate_pct: 71.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'CTR aggregation logic is branch-siloed, allowing customers to structure below $10K across multiple First Capital locations without triggering a CTR.',
      regulatoryHook: '31 C.F.R. § 1010.311 currency transaction reporting; 31 U.S.C. § 5324 structuring prohibition; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'CTR system configuration audit testing whether multi-branch same-day aggregation for the same customer identity triggers correct CTR filing.',
      remediationPath: 'Reconfigure CTR aggregation logic to operate at the customer level across all branch locations; conduct retrospective look-back for missed filings.',
      estimatedCost: '$120K–$350K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '22% of multi-branch community banks have CTR aggregation gaps across branch locations for the same customer.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3173',
    name: 'SAR Narrative Quality Failing to Meet FinCEN 5W Standard for Regulatory Utility',
    description: `First Capital's SAR narratives frequently omit the who, what, when, where, and why elements required by FinCEN, reducing law enforcement utility and triggering examiner criticism.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['sar-narrative', 'fincen-5w', 'sar-quality', 'bsa-aml', 'law-enforcement'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'SAR narratives are brief and conclusory, omitting transaction-specific facts and failing FinCEN five-element narrative quality standards.',
      regulatoryHook: 'FinCEN SAR narrative guidance; 31 C.F.R. § 1020.320; FFIEC BSA/AML Examination Manual SAR quality chapter',
      detectionMethod: 'SAR quality assurance programme reviewing a random sample of filings against FinCEN five-element scoring rubric.',
      remediationPath: 'Retrain analysts using FinCEN SAR narrative guidance; implement QA checklist before SAR submission; track narrative quality scores quarterly.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '58% of BSA examiners cite SAR narrative inadequacy as a repeat finding across examined institutions.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3174',
    name: 'Law Enforcement Referral Process Not Documented for High-Priority SAR Cases',
    description: 'First Capital files SARs but has no written procedure for proactively referring high-priority cases to law enforcement, creating an engagement gap when FinCEN or FBI outreach is warranted.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['law-enforcement-referral', 'sar-process', 'fbi-outreach', 'fincen', 'bsa-aml'],
    failure_rate_pct: 51.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'BSA policy lacks a documented law enforcement referral decision framework, leaving high-priority SAR cases without a structured escalation path.',
      regulatoryHook: '31 U.S.C. § 5318(g); FinCEN guidance on voluntary law enforcement cooperation; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'BSA policy and procedure gap analysis confirming absence of documented criteria and steps for law enforcement referral of high-priority SARs.',
      remediationPath: 'Draft and approve a law enforcement referral SOP defining escalation triggers, approval authority, and outreach protocols.',
      estimatedCost: '$20K–$50K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '46% of community banks lack a documented law enforcement referral procedure in their BSA programme.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3175',
    name: 'FinCEN 314(a) Response Process Exceeding 14-Day Statutory Window',
    description: 'First Capital does not have a dedicated 314(a) response workflow and has missed the 14-day response window on multiple recent requests, creating potential examiner findings and cooperation failures.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['fincen-314a', 'information-sharing', 'bsa-aml', 'response-sla', 'examiner-findings'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'Absence of a dedicated 314(a) workflow results in requests being routed through general compliance queues, causing responses to miss the 14-day window.',
      regulatoryHook: '31 C.F.R. § 1010.520 section 314(a) information sharing; FinCEN 314(a) programme guidance; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'Log review of FinCEN secure information sharing portal response timestamps against request dates for all 314(a) inquiries in the past 12 months.',
      remediationPath: 'Create a dedicated 314(a) response SOP with named responsible officer; establish calendar reminders; test with historical request back-log.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '17% of community banks have missed the 314(a) 14-day response window at least once in the prior 12 months.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3176',
    name: 'SAR Continuation Filing Trigger Criteria Not Defined in Written Policy',
    description: `First Capital's SAR policy specifies initial filing requirements but provides no written criteria for determining when a continuation SAR must be filed for ongoing suspicious activity.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['sar-continuation', 'ongoing-suspicious-activity', 'bsa-aml', 'sar-policy', 'fincen'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'BSA policy is silent on continuation SAR triggers, leaving analysts without guidance on when the 90-day continuation window requires a new filing.',
      regulatoryHook: '31 C.F.R. § 1020.320(a)(2) continuing suspicious activity; FinCEN SAR guidance; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'BSA policy review confirming presence of documented continuation SAR trigger criteria and analyst guidance for open cases.',
      remediationPath: 'Amend BSA SAR policy to define continuation filing triggers; train analysts; implement case management system reminders at 90-day intervals.',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '39% of banks lack written continuation SAR criteria in their BSA SAR policy.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3177',
    name: 'CTR Exempt Person List Annual Review Not Completed Within Regulatory Timeframe',
    description: 'First Capital has not completed its annual review of Phase II CTR exemptions within the calendar year, risking stale exemptions remaining active for customers whose transaction profiles have changed.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['ctr-exemption', 'annual-review', 'phase-ii-exemption', 'bsa-aml', 'fincen'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'Phase II CTR exempt persons list was not reviewed within the required annual period, leaving outdated exemptions active for customers with changed activity patterns.',
      regulatoryHook: '31 C.F.R. § 1020.315(d) annual review requirement; FinCEN CTR exemption guidance; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'CTR exemption register audit confirming last-reviewed date for each Phase II exemption against the required annual review calendar.',
      remediationPath: 'Complete overdue annual reviews immediately; implement calendar-controlled reminders; assign BSA operations owner for exemption list maintenance.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '28% of banks with Phase II CTR exemptions fail to complete annual reviews within the required timeframe.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3178',
    name: 'SAR Safe Harbor Policy Not Communicated to Front-Line Staff Who May Receive Subpoenas',
    description: 'First Capital has a legal SAR safe harbor policy but it has not been communicated to branch and operations staff who could inadvertently disclose SAR existence when responding to customer or legal inquiries.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['sar-safe-harbor', 'tipping-off-prohibition', 'bsa-aml', 'front-line-training', 'fincen'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: `Front-line employees are unaware of the SAR safe harbor and tipping-off prohibition, creating disclosure risk when receiving customer account inquiries or subpoenas.`,
      regulatoryHook: '31 U.S.C. § 5318(g)(2) SAR confidentiality; FinCEN safe harbor guidance; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'Training records review confirming BSA safe harbor and tipping-off prohibition content in annual front-line training curriculum.',
      remediationPath: 'Add SAR safe harbor and tipping-off prohibition module to annual BSA training for all customer-facing and operations staff.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '35% of banks do not explicitly include SAR safe harbor and tipping-off prohibition content in front-line BSA training.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3179',
    name: 'CTR Filing Timeliness Breached Due to Manual Paper-Based Aggregation Process',
    description: 'First Capital relies on branch-level paper transaction logs that are manually aggregated centrally, causing recurring CTR filings to miss the 15-day regulatory deadline.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['ctr-timeliness', 'manual-process', 'aggregation-failure', 'bsa-aml', 'fincen'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'Manual paper-based CTR aggregation introduces processing delays that cause the 15-day filing deadline to be missed for a material share of reportable transactions.',
      regulatoryHook: '31 C.F.R. § 1010.306(a) CTR filing deadline; FFIEC BSA/AML Examination Manual; FinCEN CTR e-filing guidance',
      detectionMethod: 'CTR filing timeliness analysis measuring elapsed time from transaction date to FinCEN e-filing for all CTRs in the last 12 months.',
      remediationPath: 'Automate CTR aggregation through core banking system integration; eliminate paper logs; validate filing timeliness with production parallel run.',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '12% of community banks using manual CTR processes miss the 15-day filing deadline at least monthly.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3180',
    name: 'Shared Account SAR Attribution Logic Not Resolving to Beneficial Owner for FinCEN Reporting',
    description: 'First Capital reports the nominal account holder on SARs for shared or jointly-held accounts without determining whether the suspicious activity is attributable to a beneficial owner.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['sar-attribution', 'beneficial-owner', 'shared-account', 'fincen', 'bsa-aml'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'SAR subject identification defaults to the nominal account holder for shared accounts, potentially misattributing suspicious activity and reducing law enforcement utility.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230; SAR beneficial ownership reporting guidance; FFIEC BSA/AML Examination Manual',
      detectionMethod: 'SAR subject field audit for shared and jointly-held accounts confirming beneficial owner identification methodology.',
      remediationPath: 'Revise SAR procedures to require beneficial owner identification analysis for all non-individual or shared accounts before SAR subject field completion.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '31% of SAR filings for business accounts do not correctly attribute suspicious activity to the beneficial owner.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3181',
    name: 'Internal SAR Reporting Hotline Not Available to Front-Line Employees',
    description: 'First Capital lacks an internal anonymous SAR referral mechanism, requiring employees to identify themselves when reporting suspicious customer activity to BSA, which suppresses referral volume.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['internal-reporting', 'sar-referral', 'employee-hotline', 'bsa-aml', 'whistleblower'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'Absence of an anonymous internal SAR referral channel causes under-reporting of employee-observed suspicious activity due to identification reluctance.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual internal controls; BSA Board-level programme adequacy expectations; OCC Heightened Standards',
      detectionMethod: 'BSA programme assessment confirming whether an anonymous internal referral mechanism exists and is communicated in employee training.',
      remediationPath: 'Deploy anonymous internal BSA tip line or online referral form; incorporate in annual training; track and report referral volume to BSA committee.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '42% of community banks lack a dedicated anonymous internal SAR referral mechanism.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3182',
    name: 'SAR Decision Committee Quorum and Documentation Requirements Not Codified',
    description: 'First Capital convenes informal SAR decision meetings with no written quorum, voting, or documentation requirements, making the decision process non-auditable by examiners.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['sar-committee', 'decision-governance', 'bsa-aml', 'audit-trail', 'fincen'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'SAR decision committee has no codified quorum or documentation standards, producing informal meeting notes that cannot withstand examiner scrutiny.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual SAR decision process documentation; OCC Heightened Standards governance requirements',
      detectionMethod: 'BSA governance review confirming whether SAR committee charter documents quorum, attendance, voting thresholds, and minutes retention requirements.',
      remediationPath: 'Formalize SAR committee charter with quorum, documentation, and dissent-recording requirements; implement structured minutes template.',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '49% of banks with SAR committees lack a formal charter documenting quorum and decision-record requirements.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3183',
    name: 'Cryptocurrency Exchange Customers Lacking Dedicated SAR Typology Guidance for Analysts',
    description: 'First Capital banks cryptocurrency exchanges but its BSA analyst guidance does not include crypto-specific SAR typologies, resulting in under-detection of blockchain-enabled suspicious activity.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['cryptocurrency', 'sar-typologies', 'virtual-asset', 'bsa-aml', 'fincen'],
    failure_rate_pct: 73.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'ctr-sar-advanced',
    data: {
      failureMode: 'BSA analyst guidance lacks cryptocurrency-specific red flags and SAR typologies, leaving analysts without tools to identify blockchain-enabled suspicious activity.',
      regulatoryHook: 'FinCEN virtual currency guidance FIN-2019-G001; FFIEC BSA/AML Examination Manual virtual assets chapter; BSA/AML Act of 2020',
      detectionMethod: 'BSA analyst procedure review confirming presence of crypto-specific red flag indicators and typology examples aligned with FinCEN virtual currency guidance.',
      remediationPath: 'Develop crypto-specific BSA analyst typology guidance; add to TM scenario library; provide targeted training for accounts with crypto exchange customers.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '44% of banks with cryptocurrency exchange customers lack analyst-facing crypto-specific SAR typology guidance.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-driven transaction obfuscation in crypto networks requires continuously updated typology guidance to remain effective.',
    },
  },

  // ── de-risking-compliance (B3184–B3195) ───────────────────────────────────

  {
    code: 'B3184',
    name: 'Correspondent Banking De-Risking Decisions Not Documented with Risk-Based Rationale',
    description: 'First Capital has terminated several correspondent banking relationships without documenting the specific AML risk factors that justified termination, exposing it to ECOA and fair access claims.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['correspondent-banking', 'de-risking', 'documentation', 'bsa-aml', 'fair-access'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Correspondent account terminations lack documented risk-based rationale, creating regulatory exposure if decisions are challenged as discriminatory or arbitrary.',
      regulatoryHook: 'OCC Fair Access Rule; ECOA 15 U.S.C. § 1691; FFIEC BSA/AML Examination Manual correspondent banking; FinCEN de-risking guidance',
      detectionMethod: 'Correspondent account termination file review confirming documented risk assessment, alternatives considered, and business decision rationale.',
      remediationPath: 'Develop correspondent account exit documentation template capturing risk factors, alternatives assessed, and approving officer; apply retroactively to recent exits.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '38% of correspondent banking de-risking decisions lack documented risk-based rationale.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3185',
    name: 'MSB Policy Imposing Blanket Prohibition Without Individual Customer Risk Assessment',
    description: 'First Capital policy prohibits all money service business accounts as a category rather than requiring individual risk-based assessment, constituting over-restrictive de-risking per FinCEN guidance.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['msb', 'de-risking', 'blanket-prohibition', 'fincen', 'bsa-aml'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Categorical MSB prohibition in BSA policy substitutes blanket exclusion for individual risk assessment, directly contradicting FinCEN de-risking guidance.',
      regulatoryHook: 'FinCEN de-risking guidance FIN-2014-A007; FFIEC BSA/AML Examination Manual MSB chapter; OCC Fair Access Rule',
      detectionMethod: 'BSA policy review confirming whether MSB accounts require individual risk assessment or are subject to a categorical prohibition.',
      remediationPath: 'Revise BSA policy to replace categorical MSB prohibition with a risk-based assessment framework; develop MSB onboarding procedures.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '25% of community banks maintain categorical MSB prohibitions that conflict with FinCEN individual assessment guidance.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3186',
    name: 'De-Risking Policy Disparate Impact on Minority-Owned Businesses Not Assessed',
    description: 'First Capital has not conducted a disparate impact analysis of its de-risking decisions to determine whether account termination patterns disproportionately affect minority-owned businesses.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['de-risking', 'disparate-impact', 'ecoa', 'fair-lending', 'minority-business'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'De-risking account exit data has not been analyzed for disparate impact on protected classes, creating undetected ECOA and fair access legal exposure.',
      regulatoryHook: 'ECOA 15 U.S.C. § 1691; Reg B 12 C.F.R. Part 202; OCC Fair Access Rule; FFIEC BSA/AML Examination Manual fair lending intersection',
      detectionMethod: 'Disparate impact analysis comparing de-risking exit rates by customer demographic proxies against the bank\'s overall business account population.',
      remediationPath: 'Commission annual disparate impact analysis for de-risking decisions; report findings to fair lending committee; adjust policy if adverse impact identified.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '61% of banks have never conducted a disparate impact analysis on their BSA-driven account exit decisions.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3187',
    name: 'No Documented Assessment of Lower-Risk Alternatives Before High-Risk Customer Exits',
    description: 'First Capital exits high-risk customers without a documented analysis of whether enhanced due diligence or transaction restrictions could mitigate risk to an acceptable level.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['de-risking', 'edd-alternatives', 'customer-exit', 'bsa-aml', 'risk-mitigation'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Customer exit decisions bypass a documented alternatives analysis, making it impossible to demonstrate that less restrictive risk mitigants were considered.',
      regulatoryHook: 'FinCEN de-risking guidance; FFIEC BSA/AML Examination Manual; OCC Fair Access Rule alternatives assessment requirement',
      detectionMethod: 'Customer exit file review confirming whether an alternatives analysis document exists before the exit decision was approved.',
      remediationPath: 'Implement a mandatory alternatives assessment step in the customer exit workflow; require completion before exit approval is granted.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '52% of bank customer exit decisions lack a documented alternatives assessment.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3188',
    name: 'De-Risked Customer Notification Process Not Providing Adequate Advance Notice',
    description: 'First Capital provides only 10 days notice before exiting high-risk customers, which regulators and courts have found insufficient to allow customers to obtain replacement banking services.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['de-risking-notification', 'customer-exit-notice', 'bsa-aml', 'fair-access', 'due-process'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Ten-day exit notice is insufficient for customers to secure replacement financial services, potentially implicating unfair or deceptive practices standards.',
      regulatoryHook: 'OCC Fair Access Rule; UDAP 15 U.S.C. § 45; CFPB unfair acts or practices; FFIEC BSA/AML Examination Manual customer exit procedures',
      detectionMethod: 'Customer exit procedure review confirming notice periods provided and whether they meet 30-day industry best practice for non-emergency exits.',
      remediationPath: 'Revise customer exit procedure to provide minimum 30-day advance written notice except in emergency or immediate-risk cases with documented justification.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '33% of banks provide less than 30 days advance notice for non-emergency customer de-risking exits.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3189',
    name: 'PDAB Cash-Intensive Business De-Risking Policy Not Calibrated to Actual Transaction Risk',
    description: `First Capital's policy treating all cash-intensive businesses as automatically high-risk results in over-exclusion of legitimate businesses without risk-level differentiation based on transaction data.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['cash-intensive-business', 'de-risking', 'risk-calibration', 'bsa-aml', 'fincen'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Categorical cash-intensive business risk classification does not account for transaction-level data, over-identifying low-risk businesses as high-risk.',
      regulatoryHook: 'FinCEN de-risking guidance FIN-2014-A007; FFIEC BSA/AML Examination Manual customer risk rating; OCC Fair Access Rule',
      detectionMethod: 'Customer risk rating methodology review confirming whether cash-intensity triggers a presumptive risk rating or is an input to a multi-factor risk assessment.',
      remediationPath: 'Revise customer risk methodology to treat cash-intensity as one risk factor among several rather than an automatic high-risk designator.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '30% of banks apply a categorical cash-intensive business designation without transaction-level risk differentiation.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3190',
    name: 'Senior Management De-Risking Authority Threshold Not Defined in Policy',
    description: `First Capital's BSA policy does not specify which customer exit decisions require senior management or board approval, leading to inconsistent approval authority for high-profile de-risking decisions.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['de-risking-authority', 'approval-matrix', 'bsa-governance', 'senior-management', 'bsa-aml'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Undefined de-risking approval thresholds result in material customer exits being approved at the analyst level without senior management or board awareness.',
      regulatoryHook: 'OCC Heightened Standards 12 C.F.R. Part 30 senior management accountability; FFIEC BSA/AML Examination Manual governance; OCC Fair Access Rule',
      detectionMethod: 'BSA policy review confirming presence of a customer exit approval matrix with thresholds differentiating analyst, management, and board approval levels.',
      remediationPath: 'Define and implement a de-risking approval matrix in BSA policy keyed to customer relationship size, strategic significance, and community impact.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '44% of banks lack a documented approval authority matrix for customer de-risking decisions in their BSA policy.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3191',
    name: 'Charity and Nonprofit Customer De-Risking Without Sector-Specific Risk Assessment',
    description: 'First Capital exits charitable and nonprofit customers under blanket high-risk policy without assessing the specific FATF-identified risks applicable to the nonprofit sector.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['nonprofit', 'charity', 'de-risking', 'fatf', 'bsa-aml'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Nonprofit and charity customers are exited under a generic high-risk designation without the FATF Recommendation 8 sector-specific risk assessment that regulators expect.',
      regulatoryHook: 'FATF Recommendation 8; FinCEN de-risking guidance; FFIEC BSA/AML Examination Manual nonprofit sector; Treasury NPO risk assessment framework',
      detectionMethod: 'Customer exit file review for nonprofit entities confirming whether FATF Recommendation 8 sector-specific risk indicators were evaluated before exit.',
      remediationPath: 'Develop nonprofit-specific BSA risk assessment procedures aligned with FATF Recommendation 8; apply to all active and prospective nonprofit accounts.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '48% of banks apply categorical rather than FATF-aligned sector-specific risk assessments to nonprofit customers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3192',
    name: 'De-Risking Impact on Local Community Credit Access Not Measured or Reported',
    description: 'First Capital does not measure or report the community credit access impact of its de-risking decisions, creating CRA examination risk where account exits disproportionately affect underserved communities.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['de-risking', 'cra', 'community-access', 'fair-access', 'bsa-aml'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'De-risking exit data is never cross-referenced with CRA assessment area geography, leaving unmeasured the impact on community credit access.',
      regulatoryHook: 'Community Reinvestment Act 12 U.S.C. § 2903; OCC Fair Access Rule; FFIEC BSA/AML Examination Manual; CRA Interagency Q&A',
      detectionMethod: 'Geographic mapping of de-risked customer locations against CRA assessment area boundaries and LMI census tracts.',
      remediationPath: 'Establish annual CRA-BSA intersection reporting confirming whether de-risking decisions are concentrated in LMI assessment areas; present to CRA committee.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '57% of banks do not conduct CRA impact analysis on BSA-driven account exit decisions.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3193',
    name: 'Remittance Company De-Risking Policy Contradicting Federal Financial Inclusion Objectives',
    description: `First Capital's categorical exclusion of remittance companies conflicts with CFPB and Treasury financial inclusion objectives and FinCEN guidance directing risk-based rather than blanket exclusion.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['remittance', 'de-risking', 'financial-inclusion', 'fincen', 'cfpb'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'Categorical remittance company exclusion directly contradicts FinCEN de-risking guidance and CFPB financial inclusion objectives, creating multi-agency regulatory tension.',
      regulatoryHook: 'FinCEN de-risking guidance FIN-2014-A007; Dodd-Frank Act § 1073 remittance; CFPB remittance rule; Treasury financial inclusion strategy',
      detectionMethod: 'BSA policy review confirming whether remittance companies require individual risk assessment or face categorical exclusion.',
      remediationPath: 'Replace categorical remittance exclusion with a risk-based onboarding framework including EDD triggers and transaction volume monitoring.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '21% of community banks maintain categorical remittance company exclusions that conflict with FinCEN de-risking guidance.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3194',
    name: 'De-Risking Decisions Not Tracked for Regulatory Trend Reporting or Internal Escalation',
    description: 'First Capital does not aggregate de-risking decision data into a management report, preventing the BSA officer from identifying elevated exit trends that would signal programme-level risk elevation.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['de-risking', 'management-reporting', 'trend-analysis', 'bsa-governance', 'escalation'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'De-risking decision data is not aggregated into management reporting, leaving the BSA officer without trend visibility to detect programme-level risk changes.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual BSA officer responsibilities; OCC Heightened Standards management reporting; FDIC examination manual',
      detectionMethod: 'BSA management reporting inventory confirming whether a periodic de-risking trend report is produced and presented to the BSA committee.',
      remediationPath: 'Implement a quarterly de-risking trend report covering exit volume, sector distribution, and geographic concentration; present to BSA committee.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '53% of banks do not produce a management-level aggregate report tracking de-risking decision trends.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3195',
    name: 'Reputational Risk Review Not Integrated into High-Profile Customer De-Risking Decisions',
    description: 'First Capital makes de-risking exit decisions based solely on BSA risk without incorporating a reputational risk review for high-profile customers, creating post-exit media and stakeholder relationship risk.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['reputational-risk', 'de-risking', 'stakeholder-management', 'bsa-aml', 'governance'],
    failure_rate_pct: 45.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'de-risking-compliance',
    data: {
      failureMode: 'De-risking decisions for high-profile customers are not reviewed for reputational impact, creating post-exit media exposure and community stakeholder relationship damage.',
      regulatoryHook: 'OCC Heightened Standards 12 C.F.R. Part 30 risk management; FFIEC BSA/AML Examination Manual governance; OCC reputational risk guidance',
      detectionMethod: 'De-risking governance review confirming whether a reputational risk sign-off step exists for customer exits above defined relationship-size thresholds.',
      remediationPath: 'Add reputational risk review step to de-risking workflow for relationships above defined balance or community-profile thresholds.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '66% of banks do not include a formal reputational risk review in their customer de-risking decision workflow.',
      aiInsertionRisk: false,
    },
  },

  // ── pep-adverse-media-screening (B3196–B3207) ─────────────────────────────

  {
    code: 'B3196',
    name: 'PEP List Vendor Coverage Insufficient for Emerging Market Jurisdictions',
    description: `First Capital's PEP screening vendor does not cover government officials from high-risk emerging market jurisdictions, leaving material gaps in politically exposed person identification.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['pep-screening', 'vendor-coverage', 'emerging-markets', 'bsa-aml', 'cdd'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'PEP screening vendor list lacks coverage for government officials in high-risk emerging market jurisdictions, creating systematic PEP identification gaps.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230; FFIEC BSA/AML Examination Manual PEP chapter; FATF Recommendation 12',
      detectionMethod: 'PEP vendor coverage gap analysis testing list comprehensiveness against FATF high-risk jurisdiction government official databases.',
      remediationPath: 'Supplement primary PEP vendor with secondary list sources for high-risk emerging market jurisdictions; implement quarterly coverage gap review.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '34% of banks have material PEP list coverage gaps for high-risk emerging market jurisdictions.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3197',
    name: 'Adverse Media False Positive Tuning Suppressing Legitimate Risk Signals',
    description: 'First Capital has aggressively tuned adverse media screening to reduce alert volume, inadvertently suppressing legitimate risk signals by over-weighting false positive reduction at the expense of detection.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['adverse-media', 'false-positive-tuning', 'screening', 'bsa-aml', 'cdd'],
    failure_rate_pct: 69.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'Adverse media screening tuning prioritised alert volume reduction over detection effectiveness, suppressing legitimate risk signals for customers with negative news coverage.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual adverse media screening; FATF Recommendation 12 EDD; FinCEN CDD Rule',
      detectionMethod: 'Back-testing adverse media screening tuning parameters against a known-risk customer population to measure signal suppression rate.',
      remediationPath: 'Reset adverse media tuning parameters with a balanced false positive / false negative objective; validate with back-test before production deployment.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '28% of banks have adverse media tuning configurations that suppress material risk signals in exchange for reduced alert volume.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-generated adverse media content may bypass keyword-based tuning configurations, requiring semantic detection capability.',
    },
  },
  {
    code: 'B3198',
    name: 'EDD Review for PEP Customers Lacking Source of Wealth Verification Documentation',
    description: 'First Capital conducts EDD interviews for PEP customers but does not obtain or retain documentary evidence of source of wealth declarations, failing FATF Recommendation 12 standards.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['edd', 'pep', 'source-of-wealth', 'fatf', 'bsa-aml'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'PEP EDD files contain self-declared source of wealth without documentary corroboration, failing FATF Recommendation 12 and FinCEN CDD Rule depth requirements.',
      regulatoryHook: 'FATF Recommendation 12; FinCEN CDD Rule 31 C.F.R. § 1010.230; FFIEC BSA/AML Examination Manual PEP EDD chapter',
      detectionMethod: 'PEP EDD file review confirming whether source of wealth declarations are supported by documentary evidence such as tax filings, business records, or financial statements.',
      remediationPath: 'Revise PEP EDD procedure to require documentary evidence of source of wealth; conduct retrospective EDD refresh for existing PEP customers lacking documentation.',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '41% of banks conducting PEP EDD fail to obtain documentary source of wealth corroboration.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3199',
    name: 'PEP Family Member and Close Associate Screening Not Extended Beyond Immediate Relatives',
    description: `First Capital's PEP screening extends to spouses and children of identified PEPs but does not cover close business associates and known intermediaries as required by FATF Recommendation 12.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['pep', 'family-member-screening', 'close-associate', 'fatf', 'bsa-aml'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'PEP screening scope is limited to immediate family, missing close business associates and known intermediaries who may hold or move PEP-related funds.',
      regulatoryHook: 'FATF Recommendation 12 close associates; FFIEC BSA/AML Examination Manual PEP chapter; FinCEN CDD Rule beneficial ownership',
      detectionMethod: 'PEP screening procedure review confirming whether close associate and known intermediary identification is required beyond immediate family relationships.',
      remediationPath: 'Expand PEP screening scope to include close business associates and known intermediaries; update screening procedures and vendor configuration.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '37% of banks do not screen for close business associates and known intermediaries of identified PEP customers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3200',
    name: 'Domestic PEP Identification Programme Not Established for State and Local Government Officials',
    description: 'First Capital screens for foreign PEPs but lacks a formal domestic PEP identification programme for state and local government officials, leaving a category of elevated corruption risk unmanaged.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['domestic-pep', 'state-local-government', 'corruption-risk', 'bsa-aml', 'cdd'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'Absence of a domestic PEP programme for state and local officials leaves corruption risk from government-proximate customers outside the EDD framework.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual domestic PEP risk; FinCEN CDD Rule; FATF Recommendation 12 domestic PEPs; OCC BSA/AML examination manual',
      detectionMethod: 'Customer risk assessment methodology review confirming whether state and local government officials are captured within a domestic PEP identification framework.',
      remediationPath: 'Develop domestic PEP identification criteria and EDD procedures covering state and local government officials; apply to new and existing customers.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '49% of banks lack a formal domestic PEP identification programme for state and local government officials.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3201',
    name: 'Adverse Media Screening Frequency Insufficient for EDD Customers Between Annual Reviews',
    description: `First Capital screens EDD customers for adverse media annually but regulatory expectations and FATF guidance call for ongoing monitoring that would detect adverse media events between annual review cycles.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['adverse-media', 'ongoing-monitoring', 'edd', 'fatf', 'bsa-aml'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'Annual adverse media refresh for EDD customers allows material negative news events to go undetected for up to 12 months between scheduled reviews.',
      regulatoryHook: 'FATF Recommendation 12 ongoing monitoring; FFIEC BSA/AML Examination Manual EDD ongoing monitoring; FinCEN CDD Rule',
      detectionMethod: 'EDD programme design review confirming whether adverse media monitoring for EDD customers is continuous or only triggered at scheduled review intervals.',
      remediationPath: 'Implement continuous or quarterly adverse media screening for EDD customers; automate alert generation for significant adverse media events.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '44% of banks limit adverse media screening for EDD customers to annual scheduled reviews rather than ongoing monitoring.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3202',
    name: 'PEP Identification Dependent on Customer Self-Declaration Without Independent Verification',
    description: 'First Capital relies on customer self-declaration to identify PEPs during onboarding without independent screening against authoritative PEP databases, creating a systematic identification gap.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['pep-identification', 'self-declaration', 'independent-screening', 'bsa-aml', 'cdd'],
    failure_rate_pct: 75.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'PEP identification relies on customer self-declaration in onboarding forms without independent database screening, systematically missing non-disclosing PEPs.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230; FATF Recommendation 12; FFIEC BSA/AML Examination Manual PEP identification',
      detectionMethod: 'Onboarding workflow audit confirming whether PEP screening is performed against an authoritative database independent of customer self-declaration.',
      remediationPath: 'Implement automated PEP database screening for all new customer onboarding, replacing exclusive reliance on customer self-declaration.',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '18% of banks still rely on customer self-declaration as the primary PEP identification mechanism without independent database screening.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3203',
    name: 'Adverse Media Coverage in Non-English Languages Not Monitored for International Customers',
    description: `First Capital's adverse media screening is limited to English-language sources, leaving customers with international profiles and non-English adverse media coverage undetected.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['adverse-media', 'multilingual-screening', 'international-customers', 'bsa-aml', 'edd'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'English-only adverse media monitoring creates systematic blind spots for international customers with negative coverage in their home-country language press.',
      regulatoryHook: 'FATF Recommendation 12; FFIEC BSA/AML Examination Manual adverse media; FinCEN CDD Rule; OCC BSA/AML examination guidance',
      detectionMethod: 'Adverse media vendor configuration review confirming supported languages and coverage against a sample of high-risk international customer home-country press.',
      remediationPath: 'Upgrade adverse media vendor to include multilingual coverage, prioritising high-risk jurisdiction home languages; validate coverage for EDD customer population.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '39% of banks screen adverse media exclusively in English despite having international customer populations.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3204',
    name: 'PEP EDD Approval Not Escalated to Senior Management Before Account Opening',
    description: 'First Capital opens PEP accounts upon BSA analyst approval without escalating to a senior officer or committee, failing FATF Recommendation 12 senior management approval requirements.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['pep', 'edd-approval', 'senior-management', 'fatf', 'bsa-aml'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'PEP account openings are approved by BSA analysts without senior management or committee sign-off, directly violating FATF Recommendation 12 approval requirements.',
      regulatoryHook: 'FATF Recommendation 12 senior management approval; FFIEC BSA/AML Examination Manual PEP chapter; FinCEN CDD Rule',
      detectionMethod: 'PEP onboarding file review confirming approval authority level and whether senior management sign-off was obtained before account opening.',
      remediationPath: 'Revise PEP onboarding procedure to require senior officer or BSA committee approval before account opening; document approval in customer file.',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '27% of banks open PEP accounts without the FATF Recommendation 12-required senior management approval.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3205',
    name: 'Negative News Vendor Alert Dismissal Process Not Documented for Audit Trail',
    description: 'First Capital analysts dismiss adverse media alerts without creating a documented rationale record, preventing examiners from reconstructing the basis for false positive determinations.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['adverse-media', 'alert-dismissal', 'audit-trail', 'bsa-aml', 'documentation'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'Adverse media alert dismissals are recorded as binary pass/fail without a rationale field, making examiner reconstruction of false positive determinations impossible.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual adverse media documentation; FinCEN CDD Rule ongoing monitoring; FATF Recommendation 12',
      detectionMethod: 'Adverse media screening system review confirming whether alert dismissal records include structured rationale fields or only binary disposition codes.',
      remediationPath: 'Implement a structured adverse media dismissal rationale template; retrain analysts; conduct retrospective QA on prior-period dismissals.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '48% of banks using adverse media screening tools lack structured rationale documentation for alert dismissals.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3206',
    name: 'State-Owned Enterprise Beneficial Ownership Screening Not Applying PEP-Equivalent Treatment',
    description: 'First Capital does not apply PEP-equivalent EDD to state-owned enterprises, missing government-associated beneficial owners who present corruption and sanctions exposure comparable to direct PEPs.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['state-owned-enterprise', 'pep-equivalent', 'beneficial-ownership', 'bsa-aml', 'edd'],
    failure_rate_pct: 71.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'State-owned enterprise accounts are not subject to PEP-equivalent EDD, leaving government-affiliated beneficial owners outside the enhanced scrutiny framework.',
      regulatoryHook: 'FATF Recommendation 12; FinCEN CDD Rule 31 C.F.R. § 1010.230; FFIEC BSA/AML Examination Manual PEP and government entities',
      detectionMethod: 'Customer classification review confirming whether state-owned enterprises and government-linked entities trigger PEP-equivalent EDD procedures.',
      remediationPath: 'Extend PEP-equivalent EDD to state-owned enterprises and government-controlled entities; refresh existing accounts under the revised framework.',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '35% of banks do not apply PEP-equivalent EDD to state-owned enterprise customers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3207',
    name: 'PEP Status Re-Screening Not Triggered by Customer Occupation or Position Change',
    description: 'First Capital does not re-screen customers for PEP status when occupation change information is received during periodic CDD refresh, missing newly-appointed government officials in the existing customer base.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['pep-rescreening', 'occupation-change', 'cdd-refresh', 'bsa-aml', 'fincen'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pep-adverse-media-screening',
    data: {
      failureMode: 'CDD refresh processes capture occupation changes but do not trigger a PEP re-screening, allowing newly appointed government officials to remain outside the EDD framework.',
      regulatoryHook: 'FinCEN CDD Rule ongoing monitoring; FATF Recommendation 12; FFIEC BSA/AML Examination Manual PEP identification',
      detectionMethod: 'CDD refresh workflow review confirming whether occupation changes automatically trigger PEP database re-screening.',
      remediationPath: 'Configure CDD system to trigger automatic PEP re-screening whenever an occupation or employer change is recorded during periodic review.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '43% of banks do not trigger PEP re-screening when customer occupation changes are recorded during CDD refresh.',
      aiInsertionRisk: false,
    },
  },

  // ── kyc-refresh-periodic-review (B3208–B3219) ─────────────────────────────

  {
    code: 'B3208',
    name: 'Periodic CDD Review Completion Rate Below Regulatory Expectation for High-Risk Segment',
    description: 'First Capital completes only 68% of scheduled high-risk customer periodic CDD reviews within the required cycle, leaving a material backlog of overdue reviews that examiners will identify.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['periodic-review', 'cdd-completion-rate', 'high-risk', 'bsa-aml', 'fincen'],
    failure_rate_pct: 73.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'High-risk periodic CDD review completion rate of 68% leaves a 32% overdue backlog that signals inadequate BSA programme resources to examiners.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230 ongoing monitoring; FFIEC BSA/AML Examination Manual periodic review; OCC BSA/AML guidance',
      detectionMethod: 'CDD system report measuring scheduled versus completed periodic reviews by risk tier and calculating completion rate and average days overdue.',
      remediationPath: 'Triage overdue high-risk reviews for immediate completion; assess staffing adequacy; implement automated scheduling and escalation at 30-day SLA breach.',
      estimatedCost: '$100K–$300K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '55% of banks report high-risk customer periodic CDD review completion rates below 85% at any given time.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3209',
    name: 'CDD Periodic Review Frequency Not Differentiated by Risk Tier',
    description: 'First Capital applies a uniform three-year periodic review cycle to all customers regardless of risk rating, failing the risk-based review frequency expected under FinCEN CDD Rule and FFIEC guidance.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['periodic-review-frequency', 'risk-based', 'cdd', 'bsa-aml', 'fincen'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Uniform three-year review cycle treats high- and low-risk customers identically, failing the risk-based review frequency standard in FinCEN CDD Rule and FFIEC guidance.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230; FFIEC BSA/AML Examination Manual risk-based periodic review; FinCEN CDD final rule preamble',
      detectionMethod: 'CDD policy review confirming whether periodic review frequency varies by customer risk tier as required by the risk-based approach.',
      remediationPath: 'Implement tiered review cycle: 12 months for high-risk, 24 months for medium-risk, 36 months for low-risk; recalibrate scheduling for existing portfolio.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '31% of banks apply a uniform review cycle across all customer risk tiers rather than a risk-differentiated schedule.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3210',
    name: 'EDD Trigger Events for Existing Customers Not Defined in CDD Policy',
    description: `First Capital's CDD policy specifies initial EDD triggers but does not enumerate the event types during the customer lifecycle that require an immediate EDD review outside the scheduled cycle.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['edd-trigger', 'lifecycle-event', 'cdd-policy', 'bsa-aml', 'fincen'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Absence of documented EDD trigger event criteria for existing customers means adverse lifecycle events such as criminal charges or sanctions matches do not prompt immediate review.',
      regulatoryHook: 'FinCEN CDD Rule ongoing monitoring; FFIEC BSA/AML Examination Manual trigger events; FATF Recommendation 10',
      detectionMethod: 'CDD policy review confirming presence of an enumerated list of lifecycle events that trigger out-of-cycle EDD for existing customers.',
      remediationPath: 'Define and document EDD trigger events in CDD policy; configure automated alerts in CDD system for trigger event types; train relationship teams.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '46% of banks lack an explicit enumerated list of lifecycle EDD trigger events in their CDD policy.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3211',
    name: 'Stale CDD Records Not Escalated to Relationship Manager When Refresh Requests Go Unanswered',
    description: 'First Capital sends periodic CDD refresh requests to customers but has no escalation process when customers do not respond, resulting in stale records accumulating without management visibility.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['stale-cdd', 'escalation', 'customer-refresh', 'bsa-aml', 'cdd'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'CDD refresh requests that go unanswered are not escalated, allowing stale records to accumulate indefinitely without relationship manager or compliance officer intervention.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230 ongoing monitoring; FFIEC BSA/AML Examination Manual CDD record staleness; OCC BSA/AML guidance',
      detectionMethod: 'CDD system review confirming whether unanswered refresh requests generate escalation alerts to relationship managers after a defined non-response period.',
      remediationPath: 'Implement a tiered escalation workflow for unanswered CDD refresh requests: relationship manager at 30 days, compliance officer at 60 days, exit consideration at 90 days.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '50% of banks lack a formal escalation process for unanswered customer CDD refresh requests.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3212',
    name: 'Periodic Review Quality Assurance Sampling Rate Below BSA Programme Standards',
    description: `First Capital's QA programme samples only 2% of completed periodic CDD reviews, which is insufficient to detect systematic quality deficiencies across the analyst population.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['quality-assurance', 'periodic-review', 'sampling', 'bsa-aml', 'cdd'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'A 2% QA sampling rate is statistically insufficient to detect systematic periodic review quality deficiencies, allowing analyst error patterns to persist undetected.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual QA and audit coverage; OCC Heightened Standards testing programme; FinCEN CDD Rule',
      detectionMethod: 'QA programme design review confirming current sampling rate and whether it is statistically sufficient to detect quality issues at a 95% confidence level.',
      remediationPath: 'Increase periodic CDD review QA sampling to a minimum of 10% for high-risk and 5% for medium-risk; implement error-rate trend tracking by analyst.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '36% of banks operate periodic CDD review QA programmes with sampling rates below 5%.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3213',
    name: 'Beneficial Ownership Refresh Not Triggered by 25% Ownership Threshold Changes',
    description: 'First Capital does not monitor corporate customer ownership structures for post-onboarding changes that cross the 25% beneficial ownership threshold, missing required CDD Rule re-verification events.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['beneficial-ownership', '25-percent-threshold', 'cdd-refresh', 'fincen', 'bsa-aml'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Ownership changes that shift a new individual above or below the 25% beneficial ownership threshold do not trigger CDD re-verification, creating stale beneficial ownership records.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230 beneficial ownership threshold; FFIEC BSA/AML Examination Manual; FinCEN CDD final rule preamble',
      detectionMethod: 'CDD refresh trigger configuration review confirming whether 25% ownership threshold changes generate automatic beneficial ownership re-verification requests.',
      remediationPath: 'Configure CDD system to detect and flag ownership changes from corporate filings or customer-reported information that cross the 25% threshold; test with synthetic scenarios.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '38% of banks do not have automated triggers for beneficial ownership re-verification when ownership changes cross the 25% threshold.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3214',
    name: 'Periodic CDD Review Not Integrating TM Alert History for Risk Reassessment',
    description: 'First Capital conducts periodic CDD reviews using static onboarding data without incorporating transaction monitoring alert history, missing behavioral risk indicators that should update the customer risk rating.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['periodic-review', 'tm-integration', 'risk-reassessment', 'bsa-aml', 'cdd'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Periodic CDD reviews rely on static customer profile data without integrating TM alert history, causing risk ratings to remain stale despite behavioral indicators of elevated risk.',
      regulatoryHook: 'FinCEN CDD Rule ongoing monitoring and risk rating update obligation; FFIEC BSA/AML Examination Manual integrated review; FATF Recommendation 10',
      detectionMethod: 'Periodic CDD review workflow analysis confirming whether TM alert history is automatically surfaced to the reviewing analyst as part of the review package.',
      remediationPath: 'Integrate TM alert summary into periodic CDD review workflow; require analyst to assess whether alert history warrants a risk rating adjustment.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '45% of banks do not integrate TM alert history into periodic CDD review workflows.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3215',
    name: 'Customer Risk Rating Downgrade Process Not Requiring Supporting Documentation',
    description: 'First Capital allows customer risk ratings to be downgraded from high to medium without a required supporting documentation standard, enabling unjustified rating reductions that reduce monitoring intensity.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['risk-rating-downgrade', 'documentation', 'cdd', 'bsa-aml', 'governance'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Risk rating downgrades from high to medium can be processed without documented supporting rationale, reducing monitoring intensity for customers without adequate risk-reduction justification.',
      regulatoryHook: 'FinCEN CDD Rule risk rating update obligation; FFIEC BSA/AML Examination Manual risk rating governance; OCC Heightened Standards',
      detectionMethod: 'Risk rating change log audit confirming whether downgrade transactions include a mandatory supporting rationale document and approval authority sign-off.',
      remediationPath: 'Implement a mandatory documentation and second-officer approval requirement for all risk rating downgrades; audit prior-period downgrades for compliance.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of banks allow risk rating downgrades without a mandatory documentation standard.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3216',
    name: 'Periodic Review SLA Breach Not Generating Automatic Regulatory Escalation Alert',
    description: 'When periodic CDD reviews breach their scheduled completion date, First Capital does not automatically generate an escalation alert to the BSA officer, allowing breaches to go unmanaged.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['periodic-review', 'sla-breach', 'escalation-alert', 'bsa-aml', 'governance'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Periodic review SLA breaches do not trigger escalation alerts, allowing overdue reviews to accumulate without BSA officer awareness or intervention.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual BSA officer oversight; FinCEN CDD Rule; OCC Heightened Standards management reporting',
      detectionMethod: 'CDD system workflow review confirming whether automated escalation alerts are generated to BSA officer when periodic reviews breach scheduled completion dates.',
      remediationPath: 'Configure CDD system to generate escalation alerts at 15-day and 30-day SLA breaches; route to BSA officer with customer risk tier and days-overdue information.',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '47% of bank CDD systems do not generate automatic escalation alerts when periodic reviews breach scheduled completion dates.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3217',
    name: 'Third-Party CDD Reliance Agreement Not Covering Periodic Refresh Obligations',
    description: `First Capital's third-party CDD reliance agreements cover initial onboarding documentation but do not specify obligations for periodic refresh, creating a gap when CDD refresh data is obtained via third-party reliance.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['third-party-reliance', 'cdd-refresh', 'periodic-review', 'bsa-aml', 'fincen'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Third-party CDD reliance agreements are scoped to initial onboarding only, creating a contractual gap for periodic refresh obligations when reliance is continued post-onboarding.',
      regulatoryHook: 'FinCEN CDD Rule 31 C.F.R. § 1010.230 third-party reliance; FFIEC BSA/AML Examination Manual; FinCEN CDD final rule preamble on reliance scope',
      detectionMethod: 'Third-party reliance agreement review confirming whether periodic refresh obligations are explicitly addressed or limited to initial onboarding scope.',
      remediationPath: 'Amend third-party reliance agreements to address periodic CDD refresh obligations; define refresh frequency expectations and reliance party update protocols.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '36% of third-party CDD reliance agreements in use by banks are silent on periodic refresh obligations.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3218',
    name: 'Annual BSA Training Not Including Periodic CDD Review Procedural Updates',
    description: `First Capital's annual BSA training curriculum has not been updated to reflect recent changes to periodic CDD review procedures, leaving front-line analysts operating on outdated procedural knowledge.`,
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['bsa-training', 'cdd-procedures', 'periodic-review', 'curriculum-update', 'bsa-aml'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Annual BSA training content has not been updated to reflect periodic CDD procedure changes, causing analysts to apply outdated review standards.',
      regulatoryHook: 'FFIEC BSA/AML Examination Manual BSA training programme; FinCEN CDD Rule; OCC Heightened Standards training obligations',
      detectionMethod: 'BSA training curriculum version review confirming alignment between current CDD periodic review procedures and the most recent annual training content.',
      remediationPath: 'Update annual BSA training curriculum to incorporate all periodic CDD procedure changes; implement a procedure-change-triggered training content review cycle.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '42% of banks do not maintain a formal synchronization process between CDD procedure updates and annual BSA training content.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'B3219',
    name: 'Shell Company Customers Lacking Enhanced Periodic Review for Transparency Regime Monitoring',
    description: 'First Capital does not apply enhanced periodic review standards to shell company customers to monitor compliance with beneficial ownership transparency regimes enacted after account opening.',
    vertical: 'banking',
    office_category: 'Compliance',
    keywords: ['shell-company', 'beneficial-ownership', 'transparency-regime', 'periodic-review', 'bsa-aml'],
    failure_rate_pct: 76.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'kyc-refresh-periodic-review',
    data: {
      failureMode: 'Shell company periodic reviews do not assess compliance with post-onboarding transparency regime changes such as FinCEN BOI Rule implementation, leaving beneficial ownership currency gaps.',
      regulatoryHook: 'FinCEN Corporate Transparency Act / BOI Rule 31 C.F.R. Part 1010; FinCEN CDD Rule; FFIEC BSA/AML Examination Manual shell company chapter',
      detectionMethod: 'Shell company periodic review procedure review confirming whether beneficial ownership transparency regime compliance is assessed during the review cycle.',
      remediationPath: 'Add FinCEN BOI Rule compliance verification to shell company periodic review checklist; refresh existing shell company beneficial ownership records against BOI registry.',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '51% of banks have not updated shell company periodic review procedures to address FinCEN Corporate Transparency Act BOI requirements.',
      aiInsertionRisk: false,
    },
  },
];
