/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 49: Interoperability, FHIR, TEFCA & AI Agents
// Part 1: H13600-H13649
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM49_PART1_PATTERNS = [
  {
    code: 'H13600',
    name: 'FHIR R4 Quality Abstraction Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for quality abstraction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'CMS CoP', 'FDA submission posture', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13601',
    name: 'TEFCA Patient Outreach Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for patient outreach but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'NCQA HEDIS audit', 'KLAS commentary', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13602',
    name: 'HL7 V2 Triage Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for triage but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'FDA SaMD guidance', 'Epic App Orchard integration', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13603',
    name: 'Agentic Integration Drafting Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for drafting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'NIST AI RMF', 'Microsoft Cloud for Healthcare', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13604',
    name: 'ADT Summarization Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for summarization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'ONC HTI-1', 'AWS HealthLake', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13605',
    name: 'FHIR R4 Risk Scoring Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for risk scoring but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'TEFCA participation', 'Azure Health Data Services', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13606',
    name: 'TEFCA Worklist Prioritization Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for worklist prioritization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'FHIR R4 mapping', 'Snowflake Healthcare', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13607',
    name: 'HL7 V2 Appeal Generation Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for appeal generation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'HL7 v2 ADT reconciliation', 'Databricks Lakehouse', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13608',
    name: 'Agentic Integration Order Recommendation Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for order recommendation but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'Epic change control', 'ServiceNow workflow', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13609',
    name: 'ADT Benefit Verification Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for benefit verification but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'model registry', 'Salesforce Health Cloud', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13610',
    name: 'FHIR R4 Eligibility Prediction Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for eligibility prediction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'deployment-site validation', 'startup maturity evidence', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13611',
    name: 'TEFCA Care Gap Closure Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for care gap closure but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'MLOps monitoring', 'SOC 2 Type II', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13612',
    name: 'HL7 V2 Cohort Matching Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for cohort matching but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'clinical safety review', 'HITRUST roadmap', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13613',
    name: 'Agentic Integration Contract Analysis Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for contract analysis but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'procurement RFP scoring', 'Series B burn rate', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13614',
    name: 'ADT Agentic Orchestration Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for agentic orchestration but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'BAFO contract clause', 'implementation partner capacity', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13615',
    name: 'FHIR R4 Coding Suggestion Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for coding suggestion but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'HIPAA BAA', 'referenceable health-system customer', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13616',
    name: 'TEFCA Documentation Review Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for documentation review but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'minimum necessary policy', 'clinical advisory board', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13617',
    name: 'HL7 V2 Vendor Comparison Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for vendor comparison but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'TJC survey evidence', 'FDA submission posture', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13618',
    name: 'Agentic Integration Capacity Forecasting Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for capacity forecasting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'CMS CoP', 'KLAS commentary', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13619',
    name: 'ADT Staffing Optimization Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for staffing optimization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'NCQA HEDIS audit', 'Epic App Orchard integration', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13620',
    name: 'FHIR R4 Quality Abstraction Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for quality abstraction but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'FDA SaMD guidance', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13621',
    name: 'TEFCA Patient Outreach Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for patient outreach but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'NIST AI RMF', 'AWS HealthLake', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13622',
    name: 'HL7 V2 Triage Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for triage but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'ONC HTI-1', 'Azure Health Data Services', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13623',
    name: 'Agentic Integration Drafting Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for drafting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'TEFCA participation', 'Snowflake Healthcare', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13624',
    name: 'ADT Summarization Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for summarization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'FHIR R4 mapping', 'Databricks Lakehouse', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13625',
    name: 'FHIR R4 Risk Scoring Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for risk scoring but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'HL7 v2 ADT reconciliation', 'ServiceNow workflow', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13626',
    name: 'TEFCA Worklist Prioritization Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for worklist prioritization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'Epic change control', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13627',
    name: 'HL7 V2 Appeal Generation Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for appeal generation but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'model registry', 'startup maturity evidence', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13628',
    name: 'Agentic Integration Order Recommendation Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for order recommendation but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'deployment-site validation', 'SOC 2 Type II', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13629',
    name: 'ADT Benefit Verification Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for benefit verification but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'MLOps monitoring', 'HITRUST roadmap', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13630',
    name: 'FHIR R4 Eligibility Prediction Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for eligibility prediction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'clinical safety review', 'Series B burn rate', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13631',
    name: 'TEFCA Care Gap Closure Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for care gap closure but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'procurement RFP scoring', 'implementation partner capacity', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13632',
    name: 'HL7 V2 Cohort Matching Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for cohort matching but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'BAFO contract clause', 'referenceable health-system customer', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13633',
    name: 'Agentic Integration Contract Analysis Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for contract analysis but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'HIPAA BAA', 'clinical advisory board', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13634',
    name: 'ADT Agentic Orchestration Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for agentic orchestration but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'minimum necessary policy', 'FDA submission posture', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13635',
    name: 'FHIR R4 Coding Suggestion Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for coding suggestion but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'TJC survey evidence', 'KLAS commentary', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13636',
    name: 'TEFCA Documentation Review Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for documentation review but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'CMS CoP', 'Epic App Orchard integration', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13637',
    name: 'HL7 V2 Vendor Comparison Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for vendor comparison but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'NCQA HEDIS audit', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13638',
    name: 'Agentic Integration Capacity Forecasting Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for capacity forecasting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'FDA SaMD guidance', 'AWS HealthLake', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13639',
    name: 'ADT Staffing Optimization Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for staffing optimization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'NIST AI RMF', 'Azure Health Data Services', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13640',
    name: 'FHIR R4 Quality Abstraction Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for quality abstraction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'ONC HTI-1', 'Snowflake Healthcare', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13641',
    name: 'TEFCA Patient Outreach Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for patient outreach but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'TEFCA participation', 'Databricks Lakehouse', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13642',
    name: 'HL7 V2 Triage Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for triage but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'FHIR R4 mapping', 'ServiceNow workflow', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13643',
    name: 'Agentic Integration Drafting Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for drafting but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'HL7 v2 ADT reconciliation', 'Salesforce Health Cloud', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13644',
    name: 'ADT Summarization Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for summarization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'Epic change control', 'startup maturity evidence', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13645',
    name: 'FHIR R4 Risk Scoring Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when FHIR R4 is used for risk scoring but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when HL7 v2 is not proven in production.`,
    keywords: ['FHIR R4', 'HL7 v2', 'model registry', 'SOC 2 Type II', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13646',
    name: 'TEFCA Worklist Prioritization Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when TEFCA is used for worklist prioritization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when agentic integration is not proven in production.`,
    keywords: ['TEFCA', 'agentic integration', 'deployment-site validation', 'HITRUST roadmap', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13647',
    name: 'HL7 V2 Appeal Generation Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when HL7 v2 is used for appeal generation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when ADT is not proven in production.`,
    keywords: ['HL7 v2', 'ADT', 'MLOps monitoring', 'Series B burn rate', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13648',
    name: 'Agentic Integration Order Recommendation Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when agentic integration is used for order recommendation but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when FHIR R4 is not proven in production.`,
    keywords: ['agentic integration', 'FHIR R4', 'clinical safety review', 'implementation partner capacity', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  },
  {
    code: 'H13649',
    name: 'ADT Benefit Verification Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Interoperability, FHIR, TEFCA & AI Agents initiatives fail when ADT is used for benefit verification but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when TEFCA is not proven in production.`,
    keywords: ['ADT', 'TEFCA', 'procurement RFP scoring', 'referenceable health-system customer', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Interoperability, FHIR, TEFCA & AI Agents',
  }
];
