/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 66: Agentic AI: Clinical Operations Orchestrators
// Part 3: H17100-H17149
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM66_PART3_PATTERNS = [
  {
    code: 'H17100',
    name: 'Clinical Operations Agent Agentic Orchestration Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for agentic orchestration but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves adoption plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'HL7 v2 ADT reconciliation', 'referenceable health-system customer', 'adoption plan', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17101',
    name: 'Workflow Orchestration Coding Suggestion Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for coding suggestion but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is Epic change control: AbarVa should turn this into a Moves pre-mortem risk and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'Epic change control', 'clinical advisory board', 'pre-mortem risk', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17102',
    name: 'EHR Action Documentation Review Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for documentation review but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is model registry: AbarVa should turn this into a Moves dependency map and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'model registry', 'FDA submission posture', 'dependency map', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17103',
    name: 'Human In The Loop Vendor Comparison Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for vendor comparison but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves approval gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'deployment-site validation', 'KLAS commentary', 'approval gate', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17104',
    name: 'Audit Trail Capacity Forecasting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for capacity forecasting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves benefit validation plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'MLOps monitoring', 'Epic App Orchard integration', 'benefit validation plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17105',
    name: 'Clinical Operations Agent Staffing Optimization Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for staffing optimization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is clinical safety review: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'clinical safety review', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17106',
    name: 'Workflow Orchestration Quality Abstraction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for quality abstraction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves value realization ledger and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'procurement RFP scoring', 'AWS HealthLake', 'value realization ledger', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17107',
    name: 'EHR Action Patient Outreach Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for patient outreach but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pilot success metric and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'BAFO contract clause', 'Azure Health Data Services', 'pilot success metric', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17108',
    name: 'Human In The Loop Triage Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for triage but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves clinical governance checklist and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'HIPAA BAA', 'Snowflake Healthcare', 'clinical governance checklist', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17109',
    name: 'Audit Trail Drafting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for drafting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves adoption plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'minimum necessary policy', 'Databricks Lakehouse', 'adoption plan', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17110',
    name: 'Clinical Operations Agent Summarization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for summarization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves pre-mortem risk and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'TJC survey evidence', 'ServiceNow workflow', 'pre-mortem risk', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17111',
    name: 'Workflow Orchestration Risk Scoring Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for risk scoring but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is CMS CoP: AbarVa should turn this into a Moves dependency map and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'CMS CoP', 'Salesforce Health Cloud', 'dependency map', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17112',
    name: 'EHR Action Worklist Prioritization Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for worklist prioritization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves approval gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'NCQA HEDIS audit', 'startup maturity evidence', 'approval gate', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17113',
    name: 'Human In The Loop Appeal Generation Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for appeal generation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves benefit validation plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'FDA SaMD guidance', 'SOC 2 Type II', 'benefit validation plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17114',
    name: 'Audit Trail Order Recommendation Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for order recommendation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'NIST AI RMF', 'HITRUST roadmap', 'unsafe-to-fund gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17115',
    name: 'Clinical Operations Agent Benefit Verification Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for benefit verification but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves value realization ledger and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'ONC HTI-1', 'Series B burn rate', 'value realization ledger', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17116',
    name: 'Workflow Orchestration Eligibility Prediction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for eligibility prediction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pilot success metric and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'TEFCA participation', 'implementation partner capacity', 'pilot success metric', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17117',
    name: 'EHR Action Care Gap Closure Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for care gap closure but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves clinical governance checklist and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'FHIR R4 mapping', 'referenceable health-system customer', 'clinical governance checklist', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17118',
    name: 'Human In The Loop Cohort Matching Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for cohort matching but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves adoption plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'HL7 v2 ADT reconciliation', 'clinical advisory board', 'adoption plan', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17119',
    name: 'Audit Trail Contract Analysis Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for contract analysis but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is Epic change control: AbarVa should turn this into a Moves pre-mortem risk and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'Epic change control', 'FDA submission posture', 'pre-mortem risk', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17120',
    name: 'Clinical Operations Agent Agentic Orchestration Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for agentic orchestration but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is model registry: AbarVa should turn this into a Moves dependency map and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'model registry', 'KLAS commentary', 'dependency map', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17121',
    name: 'Workflow Orchestration Coding Suggestion Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for coding suggestion but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves approval gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'deployment-site validation', 'Epic App Orchard integration', 'approval gate', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17122',
    name: 'EHR Action Documentation Review Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for documentation review but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves benefit validation plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'MLOps monitoring', 'Microsoft Cloud for Healthcare', 'benefit validation plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17123',
    name: 'Human In The Loop Vendor Comparison Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for vendor comparison but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is clinical safety review: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'clinical safety review', 'AWS HealthLake', 'unsafe-to-fund gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17124',
    name: 'Audit Trail Capacity Forecasting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for capacity forecasting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves value realization ledger and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'procurement RFP scoring', 'Azure Health Data Services', 'value realization ledger', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17125',
    name: 'Clinical Operations Agent Staffing Optimization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for staffing optimization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pilot success metric and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'BAFO contract clause', 'Snowflake Healthcare', 'pilot success metric', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17126',
    name: 'Workflow Orchestration Quality Abstraction Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for quality abstraction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves clinical governance checklist and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'HIPAA BAA', 'Databricks Lakehouse', 'clinical governance checklist', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17127',
    name: 'EHR Action Patient Outreach Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for patient outreach but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves adoption plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'minimum necessary policy', 'ServiceNow workflow', 'adoption plan', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17128',
    name: 'Human In The Loop Triage Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for triage but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves pre-mortem risk and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'TJC survey evidence', 'Salesforce Health Cloud', 'pre-mortem risk', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17129',
    name: 'Audit Trail Drafting Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for drafting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is CMS CoP: AbarVa should turn this into a Moves dependency map and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'CMS CoP', 'startup maturity evidence', 'dependency map', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17130',
    name: 'Clinical Operations Agent Summarization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for summarization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves approval gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'NCQA HEDIS audit', 'SOC 2 Type II', 'approval gate', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17131',
    name: 'Workflow Orchestration Risk Scoring Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for risk scoring but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves benefit validation plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'FDA SaMD guidance', 'HITRUST roadmap', 'benefit validation plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17132',
    name: 'EHR Action Worklist Prioritization Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for worklist prioritization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'NIST AI RMF', 'Series B burn rate', 'unsafe-to-fund gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17133',
    name: 'Human In The Loop Appeal Generation Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for appeal generation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves value realization ledger and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'ONC HTI-1', 'implementation partner capacity', 'value realization ledger', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17134',
    name: 'Audit Trail Order Recommendation Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for order recommendation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pilot success metric and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'TEFCA participation', 'referenceable health-system customer', 'pilot success metric', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17135',
    name: 'Clinical Operations Agent Benefit Verification Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for benefit verification but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves clinical governance checklist and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'FHIR R4 mapping', 'clinical advisory board', 'clinical governance checklist', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17136',
    name: 'Workflow Orchestration Eligibility Prediction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for eligibility prediction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves adoption plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'HL7 v2 ADT reconciliation', 'FDA submission posture', 'adoption plan', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17137',
    name: 'EHR Action Care Gap Closure Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for care gap closure but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is Epic change control: AbarVa should turn this into a Moves pre-mortem risk and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'Epic change control', 'KLAS commentary', 'pre-mortem risk', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17138',
    name: 'Human In The Loop Cohort Matching Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for cohort matching but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is model registry: AbarVa should turn this into a Moves dependency map and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'model registry', 'Epic App Orchard integration', 'dependency map', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17139',
    name: 'Audit Trail Contract Analysis Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for contract analysis but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves approval gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'deployment-site validation', 'Microsoft Cloud for Healthcare', 'approval gate', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17140',
    name: 'Clinical Operations Agent Agentic Orchestration Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for agentic orchestration but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves benefit validation plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'MLOps monitoring', 'AWS HealthLake', 'benefit validation plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17141',
    name: 'Workflow Orchestration Coding Suggestion Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for coding suggestion but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'clinical safety review', 'Azure Health Data Services', 'unsafe-to-fund gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17142',
    name: 'EHR Action Documentation Review Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for documentation review but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves value realization ledger and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'procurement RFP scoring', 'Snowflake Healthcare', 'value realization ledger', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17143',
    name: 'Human In The Loop Vendor Comparison Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for vendor comparison but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pilot success metric and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'BAFO contract clause', 'Databricks Lakehouse', 'pilot success metric', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17144',
    name: 'Audit Trail Capacity Forecasting Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for capacity forecasting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves clinical governance checklist and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'HIPAA BAA', 'ServiceNow workflow', 'clinical governance checklist', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17145',
    name: 'Clinical Operations Agent Staffing Optimization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when clinical operations agent is used for staffing optimization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves adoption plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when EHR action is not proven in production.`,
    keywords: ['clinical operations agent', 'EHR action', 'minimum necessary policy', 'Salesforce Health Cloud', 'adoption plan', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17146',
    name: 'Workflow Orchestration Quality Abstraction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when workflow orchestration is used for quality abstraction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves pre-mortem risk and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when human-in-the-loop is not proven in production.`,
    keywords: ['workflow orchestration', 'human-in-the-loop', 'TJC survey evidence', 'startup maturity evidence', 'pre-mortem risk', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17147',
    name: 'EHR Action Patient Outreach Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when EHR action is used for patient outreach but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is CMS CoP: AbarVa should turn this into a Moves dependency map and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when audit trail is not proven in production.`,
    keywords: ['EHR action', 'audit trail', 'CMS CoP', 'SOC 2 Type II', 'dependency map', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17148',
    name: 'Human In The Loop Triage Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when human-in-the-loop is used for triage but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves approval gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when clinical operations agent is not proven in production.`,
    keywords: ['human-in-the-loop', 'clinical operations agent', 'NCQA HEDIS audit', 'HITRUST roadmap', 'approval gate', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  },
  {
    code: 'H17149',
    name: 'Audit Trail Drafting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Agentic AI: Clinical Operations Orchestrators initiatives fail when audit trail is used for drafting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves benefit validation plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when workflow orchestration is not proven in production.`,
    keywords: ['audit trail', 'workflow orchestration', 'FDA SaMD guidance', 'Series B burn rate', 'benefit validation plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Clinical Operations Orchestrators',
  }
];
