interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const BANKING_DOM17_LIQUIDITY_RISK_PART1_PATTERNS: PatternSeed[] = [

  // -- Lcr Compliance (B5060-B5071) --
  {
    code: 'B5060',
    name: 'HQLA Eligibility Evidence Gap In Lcr Compliance',
    description: `First Capital lacks lcr compliance controls around hqla eligibility evidence gap, creating a treasury / liquidity failure mode where decision evidence is not investment grade.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'hqla-eligibility-evidence-gap', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `HQLA Eligibility Evidence Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `37 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5061',
    name: 'Cash Outflow Classification Drift In Lcr Compliance',
    description: `First Capital misclassifies lcr compliance controls around cash outflow classification drift, creating a treasury / liquidity failure mode where audit findings repeat across operating units.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'cash-outflow-classification-drift', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 49.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Cash Outflow Classification Drift causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `44 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5062',
    name: 'Retail Deposit Stability Mislabel In Lcr Compliance',
    description: `First Capital delays lcr compliance controls around retail deposit stability mislabel, creating a treasury / liquidity failure mode where frontline workarounds become normal practice.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'retail-deposit-stability-mislabel', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 56.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Retail Deposit Stability Mislabel causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `52 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5063',
    name: 'Wholesale Funding Runoff Error In Lcr Compliance',
    description: `First Capital understates lcr compliance controls around wholesale funding runoff error, creating a treasury / liquidity failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'wholesale-funding-runoff-error', 'treasury-liquidity', 'ffiec-handbook', 'ai-relevance'],
    failure_rate_pct: 63.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Wholesale Funding Runoff Error causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `59 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5064',
    name: 'Operational Deposit Documentation Gap In Lcr Compliance',
    description: `First Capital overrides lcr compliance controls around operational deposit documentation gap, creating a treasury / liquidity failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'operational-deposit-documentation-gap', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Operational Deposit Documentation Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `65 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5065',
    name: 'Secured Funding Haircut Mismatch In Lcr Compliance',
    description: `First Capital fragments lcr compliance controls around secured funding haircut mismatch, creating a treasury / liquidity failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'secured-funding-haircut-mismatch', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 46.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Secured Funding Haircut Mismatch causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `41 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5066',
    name: 'Intraday LCR Monitoring Delay In Lcr Compliance',
    description: `First Capital stales lcr compliance controls around intraday lcr monitoring delay, creating a treasury / liquidity failure mode where board reporting loses credibility.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'intraday-lcr-monitoring-delay', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 53.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Intraday LCR Monitoring Delay causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `49 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5067',
    name: 'LCR Data Lineage Break In Lcr Compliance',
    description: `First Capital duplicates lcr compliance controls around lcr data lineage break, creating a treasury / liquidity failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'lcr-data-lineage-break', 'treasury-liquidity', 'basel-committee-principles', 'ai-relevance'],
    failure_rate_pct: 60.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `LCR Data Lineage Break causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `56 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5068',
    name: 'Regulatory Reporting Adjustment Lag In Lcr Compliance',
    description: `First Capital bypasses lcr compliance controls around regulatory reporting adjustment lag, creating a treasury / liquidity failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'regulatory-reporting-adjustment-lag', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Regulatory Reporting Adjustment Lag causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `62 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5069',
    name: 'Currency Mismatch Blind Spot In Lcr Compliance',
    description: `First Capital weakens lcr compliance controls around currency mismatch blind spot, creating a treasury / liquidity failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'currency-mismatch-blind-spot', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 43.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Currency Mismatch Blind Spot causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `38 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5070',
    name: 'Stress Assumption Override In Lcr Compliance',
    description: `First Capital misroutes lcr compliance controls around stress assumption override, creating a treasury / liquidity failure mode where operating leaders lose confidence in the program.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'stress-assumption-override', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 50.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `Stress Assumption Override causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `46 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5071',
    name: 'AI LCR Commentary Fabrication In Lcr Compliance',
    description: `First Capital undergoverns lcr compliance controls around ai lcr commentary fabrication, creating a treasury / liquidity failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['lcr-compliance', 'ai-lcr-commentary-fabrication', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'ai-relevance'],
    failure_rate_pct: 57.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'lcr-compliance',
    data: {
      failureMode: `AI LCR Commentary Fabrication causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `53 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Nsfr Compliance (B5072-B5083) --
  {
    code: 'B5072',
    name: 'Available Stable Funding Misclassification In Nsfr Compliance',
    description: `First Capital lacks nsfr compliance controls around available stable funding misclassification, creating a treasury / liquidity failure mode where decision evidence is not investment grade.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'available-stable-funding-misclassification', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Available Stable Funding Misclassification causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `59 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5073',
    name: 'Required Stable Funding Weight Error In Nsfr Compliance',
    description: `First Capital misclassifies nsfr compliance controls around required stable funding weight error, creating a treasury / liquidity failure mode where audit findings repeat across operating units.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'required-stable-funding-weight-error', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 71.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Required Stable Funding Weight Error causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `66 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5074',
    name: 'Long Dated Asset Mapping Gap In Nsfr Compliance',
    description: `First Capital delays nsfr compliance controls around long dated asset mapping gap, creating a treasury / liquidity failure mode where frontline workarounds become normal practice.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'long-dated-asset-mapping-gap', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 47.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Long Dated Asset Mapping Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `43 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5075',
    name: 'Derivative Liability Treatment Drift In Nsfr Compliance',
    description: `First Capital understates nsfr compliance controls around derivative liability treatment drift, creating a treasury / liquidity failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'derivative-liability-treatment-drift', 'treasury-liquidity', 'sr-11-7', 'ai-relevance'],
    failure_rate_pct: 54.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Derivative Liability Treatment Drift causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `50 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5076',
    name: 'Intercompany Funding Evidence Gap In Nsfr Compliance',
    description: `First Capital overrides nsfr compliance controls around intercompany funding evidence gap, creating a treasury / liquidity failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'intercompany-funding-evidence-gap', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Intercompany Funding Evidence Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `56 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5077',
    name: 'Balance Sheet Forecast Linkage Gap In Nsfr Compliance',
    description: `First Capital fragments nsfr compliance controls around balance sheet forecast linkage gap, creating a treasury / liquidity failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'balance-sheet-forecast-linkage-gap', 'treasury-liquidity', 'basel-committee-principles', 'ai-relevance'],
    failure_rate_pct: 68.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Balance Sheet Forecast Linkage Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `63 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5078',
    name: 'NSFR Manual Adjustment Control Weakness In Nsfr Compliance',
    description: `First Capital stales nsfr compliance controls around nsfr manual adjustment control weakness, creating a treasury / liquidity failure mode where board reporting loses credibility.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'nsfr-manual-adjustment-control-weakness', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 44.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `NSFR Manual Adjustment Control Weakness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `40 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5079',
    name: 'Regulatory Interpretation Version Drift In Nsfr Compliance',
    description: `First Capital duplicates nsfr compliance controls around regulatory interpretation version drift, creating a treasury / liquidity failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'regulatory-interpretation-version-drift', 'treasury-liquidity', 'regulation-yy', 'ai-relevance'],
    failure_rate_pct: 51.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Regulatory Interpretation Version Drift causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `47 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5080',
    name: 'Treasury Data Reconciliation Gap In Nsfr Compliance',
    description: `First Capital bypasses nsfr compliance controls around treasury data reconciliation gap, creating a treasury / liquidity failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'treasury-data-reconciliation-gap', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Treasury Data Reconciliation Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `53 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5081',
    name: 'Product Code Mapping Error In Nsfr Compliance',
    description: `First Capital weakens nsfr compliance controls around product code mapping error, creating a treasury / liquidity failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'product-code-mapping-error', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 65.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Product Code Mapping Error causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `60 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5082',
    name: 'Scenario Overlay Governance Gap In Nsfr Compliance',
    description: `First Capital misroutes nsfr compliance controls around scenario overlay governance gap, creating a treasury / liquidity failure mode where operating leaders lose confidence in the program.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'scenario-overlay-governance-gap', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 72.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `Scenario Overlay Governance Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `68 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5083',
    name: 'AI NSFR Explanation Control Gap In Nsfr Compliance',
    description: `First Capital undergoverns nsfr compliance controls around ai nsfr explanation control gap, creating a treasury / liquidity failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['nsfr-compliance', 'ai-nsfr-explanation-control-gap', 'treasury-liquidity', 'ffiec-handbook', 'ai-relevance'],
    failure_rate_pct: 48.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nsfr-compliance',
    data: {
      failureMode: `AI NSFR Explanation Control Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `44 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Intraday Liquidity (B5084-B5095) --
  {
    code: 'B5084',
    name: 'Payment Queue Visibility Gap In Intraday Liquidity',
    description: `First Capital lacks intraday liquidity controls around payment queue visibility gap, creating a treasury / liquidity failure mode where decision evidence is not investment grade.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'payment-queue-visibility-gap', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Payment Queue Visibility Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `50 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5085',
    name: 'Settlement Cutoff Forecast Error In Intraday Liquidity',
    description: `First Capital misclassifies intraday liquidity controls around settlement cutoff forecast error, creating a treasury / liquidity failure mode where audit findings repeat across operating units.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'settlement-cutoff-forecast-error', 'treasury-liquidity', 'sr-11-7', 'ai-relevance'],
    failure_rate_pct: 62.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Settlement Cutoff Forecast Error causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `57 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5086',
    name: 'Correspondent Bank Balance Blind Spot In Intraday Liquidity',
    description: `First Capital delays intraday liquidity controls around correspondent bank balance blind spot, creating a treasury / liquidity failure mode where frontline workarounds become normal practice.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'correspondent-bank-balance-blind-spot', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 69.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Correspondent Bank Balance Blind Spot causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `65 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5087',
    name: 'CLS Funding Timing Drift In Intraday Liquidity',
    description: `First Capital understates intraday liquidity controls around cls funding timing drift, creating a treasury / liquidity failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'cls-funding-timing-drift', 'treasury-liquidity', 'basel-committee-principles', 'ai-relevance'],
    failure_rate_pct: 45.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `CLS Funding Timing Drift causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `41 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5088',
    name: 'Collateral Movement Lag In Intraday Liquidity',
    description: `First Capital overrides intraday liquidity controls around collateral movement lag, creating a treasury / liquidity failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'collateral-movement-lag', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Collateral Movement Lag causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `47 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5089',
    name: 'Real Time Liquidity Dashboard Staleness In Intraday Liquidity',
    description: `First Capital fragments intraday liquidity controls around real time liquidity dashboard staleness, creating a treasury / liquidity failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'real-time-liquidity-dashboard-staleness', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 59.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Real Time Liquidity Dashboard Staleness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `54 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5090',
    name: 'Treasury Operations Handoff Gap In Intraday Liquidity',
    description: `First Capital stales intraday liquidity controls around treasury operations handoff gap, creating a treasury / liquidity failure mode where board reporting loses credibility.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'treasury-operations-handoff-gap', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 66.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Treasury Operations Handoff Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `62 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5091',
    name: 'Large Payment Release Override In Intraday Liquidity',
    description: `First Capital duplicates intraday liquidity controls around large payment release override, creating a treasury / liquidity failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'large-payment-release-override', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'ai-relevance'],
    failure_rate_pct: 42.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Large Payment Release Override causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `38 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5092',
    name: 'Market Stress Intraday Spike In Intraday Liquidity',
    description: `First Capital bypasses intraday liquidity controls around market stress intraday spike, creating a treasury / liquidity failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'market-stress-intraday-spike', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Market Stress Intraday Spike causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `44 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5093',
    name: 'Payment Rail Outage Scenario Gap In Intraday Liquidity',
    description: `First Capital weakens intraday liquidity controls around payment rail outage scenario gap, creating a treasury / liquidity failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'payment-rail-outage-scenario-gap', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 56.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Payment Rail Outage Scenario Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `51 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5094',
    name: 'Intraday Buffer Calibration Error In Intraday Liquidity',
    description: `First Capital misroutes intraday liquidity controls around intraday buffer calibration error, creating a treasury / liquidity failure mode where operating leaders lose confidence in the program.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'intraday-buffer-calibration-error', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 63.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `Intraday Buffer Calibration Error causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `59 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5095',
    name: 'AI Payment Prioritization Control Gap In Intraday Liquidity',
    description: `First Capital undergoverns intraday liquidity controls around ai payment prioritization control gap, creating a treasury / liquidity failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['intraday-liquidity', 'ai-payment-prioritization-control-gap', 'treasury-liquidity', 'sr-11-7', 'ai-relevance'],
    failure_rate_pct: 70.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'intraday-liquidity',
    data: {
      failureMode: `AI Payment Prioritization Control Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `66 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Stress Testing Liquidity (B5096-B5107) --
  {
    code: 'B5096',
    name: 'Stress Scenario Library Staleness In Stress Testing Liquidity',
    description: `First Capital lacks stress testing liquidity controls around stress scenario library staleness, creating a treasury / liquidity failure mode where decision evidence is not investment grade.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'stress-scenario-library-staleness', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Stress Scenario Library Staleness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `41 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5097',
    name: 'Deposit Betas Calibration Gap In Stress Testing Liquidity',
    description: `First Capital misclassifies stress testing liquidity controls around deposit betas calibration gap, creating a treasury / liquidity failure mode where audit findings repeat across operating units.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'deposit-betas-calibration-gap', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 53.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Deposit Betas Calibration Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `48 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5098',
    name: 'Wholesale Funding Shock Understatement In Stress Testing Liquidity',
    description: `First Capital delays stress testing liquidity controls around wholesale funding shock understatement, creating a treasury / liquidity failure mode where frontline workarounds become normal practice.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'wholesale-funding-shock-understatement', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 60.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Wholesale Funding Shock Understatement causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `56 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5099',
    name: 'Contingent Liquidity Draw Error In Stress Testing Liquidity',
    description: `First Capital understates stress testing liquidity controls around contingent liquidity draw error, creating a treasury / liquidity failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'contingent-liquidity-draw-error', 'treasury-liquidity', 'regulation-yy', 'ai-relevance'],
    failure_rate_pct: 67.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Contingent Liquidity Draw Error causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `63 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5100',
    name: 'Management Action Evidence Gap In Stress Testing Liquidity',
    description: `First Capital overrides stress testing liquidity controls around management action evidence gap, creating a treasury / liquidity failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'management-action-evidence-gap', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Management Action Evidence Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `38 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5101',
    name: 'Reverse Stress Test Narrowness In Stress Testing Liquidity',
    description: `First Capital fragments stress testing liquidity controls around reverse stress test narrowness, creating a treasury / liquidity failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'reverse-stress-test-narrowness', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 50.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Reverse Stress Test Narrowness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `45 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5102',
    name: 'Resolution Liquidity Metric Drift In Stress Testing Liquidity',
    description: `First Capital stales stress testing liquidity controls around resolution liquidity metric drift, creating a treasury / liquidity failure mode where board reporting loses credibility.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'resolution-liquidity-metric-drift', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 57.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Resolution Liquidity Metric Drift causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `53 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5103',
    name: 'Model Validation Finding Lag In Stress Testing Liquidity',
    description: `First Capital duplicates stress testing liquidity controls around model validation finding lag, creating a treasury / liquidity failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'model-validation-finding-lag', 'treasury-liquidity', 'ffiec-handbook', 'ai-relevance'],
    failure_rate_pct: 64.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Model Validation Finding Lag causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `60 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5104',
    name: 'Market Data Proxy Weakness In Stress Testing Liquidity',
    description: `First Capital bypasses stress testing liquidity controls around market data proxy weakness, creating a treasury / liquidity failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'market-data-proxy-weakness', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 71.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Market Data Proxy Weakness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `66 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5105',
    name: 'Behavioral Assumption Challenge Gap In Stress Testing Liquidity',
    description: `First Capital weakens stress testing liquidity controls around behavioral assumption challenge gap, creating a treasury / liquidity failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'behavioral-assumption-challenge-gap', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 47.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Behavioral Assumption Challenge Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `42 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5106',
    name: 'Stress Test Production Timing Risk In Stress Testing Liquidity',
    description: `First Capital misroutes stress testing liquidity controls around stress test production timing risk, creating a treasury / liquidity failure mode where operating leaders lose confidence in the program.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'stress-test-production-timing-risk', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 54.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `Stress Test Production Timing Risk causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `50 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5107',
    name: 'AI Scenario Narrative Unsupported Claim In Stress Testing Liquidity',
    description: `First Capital undergoverns stress testing liquidity controls around ai scenario narrative unsupported claim, creating a treasury / liquidity failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['stress-testing-liquidity', 'ai-scenario-narrative-unsupported-claim', 'treasury-liquidity', 'basel-committee-principles', 'ai-relevance'],
    failure_rate_pct: 61.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'stress-testing-liquidity',
    data: {
      failureMode: `AI Scenario Narrative Unsupported Claim causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `57 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Contingency Funding Plan (B5108-B5119) --
  {
    code: 'B5108',
    name: 'CFP Trigger Calibration Drift In Contingency Funding Plan',
    description: `First Capital lacks contingency funding plan controls around cfp trigger calibration drift, creating a treasury / liquidity failure mode where decision evidence is not investment grade.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'cfp-trigger-calibration-drift', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `CFP Trigger Calibration Drift causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `63 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5109',
    name: 'Liquidity War Room Activation Lag In Contingency Funding Plan',
    description: `First Capital misclassifies contingency funding plan controls around liquidity war room activation lag, creating a treasury / liquidity failure mode where audit findings repeat across operating units.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'liquidity-war-room-activation-lag', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 44.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Liquidity War Room Activation Lag causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `39 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5110',
    name: 'Funding Source Availability Gap In Contingency Funding Plan',
    description: `First Capital delays contingency funding plan controls around funding source availability gap, creating a treasury / liquidity failure mode where frontline workarounds become normal practice.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'funding-source-availability-gap', 'treasury-liquidity', 'sr-11-7', 'control-risk'],
    failure_rate_pct: 51.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Funding Source Availability Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `47 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5111',
    name: 'Collateral Monetization Evidence Gap In Contingency Funding Plan',
    description: `First Capital understates contingency funding plan controls around collateral monetization evidence gap, creating a treasury / liquidity failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'collateral-monetization-evidence-gap', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'ai-relevance'],
    failure_rate_pct: 58.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Collateral Monetization Evidence Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `54 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5112',
    name: 'Board Escalation Timing Weakness In Contingency Funding Plan',
    description: `First Capital overrides contingency funding plan controls around board escalation timing weakness, creating a treasury / liquidity failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'board-escalation-timing-weakness', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Board Escalation Timing Weakness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `60 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5113',
    name: 'Communication Plan Staleness In Contingency Funding Plan',
    description: `First Capital fragments contingency funding plan controls around communication plan staleness, creating a treasury / liquidity failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'communication-plan-staleness', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 72.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Communication Plan Staleness causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `67 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5114',
    name: 'Central Bank Facility Readiness Gap In Contingency Funding Plan',
    description: `First Capital stales contingency funding plan controls around central bank facility readiness gap, creating a treasury / liquidity failure mode where board reporting loses credibility.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'central-bank-facility-readiness-gap', 'treasury-liquidity', 'regulation-yy', 'control-risk'],
    failure_rate_pct: 48.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Central Bank Facility Readiness Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `44 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5115',
    name: 'Liquidity Action Owner Ambiguity In Contingency Funding Plan',
    description: `First Capital duplicates contingency funding plan controls around liquidity action owner ambiguity, creating a treasury / liquidity failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'liquidity-action-owner-ambiguity', 'treasury-liquidity', 'sr-11-7', 'ai-relevance'],
    failure_rate_pct: 55.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Liquidity Action Owner Ambiguity causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `SR 11-7 is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `51 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'B5116',
    name: 'CFP Dry Run Evidence Gap In Contingency Funding Plan',
    description: `First Capital bypasses contingency funding plan controls around cfp dry run evidence gap, creating a treasury / liquidity failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'cfp-dry-run-evidence-gap', 'treasury-liquidity', 'occ-operational-resilience-guidance', 'control-risk'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `CFP Dry Run Evidence Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `OCC operational resilience guidance is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `57 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5117',
    name: 'Legal Entity Funding Constraint In Contingency Funding Plan',
    description: `First Capital weakens contingency funding plan controls around legal entity funding constraint, creating a treasury / liquidity failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'legal-entity-funding-constraint', 'treasury-liquidity', 'basel-committee-principles', 'control-risk'],
    failure_rate_pct: 69.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Legal Entity Funding Constraint causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Basel Committee principles is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `64 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5118',
    name: 'Recovery Option Feasibility Gap In Contingency Funding Plan',
    description: `First Capital misroutes contingency funding plan controls around recovery option feasibility gap, creating a treasury / liquidity failure mode where operating leaders lose confidence in the program.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'recovery-option-feasibility-gap', 'treasury-liquidity', 'ffiec-handbook', 'control-risk'],
    failure_rate_pct: 45.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `Recovery Option Feasibility Gap causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `FFIEC handbook is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `41 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'B5119',
    name: 'AI CFP Action Recommendation Risk In Contingency Funding Plan',
    description: `First Capital undergoverns contingency funding plan controls around ai cfp action recommendation risk, creating a treasury / liquidity failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'banking',
    office_category: 'Treasury / Liquidity',
    keywords: ['contingency-funding-plan', 'ai-cfp-action-recommendation-risk', 'treasury-liquidity', 'regulation-yy', 'ai-relevance'],
    failure_rate_pct: 52.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'contingency-funding-plan',
    data: {
      failureMode: `AI CFP Action Recommendation Risk causes treasury / liquidity decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Regulation YY is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `48 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  }
];
