/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 76: Academic Medical Center Research AI
// Part 2: H19050-H19099
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM76_PART2_PATTERNS = [
  {
    code: 'H19050',
    name: 'Research AI Summarization Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for summarization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'TEFCA participation', 'referenceable health-system customer', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19051',
    name: 'IRB Risk Scoring Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for risk scoring but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'FHIR R4 mapping', 'clinical advisory board', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19052',
    name: 'Clinical Trial Matching Worklist Prioritization Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for worklist prioritization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'HL7 v2 ADT reconciliation', 'FDA submission posture', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19053',
    name: 'OMOP Appeal Generation Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for appeal generation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'Epic change control', 'KLAS commentary', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19054',
    name: 'Academic Medical Center Order Recommendation Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for order recommendation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'model registry', 'Epic App Orchard integration', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19055',
    name: 'Research AI Benefit Verification Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for benefit verification but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'deployment-site validation', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19056',
    name: 'IRB Eligibility Prediction Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for eligibility prediction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'MLOps monitoring', 'AWS HealthLake', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19057',
    name: 'Clinical Trial Matching Care Gap Closure Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for care gap closure but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'clinical safety review', 'Azure Health Data Services', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19058',
    name: 'OMOP Cohort Matching Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for cohort matching but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'procurement RFP scoring', 'Snowflake Healthcare', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19059',
    name: 'Academic Medical Center Contract Analysis Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for contract analysis but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'BAFO contract clause', 'Databricks Lakehouse', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19060',
    name: 'Research AI Agentic Orchestration Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for agentic orchestration but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'HIPAA BAA', 'ServiceNow workflow', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19061',
    name: 'IRB Coding Suggestion Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for coding suggestion but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'minimum necessary policy', 'Salesforce Health Cloud', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19062',
    name: 'Clinical Trial Matching Documentation Review Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for documentation review but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'TJC survey evidence', 'startup maturity evidence', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19063',
    name: 'OMOP Vendor Comparison Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for vendor comparison but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'CMS CoP', 'SOC 2 Type II', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19064',
    name: 'Academic Medical Center Capacity Forecasting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for capacity forecasting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'NCQA HEDIS audit', 'HITRUST roadmap', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19065',
    name: 'Research AI Staffing Optimization Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for staffing optimization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'FDA SaMD guidance', 'Series B burn rate', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19066',
    name: 'IRB Quality Abstraction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for quality abstraction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'NIST AI RMF', 'implementation partner capacity', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19067',
    name: 'Clinical Trial Matching Patient Outreach Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for patient outreach but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'ONC HTI-1', 'referenceable health-system customer', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19068',
    name: 'OMOP Triage Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for triage but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'TEFCA participation', 'clinical advisory board', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19069',
    name: 'Academic Medical Center Drafting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for drafting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'FHIR R4 mapping', 'FDA submission posture', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19070',
    name: 'Research AI Summarization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for summarization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'HL7 v2 ADT reconciliation', 'KLAS commentary', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19071',
    name: 'IRB Risk Scoring Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for risk scoring but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'Epic change control', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19072',
    name: 'Clinical Trial Matching Worklist Prioritization Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for worklist prioritization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'model registry', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19073',
    name: 'OMOP Appeal Generation Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for appeal generation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'deployment-site validation', 'AWS HealthLake', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19074',
    name: 'Academic Medical Center Order Recommendation Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for order recommendation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'MLOps monitoring', 'Azure Health Data Services', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19075',
    name: 'Research AI Benefit Verification Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for benefit verification but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'clinical safety review', 'Snowflake Healthcare', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19076',
    name: 'IRB Eligibility Prediction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for eligibility prediction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'procurement RFP scoring', 'Databricks Lakehouse', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19077',
    name: 'Clinical Trial Matching Care Gap Closure Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for care gap closure but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'BAFO contract clause', 'ServiceNow workflow', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19078',
    name: 'OMOP Cohort Matching Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for cohort matching but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'HIPAA BAA', 'Salesforce Health Cloud', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19079',
    name: 'Academic Medical Center Contract Analysis Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for contract analysis but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'minimum necessary policy', 'startup maturity evidence', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19080',
    name: 'Research AI Agentic Orchestration Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for agentic orchestration but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'TJC survey evidence', 'SOC 2 Type II', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19081',
    name: 'IRB Coding Suggestion Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for coding suggestion but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'CMS CoP', 'HITRUST roadmap', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19082',
    name: 'Clinical Trial Matching Documentation Review Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for documentation review but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'NCQA HEDIS audit', 'Series B burn rate', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19083',
    name: 'OMOP Vendor Comparison Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for vendor comparison but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'FDA SaMD guidance', 'implementation partner capacity', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19084',
    name: 'Academic Medical Center Capacity Forecasting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for capacity forecasting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'NIST AI RMF', 'referenceable health-system customer', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19085',
    name: 'Research AI Staffing Optimization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for staffing optimization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'ONC HTI-1', 'clinical advisory board', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19086',
    name: 'IRB Quality Abstraction Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for quality abstraction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'TEFCA participation', 'FDA submission posture', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19087',
    name: 'Clinical Trial Matching Patient Outreach Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for patient outreach but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'FHIR R4 mapping', 'KLAS commentary', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19088',
    name: 'OMOP Triage Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for triage but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'HL7 v2 ADT reconciliation', 'Epic App Orchard integration', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19089',
    name: 'Academic Medical Center Drafting Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for drafting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'Epic change control', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19090',
    name: 'Research AI Summarization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for summarization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'model registry', 'AWS HealthLake', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19091',
    name: 'IRB Risk Scoring Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for risk scoring but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'deployment-site validation', 'Azure Health Data Services', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19092',
    name: 'Clinical Trial Matching Worklist Prioritization Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for worklist prioritization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'MLOps monitoring', 'Snowflake Healthcare', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19093',
    name: 'OMOP Appeal Generation Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for appeal generation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'clinical safety review', 'Databricks Lakehouse', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19094',
    name: 'Academic Medical Center Order Recommendation Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for order recommendation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'procurement RFP scoring', 'ServiceNow workflow', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19095',
    name: 'Research AI Benefit Verification Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for benefit verification but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'BAFO contract clause', 'Salesforce Health Cloud', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19096',
    name: 'IRB Eligibility Prediction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for eligibility prediction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'HIPAA BAA', 'startup maturity evidence', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19097',
    name: 'Clinical Trial Matching Care Gap Closure Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for care gap closure but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'minimum necessary policy', 'SOC 2 Type II', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19098',
    name: 'OMOP Cohort Matching Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for cohort matching but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'TJC survey evidence', 'HITRUST roadmap', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19099',
    name: 'Academic Medical Center Contract Analysis Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for contract analysis but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'CMS CoP', 'Series B burn rate', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  }
];
