/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 38: Population Health AI & VBC Risk Stratification
// Part 4: H11550-H11599
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM38_PART4_PATTERNS = [
  {
    code: 'H11550',
    name: 'Population Health AI Order Recommendation Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for order recommendation but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'model registry', 'startup maturity evidence', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11551',
    name: 'ACO Attribution Benefit Verification Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for benefit verification but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'deployment-site validation', 'SOC 2 Type II', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11552',
    name: 'HEDIS Eligibility Prediction Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for eligibility prediction but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'MLOps monitoring', 'HITRUST roadmap', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11553',
    name: 'Claims Lag Care Gap Closure Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for care gap closure but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'clinical safety review', 'Series B burn rate', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11554',
    name: 'VBC Contract Cohort Matching Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for cohort matching but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'procurement RFP scoring', 'implementation partner capacity', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11555',
    name: 'Population Health AI Contract Analysis Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for contract analysis but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'BAFO contract clause', 'referenceable health-system customer', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11556',
    name: 'ACO Attribution Agentic Orchestration Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for agentic orchestration but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'HIPAA BAA', 'clinical advisory board', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11557',
    name: 'HEDIS Coding Suggestion Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for coding suggestion but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'minimum necessary policy', 'FDA submission posture', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11558',
    name: 'Claims Lag Documentation Review Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for documentation review but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'TJC survey evidence', 'KLAS commentary', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11559',
    name: 'VBC Contract Vendor Comparison Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for vendor comparison but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'CMS CoP', 'Epic App Orchard integration', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11560',
    name: 'Population Health AI Capacity Forecasting Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for capacity forecasting but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'NCQA HEDIS audit', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11561',
    name: 'ACO Attribution Staffing Optimization Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for staffing optimization but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'FDA SaMD guidance', 'AWS HealthLake', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11562',
    name: 'HEDIS Quality Abstraction Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for quality abstraction but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'NIST AI RMF', 'Azure Health Data Services', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11563',
    name: 'Claims Lag Patient Outreach Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for patient outreach but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'ONC HTI-1', 'Snowflake Healthcare', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11564',
    name: 'VBC Contract Triage Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for triage but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'TEFCA participation', 'Databricks Lakehouse', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11565',
    name: 'Population Health AI Drafting Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for drafting but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'FHIR R4 mapping', 'ServiceNow workflow', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11566',
    name: 'ACO Attribution Summarization Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for summarization but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'HL7 v2 ADT reconciliation', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11567',
    name: 'HEDIS Risk Scoring Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for risk scoring but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'Epic change control', 'startup maturity evidence', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11568',
    name: 'Claims Lag Worklist Prioritization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for worklist prioritization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'model registry', 'SOC 2 Type II', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11569',
    name: 'VBC Contract Appeal Generation Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for appeal generation but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'deployment-site validation', 'HITRUST roadmap', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11570',
    name: 'Population Health AI Order Recommendation Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for order recommendation but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'MLOps monitoring', 'Series B burn rate', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11571',
    name: 'ACO Attribution Benefit Verification Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for benefit verification but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'clinical safety review', 'implementation partner capacity', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11572',
    name: 'HEDIS Eligibility Prediction Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for eligibility prediction but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'procurement RFP scoring', 'referenceable health-system customer', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11573',
    name: 'Claims Lag Care Gap Closure Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for care gap closure but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'BAFO contract clause', 'clinical advisory board', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11574',
    name: 'VBC Contract Cohort Matching Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for cohort matching but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'HIPAA BAA', 'FDA submission posture', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11575',
    name: 'Population Health AI Contract Analysis Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for contract analysis but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'minimum necessary policy', 'KLAS commentary', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11576',
    name: 'ACO Attribution Agentic Orchestration Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for agentic orchestration but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'TJC survey evidence', 'Epic App Orchard integration', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11577',
    name: 'HEDIS Coding Suggestion Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for coding suggestion but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'CMS CoP', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11578',
    name: 'Claims Lag Documentation Review Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for documentation review but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'NCQA HEDIS audit', 'AWS HealthLake', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11579',
    name: 'VBC Contract Vendor Comparison Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for vendor comparison but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'FDA SaMD guidance', 'Azure Health Data Services', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11580',
    name: 'Population Health AI Capacity Forecasting Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for capacity forecasting but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'NIST AI RMF', 'Snowflake Healthcare', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11581',
    name: 'ACO Attribution Staffing Optimization Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for staffing optimization but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'ONC HTI-1', 'Databricks Lakehouse', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11582',
    name: 'HEDIS Quality Abstraction Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for quality abstraction but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'TEFCA participation', 'ServiceNow workflow', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11583',
    name: 'Claims Lag Patient Outreach Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for patient outreach but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'FHIR R4 mapping', 'Salesforce Health Cloud', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11584',
    name: 'VBC Contract Triage Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for triage but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'HL7 v2 ADT reconciliation', 'startup maturity evidence', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11585',
    name: 'Population Health AI Drafting Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for drafting but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'Epic change control', 'SOC 2 Type II', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11586',
    name: 'ACO Attribution Summarization Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for summarization but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'model registry', 'HITRUST roadmap', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11587',
    name: 'HEDIS Risk Scoring Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for risk scoring but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'deployment-site validation', 'Series B burn rate', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11588',
    name: 'Claims Lag Worklist Prioritization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for worklist prioritization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'MLOps monitoring', 'implementation partner capacity', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11589',
    name: 'VBC Contract Appeal Generation Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for appeal generation but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'clinical safety review', 'referenceable health-system customer', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11590',
    name: 'Population Health AI Order Recommendation Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for order recommendation but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'procurement RFP scoring', 'clinical advisory board', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11591',
    name: 'ACO Attribution Benefit Verification Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for benefit verification but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'BAFO contract clause', 'FDA submission posture', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11592',
    name: 'HEDIS Eligibility Prediction Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for eligibility prediction but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'HIPAA BAA', 'KLAS commentary', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11593',
    name: 'Claims Lag Care Gap Closure Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for care gap closure but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'minimum necessary policy', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11594',
    name: 'VBC Contract Cohort Matching Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for cohort matching but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'TJC survey evidence', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11595',
    name: 'Population Health AI Contract Analysis Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when population health AI is used for contract analysis but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when HEDIS is not proven in production.`,
    keywords: ['population health AI', 'HEDIS', 'CMS CoP', 'AWS HealthLake', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11596',
    name: 'ACO Attribution Agentic Orchestration Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when ACO attribution is used for agentic orchestration but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when claims lag is not proven in production.`,
    keywords: ['ACO attribution', 'claims lag', 'NCQA HEDIS audit', 'Azure Health Data Services', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11597',
    name: 'HEDIS Coding Suggestion Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when HEDIS is used for coding suggestion but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when VBC contract is not proven in production.`,
    keywords: ['HEDIS', 'VBC contract', 'FDA SaMD guidance', 'Snowflake Healthcare', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11598',
    name: 'Claims Lag Documentation Review Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when claims lag is used for documentation review but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when population health AI is not proven in production.`,
    keywords: ['claims lag', 'population health AI', 'NIST AI RMF', 'Databricks Lakehouse', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  },
  {
    code: 'H11599',
    name: 'VBC Contract Vendor Comparison Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Population Health AI & VBC Risk Stratification initiatives fail when VBC contract is used for vendor comparison but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when ACO attribution is not proven in production.`,
    keywords: ['VBC contract', 'ACO attribution', 'ONC HTI-1', 'ServiceNow workflow', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Population Health AI & VBC Risk Stratification',
  }
];
