interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const MEDTECH_DOM03_QMS_PART6_PATTERNS: PatternSeed[] = [

  // ── Post-Market QMS Integration (M700–M711) ───────────────────────────────

  {
    code: 'M700',
    name: 'Post-Market Surveillance Data Not Feeding CAPA System Under ISO 13485 §8.5',
    description: 'Post-market surveillance complaint trending data is collected in a standalone CRM but never formally routed into the CAPA system, severing the closed-loop feedback mechanism ISO 13485:2016 §8.5 requires.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['post-market-surveillance', 'capa', 'iso-13485', 'complaint-trending', 'closed-loop'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'PMS complaint data siloed in CRM with no formal CAPA trigger workflow',
      regulatoryHook: 'ISO 13485:2016 §8.5.2 CAPA; FDA 21 CFR 820.100 QMSR; MDR Article 83',
      detectionMethod: 'Cross-audit of complaint log versus CAPA register for unresolved trending signals',
      remediationPath: 'Integrate CRM complaint module with eQMS CAPA workflow; define trending thresholds and escalation triggers',
      estimatedCost: '$80K–$220K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '58% of Class II device makers lack automated PMS-to-CAPA data bridging',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M701',
    name: 'MDR Vigilance Reporting Timelines Missed Due to Manual Signal Detection',
    description: 'Adverse event signal detection relies on manual weekly review of complaint spreadsheets, causing MDR 15-day serious injury reporting windows to be routinely breached when volumes spike.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdr-vigilance', 'adverse-event', 'signal-detection', 'reporting-timeline', '21-cfr-803'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Manual signal detection workflow cannot sustain MDR 15-day reporting window at scale',
      regulatoryHook: 'FDA 21 CFR 803.50; EU MDR Article 87; ISO 13485:2016 §8.2.3',
      detectionMethod: 'Audit of MDR submission dates versus event receipt dates across 12-month sample',
      remediationPath: 'Implement automated vigilance signal detection with mandatory regulatory review queue and escalation SLA',
      estimatedCost: '$100K–$300K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '42% of device manufacturers have at least one documented MDR timeline breach per year',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M702',
    name: 'Field Safety Corrective Action Not Reflected in Design History File',
    description: 'A FSCA triggered by post-market failures modifies labeling and instructions for use but the corresponding DHF is not updated, creating a documented divergence between marketed device configuration and design record under 21 CFR 820 QMSR.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['fsca', 'design-history-file', '21-cfr-820', 'labeling-change', 'dhf-update'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Post-market labeling FSCA not propagated back to DHF, creating configuration divergence',
      regulatoryHook: 'FDA 21 CFR 820.30 QMSR Design Controls; ISO 13485:2016 §7.3.10',
      detectionMethod: 'Compare current marketed labeling version against DHF-recorded IFU version',
      remediationPath: 'Establish change control gate requiring DHF update as prerequisite to FSCA closure',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '35% of FSCA reviews find DHF not updated to reflect post-market labeling changes',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M703',
    name: 'Post-Market Clinical Follow-Up Plan Missing Defined Evaluation Criteria',
    description: 'PMCF plans submitted in EU MDR technical documentation specify data collection activities but contain no pre-defined acceptance criteria or residual risk thresholds, rendering PMCF reports unable to confirm continued benefit-risk acceptability.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['pmcf', 'eu-mdr', 'clinical-follow-up', 'benefit-risk', 'acceptance-criteria'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'PMCF plan lacks measurable acceptance criteria preventing benefit-risk confirmation',
      regulatoryHook: 'EU MDR Annex XIV Part B; MEDDEV 2.12/2 rev.2; ISO 13485:2016 §8.2.1',
      detectionMethod: 'Technical documentation review scoring each PMCF plan against MEDDEV 2.12/2 checklist',
      remediationPath: 'Revise all PMCF plans to include device-specific clinical endpoints, thresholds, and review periodicity',
      estimatedCost: '$120K–$350K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '63% of EU MDR technical files audited by notified bodies cite missing PMCF acceptance criteria',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M704',
    name: 'Complaint Rate Trending Not Stratified by Device Lot or Software Version',
    description: 'The complaint management system aggregates all complaint records globally without stratification by manufacturing lot or software revision, masking localized failure signals that require targeted field action.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-trending', 'lot-stratification', 'software-version', 'signal-masking', 'qms'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Aggregate complaint trending masks lot-specific or version-specific failure clusters',
      regulatoryHook: 'FDA 21 CFR 820.198 QMSR; ISO 13485:2016 §8.2.2; FDA Guidance on Complaint Handling',
      detectionMethod: 'Retrospective lot-stratified complaint analysis to identify hidden failure rate spikes',
      remediationPath: 'Restructure complaint database schema to capture lot/version at intake; rebuild trending dashboards with stratification filters',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '47% of Class III device complaint systems lack mandatory lot-level capture fields',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M705',
    name: 'Periodic Safety Update Report Not Synchronized With PSUR Schedule Across Regulatory Jurisdictions',
    description: 'PSUR submissions to EU and FDA are managed on different schedules by different teams with no shared calendar, resulting in data-cut inconsistencies that present differing safety profiles to regulators for the same device.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['psur', 'eu-mdr', 'periodic-safety-update', 'regulatory-synchronization', 'multi-jurisdiction'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Misaligned PSUR data cuts present inconsistent device safety profiles across EU and US submissions',
      regulatoryHook: 'EU MDR Article 86; FDA 21 CFR 803; ISO 13485:2016 §8.2.1',
      detectionMethod: 'Side-by-side comparison of concurrent PSUR data-cut dates and complaint denominator values',
      remediationPath: 'Establish unified PSUR calendar with synchronized data-cut dates and a single source-of-truth complaint dataset',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '39% of multi-jurisdictional device companies have documented PSUR data-cut misalignment',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M706',
    name: 'Returned Device Analysis Not Systematically Linked to Risk Management File',
    description: 'Returned device analysis findings are documented in service reports but are never formally reviewed against the device risk management file, breaking the post-production feedback loop mandated by ISO 14971:2019 §10.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['returned-device', 'risk-management', 'iso-14971', 'post-production', 'service-report'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Service return findings not feeding ISO 14971 post-production risk review cycle',
      regulatoryHook: 'ISO 14971:2019 §10; ISO 13485:2016 §8.5; FDA 21 CFR 820 QMSR',
      detectionMethod: 'Audit service return log for linkage to risk management file review records',
      remediationPath: 'Implement formal returned-device analysis workflow with mandatory risk file review step and closure sign-off',
      estimatedCost: '$45K–$130K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '53% of audited QMS programmes lack a documented link between service returns and risk file updates',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M707',
    name: 'UDI Traceability Gaps Preventing Accurate Post-Market Device Tracking',
    description: 'UDI assignment exists for finished devices but is not captured in the complaint management system at intake, making it impossible to trace specific complaints back to production batches for recall scope determination.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['udi', 'traceability', 'complaint-management', 'recall-scope', '21-cfr-830'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'UDI not captured at complaint intake, blocking batch-level recall scope determination',
      regulatoryHook: 'FDA 21 CFR 830; EU MDR Article 27; ISO 13485:2016 §7.5.9',
      detectionMethod: 'Sample 100 recent complaint records and score for presence of UDI or device identifier',
      remediationPath: 'Update complaint intake form and eQMS to require UDI as mandatory field; backfill open complaints',
      estimatedCost: '$35K–$95K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '46% of complaint records in device company audits are missing UDI capture',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M708',
    name: 'Post-Market Risk Benefit Analysis Not Updated After Serious Adverse Event Cluster',
    description: 'Following a cluster of serious adverse events, the device risk-benefit analysis in the clinical evaluation report is not updated prior to submission of the periodic safety report, leaving regulators with a stale benefit-risk determination.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['benefit-risk', 'clinical-evaluation', 'serious-adverse-event', 'cer', 'eu-mdr'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'CER benefit-risk section not updated following SAE cluster before PSUR submission',
      regulatoryHook: 'EU MDR Annex XIV; MEDDEV 2.7/1 rev.4; ISO 14971:2019 §10.2',
      detectionMethod: 'Compare CER last-update date against SAE cluster date and PSUR data-cut date',
      remediationPath: 'Trigger mandatory CER benefit-risk review upon any SAE cluster exceeding defined threshold before next PSUR',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '58% of EU MDR notified body queries cite CER benefit-risk not reflecting recent safety signals',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M709',
    name: 'Complaint Closure Without Confirmed Root Cause Under 21 CFR 820 QMSR',
    description: 'Complaints are administratively closed within SLA windows by marking them "no device defect found" without documented investigation evidence or confirmed root cause, systematically bypassing the CAPA trigger requirement.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-closure', 'root-cause', '21-cfr-820', 'capa-bypass', 'investigation'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Complaints closed as "no defect" without documented investigation evidence to bypass CAPA SLA',
      regulatoryHook: 'FDA 21 CFR 820.198 QMSR; ISO 13485:2016 §8.2.2; FDA Warning Letter patterns',
      detectionMethod: 'Statistical audit of "no defect found" closure rate versus industry benchmark; review supporting investigation records',
      remediationPath: 'Mandate investigation evidence attachment for any complaint closure; implement second-tier QA review for no-defect dispositions',
      estimatedCost: '$55K–$160K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '67% of FDA Warning Letters for complaint management cite inadequate investigation before closure',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M710',
    name: 'Software Anomaly Reports Not Integrated Into Post-Market QMS Workflow',
    description: 'Software defect tracking occurs in an engineering bug tracker that is not integrated with the QMS, causing software anomalies meeting MDR reportability criteria to never reach the regulatory affairs team.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['software-anomaly', 'bug-tracker', 'qms-integration', 'iec-62304', 'reportability'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Engineering bug tracker not integrated with QMS; reportable software anomalies missed by regulatory affairs',
      regulatoryHook: 'IEC 62304:2006 §9; FDA 21 CFR 803; ISO 13485:2016 §8.2.3',
      detectionMethod: 'Cross-reference closed software defects against MDR reportability criteria retrospectively',
      remediationPath: 'Build integration bridge between bug tracker and eQMS with automated reportability screening workflow',
      estimatedCost: '$90K–$250K',
      timeToRemediate: '4–7 months',
      industryBenchmark: '55% of software-enabled device makers have no formal integration between bug tracking and QMS',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M711',
    name: 'Trend Analysis Frequency Insufficient to Detect Emerging Safety Signals',
    description: 'Complaint trend analysis is conducted quarterly, creating a 90-day blind spot during which an emerging failure mode can reach Field Safety Corrective Action thresholds before detection under ISO 13485:2016 §8.4.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['trend-analysis', 'signal-detection', 'quarterly-review', 'iso-13485', 'fsca-threshold'],
    failure_rate_pct: 45.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'post-market-qms-integration',
    data: {
      failureMode: 'Quarterly trend cadence allows emerging failure mode to reach FSCA threshold undetected for up to 90 days',
      regulatoryHook: 'ISO 13485:2016 §8.4; FDA 21 CFR 820 QMSR; EU MDR Article 83',
      detectionMethod: 'Retrospective analysis of FSCA history to determine whether earlier monthly trending would have triggered earlier action',
      remediationPath: 'Shift to monthly trend analysis with dynamic thresholds and automated alert generation for rate exceedances',
      estimatedCost: '$30K–$85K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of Class II/III device QMS programmes use quarterly-or-less trending, below FDA best-practice guidance',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── QMS Digital Transformation (M712–M723) ───────────────────────────────

  {
    code: 'M712',
    name: 'eQMS Validation Not Compliant With 21 CFR Part 11 Electronic Records Requirements',
    description: 'The cloud-based eQMS system processes controlled quality records electronically but was validated without a 21 CFR Part 11 gap assessment, leaving audit trail, electronic signature, and record retention controls unverified.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['eqms', '21-cfr-part-11', 'electronic-records', 'validation', 'audit-trail'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'eQMS deployed without Part 11 gap assessment; electronic signatures and audit trails unvalidated',
      regulatoryHook: 'FDA 21 CFR Part 11; FDA 21 CFR 820 QMSR; ISO 13485:2016 §4.2.5',
      detectionMethod: 'Part 11 gap assessment against validated system documentation and audit trail configuration',
      remediationPath: 'Conduct Part 11 gap assessment; remediate audit trail configuration; revalidate affected workflows',
      estimatedCost: '$120K–$350K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '62% of eQMS implementations inspected by FDA lack complete Part 11 compliance documentation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M713',
    name: 'Paper-Based Document Control Not Migrated to Controlled eQMS With Version Locking',
    description: 'Critical SOPs exist simultaneously as PDF files on shared drives and in the eQMS, with no version-lock enforcement, enabling personnel to access and follow superseded procedures.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['document-control', 'sop-versioning', 'eqms-migration', 'shared-drive', 'iso-13485'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'Dual-source SOP environment allows personnel to follow superseded procedures from shared drives',
      regulatoryHook: 'ISO 13485:2016 §4.2.3 Document Control; FDA 21 CFR 820 QMSR §820.40',
      detectionMethod: 'Inventory shared drives for SOP files and compare against eQMS current-version index',
      remediationPath: 'Complete eQMS migration; archive all shared-drive SOP copies; restrict access to superseded versions',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '54% of FDA inspections at companies mid-eQMS-migration cite dual-source document control deficiencies',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M714',
    name: 'AI-Assisted QMS Document Drafting Without Formal Change Control Review',
    description: 'Quality personnel use generative AI tools to draft SOP updates which are imported directly into the eQMS under the original author\'s credentials without a separate AI-content disclosure or enhanced review step.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['ai-document-drafting', 'genai-qms', 'change-control', 'sop-authorship', 'part-11'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'AI-drafted QMS documents enter controlled system without AI-content disclosure or enhanced SME review',
      regulatoryHook: 'FDA 21 CFR 820 QMSR; FDA AI/ML Action Plan 2021; ISO 13485:2016 §4.2.3',
      detectionMethod: 'Audit eQMS change log for AI-tool usage patterns; interview authors on drafting process',
      remediationPath: 'Establish AI-content policy for QMS documents; require SME attestation and enhanced review gate for AI-drafted records',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '68% of device QMS teams using GenAI for drafting have no formal AI-content disclosure policy',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-drafted QMS content enters controlled records without adequate human verification of technical accuracy',
    },
  },
  {
    code: 'M715',
    name: 'Training Management System Not Integrated With Document Control for Automatic Retraining Triggers',
    description: 'When SOPs are revised in the eQMS, affected personnel are not automatically notified in the learning management system, creating training currency gaps that persist until the next periodic training audit.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['training-management', 'document-control', 'lms-integration', 'retraining-trigger', 'iso-13485'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'SOP revision does not auto-trigger LMS retraining assignment, leaving personnel on superseded training records',
      regulatoryHook: 'ISO 13485:2016 §6.2 Human Resources; FDA 21 CFR 820 QMSR §820.25',
      detectionMethod: 'Sample SOP revision history and verify corresponding LMS training assignments were triggered within 5 business days',
      remediationPath: 'Integrate eQMS document approval workflow with LMS to auto-assign retraining upon SOP effective date',
      estimatedCost: '$35K–$100K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '51% of device companies have no automated link between document control approvals and LMS retraining triggers',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M716',
    name: 'Digital Quality Metrics Dashboard Reporting Lagged Data Due to Manual ETL Dependency',
    description: 'The executive quality dashboard pulls KPI data via a manually executed weekly ETL script, introducing up to 7-day lags in CAPA aging and complaint rate metrics that management relies on for timely decision-making.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['quality-metrics', 'dashboard', 'etl-lag', 'capa-aging', 'management-review'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'Manual ETL script introduces up to 7-day data lag in quality KPI dashboard used for management review',
      regulatoryHook: 'ISO 13485:2016 §5.6 Management Review; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Compare dashboard metric timestamps against eQMS source data timestamps across 4-week sample',
      remediationPath: 'Replace manual ETL with real-time API integration between eQMS and BI platform; implement data freshness indicator on dashboard',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '37% of device quality dashboards operate on stale data due to manual refresh dependencies',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M717',
    name: 'Supplier Quality Data Not Ingested Into Central QMS for Holistic Risk Scoring',
    description: 'Supplier audit results, incoming inspection failures, and supplier CAPAs are managed in separate spreadsheets outside the eQMS, preventing holistic supplier risk scoring required by ISO 13485:2016 §7.4.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['supplier-quality', 'supplier-risk-scoring', 'iso-13485', 'eqms-integration', 'incoming-inspection'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'Supplier quality data siloed in spreadsheets; holistic supplier risk scores unavailable in eQMS',
      regulatoryHook: 'ISO 13485:2016 §7.4 Purchasing; FDA 21 CFR 820 QMSR §820.50',
      detectionMethod: 'Inventory data sources contributing to supplier scorecards; assess completeness against eQMS records',
      remediationPath: 'Migrate supplier audit, incoming inspection, and SCAPA records into eQMS; implement automated supplier risk scoring model',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '4–6 months',
      industryBenchmark: '56% of ISO 13485-certified companies maintain critical supplier quality data outside the QMS',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M718',
    name: 'Cloud eQMS Disaster Recovery Plan Not Validated for RTO Compliance',
    description: 'The cloud-hosted eQMS has a vendor-stated RTO of 4 hours but no site-level disaster recovery test has been performed to validate that controlled quality records remain accessible within that window under ISO 13485:2016 §4.2.5.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['disaster-recovery', 'eqms', 'rto-validation', 'iso-13485', 'business-continuity'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'eQMS disaster recovery RTO relies on vendor SLA without customer-side validation testing',
      regulatoryHook: 'ISO 13485:2016 §4.2.5; FDA 21 CFR Part 11 §11.10(c); GAMP 5 Annex 11',
      detectionMethod: 'Review DR test records; if none exist, commission tabletop exercise against RTO objective',
      remediationPath: 'Conduct annual DR test for eQMS including controlled record restoration; document results and RTO achievement',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '43% of companies running cloud eQMS have never validated recovery time against their stated RTO',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M719',
    name: 'Barcode-Based In-Process Inspection Data Not Directly Captured Into QMS',
    description: 'In-process inspection results are scanned via barcode readers into a manufacturing execution system that has no validated interface with the QMS, requiring double-entry that introduces transcription errors in device history records.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['in-process-inspection', 'mes-qms-integration', 'barcode', 'dhr', 'transcription-error'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'MES-to-QMS double-entry for in-process inspection introduces transcription errors in device history records',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.80; ISO 13485:2016 §7.5.1; FDA 21 CFR Part 11',
      detectionMethod: 'Sample 50 DHR records and cross-verify values against MES source data for discrepancies',
      remediationPath: 'Build validated MES-to-QMS integration eliminating manual transcription; implement bi-directional reconciliation check',
      estimatedCost: '$80K–$230K',
      timeToRemediate: '4–7 months',
      industryBenchmark: '46% of device manufacturers still use manual transcription between MES and QMS for inspection data',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M720',
    name: 'Electronic Device History Record Missing Mandatory Inspection Sign-Offs',
    description: 'The electronic DHR system permits device release to proceed when individual inspection sign-off fields are left blank, due to a validation defect in the required-field enforcement logic introduced during a software upgrade.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['ehr', 'dhr', 'electronic-signature', 'required-field', 'device-release'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'eQMS software upgrade introduced defect allowing device release with missing DHR inspection sign-offs',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.184; ISO 13485:2016 §7.5.1; 21 CFR Part 11',
      detectionMethod: 'Run database query on DHR records released in past 6 months with null sign-off fields',
      remediationPath: 'Patch required-field logic; retrospectively identify and quarantine released devices with incomplete DHRs; notify QA management',
      estimatedCost: '$60K–$170K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '49% of device companies report at least one DHR completeness defect following an eQMS upgrade',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M721',
    name: 'Remote Audit Capability Not Validated as Equivalent to On-Site Audit Under ISO 13485',
    description: 'Supplier audits have shifted to remote video-based formats but no equivalency validation has been performed to confirm remote auditing captures the same objective evidence as on-site physical audits required by ISO 13485:2016 §7.4.1.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['remote-audit', 'supplier-audit', 'iso-13485', 'equivalency', 'objective-evidence'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'Remote supplier audits substituted for on-site without documented equivalency justification',
      regulatoryHook: 'ISO 13485:2016 §7.4.1; IAF MD 4:2022 Remote Audit Guidance; FDA 21 CFR 820 QMSR',
      detectionMethod: 'Review remote audit SOPs for IAF MD 4-aligned equivalency criteria and risk-based selection rationale',
      remediationPath: 'Develop remote-audit equivalency procedure aligned with IAF MD 4; classify suppliers by remote-audit suitability',
      estimatedCost: '$30K–$85K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '52% of ISO 13485 certified companies lack a formal remote audit equivalency procedure',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M722',
    name: 'IoT-Connected Device Field Data Not Routed Through Formal QMS Feedback Channel',
    description: 'IoT-enabled devices transmit real-time performance data to a cloud analytics platform but the data pipeline has no formal interface with the QMS complaint or PMS module, leaving continuous operational data outside the regulatory feedback loop.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['iot-device', 'real-time-data', 'qms-feedback', 'pms', 'cloud-analytics'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'IoT device telemetry bypasses QMS complaint/PMS channels entirely; field anomalies go undetected in regulatory feedback loop',
      regulatoryHook: 'EU MDR Article 83; FDA 21 CFR 820 QMSR §820.198; ISO 13485:2016 §8.2.1',
      detectionMethod: 'Map IoT data pipeline endpoints; verify QMS integration point exists and routes anomalies to complaint management',
      remediationPath: 'Define anomaly-detection rules in IoT platform with automated QMS complaint creation for threshold exceedances',
      estimatedCost: '$100K–$300K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '60% of connected device manufacturers have no validated pathway from IoT telemetry to QMS complaint module',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-based anomaly detection in IoT pipeline may suppress or misclassify signals before they reach the QMS',
    },
  },
  {
    code: 'M723',
    name: 'Digital Quality Records Retention Policy Not Aligned With 21 CFR Part 820 QMSR Lifetime Requirements',
    description: 'The eQMS archive policy purges completed CAPA and nonconformance records after 7 years, which falls short of the device expected service lifetime plus 2 years retention requirement for Class III devices under 21 CFR 820 QMSR.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['record-retention', 'eqms-archiving', '21-cfr-820', 'capa-records', 'class-iii'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-digital-transformation',
    data: {
      failureMode: 'eQMS 7-year purge policy falls short of lifetime-plus-2-years retention for Class III device records',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.180; ISO 13485:2016 §4.2.5; EU MDR Article 10(8)',
      detectionMethod: 'Map device expected service lifetimes for each product line and compare against eQMS archive retention settings',
      remediationPath: 'Update eQMS retention policy by device classification and expected service life; validate archive integrity for extended retention',
      estimatedCost: '$25K–$65K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '38% of Class III device companies have eQMS archive settings that do not comply with lifetime-plus-2 retention requirement',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── Design Controls Advanced (M724–M735) ─────────────────────────────────

  {
    code: 'M724',
    name: 'Design Verification Testing Performed Before Design Inputs Are Formally Approved',
    description: 'Engineering teams initiate V&V testing before the design input specification achieves formal QA sign-off, invalidating the verification evidence because the requirement baseline was not locked at test execution.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['design-verification', 'design-inputs', '21-cfr-820', 'vv-testing', 'requirement-baseline'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'V&V testing executed against unlocked design inputs; verification evidence is not traceable to approved requirements',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.30(f); ISO 13485:2016 §7.3.6; IEC 62366-1:2015',
      detectionMethod: 'Audit V&V test execution dates against design input approval dates in DHF',
      remediationPath: 'Enforce eQMS gate preventing V&V protocol approval unless design input specification is in approved state',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '53% of FDA 483 design control observations cite V&V initiated before design input approval',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M725',
    name: 'Design Transfer Procedure Does Not Include Manufacturing Process Validation Requirements',
    description: 'The design transfer SOP specifies device performance transfer criteria but omits manufacturing process validation requirements, resulting in production processes that meet product specs but lack IQ/OQ/PQ validation per 21 CFR 820 QMSR.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['design-transfer', 'process-validation', 'iq-oq-pq', '21-cfr-820', 'manufacturing'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Design transfer SOP omits process validation scope; IQ/OQ/PQ not completed before production release',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.30(h); ISO 13485:2016 §7.3.8; FDA Process Validation Guidance 2011',
      detectionMethod: 'Review design transfer checklist against FDA 2011 process validation guidance scope requirements',
      remediationPath: 'Revise design transfer SOP to mandate process validation plan as transfer gate; retroactively validate any undocumented processes',
      estimatedCost: '$90K–$260K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '57% of design transfer reviews find process validation scope gaps relative to FDA 2011 guidance',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M726',
    name: 'Human Factors Summative Evaluation Not Conducted for Modified Use Environment',
    description: 'A design change expands the intended use environment from clinical settings to home-use but no summative usability evaluation is conducted for the new use environment, violating IEC 62366-1 and FDA HF guidance for substantial modification.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['human-factors', 'summative-evaluation', 'home-use', 'iec-62366', 'use-environment'],
    failure_rate_pct: 69.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Use environment expanded to home-use without summative HF evaluation for new intended user population',
      regulatoryHook: 'IEC 62366-1:2015 §5; FDA HF Guidance 2016; FDA 21 CFR 820 QMSR §820.30(c)',
      detectionMethod: 'Review change control record for use-environment scope change and corresponding HF evaluation documentation',
      remediationPath: 'Conduct summative usability study for home-use environment with lay-user representative population before distribution',
      estimatedCost: '$150K–$450K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '64% of FDA 510(k) refusals for design changes cite inadequate human factors for modified use environments',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M727',
    name: 'Traceability Matrix Not Bidirectional Between Design Outputs and Risk Controls',
    description: 'The design traceability matrix maps design requirements to outputs but has no reverse trace from risk controls back to design outputs, making it impossible to verify that all identified risk controls are implemented in the design.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['traceability-matrix', 'risk-controls', 'design-outputs', 'iso-14971', 'bidirectional'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'One-directional traceability matrix cannot verify all ISO 14971 risk controls are implemented in design outputs',
      regulatoryHook: 'ISO 14971:2019 §9; FDA 21 CFR 820 QMSR §820.30; ISO 13485:2016 §7.3.7',
      detectionMethod: 'Audit traceability matrix for reverse trace from risk management file risk controls to design output elements',
      remediationPath: 'Rebuild traceability matrix as bidirectional; map all risk controls to implementing design output artifacts',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '50% of design control audits find unidirectional traceability matrices missing reverse risk-control trace',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M728',
    name: 'Design Review Records Missing Documented Basis for Risk Acceptance Decisions',
    description: 'Design review meeting minutes record decisions to accept residual risks but omit the quantitative or qualitative basis for acceptance, violating ISO 14971:2019 §7.4 which requires documented justification for benefit-risk acceptance.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['design-review', 'risk-acceptance', 'iso-14971', 'meeting-minutes', 'documentation'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Design review records accept residual risks without documented acceptance basis or benefit-risk justification',
      regulatoryHook: 'ISO 14971:2019 §7.4 Risk Acceptance; ISO 13485:2016 §7.3.5; FDA 21 CFR 820 QMSR',
      detectionMethod: 'Sample design review minutes and score for presence of documented risk acceptance rationale',
      remediationPath: 'Update design review minute template to require documented acceptance basis for each risk acceptance decision',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '44% of design review records in FDA-inspected companies lack explicit residual risk acceptance documentation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M729',
    name: 'Software Architecture Design Reviews Not Conducted at IEC 62304 Defined SOUP Integration Points',
    description: 'Software of Unknown Provenance is integrated into the medical device software architecture without conducting the design review required by IEC 62304:2006 §8.1.2 at SOUP integration points, leaving interface risk unassessed.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['soup', 'iec-62304', 'software-architecture', 'design-review', 'interface-risk'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'SOUP integrated without IEC 62304 §8.1.2 design review; interface risks undocumented in software risk file',
      regulatoryHook: 'IEC 62304:2006 §8.1; ISO 14971:2019; FDA 21 CFR 820 QMSR Design Controls',
      detectionMethod: 'Inventory SOUP components against design review records to identify integration points lacking §8.1.2 review',
      remediationPath: 'Conduct retroactive SOUP integration design reviews; update software risk file with interface risk assessments',
      estimatedCost: '$55K–$160K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '58% of medical device software audits find SOUP integrations without required IEC 62304 design review records',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M730',
    name: 'Combination Product Design Controls Not Segregating Drug and Device Development Activities',
    description: 'For a drug-device combination product, a single integrated design control plan conflates drug development activities governed by 21 CFR 312 with device design controls under 21 CFR 820, causing cross-contamination of regulatory requirements in the DHF.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['combination-product', 'design-controls', 'drug-device', '21-cfr-820', '21-cfr-312'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Integrated design plan conflates 21 CFR 312 drug and 21 CFR 820 device requirements in single DHF',
      regulatoryHook: 'FDA 21 CFR 820 QMSR; 21 CFR 3.2(e) Combination Products; FDA Combination Product Guidance 2017',
      detectionMethod: 'Review DHF structure for segregation of drug and device design control activities and applicable regulations',
      remediationPath: 'Restructure DHF to segregate drug and device design control activities with clear regulatory assignment for each',
      estimatedCost: '$80K–$220K',
      timeToRemediate: '4–7 months',
      industryBenchmark: '52% of FDA combination product inspections cite design control commingling in the device history file',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M731',
    name: 'Design Change Control Not Triggering Regulatory Impact Assessment for Substantial Equivalence',
    description: 'Device design changes are processed through an internal change control workflow that has no mandatory step to assess whether the modification triggers a new 510(k) requirement under the FDA substantial equivalence framework.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['design-change', 'substantial-equivalence', '510k', 'regulatory-impact', 'change-control'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Design change workflow lacks mandatory 510(k) substantial equivalence assessment step',
      regulatoryHook: 'FDA 21 CFR 807.81(a)(3); FDA Deciding When to Submit 510(k) Guidance 1997; ISO 13485:2016 §7.3.9',
      detectionMethod: 'Audit closed design change orders for presence of documented 510(k) impact assessment',
      remediationPath: 'Add 510(k) regulatory impact assessment as mandatory gate in design change control workflow',
      estimatedCost: '$30K–$85K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '61% of FDA Warning Letters for unauthorized device modifications trace to change control without 510(k) assessment',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M732',
    name: 'Cybersecurity Threat Modeling Not Included in Design Risk Management for Connected Devices',
    description: 'Connected medical device design risk assessments address hardware and software failure modes but contain no cybersecurity threat model, omitting the attack-surface risk analysis required by FDA Cybersecurity Guidance 2023.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['cybersecurity', 'threat-modeling', 'connected-device', 'fda-guidance-2023', 'risk-management'],
    failure_rate_pct: 71.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Design risk file omits cybersecurity threat model for connected device attack surface',
      regulatoryHook: 'FDA Cybersecurity Guidance Sep 2023; FDA 21 CFR 820 QMSR; ISO 14971:2019',
      detectionMethod: 'Review risk management file for cybersecurity threat modeling section and SBOM documentation',
      remediationPath: 'Conduct STRIDE or equivalent threat model; integrate cybersecurity risk controls into design risk file and SBOM',
      estimatedCost: '$120K–$350K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '66% of connected device premarket submissions lack a complete cybersecurity threat model per FDA 2023 guidance',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-enabled device features expand the attack surface without corresponding threat model updates in the design risk file',
    },
  },
  {
    code: 'M733',
    name: 'Validation Protocol Deviations Closed Without Impact Assessment on Test Conclusions',
    description: 'Deviations from approved V&V protocols are documented during execution but are closed as "no impact" by the test lead without formal impact assessment reviewed by QA, invalidating the evidentiary value of affected test results.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['validation-protocol', 'deviation', 'impact-assessment', 'vv', 'test-conclusions'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Protocol deviations self-closed by test lead without QA-reviewed impact assessment on test conclusions',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.30(f)(g); ISO 13485:2016 §7.3.6; FDA Process Validation Guidance 2011',
      detectionMethod: 'Audit V&V deviation records for QA reviewer signature and documented impact conclusion',
      remediationPath: 'Require QA second review for all protocol deviations; implement deviation impact classification matrix',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '54% of V&V package audits find deviations closed without independent QA impact assessment',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M734',
    name: 'Biocompatibility Risk Assessment Not Updated After Change in Device Material Supplier',
    description: 'A supplier change for a primary contact material triggers a material qualification but the biocompatibility risk assessment in the ISO 10993-1 file is not updated to reflect the change, leaving the safety determination based on the previous supplier\'s material data.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['biocompatibility', 'iso-10993', 'material-supplier-change', 'risk-assessment', 'contact-material'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'ISO 10993-1 biocompatibility file not updated to reflect new contact material supplier data',
      regulatoryHook: 'ISO 10993-1:2018; FDA Use of International Standard ISO 10993-1 Guidance 2020; ISO 13485:2016 §7.3.9',
      detectionMethod: 'Cross-reference material supplier change order dates against biocompatibility file revision dates',
      remediationPath: 'Require biocompatibility file review as mandatory output of contact-material supplier change control workflow',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '47% of supplier change audits for contact materials find no corresponding biocompatibility file update',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M735',
    name: 'Usability File Not Documenting Rationale for Excluding Identified Use Errors From Summative Evaluation',
    description: 'The usability engineering file identifies use errors during formative studies that are subsequently excluded from the summative evaluation test plan without documented rationale, leaving gaps in the use-related risk evidence package.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['usability', 'use-error', 'summative-evaluation', 'iec-62366', 'usability-file'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'design-controls-advanced',
    data: {
      failureMode: 'Formative use errors excluded from summative evaluation without documented rationale in usability file',
      regulatoryHook: 'IEC 62366-1:2015 §5.9; FDA HF Guidance 2016; ISO 13485:2016 §7.3.6',
      detectionMethod: 'Cross-reference formative use error log against summative evaluation task list for unexplained exclusions',
      remediationPath: 'Document explicit rationale for each use error exclusion from summative evaluation; obtain QA sign-off',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of HF submission packages reviewed by FDA cite unexplained use error exclusions from summative testing',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── Sterilization Validation (M736–M747) ──────────────────────────────────

  {
    code: 'M736',
    name: 'EO Sterilization Validation Not Requalified After Packaging System Change Under ISO 11135',
    description: 'A change to the device primary packaging barrier system triggers a product qualification but EO sterilization cycle parameters are not revalidated, assuming unchanged gas penetration through an untested packaging configuration.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['eo-sterilization', 'packaging-change', 'iso-11135', 'requalification', 'gas-penetration'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'EO cycle parameters not revalidated following packaging barrier system change; sterility assurance unconfirmed',
      regulatoryHook: 'ISO 11135:2014 §10; AAMI TIR17; FDA 21 CFR 820 QMSR §820.75',
      detectionMethod: 'Cross-reference packaging change control records against ISO 11135 revalidation trigger criteria',
      remediationPath: 'Conduct ISO 11135 EO revalidation for new packaging configuration before continued distribution; quarantine current stock pending assessment',
      estimatedCost: '$150K–$450K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '61% of sterilization nonconformances in FDA inspections trace to packaging changes without cycle revalidation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M737',
    name: 'Radiation Sterilization Dose Audit Not Performed at Required Frequency Under ISO 11137',
    description: 'ISO 11137-3 requires dose audit at intervals not exceeding three months for the method 1 dose-setting approach, but the facility\'s SOPs schedule annual audits, creating a 9-month gap in sterility assurance confirmation.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['radiation-sterilization', 'dose-audit', 'iso-11137', 'sterility-assurance', 'method-1'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Annual dose audit cadence violates ISO 11137-3 quarterly requirement for method 1 dose-setting approach',
      regulatoryHook: 'ISO 11137-3:2017 §10; ISO 13485:2016 §7.5.2; FDA 21 CFR 820 QMSR §820.75',
      detectionMethod: 'Review dose audit SOP and completed audit records against ISO 11137-3 §10 quarterly frequency requirement',
      remediationPath: 'Update SOP to quarterly dose audit cadence; schedule immediate audit if >3 months since last audit',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '53% of radiation sterilization nonconformance findings in audits cite dose audit frequency below ISO 11137-3 requirement',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M738',
    name: 'Steam Sterilization Cycle Development Not Supported by Half-Cycle Biological Indicator Study',
    description: 'Steam sterilization cycle parameters were set based on physical characterization data alone without the half-cycle biological indicator overkill study required to establish the 10-6 SAL margin under AAMI TIR33.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['steam-sterilization', 'biological-indicator', 'aami-tir33', 'half-cycle', 'sal'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Steam cycle parameters set by physical characterization only; 10-6 SAL not confirmed by half-cycle BI overkill study',
      regulatoryHook: 'AAMI TIR33:2005; ISO 17665-1:2006; FDA 21 CFR 820 QMSR §820.75',
      detectionMethod: 'Review sterilization validation package for half-cycle BI study protocols and results',
      remediationPath: 'Conduct retroactive half-cycle BI overkill study; suspend further distribution pending SAL confirmation if study results are inconclusive',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '49% of steam sterilization validation packages reviewed in notified body audits lack half-cycle BI overkill documentation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M739',
    name: 'Sterilization Validation Records Not Retained for Device Lifetime Plus Prescribed Period',
    description: 'Sterilization validation original test records are retained for only 5 years post-validation, falling below the FDA requirement to retain sterilization records throughout the device lifetime and for the prescribed regulatory period after last manufacture.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['sterilization-records', 'record-retention', '21-cfr-820', 'validation-records', 'device-lifetime'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: '5-year sterilization record retention falls below device-lifetime plus regulatory period requirement',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.180; ISO 13485:2016 §4.2.5; ISO 11135:2014',
      detectionMethod: 'Map device product lifetime for each sterilized product line; compare against sterilization record archive policy',
      remediationPath: 'Update sterilization record retention schedule by product classification; verify archive integrity for records at risk of premature deletion',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '38% of device companies have sterilization validation record retention policies that do not cover full device lifetime',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M740',
    name: 'Bioburden Monitoring Frequency Insufficient to Support Continuous Sterility Assurance Under ISO 11137',
    description: 'Bioburden testing is performed quarterly on finished devices, but the site processes multiple product families under the same radiation dose with divergent bioburden profiles requiring more frequent monitoring under ISO 11137-2 to maintain dose adequacy.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['bioburden', 'radiation-dose', 'iso-11137', 'monitoring-frequency', 'dose-adequacy'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Quarterly bioburden monitoring insufficient for multi-family irradiation program with divergent bioburden profiles',
      regulatoryHook: 'ISO 11137-2:2013; ISO 11137-3:2017; FDA 21 CFR 820 QMSR §820.75',
      detectionMethod: 'Analyze bioburden data across product families to identify variance and evaluate against dose adequacy margins',
      remediationPath: 'Increase bioburden monitoring to monthly for high-variance product families; implement statistical control charting',
      estimatedCost: '$35K–$100K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '45% of multi-product radiation sterilization programs have bioburden monitoring frequencies that do not reflect product family bioburden variance',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M741',
    name: 'EO Residual Limits Not Re-Established for New Patient Population Following Indication Expansion',
    description: 'A device label expansion adds a pediatric indication but EO residual and degradant limits established under ISO 10993-7 were calculated for adult patients only, creating an unaddressed safety gap for the pediatric population.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['eo-residuals', 'iso-10993-7', 'pediatric', 'indication-expansion', 'sterilization'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'ISO 10993-7 EO residual limits based on adult patient exposure; pediatric limits not recalculated after indication expansion',
      regulatoryHook: 'ISO 10993-7:2008 Amd 1:2019; FDA EO Residuals Guidance 2019; ISO 13485:2016 §7.3.9',
      detectionMethod: 'Review ISO 10993-7 risk assessment for patient weight basis and compare against expanded indication patient population',
      remediationPath: 'Recalculate EO residual limits for pediatric body weight; conduct residual testing against new limits before pediatric distribution',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '59% of FDA 510(k) reviews for pediatric indication expansions of EO-sterilized devices request updated ISO 10993-7 calculations',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M742',
    name: 'Sterilization Contractor Change Not Triggering Full Requalification Under ISO 11135',
    description: 'Contract sterilization is transferred to a new EO facility with a different chamber size and loading configuration, but the change is processed as a minor supplier change without the full product and process requalification required by ISO 11135.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['sterilization-contractor', 'requalification', 'iso-11135', 'eo-chamber', 'supplier-change'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'EO contractor change processed as minor supplier change without ISO 11135 full requalification',
      regulatoryHook: 'ISO 11135:2014 §10.4; FDA 21 CFR 820 QMSR §820.50; ISO 13485:2016 §7.4',
      detectionMethod: 'Review change control for sterilization contractor transfer; verify requalification scope against ISO 11135 §10.4 requirements',
      remediationPath: 'Conduct full ISO 11135 product and process qualification at new facility; quarantine product sterilized at new site pending qualification completion',
      estimatedCost: '$180K–$550K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '65% of sterilization contractor transfer audits find underscoped requalification relative to ISO 11135 requirements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M743',
    name: 'Gamma Irradiation Dose Mapping Study Not Updated After Load Configuration Change',
    description: 'Product pallet configuration is changed to improve logistics efficiency but the gamma dose mapping study, which established minimum and maximum dose zones, is not updated for the new loading geometry, invalidating the dose distribution data.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['dose-mapping', 'gamma-irradiation', 'load-configuration', 'iso-11137', 'dose-distribution'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Load configuration change invalidates existing gamma dose mapping study; min/max dose zones unverified for new geometry',
      regulatoryHook: 'ISO 11137-1:2006 §10.4; ISO 11137-3:2017; FDA 21 CFR 820 QMSR §820.75',
      detectionMethod: 'Review load change record against dose mapping requalification trigger criteria in ISO 11137-1 §10.4',
      remediationPath: 'Conduct dose mapping for new load configuration before continued irradiation; assess sterility risk for intervening product',
      estimatedCost: '$70K–$200K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '55% of gamma irradiation change control audits find load configuration changes processed without dose mapping update',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M744',
    name: 'Packaging Integrity Testing Not Included in Sterilization Validation Package',
    description: 'Sterilization validation demonstrates cycle efficacy but the validation package contains no packaging integrity test data confirming the sterile barrier system maintains integrity post-sterilization, a gap identified in AAMI TIR22.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['packaging-integrity', 'sterile-barrier', 'aami-tir22', 'sterilization-validation', 'iso-11607'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Sterilization validation package omits post-sterilization packaging integrity test data required by AAMI TIR22',
      regulatoryHook: 'ISO 11607-1:2019; AAMI TIR22; ISO 11135:2014; FDA 21 CFR 820 QMSR §820.75',
      detectionMethod: 'Audit sterilization validation report against ISO 11607-1 and AAMI TIR22 validation component checklist',
      remediationPath: 'Conduct ISO 11607-1 packaging integrity testing post-sterilization; integrate results into validation package',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '48% of sterilization validation packages reviewed in FDA premarket submissions lack packaging integrity test data',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M745',
    name: 'Sterilization Nonconformance Disposition Releasing Product Without QA Authorization',
    description: 'Manufacturing records show sterilization cycle parameter deviations were dispositioned as acceptable by production supervisors without QA review, bypassing the formal nonconformance review board required for sterilization process deviations.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['sterilization-nonconformance', 'disposition', 'qa-authorization', 'cycle-deviation', 'review-board'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Sterilization cycle deviations dispositioned by production supervisor without QA nonconformance review board authorization',
      regulatoryHook: 'FDA 21 CFR 820 QMSR §820.90; ISO 13485:2016 §8.3; ISO 11135:2014 §11',
      detectionMethod: 'Audit sterilization batch records for cycle deviations and verify dispositions carry QA review board authorization',
      remediationPath: 'Mandate QA nonconformance board review for all sterilization cycle parameter deviations; quarantine product in pending review',
      estimatedCost: '$35K–$95K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '63% of sterilization-related FDA 483 observations cite disposition of cycle deviations without formal QA review',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M746',
    name: 'Accelerated Aging Study Not Correlated With Real-Time Aging Data for Sterile Barrier Shelf Life Claim',
    description: 'Device shelf-life labeling relies solely on accelerated aging data without an ongoing real-time aging correlation study, violating ASTM F1980 requirements for corroborating accelerated aging claims with real-time data before the accelerated study end date.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['accelerated-aging', 'real-time-aging', 'astm-f1980', 'shelf-life', 'sterile-barrier'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'Shelf life claim supported only by accelerated aging; real-time aging correlation study not initiated per ASTM F1980',
      regulatoryHook: 'ASTM F1980; ISO 11607-1:2019; FDA 21 CFR 820 QMSR; AAMI TIR22',
      detectionMethod: 'Review shelf life file for ASTM F1980 accelerated/real-time study design and confirm real-time study is active in parallel',
      remediationPath: 'Initiate real-time aging study immediately; update shelf life claim timeline to ensure real-time confirmation before accelerated study expiry',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '1–2 months (to initiate; real-time data over full product lifetime)',
      industryBenchmark: '43% of device shelf life files rely on accelerated aging alone without a running real-time correlation study',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M747',
    name: 'Resterilization Instructions in Device Labeling Not Supported by Validated Reprocessing Study',
    description: 'The device IFU specifies a resterilization method for reusable components but the corresponding reprocessing validation study required by AAMI TIR30 and FDA reprocessing guidance has not been performed.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['resterilization', 'reprocessing-validation', 'aami-tir30', 'ifu', 'reusable-device'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'sterilization-validation',
    data: {
      failureMode: 'IFU specifies resterilization method without supporting AAMI TIR30 reprocessing validation study',
      regulatoryHook: 'AAMI TIR30; FDA Reprocessing Guidance 2015; ISO 17664-1:2021; FDA 21 CFR 820 QMSR',
      detectionMethod: 'Map IFU resterilization claims against reprocessing validation study index in DHF',
      remediationPath: 'Conduct AAMI TIR30 reprocessing validation for each specified resterilization method; revise IFU if methods cannot be validated',
      estimatedCost: '$80K–$240K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '57% of reusable device IFU reviews find resterilization instructions unsupported by reprocessing validation data',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── QMS Culture & Leadership (M748–M759) ──────────────────────────────────

  {
    code: 'M748',
    name: 'Management Review Not Covering All ISO 13485 §5.6 Required Input Elements',
    description: 'Annual management review agendas systematically omit feedback from customers, regulatory body notifications, and process performance metrics, leaving the review non-compliant with the mandatory input list in ISO 13485:2016 §5.6.2.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['management-review', 'iso-13485', 'review-inputs', 'regulatory-feedback', 'process-performance'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Management review agendas missing ISO 13485 §5.6.2 mandatory input elements for customer feedback and regulatory notifications',
      regulatoryHook: 'ISO 13485:2016 §5.6; FDA 21 CFR 820 QMSR §820.20(c)',
      detectionMethod: 'Score management review minutes against ISO 13485 §5.6.2 mandatory input checklist',
      remediationPath: 'Update management review SOP and agenda template with all §5.6.2 required inputs; verify completion at next review',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '49% of ISO 13485 surveillance audits cite management review records missing one or more §5.6.2 mandatory inputs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M749',
    name: 'Quality Policy Not Communicated or Understood at Operational Levels Below Senior Management',
    description: 'The quality policy is posted on the intranet and reviewed annually at senior management level but front-line manufacturing and service personnel cannot articulate its relevance to their work, a recurring audit finding under ISO 13485:2016 §5.3.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['quality-policy', 'communication', 'iso-13485', 'quality-culture', 'front-line-awareness'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Quality policy not cascaded to operational level; front-line personnel cannot articulate policy relevance to their roles',
      regulatoryHook: 'ISO 13485:2016 §5.3 Quality Policy; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Interview sample of manufacturing and service personnel on quality policy content and personal relevance',
      remediationPath: 'Develop role-specific quality policy cascade materials; integrate quality policy into onboarding and annual refresh training',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '42% of ISO 13485 surveillance audits find quality policy awareness deficient below senior management level',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M750',
    name: 'Quality Objectives Not Measurable or Time-Bound Under ISO 13485 §5.4.1',
    description: 'Documented quality objectives describe aspirational states without specific metrics, baselines, or target dates, preventing meaningful progress measurement and rendering the objectives non-compliant with ISO 13485:2016 §5.4.1.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['quality-objectives', 'measurable', 'iso-13485', 'kpi', 'time-bound'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Quality objectives are aspirational text without metrics, baselines, or target dates; progress cannot be measured',
      regulatoryHook: 'ISO 13485:2016 §5.4.1 Quality Objectives; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Score each quality objective against SMART criteria (Specific, Measurable, Achievable, Relevant, Time-bound)',
      remediationPath: 'Rewrite all quality objectives to include baseline metric, target value, and achievement date; assign owners',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '38% of ISO 13485 first-surveillance audits issue nonconformances for quality objectives lacking measurable criteria',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M751',
    name: 'Internal Audit Programme Not Risk-Stratified Across QMS Process Areas',
    description: 'Internal audits are conducted on a fixed annual rotation covering all QMS process areas equally, without risk-based frequency adjustment that ISO 13485:2016 §8.2.4 requires to give higher audit frequency to higher-risk or historically deficient areas.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['internal-audit', 'risk-stratification', 'iso-13485', 'audit-frequency', 'process-risk'],
    failure_rate_pct: 51.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Fixed-rotation audit schedule applies equal frequency to all process areas regardless of risk or historical deficiency',
      regulatoryHook: 'ISO 13485:2016 §8.2.4 Internal Audit; FDA 21 CFR 820 QMSR §820.22',
      detectionMethod: 'Compare audit schedule frequency allocation against CAPA history and regulatory inspection findings by process area',
      remediationPath: 'Implement risk-stratified audit programme with frequency model weighting deficiency history, regulatory impact, and complaint contribution',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '46% of ISO 13485 audit programmes use fixed rotation without risk-based frequency stratification',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M752',
    name: 'CAPA Effectiveness Verification Not Independently Assessed From Original CAPA Owner',
    description: 'CAPA effectiveness checks are performed and documented by the same personnel who executed the corrective action, creating a conflict of interest that violates the independence principle expected under ISO 13485:2016 §8.5.2.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-effectiveness', 'independent-verification', 'iso-13485', 'conflict-of-interest', 'quality-system'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'CAPA effectiveness check performed by corrective action implementer; independence principle violated',
      regulatoryHook: 'ISO 13485:2016 §8.5.2; FDA 21 CFR 820 QMSR §820.100; FDA Warning Letter CAPA patterns',
      detectionMethod: 'Audit closed CAPA records for independence of effectiveness check reviewer from implementation team',
      remediationPath: 'Update CAPA SOP to require independent QA or cross-functional reviewer for all effectiveness checks; retrain CAPA owners',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '54% of FDA Warning Letters for CAPA system deficiencies cite lack of independent effectiveness verification',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M753',
    name: 'Quality Culture Survey Results Not Analyzed or Actioned Before Next Management Review Cycle',
    description: 'Annual quality culture surveys are administered to all employees but results are summarized in a presentation that is never formally reviewed in the management review meeting, preventing systematic actioning of quality culture gaps.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['quality-culture', 'employee-survey', 'management-review', 'actioning', 'quality-system'],
    failure_rate_pct: 38.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Quality culture survey results not included in management review inputs; systemic culture gaps go unaddressed',
      regulatoryHook: 'ISO 13485:2016 §5.6.2 Management Review Inputs; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Review management review agendas and minutes for quality culture survey data as a standing input item',
      remediationPath: 'Add quality culture survey analysis as mandatory management review input; assign action owners for identified culture gaps',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '35% of device companies conducting quality culture surveys do not formally integrate results into management review',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M754',
    name: 'Quality Manual Not Reflecting Current QMS Scope After Organizational Restructuring',
    description: 'A major organizational restructuring merged two quality organizations under a single QMS but the quality manual still describes the pre-merger dual-QMS structure, creating a documented mismatch with actual QMS scope under ISO 13485:2016 §4.2.2.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['quality-manual', 'qms-scope', 'organizational-change', 'iso-13485', 'documentation'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Quality manual describes pre-merger dual-QMS structure; current unified QMS scope undocumented',
      regulatoryHook: 'ISO 13485:2016 §4.2.2 Quality Manual; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Compare quality manual organization chart and scope statement against current organizational structure',
      remediationPath: 'Revise quality manual to reflect unified organizational structure and QMS scope; obtain management approval and re-issue',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '43% of post-merger device organization audits find quality manual not updated within 12 months of organizational change',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M755',
    name: 'Escalation Pathway for Quality System Breakdown Scenarios Not Defined in QMS Procedures',
    description: 'QMS procedures describe normal operating workflows but contain no documented escalation pathway for scenarios where critical quality system functions—such as CAPA closure SLA breach or complaint backlog exceeding capacity—require executive intervention.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['escalation-pathway', 'quality-system-breakdown', 'capa-sla', 'executive-escalation', 'iso-13485'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'No documented escalation pathway for QMS capacity breakdown scenarios requiring executive intervention',
      regulatoryHook: 'ISO 13485:2016 §5.1 Management Commitment; FDA 21 CFR 820 QMSR §820.20; ISO 9001:2015 §9.3',
      detectionMethod: 'Review QMS procedure index for escalation scenarios; interview QA directors on escalation triggers and contacts',
      remediationPath: 'Define and document escalation matrix for QMS breakdown scenarios with owner, trigger threshold, and executive contact',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '48% of device QMS programmes lack formal escalation procedures for quality system capacity or SLA breach scenarios',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M756',
    name: 'Regulatory Intelligence Function Not Integrated Into QMS Change Trigger Process',
    description: 'The quality team has no formal mechanism to receive and act on regulatory intelligence—such as new FDA guidance, ISO standard revisions, or notified body interpretation updates—before they create compliance gaps in the QMS.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['regulatory-intelligence', 'qms-change-trigger', 'fda-guidance', 'iso-revision', 'compliance-gap'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'No formal regulatory intelligence-to-QMS-change-trigger pathway; new guidance creates undetected compliance gaps',
      regulatoryHook: 'ISO 13485:2016 §4.1; FDA 21 CFR 820 QMSR; EU MDR Article 10',
      detectionMethod: 'Interview QA leadership on process for receiving and actioning new FDA guidance or ISO standard revisions',
      remediationPath: 'Establish regulatory intelligence function with monitored sources, gap assessment procedure, and QMS change trigger workflow',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '52% of device quality organisations have no documented regulatory intelligence-to-change-trigger workflow',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M757',
    name: 'Supplier Quality Engineer Role Not Formally Defined Within QMS Organizational Structure',
    description: 'Supplier quality activities are informally distributed among QA generalists without a formally defined Supplier Quality Engineer role with documented responsibilities, authority, and competency requirements under ISO 13485:2016 §6.2.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['supplier-quality-engineer', 'role-definition', 'iso-13485', 'competency', 'organizational-structure'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Supplier quality activities distributed informally with no defined SQE role, authority, or competency requirements',
      regulatoryHook: 'ISO 13485:2016 §6.2 Human Resources; FDA 21 CFR 820 QMSR §820.25',
      detectionMethod: 'Review organizational chart and job descriptions for formally defined SQE responsibilities and competency criteria',
      remediationPath: 'Create SQE job description with defined responsibilities, authority, and competency requirements; assign named role owners',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '40% of device companies lack a formally defined SQE role in their QMS organizational structure',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M758',
    name: 'Quality System Performance Metrics Not Benchmarked Against Industry Peers or Regulatory Expectations',
    description: 'Management review quality KPIs are evaluated only against internal historical trends without any benchmarking against industry peer data or FDA Quality Metrics program expectations, obscuring whether performance is objectively acceptable.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['quality-metrics', 'benchmarking', 'fda-quality-metrics', 'management-review', 'peer-comparison'],
    failure_rate_pct: 39.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Quality KPIs evaluated only against internal trends; no external benchmarking against FDA Quality Metrics or peer data',
      regulatoryHook: 'FDA Quality Metrics Program; ISO 13485:2016 §5.6; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Review management review inputs for external benchmark data sources and peer comparison analysis',
      remediationPath: 'Integrate FDA Quality Metrics voluntary reporting data and industry survey benchmarks into annual management review inputs',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '35% of device companies include external quality metrics benchmarking in their management review process',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M759',
    name: 'Quality Management Review Action Items Not Tracked to Closure With Accountable Owners',
    description: 'Management review outputs include action items but no formal tracking system assigns individual owners or target dates, resulting in recurring open actions across multiple review cycles that are never formally closed.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['management-review', 'action-tracking', 'accountability', 'iso-13485', 'closure'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'qms-culture-leadership',
    data: {
      failureMode: 'Management review action items lack assigned owners and target dates; actions recur across multiple review cycles without closure',
      regulatoryHook: 'ISO 13485:2016 §5.6.3 Management Review Outputs; FDA 21 CFR 820 QMSR §820.20',
      detectionMethod: 'Trace action items from the last three management reviews through to formal closure documentation',
      remediationPath: 'Implement action register with owner, due date, and formal closure sign-off as mandatory management review output; review status at each meeting',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '47% of ISO 13485 surveillance audits cite management review action items not tracked to formal closure',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

];
