/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 69: Agentic AI: IT Service Desk & EHR Build Agents
// Part 3: H17700-H17749
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM69_PART3_PATTERNS = [
  {
    code: 'H17700',
    name: 'IT Service Desk Agent Quality Abstraction Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for quality abstraction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'minimum necessary policy', 'Series B burn rate', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17701',
    name: 'EHR Build Agent Patient Outreach Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for patient outreach but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'TJC survey evidence', 'implementation partner capacity', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17702',
    name: 'ServiceNow Triage Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for triage but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is CMS CoP: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'CMS CoP', 'referenceable health-system customer', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17703',
    name: 'Change Control Drafting Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for drafting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'NCQA HEDIS audit', 'clinical advisory board', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17704',
    name: 'CAB Summarization Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for summarization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'FDA SaMD guidance', 'FDA submission posture', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17705',
    name: 'IT Service Desk Agent Risk Scoring Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for risk scoring but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'NIST AI RMF', 'KLAS commentary', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17706',
    name: 'EHR Build Agent Worklist Prioritization Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for worklist prioritization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'ONC HTI-1', 'Epic App Orchard integration', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17707',
    name: 'ServiceNow Appeal Generation Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for appeal generation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'TEFCA participation', 'Microsoft Cloud for Healthcare', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17708',
    name: 'Change Control Order Recommendation Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for order recommendation but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'FHIR R4 mapping', 'AWS HealthLake', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17709',
    name: 'CAB Benefit Verification Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for benefit verification but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'HL7 v2 ADT reconciliation', 'Azure Health Data Services', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17710',
    name: 'IT Service Desk Agent Eligibility Prediction Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for eligibility prediction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is Epic change control: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'Epic change control', 'Snowflake Healthcare', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17711',
    name: 'EHR Build Agent Care Gap Closure Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for care gap closure but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is model registry: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'model registry', 'Databricks Lakehouse', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17712',
    name: 'ServiceNow Cohort Matching Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for cohort matching but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'deployment-site validation', 'ServiceNow workflow', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17713',
    name: 'Change Control Contract Analysis Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for contract analysis but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'MLOps monitoring', 'Salesforce Health Cloud', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17714',
    name: 'CAB Agentic Orchestration Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for agentic orchestration but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is clinical safety review: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'clinical safety review', 'startup maturity evidence', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17715',
    name: 'IT Service Desk Agent Coding Suggestion Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for coding suggestion but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'procurement RFP scoring', 'SOC 2 Type II', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17716',
    name: 'EHR Build Agent Documentation Review Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for documentation review but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'BAFO contract clause', 'HITRUST roadmap', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17717',
    name: 'ServiceNow Vendor Comparison Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for vendor comparison but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'HIPAA BAA', 'Series B burn rate', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17718',
    name: 'Change Control Capacity Forecasting Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for capacity forecasting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'minimum necessary policy', 'implementation partner capacity', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17719',
    name: 'CAB Staffing Optimization Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for staffing optimization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'TJC survey evidence', 'referenceable health-system customer', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17720',
    name: 'IT Service Desk Agent Quality Abstraction Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for quality abstraction but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is CMS CoP: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'CMS CoP', 'clinical advisory board', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17721',
    name: 'EHR Build Agent Patient Outreach Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for patient outreach but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'NCQA HEDIS audit', 'FDA submission posture', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17722',
    name: 'ServiceNow Triage Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for triage but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'FDA SaMD guidance', 'KLAS commentary', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17723',
    name: 'Change Control Drafting Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for drafting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'NIST AI RMF', 'Epic App Orchard integration', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17724',
    name: 'CAB Summarization Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for summarization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'ONC HTI-1', 'Microsoft Cloud for Healthcare', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17725',
    name: 'IT Service Desk Agent Risk Scoring Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for risk scoring but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'TEFCA participation', 'AWS HealthLake', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17726',
    name: 'EHR Build Agent Worklist Prioritization Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for worklist prioritization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'FHIR R4 mapping', 'Azure Health Data Services', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17727',
    name: 'ServiceNow Appeal Generation Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for appeal generation but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'HL7 v2 ADT reconciliation', 'Snowflake Healthcare', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17728',
    name: 'Change Control Order Recommendation Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for order recommendation but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is Epic change control: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'Epic change control', 'Databricks Lakehouse', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17729',
    name: 'CAB Benefit Verification Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for benefit verification but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is model registry: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'model registry', 'ServiceNow workflow', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17730',
    name: 'IT Service Desk Agent Eligibility Prediction Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for eligibility prediction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'deployment-site validation', 'Salesforce Health Cloud', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17731',
    name: 'EHR Build Agent Care Gap Closure Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for care gap closure but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'MLOps monitoring', 'startup maturity evidence', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17732',
    name: 'ServiceNow Cohort Matching Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for cohort matching but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is clinical safety review: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'clinical safety review', 'SOC 2 Type II', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17733',
    name: 'Change Control Contract Analysis Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for contract analysis but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'procurement RFP scoring', 'HITRUST roadmap', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17734',
    name: 'CAB Agentic Orchestration Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for agentic orchestration but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'BAFO contract clause', 'Series B burn rate', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17735',
    name: 'IT Service Desk Agent Coding Suggestion Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for coding suggestion but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'HIPAA BAA', 'implementation partner capacity', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17736',
    name: 'EHR Build Agent Documentation Review Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for documentation review but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'minimum necessary policy', 'referenceable health-system customer', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17737',
    name: 'ServiceNow Vendor Comparison Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for vendor comparison but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'TJC survey evidence', 'clinical advisory board', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17738',
    name: 'Change Control Capacity Forecasting Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for capacity forecasting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is CMS CoP: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'CMS CoP', 'FDA submission posture', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17739',
    name: 'CAB Staffing Optimization Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for staffing optimization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'NCQA HEDIS audit', 'KLAS commentary', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17740',
    name: 'IT Service Desk Agent Quality Abstraction Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for quality abstraction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'FDA SaMD guidance', 'Epic App Orchard integration', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17741',
    name: 'EHR Build Agent Patient Outreach Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for patient outreach but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'NIST AI RMF', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17742',
    name: 'ServiceNow Triage Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for triage but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'ONC HTI-1', 'AWS HealthLake', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17743',
    name: 'Change Control Drafting Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for drafting but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'TEFCA participation', 'Azure Health Data Services', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17744',
    name: 'CAB Summarization Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for summarization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'FHIR R4 mapping', 'Snowflake Healthcare', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17745',
    name: 'IT Service Desk Agent Risk Scoring Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when IT service desk agent is used for risk scoring but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when ServiceNow is not proven in production.`,
    keywords: ['IT service desk agent', 'ServiceNow', 'HL7 v2 ADT reconciliation', 'Databricks Lakehouse', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17746',
    name: 'EHR Build Agent Worklist Prioritization Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when EHR build agent is used for worklist prioritization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is Epic change control: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when change control is not proven in production.`,
    keywords: ['EHR build agent', 'change control', 'Epic change control', 'ServiceNow workflow', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17747',
    name: 'ServiceNow Appeal Generation Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when ServiceNow is used for appeal generation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is model registry: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when CAB is not proven in production.`,
    keywords: ['ServiceNow', 'CAB', 'model registry', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17748',
    name: 'Change Control Order Recommendation Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when change control is used for order recommendation but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when IT service desk agent is not proven in production.`,
    keywords: ['change control', 'IT service desk agent', 'deployment-site validation', 'startup maturity evidence', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  },
  {
    code: 'H17749',
    name: 'CAB Benefit Verification Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Agentic AI: IT Service Desk & EHR Build Agents initiatives fail when CAB is used for benefit verification but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when EHR build agent is not proven in production.`,
    keywords: ['CAB', 'EHR build agent', 'MLOps monitoring', 'SOC 2 Type II', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: IT Service Desk & EHR Build Agents',
  }
];
