// seed-medtech-dom13-erp-sap-part2.ts
// Medtech genome patterns — ERP & SAP Transformation
// Code range: M1960–M2019  (60 patterns)
// Loaded by: scripts/corpus/load-authored-genome-seeds.ts

type OfficeCategory = 'front_office' | 'middle_office' | 'back_office';

interface PatternSeed {
  code: string;
  name: string;
  officeCategory: OfficeCategory;
  failureRatePct: number;
  description: string;
  keywords: string[];
  demoRelevant?: boolean;
  subTopic?: string;
}

export const MEDTECH_DOM13_ERP_SAP_PART2_PATTERNS: PatternSeed[] = [

  // ── erp-validation: CSV / GxP / 21 CFR Part 11 / GAMP 5 ──────────────────

  {
    code: 'M1960',
    name: 'SAP S/4HANA Validation Master Plan Lacks Cross-Module Risk Classification Matrix',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `The Validation Master Plan for SAP S/4HANA covers GxP-regulated modules in separate validation sub-plans but does not include a cross-module risk classification matrix that assigns GAMP 5 software categories to every integration touchpoint between validated and non-validated modules — leaving gaps where a Category 4 configured module exchanges data with a non-validated custom ABAP report without any validation artefact tracing the interface. FDA inspectors performing a Part 11 inspection expect a Validation Master Plan that demonstrates systematic identification of all computerised system components with a direct or indirect impact on product quality, and a plan that addresses modules in isolation without a cross-module risk classification fails to meet the holistic validated system boundary definition in GAMP 5 §5.`,
    keywords: ['GAMP 5', 'Validation Master Plan', 'SAP S/4HANA', '21 CFR Part 11', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1961',
    name: 'SAP S/4HANA Purchase Information Records Lack CSV Coverage for Regulated Materials',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Purchase information records in SAP that define approved sources, pricing conditions, and delivery terms for regulated incoming materials are modified through standard SAP purchasing transactions without a computerised system validation control confirming that changes to purchase information records for critical component suppliers are subject to quality review before the changed record affects purchasing order creation. Under ISO 13485:2016 §7.4.1, purchasing information must specify quality requirements applicable to externally provided goods, and changes to the SAP purchase information records that affect quality specifications — approved supplier scope, incoming inspection requirements, and certificate-of-conformance requirements — without quality review are de facto changes to the quality-relevant purchasing specification outside the approved change control process.`,
    keywords: ['GAMP 5', 'CSV', 'SAP S/4HANA', 'ISO 13485', 'purchasing controls'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1962',
    name: 'SAP Quality Management Inspection Plan Versions Not Controlled Under 21 CFR Part 11',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `SAP Quality Management inspection plans defining sampling plans, acceptance criteria, and inspection characteristics for device components are maintained as versioned objects in SAP, but the version control mechanism does not implement 21 CFR Part 11 §11.10(e) audit trail requirements — changes to inspection plan acceptance criteria, sampling levels, or characteristic sequences do not generate a complete audit trail capturing the change author, timestamp, prior value, and new value in a manner that can be exported for regulatory review. When an FDA investigator requests the history of changes to a specific incoming inspection plan over a three-year period, the SAP inspection plan change history lacks the granularity required to demonstrate that acceptance criteria were not loosened without documented justification, creating a data integrity finding for all quality inspection results generated using the inspection plan.`,
    keywords: ['21 CFR Part 11', 'SAP QM', 'inspection plan', 'GAMP 5', 'audit trail'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1963',
    name: 'GAMP 5 Category Assignment for SAP Quality Module Underestimates Configurable Software Risk',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `The GxP risk assessment for the SAP S/4HANA Quality Management module assigns a GAMP 5 Category 4 classification to the module as a whole, treating configurable application software as a uniform category — but the specific quality management workflows implemented for batch disposition, quality notification generation, and inspection lot processing involve substantial custom ABAP code, user exits, and BAdI implementations that exceed the configuration definition for Category 4 and should be classified as Category 5 bespoke software requiring full software lifecycle validation. The GAMP 5 category under-assignment results in a validation effort that follows the Category 4 protocol — configuration testing against specifications — without the additional design reviews, code reviews, and unit testing required for Category 5 software, leaving the custom quality workflow logic validated at a lower level of rigor than the regulatory function it implements warrants.`,
    keywords: ['GAMP 5', 'SAP QM', 'CSV', 'bespoke software', '21 CFR Part 11'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1964',
    name: `SAP Production Order Closure Without Complete Batch Record Triggers 21 CFR 820 Gap`,
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `SAP S/4HANA production order completion and goods receipt posting can be executed without confirming that all mandatory batch record entries — in-process inspection results, deviation sign-offs, and environmental monitoring reference confirmations — have been completed, because the production order status management configuration does not enforce a user-exit check requiring all GxP mandatory fields to be populated before the order is technically completed and inventory posted to unrestricted stock. The device history record under 21 CFR 820.184 requires that each production lot have a complete device history record, and a SAP production order that permits goods receipt to unrestricted inventory before the DHR is complete creates finished goods inventory whose production history record cannot meet the completeness standard required for regulatory compliance.`,
    keywords: ['SAP production order', 'batch records', 'GAMP 5', 'FDA 21 CFR 820', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1965',
    name: 'SAP Test System Used for Regulated CAPA Investigation Evidence Lacks Part 11 Controls',
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `Quality engineering teams reproduce manufacturing defects in the SAP development or quality assurance client systems as part of CAPA root cause investigations, generating electronic records of simulated production runs and quality inspection results in non-production SAP clients that do not have 21 CFR Part 11 audit trail and access control configurations active — because Part 11 controls are typically implemented only in the validated production client. When CAPA investigation reports cite evidence from SAP test client test runs, the underlying records do not meet Part 11 requirements for authentic, accurate, and trustworthy electronic records, creating a quality system documentation gap where CAPA evidence records are of lower evidentiary value than the production records they are intended to simulate.`,
    keywords: ['21 CFR Part 11', 'CAPA', 'SAP S/4HANA', 'GAMP 5', 'GxP validation'],
    subTopic: 'erp-validation',
  },
  {
    code: 'M1966',
    name: `SAP Workflow Approval Steps Not Validated as Electronic Signature Equivalents`,
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `SAP workflow approval steps used for quality hold release, batch disposition authorisation, and engineering change order approval are implemented using the SAP Business Workflow agent assignment mechanism — where a user receives a workflow task and clicks "complete" to advance the workflow — without the system prompting for password re-entry, generating a signature meaning statement, or linking the approval action to the GxP attestation the approver is making, falling short of 21 CFR Part 11 §11.50 requirements for electronic signature components. The workflow completion action is treated by the SAP implementation team as an approval step equivalent to an electronic signature, but without the mandated signature components it represents an acknowledgment of task completion rather than a signed attestation to a quality or regulatory statement, and FDA inspectors distinguish between the two in determining whether an electronic signature is Part 11-compliant.`,
    keywords: ['21 CFR Part 11', 'electronic signature', 'SAP workflow', 'GAMP 5', 'batch disposition'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1967',
    name: `SAP System Clock Synchronisation Not Validated — Audit Trail Timestamp Integrity at Risk`,
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `The SAP S/4HANA production server's system clock synchronisation to a validated time standard has not been documented as a qualification activity in the GAMP 5 infrastructure qualification record, and the time synchronisation interval and source NTP server are not specified in the validated configuration baseline — leaving open the question of whether SAP audit trail timestamps accurately represent the real-world time of each recorded action to the precision required by 21 CFR Part 11 §11.10(e). A clock drift of even a few minutes in the SAP system clock can create audit trail entries where the recorded timestamp of a batch disposition is chronologically earlier than the inspection results that led to the disposition decision, creating an audit trail sequence anomaly that FDA investigators interpret as evidence of pre-dating or backdating of quality records.`,
    keywords: ['21 CFR Part 11', 'GAMP 5', 'audit trail', 'SAP S/4HANA', 'GxP validation'],
    subTopic: 'erp-validation',
  },
  {
    code: 'M1968',
    name: `GAMP 5 Vendor Assessment for SAP S/4HANA Not Refreshed After Version Upgrade`,
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `The GAMP 5 supplier assessment for SAP SE as the software vendor supporting the validated S/4HANA installation was completed during the initial implementation and has not been refreshed following major version upgrades — SAP S/4HANA 2021 to 2023 — that introduced significant changes to the quality management module's data structures, workflow engine, and audit log architecture. GAMP 5 §6.1 requires that the regulated user assess the software supplier's quality management system and the degree of supplier QMS assurance appropriate to the GAMP 5 category, and a supplier assessment that does not reflect the version of the software in current GxP production use cannot demonstrate that the assessment covers the specific version's quality attributes, leaving an implicit assumption that the initial assessment remains valid through all subsequent version changes.`,
    keywords: ['GAMP 5', 'vendor assessment', 'SAP S/4HANA', 'CSV', 'GxP validation'],
    subTopic: 'erp-validation',
  },
  {
    code: 'M1969',
    name: 'SAP S/4HANA Process Order Confirmation Screen Modification Voids OQ Evidence',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `A post-go-live enhancement to the SAP production order confirmation screen — adding a custom field for operator identification number and modifying the goods movement confirmation sequence — was approved through the IT change management board without routing to the validation team for a GAMP 5 change impact assessment, and was transported to production without re-executing the Operational Qualification test scripts that covered the production order confirmation workflow. The OQ test evidence in the validation file no longer describes the screen or confirmation sequence currently in production, meaning the validated state documented in the OQ report is not the state the system operates in — a fundamental CSV breakdown where the validation evidence base describes a system that no longer exists.`,
    keywords: ['GAMP 5', 'OQ', 'SAP S/4HANA', 'CSV', '21 CFR Part 11'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1970',
    name: `Performance Qualification for SAP Batch Release Under Peak Volume Not Executed`,
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `The Performance Qualification for the SAP S/4HANA batch release workflow was executed in a test environment using a sample of ten batch disposition records to confirm system functionality, without simulating the peak production volume of 200 concurrent batch release transactions that occurs at fiscal quarter-end when multiple production campaigns are closed simultaneously — leaving the production system in a state where PQ evidence demonstrates functionality but not performance fitness under operational load conditions. Under GAMP 5, Performance Qualification must demonstrate that the system performs its intended functions within operational parameters, and operational parameters for a batch release system in a medical device manufacturer include peak transaction volume, concurrent user counts, and response time under load — parameters that are not captured in a ten-record functional PQ executed in a reduced-capacity test environment.`,
    keywords: ['GAMP 5', 'PQ', 'SAP S/4HANA', 'batch records', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-validation',
  },
  {
    code: 'M1971',
    name: `SAP Number Range Configuration for GxP-Critical Documents Not in Validated Baseline`,
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `SAP number range configurations governing the sequential numbering of quality notification records, batch master records, and inspection lot numbers are maintained in the SAP number range object table but are not documented as validated configuration parameters in the CSV configuration specification, creating a gap where the numbering configuration that ensures unique, sequential, and non-reusable record identifiers for GxP records — a requirement under 21 CFR Part 11 §11.10(a) for accurate and complete copies of records and under FDA CGMP for complete device history records — is outside the formal validated configuration baseline and could be changed without triggering a GxP change assessment.`,
    keywords: ['GAMP 5', 'SAP configuration', '21 CFR Part 11', 'CSV', 'GxP validation'],
    subTopic: 'erp-validation',
  },

  // ── sap-quality-integration: SAP QM, MES, electronic batch records ─────────

  {
    code: 'M1972',
    name: `SAP QM Usage Decision Does Not Block Goods Issue When Batch Is Conditionally Released`,
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `SAP Quality Management's usage decision functionality for incoming inspection lots is configured to allow a "conditionally released" usage decision that posts inventory to unrestricted use stock while a quality hold reason is still open — because the usage decision code configuration does not enforce a batch restriction status transition for conditional releases — allowing materials with unresolved quality concerns to be consumed in production before the conditional release conditions have been verified and closed. An FDA inspection of incoming material quality records discovers that SAP usage decision history shows conditional releases for three critical component batches where the release conditions were never formally closed, and the finished device lots manufactured with those components have a batch history that cannot demonstrate the conditional release conditions were satisfied before consumption.`,
    keywords: ['SAP QM', 'usage decision', 'batch management', 'ISO 13485', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1973',
    name: `SAP QM-MES Result Transfer Uses Delta Sync That Misses Late-Posted Inspection Results`,
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `The interface transferring in-process inspection results from the Manufacturing Execution System to SAP Quality Management inspection lots uses a delta synchronisation approach that captures results posted in MES after the last sync cycle was completed, but late-posted corrections — where an operator adds a result after the batch record is nominally closed due to a system access issue or paper-to-digital transcription delay — are not captured by the delta sync because the late post falls outside the sync window. The MES-to-SAP inspection result transfer is the primary data source for the electronic batch record in SAP, and late-posted corrections that are visible in MES but absent from the SAP batch record create a discrepancy between the MES source record and the SAP batch record, raising the question of which system holds the authoritative record and whether the SAP batch record is complete.`,
    keywords: ['MES integration', 'SAP QM', '21 CFR Part 11', 'GAMP 5', 'electronic batch records'],
    demoRelevant: true,
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1974',
    name: `SAP Quality Notification Escalation Rules Do Not Route MDR-Threshold Events to Regulatory Affairs`,
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `SAP Quality Notification categorisation and escalation configuration routes complaint records by device family and complaint type to the appropriate quality engineering team for investigation but does not include an MDR threshold screening rule that evaluates whether the complaint describes an event that meets or potentially meets the 21 CFR Part 803 MDR reporting threshold — requiring a manual secondary review process where quality engineers must independently assess each complaint for MDR reportability after SAP routing has already directed the complaint to the technical investigation workstream. The gap between SAP complaint routing and MDR threshold screening creates a timeline risk because the manual MDR assessment step must be completed within the 30-day MDR reporting window, but SAP's investigation workflow does not enforce the MDR timeline as a separate due-date obligation, and high investigation volumes during product quality events result in MDR assessments that miss the reporting deadline.`,
    keywords: ['SAP QM', 'MDR', 'complaint handling', 'FDA 21 CFR 803', 'quality notification'],
    demoRelevant: true,
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1975',
    name: `SAP QM Sampling Procedure for Released Finished Goods Does Not Reflect ANSI/ASQ Z1.4 Level`,
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `The SAP QM sampling procedure configuration for final device inspection uses a fixed sample size specified during the SAP implementation based on a general AQL level, without implementing the ANSI/ASQ Z1.4 or ISO 2859-1 switching rules that require tightened inspection when consecutive lots fail and permit reduced inspection when consecutive lots pass — meaning the sampling intensity never adjusts in response to process performance, systematically over-inspecting stable product lines and under-reacting to quality deterioration. The static SAP sampling procedure violates the adaptive sampling intent of ISO 13485:2016 §8.2.6, which requires that statistical techniques used for inspection and measurement be controlled and appropriate to the situation — a situation where the SAP configuration treats all production lots as requiring the same inspection intensity regardless of historical process performance is not an appropriate statistical technique.`,
    keywords: ['SAP QM', 'sampling', 'ISO 13485', 'ANSI ASQ Z1.4', 'AQL'],
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1976',
    name: `SAP Electronic Batch Record Assembly Lacks Completeness Check Before Quality Disposition`,
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `SAP's electronic batch record for each finished device lot is assembled from multiple source records — production order confirmations, quality inspection lots, goods movement records, and attached PDFs for calibration certificates — but the batch disposition workflow does not enforce a completeness check confirming that all mandatory batch record sections have been populated before the usage decision can be posted, allowing quality reviewers to release batches to unrestricted stock with incomplete electronic batch records because the system does not block disposition on incomplete records. Under 21 CFR 820.184, the device history record must be maintained to demonstrate that the device was manufactured in accordance with the device master record, and a batch disposition process that does not enforce completeness before release creates finished goods whose DHR cannot demonstrate compliance at the time of release.`,
    keywords: ['SAP QM', 'electronic batch records', 'GAMP 5', 'FDA 21 CFR 820', 'batch disposition'],
    demoRelevant: true,
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1977',
    name: `SAP and LIMS Maintain Separate Stability Study Results With No Reconciliation Control`,
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Stability study results for device components and reagent kits are managed in both the LIMS and SAP Quality Management systems — LIMS holds the instrument-generated analytical data, while SAP holds the stability acceptance criteria and the disposition decision — but no automated reconciliation confirms that the stability results entered in SAP match the instrument results in LIMS before the stability disposition is posted, creating a manual transcription gap where entry errors in the SAP stability inspection lot go undetected. A stability data integrity finding by an FDA inspector reviewing an IVD diagnostic kit registration dossier identified that the SAP-recorded stability result for a specific reagent lot differed from the LIMS instrument record by a margin sufficient to change the pass/fail outcome, and the SAP disposition was used as the basis for the lot release decision without LIMS-source verification.`,
    keywords: ['LIMS integration', 'SAP QM', 'stability study', 'GxP data integrity', 'ISO 13485'],
    demoRelevant: true,
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1978',
    name: `SAP Quality Certificate Generation Does Not Pull MDR-Verified Device Status`,
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `SAP's automated quality certificate of conformance generation for device shipments pulls the quality inspection result and batch release status from the SAP batch master but does not check the complaint and quality notification history to confirm that the batch being shipped is not subject to an open investigation or pending MDR assessment — meaning a certificate of conformance can be generated and shipped with a device lot that is under active quality investigation, because the certificate generation logic only evaluates the SAP batch classification release status, not the open quality notification queue. A customer receiving a certificate of conformance for a device lot later subject to a field safety corrective action has a legitimate quality system concern about the device manufacturer's quality release process, and the SAP certificate generation gap that produces compliant-looking certificates for investigationally compromised lots creates a trust and liability risk in addition to the immediate quality system deficiency.`,
    keywords: ['SAP QM', 'certificate of conformance', 'complaint handling', 'ISO 13485', 'MDR'],
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1979',
    name: `SAP QM Control Chart Configuration Does Not Trigger CAPA at Statistical Process Control Limits`,
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `SAP Quality Management's SPC chart functionality is configured to display control chart data for monitored process parameters but is not configured to automatically generate a quality notification or CAPA request when a control chart rule violation is detected — such as eight consecutive points on one side of the centreline or two of three consecutive points beyond two sigma — meaning process capability trends that indicate imminent quality failure are visible to quality engineers reviewing SAP SPC charts but do not trigger the automated corrective action initiation required under ISO 13485:2016 §8.4. The disconnect between SAP SPC data and the CAPA system creates a dependency on quality engineer vigilance to manually initiate CAPAs in response to control chart signals, and in high-volume manufacturing environments the SPC-to-CAPA initiation step is consistently delayed or skipped during peak production periods.`,
    keywords: ['SAP QM', 'SPC', 'CAPA', 'ISO 13485', 'statistical process control'],
    subTopic: 'sap-quality-integration',
  },
  {
    code: 'M1980',
    name: `SAP Goods Receipt for Contract Manufacturing Lacks Incoming Test Report Validation`,
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `SAP goods receipt processing for finished device assemblies received from contract manufacturers posts inventory to unrestricted stock after three-way match without requiring the submission and review of the contract manufacturer's incoming test report or certificate of conformance as a mandatory attachment — because the goods receipt workflow does not enforce document attachment before posting — allowing devices manufactured by contract manufacturers to enter Northstar's inventory and be available for customer shipment without the quality documentation review required under ISO 13485:2016 §7.4.3 for purchased product verification. The absence of incoming documentation enforcement in SAP is discovered during an internal audit when a sample of contract-manufactured device lots in inventory shows that 30% have no incoming test report attached to the SAP goods receipt record, with the test reports existing only in email correspondence between the procurement and quality teams.`,
    keywords: ['SAP goods receipt', 'contract manufacturing', 'ISO 13485', 'incoming inspection', 'quality documentation'],
    demoRelevant: true,
    subTopic: 'sap-quality-integration',
  },

  // ── erp-change-management: ERP upgrade, SAP patching, 21 CFR 820 ──────────

  {
    code: 'M1981',
    name: `ERP Upgrade Project Skips GxP Impact Triage Gate — Validated Modules Changed Without CSV`,
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `The SAP S/4HANA upgrade project that moves from support package stack 12 to stack 18 is scoped and managed as an IT upgrade project with functional regression testing, without a formal GxP impact triage gate that identifies which validated GxP modules are affected by the upgrade and requires CSV activity — partial re-validation — before the upgraded system is placed back into GxP operation. GAMP 5 §10 requires that changes to validated systems be assessed for impact on the validated state, and a support package stack upgrade that includes corrections to quality management, production planning, and financial accounting functions is a material change to validated software that requires a documented impact assessment and execution of affected validation test scripts before the upgraded system processes GxP-relevant transactions.`,
    keywords: ['ERP upgrade', 'GAMP 5', 'SAP S/4HANA', 'CSV', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1982',
    name: `SAP Upgrade Regression Suite Does Not Include GxP Scenario Library — Post-Upgrade Defects Undetected`,
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `The regression test suite used for SAP S/4HANA upgrade testing is maintained by the IT department as a functional test library covering business process scenarios derived from business requirements, but it does not include a parallel GxP validation scenario library derived from the validated process flows documented in the CSV test protocols — meaning upgrade regressions in GxP-critical functions, such as batch disposition approval routing, electronic signature component display, and audit log field population, are not tested during upgrade regression because the IT regression suite does not cover these regulatory-specific scenarios. Post-upgrade defects in GxP functions are discovered only after the upgraded system has been in GxP production for several weeks, when quality engineers reviewing batch records notice discrepancies that should have been caught by a GxP-specific regression test during the upgrade testing phase.`,
    keywords: ['SAP upgrade', 'regression testing', 'GAMP 5', 'CSV', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1983',
    name: `SAP S/4HANA Annual Enhancement Release Treated as Minor Update — GAMP 5 Change Classification Error`,
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `SAP's annual S/4HANA release update, which introduces significant changes to module functionality, database tables, and workflow engine behaviours, is classified by the IT change management board as a "minor update" exempt from GxP change management review — based on the assumption that SAP's annual release is equivalent to a security patch — when GAMP 5's change classification criteria require that changes resulting in new or modified functionality in a validated system be assessed as significant changes requiring impact assessment and re-validation of affected functions. Northstar Clinical's GxP modules are affected by three functional changes in the annual S/4HANA release that alter batch management behaviour, inspection lot creation rules, and usage decision routing — changes that are deployed to the GxP production environment without validation evidence, placing the system in an unvalidated operating state for those affected functions.`,
    keywords: ['GAMP 5', 'SAP S/4HANA', 'change management', 'CSV', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1984',
    name: `ERP Change Freeze Policy Conflicts With Mandatory FDA-Driven Software Corrections`,
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Northstar Clinical's SAP change freeze policy, implemented to protect financial close periods and product launch milestones, prohibits transport requests to the GxP production system during freeze periods of up to six weeks — but the change freeze policy includes no exception pathway for mandatory FDA-driven software corrections, such as corrections to 21 CFR Part 11 audit trail configuration required by an FDA warning letter remediation plan, that cannot be deferred without extending the regulatory compliance timeline. The absence of a regulatory-priority exception pathway in the SAP change control process means that the GxP validation team must either violate the change freeze to implement mandatory corrections or accept a compliance remediation delay that extends the Warning Letter response period and increases the FDA enforcement risk during the freeze.`,
    keywords: ['SAP change management', 'GAMP 5', 'FDA warning letter', '21 CFR Part 11', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1985',
    name: `SAP Landscape Strategy Does Not Maintain a Validated Reference Client for Rollback Comparison`,
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `The SAP S/4HANA system landscape strategy uses a standard three-client model — development, quality assurance, and production — without maintaining a validated reference client that preserves the last validated configuration baseline for comparison after changes are applied, making it impossible to perform a configuration delta comparison between the current production state and the last validated baseline to identify the accumulated configuration drift since the last full validation was performed. GAMP 5 recommends that the validated configuration baseline be maintained in a form that permits comparison against the current production configuration, and without a reference client or configuration snapshot mechanism, the organisation cannot quantify the extent to which the current production system deviates from its validated baseline without conducting a full configuration audit.`,
    keywords: ['GAMP 5', 'SAP landscape', 'CSV', 'configuration management', 'GxP validation'],
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1986',
    name: `SAP Project System for R&D Investment Tracking Not Aligned With 21 CFR 820 Design Control`,
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `The SAP Project System used to track R&D expenditures by project phase allocates costs by project milestone but does not enforce the phase-gate structure required for design and development controls under 21 CFR 820.30 — specifically, SAP does not block continued cost posting to a design phase when the design review gate for that phase has not been formally approved in the QMS, allowing project teams to record development expenditures in phases they have not been authorised to enter by the design review governance process. The SAP-QMS phase-gate integration gap means that SAP project cost records do not provide reliable evidence of design control compliance, and an FDA inspection of the design and development records for a 510(k) submission cannot use SAP project data to demonstrate that design phase gates were completed before development activities proceeded.`,
    keywords: ['SAP PS', 'design control', 'FDA 21 CFR 820', 'R&D tracking', 'project management'],
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1987',
    name: `SAP Patching Under FDA Quality System Regulation Creates Undocumented System Configuration Changes`,
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `SAP basis-level patches applied under the emergency patch process modify SAP system tables, profile parameters, and kernel settings that are part of the validated SAP configuration baseline without generating a change record in the GxP change management system — because the emergency patch process bypasses the standard SAP change management transport mechanism and applies changes directly to the production system at the database or operating system layer. Under FDA 21 CFR 820.40, document control requires that changes be reviewed and approved before implementation, and a basis-level patch that modifies validated system configuration parameters without a GxP change assessment, impact evaluation, and documented approval is an unauthorised change to a quality system component subject to FDA inspection.`,
    keywords: ['SAP patching', 'GAMP 5', 'FDA 21 CFR 820', 'change management', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'erp-change-management',
  },
  {
    code: 'M1988',
    name: `ERP Stabilisation Post-Go-Live Deferral Creates Accumulated GxP Technical Debt`,
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `After SAP S/4HANA go-live, the post-go-live stabilisation phase identifies 43 GxP-relevant configuration gaps and deficiencies — missing audit trail fields, incomplete electronic signature configurations, and inspection plan settings that do not match the validation specifications — but the stabilisation project team defers remediation of non-critical GxP gaps to a future phase to meet the business operations handover deadline, accepting residual validated state deficiencies without documenting them as formal residual validation risks in the validation plan. The consequence is a production system with known GxP compliance gaps that are tracked in the project issue log but not in the quality system as open non-conformances with assigned owners and remediation timelines, and as the stabilisation team disbands the issue list becomes orphaned without systematic remediation governance.`,
    keywords: ['GAMP 5', 'SAP go-live', 'GxP validation', 'CSV', 'post-go-live remediation'],
    demoRelevant: true,
    subTopic: 'erp-change-management',
  },

  // ── ai-erp-enterprise: AI/ML in SAP S/4HANA, LLM ERP config, GenAI risk ────

  {
    code: 'M1989',
    name: `SAP AI Joule Procurement Recommendations Deployed Without ISO 13485 Supplier Control Review`,
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `SAP's embedded AI assistant Joule, deployed in the SAP S/4HANA procurement workflow to generate supplier recommendation, purchase order draft, and price negotiation advice, makes supplier suggestions from the approved vendor list without accessing the ISO 13485 qualification status, last audit date, or approved product scope fields maintained in a separate quality system — because Joule's underlying data model does not integrate with the external QMS API — resulting in Joule recommending suppliers for critical device components whose ISO 13485 qualification has lapsed or whose approved scope does not cover the specific component being sourced. Procurement teams using Joule recommendations without independently verifying ISO 13485 qualification status create purchase orders for regulated components from unqualified suppliers, generating a supply chain compliance finding under ISO 13485:2016 §7.4.1 and requiring a retrospective supplier qualification assessment for all affected component batches.`,
    keywords: ['SAP AI Joule', 'ISO 13485', 'supplier qualification', 'GAMP 5', 'procurement AI'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1990',
    name: `SAP S/4HANA Generative AI Finance Copilot Creates Journal Entries Bypassing SOX Dual Control`,
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `SAP's generative AI finance assistant for automated journal entry creation, deployed in Northstar Clinical's month-end financial close, generates and posts standard adjustment entries — accruals, prepaid expense amortisations, and intercompany eliminations — with a single-user approval workflow, bypassing the dual-authorisation control for manual journal entries above $50,000 that is documented as a key preventive control in the SOX 404 control framework. The AI journal entry tool's single-approval workflow was configured for speed rather than compliance because the implementation team treated AI-generated entries as lower-risk than manually drafted entries, an assumption that SOX 404 does not support — the SOX control framework governs the entry posting process regardless of whether the entry was drafted by a human or an AI system.`,
    keywords: ['SAP AI finance', 'SOX 404', 'journal entry automation', 'GenAI ERP', 'financial controls'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1991',
    name: `AI-Generated SAP Configuration Specification Lacks GxP Control Point Identification`,
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `An AI tool used to generate the SAP functional configuration specification from business process workshop outputs produces a comprehensive configuration document that maps business requirements to SAP configuration settings but does not flag which configuration settings correspond to GxP control points — audit trail activation switches, electronic signature requirement settings, and batch management controls — leaving the validation team without the critical configuration point identification needed to define the GAMP 5 CSV test scope from the AI-generated specification document. The AI specification tool generates documentation optimised for SAP configuration completeness, not regulatory compliance traceability, and the validation team that adopts the AI-generated specification as the basis for their CSV test protocols produces test scripts that confirm configuration completeness without confirming that GxP control points are correctly configured.`,
    keywords: ['AI SAP configuration', 'GAMP 5', 'CSV', 'SAP S/4HANA', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1992',
    name: `LLM ERP Implementation Assistant Recommends SAP Best Practices That Conflict With GAMP 5`,
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `An LLM-based ERP implementation assistant used by the SAP implementation partner to answer configurator questions and recommend SAP best-practice settings consistently recommends the SAP industry solution defaults for pharmaceutical manufacturing when asked about medical device quality management configuration — and the pharmaceutical defaults for audit trail, electronic signature, and batch management are not identical to the GAMP 5-compliant settings required for FDA medical device GMP, introducing a configuration alignment gap that the quality validation team discovers only during the CSV test execution phase when test scenarios designed to the medical device GMP requirements fail against the pharmaceutical-default configuration. The LLM assistant's training data overweights pharmaceutical SAP implementations relative to medical device implementations, causing systematic best-practice recommendation errors for GxP medical device configuration scenarios.`,
    keywords: ['LLM ERP assistant', 'GAMP 5', 'SAP S/4HANA', 'GxP validation', '21 CFR Part 11'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1993',
    name: `GenAI SAP Change Impact Assessment Tool Does Not Recognise Validated System Boundary`,
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `A generative AI change impact assessment tool integrated with the SAP change management workflow analyses proposed transport requests and generates change impact narratives, but the AI tool does not have access to the validated system boundary documentation that defines which SAP modules, transaction codes, and configuration tables are within the GAMP 5 validated scope — causing the AI impact assessment to rate changes to validated GxP modules at the same risk level as changes to non-validated commercial modules, and recommending approval routing that does not include the quality validation team review required for GxP-scope changes. The AI change impact tool was trained on IT change management risk data from non-regulated SAP installations and generates impact assessments calibrated to IT service risk rather than GxP regulatory compliance risk, systematically under-escalating changes to validated modules.`,
    keywords: ['GenAI change management', 'GAMP 5', 'SAP S/4HANA', 'CSV', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1994',
    name: `SAP AI Demand Sensing Module Trained on Distributor Orders Creates Bullwhip Amplification`,
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `SAP's AI-powered demand sensing module is trained on distributor purchase order history rather than end-customer consumption data — because point-of-use consumption data from hospital inventory management systems is not systematically collected or integrated with SAP — causing the AI demand signal to amplify distributor stocking and de-stocking cycles as if they represent end-market demand changes, producing production plans that overshoot actual patient demand during distributor build periods and create supply shortages during distributor drawdown periods. For imaging and diagnostics device manufacturers with long production lead times and cold-chain storage requirements, AI demand sensing amplification creates a costly inventory mismatch cycle where excess production during artificial demand peaks is followed by production stoppages to draw down over-inventory, disrupting the manufacturing plan and creating expired-product write-offs for time-limited reagent kits.`,
    keywords: ['SAP AI demand sensing', 'supply chain', 'demand planning', 'SAP S/4HANA', 'inventory management'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1995',
    name: `AI ERP Cash Flow Forecasting Ignores Regulatory Reserve Obligations — Liquidity Misstatement`,
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `SAP's AI-powered cash flow forecasting tool generates 13-week rolling liquidity forecasts from SAP receivables, payables, and bank account data without incorporating regulatory reserve obligations — notified body certification fees, FDA registration fees, PMDA application fees, and post-market surveillance cost accruals — that are maintained outside the SAP accounts payable workflow in the regulatory affairs budget tracking system. The AI forecast presents a liquidity picture that overstates free cash by the amount of unaccrued regulatory obligations, causing the CFO and treasury team to approve capital allocation decisions based on AI-forecast cash that is already committed to regulatory compliance obligations, creating a liquidity surprise when the regulatory invoices post to SAP and temporarily reduce available cash below the minimum liquidity covenant in Northstar Clinical's credit facility.`,
    keywords: ['SAP AI cash forecasting', 'treasury', 'SOX 404', 'financial controls', 'regulatory reserves'],
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1996',
    name: `AI-Powered SAP Quality Analytics Flags False CAPA Triggers From Seasonal Complaint Patterns`,
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `An AI quality analytics module deployed on top of SAP quality notification data generates automated CAPA recommendations when complaint frequency exceeds a statistical threshold — but the model was trained on a 24-month data set that does not include enough historical data to distinguish seasonal complaint patterns (higher IVD complaint rates during respiratory disease season when kit usage surges) from genuine process deterioration signals, causing the AI module to trigger CAPA recommendations for seasonal volume spikes that do not represent product quality issues. Quality teams following up AI-triggered CAPAs for seasonal complaint patterns conduct full root cause investigations that consume quality engineering resources without identifying actionable corrective actions, causing CAPA backlog growth and diluting attention from genuine quality signals — a quality resource allocation failure driven by AI model underfitting to seasonal complaint dynamics.`,
    keywords: ['AI quality analytics', 'SAP QM', 'CAPA', 'ISO 13485', 'complaint analytics'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1997',
    name: `SAP S/4HANA Embedded AI Pricing Violates Anti-Kickback Statute Guardrails for HCP Customers`,
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `SAP S/4HANA's AI-driven pricing module uses customer purchase history, deal type, and competitive pricing data to generate dynamic discount recommendations for sales representatives, but the pricing model does not enforce the federal anti-kickback statute (AKS) guardrails that limit the maximum discount permissible for sales to government-covered programme beneficiaries — Medicare and Medicaid-funded hospital purchases — because the AI model was trained on commercial pricing data that does not distinguish between government-covered and commercial customers. Sales representatives relying on AI-generated pricing recommendations for hospital accounts that are primarily Medicare-reimbursed create invoice transactions at discount levels that exceed AKS safe harbour thresholds, generating potential False Claims Act exposure that is only identified during an annual compliance review of SAP pricing data.`,
    keywords: ['SAP AI pricing', 'anti-kickback statute', 'AKS', 'HCP engagement', 'compliance controls'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1998',
    name: `LLM SAP Query Assistant Provides Incorrect Regulatory Status Answers From Stale Master Data`,
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `An LLM-based SAP query assistant deployed in the procurement and regulatory teams answers natural-language questions about device regulatory status, supplier qualification standing, and active material specifications by querying SAP master data fields — but the LLM assistant does not timestamp its responses or indicate the last-updated date of the underlying SAP data, causing users to receive regulatory status answers based on SAP master data that has not been updated to reflect recent qualification lapses, specification revisions, or clearance changes that are tracked in external regulatory systems. A regulatory affairs team member using the LLM SAP assistant to check whether a specific device configuration is currently cleared for the EU market receives a "cleared" response based on a CE certificate reference in the SAP material master that has been superseded by a lapsed notified body certificate, and acts on the incorrect status in a customer quotation for a clinical site in Germany.`,
    keywords: ['LLM SAP assistant', 'regulatory status', 'master data', 'EU MDR', 'SAP S/4HANA'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M1999',
    name: `AI Inventory Optimisation in SAP Reduces Safety Stock Below Regulatory Service Level for Critical Devices`,
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `SAP's AI inventory optimisation tool recommends safety stock reductions for device product lines based on recent demand variability and lead time data, driving down working capital without modelling the regulatory and patient safety consequences of a stockout — specifically, that a stockout of an imaging contrast agent delivery system or a point-of-care diagnostic kit is not a commercial inconvenience but a patient safety event that triggers FDA medical device shortage reporting obligations under the CARES Act. The AI optimisation model's objective function is working capital cost minimisation, and it treats all product lines symmetrically when evaluating safety stock reduction opportunities, without a product-level flag distinguishing devices where a supply interruption creates a regulatory reporting obligation from commodity products where a temporary stockout is a manageable commercial event.`,
    keywords: ['SAP AI inventory optimisation', 'safety stock', 'FDA shortage reporting', 'CARES Act', 'supply chain'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2000',
    name: `GenAI SAP Compliance Monitoring Misclassifies GxP Configuration as Non-Regulated IT Settings`,
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `A generative AI compliance monitoring tool that continuously scans SAP configuration tables for compliance deviations against a rule library is deployed for the SAP S/4HANA environment but uses a rule library built for financial systems SOX compliance without a GxP-specific rule extension — causing the AI compliance monitor to flag SOX-relevant configuration deviations accurately while systematically missing GAMP 5 validated configuration deviations such as disabled audit trail logging for batch management tables or inactive electronic signature requirements for quality notification approval workflows. Quality engineering discovers the AI compliance monitor's GxP blind spot during an internal audit when a manual SAP configuration review identifies validated configuration deviations that the AI compliance tool has not flagged in six months of automated monitoring, demonstrating that the AI tool provided false assurance of validated system integrity.`,
    keywords: ['GenAI compliance monitoring', 'GAMP 5', 'SAP S/4HANA', 'SOX 404', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2001',
    name: `AI SAP S/4HANA Regulatory Reporting Module Generates EU MDR PSUR Drafts Without PMS Data Integration`,
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `An AI module integrated with SAP's regulatory reporting workflow generates draft Periodic Safety Update Report outlines for EU MDR compliance by extracting complaint and MDR data from SAP QM quality notifications — but the AI PSUR generation tool does not pull the real-world evidence from post-market clinical follow-up studies, literature surveillance records, and registry data that EU MDR Annex III requires for a complete PSUR, producing a draft that is structurally compliant but substantively incomplete because only the SAP-sourced complaint data is populated. Regulatory affairs teams that use AI-generated PSUR drafts as the submission basis without supplementing them with the non-SAP post-market evidence sources submit PSURs to notified bodies that lack the clinical evidence component required by EU MDR Article 86, generating a major non-conformity finding in the notified body review that requires a complete PSUR revision.`,
    keywords: ['AI PSUR generation', 'EU MDR', 'SAP QM', 'post-market surveillance', 'notified body'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2002',
    name: `SAP AI Natural Language Interface for Quality Data Queries Returns Unvalidated Aggregate Results`,
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `An AI natural language query interface deployed on top of SAP's quality management database allows quality engineers to ask plain-language questions and receive aggregate quality data — first-pass yield by product line, CAPA closure rate by month, complaint rate per 1,000 units — without the query logic being validated as a quality system report under 21 CFR 820.250 or ISO 13485 §8.4, which require that statistical techniques be controlled and that the data sources and calculation methods for quality metrics be defined and validated. Quality leadership presents AI-generated quality metrics from the natural language interface in management review meetings without recognising that the aggregate results are derived from unvalidated query logic that may include or exclude records inconsistently, and the management review decisions made on the basis of AI-aggregated quality data do not meet the quality system requirement for controlled statistical techniques.`,
    keywords: ['SAP AI query', 'ISO 13485', 'quality metrics', 'validated reporting', 'GAMP 5'],
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2003',
    name: `AI ERP Supplier Risk Scoring Ignores GMP Inspection History — Qualified Supplier Default Risk`,
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `An AI supplier risk scoring system integrated with SAP purchasing and vendor master data scores suppliers on financial stability, delivery performance, and quality complaints from SAP data, but does not incorporate the FDA and ISO 13485 supplier audit history maintained in the QMS — meaning that a financially stable supplier with strong SAP delivery metrics but a history of ISO 13485 audit findings and an open CAPA with the regulatory body receives a high AI risk score that does not reflect the GMP compliance risk. Northstar Clinical's procurement team uses the AI risk scores as the primary input for supplier renegotiation and volume allocation decisions, directing additional volume to a high-AI-scored supplier who is simultaneously under a FDA warning letter for GMP violations — a procurement risk management failure enabled by an AI scoring model without regulatory compliance data integration.`,
    keywords: ['AI supplier risk', 'SAP S/4HANA', 'ISO 13485', 'supplier qualification', 'GMP inspection'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2004',
    name: `AI-Assisted ERP Role Mining Removes Access Controls Required for 21 CFR Part 11 Compliance`,
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `An AI role mining tool used to rationalise SAP role assignments and reduce access provisioning complexity identifies user-role combinations with low utilisation and recommends role removals to simplify the role architecture — but the tool does not distinguish between roles with low utilisation that are nonetheless required for Part 11 compliance (such as the electronic signature authority role required for batch disposition by users who perform disposition infrequently) and roles with low utilisation that represent genuine access excess. Role removals implemented based on AI role mining recommendations remove Part 11-required access authorities from users who need them for infrequent but GxP-critical tasks, creating access control gaps discovered when those users attempt to perform a GxP transaction they are no longer authorised for, interrupting GxP workflows and requiring emergency access restoration that bypasses the formal provisioning process.`,
    keywords: ['AI role mining', 'SAP access controls', '21 CFR Part 11', 'GAMP 5', 'segregation of duties'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2005',
    name: `SAP Predictive Quality AI Model Drift Creates Systematic False Accept Disposition Recommendation`,
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `A predictive quality AI model integrated with SAP QM that recommends batch disposition outcomes based on process parameter patterns was validated at go-live using training data from a process that has since been significantly modified — new raw material supplier, revised mixing parameters, and updated clean room classification — causing the model to generate systematic false-accept disposition recommendations for batches produced under the new process because the model's decision boundary is calibrated to the old process's quality signal distribution. The AI model drift is not detected because Northstar Clinical has no automated performance monitoring process for the SAP-integrated AI model and no predetermined change control plan specifying the process change conditions that require model revalidation, a governance gap that mirrors the SaMD algorithm drift without revalidation failure archetype applied to an ERP-integrated rather than device-embedded AI.`,
    keywords: ['AI model drift', 'SAP QM', 'predictive quality AI', 'GAMP 5', 'ISO 13485'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2006',
    name: `GenAI ERP Documentation Generator Produces SOPs With Non-Current SAP Screen References`,
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `A generative AI documentation assistant used to accelerate SAP procedure writing generates standard operating procedures for GxP SAP transactions by combining SAP transaction documentation with business process descriptions, but the AI tool's training data for SAP screen layouts and transaction paths is based on a prior SAP S/4HANA version that had different menu paths, screen field labels, and transaction codes from the current version, producing SOPs that reference non-existent transactions or screen elements that cause operators following the AI-generated SOP to be unable to complete the procedure as written. Under ISO 13485:2016 §4.2.4, controlled documents must be adequate before use and re-approved after updating, and an AI-generated SOP whose SAP references do not match the current system fails the adequacy requirement, creating a document control compliance gap for every GxP SOP generated by the AI tool without a version-specific SAP screenshot review.`,
    keywords: ['GenAI SOP generation', 'SAP S/4HANA', 'ISO 13485', 'document control', 'GxP validation'],
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2007',
    name: `AI ERP Order Management Automation Bypasses Restricted Party Screening for Regulated Devices`,
    officeCategory: 'back_office',
    failureRatePct: 52,
    description: `SAP's AI-driven order management automation processes routine device orders through expedited fulfillment pathways that bypass the restricted party list screening step implemented in the standard order-to-cash workflow — because the AI routing logic identifies these orders as routine based on customer order frequency and SKU patterns without evaluating whether the order requires restricted party screening under US EAR, OFAC, or EU dual-use regulations. Medical device components incorporating encryption technology or advanced imaging capabilities are subject to export control screening requirements regardless of order frequency, and AI order automation that bypasses screening for repeat customers creates an export compliance violation risk when a long-established distributor customer in a regulated market ships devices to a restricted end-user without Northstar Clinical's knowledge or approval.`,
    keywords: ['SAP AI order management', 'export control', 'OFAC', 'EAR', 'restricted party screening'],
    subTopic: 'ai-erp-enterprise',
  },
  {
    code: 'M2008',
    name: `SAP AI Predictive Maintenance for GxP Equipment Lacks GAMP 5 Validation Protocol`,
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `SAP's AI predictive maintenance capability for manufacturing equipment in GxP-regulated areas is deployed as an extension to the validated SAP PM module without a separate validation protocol confirming that the AI model's equipment health scoring and maintenance trigger logic is appropriately qualified as a GxP computer system component — because the AI predictive maintenance add-on is classified as an analytics tool rather than a computerised system affecting product quality. The SAP AI predictive maintenance module generates work orders that determine when GxP-critical manufacturing and laboratory equipment receives preventive maintenance, and the decision logic that governs these work order triggers has a direct impact on whether equipment is maintained in a calibrated and qualified state during production — making the AI model a GxP-relevant computer system component that requires validation evidence under GAMP 5, not an excluded analytics tool.`,
    keywords: ['SAP AI predictive maintenance', 'GAMP 5', 'GxP validation', 'SAP PM', 'equipment qualification'],
    demoRelevant: true,
    subTopic: 'ai-erp-enterprise',
  },

  // ── financial-controls-erp: SOX IT general controls, SoD, access management ─

  {
    code: 'M2009',
    name: `SAP User Access Review Cycle Is Annual but SOX IT Controls Require Quarterly Recertification`,
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `The SAP S/4HANA user access review cycle is conducted annually by the IT access management team, requiring business managers to recertify the appropriateness of each user's role assignments once per year — but the external auditor's assessment of IT general controls under SOX 404 identifies access recertification as a preventive control that should operate on a quarterly basis for financial reporting-relevant SAP roles to meet the control objective of preventing and detecting inappropriate access in a timely manner. The annual recertification cycle was implemented as a pragmatic balance between control rigour and business manager effort, but it creates a SOX 404 control gap for the 11-month window between certifications when terminated employees, role changes, and job function shifts may leave SAP access privileges in place that should have been removed, creating a quarterly access control deficiency finding in the annual SOX audit.`,
    keywords: ['SAP user access review', 'SOX 404', 'IT general controls', 'access management', 'segregation of duties'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2010',
    name: `SAP Basis Super-User Access Without Compensating Controls Creates SOX 404 Material Weakness`,
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `SAP Basis administrators maintain standing super-user access (SAP_ALL profile or equivalent) in the GxP and financial production clients to support emergency support activities, without compensating detective controls such as a privileged access management system with session recording, real-time monitoring, or mandatory ticket-based access justification — creating a SOX 404 material weakness because SAP Basis super-user access allows modification of financial records, audit log configuration, and access control settings without any systematic record of what was changed and why. The SOX 404 external auditor identifies standing super-user access without compensating controls as a material weakness in IT general controls because the combination of unrestricted access authority and absence of monitoring creates a control environment where financial data integrity cannot be independently verified.`,
    keywords: ['SAP super-user', 'SOX 404', 'IT general controls', 'privileged access management', 'SAP Basis'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2011',
    name: `SAP Segregation of Duties Conflicts in Finance Remain Unresolved After Three Audit Cycles`,
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `SAP role assignments in the financial accounting module contain documented segregation of duties conflicts — most significantly, the combination of vendor master maintenance access and payment run execution authority in a single user account — that have been identified in three consecutive annual SOX 404 audits and accepted as risk exceptions by management without systemic remediation, creating a pattern of repeated control deficiency that external auditors escalate from a significant deficiency to a material weakness determination in the third year. The SoD conflicts remain in place because the IT access management team's proposed remediation requires creating a net-new role structure that the implementation partner estimates at 800 person-hours, and the project has not been funded in three consecutive annual planning cycles, resulting in compensating controls — management review of payment run logs — that the auditor judges insufficient to reduce the risk to an acceptable level.`,
    keywords: ['segregation of duties', 'SAP finance', 'SOX 404', 'IT general controls', 'access management'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2012',
    name: `SAP Automated Payment Approval Threshold Misconfiguration Enables Unilateral High-Value Payments`,
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `SAP payment approval workflow configuration sets the automatic payment approval threshold — the payment value below which a single-signatory payment run is permitted without a second financial controller authorisation — at $1,000,000 USD rather than the $100,000 threshold documented in the treasury policy and the SOX 404 financial control narrative, allowing individual payment runs up to $999,999 to be executed by a single accounts payable manager without the dual-authorisation required by the payment controls framework. The threshold misconfiguration was introduced during a SAP upgrade when the payment workflow configuration was re-entered by the basis team and a decimal point error was not caught in post-upgrade testing because the payment workflow regression test only verified that the approval workflow triggered — not that it triggered at the correct threshold value documented in the controls framework.`,
    keywords: ['SAP payment approval', 'SOX 404', 'financial controls', 'treasury policy', 'IT general controls'],
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2013',
    name: `SAP Revenue Recognition Period-Close Process Lacks IT General Control Over Manual Override`,
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `The SAP Revenue Accounting and Reporting period-close process includes a manual override capability that allows the revenue manager to post revenue recognition entries outside the automated RAR waterfall for contract amendments, milestone billing adjustments, and performance obligation modifications — but the SAP configuration does not require a second-level financial controller review for manual RAR override entries, removing the dual-control SOX preventive control that applies to all other revenue recognition decisions. The manual RAR override capability was designed for exceptional contract situations but is used for 15–20% of revenue recognition entries each quarter because the SAP RAR configuration does not handle device-software bundle modifications automatically, creating a systematic process where a significant portion of reported revenue is determined by single-approved manual overrides without independent financial controller review.`,
    keywords: ['SAP RAR', 'SOX 404', 'revenue recognition', 'financial controls', 'IFRS 15'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2014',
    name: `SAP IT General Controls Over Patch Management Do Not Cover GxP-Validated System Change Tracking`,
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `The IT general controls framework for SAP change management, evaluated by external auditors under SOX 404, covers the standard IT change management process — change request, impact assessment, testing, and deployment approval — but the assessment does not extend to the GxP change management controls that govern validated system changes to GAMP 5-regulated SAP modules, creating a segregated control framework where SAP changes are simultaneously subject to SOX ITGC assessment and GAMP 5 validation requirements without a unified control narrative that satisfies both regulatory frameworks. External auditors assessing SAP ITGC and FDA inspectors assessing GAMP 5 change management both find gaps because neither framework's documentation covers the complete change management control set that applies to GxP ERP changes subject to both SOX ITGC and GxP regulatory requirements.`,
    keywords: ['SOX 404', 'IT general controls', 'GAMP 5', 'SAP change management', 'GxP validation'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2015',
    name: `SAP Financial Consolidation Access Control Allows Subsidiary to Modify Parent Elimination Entries`,
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `SAP Group Reporting access controls permit subsidiary finance controllers to create and modify intercompany elimination entries in the consolidated group reporting layer — a capability that should be restricted to the group finance team at the parent entity — because the role design for the group reporting implementation did not enforce a strict separation between subsidiary financial reporting access and consolidated reporting access. The access control gap allows subsidiary controllers to create manual elimination entries that affect the consolidated P&L and balance sheet without a group-level review, creating a financial reporting risk where subsidiary-initiated adjustments to consolidated financial statements are not subject to the independent group finance review that forms a key SOX 404 detective control over the consolidation process.`,
    keywords: ['SAP Group Reporting', 'SOX 404', 'access controls', 'financial consolidation', 'intercompany'],
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2016',
    name: `ERP Master Data Governance Lacks IT General Control Over Vendor Bank Account Modifications`,
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `SAP vendor master bank account data — the payment routing information that determines where Northstar Clinical's accounts payable payments are sent — can be modified by users in the accounts payable processing role without a mandatory second-approver control confirming the change before the modified bank account is used in a payment run, representing an accounts payable fraud risk that is a documented IT general control failure under SOX 404. Vendor master bank account changes are a primary vector for business email compromise fraud schemes, where fraudsters impersonating vendors request bank account changes that redirect legitimate vendor payments — and a SAP access control environment that permits single-user bank account modification without independent approval provides no automated control against this fraud vector.`,
    keywords: ['SAP vendor master', 'SOX 404', 'IT general controls', 'payment fraud', 'access controls'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2017',
    name: `SAP Inventory Valuation Method Change Requires SOX Disclosure but ERP Control Does Not Enforce Approval`,
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `The SAP material ledger configuration governing inventory valuation methodology — standard cost versus actual cost, and the costing variant applied to each plant — can be modified by SAP controlling team members with access to the material ledger configuration transaction, without a dual-authorisation control confirming that inventory valuation method changes have been reviewed and approved by the CFO and the external auditor as required for an accounting method change disclosed in the financial statement notes under ASC 250. A valuation method change implemented in SAP without the required accounting approval and SEC disclosure constitutes an undisclosed accounting policy change that creates a restatement risk if the external auditor identifies the change during the annual audit and determines that the change required disclosure in the prior period's financial statements.`,
    keywords: ['SAP material ledger', 'SOX 404', 'inventory valuation', 'ASC 250', 'financial controls'],
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2018',
    name: `SAP Cost Centre Structure Permits Marketing Costs to Be Booked to R&D — SOX 302 Misclassification Risk`,
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `The SAP cost centre structure and account assignment configuration does not enforce the segregation between R&D expense accounts and sales and marketing expense accounts that supports accurate financial reporting of medical device R&D spending — allowing marketing account managers to post trade show expenses, HCP presentation costs, and distributor training costs to R&D cost centres because the two cost centre hierarchies use the same general ledger accounts and there is no SAP validation rule blocking the cross-posting. The misclassification of sales and marketing costs as R&D expense inflates the reported R&D-to-revenue ratio disclosed in the annual report, a metric that investors use to assess Northstar Clinical's innovation investment rate — creating a SOX 302 CEO and CFO certification risk if the misclassification is material and the certifying officers are unaware of the systematic SAP posting pattern.`,
    keywords: ['SAP cost centres', 'SOX 302', 'R&D expense', 'financial reporting', 'IT general controls'],
    subTopic: 'financial-controls-erp',
  },
  {
    code: 'M2019',
    name: `SAP ERP Decommission Without Regulatory Record Extraction Plan — FDA Inspectable Records at Risk`,
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `The decommission of legacy SAP ECC systems following migration to SAP S/4HANA proceeds on a twelve-month sunset schedule without a regulatory record extraction plan that identifies all FDA-inspectable records stored exclusively in legacy SAP — batch records, quality inspection lots, complaint records, calibration data, and change management history — and confirms their migration, archival, or retrieval mechanism before the legacy system is taken offline. Legacy SAP ECC decommission without a regulatory record extraction plan is the medtech analogue of the TSA exit without data room discipline failure archetype: when the legacy system is taken offline, any FDA-inspectable record that was not extracted and verified becomes effectively inaccessible, and an FDA investigation requesting historical batch records or complaint history from the decommissioned period cannot be satisfied from the S/4HANA system if the legacy records were not migrated with full field-level fidelity.`,
    keywords: ['SAP decommission', 'FDA inspection readiness', 'GxP data integrity', 'record retention', 'FDA 21 CFR 820'],
    demoRelevant: true,
    subTopic: 'financial-controls-erp',
  },
];
