interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const HEALTHCARE_DOM10_CLINICAL_QUALITY_PART1_PATTERNS: PatternSeed[] = [

  // -- Joint Commission Readiness (H2120-H2131) --
  {
    code: 'H2120',
    name: 'Tracer Finding Pattern Recurrence In Joint Commission Readiness',
    description: `Meridian Health System lacks joint commission readiness controls around tracer finding pattern recurrence, creating a quality failure mode where decision evidence is not investment grade.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'tracer-finding-pattern-recurrence', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 34.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Tracer Finding Pattern Recurrence causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `29 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2121',
    name: 'Policy Version Control Gap In Joint Commission Readiness',
    description: `Meridian Health System misclassifies joint commission readiness controls around policy version control gap, creating a quality failure mode where audit findings repeat across operating units.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'policy-version-control-gap', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 41.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Policy Version Control Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `36 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2122',
    name: 'Mock Survey Evidence Staleness In Joint Commission Readiness',
    description: `Meridian Health System delays joint commission readiness controls around mock survey evidence staleness, creating a quality failure mode where frontline workarounds become normal practice.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'mock-survey-evidence-staleness', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 48.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Mock Survey Evidence Staleness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `44 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2123',
    name: 'Environment Of Care Rounding Drift In Joint Commission Readiness',
    description: `Meridian Health System understates joint commission readiness controls around environment of care rounding drift, creating a quality failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'environment-of-care-rounding-drift', 'quality', 'nhsn-guidance', 'ai-relevance'],
    failure_rate_pct: 55.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Environment Of Care Rounding Drift causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `51 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2124',
    name: 'Life Safety Documentation Gap In Joint Commission Readiness',
    description: `Meridian Health System overrides joint commission readiness controls around life safety documentation gap, creating a quality failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'life-safety-documentation-gap', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Life Safety Documentation Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `57 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2125',
    name: 'Credential File Exception In Joint Commission Readiness',
    description: `Meridian Health System fragments joint commission readiness controls around credential file exception, creating a quality failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'credential-file-exception', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 38.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Credential File Exception causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `33 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2126',
    name: 'Medication Management Standard Gap In Joint Commission Readiness',
    description: `Meridian Health System stales joint commission readiness controls around medication management standard gap, creating a quality failure mode where board reporting loses credibility.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'medication-management-standard-gap', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 45.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Medication Management Standard Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `41 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2127',
    name: 'Patient Rights Evidence Miss In Joint Commission Readiness',
    description: `Meridian Health System duplicates joint commission readiness controls around patient rights evidence miss, creating a quality failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'patient-rights-evidence-miss', 'quality', 'hipaa', 'ai-relevance'],
    failure_rate_pct: 52.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Patient Rights Evidence Miss causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `48 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2128',
    name: 'Emergency Management Exercise Weakness In Joint Commission Readiness',
    description: `Meridian Health System bypasses joint commission readiness controls around emergency management exercise weakness, creating a quality failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'emergency-management-exercise-weakness', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Emergency Management Exercise Weakness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `54 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2129',
    name: 'Survey Readiness Dashboard Lag In Joint Commission Readiness',
    description: `Meridian Health System weakens joint commission readiness controls around survey readiness dashboard lag, creating a quality failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'survey-readiness-dashboard-lag', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 35.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Survey Readiness Dashboard Lag causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `30 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2130',
    name: 'AI Survey Prep False Assurance In Joint Commission Readiness',
    description: `Meridian Health System misroutes joint commission readiness controls around ai survey prep false assurance, creating a quality failure mode where operating leaders lose confidence in the program.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'ai-survey-prep-false-assurance', 'quality', 'cms-conditions-of-participation', 'ai-relevance'],
    failure_rate_pct: 42.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `AI Survey Prep False Assurance causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `38 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2131',
    name: 'Corrective Action Sustainability Gap In Joint Commission Readiness',
    description: `Meridian Health System undergoverns joint commission readiness controls around corrective action sustainability gap, creating a quality failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['joint-commission-readiness', 'corrective-action-sustainability-gap', 'quality', 'joint-commission-standards', 'ai-relevance'],
    failure_rate_pct: 49.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'joint-commission-readiness',
    data: {
      failureMode: `Corrective Action Sustainability Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `45 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Cms Conditions Of Participation (H2132-H2143) --
  {
    code: 'H2132',
    name: 'Governing Body Evidence Gap In Cms Conditions Of Participation',
    description: `Meridian Health System lacks cms conditions of participation controls around governing body evidence gap, creating a quality failure mode where decision evidence is not investment grade.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'governing-body-evidence-gap', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Governing Body Evidence Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `51 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2133',
    name: 'Nursing Plan Of Care Drift In Cms Conditions Of Participation',
    description: `Meridian Health System misclassifies cms conditions of participation controls around nursing plan of care drift, creating a quality failure mode where audit findings repeat across operating units.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'nursing-plan-of-care-drift', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 63.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Nursing Plan Of Care Drift causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `58 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2134',
    name: 'Medical Staff Bylaws Version Risk In Cms Conditions Of Participation',
    description: `Meridian Health System delays cms conditions of participation controls around medical staff bylaws version risk, creating a quality failure mode where frontline workarounds become normal practice.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'medical-staff-bylaws-version-risk', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 39.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Medical Staff Bylaws Version Risk causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `35 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2135',
    name: 'QAPI Meeting Documentation Weakness In Cms Conditions Of Participation',
    description: `Meridian Health System understates cms conditions of participation controls around qapi meeting documentation weakness, creating a quality failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'qapi-meeting-documentation-weakness', 'quality', 'cms-conditions-of-participation', 'ai-relevance'],
    failure_rate_pct: 46.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `QAPI Meeting Documentation Weakness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `42 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2136',
    name: 'Informed Consent Form Defect In Cms Conditions Of Participation',
    description: `Meridian Health System overrides cms conditions of participation controls around informed consent form defect, creating a quality failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'informed-consent-form-defect', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Informed Consent Form Defect causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `48 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2137',
    name: 'Restraint Order Compliance Gap In Cms Conditions Of Participation',
    description: `Meridian Health System fragments cms conditions of participation controls around restraint order compliance gap, creating a quality failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'restraint-order-compliance-gap', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 60.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Restraint Order Compliance Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `55 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2138',
    name: 'Patient Grievance Timing Miss In Cms Conditions Of Participation',
    description: `Meridian Health System stales cms conditions of participation controls around patient grievance timing miss, creating a quality failure mode where board reporting loses credibility.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'patient-grievance-timing-miss', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 36.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Patient Grievance Timing Miss causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `32 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2139',
    name: 'Discharge Planning CoP Gap In Cms Conditions Of Participation',
    description: `Meridian Health System duplicates cms conditions of participation controls around discharge planning cop gap, creating a quality failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'discharge-planning-cop-gap', 'quality', 'usp-requirements', 'ai-relevance'],
    failure_rate_pct: 43.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Discharge Planning CoP Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `39 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2140',
    name: 'Infection Control Committee Evidence Gap In Cms Conditions Of Participation',
    description: `Meridian Health System bypasses cms conditions of participation controls around infection control committee evidence gap, creating a quality failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'infection-control-committee-evidence-gap', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Infection Control Committee Evidence Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `45 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2141',
    name: 'Contracted Service Oversight Gap In Cms Conditions Of Participation',
    description: `Meridian Health System weakens cms conditions of participation controls around contracted service oversight gap, creating a quality failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'contracted-service-oversight-gap', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 57.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Contracted Service Oversight Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `52 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2142',
    name: 'AI CoP Gap Analysis Miss In Cms Conditions Of Participation',
    description: `Meridian Health System misroutes cms conditions of participation controls around ai cop gap analysis miss, creating a quality failure mode where operating leaders lose confidence in the program.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'ai-cop-gap-analysis-miss', 'quality', 'hipaa', 'ai-relevance'],
    failure_rate_pct: 64.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `AI CoP Gap Analysis Miss causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `60 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2143',
    name: 'Survey Response Evidence Lag In Cms Conditions Of Participation',
    description: `Meridian Health System undergoverns cms conditions of participation controls around survey response evidence lag, creating a quality failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['cms-conditions-of-participation', 'survey-response-evidence-lag', 'quality', 'nhsn-guidance', 'ai-relevance'],
    failure_rate_pct: 40.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'cms-conditions-of-participation',
    data: {
      failureMode: `Survey Response Evidence Lag causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `36 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Peer Review Program (H2144-H2155) --
  {
    code: 'H2144',
    name: 'Case Selection Bias In Peer Review Program',
    description: `Meridian Health System lacks peer review program controls around case selection bias, creating a quality failure mode where decision evidence is not investment grade.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'case-selection-bias', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Case Selection Bias causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `42 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2145',
    name: 'Peer Review Timeliness Drift In Peer Review Program',
    description: `Meridian Health System misclassifies peer review program controls around peer review timeliness drift, creating a quality failure mode where audit findings repeat across operating units.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'peer-review-timeliness-drift', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 54.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Peer Review Timeliness Drift causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `49 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2146',
    name: 'Physician Conflict Of Interest Gap In Peer Review Program',
    description: `Meridian Health System delays peer review program controls around physician conflict of interest gap, creating a quality failure mode where frontline workarounds become normal practice.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'physician-conflict-of-interest-gap', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 61.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Physician Conflict Of Interest Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `57 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2147',
    name: 'OPPE FPPE Evidence Break In Peer Review Program',
    description: `Meridian Health System understates peer review program controls around oppe fppe evidence break, creating a quality failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'oppe-fppe-evidence-break', 'quality', 'hipaa', 'ai-relevance'],
    failure_rate_pct: 37.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `OPPE FPPE Evidence Break causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `33 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2148',
    name: 'Action Plan Follow Through Gap In Peer Review Program',
    description: `Meridian Health System overrides peer review program controls around action plan follow through gap, creating a quality failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'action-plan-follow-through-gap', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Action Plan Follow Through Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `39 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2149',
    name: 'Protected Peer Review Documentation Risk In Peer Review Program',
    description: `Meridian Health System fragments peer review program controls around protected peer review documentation risk, creating a quality failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'protected-peer-review-documentation-risk', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 51.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Protected Peer Review Documentation Risk causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `46 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2150',
    name: 'Specialty Reviewer Capacity Shortfall In Peer Review Program',
    description: `Meridian Health System stales peer review program controls around specialty reviewer capacity shortfall, creating a quality failure mode where board reporting loses credibility.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'specialty-reviewer-capacity-shortfall', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 58.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Specialty Reviewer Capacity Shortfall causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `54 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2151',
    name: 'Outcome Feedback Loop Gap In Peer Review Program',
    description: `Meridian Health System duplicates peer review program controls around outcome feedback loop gap, creating a quality failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'outcome-feedback-loop-gap', 'quality', 'joint-commission-standards', 'ai-relevance'],
    failure_rate_pct: 34.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Outcome Feedback Loop Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `30 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2152',
    name: 'Low Volume Provider Signal Weakness In Peer Review Program',
    description: `Meridian Health System bypasses peer review program controls around low volume provider signal weakness, creating a quality failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'low-volume-provider-signal-weakness', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 41.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Low Volume Provider Signal Weakness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `36 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2153',
    name: 'Adverse Event Linkage Gap In Peer Review Program',
    description: `Meridian Health System weakens peer review program controls around adverse event linkage gap, creating a quality failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'adverse-event-linkage-gap', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 48.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Adverse Event Linkage Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `43 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2154',
    name: 'AI Peer Review Triage Bias In Peer Review Program',
    description: `Meridian Health System misroutes peer review program controls around ai peer review triage bias, creating a quality failure mode where operating leaders lose confidence in the program.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'ai-peer-review-triage-bias', 'quality', 'usp-requirements', 'ai-relevance'],
    failure_rate_pct: 55.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `AI Peer Review Triage Bias causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `51 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2155',
    name: 'Credentialing Committee Handoff Gap In Peer Review Program',
    description: `Meridian Health System undergoverns peer review program controls around credentialing committee handoff gap, creating a quality failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['peer-review-program', 'credentialing-committee-handoff-gap', 'quality', 'cms-conditions-of-participation', 'ai-relevance'],
    failure_rate_pct: 62.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'peer-review-program',
    data: {
      failureMode: `Credentialing Committee Handoff Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `58 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Mortality Morbidity Review (H2156-H2167) --
  {
    code: 'H2156',
    name: 'Mortality Case Capture Gap In Mortality Morbidity Review',
    description: `Meridian Health System lacks mortality morbidity review controls around mortality case capture gap, creating a quality failure mode where decision evidence is not investment grade.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'mortality-case-capture-gap', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 38.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Mortality Case Capture Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `33 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2157',
    name: 'Preventability Classification Drift In Mortality Morbidity Review',
    description: `Meridian Health System misclassifies mortality morbidity review controls around preventability classification drift, creating a quality failure mode where audit findings repeat across operating units.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'preventability-classification-drift', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 45.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Preventability Classification Drift causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `40 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2158',
    name: 'M and M Action Owner Ambiguity In Mortality Morbidity Review',
    description: `Meridian Health System delays mortality morbidity review controls around m and m action owner ambiguity, creating a quality failure mode where frontline workarounds become normal practice.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'm-and-m-action-owner-ambiguity', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 52.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `M and M Action Owner Ambiguity causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `48 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2159',
    name: 'Sepsis Death Review Delay In Mortality Morbidity Review',
    description: `Meridian Health System understates mortality morbidity review controls around sepsis death review delay, creating a quality failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'sepsis-death-review-delay', 'quality', 'usp-requirements', 'ai-relevance'],
    failure_rate_pct: 59.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Sepsis Death Review Delay causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `55 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2160',
    name: 'Surgical Complication Coding Mismatch In Mortality Morbidity Review',
    description: `Meridian Health System overrides mortality morbidity review controls around surgical complication coding mismatch, creating a quality failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'surgical-complication-coding-mismatch', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 35.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Surgical Complication Coding Mismatch causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `30 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2161',
    name: 'Equity Lens Missing From Review In Mortality Morbidity Review',
    description: `Meridian Health System fragments mortality morbidity review controls around equity lens missing from review, creating a quality failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'equity-lens-missing-from-review', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 42.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Equity Lens Missing From Review causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `37 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2162',
    name: 'Autopsy Result Feedback Lag In Mortality Morbidity Review',
    description: `Meridian Health System stales mortality morbidity review controls around autopsy result feedback lag, creating a quality failure mode where board reporting loses credibility.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'autopsy-result-feedback-lag', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 49.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Autopsy Result Feedback Lag causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `45 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2163',
    name: 'Committee Attendance Evidence Gap In Mortality Morbidity Review',
    description: `Meridian Health System duplicates mortality morbidity review controls around committee attendance evidence gap, creating a quality failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'committee-attendance-evidence-gap', 'quality', 'nhsn-guidance', 'ai-relevance'],
    failure_rate_pct: 56.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Committee Attendance Evidence Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `52 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2164',
    name: 'Learning Dissemination Weakness In Mortality Morbidity Review',
    description: `Meridian Health System bypasses mortality morbidity review controls around learning dissemination weakness, creating a quality failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'learning-dissemination-weakness', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Learning Dissemination Weakness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `58 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2165',
    name: 'Repeat Contributing Factor Blind Spot In Mortality Morbidity Review',
    description: `Meridian Health System weakens mortality morbidity review controls around repeat contributing factor blind spot, creating a quality failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'repeat-contributing-factor-blind-spot', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 39.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Repeat Contributing Factor Blind Spot causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `34 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2166',
    name: 'AI Mortality Summary Omission Risk In Mortality Morbidity Review',
    description: `Meridian Health System misroutes mortality morbidity review controls around ai mortality summary omission risk, creating a quality failure mode where operating leaders lose confidence in the program.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'ai-mortality-summary-omission-risk', 'quality', 'joint-commission-standards', 'ai-relevance'],
    failure_rate_pct: 46.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `AI Mortality Summary Omission Risk causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `42 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2167',
    name: 'Outcome Measure Linkage Gap In Mortality Morbidity Review',
    description: `Meridian Health System undergoverns mortality morbidity review controls around outcome measure linkage gap, creating a quality failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['mortality-morbidity-review', 'outcome-measure-linkage-gap', 'quality', 'hipaa', 'ai-relevance'],
    failure_rate_pct: 53.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mortality-morbidity-review',
    data: {
      failureMode: `Outcome Measure Linkage Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `49 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },

  // -- Accreditation Gap Remediation (H2168-H2179) --
  {
    code: 'H2168',
    name: 'CAPA Due Date Slippage In Accreditation Gap Remediation',
    description: `Meridian Health System lacks accreditation gap remediation controls around capa due date slippage, creating a quality failure mode where decision evidence is not investment grade.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'capa-due-date-slippage', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `CAPA Due Date Slippage causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `monthly control testing exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should establish accountable owner and evidence gate before expanding the workflow or funding the next phase`,
      industryBenchmark: `55 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2169',
    name: 'Evidence Binder Fragmentation In Accreditation Gap Remediation',
    description: `Meridian Health System misclassifies accreditation gap remediation controls around evidence binder fragmentation, creating a quality failure mode where audit findings repeat across operating units.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'evidence-binder-fragmentation', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 36.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Evidence Binder Fragmentation causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `internal audit sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should refresh policy mapping and automate exception aging before expanding the workflow or funding the next phase`,
      industryBenchmark: `31 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2170',
    name: 'Policy Remediation Without Training In Accreditation Gap Remediation',
    description: `Meridian Health System delays accreditation gap remediation controls around policy remediation without training, creating a quality failure mode where frontline workarounds become normal practice.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'policy-remediation-without-training', 'quality', 'cms-conditions-of-participation', 'control-risk'],
    failure_rate_pct: 43.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Policy Remediation Without Training causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `dashboard variance review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should rebuild the source-data lineage and sampling plan before expanding the workflow or funding the next phase`,
      industryBenchmark: `39 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2171',
    name: 'Owner Accountability Ambiguity In Accreditation Gap Remediation',
    description: `Meridian Health System understates accreditation gap remediation controls around owner accountability ambiguity, creating a quality failure mode where value leakage remains hidden until quarter close.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'owner-accountability-ambiguity', 'quality', 'joint-commission-standards', 'ai-relevance'],
    failure_rate_pct: 50.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Owner Accountability Ambiguity causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `policy-to-system trace review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add workflow controls before scaling automation before expanding the workflow or funding the next phase`,
      industryBenchmark: `46 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2172',
    name: 'Repeat Finding Root Cause Weakness In Accreditation Gap Remediation',
    description: `Meridian Health System overrides accreditation gap remediation controls around repeat finding root cause weakness, creating a quality failure mode where regulatory response timelines compress dangerously.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'repeat-finding-root-cause-weakness', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Repeat Finding Root Cause Weakness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `case file sampling exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a steward-reviewed remediation playbook before expanding the workflow or funding the next phase`,
      industryBenchmark: `52 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2173',
    name: 'Regulatory Calendar Overlap Risk In Accreditation Gap Remediation',
    description: `Meridian Health System fragments accreditation gap remediation controls around regulatory calendar overlap risk, creating a quality failure mode where manual reconciliation becomes the control of last resort.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'regulatory-calendar-overlap-risk', 'quality', 'nhsn-guidance', 'control-risk'],
    failure_rate_pct: 64.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Regulatory Calendar Overlap Risk causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `workflow telemetry analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should renegotiate evidence obligations and reporting cadence before expanding the workflow or funding the next phase`,
      industryBenchmark: `59 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2174',
    name: 'Document Control Approval Lag In Accreditation Gap Remediation',
    description: `Meridian Health System stales accreditation gap remediation controls around document control approval lag, creating a quality failure mode where board reporting loses credibility.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'document-control-approval-lag', 'quality', 'usp-requirements', 'control-risk'],
    failure_rate_pct: 40.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Document Control Approval Lag causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `vendor evidence review exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should define human approval boundaries for AI assisted decisions before expanding the workflow or funding the next phase`,
      industryBenchmark: `36 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2175',
    name: 'Unit Level Adoption Gap In Accreditation Gap Remediation',
    description: `Meridian Health System duplicates accreditation gap remediation controls around unit level adoption gap, creating a quality failure mode where exception queues mask the underlying control weakness.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'unit-level-adoption-gap', 'quality', 'cms-conditions-of-participation', 'ai-relevance'],
    failure_rate_pct: 47.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Unit Level Adoption Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `CMS Conditions of Participation is the primary governance hook for this pattern`,
      detectionMethod: `regulatory readiness walk-through exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should run a tabletop exercise and close the action log before expanding the workflow or funding the next phase`,
      industryBenchmark: `43 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2176',
    name: 'Internal Audit Sampling Weakness In Accreditation Gap Remediation',
    description: `Meridian Health System bypasses accreditation gap remediation controls around internal audit sampling weakness, creating a quality failure mode where vendor accountability becomes hard to prove.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'internal-audit-sampling-weakness', 'quality', 'joint-commission-standards', 'control-risk'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Internal Audit Sampling Weakness causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `Joint Commission standards is the primary governance hook for this pattern`,
      detectionMethod: `exception aging analysis exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should create a KPI baseline and variance threshold before expanding the workflow or funding the next phase`,
      industryBenchmark: `49 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2177',
    name: 'Executive Escalation Threshold Drift In Accreditation Gap Remediation',
    description: `Meridian Health System weakens accreditation gap remediation controls around executive escalation threshold drift, creating a quality failure mode where AI assisted recommendations amplify stale assumptions.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'executive-escalation-threshold-drift', 'quality', 'hipaa', 'control-risk'],
    failure_rate_pct: 61.3,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Executive Escalation Threshold Drift causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `HIPAA is the primary governance hook for this pattern`,
      detectionMethod: `management action validation exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should split high-risk exceptions into a board-visible queue before expanding the workflow or funding the next phase`,
      industryBenchmark: `56 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: false,
      aiRiskDescription: `AI is not the primary trigger but can improve monitoring once the control baseline is repaired`,
    },
  },
  {
    code: 'H2178',
    name: 'AI Remediation Plan Generic Output In Accreditation Gap Remediation',
    description: `Meridian Health System misroutes accreditation gap remediation controls around ai remediation plan generic output, creating a quality failure mode where operating leaders lose confidence in the program.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'ai-remediation-plan-generic-output', 'quality', 'nhsn-guidance', 'ai-relevance'],
    failure_rate_pct: 37.6,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `AI Remediation Plan Generic Output causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `NHSN guidance is the primary governance hook for this pattern`,
      detectionMethod: `AI output spot check exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should add second-line review before production release before expanding the workflow or funding the next phase`,
      industryBenchmark: `33 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  },
  {
    code: 'H2179',
    name: 'Sustainability Check Evidence Gap In Accreditation Gap Remediation',
    description: `Meridian Health System undergoverns accreditation gap remediation controls around sustainability check evidence gap, creating a quality failure mode where remediation cost doubles before ownership is clarified.`,
    vertical: 'healthcare_provider',
    office_category: 'Quality',
    keywords: ['accreditation-gap-remediation', 'sustainability-check-evidence-gap', 'quality', 'usp-requirements', 'ai-relevance'],
    failure_rate_pct: 44.9,
    is_active: true,
    demoRelevant: true,
    subTopic: 'accreditation-gap-remediation',
    data: {
      failureMode: `Sustainability Check Evidence Gap causes quality decisions to proceed without complete evidence and accountable ownership`,
      regulatoryHook: `USP requirements is the primary governance hook for this pattern`,
      detectionMethod: `root cause replay exposes the gap before it becomes a material operating issue`,
      remediationPath: `Teams should link remediation to value and risk acceptance gates before expanding the workflow or funding the next phase`,
      industryBenchmark: `40 percent of comparable programs show this weakness before formal remediation`,
      aiInsertionRisk: true,
      aiRiskDescription: `AI can accelerate this failure when recommendations inherit stale controls or weak evidence gates`,
    },
  }
];
