/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 76: Academic Medical Center Research AI
// Part 4: H19150-H19199
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM76_PART4_PATTERNS = [
  {
    code: 'H19150',
    name: 'Research AI Summarization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for summarization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'HIPAA BAA', 'Series B burn rate', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19151',
    name: 'IRB Risk Scoring Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for risk scoring but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'minimum necessary policy', 'implementation partner capacity', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19152',
    name: 'Clinical Trial Matching Worklist Prioritization Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for worklist prioritization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'TJC survey evidence', 'referenceable health-system customer', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19153',
    name: 'OMOP Appeal Generation Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for appeal generation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'CMS CoP', 'clinical advisory board', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19154',
    name: 'Academic Medical Center Order Recommendation Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for order recommendation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'NCQA HEDIS audit', 'FDA submission posture', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19155',
    name: 'Research AI Benefit Verification Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for benefit verification but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'FDA SaMD guidance', 'KLAS commentary', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19156',
    name: 'IRB Eligibility Prediction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for eligibility prediction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'NIST AI RMF', 'Epic App Orchard integration', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19157',
    name: 'Clinical Trial Matching Care Gap Closure Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for care gap closure but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'ONC HTI-1', 'Microsoft Cloud for Healthcare', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19158',
    name: 'OMOP Cohort Matching Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for cohort matching but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'TEFCA participation', 'AWS HealthLake', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19159',
    name: 'Academic Medical Center Contract Analysis Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for contract analysis but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'FHIR R4 mapping', 'Azure Health Data Services', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19160',
    name: 'Research AI Agentic Orchestration Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for agentic orchestration but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'HL7 v2 ADT reconciliation', 'Snowflake Healthcare', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19161',
    name: 'IRB Coding Suggestion Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for coding suggestion but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'Epic change control', 'Databricks Lakehouse', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19162',
    name: 'Clinical Trial Matching Documentation Review Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for documentation review but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'model registry', 'ServiceNow workflow', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19163',
    name: 'OMOP Vendor Comparison Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for vendor comparison but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'deployment-site validation', 'Salesforce Health Cloud', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19164',
    name: 'Academic Medical Center Capacity Forecasting Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for capacity forecasting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'MLOps monitoring', 'startup maturity evidence', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19165',
    name: 'Research AI Staffing Optimization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for staffing optimization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'clinical safety review', 'SOC 2 Type II', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19166',
    name: 'IRB Quality Abstraction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for quality abstraction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'procurement RFP scoring', 'HITRUST roadmap', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19167',
    name: 'Clinical Trial Matching Patient Outreach Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for patient outreach but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'BAFO contract clause', 'Series B burn rate', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19168',
    name: 'OMOP Triage Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for triage but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'HIPAA BAA', 'implementation partner capacity', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19169',
    name: 'Academic Medical Center Drafting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for drafting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'minimum necessary policy', 'referenceable health-system customer', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19170',
    name: 'Research AI Summarization Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for summarization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'TJC survey evidence', 'clinical advisory board', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19171',
    name: 'IRB Risk Scoring Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for risk scoring but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'CMS CoP', 'FDA submission posture', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19172',
    name: 'Clinical Trial Matching Worklist Prioritization Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for worklist prioritization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'NCQA HEDIS audit', 'KLAS commentary', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19173',
    name: 'OMOP Appeal Generation Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for appeal generation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'FDA SaMD guidance', 'Epic App Orchard integration', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19174',
    name: 'Academic Medical Center Order Recommendation Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for order recommendation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'NIST AI RMF', 'Microsoft Cloud for Healthcare', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19175',
    name: 'Research AI Benefit Verification Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for benefit verification but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'ONC HTI-1', 'AWS HealthLake', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19176',
    name: 'IRB Eligibility Prediction Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for eligibility prediction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'TEFCA participation', 'Azure Health Data Services', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19177',
    name: 'Clinical Trial Matching Care Gap Closure Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for care gap closure but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'FHIR R4 mapping', 'Snowflake Healthcare', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19178',
    name: 'OMOP Cohort Matching Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for cohort matching but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'HL7 v2 ADT reconciliation', 'Databricks Lakehouse', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19179',
    name: 'Academic Medical Center Contract Analysis Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for contract analysis but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'Epic change control', 'ServiceNow workflow', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19180',
    name: 'Research AI Agentic Orchestration Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for agentic orchestration but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'model registry', 'Salesforce Health Cloud', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19181',
    name: 'IRB Coding Suggestion Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for coding suggestion but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'deployment-site validation', 'startup maturity evidence', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19182',
    name: 'Clinical Trial Matching Documentation Review Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for documentation review but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'MLOps monitoring', 'SOC 2 Type II', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19183',
    name: 'OMOP Vendor Comparison Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for vendor comparison but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'clinical safety review', 'HITRUST roadmap', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19184',
    name: 'Academic Medical Center Capacity Forecasting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for capacity forecasting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'procurement RFP scoring', 'Series B burn rate', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19185',
    name: 'Research AI Staffing Optimization Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for staffing optimization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'BAFO contract clause', 'implementation partner capacity', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19186',
    name: 'IRB Quality Abstraction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for quality abstraction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'HIPAA BAA', 'referenceable health-system customer', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19187',
    name: 'Clinical Trial Matching Patient Outreach Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for patient outreach but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'minimum necessary policy', 'clinical advisory board', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19188',
    name: 'OMOP Triage Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for triage but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'TJC survey evidence', 'FDA submission posture', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19189',
    name: 'Academic Medical Center Drafting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for drafting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'CMS CoP', 'KLAS commentary', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19190',
    name: 'Research AI Summarization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for summarization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'NCQA HEDIS audit', 'Epic App Orchard integration', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19191',
    name: 'IRB Risk Scoring Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for risk scoring but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'FDA SaMD guidance', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19192',
    name: 'Clinical Trial Matching Worklist Prioritization Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for worklist prioritization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'NIST AI RMF', 'AWS HealthLake', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19193',
    name: 'OMOP Appeal Generation Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for appeal generation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'ONC HTI-1', 'Azure Health Data Services', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19194',
    name: 'Academic Medical Center Order Recommendation Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for order recommendation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'TEFCA participation', 'Snowflake Healthcare', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19195',
    name: 'Research AI Benefit Verification Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Academic Medical Center Research AI initiatives fail when research AI is used for benefit verification but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when clinical trial matching is not proven in production.`,
    keywords: ['research AI', 'clinical trial matching', 'FHIR R4 mapping', 'Databricks Lakehouse', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19196',
    name: 'IRB Eligibility Prediction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Academic Medical Center Research AI initiatives fail when IRB is used for eligibility prediction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when OMOP is not proven in production.`,
    keywords: ['IRB', 'OMOP', 'HL7 v2 ADT reconciliation', 'ServiceNow workflow', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19197',
    name: 'Clinical Trial Matching Care Gap Closure Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Academic Medical Center Research AI initiatives fail when clinical trial matching is used for care gap closure but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when academic medical center is not proven in production.`,
    keywords: ['clinical trial matching', 'academic medical center', 'Epic change control', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19198',
    name: 'OMOP Cohort Matching Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Academic Medical Center Research AI initiatives fail when OMOP is used for cohort matching but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when research AI is not proven in production.`,
    keywords: ['OMOP', 'research AI', 'model registry', 'startup maturity evidence', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Academic Medical Center Research AI',
  },
  {
    code: 'H19199',
    name: 'Academic Medical Center Contract Analysis Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Academic Medical Center Research AI initiatives fail when academic medical center is used for contract analysis but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when IRB is not proven in production.`,
    keywords: ['academic medical center', 'IRB', 'deployment-site validation', 'SOC 2 Type II', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Academic Medical Center Research AI',
  }
];
