interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const MEDTECH_DOM06_PMS_PART6_PATTERNS: PatternSeed[] = [

  // ── Safety Signal Quantification (M1150–M1161) ──────────────────────────

  {
    code: 'M1150',
    name: 'Signal-to-Noise Ratio Gap in Complaint Database Obscures True Safety Signals',
    description: 'The complaint database contains a high volume of low-severity service calls that dilute the signal-to-noise ratio, causing statistically significant safety signals to be missed during routine PMS review.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['signal-to-noise', 'complaint-database', 'pms', 'signal-detection', 'mdr'],
    failure_rate_pct: 52,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'High noise-to-signal ratio in the complaint log masks true safety events during PMS triage.',
      regulatoryHook: 'MDR Article 83; IVDR Article 78; ISO 13485 §8.2.1',
      detectionMethod: 'Stratified complaint re-classification audit separating service events from safety-relevant reports.',
      remediationPath: 'Implement complaint severity triage taxonomy and re-score historical database before next PSUR cycle.',
      estimatedCost: '$80K–$200K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '48% of medtech firms lack a formal signal-to-noise stratification methodology in PMS.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-assisted triage mis-classifies safety events as service noise without human oversight.',
    },
  },
  {
    code: 'M1151',
    name: 'Absence of Statistical Signal Detection Methodology in PMS Plan',
    description: `The manufacturer's PMS plan describes a narrative review process but does not specify any statistical signal detection methodology, leaving signal identification dependent on individual reviewer judgment.`,
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['signal-detection-methodology', 'pms-plan', 'statistical-methods', 'mdr', 'eudamed'],
    failure_rate_pct: 61,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'PMS plan relies on narrative review rather than a defined statistical signal detection approach.',
      regulatoryHook: 'MDR Article 84; MEDDEV 2.12/1 Rev 8; IMDRF N56',
      detectionMethod: 'PMS plan document review against IMDRF N56 statistical methodology requirements.',
      remediationPath: 'Define and document a proportional reporting ratio or Bayesian methodology in the PMS plan.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '55% of class IIb device PMS plans omit any reference to a statistical detection methodology.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1152',
    name: 'CUSUM Algorithm Implementation Error Producing False Negatives',
    description: 'The cumulative sum algorithm deployed for adverse event trend detection has an incorrectly configured threshold parameter, causing it to generate false negatives and delay detection of emerging signals.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['cusum', 'algorithm', 'false-negative', 'trend-detection', 'pms'],
    failure_rate_pct: 57,
    is_active: true,
    demoRelevant: false,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'CUSUM threshold misconfiguration suppresses true signals and produces false-negative trend reports.',
      regulatoryHook: 'MDR Article 83; ISO 13485 §8.2.1; IMDRF N56',
      detectionMethod: 'Retrospective algorithm validation against known signal event set to expose threshold errors.',
      remediationPath: 'Recalibrate CUSUM threshold using validated reference dataset and reprocess historical data.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '34% of automated signal detection implementations lack documented algorithm validation.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1153',
    name: 'Safety Signal Peer Review Not Conducted Before Regulatory Submission',
    description: 'Identified safety signals are escalated directly to the regulatory affairs team for submission drafting without a documented peer review step, increasing the risk of misclassified signals reaching the NCA.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['peer-review', 'safety-signal', 'regulatory-submission', 'pms', 'mdr'],
    failure_rate_pct: 49,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Absence of signal peer review allows misclassified or spurious signals to enter regulatory reports.',
      regulatoryHook: 'MDR Article 85; MDR Annex XIV Part B; ISO 13485 §5.6',
      detectionMethod: 'SOP audit comparing signal escalation workflow against MDR Annex XIV peer review expectations.',
      remediationPath: 'Insert a mandatory cross-functional peer review gate into the signal escalation SOP.',
      estimatedCost: '$15K–$45K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of SME manufacturers have no documented signal peer review step before NCA submission.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1154',
    name: 'Quantified Benefit-Risk Assessment Not Updated After New Safety Signal',
    description: 'The clinical evaluation contains a benefit-risk determination that has not been updated following identification of a new safety signal, leaving the regulatory dossier inconsistent with current PMS findings.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['benefit-risk', 'clinical-evaluation', 'safety-signal', 'mdr', 'annex-xiv'],
    failure_rate_pct: 66,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Benefit-risk section in CER is stale relative to PMS signal findings, creating dossier inconsistency.',
      regulatoryHook: 'MDR Annex XIV Part A §1(c); MDCG 2020-13; MDR Article 10(3)',
      detectionMethod: 'Cross-reference CER benefit-risk date against PMS signal log timestamps.',
      remediationPath: 'Establish a triggered CER update workflow that fires automatically on confirmed signal classification.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '60% of class III device CERs are not updated within 90 days of a confirmed new safety signal.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1155',
    name: 'Complaint Volume Spike Not Triggering Automatic Signal Quantification Review',
    description: 'A 35% month-over-month complaint volume increase for a specific failure mode was not automatically escalated for signal quantification because the PMS plan threshold was set at 50%, creating a detection gap.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['complaint-volume', 'signal-quantification', 'threshold', 'pms', 'mdr'],
    failure_rate_pct: 54,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'PMS threshold set too high causes genuine volume spikes to pass unreviewed.',
      regulatoryHook: 'MDR Article 83; IMDRF N56; ISO 13485 §8.2.1',
      detectionMethod: 'Back-test threshold against 24-month complaint history to identify missed escalation events.',
      remediationPath: 'Lower threshold to 20% and add a trend-based secondary trigger for three consecutive monthly increases.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '2–4 months',
      industryBenchmark: 'Industry median complaint-spike threshold is 25%; 38% of firms are set above 40%.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1156',
    name: 'Lack of Denominator Data Prevents Incidence Rate Calculation for PMS Signals',
    description: 'The PMS team cannot compute device-specific adverse event incidence rates because unit-in-use denominator data is not collected or maintained, preventing meaningful signal quantification.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['denominator-data', 'incidence-rate', 'signal-quantification', 'pms', 'psur'],
    failure_rate_pct: 70,
    is_active: true,
    demoRelevant: false,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Missing units-in-use denominator data makes adverse event rate calculation impossible for PSUR.',
      regulatoryHook: 'MDR Annex XIV Part B §3; MDCG 2022-21; ISO 13485 §7.1',
      detectionMethod: 'PSUR audit verifying presence of units-sold and units-in-use figures used in rate calculations.',
      remediationPath: 'Integrate sales and distribution data into PMS database to produce device-population denominators.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '45% of PSUR submissions reviewed by NCAs lack device-specific incidence rate calculations.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1157',
    name: 'Multi-Source Signal Aggregation Failure Across Global Complaint Channels',
    description: 'Safety signals generated from EU, US MDR, and Japan PMDA complaint streams are reviewed in separate siloed processes, preventing cross-jurisdictional aggregation that could meet global signal thresholds.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['signal-aggregation', 'global-pms', 'cross-jurisdictional', 'mdr', 'fda-mdr'],
    failure_rate_pct: 63,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Siloed regional complaint reviews prevent global signal aggregation that would cross detection thresholds.',
      regulatoryHook: 'MDR Article 83; IMDRF N63; 21 CFR 803',
      detectionMethod: 'Audit global complaint log for duplicate device-failure-mode events reviewed only in regional silos.',
      remediationPath: 'Implement a unified global PMS database with cross-jurisdictional signal aggregation workflow.',
      estimatedCost: '$150K–$400K',
      timeToRemediate: '9–18 months',
      industryBenchmark: '52% of multinational medtech firms lack a unified cross-jurisdictional PMS signal database.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI translation and triage tools may introduce language-based classification disparities across regions.',
    },
  },
  {
    code: 'M1158',
    name: 'Software Algorithm Change Not Reassessed for Signal Detection Impact',
    description: `A software update modified the device's operational algorithm but the PMS signal detection methodology was not reassessed to determine whether new failure modes required updated signal thresholds.`,
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['software-change', 'signal-detection', 'algorithm-update', 'pms', 'mdr-article-83'],
    failure_rate_pct: 58,
    is_active: true,
    demoRelevant: false,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Post-software-update PMS plan was not revised to capture new failure modes introduced by the algorithm change.',
      regulatoryHook: 'MDR Article 83; MDCG 2019-11; IEC 62304 §9',
      detectionMethod: 'Change control record review comparing PMS plan revision dates against software version release dates.',
      remediationPath: 'Add PMS plan review as a mandatory step in the software change control procedure.',
      estimatedCost: '$25K–$75K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '39% of software device manufacturers do not trigger a PMS plan review upon algorithm updates.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-driven algorithm updates may introduce failure modes that existing signal thresholds were not designed to detect.',
    },
  },
  {
    code: 'M1159',
    name: 'Complaint Coding Inconsistency Distorting Signal Detection Outputs',
    description: 'Inconsistent application of the internal complaint coding taxonomy across different complaint handlers produces artificially fragmented failure-mode counts that fall below signal thresholds individually.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['complaint-coding', 'taxonomy', 'signal-detection', 'pms', 'iso-13485'],
    failure_rate_pct: 62,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Inconsistent complaint coding fragments related events across multiple codes, suppressing signal detection.',
      regulatoryHook: 'ISO 13485 §8.2.2; MDR Article 83; IMDRF N36 GMDN',
      detectionMethod: 'Inter-rater reliability study on a random sample of 200 complaints coded by different handlers.',
      remediationPath: 'Conduct complaint coding calibration training and implement mandatory dual-code review for borderline events.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: 'Inter-rater agreement below 80% observed in 43% of complaint department audits.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1160',
    name: 'Absence of Proactive Signal Hunting Beyond Incoming Complaint Streams',
    description: 'The PMS process is entirely reactive, relying solely on manufacturer-received complaints, without proactive literature surveillance, registry monitoring, or social media signal hunting as required by MDR.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['proactive-pms', 'literature-surveillance', 'signal-hunting', 'mdr', 'annex-xiv'],
    failure_rate_pct: 67,
    is_active: true,
    demoRelevant: true,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'PMS relies exclusively on reactive complaint intake rather than mandated proactive data gathering.',
      regulatoryHook: 'MDR Annex XIV Part A §1; MDCG 2020-7; MDR Article 83(1)',
      detectionMethod: 'PMS plan gap analysis against MDCG 2020-7 proactive data gathering checklist.',
      remediationPath: 'Add structured literature, registry, and digital signal monitoring protocols to the PMS plan.',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '61% of SME medtech PMS plans do not include a documented proactive surveillance component.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1161',
    name: 'Signal Quantification Results Not Documented in Traceable Format for NCA Inspection',
    description: 'Signal quantification outputs are stored in transient email threads and spreadsheets without a traceable, version-controlled record that can be reconstructed during an NCA inspection.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['signal-quantification', 'traceability', 'nca-inspection', 'pms', 'mdr'],
    failure_rate_pct: 53,
    is_active: true,
    demoRelevant: false,
    subTopic: 'safety-signal-quantification',
    data: {
      failureMode: 'Signal quantification decisions lack a traceable audit trail, making NCA inspection reconstruction impossible.',
      regulatoryHook: 'MDR Article 10(8); ISO 13485 §4.2.5; MDR Annex XIV Part B',
      detectionMethod: 'Simulated NCA inspection requesting signal quantification audit trail for a specific PSUR period.',
      remediationPath: 'Migrate signal quantification outputs to the document management system with version history enabled.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '44% of NCA inspection findings cite inadequate traceability of PMS signal quantification records.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },

  // ── Device Surveillance Registry (M1162–M1173) ──────────────────────────

  {
    code: 'M1162',
    name: 'National Registry Participation Gap for High-Risk Implantable Devices',
    description: 'A class III implantable device is not enrolled in the nationally mandated device registry, creating a PMS evidence gap and exposing the manufacturer to regulatory sanction.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['national-registry', 'implantable', 'pms', 'mdr', 'registry-participation'],
    failure_rate_pct: 48,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Class III implant is absent from the national device registry, creating a PMS evidence and compliance gap.',
      regulatoryHook: 'MDR Article 108; NHS GIRFT; ODEP; national registry regulations',
      detectionMethod: 'Cross-reference device portfolio against mandatory national registry enrollment lists.',
      remediationPath: 'Complete registry enrollment application, back-fill historical implant data, and assign a registry coordinator.',
      estimatedCost: '$40K–$100K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '22% of class III implantable devices in the EU are not enrolled in relevant national registries.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1163',
    name: 'Registry Data Quality Standards Not Meeting Minimum Completeness Thresholds',
    description: 'Registry submissions contain incomplete patient outcome fields at a rate of 28%, falling below the registry operator minimum completeness standard of 90%, risking suspension of participation.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-data-quality', 'completeness', 'pms', 'outcome-data', 'registry'],
    failure_rate_pct: 56,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Incomplete registry submissions fall below completeness thresholds and risk participation suspension.',
      regulatoryHook: 'MDR Article 108; registry operator data quality guidelines; ISO 13485 §7.1',
      detectionMethod: 'Registry data completeness report for the prior 12 months compared against operator minimum standards.',
      remediationPath: 'Assign a dedicated registry data steward and automate completeness checks before submission.',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '31% of manufacturers participating in national registries receive data quality warnings annually.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1164',
    name: 'Registry Data Not Linked Back Into PMS Plan as a Defined Data Source',
    description: `Registry-derived outcome data is reviewed informally by clinical affairs but is not formally referenced in the PMS plan as a scheduled data source, preventing its systematic integration into the manufacturer's PMS evidence.`,
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-linkage', 'pms-plan', 'data-source', 'mdr', 'annex-xiv'],
    failure_rate_pct: 60,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Registry data is reviewed informally but is absent from the PMS plan as a defined evidence source.',
      regulatoryHook: 'MDR Annex XIV Part A §1; MDCG 2020-7; MDR Article 83',
      detectionMethod: 'PMS plan document review for explicit registry data linkage and scheduled review frequency.',
      remediationPath: 'Amend PMS plan to list each registry as a data source with defined retrieval intervals and responsible owner.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '53% of PMS plans for implantable devices do not explicitly reference national registry data sources.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1165',
    name: 'Passive Surveillance Not Supplemented by Active Registry-Based Follow-Up',
    description: 'PMS relies entirely on passive complaint intake for long-term outcome monitoring without any active registry-based patient follow-up, creating evidence gaps for late-onset adverse events.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['passive-surveillance', 'active-follow-up', 'registry', 'pms', 'pmcf'],
    failure_rate_pct: 65,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Exclusive reliance on passive surveillance misses late-onset adverse events captured only by active registry follow-up.',
      regulatoryHook: 'MDR Annex XIV Part B; MDCG 2020-6; MDR Article 83(1)',
      detectionMethod: 'PMCF plan review for active data collection methods and registry-based follow-up protocols.',
      remediationPath: 'Design a registry-linked PMCF study with defined follow-up intervals for high-risk device classes.',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '6–18 months',
      industryBenchmark: '47% of class IIb/III manufacturers rely solely on passive surveillance for long-term outcome data.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1166',
    name: 'Rare Disease Device Registry Enrollment Impeded by Small Patient Population',
    description: 'A device indicated for a rare disease cannot meet registry completeness requirements due to the small patient population, and no alternative methodology has been agreed with the NCA to address this structural limitation.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['rare-disease', 'small-population', 'registry', 'pms', 'nca'],
    failure_rate_pct: 43,
    is_active: true,
    demoRelevant: false,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Rare-indication device cannot meet registry statistical thresholds and has no NCA-agreed alternative PMS methodology.',
      regulatoryHook: 'MDR Article 83; MDR Annex XIV Part A; MDCG 2020-7 §3.3',
      detectionMethod: 'PMS plan review for rare-population statistical justification and documented NCA consultation.',
      remediationPath: 'Initiate NCA scientific advice to agree a proportionate PMS methodology for small patient populations.',
      estimatedCost: '$30K–$90K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '29% of rare-indication device PMS plans lack a documented alternative to registry-based surveillance.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1167',
    name: 'Registry Submission Lag Exceeding Operator-Defined Reporting Window',
    description: 'Device implantation events are being submitted to the national registry an average of 47 days post-procedure, exceeding the registry operator maximum of 30 days and accumulating a backlog of overdue records.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-submission-lag', 'reporting-window', 'timeliness', 'pms', 'registry'],
    failure_rate_pct: 50,
    is_active: true,
    demoRelevant: false,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Registry submission lag exceeds the operator window, creating a growing backlog of non-compliant records.',
      regulatoryHook: 'Registry operator data submission rules; MDR Article 108; ISO 13485 §8.2.2',
      detectionMethod: 'Registry operator lag report compared against internal procedure dates for a rolling 6-month period.',
      remediationPath: 'Automate registry data extraction from the hospital information system to eliminate manual submission delays.',
      estimatedCost: '$35K–$90K',
      timeToRemediate: '3–6 months',
      industryBenchmark: 'Industry median registry submission lag is 18 days; 27% of participants exceed the 30-day threshold.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1168',
    name: 'Registry Outcome Data Not Incorporated Into PSUR Benefit-Risk Section',
    description: 'The most recent PSUR benefit-risk update does not reference registry-derived long-term outcome data that was available at the time of writing, producing an incomplete benefit characterization.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-data', 'psur', 'benefit-risk', 'pms', 'mdr-annex-xiv'],
    failure_rate_pct: 58,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'PSUR benefit characterization omits available registry outcome data, understating the benefit evidence base.',
      regulatoryHook: 'MDR Annex XIV Part B §3; MDCG 2022-21; MDR Article 85',
      detectionMethod: 'Cross-reference PSUR evidence table against registry data extraction log for the same reporting period.',
      remediationPath: 'Establish a mandatory registry data pull step in the PSUR authoring workflow.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '38% of PSUR submissions for class III devices do not cite available national registry outcome data.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1169',
    name: 'No Formal Process to Monitor Registry Protocol Amendments Affecting PMS Evidence',
    description: 'The national registry changed its data collection schema without the manufacturer being notified, causing historical comparability gaps that were not identified until a PSUR audit.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-protocol-change', 'pms', 'data-comparability', 'psur', 'mdr'],
    failure_rate_pct: 44,
    is_active: true,
    demoRelevant: false,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Unmonitored registry schema changes create historical data comparability gaps in the PMS evidence chain.',
      regulatoryHook: 'MDR Article 83; MDCG 2020-7; ISO 13485 §7.1',
      detectionMethod: 'Registry protocol amendment history review against PMS plan version history for alignment.',
      remediationPath: 'Subscribe to registry operator change notifications and add a registry protocol review step to PSUR preparation.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '35% of manufacturers are not formally subscribed to registry operator amendment notifications.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1170',
    name: 'Multi-Country Registry Reconciliation Producing Duplicate Patient Records',
    description: 'A device sold across five EU member states is enrolled in multiple national registries, and the absence of a patient deduplication protocol is producing double-counted adverse event records that inflate PMS safety metrics.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-reconciliation', 'deduplication', 'multi-country', 'pms', 'adverse-events'],
    failure_rate_pct: 46,
    is_active: true,
    demoRelevant: false,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Cross-registry duplicate patient records inflate adverse event counts and distort PMS safety metrics.',
      regulatoryHook: 'MDR Article 83; IMDRF N63; GDPR Article 9 for health data',
      detectionMethod: 'Statistical deduplication analysis of merged registry datasets using patient-level identifiers.',
      remediationPath: 'Implement GDPR-compliant probabilistic matching to deduplicate records before PMS signal analysis.',
      estimatedCost: '$60K–$160K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '21% of devices enrolled in multiple EU national registries have identified deduplication issues.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI probabilistic matching may incorrectly merge distinct patients, introducing false data linkages.',
    },
  },
  {
    code: 'M1171',
    name: 'Patient Consent for Registry Participation Not Documented at Device Implantation',
    description: 'Hospitals implanting the device have not consistently obtained and documented patient consent for registry participation, creating a GDPR compliance gap and incomplete registry coverage.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['patient-consent', 'registry', 'gdpr', 'pms', 'implant'],
    failure_rate_pct: 52,
    is_active: true,
    demoRelevant: false,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Inconsistent patient consent documentation creates GDPR gaps and incomplete registry coverage for PMS.',
      regulatoryHook: 'GDPR Article 9; MDR Article 108; national registry consent requirements',
      detectionMethod: 'Registry enrollment rate audit compared against device implantation procedure volume by hospital site.',
      remediationPath: 'Provide hospitals with a standardized consent form and checklist integrated into the implantation procedure.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '18% of device implantation sites have documented patient consent gaps for registry enrollment.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1172',
    name: 'Registry-Identified Safety Trend Not Escalated to PMS Signal Review Process',
    description: 'The national registry published an annual data report identifying an elevated revision rate for the manufacturer device, which was not escalated into the internal PMS signal review process.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['registry-trend', 'signal-escalation', 'pms', 'revision-rate', 'mdr'],
    failure_rate_pct: 68,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Published registry safety trend was not routed into the internal PMS signal review process.',
      regulatoryHook: 'MDR Article 83; MDR Annex XIV Part A §1; ISO 13485 §8.5.2',
      detectionMethod: 'Audit registry annual report review process for documented escalation to PMS signal owner.',
      remediationPath: 'Designate a registry monitoring owner and add registry report review to the PMS calendar with escalation criteria.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '42% of manufacturers lack a formal process to escalate registry-published trends to PMS review.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1173',
    name: 'Distributor Markets Not Covered by Any Registry-Based PMS Evidence',
    description: 'Devices sold through distributors in five non-EU markets have no registry enrollment or structured PMS data collection, leaving the global PMS dataset blind to safety events in those markets.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['distributor-markets', 'global-pms', 'registry-gap', 'pms', 'mdr'],
    failure_rate_pct: 71,
    is_active: true,
    demoRelevant: true,
    subTopic: 'device-surveillance-registry',
    data: {
      failureMode: 'Distributor-market PMS evidence gap leaves a significant portion of the global device population unmonitored.',
      regulatoryHook: 'MDR Article 83; IMDRF N63; 21 CFR 803 for US distributors',
      detectionMethod: 'PMS plan geographic coverage map compared against device sales territory distribution.',
      remediationPath: 'Contractually require distributors to collect and transmit adverse event data and enroll in available registries.',
      estimatedCost: '$50K–$140K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '58% of manufacturers with distributor networks lack PMS data collection requirements in distributor contracts.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },

  // ── PMS for IVD (M1174–M1185) ──────────────────────────────────────────

  {
    code: 'M1174',
    name: 'IVD PSUR Periodic Review Cycle Not Aligned With IVDR Mandatory Intervals',
    description: 'The IVD manufacturer performs PSUR updates every three years for a class C IVD, whereas IVDR mandates an annual cycle for this class, resulting in overdue regulatory submissions.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['ivd-psur', 'ivdr', 'periodic-review', 'class-c-ivd', 'pms'],
    failure_rate_pct: 59,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'IVD PSUR cycle is set at three years for a class C device requiring annual IVDR submission.',
      regulatoryHook: 'IVDR Article 82; IVDR Annex XIII; MDCG 2022-21',
      detectionMethod: 'PSUR schedule audit comparing planned review intervals against IVDR class-specific mandatory frequencies.',
      remediationPath: 'Update PSUR schedule in the PMS plan to annual intervals for all class C/D IVDs and submit overdue reports.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '41% of class C IVD manufacturers had incorrect PSUR intervals at the 2024 IVDR transition audit.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1175',
    name: 'Analytical Performance Drift Not Monitored as PMS Data Source in IVD',
    description: 'The PMS plan for a quantitative IVD does not include ongoing monitoring of analytical performance drift from post-market use data, creating a blind spot for gradual reagent or calibration degradation.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['analytical-performance', 'drift-monitoring', 'ivd', 'pms', 'ivdr'],
    failure_rate_pct: 64,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'Gradual analytical performance drift goes undetected because PMS plan lacks drift monitoring as a data source.',
      regulatoryHook: 'IVDR Annex XIII §1.1; ISO 15189; IVDR Article 78',
      detectionMethod: 'PMS plan review for analytical performance trending data sources and drift threshold definitions.',
      remediationPath: 'Add field-calibration data streams and EQA results as scheduled PMS data sources with drift alert thresholds.',
      estimatedCost: '$35K–$100K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '49% of quantitative IVD PMS plans lack a defined analytical performance drift monitoring protocol.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1176',
    name: 'External Quality Assessment Programme Results Not Reviewed as PMS Evidence',
    description: 'Results from national external quality assessment schemes in which laboratory customers participate are not systematically collected or reviewed as PMS evidence for the IVD.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['eqa', 'external-quality-assessment', 'ivd', 'pms', 'ivdr'],
    failure_rate_pct: 55,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'EQA programme results from customer laboratories are not harvested as PMS evidence for the IVD manufacturer.',
      regulatoryHook: 'IVDR Annex XIII §1.1; IVDR Article 78; ISO 13485 §8.2.1',
      detectionMethod: 'PMS plan review for EQA data collection process and customer EQA result sharing agreements.',
      remediationPath: 'Establish EQA result sharing agreements with major customer laboratories and integrate results into PMS review.',
      estimatedCost: '$20K–$60K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '57% of IVD manufacturers do not have a formal process to collect customer EQA results as PMS data.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1177',
    name: 'Reagent Lot Traceability Gap Preventing Root Cause Analysis in PMS Complaints',
    description: 'Complaints involving potential analytical failures cannot be fully investigated because the specific reagent lot used at the time of the reported result is not captured in the complaint record.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['reagent-lot', 'traceability', 'ivd', 'complaint', 'pms'],
    failure_rate_pct: 67,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'Missing reagent lot information in complaint records prevents lot-specific root cause investigation.',
      regulatoryHook: 'IVDR Article 78; ISO 13485 §7.5.10; 21 CFR 820.90',
      detectionMethod: 'Complaint record audit for lot number field completion rate across a 12-month sample.',
      remediationPath: 'Make reagent lot number a mandatory field in the complaint intake form and retrofit outstanding open cases.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '36% of IVD complaint records are missing the reagent lot number field at intake.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1178',
    name: 'In-Use Stability PMS Gap for Temperature-Sensitive IVD Reagent',
    description: 'The PMS plan does not include data collection on in-use stability complaints for a temperature-sensitive reagent, despite field reports suggesting performance degradation linked to cold-chain excursions.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['in-use-stability', 'cold-chain', 'ivd', 'pms', 'ivdr'],
    failure_rate_pct: 61,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'In-use stability events from cold-chain excursions are not captured in the PMS plan as a targeted data source.',
      regulatoryHook: 'IVDR Annex XIII §1.1; ISO 15224; IVDR Article 78',
      detectionMethod: 'PMS plan review for in-use stability monitoring protocol and complaint coding for cold-chain events.',
      remediationPath: 'Add cold-chain excursion and in-use stability as specific complaint complaint categories and PMS data fields.',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '44% of temperature-sensitive IVD PMS plans lack a dedicated in-use stability monitoring section.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1179',
    name: 'IVD PSUR Not Including Comparative Performance Against Predicate Device',
    description: 'The PSUR for a class C IVD does not include a comparative performance analysis against the predicate device claimed in the initial conformity assessment, leaving the state-of-the-art assessment incomplete.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['ivd-psur', 'predicate-device', 'comparative-performance', 'ivdr', 'state-of-the-art'],
    failure_rate_pct: 57,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'PSUR omits predicate device performance comparison, making the state-of-the-art assessment incomplete.',
      regulatoryHook: 'IVDR Annex XIII §2; MDCG 2022-21; IVDR Article 82',
      detectionMethod: 'PSUR content audit against MDCG 2022-21 section requirements for comparative performance.',
      remediationPath: 'Add a comparative performance section to the PSUR template that references the registered predicate device.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '33% of class C IVD PSURs reviewed in 2024 lacked a comparative state-of-the-art performance section.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1180',
    name: 'Post-Market Clinical Follow-Up Study for IVD Not Initiated Within Required Timeframe',
    description: 'The PSUR identifies a need for additional post-market clinical follow-up data but no PMCF study has been initiated within the NB-required 12-month timeframe, resulting in a notified body finding.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pmcf', 'ivd', 'post-market-follow-up', 'ivdr', 'notified-body'],
    failure_rate_pct: 53,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'PMCF study identified in PSUR was not initiated within the NB-required timeframe, generating a finding.',
      regulatoryHook: 'IVDR Annex XIII Part B; IVDR Article 82; MDCG 2020-6',
      detectionMethod: 'PMCF plan status review against PSUR commitment dates and NB correspondence.',
      remediationPath: 'Appoint a PMCF study sponsor, submit the study protocol to the NB, and set a milestone-based activation plan.',
      estimatedCost: '$100K–$400K',
      timeToRemediate: '12–24 months',
      industryBenchmark: '28% of PSUR PMCF commitments for IVDs are not initiated within the agreed timeframe.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1181',
    name: 'Interference and Cross-Reactivity Complaints Not Segmented in IVD PMS Review',
    description: 'Analytical interference and cross-reactivity complaints are aggregated with general performance complaints in the PMS review, masking a pattern specific to a particular analyte interferent.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['interference', 'cross-reactivity', 'ivd', 'pms', 'complaint'],
    failure_rate_pct: 49,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'Interference complaints are aggregated with general PMS data, concealing interferent-specific signal patterns.',
      regulatoryHook: 'IVDR Annex XIII §1.1; ISO 17511; IVDR Article 78',
      detectionMethod: 'Complaint re-coding exercise separating interference and cross-reactivity events from general performance.',
      remediationPath: 'Add interference and cross-reactivity as primary complaint complaint categories in the IVD complaint taxonomy.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '39% of IVD complaint taxonomies do not have a distinct category for interference-specific events.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1182',
    name: 'Calibration Frequency Drift Signal Not Correlated With Field Service Data',
    description: 'PMS review does not correlate field service calibration frequency data with analytical performance complaints, missing a leading indicator of systematic calibrator degradation.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['calibration', 'field-service', 'ivd', 'pms', 'drift-correlation'],
    failure_rate_pct: 54,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'Field service calibration logs are not integrated into PMS analysis, missing a calibrator degradation leading indicator.',
      regulatoryHook: 'IVDR Article 78; ISO 15189; IVDR Annex XIII',
      detectionMethod: 'Data linkage analysis correlating field service calibration frequency against analytical performance complaint dates.',
      remediationPath: 'Integrate field service data into the PMS database and add calibration frequency as a PMS leading indicator metric.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '47% of IVD manufacturers do not integrate field service calibration data into PMS signal analysis.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1183',
    name: 'Near-Patient Testing IVD PMS Not Capturing Lay-User Error Events',
    description: 'A near-patient testing IVD intended for lay-user self-testing does not have a PMS data collection mechanism for user error events, which represent the dominant real-world failure mode.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['near-patient-testing', 'lay-user', 'user-error', 'pms', 'ivdr'],
    failure_rate_pct: 70,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'PMS plan for a lay-user IVD has no mechanism to capture user error events, the dominant real-world failure mode.',
      regulatoryHook: 'IVDR Annex XIII §1.1; IEC 62366-1; IVDR Article 78',
      detectionMethod: 'PMS plan review for user error data collection methods and helpline call complaint categorization.',
      remediationPath: 'Add a customer helpline user error complaint category and online user survey to capture lay-user PMS data.',
      estimatedCost: '$40K–$110K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '53% of lay-user IVD PMS plans lack a structured user error data collection mechanism.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1184',
    name: 'IVD PMS Plan Does Not Address Next-Generation Sequencing Result Interpretation Variability',
    description: 'A next-generation sequencing IVD PMS plan focuses on reagent performance but does not monitor inter-laboratory interpretation variability, which is the primary source of clinical outcome divergence.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['ngs', 'interpretation-variability', 'ivd', 'pms', 'ivdr'],
    failure_rate_pct: 66,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'NGS IVD PMS plan omits inter-laboratory interpretation variability, the primary clinical outcome risk.',
      regulatoryHook: 'IVDR Annex XIII §1.1; MDCG 2022-2; IVDR Article 78',
      detectionMethod: 'PMS plan review for inter-laboratory concordance monitoring protocols and proficiency testing references.',
      remediationPath: 'Add inter-laboratory concordance studies and participation in genomics proficiency testing schemes to the PMS plan.',
      estimatedCost: '$60K–$180K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '44% of NGS IVD PMS plans do not include inter-laboratory interpretation variability monitoring.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI variant calling algorithms introduce additional interpretation variability not captured by traditional PMS methods.',
    },
  },
  {
    code: 'M1185',
    name: 'IVD PMS Not Distinguishing Between Assay Failure and Pre-Analytical Sample Quality Issues',
    description: 'The PMS complaint classification system does not separate assay failures from pre-analytical sample quality problems, inflating the apparent device failure rate and obscuring true analytical performance.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pre-analytical', 'sample-quality', 'ivd', 'pms', 'assay-failure'],
    failure_rate_pct: 56,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-for-ivd',
    data: {
      failureMode: 'Lumped complaint classification inflates device failure rate by not separating pre-analytical from assay issues.',
      regulatoryHook: 'IVDR Article 78; IVDR Annex XIII; ISO 22367',
      detectionMethod: 'Complaint record re-classification using root cause to separate pre-analytical from device failure modes.',
      remediationPath: 'Update complaint taxonomy to mandate pre-analytical root cause assessment before device failure classification.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '42% of IVD complaint records do not distinguish between pre-analytical and assay failure root causes.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },

  // ── Vigilance Reporting Quality (M1186–M1197) ──────────────────────────

  {
    code: 'M1186',
    name: 'Initial Vigilance Reports Consistently Missing Mandatory Device Identification Fields',
    description: 'NCA feedback indicates that 30% of initial vigilance reports submitted by the manufacturer are missing UDI or device model version, triggering NCA follow-up requests and delaying report acceptance.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['vigilance-report', 'initial-report', 'udi', 'mdr-article-87', 'nca'],
    failure_rate_pct: 62,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Initial vigilance reports are missing UDI or device model fields, generating NCA follow-up delays.',
      regulatoryHook: 'MDR Article 87(1); MDR Annex X; EUDAMED vigilance module requirements',
      detectionMethod: 'Initial report completeness audit against MDR Annex X mandatory field checklist.',
      remediationPath: 'Implement a mandatory field validation step in the vigilance report authoring tool before submission.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '29% of initial MDR vigilance reports require NCA follow-up due to incomplete mandatory fields.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1187',
    name: 'Article 87 Thirty-Day Follow-Up Report Deadline Missed for Serious Incidents',
    description: 'The regulatory affairs team consistently submits 30-day follow-up reports for serious incidents on day 32–35, creating a pattern of minor but documented MDR Article 87 non-compliance.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['article-87', '30-day-timeline', 'vigilance', 'mdr', 'serious-incident'],
    failure_rate_pct: 58,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Follow-up reports for serious incidents are systematically submitted 2–5 days beyond the Article 87 30-day deadline.',
      regulatoryHook: 'MDR Article 87(3); MEDDEV 2.12/1 Rev 8; NCA enforcement guidance',
      detectionMethod: 'Vigilance log timeline audit comparing incident classification date against follow-up submission date.',
      remediationPath: 'Configure automated reminders at day 20 and day 25 post-incident classification in the QMS.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '23% of manufacturers have at least one Article 87 30-day deadline breach per year.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1188',
    name: 'Root Cause Investigation Depth in MDR Reports Insufficient for NCA Acceptance',
    description: 'Submitted MDR reports describe probable cause at a high level without evidence of systematic root cause analysis, leading to NCA rejection of reports as incomplete under MDR Annex X.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['root-cause', 'mdr-report', 'investigation-depth', 'annex-x', 'nca'],
    failure_rate_pct: 69,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'MDR reports contain superficial root cause narratives that fail the NCA Annex X investigation depth standard.',
      regulatoryHook: 'MDR Annex X §4; MDR Article 87; MEDDEV 2.12/1 Rev 8',
      detectionMethod: 'Structured content review of last 12 months of MDR submissions against Annex X investigation depth criteria.',
      remediationPath: 'Train the complaint investigation team on 5-Why and Fishbone methodology and add review gate before submission.',
      estimatedCost: '$25K–$70K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '34% of MDR vigilance report rejections cite insufficient root cause investigation depth.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1189',
    name: 'EUDAMED Vigilance Module Entries Contain Incorrect Incident Classification Codes',
    description: 'Spot audit of EUDAMED vigilance module entries identified that 18% of incident classification codes are incorrect, misrepresenting incident severity to NCA reviewers.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['eudamed', 'vigilance-module', 'classification-code', 'mdr', 'nca'],
    failure_rate_pct: 55,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'EUDAMED entries contain incorrect incident classification codes, misrepresenting severity to NCA reviewers.',
      regulatoryHook: 'MDR Article 87; EUDAMED actor module guide; MDR Annex X',
      detectionMethod: 'EUDAMED entry audit comparing submitted classification codes against internal incident severity determinations.',
      remediationPath: 'Implement a dual-check process for EUDAMED classification code entry before final submission.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '16% of EUDAMED vigilance entries contain at least one classification code discrepancy.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1190',
    name: 'NCA Follow-Up Request Response Time Exceeding Agreed Turnaround Period',
    description: 'NCAs are issuing follow-up information requests and receiving responses an average of 22 days later, exceeding the informally agreed 14-day standard and creating compliance relationship risk.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['nca-follow-up', 'response-time', 'vigilance', 'mdr', 'compliance'],
    failure_rate_pct: 47,
    is_active: true,
    demoRelevant: false,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'NCA follow-up responses are taking 8 days longer than the informally agreed turnaround standard.',
      regulatoryHook: 'MDR Article 88; MEDDEV 2.12/1 Rev 8; NCA bilateral engagement guidance',
      detectionMethod: 'NCA correspondence log audit measuring request-to-response elapsed days over the past 12 months.',
      remediationPath: 'Assign a dedicated regulatory affairs owner for each NCA with an escalation trigger at day 10 post-request.',
      estimatedCost: '$10K–$25K',
      timeToRemediate: '1–2 months',
      industryBenchmark: 'Median NCA follow-up response time is 11 days; 31% of manufacturers exceed 20 days.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1191',
    name: 'Field Safety Corrective Action Not Linked to Originating Vigilance Report in EUDAMED',
    description: 'FSCAs are entered in EUDAMED without cross-referencing the originating vigilance report, breaking the traceability chain required by MDR and preventing NCA impact assessment.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['fsca', 'eudamed', 'traceability', 'vigilance', 'mdr'],
    failure_rate_pct: 61,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'EUDAMED FSCA records are not linked to the originating vigilance report, breaking the MDR traceability chain.',
      regulatoryHook: 'MDR Article 89; EUDAMED FSCA module guide; MDR Annex X',
      detectionMethod: 'EUDAMED FSCA record audit for presence of originating vigilance report link field population.',
      remediationPath: 'Update the FSCA entry procedure to mandate vigilance report reference number as a required field.',
      estimatedCost: '$10K–$25K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '24% of EUDAMED FSCA entries lack a link to the originating vigilance report.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1192',
    name: 'Trend Report Threshold Not Defined for Statistically Significant Non-Serious Incidents',
    description: 'The vigilance procedure does not define a quantitative threshold for submitting trend reports on non-serious incidents, exposing the manufacturer to NCA criticism for lack of proactive trend reporting.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['trend-report', 'non-serious-incident', 'mdr-article-88', 'vigilance', 'threshold'],
    failure_rate_pct: 63,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Absence of a quantitative trend report threshold for non-serious incidents leaves reporting at individual discretion.',
      regulatoryHook: 'MDR Article 88; MEDDEV 2.12/1 Rev 8; IMDRF N56',
      detectionMethod: 'Vigilance procedure review for Article 88 trend report threshold definition and associated criteria.',
      remediationPath: 'Define a statistical threshold (e.g., 10% increase over 6-month baseline) for triggering non-serious trend reports.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '48% of vigilance procedures do not contain a defined quantitative threshold for Article 88 trend reports.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1193',
    name: 'Vigilance Report Narrative Quality Inconsistent Across Different Regulatory Affairs Authors',
    description: 'NCA feedback shows significant quality variation in vigilance report narratives depending on the regulatory affairs author, indicating an absence of standardized narrative templates.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['vigilance-narrative', 'report-quality', 'standardization', 'mdr', 'regulatory-affairs'],
    failure_rate_pct: 51,
    is_active: true,
    demoRelevant: false,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Vigilance report narrative quality varies by author, generating inconsistent NCA reception and follow-up rates.',
      regulatoryHook: 'MDR Annex X; MEDDEV 2.12/1 Rev 8; MDR Article 87',
      detectionMethod: 'Comparative narrative quality review across 24 reports from different authors against Annex X criteria.',
      remediationPath: 'Develop and mandate use of standardized narrative templates with annotated examples for each incident type.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '37% of regulatory affairs teams report that vigilance narrative quality varies significantly by author.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1194',
    name: 'MDR Reportability Decision Not Documented for Events Classified as Non-Reportable',
    description: 'Events reviewed and classified as non-reportable do not have a documented reportability rationale, preventing reconstruction of the decision rationale during NCA inspection or litigation.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['reportability-decision', 'non-reportable', 'mdr', 'documentation', 'vigilance'],
    failure_rate_pct: 68,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Non-reportable event decisions lack documented rationale, creating reconstruction gaps for NCA inspections.',
      regulatoryHook: 'MDR Article 87; ISO 13485 §8.2.2; MEDDEV 2.12/1 Rev 8',
      detectionMethod: 'Complaint record audit for documented reportability rationale on non-reportable event classifications.',
      remediationPath: 'Add a mandatory reportability rationale field to the complaint record form for all non-reportable classifications.',
      estimatedCost: '$10K–$25K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '46% of complaint records for non-reportable events lack a documented reportability determination rationale.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1195',
    name: 'Vigilance Procedure Not Updated Following MDR Implementation Guidance Revision',
    description: 'MDCG 2023-3 guidance on vigilance reporting was published 18 months ago, but the internal vigilance procedure has not been updated to reflect the clarified serious incident definition.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['vigilance-procedure', 'mdcg-guidance', 'procedure-update', 'mdr', 'serious-incident'],
    failure_rate_pct: 57,
    is_active: true,
    demoRelevant: false,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Vigilance procedure is 18 months out of date with MDCG guidance, risking misclassification of serious incidents.',
      regulatoryHook: 'MDR Article 87; MDCG 2023-3; ISO 13485 §4.2.3',
      detectionMethod: 'Procedure version date comparison against MDCG guidance publication dates for all in-scope guidance.',
      remediationPath: 'Assign a regulatory intelligence owner to monitor MDCG publications and trigger procedure updates within 90 days.',
      estimatedCost: '$10K–$30K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '41% of vigilance procedures are not updated within 6 months of a relevant MDCG guidance revision.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1196',
    name: 'Manufacturer Trend Data Not Shared With Notified Body in Annual PMS Report',
    description: 'The annual PMS report submitted to the notified body does not include the manufacturer trend report data required under MDR Annex XIV Part B, leaving the NB without complete PMS evidence for certificate renewal.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['trend-data', 'notified-body', 'pms-report', 'mdr-annex-xiv', 'certificate-renewal'],
    failure_rate_pct: 64,
    is_active: true,
    demoRelevant: true,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'Annual PMS report omits trend report data required by MDR Annex XIV Part B for NB certificate renewal.',
      regulatoryHook: 'MDR Annex XIV Part B §3; MDR Article 85; NB audit programme',
      detectionMethod: 'PMS report content audit against MDR Annex XIV Part B required elements checklist.',
      remediationPath: 'Add trend report data summary as a mandatory section in the annual PMS report template.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '30% of annual PMS reports submitted for NB review are missing MDR Annex XIV Part B required elements.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1197',
    name: 'Periodic Safety Update Report Submitted Late to Notified Body for Class IIb Device',
    description: 'The PSUR for a class IIb device was submitted to the notified body 45 days after the annual review date, missing the mandatory submission window and triggering a NB non-conformity.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['psur', 'submission-timeline', 'notified-body', 'mdr', 'class-iib'],
    failure_rate_pct: 53,
    is_active: true,
    demoRelevant: false,
    subTopic: 'vigilance-reporting-quality',
    data: {
      failureMode: 'PSUR submitted 45 days late to the NB, triggering a non-conformity for the class IIb device.',
      regulatoryHook: 'MDR Article 85; MDR Annex XIV Part B; NB audit programme',
      detectionMethod: 'PSUR submission date log audit against annual review calendar for all device classes.',
      remediationPath: 'Set PSUR authoring start date 90 days before the annual review date and assign milestone owners.',
      estimatedCost: '$10K–$25K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '21% of class IIb PSURs are submitted at least 30 days late to the notified body.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },

  // ── PMS Plan Update Governance (M1198–M1209) ────────────────────────────

  {
    code: 'M1198',
    name: 'PMS Plan Revision Triggers Not Formally Documented in QMS',
    description: 'The PMS plan is updated on an ad hoc basis without formally documented revision triggers in the QMS, leading to inconsistent plan currency across the device portfolio.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pms-plan', 'revision-trigger', 'qms', 'mdr', 'governance'],
    failure_rate_pct: 60,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Ad hoc PMS plan updates without QMS-defined triggers produce inconsistent plan currency across the portfolio.',
      regulatoryHook: 'MDR Article 84; ISO 13485 §8.2.1; MDR Annex XIV Part A',
      detectionMethod: 'QMS procedure review for documented PMS plan revision trigger list and associated owners.',
      remediationPath: 'Define a formal trigger list in the PMS SOP covering PMCF conclusions, signal events, and IFU changes.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '52% of device portfolios lack formal PMS plan revision triggers documented in the QMS.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1199',
    name: 'PMCF Study Conclusions Not Integrated Into Updated PMS Plan Within Required Period',
    description: 'A PMCF study concluded 14 months ago, but its clinical findings have not been integrated into the PMS plan update as required by MDR Annex XIV, leaving an unresolved gap in the regulatory dossier.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pmcf', 'pms-plan', 'conclusion-integration', 'mdr-annex-xiv', 'governance'],
    failure_rate_pct: 65,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'PMCF conclusions 14 months old are not integrated into the PMS plan, creating a dossier gap.',
      regulatoryHook: 'MDR Annex XIV Part B §4; MDCG 2020-6; MDR Article 83',
      detectionMethod: 'PMCF study completion date compared against PMS plan version dates to identify integration gaps.',
      remediationPath: 'Add PMCF conclusion integration as a mandatory PMS plan revision trigger with a 90-day deadline.',
      estimatedCost: '$20K–$55K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '38% of PMS plans are not updated within 12 months of a PMCF study conclusion.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1200',
    name: 'PMS Plan Not Linked to QMS Document Control for Version Management',
    description: 'The PMS plan exists as an uncontrolled Word document outside the QMS, preventing version history tracking and making it impossible to verify which version was active during a given PMS review period.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pms-plan', 'document-control', 'qms', 'version-management', 'mdr'],
    failure_rate_pct: 58,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Uncontrolled PMS plan document prevents version history tracing and active-version verification.',
      regulatoryHook: 'ISO 13485 §4.2.3; MDR Article 10(8); MDR Annex XIV Part A',
      detectionMethod: 'QMS document register audit to verify PMS plan is a controlled document with version history.',
      remediationPath: 'Migrate PMS plan into the QMS document control system with version numbering and owner assignment.',
      estimatedCost: '$10K–$25K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '33% of SME manufacturers store the PMS plan outside the QMS document control system.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1201',
    name: 'Benefit-Risk Section in PMS Plan Not Updated Since Initial CE Marking',
    description: `The PMS plan benefit-risk section reflects the pre-market benefit-risk determination and has not been updated with post-market experience data since the device's initial CE marking three years ago.`,
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['benefit-risk', 'pms-plan', 'ce-marking', 'mdr', 'annex-xiv'],
    failure_rate_pct: 72,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'PMS plan benefit-risk section remains at initial CE marking determination with no post-market evidence updates.',
      regulatoryHook: 'MDR Annex XIV Part A §1(c); MDCG 2020-13; MDR Article 10(3)',
      detectionMethod: 'PMS plan benefit-risk version date audit against CE certificate date and post-market evidence milestones.',
      remediationPath: 'Establish an annual benefit-risk currency review as a mandatory governance step in the PMS plan.',
      estimatedCost: '$30K–$80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '55% of class IIb PMS plans have a benefit-risk section that has not been updated post-CE marking.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1202',
    name: 'Annex XIV PMS Output Not Feeding Back Into Design and Manufacturing Process Review',
    description: 'PMS findings are summarized in the PSUR but are not formally fed back into the design review and manufacturing process review as required by MDR Annex XIV, creating a closed-loop gap.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['annex-xiv', 'pms-output', 'design-review', 'closed-loop', 'mdr'],
    failure_rate_pct: 67,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'PMS output is not formally fed into design or manufacturing reviews, breaking the MDR Annex XIV closed loop.',
      regulatoryHook: 'MDR Annex XIV Part A §3; ISO 13485 §7.3.8; MDR Article 83',
      detectionMethod: 'Design review and manufacturing review records audit for documented PMS input traceability.',
      remediationPath: 'Add a PMS input agenda item to the annual design review meeting and document action items.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '49% of design review records for commercial devices show no documented PMS input traceability.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1203',
    name: 'PMS Plan Update Approval Authority Not Defined in QMS Governance Matrix',
    description: 'The QMS governance matrix does not specify approval authority for PMS plan updates, resulting in plans being approved by inappropriate personnel and creating a compliance risk.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pms-plan', 'approval-authority', 'qms', 'governance', 'mdr'],
    failure_rate_pct: 48,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Undefined PMS plan approval authority leads to inappropriate signatories and a QMS governance gap.',
      regulatoryHook: 'ISO 13485 §5.5.1; MDR Article 10(9); MDR Annex XIV Part A',
      detectionMethod: 'QMS governance matrix review for PMS plan approval authority designation.',
      remediationPath: 'Update the governance matrix to designate the responsible person and deputy as PMS plan approval authority.',
      estimatedCost: '$5K–$15K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '27% of QMS governance matrices do not explicitly define PMS plan approval authority.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1204',
    name: 'PMS Plan Scope Not Updated to Include New Accessory Devices Added Post-CE Marking',
    description: 'Two accessory devices added to the product family after initial CE marking are not included in the PMS plan scope, leaving post-market surveillance gaps for these regulated accessories.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pms-plan', 'accessory', 'scope', 'mdr', 'ce-marking'],
    failure_rate_pct: 54,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Post-CE accessory additions are absent from the PMS plan scope, creating surveillance gaps for regulated accessories.',
      regulatoryHook: 'MDR Article 84; MDR Article 2(2); ISO 13485 §8.2.1',
      detectionMethod: 'Device registration cross-reference against PMS plan scope to identify post-CE accessories not listed.',
      remediationPath: 'Update the PMS plan scope to include all accessories and add product family scope review to the annual PMS plan update.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '31% of PMS plans for multi-accessory families have at least one accessory omitted from scope.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1205',
    name: 'IFU Change Not Triggering PMS Plan Review for Affected Indications',
    description: 'A label change expanding the device indication was implemented without triggering a PMS plan review to address the surveillance requirements of the new patient population.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['ifu-change', 'pms-plan-review', 'indication-expansion', 'mdr', 'governance'],
    failure_rate_pct: 62,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Indication expansion label change was not linked to a PMS plan review for the new patient population.',
      regulatoryHook: 'MDR Article 84; MDR Article 54; ISO 13485 §7.3.7',
      detectionMethod: 'Change control log cross-reference against PMS plan revision dates for IFU indication changes.',
      remediationPath: 'Add PMS plan review as a mandatory action item in the change control procedure for IFU indication changes.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '44% of IFU indication change control records do not include a linked PMS plan review action.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1206',
    name: 'PMS Plan Annual Review Conducted Without Cross-Functional Input From Clinical Affairs',
    description: 'The annual PMS plan review is conducted exclusively by the regulatory affairs team without formal input from clinical affairs, resulting in PMCF adequacy judgments that lack clinical expertise.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pms-plan', 'cross-functional', 'clinical-affairs', 'annual-review', 'mdr'],
    failure_rate_pct: 56,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Annual PMS plan review without clinical affairs input produces PMCF adequacy judgments lacking clinical expertise.',
      regulatoryHook: 'MDR Annex XIV Part A; ISO 13485 §5.6; MDR Article 83',
      detectionMethod: 'Annual review meeting minutes audit for cross-functional attendee list and clinical affairs participation.',
      remediationPath: 'Mandate clinical affairs participation in the annual PMS plan review and document their sign-off.',
      estimatedCost: '$5K–$15K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '38% of annual PMS plan review meeting records show no clinical affairs representative participation.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1207',
    name: 'PMS Plan Update Backlog Growing Due to Understaffed PMS Function',
    description: 'The PMS function is staffed by a single person responsible for 18 devices, creating a backlog of 7 overdue PMS plan updates that have exceeded their scheduled review dates.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['pms-staffing', 'plan-backlog', 'resource-gap', 'mdr', 'governance'],
    failure_rate_pct: 73,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Single-person PMS function for 18 devices has created a 7-plan update backlog exceeding scheduled review dates.',
      regulatoryHook: 'MDR Article 10(10); ISO 13485 §6.2; MDR Annex XIV Part A',
      detectionMethod: 'PMS plan schedule audit comparing planned review dates against actual completion dates per device.',
      remediationPath: 'Conduct a PMS workload assessment and either hire additional staff or triage devices by risk class for prioritization.',
      estimatedCost: '$80K–$200K',
      timeToRemediate: '6–12 months',
      industryBenchmark: '26% of SME manufacturers have PMS plan update backlogs exceeding 90 days at time of NB audit.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1208',
    name: 'State-of-the-Art Review in PMS Plan Not Updated to Reflect Current Clinical Guidelines',
    description: 'The state-of-the-art section of the PMS plan references clinical guidelines from 2021 that have since been superseded, creating an inconsistency with the current clinical benchmark for the device.',
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['state-of-the-art', 'clinical-guidelines', 'pms-plan', 'mdr', 'benchmark'],
    failure_rate_pct: 61,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'Outdated clinical guideline references in the state-of-the-art section create a benchmark inconsistency with current practice.',
      regulatoryHook: 'MDR Annex XIV Part A §1; MDCG 2020-13; MDR Article 83',
      detectionMethod: 'Literature currency check comparing PMS plan guideline references against current published versions.',
      remediationPath: 'Schedule an annual state-of-the-art literature update as part of the PMS plan annual review cycle.',
      estimatedCost: '$15K–$40K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '43% of PMS plans contain clinical guideline references that are more than two years out of date.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },
  {
    code: 'M1209',
    name: 'PMS Plan Output Not Formally Reviewed by Responsible Person Before NB Submission',
    description: `PMS plan outputs, including the PSUR and PMCF evaluation report, are submitted to the notified body without a formal review and sign-off by the manufacturer's responsible person as required by MDR.`,
    vertical: 'medtech',
    office_category: 'Post-Market Surveillance',
    keywords: ['responsible-person', 'pms-output', 'notified-body', 'mdr-article-15', 'governance'],
    failure_rate_pct: 49,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pms-plan-update-governance',
    data: {
      failureMode: 'PSUR and PMCF evaluation report are submitted to the NB without the MDR responsible person sign-off.',
      regulatoryHook: 'MDR Article 15; MDR Article 85; ISO 13485 §5.5.2',
      detectionMethod: 'NB submission package audit for responsible person signature on PSUR and PMCF evaluation reports.',
      remediationPath: 'Add responsible person review and electronic sign-off as the final gate in the NB submission approval workflow.',
      estimatedCost: '$5K–$15K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '19% of PSUR NB submissions lack a documented responsible person review sign-off.',
      aiInsertionRisk: false,
      aiRiskDescription: 'No AI-specific risk identified for this pattern.',
    },
  },

];
