/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 67: Agentic AI: Administrative Copilots
// Part 1: H17200-H17249
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM67_PART1_PATTERNS = [
  {
    code: 'H17200',
    name: 'Administrative Copilot Documentation Review Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for documentation review but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'CMS CoP', 'Azure Health Data Services', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17201',
    name: 'Task Automation Vendor Comparison Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for vendor comparison but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'NCQA HEDIS audit', 'Snowflake Healthcare', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17202',
    name: 'HR Service Delivery Capacity Forecasting Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for capacity forecasting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'FDA SaMD guidance', 'Databricks Lakehouse', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17203',
    name: 'Policy Retrieval Staffing Optimization Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for staffing optimization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'NIST AI RMF', 'ServiceNow workflow', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17204',
    name: 'Approval Workflow Quality Abstraction Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for quality abstraction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'ONC HTI-1', 'Salesforce Health Cloud', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17205',
    name: 'Administrative Copilot Patient Outreach Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for patient outreach but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'TEFCA participation', 'startup maturity evidence', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17206',
    name: 'Task Automation Triage Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for triage but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'FHIR R4 mapping', 'SOC 2 Type II', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17207',
    name: 'HR Service Delivery Drafting Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for drafting but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'HL7 v2 ADT reconciliation', 'HITRUST roadmap', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17208',
    name: 'Policy Retrieval Summarization Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for summarization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'Epic change control', 'Series B burn rate', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17209',
    name: 'Approval Workflow Risk Scoring Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for risk scoring but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'model registry', 'implementation partner capacity', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17210',
    name: 'Administrative Copilot Worklist Prioritization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for worklist prioritization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'deployment-site validation', 'referenceable health-system customer', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17211',
    name: 'Task Automation Appeal Generation Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for appeal generation but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'MLOps monitoring', 'clinical advisory board', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17212',
    name: 'HR Service Delivery Order Recommendation Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for order recommendation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'clinical safety review', 'FDA submission posture', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17213',
    name: 'Policy Retrieval Benefit Verification Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for benefit verification but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'procurement RFP scoring', 'KLAS commentary', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17214',
    name: 'Approval Workflow Eligibility Prediction Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for eligibility prediction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'BAFO contract clause', 'Epic App Orchard integration', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17215',
    name: 'Administrative Copilot Care Gap Closure Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for care gap closure but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'HIPAA BAA', 'Microsoft Cloud for Healthcare', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17216',
    name: 'Task Automation Cohort Matching Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for cohort matching but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'minimum necessary policy', 'AWS HealthLake', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17217',
    name: 'HR Service Delivery Contract Analysis Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for contract analysis but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'TJC survey evidence', 'Azure Health Data Services', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17218',
    name: 'Policy Retrieval Agentic Orchestration Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for agentic orchestration but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'CMS CoP', 'Snowflake Healthcare', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17219',
    name: 'Approval Workflow Coding Suggestion Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for coding suggestion but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'NCQA HEDIS audit', 'Databricks Lakehouse', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17220',
    name: 'Administrative Copilot Documentation Review Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for documentation review but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'FDA SaMD guidance', 'ServiceNow workflow', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17221',
    name: 'Task Automation Vendor Comparison Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for vendor comparison but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'NIST AI RMF', 'Salesforce Health Cloud', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17222',
    name: 'HR Service Delivery Capacity Forecasting Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for capacity forecasting but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'ONC HTI-1', 'startup maturity evidence', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17223',
    name: 'Policy Retrieval Staffing Optimization Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for staffing optimization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'TEFCA participation', 'SOC 2 Type II', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17224',
    name: 'Approval Workflow Quality Abstraction Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for quality abstraction but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'FHIR R4 mapping', 'HITRUST roadmap', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17225',
    name: 'Administrative Copilot Patient Outreach Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for patient outreach but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'HL7 v2 ADT reconciliation', 'Series B burn rate', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17226',
    name: 'Task Automation Triage Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for triage but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'Epic change control', 'implementation partner capacity', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17227',
    name: 'HR Service Delivery Drafting Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for drafting but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'model registry', 'referenceable health-system customer', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17228',
    name: 'Policy Retrieval Summarization Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for summarization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'deployment-site validation', 'clinical advisory board', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17229',
    name: 'Approval Workflow Risk Scoring Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for risk scoring but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'MLOps monitoring', 'FDA submission posture', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17230',
    name: 'Administrative Copilot Worklist Prioritization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for worklist prioritization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'clinical safety review', 'KLAS commentary', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17231',
    name: 'Task Automation Appeal Generation Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for appeal generation but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'procurement RFP scoring', 'Epic App Orchard integration', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17232',
    name: 'HR Service Delivery Order Recommendation Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for order recommendation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'BAFO contract clause', 'Microsoft Cloud for Healthcare', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17233',
    name: 'Policy Retrieval Benefit Verification Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for benefit verification but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'HIPAA BAA', 'AWS HealthLake', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17234',
    name: 'Approval Workflow Eligibility Prediction Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for eligibility prediction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'minimum necessary policy', 'Azure Health Data Services', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17235',
    name: 'Administrative Copilot Care Gap Closure Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for care gap closure but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'TJC survey evidence', 'Snowflake Healthcare', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17236',
    name: 'Task Automation Cohort Matching Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for cohort matching but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'CMS CoP', 'Databricks Lakehouse', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17237',
    name: 'HR Service Delivery Contract Analysis Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for contract analysis but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'NCQA HEDIS audit', 'ServiceNow workflow', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17238',
    name: 'Policy Retrieval Agentic Orchestration Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for agentic orchestration but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'FDA SaMD guidance', 'Salesforce Health Cloud', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17239',
    name: 'Approval Workflow Coding Suggestion Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for coding suggestion but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'NIST AI RMF', 'startup maturity evidence', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17240',
    name: 'Administrative Copilot Documentation Review Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for documentation review but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'ONC HTI-1', 'SOC 2 Type II', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17241',
    name: 'Task Automation Vendor Comparison Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for vendor comparison but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'TEFCA participation', 'HITRUST roadmap', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17242',
    name: 'HR Service Delivery Capacity Forecasting Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for capacity forecasting but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'FHIR R4 mapping', 'Series B burn rate', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17243',
    name: 'Policy Retrieval Staffing Optimization Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for staffing optimization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'HL7 v2 ADT reconciliation', 'implementation partner capacity', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17244',
    name: 'Approval Workflow Quality Abstraction Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for quality abstraction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'Epic change control', 'referenceable health-system customer', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17245',
    name: 'Administrative Copilot Patient Outreach Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for patient outreach but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'model registry', 'clinical advisory board', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17246',
    name: 'Task Automation Triage Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for triage but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'deployment-site validation', 'FDA submission posture', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17247',
    name: 'HR Service Delivery Drafting Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for drafting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'MLOps monitoring', 'KLAS commentary', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17248',
    name: 'Policy Retrieval Summarization Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for summarization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'clinical safety review', 'Epic App Orchard integration', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17249',
    name: 'Approval Workflow Risk Scoring Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for risk scoring but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'procurement RFP scoring', 'Microsoft Cloud for Healthcare', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  }
];
