/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 56: Compliance, Privacy, HIPAA & BAA AI Controls
// Part 3: H15100-H15149
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM56_PART3_PATTERNS = [
  {
    code: 'H15100',
    name: 'HIPAA Agentic Orchestration Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for agentic orchestration but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'procurement RFP scoring', 'clinical advisory board', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15101',
    name: 'BAA Coding Suggestion Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for coding suggestion but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'BAFO contract clause', 'FDA submission posture', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15102',
    name: 'Subprocessor Documentation Review Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for documentation review but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'HIPAA BAA', 'KLAS commentary', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15103',
    name: 'AI Privacy Vendor Comparison Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for vendor comparison but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'minimum necessary policy', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15104',
    name: 'Minimum Necessary Capacity Forecasting Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for capacity forecasting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'TJC survey evidence', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15105',
    name: 'HIPAA Staffing Optimization Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for staffing optimization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'CMS CoP', 'AWS HealthLake', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15106',
    name: 'BAA Quality Abstraction Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for quality abstraction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'NCQA HEDIS audit', 'Azure Health Data Services', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15107',
    name: 'Subprocessor Patient Outreach Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for patient outreach but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'FDA SaMD guidance', 'Snowflake Healthcare', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15108',
    name: 'AI Privacy Triage Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for triage but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'NIST AI RMF', 'Databricks Lakehouse', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15109',
    name: 'Minimum Necessary Drafting Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for drafting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'ONC HTI-1', 'ServiceNow workflow', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15110',
    name: 'HIPAA Summarization Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for summarization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'TEFCA participation', 'Salesforce Health Cloud', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15111',
    name: 'BAA Risk Scoring Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for risk scoring but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'FHIR R4 mapping', 'startup maturity evidence', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15112',
    name: 'Subprocessor Worklist Prioritization Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for worklist prioritization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'HL7 v2 ADT reconciliation', 'SOC 2 Type II', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15113',
    name: 'AI Privacy Appeal Generation Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for appeal generation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'Epic change control', 'HITRUST roadmap', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15114',
    name: 'Minimum Necessary Order Recommendation Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for order recommendation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'model registry', 'Series B burn rate', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15115',
    name: 'HIPAA Benefit Verification Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for benefit verification but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'deployment-site validation', 'implementation partner capacity', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15116',
    name: 'BAA Eligibility Prediction Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for eligibility prediction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'MLOps monitoring', 'referenceable health-system customer', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15117',
    name: 'Subprocessor Care Gap Closure Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for care gap closure but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'clinical safety review', 'clinical advisory board', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15118',
    name: 'AI Privacy Cohort Matching Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for cohort matching but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'procurement RFP scoring', 'FDA submission posture', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15119',
    name: 'Minimum Necessary Contract Analysis Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for contract analysis but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'BAFO contract clause', 'KLAS commentary', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15120',
    name: 'HIPAA Agentic Orchestration Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for agentic orchestration but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'HIPAA BAA', 'Epic App Orchard integration', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15121',
    name: 'BAA Coding Suggestion Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for coding suggestion but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'minimum necessary policy', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15122',
    name: 'Subprocessor Documentation Review Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for documentation review but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'TJC survey evidence', 'AWS HealthLake', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15123',
    name: 'AI Privacy Vendor Comparison Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for vendor comparison but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'CMS CoP', 'Azure Health Data Services', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15124',
    name: 'Minimum Necessary Capacity Forecasting Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for capacity forecasting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'NCQA HEDIS audit', 'Snowflake Healthcare', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15125',
    name: 'HIPAA Staffing Optimization Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for staffing optimization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'FDA SaMD guidance', 'Databricks Lakehouse', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15126',
    name: 'BAA Quality Abstraction Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for quality abstraction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'NIST AI RMF', 'ServiceNow workflow', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15127',
    name: 'Subprocessor Patient Outreach Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for patient outreach but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'ONC HTI-1', 'Salesforce Health Cloud', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15128',
    name: 'AI Privacy Triage Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for triage but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'TEFCA participation', 'startup maturity evidence', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15129',
    name: 'Minimum Necessary Drafting Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for drafting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'FHIR R4 mapping', 'SOC 2 Type II', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15130',
    name: 'HIPAA Summarization Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for summarization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'HL7 v2 ADT reconciliation', 'HITRUST roadmap', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15131',
    name: 'BAA Risk Scoring Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for risk scoring but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'Epic change control', 'Series B burn rate', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15132',
    name: 'Subprocessor Worklist Prioritization Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for worklist prioritization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'model registry', 'implementation partner capacity', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15133',
    name: 'AI Privacy Appeal Generation Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for appeal generation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'deployment-site validation', 'referenceable health-system customer', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15134',
    name: 'Minimum Necessary Order Recommendation Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for order recommendation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'MLOps monitoring', 'clinical advisory board', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15135',
    name: 'HIPAA Benefit Verification Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for benefit verification but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'clinical safety review', 'FDA submission posture', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15136',
    name: 'BAA Eligibility Prediction Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for eligibility prediction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'procurement RFP scoring', 'KLAS commentary', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15137',
    name: 'Subprocessor Care Gap Closure Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for care gap closure but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'BAFO contract clause', 'Epic App Orchard integration', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15138',
    name: 'AI Privacy Cohort Matching Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for cohort matching but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'HIPAA BAA', 'Microsoft Cloud for Healthcare', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15139',
    name: 'Minimum Necessary Contract Analysis Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for contract analysis but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'minimum necessary policy', 'AWS HealthLake', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15140',
    name: 'HIPAA Agentic Orchestration Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for agentic orchestration but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'TJC survey evidence', 'Azure Health Data Services', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15141',
    name: 'BAA Coding Suggestion Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for coding suggestion but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'CMS CoP', 'Snowflake Healthcare', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15142',
    name: 'Subprocessor Documentation Review Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for documentation review but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'NCQA HEDIS audit', 'Databricks Lakehouse', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15143',
    name: 'AI Privacy Vendor Comparison Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for vendor comparison but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'FDA SaMD guidance', 'ServiceNow workflow', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15144',
    name: 'Minimum Necessary Capacity Forecasting Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for capacity forecasting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'NIST AI RMF', 'Salesforce Health Cloud', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15145',
    name: 'HIPAA Staffing Optimization Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 60,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when HIPAA is used for staffing optimization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when subprocessor is not proven in production.`,
    keywords: ['HIPAA', 'subprocessor', 'ONC HTI-1', 'startup maturity evidence', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15146',
    name: 'BAA Quality Abstraction Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when BAA is used for quality abstraction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when AI privacy is not proven in production.`,
    keywords: ['BAA', 'AI privacy', 'TEFCA participation', 'SOC 2 Type II', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15147',
    name: 'Subprocessor Patient Outreach Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when subprocessor is used for patient outreach but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when minimum necessary is not proven in production.`,
    keywords: ['subprocessor', 'minimum necessary', 'FHIR R4 mapping', 'HITRUST roadmap', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15148',
    name: 'AI Privacy Triage Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when AI privacy is used for triage but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when HIPAA is not proven in production.`,
    keywords: ['AI privacy', 'HIPAA', 'HL7 v2 ADT reconciliation', 'Series B burn rate', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  },
  {
    code: 'H15149',
    name: 'Minimum Necessary Drafting Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Compliance, Privacy, HIPAA & BAA AI Controls initiatives fail when minimum necessary is used for drafting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when BAA is not proven in production.`,
    keywords: ['minimum necessary', 'BAA', 'Epic change control', 'implementation partner capacity', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Compliance, Privacy, HIPAA & BAA AI Controls',
  }
];
