/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 47: Behavioral Health AI & Digital Therapeutics
// Part 1: H13200-H13249
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM47_PART1_PATTERNS = [
  {
    code: 'H13200',
    name: 'Behavioral Health AI Documentation Review Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for documentation review but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'clinical safety review', 'Databricks Lakehouse', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13201',
    name: 'Digital Therapeutics Vendor Comparison Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for vendor comparison but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'procurement RFP scoring', 'ServiceNow workflow', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13202',
    name: 'Suicide Risk Capacity Forecasting Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for capacity forecasting but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'BAFO contract clause', 'Salesforce Health Cloud', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13203',
    name: '42 CFR Part 2 Staffing Optimization Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for staffing optimization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'HIPAA BAA', 'startup maturity evidence', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13204',
    name: 'Telepsychiatry Quality Abstraction Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for quality abstraction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'minimum necessary policy', 'SOC 2 Type II', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13205',
    name: 'Behavioral Health AI Patient Outreach Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for patient outreach but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'TJC survey evidence', 'HITRUST roadmap', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13206',
    name: 'Digital Therapeutics Triage Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for triage but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'CMS CoP', 'Series B burn rate', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13207',
    name: 'Suicide Risk Drafting Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for drafting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'NCQA HEDIS audit', 'implementation partner capacity', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13208',
    name: '42 CFR Part 2 Summarization Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for summarization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'FDA SaMD guidance', 'referenceable health-system customer', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13209',
    name: 'Telepsychiatry Risk Scoring Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for risk scoring but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'NIST AI RMF', 'clinical advisory board', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13210',
    name: 'Behavioral Health AI Worklist Prioritization Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for worklist prioritization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'ONC HTI-1', 'FDA submission posture', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13211',
    name: 'Digital Therapeutics Appeal Generation Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for appeal generation but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'TEFCA participation', 'KLAS commentary', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13212',
    name: 'Suicide Risk Order Recommendation Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for order recommendation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'FHIR R4 mapping', 'Epic App Orchard integration', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13213',
    name: '42 CFR Part 2 Benefit Verification Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for benefit verification but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'HL7 v2 ADT reconciliation', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13214',
    name: 'Telepsychiatry Eligibility Prediction Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for eligibility prediction but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'Epic change control', 'AWS HealthLake', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13215',
    name: 'Behavioral Health AI Care Gap Closure Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for care gap closure but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'model registry', 'Azure Health Data Services', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13216',
    name: 'Digital Therapeutics Cohort Matching Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for cohort matching but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'deployment-site validation', 'Snowflake Healthcare', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13217',
    name: 'Suicide Risk Contract Analysis Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for contract analysis but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'MLOps monitoring', 'Databricks Lakehouse', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13218',
    name: '42 CFR Part 2 Agentic Orchestration Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for agentic orchestration but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'clinical safety review', 'ServiceNow workflow', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13219',
    name: 'Telepsychiatry Coding Suggestion Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for coding suggestion but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'procurement RFP scoring', 'Salesforce Health Cloud', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13220',
    name: 'Behavioral Health AI Documentation Review Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for documentation review but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'BAFO contract clause', 'startup maturity evidence', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13221',
    name: 'Digital Therapeutics Vendor Comparison Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for vendor comparison but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'HIPAA BAA', 'SOC 2 Type II', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13222',
    name: 'Suicide Risk Capacity Forecasting Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for capacity forecasting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'minimum necessary policy', 'HITRUST roadmap', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13223',
    name: '42 CFR Part 2 Staffing Optimization Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for staffing optimization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'TJC survey evidence', 'Series B burn rate', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13224',
    name: 'Telepsychiatry Quality Abstraction Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for quality abstraction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'CMS CoP', 'implementation partner capacity', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13225',
    name: 'Behavioral Health AI Patient Outreach Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for patient outreach but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'NCQA HEDIS audit', 'referenceable health-system customer', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13226',
    name: 'Digital Therapeutics Triage Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for triage but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'FDA SaMD guidance', 'clinical advisory board', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13227',
    name: 'Suicide Risk Drafting Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for drafting but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'NIST AI RMF', 'FDA submission posture', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13228',
    name: '42 CFR Part 2 Summarization Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 54,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for summarization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'ONC HTI-1', 'KLAS commentary', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13229',
    name: 'Telepsychiatry Risk Scoring Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for risk scoring but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'TEFCA participation', 'Epic App Orchard integration', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13230',
    name: 'Behavioral Health AI Worklist Prioritization Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for worklist prioritization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'FHIR R4 mapping', 'Microsoft Cloud for Healthcare', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13231',
    name: 'Digital Therapeutics Appeal Generation Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for appeal generation but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'HL7 v2 ADT reconciliation', 'AWS HealthLake', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13232',
    name: 'Suicide Risk Order Recommendation Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for order recommendation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'Epic change control', 'Azure Health Data Services', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13233',
    name: '42 CFR Part 2 Benefit Verification Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for benefit verification but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'model registry', 'Snowflake Healthcare', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13234',
    name: 'Telepsychiatry Eligibility Prediction Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for eligibility prediction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'deployment-site validation', 'Databricks Lakehouse', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13235',
    name: 'Behavioral Health AI Care Gap Closure Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for care gap closure but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'MLOps monitoring', 'ServiceNow workflow', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13236',
    name: 'Digital Therapeutics Cohort Matching Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 83,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for cohort matching but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'clinical safety review', 'Salesforce Health Cloud', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13237',
    name: 'Suicide Risk Contract Analysis Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for contract analysis but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'procurement RFP scoring', 'startup maturity evidence', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13238',
    name: '42 CFR Part 2 Agentic Orchestration Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 56,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for agentic orchestration but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'BAFO contract clause', 'SOC 2 Type II', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13239',
    name: 'Telepsychiatry Coding Suggestion Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 79,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for coding suggestion but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'HIPAA BAA', 'HITRUST roadmap', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13240',
    name: 'Behavioral Health AI Documentation Review Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for documentation review but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'minimum necessary policy', 'Series B burn rate', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13241',
    name: 'Digital Therapeutics Vendor Comparison Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for vendor comparison but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'TJC survey evidence', 'implementation partner capacity', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13242',
    name: 'Suicide Risk Capacity Forecasting Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for capacity forecasting but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'CMS CoP', 'referenceable health-system customer', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13243',
    name: '42 CFR Part 2 Staffing Optimization Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for staffing optimization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'NCQA HEDIS audit', 'clinical advisory board', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13244',
    name: 'Telepsychiatry Quality Abstraction Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for quality abstraction but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'FDA SaMD guidance', 'FDA submission posture', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13245',
    name: 'Behavioral Health AI Patient Outreach Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 79,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when behavioral health AI is used for patient outreach but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when suicide risk is not proven in production.`,
    keywords: ['behavioral health AI', 'suicide risk', 'NIST AI RMF', 'KLAS commentary', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13246',
    name: 'Digital Therapeutics Triage Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when digital therapeutics is used for triage but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when 42 CFR Part 2 is not proven in production.`,
    keywords: ['digital therapeutics', '42 CFR Part 2', 'ONC HTI-1', 'Epic App Orchard integration', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13247',
    name: 'Suicide Risk Drafting Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when suicide risk is used for drafting but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when telepsychiatry is not proven in production.`,
    keywords: ['suicide risk', 'telepsychiatry', 'TEFCA participation', 'Microsoft Cloud for Healthcare', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13248',
    name: '42 CFR Part 2 Summarization Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 77,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when 42 CFR Part 2 is used for summarization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when behavioral health AI is not proven in production.`,
    keywords: ['42 CFR Part 2', 'behavioral health AI', 'FHIR R4 mapping', 'AWS HealthLake', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  },
  {
    code: 'H13249',
    name: 'Telepsychiatry Risk Scoring Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Behavioral Health AI & Digital Therapeutics initiatives fail when telepsychiatry is used for risk scoring but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when digital therapeutics is not proven in production.`,
    keywords: ['telepsychiatry', 'digital therapeutics', 'HL7 v2 ADT reconciliation', 'Azure Health Data Services', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Behavioral Health AI & Digital Therapeutics',
  }
];
