/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 41: Pathology, Lab & Genomics AI
// Part 2: H12050-H12099
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM41_PART2_PATTERNS = [
  {
    code: 'H12050',
    name: 'Pathology AI Agentic Orchestration Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for agentic orchestration but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is Epic change control: AbarVa should turn this into a Moves adoption plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'Epic change control', 'startup maturity evidence', 'adoption plan', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12051',
    name: 'LIS Coding Suggestion Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for coding suggestion but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is model registry: AbarVa should turn this into a Moves pre-mortem risk and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'model registry', 'SOC 2 Type II', 'pre-mortem risk', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12052',
    name: 'CLIA Documentation Review Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for documentation review but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves dependency map and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'deployment-site validation', 'HITRUST roadmap', 'dependency map', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12053',
    name: 'Genomics Vendor Comparison Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for vendor comparison but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves approval gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'MLOps monitoring', 'Series B burn rate', 'approval gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12054',
    name: 'Variant Interpretation Capacity Forecasting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 84,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for capacity forecasting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is clinical safety review: AbarVa should turn this into a Moves benefit validation plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'clinical safety review', 'implementation partner capacity', 'benefit validation plan', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12055',
    name: 'Pathology AI Staffing Optimization Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for staffing optimization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'procurement RFP scoring', 'referenceable health-system customer', 'unsafe-to-fund gate', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12056',
    name: 'LIS Quality Abstraction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for quality abstraction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves value realization ledger and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'BAFO contract clause', 'clinical advisory board', 'value realization ledger', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12057',
    name: 'CLIA Patient Outreach Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for patient outreach but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves pilot success metric and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'HIPAA BAA', 'FDA submission posture', 'pilot success metric', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12058',
    name: 'Genomics Triage Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for triage but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves clinical governance checklist and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'minimum necessary policy', 'KLAS commentary', 'clinical governance checklist', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12059',
    name: 'Variant Interpretation Drafting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for drafting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves adoption plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'TJC survey evidence', 'Epic App Orchard integration', 'adoption plan', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12060',
    name: 'Pathology AI Summarization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for summarization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pre-mortem risk and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'CMS CoP', 'Microsoft Cloud for Healthcare', 'pre-mortem risk', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12061',
    name: 'LIS Risk Scoring Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for risk scoring but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves dependency map and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'NCQA HEDIS audit', 'AWS HealthLake', 'dependency map', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12062',
    name: 'CLIA Worklist Prioritization Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for worklist prioritization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves approval gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'FDA SaMD guidance', 'Azure Health Data Services', 'approval gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12063',
    name: 'Genomics Appeal Generation Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for appeal generation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves benefit validation plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'NIST AI RMF', 'Snowflake Healthcare', 'benefit validation plan', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12064',
    name: 'Variant Interpretation Order Recommendation Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for order recommendation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'ONC HTI-1', 'Databricks Lakehouse', 'unsafe-to-fund gate', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12065',
    name: 'Pathology AI Benefit Verification Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for benefit verification but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves value realization ledger and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'TEFCA participation', 'ServiceNow workflow', 'value realization ledger', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12066',
    name: 'LIS Eligibility Prediction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for eligibility prediction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves pilot success metric and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'FHIR R4 mapping', 'Salesforce Health Cloud', 'pilot success metric', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12067',
    name: 'CLIA Care Gap Closure Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for care gap closure but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves clinical governance checklist and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'HL7 v2 ADT reconciliation', 'startup maturity evidence', 'clinical governance checklist', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12068',
    name: 'Genomics Cohort Matching Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for cohort matching but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is Epic change control: AbarVa should turn this into a Moves adoption plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'Epic change control', 'SOC 2 Type II', 'adoption plan', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12069',
    name: 'Variant Interpretation Contract Analysis Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for contract analysis but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is model registry: AbarVa should turn this into a Moves pre-mortem risk and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'model registry', 'HITRUST roadmap', 'pre-mortem risk', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12070',
    name: 'Pathology AI Agentic Orchestration Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for agentic orchestration but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves dependency map and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'deployment-site validation', 'Series B burn rate', 'dependency map', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12071',
    name: 'LIS Coding Suggestion Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for coding suggestion but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves approval gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'MLOps monitoring', 'implementation partner capacity', 'approval gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12072',
    name: 'CLIA Documentation Review Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for documentation review but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves benefit validation plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'clinical safety review', 'referenceable health-system customer', 'benefit validation plan', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12073',
    name: 'Genomics Vendor Comparison Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for vendor comparison but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'procurement RFP scoring', 'clinical advisory board', 'unsafe-to-fund gate', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12074',
    name: 'Variant Interpretation Capacity Forecasting Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for capacity forecasting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves value realization ledger and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'BAFO contract clause', 'FDA submission posture', 'value realization ledger', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12075',
    name: 'Pathology AI Staffing Optimization Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for staffing optimization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves pilot success metric and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'HIPAA BAA', 'KLAS commentary', 'pilot success metric', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12076',
    name: 'LIS Quality Abstraction Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for quality abstraction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves clinical governance checklist and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'minimum necessary policy', 'Epic App Orchard integration', 'clinical governance checklist', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12077',
    name: 'CLIA Patient Outreach Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for patient outreach but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves adoption plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'TJC survey evidence', 'Microsoft Cloud for Healthcare', 'adoption plan', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12078',
    name: 'Genomics Triage Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for triage but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pre-mortem risk and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'CMS CoP', 'AWS HealthLake', 'pre-mortem risk', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12079',
    name: 'Variant Interpretation Drafting Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for drafting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves dependency map and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'NCQA HEDIS audit', 'Azure Health Data Services', 'dependency map', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12080',
    name: 'Pathology AI Summarization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for summarization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves approval gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'FDA SaMD guidance', 'Snowflake Healthcare', 'approval gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12081',
    name: 'LIS Risk Scoring Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for risk scoring but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves benefit validation plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'NIST AI RMF', 'Databricks Lakehouse', 'benefit validation plan', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12082',
    name: 'CLIA Worklist Prioritization Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for worklist prioritization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'ONC HTI-1', 'ServiceNow workflow', 'unsafe-to-fund gate', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12083',
    name: 'Genomics Appeal Generation Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for appeal generation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves value realization ledger and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'TEFCA participation', 'Salesforce Health Cloud', 'value realization ledger', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12084',
    name: 'Variant Interpretation Order Recommendation Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for order recommendation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves pilot success metric and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'FHIR R4 mapping', 'startup maturity evidence', 'pilot success metric', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12085',
    name: 'Pathology AI Benefit Verification Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for benefit verification but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves clinical governance checklist and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'HL7 v2 ADT reconciliation', 'SOC 2 Type II', 'clinical governance checklist', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12086',
    name: 'LIS Eligibility Prediction Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for eligibility prediction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is Epic change control: AbarVa should turn this into a Moves adoption plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'Epic change control', 'HITRUST roadmap', 'adoption plan', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12087',
    name: 'CLIA Care Gap Closure Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for care gap closure but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is model registry: AbarVa should turn this into a Moves pre-mortem risk and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'model registry', 'Series B burn rate', 'pre-mortem risk', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12088',
    name: 'Genomics Cohort Matching Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for cohort matching but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves dependency map and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'deployment-site validation', 'implementation partner capacity', 'dependency map', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12089',
    name: 'Variant Interpretation Contract Analysis Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for contract analysis but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves approval gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'MLOps monitoring', 'referenceable health-system customer', 'approval gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12090',
    name: 'Pathology AI Agentic Orchestration Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for agentic orchestration but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is clinical safety review: AbarVa should turn this into a Moves benefit validation plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'clinical safety review', 'clinical advisory board', 'benefit validation plan', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12091',
    name: 'LIS Coding Suggestion Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for coding suggestion but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'procurement RFP scoring', 'FDA submission posture', 'unsafe-to-fund gate', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12092',
    name: 'CLIA Documentation Review Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for documentation review but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves value realization ledger and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'BAFO contract clause', 'KLAS commentary', 'value realization ledger', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12093',
    name: 'Genomics Vendor Comparison Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for vendor comparison but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves pilot success metric and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'HIPAA BAA', 'Epic App Orchard integration', 'pilot success metric', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12094',
    name: 'Variant Interpretation Capacity Forecasting Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for capacity forecasting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves clinical governance checklist and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'minimum necessary policy', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12095',
    name: 'Pathology AI Staffing Optimization Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Pathology, Lab & Genomics AI initiatives fail when pathology AI is used for staffing optimization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves adoption plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when CLIA is not proven in production.`,
    keywords: ['pathology AI', 'CLIA', 'TJC survey evidence', 'AWS HealthLake', 'adoption plan', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12096',
    name: 'LIS Quality Abstraction Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Pathology, Lab & Genomics AI initiatives fail when LIS is used for quality abstraction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pre-mortem risk and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when genomics is not proven in production.`,
    keywords: ['LIS', 'genomics', 'CMS CoP', 'Azure Health Data Services', 'pre-mortem risk', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12097',
    name: 'CLIA Patient Outreach Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Pathology, Lab & Genomics AI initiatives fail when CLIA is used for patient outreach but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves dependency map and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when variant interpretation is not proven in production.`,
    keywords: ['CLIA', 'variant interpretation', 'NCQA HEDIS audit', 'Snowflake Healthcare', 'dependency map', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12098',
    name: 'Genomics Triage Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Pathology, Lab & Genomics AI initiatives fail when genomics is used for triage but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves approval gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when pathology AI is not proven in production.`,
    keywords: ['genomics', 'pathology AI', 'FDA SaMD guidance', 'Databricks Lakehouse', 'approval gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  },
  {
    code: 'H12099',
    name: 'Variant Interpretation Drafting Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Pathology, Lab & Genomics AI initiatives fail when variant interpretation is used for drafting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves benefit validation plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when LIS is not proven in production.`,
    keywords: ['variant interpretation', 'LIS', 'NIST AI RMF', 'ServiceNow workflow', 'benefit validation plan', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Pathology, Lab & Genomics AI',
  }
];
