/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 34: Revenue Cycle Automation & Denial AI
// Part 2: H10650-H10699
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM34_PART2_PATTERNS = [
  {
    code: 'H10650',
    name: 'Denial AI Quality Abstraction Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for quality abstraction but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'TEFCA participation', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10651',
    name: 'Claim Scrubber Patient Outreach Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for patient outreach but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'FHIR R4 mapping', 'startup maturity evidence', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10652',
    name: '835 Remittance Triage Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for triage but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'HL7 v2 ADT reconciliation', 'SOC 2 Type II', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10653',
    name: 'RCM Automation Drafting Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for drafting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is Epic change control: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'Epic change control', 'HITRUST roadmap', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10654',
    name: 'Appeal Workflow Summarization Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for summarization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is model registry: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'model registry', 'Series B burn rate', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10655',
    name: 'Denial AI Risk Scoring Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for risk scoring but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'deployment-site validation', 'implementation partner capacity', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10656',
    name: 'Claim Scrubber Worklist Prioritization Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for worklist prioritization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'MLOps monitoring', 'referenceable health-system customer', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10657',
    name: '835 Remittance Appeal Generation Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for appeal generation but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'clinical safety review', 'clinical advisory board', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10658',
    name: 'RCM Automation Order Recommendation Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for order recommendation but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'procurement RFP scoring', 'FDA submission posture', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10659',
    name: 'Appeal Workflow Benefit Verification Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for benefit verification but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'BAFO contract clause', 'KLAS commentary', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10660',
    name: 'Denial AI Eligibility Prediction Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for eligibility prediction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'HIPAA BAA', 'Epic App Orchard integration', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10661',
    name: 'Claim Scrubber Care Gap Closure Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for care gap closure but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'minimum necessary policy', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10662',
    name: '835 Remittance Cohort Matching Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for cohort matching but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'TJC survey evidence', 'AWS HealthLake', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10663',
    name: 'RCM Automation Contract Analysis Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for contract analysis but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'CMS CoP', 'Azure Health Data Services', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10664',
    name: 'Appeal Workflow Agentic Orchestration Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for agentic orchestration but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'NCQA HEDIS audit', 'Snowflake Healthcare', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10665',
    name: 'Denial AI Coding Suggestion Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for coding suggestion but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'FDA SaMD guidance', 'Databricks Lakehouse', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10666',
    name: 'Claim Scrubber Documentation Review Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for documentation review but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'NIST AI RMF', 'ServiceNow workflow', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10667',
    name: '835 Remittance Vendor Comparison Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for vendor comparison but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'ONC HTI-1', 'Salesforce Health Cloud', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10668',
    name: 'RCM Automation Capacity Forecasting Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for capacity forecasting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'TEFCA participation', 'startup maturity evidence', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10669',
    name: 'Appeal Workflow Staffing Optimization Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for staffing optimization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'FHIR R4 mapping', 'SOC 2 Type II', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10670',
    name: 'Denial AI Quality Abstraction Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for quality abstraction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'HL7 v2 ADT reconciliation', 'HITRUST roadmap', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10671',
    name: 'Claim Scrubber Patient Outreach Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for patient outreach but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'Epic change control', 'Series B burn rate', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10672',
    name: '835 Remittance Triage Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for triage but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'model registry', 'implementation partner capacity', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10673',
    name: 'RCM Automation Drafting Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for drafting but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'deployment-site validation', 'referenceable health-system customer', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10674',
    name: 'Appeal Workflow Summarization Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for summarization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'MLOps monitoring', 'clinical advisory board', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10675',
    name: 'Denial AI Risk Scoring Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for risk scoring but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'clinical safety review', 'FDA submission posture', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10676',
    name: 'Claim Scrubber Worklist Prioritization Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for worklist prioritization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'procurement RFP scoring', 'KLAS commentary', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10677',
    name: '835 Remittance Appeal Generation Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for appeal generation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'BAFO contract clause', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10678',
    name: 'RCM Automation Order Recommendation Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for order recommendation but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'HIPAA BAA', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10679',
    name: 'Appeal Workflow Benefit Verification Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for benefit verification but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'minimum necessary policy', 'AWS HealthLake', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10680',
    name: 'Denial AI Eligibility Prediction Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for eligibility prediction but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'TJC survey evidence', 'Azure Health Data Services', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10681',
    name: 'Claim Scrubber Care Gap Closure Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for care gap closure but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'CMS CoP', 'Snowflake Healthcare', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10682',
    name: '835 Remittance Cohort Matching Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for cohort matching but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'NCQA HEDIS audit', 'Databricks Lakehouse', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10683',
    name: 'RCM Automation Contract Analysis Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for contract analysis but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'FDA SaMD guidance', 'ServiceNow workflow', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10684',
    name: 'Appeal Workflow Agentic Orchestration Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for agentic orchestration but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'NIST AI RMF', 'Salesforce Health Cloud', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10685',
    name: 'Denial AI Coding Suggestion Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for coding suggestion but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'ONC HTI-1', 'startup maturity evidence', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10686',
    name: 'Claim Scrubber Documentation Review Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for documentation review but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'TEFCA participation', 'SOC 2 Type II', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10687',
    name: '835 Remittance Vendor Comparison Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for vendor comparison but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'FHIR R4 mapping', 'HITRUST roadmap', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10688',
    name: 'RCM Automation Capacity Forecasting Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for capacity forecasting but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'HL7 v2 ADT reconciliation', 'Series B burn rate', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10689',
    name: 'Appeal Workflow Staffing Optimization Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for staffing optimization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is Epic change control: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'Epic change control', 'implementation partner capacity', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10690',
    name: 'Denial AI Quality Abstraction Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for quality abstraction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is model registry: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'model registry', 'referenceable health-system customer', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10691',
    name: 'Claim Scrubber Patient Outreach Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for patient outreach but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'deployment-site validation', 'clinical advisory board', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10692',
    name: '835 Remittance Triage Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for triage but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'MLOps monitoring', 'FDA submission posture', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10693',
    name: 'RCM Automation Drafting Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for drafting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is clinical safety review: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'clinical safety review', 'KLAS commentary', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10694',
    name: 'Appeal Workflow Summarization Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for summarization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'procurement RFP scoring', 'Epic App Orchard integration', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10695',
    name: 'Denial AI Risk Scoring Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when denial AI is used for risk scoring but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when 835 remittance is not proven in production.`,
    keywords: ['denial AI', '835 remittance', 'BAFO contract clause', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10696',
    name: 'Claim Scrubber Worklist Prioritization Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when claim scrubber is used for worklist prioritization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when RCM automation is not proven in production.`,
    keywords: ['claim scrubber', 'RCM automation', 'HIPAA BAA', 'AWS HealthLake', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10697',
    name: '835 Remittance Appeal Generation Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when 835 remittance is used for appeal generation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when appeal workflow is not proven in production.`,
    keywords: ['835 remittance', 'appeal workflow', 'minimum necessary policy', 'Azure Health Data Services', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10698',
    name: 'RCM Automation Order Recommendation Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when RCM automation is used for order recommendation but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when denial AI is not proven in production.`,
    keywords: ['RCM automation', 'denial AI', 'TJC survey evidence', 'Snowflake Healthcare', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  },
  {
    code: 'H10699',
    name: 'Appeal Workflow Benefit Verification Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Revenue Cycle Automation & Denial AI initiatives fail when appeal workflow is used for benefit verification but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is CMS CoP: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when claim scrubber is not proven in production.`,
    keywords: ['appeal workflow', 'claim scrubber', 'CMS CoP', 'Databricks Lakehouse', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Revenue Cycle Automation & Denial AI',
  }
];
