interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const MEDTECH_DOM01_FDA_REGULATORY_PART7_PATTERNS: PatternSeed[] = [

  // ── PMA Supplement Strategy (M450–M461) ──────────────────────────────────

  {
    code: 'M450',
    name: 'PMA Supplement Type Misclassification Between Panel-Track and 180-Day Submissions',
    description: 'A medtech manufacturer submits a 180-day PMA supplement for a device change that materially affects safety or effectiveness, when FDA guidance requires a panel-track supplement, resulting in automatic deficiency and review delay.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['pma-supplement', 'panel-track', '180-day', 'supplement-type', 'fda-guidance'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Supplement type selected without applying the FDA PMA supplement type decision matrix to the specific change.',
      regulatoryHook: '21 CFR 814.39; FDA Guidance on PMA Supplement Decision-Making',
      detectionMethod: 'Pre-submission meeting transcript review against proposed supplement classification.',
      remediationPath: 'Request pre-submission meeting with FDA to confirm supplement type before filing.',
      estimatedCost: '$150K–$400K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '38% of PMA supplements receive an incomplete or deficiency letter within 15 days of filing.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M451',
    name: '30-Day Notice Submitted for Change Requiring Full PMA Supplement',
    description: `A device manufacturer uses a 30-day notice for a manufacturing process change that alters a device's performance specification, a change FDA has indicated warrants a PMA supplement under 21 CFR 814.39(f).`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['30-day-notice', 'pma-supplement', 'manufacturing-change', '21-cfr-814', 'fda-enforcement'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Regulatory team applied 30-day notice pathway to a change affecting labeled performance without documented justification.',
      regulatoryHook: '21 CFR 814.39(f); FDA Guidance for PMA Supplements and Annual Reports',
      detectionMethod: 'Change control record audit comparing change classification against 30-day notice eligibility criteria.',
      remediationPath: 'Withdraw 30-day notice and file appropriate PMA supplement; conduct retrospective change control review.',
      estimatedCost: '$200K–$600K',
      timeToRemediate: '4–10 months',
      industryBenchmark: '29% of 30-day notices are converted to PMA supplements after FDA review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M452',
    name: 'PMA Annual Report Missing Required Design Change Documentation',
    description: 'A manufacturer includes changes in a PMA annual report that exceed the scope permitted under 21 CFR 814.84, specifically design changes affecting device performance that require a separate supplement.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['pma-annual-report', 'design-change', '21-cfr-814-84', 'supplement-threshold', 'fda-review'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Annual report included design modifications without determining whether each change required a separate supplement.',
      regulatoryHook: '21 CFR 814.84; FDA Guidance for Annual Reports for Approved PMAs',
      detectionMethod: 'Annual report content audit against change control records and supplement threshold criteria.',
      remediationPath: 'File retroactive PMA supplements for out-of-scope changes; update SOP for annual report content gating.',
      estimatedCost: '$100K–$350K',
      timeToRemediate: '3–9 months',
      industryBenchmark: '22% of PMA holders receive FDA information requests following annual report submission.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M453',
    name: 'Real-Time PMA Supplement Trigger Criteria Not Embedded in Change Control SOP',
    description: 'A manufacturer lacks documented criteria in its change control SOP to identify when a change qualifies for the real-time PMA supplement pathway, causing inappropriate use of longer-cycle supplement types for time-sensitive device improvements.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['real-time-supplement', 'change-control', 'sop', 'pma', 'supplement-strategy'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Change control SOP does not include a real-time supplement eligibility checklist, delaying approval of safety improvements.',
      regulatoryHook: '21 CFR 814.39(d); FDA Real-Time PMA Supplement Guidance',
      detectionMethod: 'SOP gap analysis against FDA real-time supplement eligibility criteria list.',
      remediationPath: 'Revise change control SOP to embed real-time supplement decision tree; train regulatory affairs staff.',
      estimatedCost: '$40K–$120K',
      timeToRemediate: '1–3 months',
      industryBenchmark: 'Only 11% of eligible changes are submitted via the real-time supplement pathway.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M454',
    name: 'Post-Approval Study Protocol Deviations Not Reported as Required Supplement',
    description: 'A PMA holder conducts a post-approval study under 21 CFR 814.82 and implements protocol amendments without submitting them as PMA supplements, violating post-approval conditions.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['post-approval-study', 'pma-supplement', '21-cfr-814-82', 'protocol-deviation', 'fda-conditions'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Protocol amendments implemented during post-approval study without FDA notification or supplement filing.',
      regulatoryHook: '21 CFR 814.82(a)(2); PMA approval order post-approval study conditions',
      detectionMethod: 'Comparison of current study protocol against FDA-approved protocol in the PMA approval order.',
      remediationPath: 'File retrospective PMA supplement documenting protocol changes; disclose deviation in next study progress report.',
      estimatedCost: '$180K–$500K',
      timeToRemediate: '4–9 months',
      industryBenchmark: '34% of post-approval studies have unreported protocol amendments at time of FDA inspection.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M455',
    name: 'PMA Supplement Lacking Clinical Data for Expanded Indications',
    description: 'A manufacturer files a PMA supplement to expand device indications without including clinical data adequate to support the new use, leading to not-approvable action.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['pma-supplement', 'expanded-indications', 'clinical-data', 'not-approvable', 'fda-guidance'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Supplement filed for expanded indications relying on extrapolated bench data rather than clinical evidence specific to the new patient population.',
      regulatoryHook: '21 CFR 814.39; FDA Guidance on Expanded Access and Indications',
      detectionMethod: 'Regulatory strategy review comparing proposed clinical evidence package against FDA precedent for similar indication expansions.',
      remediationPath: 'Design prospective clinical study or meta-analysis; request pre-submission meeting to align with FDA on data requirements.',
      estimatedCost: '$500K–$2M',
      timeToRemediate: '12–36 months',
      industryBenchmark: '41% of indication-expansion PMA supplements receive not-approvable letters on first submission.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M456',
    name: 'PMA Supplement Filing Without Resolving Outstanding Post-Approval Conditions',
    description: `A manufacturer files a new PMA supplement while delinquent on post-approval study milestone reports, triggering FDA's discretion to refuse to file the new supplement.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['pma-supplement', 'post-approval-conditions', 'refuse-to-file', 'fda-discretion', 'milestone-report'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Regulatory team submitted new supplement without auditing open post-approval conditions that create filing risk.',
      regulatoryHook: '21 CFR 814.82; FDA PMA Refuse-to-File Criteria',
      detectionMethod: 'Post-approval conditions tracker reconciliation before each supplement filing.',
      remediationPath: 'Submit all overdue post-approval study reports; obtain FDA confirmation before filing new supplement.',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '17% of PMA holders have at least one overdue post-approval study report at any given time.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M457',
    name: 'Software Change to PMA Device Not Assessed Against OTS Software Guidance',
    description: 'A PMA device manufacturer implements a software update without applying the FDA OTS software guidance to determine whether the change requires a supplement.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['ots-software', 'software-change', 'pma-supplement', 'fda-guidance', 'samd'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Software update deployed without applying the five-step software change significance assessment from FDA guidance.',
      regulatoryHook: 'FDA Guidance: Deciding When to Submit a 510(k) for a Software Change; 21 CFR 814.39',
      detectionMethod: 'Software change record review for documented FDA significance flowchart determination.',
      remediationPath: 'Conduct retrospective significance assessment; file PMA supplement if change affects safety or effectiveness.',
      estimatedCost: '$120K–$400K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '46% of software-related PMA supplements follow undocumented changes that triggered FDA concern.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-driven algorithm updates to PMA devices may be deployed without supplement review under misclassified OTS software determination.',
    },
  },
  {
    code: 'M458',
    name: 'PMA Supplement Clinical Section Missing Adverse Event Reporting Context',
    description: 'A PMA supplement clinical section omits summarized MDR adverse event data relevant to the change being proposed, creating an incomplete safety narrative that FDA flags during review.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['pma-supplement', 'mdr', 'adverse-event', 'clinical-section', 'safety-narrative'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Supplement clinical section prepared without cross-referencing MDR complaint database for related adverse events.',
      regulatoryHook: '21 CFR 814.39; FDA Guidance on Content of Premarket Submissions',
      detectionMethod: 'Supplement clinical section peer review against MDR database extract for the device model.',
      remediationPath: 'Amend supplement clinical section to include MDR summary and contextual analysis.',
      estimatedCost: '$50K–$150K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '25% of PMA supplements receive FDA requests for additional MDR context during review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M459',
    name: 'Combination Product PMA Supplement Without CDER/CBER Coordination',
    description: 'A manufacturer of a drug-device combination product submits a PMA supplement for a device component change without coordinating with the lead center or the other FDA center, violating combination product cross-center review obligations.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['combination-product', 'pma-supplement', 'cder', 'cber', 'cross-center-review'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Supplement filed through CDRH only without triggering mandatory combination product cross-center consultation.',
      regulatoryHook: '21 CFR Part 3; FDA Combination Products Policy; 21 CFR 814.39',
      detectionMethod: 'Pre-submission meeting with OCP to confirm lead center assignment and cross-center review obligation.',
      remediationPath: 'File RFD with OCP; amend supplement to include drug/biologic component data and cross-center coordination plan.',
      estimatedCost: '$200K–$700K',
      timeToRemediate: '6–14 months',
      industryBenchmark: '31% of combination product submissions require RFD clarification before substantive review begins.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M460',
    name: 'PMA Supplement Labeling Section Inconsistent With Approved Indications',
    description: 'A manufacturer submits a PMA supplement with proposed labeling that expands the indications for use beyond those in the current approval without flagging this as an indication change requiring clinical support.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['pma-labeling', 'indications-for-use', 'labeling-inconsistency', 'pma-supplement', 'fda-review'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Proposed labeling draft added patient population language not supported by clinical evidence in the existing PMA.',
      regulatoryHook: '21 CFR 814.39; 21 CFR 801; FDA Labeling Guidance for Medical Devices',
      detectionMethod: 'Side-by-side redline comparison of proposed labeling against current approved labeling indications.',
      remediationPath: 'Revert labeling to approved indications or file separate indication expansion supplement with clinical data.',
      estimatedCost: '$60K–$200K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '19% of PMA supplements include labeling changes that FDA classifies as indication expansions requiring additional data.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M461',
    name: 'PMA Supplement Biocompatibility Data Outdated After Material Supplier Change',
    description: 'A manufacturer submits a PMA supplement reflecting a material supplier change without updating biocompatibility testing to the current ISO 10993-1:2018 standard, using data that FDA no longer considers adequate.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['biocompatibility', 'iso-10993', 'material-change', 'pma-supplement', 'fda-guidance'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'pma-supplement-strategy',
    data: {
      failureMode: 'Supplement referenced biocompatibility data generated under superseded ISO 10993-1:2009 without bridging justification.',
      regulatoryHook: '21 CFR 814.39; FDA Use of ISO 10993-1 Guidance (2020)',
      detectionMethod: 'Biocompatibility data package audit for ISO edition, test date, and material equivalence to changed supplier.',
      remediationPath: 'Commission updated biocompatibility testing under ISO 10993-1:2018 and include a risk-based evaluation summary.',
      estimatedCost: '$80K–$300K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '36% of material-change PMA supplements receive FDA requests for updated biocompatibility data.',
      aiInsertionRisk: false,
    },
  },

  // ── 510(k) / De Novo Advanced (M462–M473) ────────────────────────────────

  {
    code: 'M462',
    name: 'De Novo Request Submitted Without Meeting Valid Scientific Evidence Standard',
    description: 'A manufacturer files a de novo request for a Class III device reclassification to Class II without providing the valid scientific evidence required to demonstrate reasonable assurance of safety and effectiveness for the new device type.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['de-novo', 'valid-scientific-evidence', 'class-ii-reclassification', 'fda-guidance', '21-cfr-860'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'De novo submission relied on bench performance data alone without clinical evidence for a device with no predicate.',
      regulatoryHook: '21 CFR 860.260; FDA De Novo Classification Process Guidance (2021)',
      detectionMethod: 'Evidence gap analysis comparing submission data package against FDA de novo evidentiary standard checklist.',
      remediationPath: 'Design prospective clinical study or real-world evidence study; request pre-submission meeting to align with FDA.',
      estimatedCost: '$400K–$1.5M',
      timeToRemediate: '12–30 months',
      industryBenchmark: '44% of de novo requests receive not-substantially-equivalent or additional information requests on first submission.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI/ML-based novel devices seeking de novo classification frequently lack sufficient clinical evidence packages.',
    },
  },
  {
    code: 'M463',
    name: '510k Predicate Device Recalled or Withdrawn Post-Submission',
    description: 'A 510(k) submission relies on a predicate device that is recalled or withdrawn from the market after the submission is filed, invalidating the substantial equivalence argument without the submitter updating the filing.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['510k', 'predicate-recall', 'substantial-equivalence', 'fda-review', 'predicate-obsolescence'],
    failure_rate_pct: 40.0,
    is_active: true,
    demoRelevant: false,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Regulatory team did not monitor predicate device recall status during the 510(k) review cycle.',
      regulatoryHook: 'Section 513(i)(1)(A) of the FD&C Act; FDA Guidance on Substantial Equivalence',
      detectionMethod: 'Monthly predicate device status check against FDA recall database during active review.',
      remediationPath: 'Identify alternate predicate and amend submission or file new 510(k); notify FDA reviewer immediately.',
      estimatedCost: '$80K–$300K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '7% of 510(k) submissions are affected by predicate recall or market withdrawal during FDA review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M464',
    name: 'Comparative Summary in 510k Inadequate for Performance Characteristic Differences',
    description: `A 510(k) comparative summary fails to address technological differences between the subject device and predicate at the level of detail FDA requires, resulting in a deficiency letter requesting additional characterization.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['510k', 'comparative-summary', 'technological-characteristics', 'fda-deficiency', 'substantial-equivalence'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Comparative summary used generic performance claims without quantitative comparison for each technological difference.',
      regulatoryHook: 'Section 513(i) of the FD&C Act; FDA Guidance on Recommended Content and Format for 510(k)',
      detectionMethod: 'Comparative summary peer review against FDA 510(k) decision-making framework flowchart.',
      remediationPath: 'Revise comparative summary with quantitative performance data per technological characteristic; use tabular format.',
      estimatedCost: '$40K–$150K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '52% of 510(k) deficiency letters cite inadequate comparative summary as a primary deficiency.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M465',
    name: 'De Novo Special Controls Draft Insufficient to Mitigate Identified Risks',
    description: 'A de novo request includes proposed special controls that do not adequately mitigate the risks identified in the benefit-risk analysis, causing FDA to reject the classification proposal.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['de-novo', 'special-controls', 'risk-mitigation', 'benefit-risk', 'fda-classification'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Proposed special controls were generic performance testing requirements not mapped to specific device risks.',
      regulatoryHook: '21 CFR 860.260; FDA De Novo Classification Process Guidance; 21 CFR Part 880',
      detectionMethod: 'Risk-to-special-controls traceability matrix review against FDA precedent for analogous device types.',
      remediationPath: 'Develop device-specific special controls mapped to each identified hazard; reference comparable de novo orders.',
      estimatedCost: '$100K–$400K',
      timeToRemediate: '4–10 months',
      industryBenchmark: '37% of de novo requests require revision of proposed special controls before FDA issues the order.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M466',
    name: 'De Novo Order Implementation Incomplete Before Subsequent 510k Filing',
    description: 'A manufacturer cites a de novo order as a predicate in a 510(k) without confirming that the ordering manufacturer has fully implemented the special controls specified in the de novo order.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['de-novo-order', '510k-predicate', 'special-controls', 'implementation', 'substantial-equivalence'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: `510(k) submission cited de novo device as predicate without verifying the originating company's special controls compliance.`,
      regulatoryHook: 'Section 513(i)(1)(A) FD&C Act; FDA De Novo Classification Process Guidance',
      detectionMethod: `Review de novo order special controls and assess originating device's compliance documentation.`,
      remediationPath: 'Confirm full special controls implementation by predicate holder; document compliance assessment in 510(k) submission.',
      estimatedCost: '$30K–$100K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '14% of 510(k)s citing de novo predicates receive FDA questions about special controls compliance.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M467',
    name: '510k Submission Missing Cybersecurity Documentation Required by 2023 Guidance',
    description: 'A 510(k) for a network-connected device omits the cybersecurity information required under the 2023 FDA cybersecurity guidance, including the software bill of materials and security risk assessment.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['510k', 'cybersecurity', 'sbom', 'fda-2023-guidance', 'network-connected'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: `510(k) cybersecurity section prepared under pre-2023 framework without SBOM, threat model, or vulnerability assessment.`,
      regulatoryHook: `FDA Guidance: Cybersecurity in Medical Devices (2023); Section 524B of the FD&C Act`,
      detectionMethod: `Cybersecurity documentation checklist audit against FDA's 2023 guidance recommended content.`,
      remediationPath: `Engage cybersecurity subject-matter expert to build compliant SBOM, security risk assessment, and patch management plan.`,
      estimatedCost: '$100K–$350K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '61% of network-connected device 510(k)s received cybersecurity deficiency letters in 2024.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-enabled connected devices often lack transparent SBOM for the AI model component, creating a recurring cybersecurity gap.',
    },
  },
  {
    code: 'M468',
    name: `510k Substantial Equivalence Argument Undermined by New Intended Use Claim`,
    description: `A manufacturer adds a new clinical claim in device labeling that was not included in the predicate's indications for use, breaking the intended use equivalence required for 510(k) clearance.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['510k', 'intended-use', 'substantial-equivalence', 'labeling-claim', 'fda-deficiency'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: true,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Marketing-driven labeling additions introduced intended use language that differentiated the device from its predicate.',
      regulatoryHook: 'Section 513(i) of the FD&C Act; FDA Guidance on Indications for Use',
      detectionMethod: 'Intended use statement comparison between subject device draft labeling and predicate cleared labeling.',
      remediationPath: 'Revert indications to match predicate or file de novo request for expanded indications with supporting data.',
      estimatedCost: '$60K–$250K',
      timeToRemediate: '2–6 months',
      industryBenchmark: '23% of NSE decisions cite new intended use not present in the predicate as the primary basis.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M469',
    name: 'Abbreviated 510k Using Guidance Document With Expired Recognition Status',
    description: `A manufacturer submits an abbreviated 510(k) conforming to a recognized consensus standard that FDA has withdrawn from its list of recognized standards, invalidating the abbreviated pathway.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['abbreviated-510k', 'recognized-standards', 'fda-standards-recognition', 'consensus-standard', 'submission-pathway'],
    failure_rate_pct: 40.0,
    is_active: true,
    demoRelevant: false,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Regulatory team referenced a consensus standard without verifying its current recognition status in the FDA database.',
      regulatoryHook: `FDA Guidance: Abbreviated 510(k); FDA Standards Recognition Database`,
      detectionMethod: 'Standards recognition status verification against the FDA CDRH standards database at time of submission.',
      remediationPath: `Identify currently recognized standard covering the same performance characteristics and resubmit.`,
      estimatedCost: '$30K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '9% of abbreviated 510(k)s cite at least one standard with lapsed or withdrawn recognition status.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M470',
    name: `510k Electrical Safety Testing Performed to Superseded IEC 60601 Edition`,
    description: `A 510(k) electrical safety section cites testing data collected under IEC 60601-1:2005 (3rd edition) when FDA now expects conformance to the 3.1 amendment or 4th edition for new submissions.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['iec-60601', 'electrical-safety', '510k', 'standards-edition', 'fda-deficiency'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Electrical safety testing conducted to superseded standard edition without bridging analysis to current edition requirements.',
      regulatoryHook: 'FDA Recognized Standards Database; IEC 60601-1:2005+AMD1:2012+AMD2:2020',
      detectionMethod: 'Test report edition audit against FDA current recognized standard version at submission date.',
      remediationPath: 'Conduct gap analysis and supplemental testing to current recognized standard edition before submission.',
      estimatedCost: '$50K–$180K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '28% of 510(k) electrical safety deficiencies cite superseded standard edition testing.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M471',
    name: 'De Novo Request Performance Testing Conducted on Non-Final Device Configuration',
    description: `A de novo request includes bench and clinical performance data generated on a device configuration that differs from the final design submitted for classification.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['de-novo', 'device-configuration', 'performance-testing', 'design-freeze', 'fda-review'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: true,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Performance testing was executed on a prototype configuration that underwent post-test design changes not reflected in the submission.',
      regulatoryHook: '21 CFR 860.260; FDA De Novo Classification Process Guidance',
      detectionMethod: 'Device configuration change log comparison between test article specifications and final design history file.',
      remediationPath: 'Freeze device design before performance testing; conduct supplemental testing on final configuration.',
      estimatedCost: '$200K–$800K',
      timeToRemediate: '6–18 months',
      industryBenchmark: '26% of de novo submissions require FDA requests for testing conducted on the final device configuration.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M472',
    name: '510k Submission for High-Risk Device Without iQ Submission Program Engagement',
    description: 'A manufacturer submits a 510(k) for a Class II device with a novel technology without leveraging the FDA Interactive Review or iQ Program, missing opportunities to resolve critical issues before formal review.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['510k', 'iq-submission-program', 'interactive-review', 'fda-program', 'novel-technology'],
    failure_rate_pct: 45.0,
    is_active: true,
    demoRelevant: false,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Regulatory strategy did not include pre-submission engagement to identify and resolve novel technology review concerns.',
      regulatoryHook: `FDA Guidance: Requests for Feedback and Meetings for Medical Device Submissions (Q-Submission Program)`,
      detectionMethod: `Review of pre-submission meeting history against device novelty risk score.`,
      remediationPath: `File Q-submission requesting FDA feedback on the review plan and data package adequacy before formal submission.`,
      estimatedCost: '$20K–$80K',
      timeToRemediate: '2–5 months',
      industryBenchmark: 'Devices with pre-submission meetings have 31% shorter review cycles than those without.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M473',
    name: `510k Sterilization Validation Data Inadequate for New Distribution Market`,
    description: `A 510(k) includes sterilization validation data qualified for one distribution environment that does not cover the temperature and humidity stresses of the new target market.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['510k', 'sterilization-validation', 'distribution-environment', 'iso-11135', 'fda-deficiency'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: false,
    subTopic: '510k-de-novo-advanced',
    data: {
      failureMode: 'Sterilization validation and package integrity testing did not include simulated distribution stresses for tropical or extreme climates.',
      regulatoryHook: 'ISO 11135; ASTM D4169; FDA Guidance on Shelf Life Testing',
      detectionMethod: 'Distribution environment matrix review comparing test conditions against labeling claims for all target markets.',
      remediationPath: 'Conduct distribution simulation and aging studies covering new environmental conditions; update sterilization validation.',
      estimatedCost: '$60K–$200K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '18% of 510(k) sterilization deficiencies arise from distribution environment scope gaps.',
      aiInsertionRisk: false,
    },
  },

  // ── Enforcement Action Response (M474–M485) ───────────────────────────────

  {
    code: 'M474',
    name: 'Warning Letter CAPA Response Submitted Without Root Cause Analysis',
    description: 'A manufacturer responds to an FDA warning letter with a corrective action plan that describes symptom-level fixes without demonstrating systematic root cause analysis for each cited violation.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['warning-letter', 'capa', 'root-cause-analysis', 'fda-response', '21-cfr-820'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Warning letter response outlined procedural changes without demonstrating a formal root cause investigation tied to each observation.',
      regulatoryHook: '21 CFR 820.100; FDA Warning Letter Response Expectations Guidance',
      detectionMethod: 'Warning letter response audit mapping each cited violation to a documented root cause and verified corrective action.',
      remediationPath: 'Conduct structured root cause analysis (5-why or fishbone) for each observation; resubmit with evidence of completion.',
      estimatedCost: '$250K–$900K',
      timeToRemediate: '6–18 months',
      industryBenchmark: '58% of initial warning letter responses are deemed inadequate by FDA on first review.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M475',
    name: 'Consent Decree Obligation Monitoring Without Independent Third-Party Auditor',
    description: 'A manufacturer under an FDA consent decree relies on internal quality staff to monitor compliance obligations rather than engaging an FDA-approved independent third-party expert auditor as required by the decree.',
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['consent-decree', 'third-party-auditor', 'fda-compliance', 'independent-expert', 'quality-system'],
    failure_rate_pct: 70.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Consent decree audit program managed by internal QA without engaging a DOJ/FDA-approved independent expert.',
      regulatoryHook: 'Consent Decree of Permanent Injunction Terms; 21 CFR Part 820',
      detectionMethod: 'Consent decree text review to identify third-party auditor requirements and current engagement status.',
      remediationPath: 'Engage FDA-acceptable independent expert auditor; submit auditor credentials and audit plan to FDA for approval.',
      estimatedCost: '$500K–$2M/year',
      timeToRemediate: '3–6 months to establish',
      industryBenchmark: '71% of consent decree contempt actions involve failure to maintain an adequate independent audit program.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M476',
    name: 'FDA Form 483 Response Missing Interim Controls for Continuing Risk',
    description: `A manufacturer submits a Form 483 response addressing long-term corrective actions without specifying interim controls to mitigate patient risk during the remediation period.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['fda-483', 'interim-controls', 'capa', 'patient-risk', 'fda-response'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: '483 response focused exclusively on systemic long-term fixes without addressing immediate risk containment actions.',
      regulatoryHook: '21 CFR 820.100; FDA Inspection and Enforcement Policy',
      detectionMethod: `Review 483 response for explicit interim controls with implementation dates and responsible owners.`,
      remediationPath: `Amend 483 response to include interim controls, risk assessment of continued operations, and bridge plan.`,
      estimatedCost: '$100K–$400K',
      timeToRemediate: '1–4 months',
      industryBenchmark: '43% of 483 responses are escalated to warning letters when interim controls are absent.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M477',
    name: 'Import Alert Resolution Plan Lacking Voluntary Action Indicated Milestone Evidence',
    description: `A manufacturer subject to an import alert submits a corrective action plan to FDA without providing objective evidence for each voluntary action indicated (VAI) milestone required before FDA will lift the alert.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['import-alert', 'vai', 'fda-enforcement', 'corrective-action', 'milestone-evidence'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Import alert response submitted without the batch record reviews, testing data, and third-party audit reports FDA requires.',
      regulatoryHook: `FDA Import Alert 89-08; 21 CFR 801; FDA Regulatory Procedures Manual Chapter 9`,
      detectionMethod: `Gap analysis of corrective action plan against FDA's import alert removal criteria for the device category.`,
      remediationPath: `Engage FDA district office to confirm removal criteria; provide complete evidence package with third-party audit confirmation.`,
      estimatedCost: '$300K–$1M',
      timeToRemediate: '9–24 months',
      industryBenchmark: 'Average time from import alert initiation to removal for device firms is 27 months.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M478',
    name: 'Injunction Compliance Certification Submitted Without Required Quality Data',
    description: `A manufacturer subject to a permanent injunction files its required certification of compliance with FDA without the quality system audit reports and product testing data that the injunction specifies must accompany the certification.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['injunction', 'compliance-certification', 'quality-data', 'fda-enforcement', 'consent-decree'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Compliance certification filed without attaching the audit report and testing data required by injunction Paragraph 12.',
      regulatoryHook: `Permanent Injunction Decree Terms; 21 U.S.C. § 332; FDA Regulatory Procedures Manual`,
      detectionMethod: `Injunction compliance checklist review prior to certification filing to verify all required attachments are present.`,
      remediationPath: `Amend certification to include all required attachments; implement pre-filing checklist for future certifications.`,
      estimatedCost: '$80K–$300K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '22% of injunction compliance certifications require FDA requests for missing supporting documentation.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M479',
    name: 'Warning Letter CAPA Not Completed Within Committed Timeline',
    description: `A manufacturer commits to a 90-day corrective action completion timeline in a warning letter response but does not complete all actions within that window without proactively notifying FDA of the delay.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['warning-letter', 'capa-timeline', 'fda-response', 'commitment-breach', 'fda-escalation'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'CAPA project plan had no executive escalation trigger for timeline slippage, resulting in missed FDA commitment without notice.',
      regulatoryHook: `FDA Warning Letter Response Expectations; 21 U.S.C. § 333`,
      detectionMethod: `CAPA milestone tracker compared against warning letter response commitment dates.`,
      remediationPath: `Proactively notify FDA of delay with revised timeline and root cause of slippage before commitment date passes.`,
      estimatedCost: '$150K–$500K',
      timeToRemediate: '2–6 months',
      industryBenchmark: '47% of warning letter CAPA programs experience at least one missed committed milestone.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M480',
    name: 'Recalled Device Field Action Effectiveness Check Not Documented',
    description: `A manufacturer completes a recall field action but fails to document effectiveness check results confirming that recalled devices have been removed from commerce, as required by 21 CFR 806.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['recall', 'effectiveness-check', '21-cfr-806', 'field-action', 'fda-documentation'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Recall closure report submitted without effectiveness check data confirming customer response rate and device retrieval.',
      regulatoryHook: `21 CFR 806.20; FDA Recall Regulations; FDA Guidance on Medical Device Recalls`,
      detectionMethod: `Recall closure report audit for effectiveness check percentage and evidence of unreachable consignees follow-up.`,
      remediationPath: `Conduct and document effectiveness checks; reopen recall if response rate falls below FDA-accepted threshold.`,
      estimatedCost: '$50K–$200K',
      timeToRemediate: '2–6 months',
      industryBenchmark: 'FDA requires a minimum 70% effectiveness check response rate for Class I recalls.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M481',
    name: 'MDR Malfunction Reporting Threshold Not Embedded in Complaint Handling SOP',
    description: `A manufacturer's complaint handling SOP does not include a documented decision tree for determining whether a malfunction complaint meets the MDR malfunction reporting threshold under 21 CFR 803.50.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['mdr', 'malfunction-reporting', '21-cfr-803-50', 'complaint-handling', 'sop'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Complaint handlers make MDR malfunction reporting decisions ad hoc without a documented threshold assessment process.',
      regulatoryHook: `21 CFR 803.50; FDA Guidance on MDR Reporting for Manufacturers`,
      detectionMethod: `Complaint file audit comparing malfunction-type complaints against MDR submission records for under-reporting.`,
      remediationPath: `Revise complaint SOP to include MDR malfunction decision tree; retrain complaint handlers; conduct retrospective MDR review.`,
      estimatedCost: '$80K–$300K',
      timeToRemediate: '2–5 months',
      industryBenchmark: 'FDA MDR audits identify unreported malfunction reports in 39% of inspected manufacturers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M482',
    name: 'Field Safety Corrective Action Not Synchronized With International Competent Authority Notifications',
    description: `A manufacturer initiates a US recall without simultaneously notifying international competent authorities for affected markets, violating FSCA synchronization requirements in the EU MDR and Health Canada regulations.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['fsca', 'recall', 'eu-mdr', 'competent-authority', 'global-recall'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'US recall initiated by domestic regulatory team without triggering the global regulatory affairs notification workflow.',
      regulatoryHook: `21 CFR 806; EU MDR Article 87; Health Canada Medical Device Recall Guidance`,
      detectionMethod: `Recall notification timeline audit comparing US FDA submission date against international competent authority notification dates.`,
      remediationPath: `Implement global recall notification SOP with simultaneous multi-jurisdiction submission workflow.`,
      estimatedCost: '$100K–$350K',
      timeToRemediate: '2–6 months',
      industryBenchmark: '33% of US recalls affecting international markets have a notification lag of more than 30 days to non-US authorities.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M483',
    name: 'Establishment Registration and Device Listing Not Updated After Warning Letter Corrective Actions',
    description: `A manufacturer that discontinued a device model as part of warning letter corrective actions fails to update FDA device listing records to reflect the discontinuation, creating a compliance gap.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['device-listing', 'establishment-registration', '21-cfr-807', 'warning-letter', 'fda-database'],
    failure_rate_pct: 41.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Device listing database not updated to reflect product discontinuations made during warning letter remediation.',
      regulatoryHook: `21 CFR 807.30; FDA Device Listing Guidance`,
      detectionMethod: `Annual device listing reconciliation comparing active FDA listing records against current product portfolio.`,
      remediationPath: `Submit FDA device listing updates; implement post-CAPA regulatory database update checklist.`,
      estimatedCost: '$15K–$50K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '16% of manufacturers have FDA device listing records that do not reflect current product status.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M484',
    name: 'Post-Warning Letter Audit Finding Recurrence Due to Ineffective Training',
    description: `FDA re-inspects a manufacturer after a warning letter closure and finds recurrence of original observations because training records do not demonstrate that all affected personnel completed required retraining.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['warning-letter', 'retraining', 'capa-recurrence', 'fda-inspection', 'training-records'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Training CAPA implemented for a subset of personnel, with no tracking of temporary and contractor staff completion.',
      regulatoryHook: `21 CFR 820.25; FDA CAPA Guidance; Warning Letter Closeout Expectations`,
      detectionMethod: `Training completion report audit covering all roles identified in root cause analysis; include contractors and temps.`,
      remediationPath: `Extend training program to all affected roles; implement training effectiveness verification; document completion evidence.`,
      estimatedCost: '$80K–$300K',
      timeToRemediate: '2–5 months',
      industryBenchmark: 'CAPA recurrence rate within 24 months of warning letter closeout is 29% across medical device manufacturers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M485',
    name: 'Consent Decree Product Distribution Resumption Without Required FDA Certification',
    description: `A manufacturer resumes distribution of products covered by a consent decree without obtaining the required written FDA certification that the facility meets GMP requirements, violating the decree.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['consent-decree', 'distribution-resumption', 'gmp-certification', 'fda-enforcement', 'contempt'],
    failure_rate_pct: 73.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'enforcement-action-response',
    data: {
      failureMode: 'Supply chain team resumed shipments based on internal quality clearance without confirming FDA written certification.',
      regulatoryHook: `Consent Decree of Permanent Injunction; 21 U.S.C. § 332; FD&C Act § 301`,
      detectionMethod: `Distribution release gate audit confirming FDA written certification is on file before any decree-covered product ships.`,
      remediationPath: `Immediately halt distribution; engage FDA to obtain certification; implement release hold requiring certification as prerequisite.`,
      estimatedCost: '$1M–$5M+',
      timeToRemediate: '6–18 months',
      industryBenchmark: 'Unauthorized distribution under a consent decree results in contempt proceedings in 89% of identified cases.',
      aiInsertionRisk: false,
    },
  },

  // ── FDA Inspection Readiness (M486–M497) ──────────────────────────────────

  {
    code: 'M486',
    name: 'QSIT Inspection Framework Readiness Assessment Not Conducted Annually',
    description: `A manufacturer has not performed an annual internal QSIT-structured audit covering all four subsystems (Design Controls, CAPA, Production and Process Controls, and Management Controls) before an FDA inspection cycle.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['qsit', 'inspection-readiness', 'internal-audit', 'fda-inspection', 'quality-system'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Internal audit program does not mirror QSIT structure, leaving cross-subsystem linkage gaps undetected before FDA arrives.',
      regulatoryHook: `FDA Quality System Inspection Technique (QSIT) Guide; 21 CFR Part 820`,
      detectionMethod: `Internal audit schedule and report review for QSIT four-subsystem coverage in the prior 12 months.`,
      remediationPath: `Conduct QSIT-structured mock inspection; address findings before next scheduled FDA inspection window.`,
      estimatedCost: '$80K–$250K',
      timeToRemediate: '2–5 months',
      industryBenchmark: 'Manufacturers with QSIT-aligned internal audit programs receive 41% fewer FDA 483 observations.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M487',
    name: 'Inspection Host Team Lacks Documented Role Assignments and Escalation Protocol',
    description: `A manufacturer has no written inspection management plan assigning specific roles to an escort, subject matter experts, document room manager, and executive sponsor for FDA inspection response.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['inspection-management', 'host-team', 'fda-inspection', 'escalation-protocol', 'role-assignment'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Inspection response improvised during active FDA visit, with no pre-assigned document room manager or executive escalation path.',
      regulatoryHook: `FDA Investigations Operations Manual; 21 CFR Part 820`,
      detectionMethod: `Inspection management plan review for role assignments, training completion, and escalation decision tree.`,
      remediationPath: `Develop and drill inspection management plan with all assigned roles at least annually.`,
      estimatedCost: '$20K–$80K',
      timeToRemediate: '1–2 months',
      industryBenchmark: 'Facilities with documented inspection management plans receive 35% fewer observations per inspection.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M488',
    name: 'Data Integrity Gaps in Electronic Batch Records Detectable by FDA Audit Trail Review',
    description: `A manufacturer uses an electronic batch record system without enabling 21 CFR Part 11-compliant audit trails, allowing record deletion and modification without traceable attribution that FDA investigators can verify.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['data-integrity', '21-cfr-part-11', 'audit-trail', 'electronic-records', 'fda-inspection'],
    failure_rate_pct: 68.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Electronic batch record system audit trail feature was not activated, enabling record edits without traceable user attribution.',
      regulatoryHook: `21 CFR Part 11; FDA Guidance on Data Integrity and Compliance with Drug CGMP (applied by analogy); 21 CFR 820.180`,
      detectionMethod: `IT system configuration audit for Part 11 audit trail activation and periodic administrator access review.`,
      remediationPath: `Enable audit trail in all electronic record systems; conduct retrospective data integrity review; retrain users.`,
      estimatedCost: '$150K–$500K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '52% of FDA 483 observations for Class II manufacturers involve data integrity or electronic records deficiencies.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M489',
    name: 'Establishment Inspection Report Prior Observations Not Tracked to Closure',
    description: `A manufacturer received observations in a prior establishment inspection report (EIR) and committed to corrections, but has no system tracking closure status and objective evidence for each prior observation.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['eir', 'prior-observations', 'capa-closure', 'fda-inspection', 'inspection-readiness'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Prior EIR observations were not entered into the CAPA system with closure milestones and objective evidence requirements.',
      regulatoryHook: `21 CFR 820.100; FDA QSIT Guide; FDA EIR Review Policy`,
      detectionMethod: `EIR observation tracker audit comparing prior inspection findings against verified closure evidence.`,
      remediationPath: `Create EIR observation tracker; assign owner and closure deadline for each open observation; compile evidence packages.`,
      estimatedCost: '$50K–$180K',
      timeToRemediate: '2–5 months',
      industryBenchmark: `Unresolved prior EIR observations are cited in 44% of repeat FDA inspections at the same facility.`,
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M490',
    name: 'Inspection Backroom Document Retrieval Time Exceeds FDA Expectation',
    description: `A manufacturer's document management system requires more than 30 minutes to retrieve requested records during a mock inspection, creating a risk of FDA investigator frustration and unresolved information requests during actual inspections.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['backroom-management', 'document-retrieval', 'fda-inspection', 'inspection-readiness', 'document-control'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Document control system not organized for rapid retrieval by product family, device model, and inspection topic.',
      regulatoryHook: `21 CFR 820.180; FDA Investigations Operations Manual Chapter 5`,
      detectionMethod: `Mock inspection document drill measuring retrieval time for 10 sample record requests across subsystems.`,
      remediationPath: `Reorganize document management system with inspection-topic tagging; conduct quarterly document retrieval drills.`,
      estimatedCost: '$30K–$100K',
      timeToRemediate: '1–3 months',
      industryBenchmark: 'Document retrieval delays contribute to 21% of avoidable 483 observations during FDA inspections.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M491',
    name: 'Contract Manufacturer Included in Scope Without Supplier Audit Evidence',
    description: `A manufacturer plans to introduce a contract manufacturer into its FDA inspection scope without having completed a quality agreement and surveillance audit for that supplier.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['contract-manufacturer', 'supplier-audit', 'quality-agreement', 'fda-inspection', '21-cfr-820-50'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Contract manufacturing arrangement was established without a quality agreement or incoming audit before production began.',
      regulatoryHook: `21 CFR 820.50; FDA Guidance on Quality Systems Regulation; ISO 13485:2016 Section 7.4`,
      detectionMethod: `Approved supplier list audit for quality agreement execution and most recent surveillance audit date.`,
      remediationPath: `Execute quality agreement; conduct supplier audit; implement incoming inspection protocol before using contract output.`,
      estimatedCost: '$80K–$300K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '37% of FDA 483 observations at contract manufacturer sites reflect deficiencies in the customer quality agreement.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M492',
    name: 'Design History File Incomplete for Currently Marketed PMA Device',
    description: `A manufacturer cannot produce a complete Design History File (DHF) for a currently marketed PMA device during an FDA inspection because legacy records were archived in a non-retrievable format.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['design-history-file', 'dhf', 'fda-inspection', 'pma', '21-cfr-820-30'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Legacy DHF records stored on obsolete media formats were not migrated to current document management system.',
      regulatoryHook: `21 CFR 820.30(j); FDA QSIT Guide Design Controls Subsystem`,
      detectionMethod: `DHF completeness audit for each marketed device model verifying retrievability of all required elements.`,
      remediationPath: `Migrate legacy DHF records to current DMS; remediate gaps with retrospective engineering documentation.`,
      estimatedCost: '$150K–$600K',
      timeToRemediate: '4–12 months',
      industryBenchmark: '29% of DHF inspections identify at least one missing or non-retrievable design verification or validation record.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M493',
    name: 'Process Validation Not Revalidated After Equipment Replacement',
    description: `A manufacturer replaced a critical production line instrument without triggering process revalidation, creating an unresolved gap between validated process parameters and current equipment specifications.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['process-validation', 'equipment-change', 'revalidation', 'fda-inspection', '21-cfr-820-75'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Change control process did not include a revalidation trigger for equipment substitutions affecting validated process parameters.',
      regulatoryHook: `21 CFR 820.75; FDA Process Validation Guidance; ISO 13485:2016 Section 7.5.6`,
      detectionMethod: `Change control record audit comparing equipment replacements against process validation status for affected lines.`,
      remediationPath: `Conduct equipment qualification (IQ/OQ/PQ) and process revalidation; update validation master plan.`,
      estimatedCost: '$100K–$400K',
      timeToRemediate: '3–8 months',
      industryBenchmark: '44% of production-line 483 observations involve process validation records that do not reflect current equipment.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M494',
    name: 'Management Review Records Lacking Evidence of Quality Metric Trend Analysis',
    description: `A manufacturer's management review records document decisions without capturing the quality metric trend data and analysis that FDA investigators use to assess whether management is effectively monitoring the quality system.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['management-review', 'quality-metrics', 'trend-analysis', 'fda-inspection', '21-cfr-820-20'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Management review minutes record action items without attaching the underlying quality metric trend data that drove each decision.',
      regulatoryHook: `21 CFR 820.20; FDA QSIT Guide Management Controls Subsystem`,
      detectionMethod: `Management review record audit verifying trend data attachments for complaint rate, CAPA aging, and audit findings.`,
      remediationPath: `Revise management review template to require trend charts as exhibits; conduct training for QA and executive participants.`,
      estimatedCost: '$20K–$70K',
      timeToRemediate: '1–2 months',
      industryBenchmark: 'Management Controls is the subsystem most frequently escalated to a deeper dive in FDA QSIT inspections.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M495',
    name: 'Sterilization Revalidation Cycle Not Completed After Maximum Product Load Change',
    description: `A manufacturer increased the product load per sterilization cycle without triggering a sterilization revalidation, operating outside the validated load parameters established during initial process qualification.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['sterilization', 'revalidation', 'process-validation', 'fda-inspection', 'iso-11135'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Production scheduling increased sterilization load without change control review of validated load range limits.',
      regulatoryHook: `ISO 11135; AAMI TIR17; 21 CFR 820.75`,
      detectionMethod: `Sterilization batch record audit comparing current load configurations against validated load parameters.`,
      remediationPath: `Halt out-of-range loads; conduct revalidation at the new maximum load; update sterilization validation protocol.`,
      estimatedCost: '$100K–$350K',
      timeToRemediate: '3–7 months',
      industryBenchmark: 'Sterilization validation gaps are cited in 31% of FDA inspections at sterile medical device manufacturers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M496',
    name: 'Complaint Investigation Closure Rate Below FDA Acceptable Threshold',
    description: `A manufacturer has a complaint investigation closure rate below 90% at 60 days, with aging investigations that FDA investigators will identify as evidence of an ineffective complaint handling system.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['complaint-handling', 'investigation-closure', 'fda-inspection', '21-cfr-820-198', 'aging-complaints'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Complaint handling team backlog caused by understaffing and complex product lines resulted in 35% open-beyond-60-day rate.',
      regulatoryHook: `21 CFR 820.198; FDA QSIT Guide Production and Process Controls`,
      detectionMethod: `Complaint database aging report segmented by complaint type, product line, and days-open status.`,
      remediationPath: `Triage aging complaints; add temporary investigation resources; implement 45-day escalation trigger to management.`,
      estimatedCost: '$80K–$250K',
      timeToRemediate: '2–5 months',
      industryBenchmark: 'Complaint handling deficiencies appear in 48% of FDA inspection 483s for Class II device manufacturers.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M497',
    name: 'Internal Auditor Qualification Records Not Maintained Per 21 CFR 820',
    description: `A manufacturer cannot produce training records demonstrating that internal auditors conducting quality system audits have been trained to audit procedures and applicable quality standards.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['internal-audit', 'auditor-qualification', 'training-records', 'fda-inspection', '21-cfr-820-22'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'fda-inspection-readiness',
    data: {
      failureMode: 'Internal auditors assigned based on availability rather than documented qualification criteria and training completion.',
      regulatoryHook: `21 CFR 820.22; ISO 13485:2016 Section 8.2.4; ISO 19011`,
      detectionMethod: `Auditor qualification record review for each active internal auditor against SOP qualification criteria.`,
      remediationPath: `Establish auditor qualification SOP with minimum training and experience requirements; backfill missing records.`,
      estimatedCost: '$20K–$70K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '21% of audit program 483 observations involve unqualified or undocumented internal auditors.',
      aiInsertionRisk: false,
    },
  },

  // ── UDI / EUDAMED Global (M498–M509) ─────────────────────────────────────

  {
    code: 'M498',
    name: 'GUDID Submission Contains Inaccurate Device Identifier for Configuration Variant',
    description: `A manufacturer submits a Global UDI Database record with an incorrect device identifier (DI) for a device configuration variant, creating a discrepancy between labeled UDI and GUDID-published data.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['gudid', 'device-identifier', 'udi', 'fda-submission', 'labeling-accuracy'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'UDI submission team used a legacy part number for configuration variants without mapping to current DI assignment.',
      regulatoryHook: `21 CFR 830; FDA UDI System Final Rule; FDA GUDID Guidance`,
      detectionMethod: `GUDID record reconciliation against product label DI for each active device configuration.`,
      remediationPath: `Correct GUDID record; implement DI-to-label verification step in the product release process.`,
      estimatedCost: '$30K–$100K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '19% of GUDID records for Class II devices contain at least one inaccurate device attribute.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M499',
    name: 'New Device Configuration Lacks DI Assignment Before Market Release',
    description: `A manufacturer introduces a new device configuration into distribution without assigning and registering a new device identifier, instead shipping product with the DI of an existing configuration.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['device-identifier', 'new-configuration', 'udi', 'fda-compliance', '21-cfr-830'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'Product launch checklist did not include UDI DI assignment as a required gating item before first distribution.',
      regulatoryHook: `21 CFR 830.20; 21 CFR 801.20; FDA UDI System Final Rule`,
      detectionMethod: `New product release audit comparing product launch records against UDI DI assignment and GUDID submission evidence.`,
      remediationPath: `Assign new DI through an FDA-accredited issuing agency; submit GUDID record; relabel affected distributed units.`,
      estimatedCost: '$50K–$200K',
      timeToRemediate: '2–5 months',
      industryBenchmark: 'New configuration DI omissions are identified in 24% of FDA UDI compliance inspections.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M500',
    name: 'DI Record Update Not Triggered After Labeling Change Affecting Version Identifier',
    description: `A manufacturer updates device labeling in a way that changes the version or model identifier but does not update the GUDID DI record to reflect the new labeling version.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['gudid', 'di-record-update', 'labeling-change', 'udi', 'version-identifier'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'Labeling change control process does not include a GUDID update trigger assessment step.',
      regulatoryHook: `21 CFR 830.30; FDA GUDID Guidance Section 5`,
      detectionMethod: `Labeling change control records audit for UDI DI update trigger assessment documentation.`,
      remediationPath: `Amend labeling change control SOP to include GUDID update assessment; update affected DI records.`,
      estimatedCost: '$20K–$70K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '31% of GUDID discrepancies traced to labeling changes where DI update was not triggered.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M501',
    name: 'International UDI Harmonization Gap Between US DI and EU Basic UDI-DI',
    description: `A manufacturer maintains separate UDI assignments for its US GUDID and EU EUDAMED registrations for the same device, creating a regulatory harmonization gap that complicates global traceability and adverse event reporting.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['udi-harmonization', 'eudamed', 'gudid', 'basic-udi-di', 'eu-mdr'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'US and EU UDI programs managed by separate regional teams using different issuing agencies and nomenclature systems.',
      regulatoryHook: `21 CFR 830; EU MDR Article 27; IMDRF UDI Guidance; EUDAMED Registration Requirements`,
      detectionMethod: `Cross-reference GUDID DI records against EUDAMED Basic UDI-DI for the same device models.`,
      remediationPath: `Develop global UDI harmonization map; align US DI and EU Basic UDI-DI; update GUDID and EUDAMED records.`,
      estimatedCost: '$100K–$400K',
      timeToRemediate: '4–10 months',
      industryBenchmark: '43% of global device manufacturers have at least one UDI mismatch between GUDID and EUDAMED records.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M502',
    name: 'Direct-to-Consumer UDI Labeling Non-Compliant With 21 CFR 801.20 Human Readable Format',
    description: `A manufacturer sells a Class II device directly to consumers via e-commerce with labeling that includes the UDI in barcode form only, without the human-readable interpretation required under 21 CFR 801.20.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['udi-labeling', 'human-readable', '21-cfr-801-20', 'direct-to-consumer', 'ecommerce'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: `Product label design team included barcode UDI without adding the plain-text human-readable format below the symbol.`,
      regulatoryHook: `21 CFR 801.20; FDA UDI System Final Rule; FDA UDI Labeling Guidance`,
      detectionMethod: `Label compliance audit for all consumer-directed SKUs verifying human-readable UDI format presence.`,
      remediationPath: `Update label artwork to include human-readable UDI; implement label compliance checklist with UDI format verification.`,
      estimatedCost: '$20K–$80K',
      timeToRemediate: '1–4 months',
      industryBenchmark: '16% of direct-to-consumer medical device labels are missing the required human-readable UDI interpretation.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M503',
    name: 'EUDAMED Actor Registration Incomplete Before EU MDR Compliance Deadline',
    description: `A manufacturer planning to continue EU device distribution has not completed EUDAMED actor registration for its EU Authorized Representative and importer, blocking UDI device registration obligations.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['eudamed', 'actor-registration', 'eu-mdr', 'authorized-representative', 'compliance-deadline'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: `EU Authorized Representative and importer EUDAMED actor registrations not initiated 90 days before the EU MDR compliance date.`,
      regulatoryHook: `EU MDR Article 28–31; EUDAMED Registration Guidance; EU MDR Article 27`,
      detectionMethod: `EUDAMED actor registration status check for manufacturer, EU AR, and all importers in the EU supply chain.`,
      remediationPath: `Initiate EUDAMED actor registration immediately; engage EU AR to confirm their own registration status.`,
      estimatedCost: '$50K–$200K',
      timeToRemediate: '2–6 months',
      industryBenchmark: '39% of US manufacturers selling into the EU were non-compliant with EUDAMED actor registration at the MDR go-live date.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M504',
    name: 'Implantable Device UDI Not Included in Patient Implant Card',
    description: `A manufacturer of an implantable device provides patient implant cards that do not include the UDI as required by EU MDR Article 18 and FDA guidance for high-risk implants.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['implant-card', 'udi', 'eu-mdr-article-18', 'implantable-device', 'patient-safety'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'Patient implant card template was designed before UDI requirements applied and was not updated when regulations took effect.',
      regulatoryHook: `EU MDR Article 18; 21 CFR 801; FDA UDI System Final Rule`,
      detectionMethod: `Patient implant card template review for UDI inclusion in both human-readable and AIDC format.`,
      remediationPath: `Update implant card template to include UDI; re-validate card against EU MDR Article 18 minimum content requirements.`,
      estimatedCost: '$15K–$60K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '27% of Class III implantable device manufacturers had non-compliant patient implant cards at EU MDR go-live.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M505',
    name: 'GUDID Batch Upload Containing Production Identifier Fields Not Updated Post-Distribution',
    description: `A manufacturer distributes device lots with new expiration date ranges without updating the corresponding GUDID production identifier (PI) batch records, creating a traceability mismatch.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['gudid', 'production-identifier', 'pi-update', 'expiration-date', 'lot-traceability'],
    failure_rate_pct: 45.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'GUDID batch upload process was not integrated with the lot release workflow, leaving PI records static after initial submission.',
      regulatoryHook: `21 CFR 830; FDA GUDID Guidance; FDA UDI System Final Rule`,
      detectionMethod: `GUDID PI record audit comparing submitted lot and expiration data against distribution records for the past 12 months.`,
      remediationPath: `Integrate GUDID PI submission into lot release SOPs; conduct retrospective GUDID PI updates for distributed lots.`,
      estimatedCost: '$30K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: 'PI record maintenance is the most frequently deficient GUDID element identified in FDA UDI compliance reviews.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M506',
    name: 'UDI Carrier Placement Violates FDA Minimum Label Real Estate Requirements',
    description: `A manufacturer places the UDI carrier on device packaging in a location that obscures adjacent required label information or reduces scan reliability below FDA minimum requirements.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['udi-carrier', 'label-placement', 'scan-reliability', 'fda-labeling', '21-cfr-801'],
    failure_rate_pct: 40.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'UDI carrier placement was determined by packaging aesthetics without verifying scan reliability and label real estate compliance.',
      regulatoryHook: `21 CFR 801.20; FDA UDI Labeling Guidance; ISO/IEC 15415 barcode quality standard`,
      detectionMethod: `Label scan reliability test per ISO/IEC 15415 and label real estate compliance review for UDI carrier placement.`,
      remediationPath: `Relocate UDI carrier to comply with placement and scan quality requirements; revalidate label artwork.`,
      estimatedCost: '$20K–$80K',
      timeToRemediate: '1–4 months',
      industryBenchmark: '13% of UDI barcodes on medical device packaging fail minimum ISO scan reliability standards.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M507',
    name: 'Health Canada DPIN UDI Submission Not Synchronized With GUDID Record',
    description: `A manufacturer selling in Canada submits a Health Canada Device Product Identification Number (DPIN) UDI record that differs from the corresponding GUDID record for the same device.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['health-canada', 'dpin', 'udi-harmonization', 'gudid', 'cross-border-compliance'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: `US and Canadian UDI submissions managed independently without cross-checking data consistency between GUDID and Health Canada's database.`,
      regulatoryHook: `Health Canada Medical Device Regulations SOR/98-282; 21 CFR 830; IMDRF UDI Guidance`,
      detectionMethod: `Comparative audit of GUDID and Health Canada DPIN records for all devices distributed in both markets.`,
      remediationPath: `Establish UDI data governance process requiring synchronized submission across all national UDI databases.`,
      estimatedCost: '$40K–$150K',
      timeToRemediate: '2–5 months',
      industryBenchmark: '36% of devices sold in both US and Canadian markets have at least one attribute discrepancy between GUDID and DPIN.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M508',
    name: 'Legacy Device UDI Exemption Claim Applied Without Annual Portfolio Review',
    description: `A manufacturer claims UDI exemptions for legacy device models without conducting an annual portfolio review to confirm that each exemption claim remains valid under current FDA regulations.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['udi-exemption', 'legacy-device', 'portfolio-review', 'fda-compliance', '21-cfr-801'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'UDI exemption rationale documented once at initial assessment with no process for annual revalidation as regulations evolved.',
      regulatoryHook: `21 CFR 801.30; 21 CFR 801.40; FDA UDI Exemption List`,
      detectionMethod: `UDI exemption register review comparing each claimed exemption against current FDA UDI regulation and exemption list.`,
      remediationPath: `Conduct annual UDI exemption revalidation; assign UDI to devices whose exemption basis no longer applies.`,
      estimatedCost: '$20K–$70K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '18% of manufacturers claiming UDI exemptions cannot demonstrate that exemption criteria were reviewed within the past 24 months.',
      aiInsertionRisk: false,
    },
  },
  {
    code: 'M509',
    name: 'AI-Enabled Software as Medical Device UDI Classification Inconsistent With FDA SaMD Guidance',
    description: `A manufacturer of an AI-enabled software as a medical device (SaMD) applies a Class I UDI label format when the device meets the criteria for Class II or Class III UDI requirements under FDA SaMD guidance.`,
    vertical: 'medtech',
    office_category: 'FDA Regulatory Affairs',
    keywords: ['samd', 'ai-ml', 'udi-classification', 'fda-samd-guidance', 'software-labeling'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'udi-eudamed-global',
    data: {
      failureMode: 'SaMD UDI classification based on legacy device class assignment rather than current FDA AI/ML SaMD risk framework.',
      regulatoryHook: `FDA AI/ML SaMD Action Plan; 21 CFR 830; FDA UDI System Final Rule; FDA Digital Health Policy`,
      detectionMethod: `SaMD UDI classification review against FDA AI/ML risk categorization framework for each software module.`,
      remediationPath: `Reclassify SaMD UDI requirements; update GUDID records; implement AI/ML change protocol per FDA proposed action plan.`,
      estimatedCost: '$80K–$300K',
      timeToRemediate: '3–7 months',
      industryBenchmark: '54% of AI/ML SaMD products have UDI records that do not reflect current FDA SaMD risk classification expectations.',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI/ML SaMD update cycles create recurring UDI reclassification obligations that are systematically undertracked by regulatory teams.',
    },
  },

];
