/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 46: Remote Patient Monitoring & Hospital-at-Home
// Part 3: H13100-H13149
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM46_PART3_PATTERNS = [
  {
    code: 'H13100',
    name: 'RPM Agentic Orchestration Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for agentic orchestration but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'NCQA HEDIS audit', 'FDA submission posture', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13101',
    name: 'Hospital At Home Coding Suggestion Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for coding suggestion but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'FDA SaMD guidance', 'KLAS commentary', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13102',
    name: 'Device Telemetry Documentation Review Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for documentation review but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'NIST AI RMF', 'Epic App Orchard integration', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13103',
    name: 'CMS Waiver Vendor Comparison Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for vendor comparison but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'ONC HTI-1', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13104',
    name: 'Care Escalation Capacity Forecasting Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 77,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for capacity forecasting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'TEFCA participation', 'AWS HealthLake', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13105',
    name: 'RPM Staffing Optimization Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 79,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for staffing optimization but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'FHIR R4 mapping', 'Azure Health Data Services', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13106',
    name: 'Hospital At Home Quality Abstraction Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for quality abstraction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'HL7 v2 ADT reconciliation', 'Snowflake Healthcare', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13107',
    name: 'Device Telemetry Patient Outreach Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for patient outreach but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is Epic change control: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'Epic change control', 'Databricks Lakehouse', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13108',
    name: 'CMS Waiver Triage Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for triage but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is model registry: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'model registry', 'ServiceNow workflow', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13109',
    name: 'Care Escalation Drafting Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for drafting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'deployment-site validation', 'Salesforce Health Cloud', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13110',
    name: 'RPM Summarization Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 72,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for summarization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'MLOps monitoring', 'startup maturity evidence', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13111',
    name: 'Hospital At Home Risk Scoring Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for risk scoring but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is clinical safety review: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'clinical safety review', 'SOC 2 Type II', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13112',
    name: 'Device Telemetry Worklist Prioritization Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for worklist prioritization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'procurement RFP scoring', 'HITRUST roadmap', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13113',
    name: 'CMS Waiver Appeal Generation Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for appeal generation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'BAFO contract clause', 'Series B burn rate', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13114',
    name: 'Care Escalation Order Recommendation Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 56,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for order recommendation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'HIPAA BAA', 'implementation partner capacity', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13115',
    name: 'RPM Benefit Verification Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for benefit verification but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'minimum necessary policy', 'referenceable health-system customer', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13116',
    name: 'Hospital At Home Eligibility Prediction Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 79,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for eligibility prediction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'TJC survey evidence', 'clinical advisory board', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13117',
    name: 'Device Telemetry Care Gap Closure Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 63,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for care gap closure but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is CMS CoP: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'CMS CoP', 'FDA submission posture', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13118',
    name: 'CMS Waiver Cohort Matching Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for cohort matching but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'NCQA HEDIS audit', 'KLAS commentary', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13119',
    name: 'Care Escalation Contract Analysis Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for contract analysis but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'FDA SaMD guidance', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13120',
    name: 'RPM Agentic Orchestration Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for agentic orchestration but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'NIST AI RMF', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13121',
    name: 'Hospital At Home Coding Suggestion Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for coding suggestion but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'ONC HTI-1', 'AWS HealthLake', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13122',
    name: 'Device Telemetry Documentation Review Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for documentation review but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'TEFCA participation', 'Azure Health Data Services', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13123',
    name: 'CMS Waiver Vendor Comparison Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 80,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for vendor comparison but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'FHIR R4 mapping', 'Snowflake Healthcare', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13124',
    name: 'Care Escalation Capacity Forecasting Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for capacity forecasting but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'HL7 v2 ADT reconciliation', 'Databricks Lakehouse', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13125',
    name: 'RPM Staffing Optimization Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for staffing optimization but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is Epic change control: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'Epic change control', 'ServiceNow workflow', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13126',
    name: 'Hospital At Home Quality Abstraction Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for quality abstraction but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is model registry: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'model registry', 'Salesforce Health Cloud', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13127',
    name: 'Device Telemetry Patient Outreach Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 56,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for patient outreach but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'deployment-site validation', 'startup maturity evidence', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13128',
    name: 'CMS Waiver Triage Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for triage but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'MLOps monitoring', 'SOC 2 Type II', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13129',
    name: 'Care Escalation Drafting Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for drafting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is clinical safety review: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'clinical safety review', 'HITRUST roadmap', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13130',
    name: 'RPM Summarization Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for summarization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'procurement RFP scoring', 'Series B burn rate', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13131',
    name: 'Hospital At Home Risk Scoring Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 83,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for risk scoring but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'BAFO contract clause', 'implementation partner capacity', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13132',
    name: 'Device Telemetry Worklist Prioritization Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for worklist prioritization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'HIPAA BAA', 'referenceable health-system customer', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13133',
    name: 'CMS Waiver Appeal Generation Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for appeal generation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'minimum necessary policy', 'clinical advisory board', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13134',
    name: 'Care Escalation Order Recommendation Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for order recommendation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'TJC survey evidence', 'FDA submission posture', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13135',
    name: 'RPM Benefit Verification Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for benefit verification but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is CMS CoP: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'CMS CoP', 'KLAS commentary', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13136',
    name: 'Hospital At Home Eligibility Prediction Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for eligibility prediction but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'NCQA HEDIS audit', 'Epic App Orchard integration', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13137',
    name: 'Device Telemetry Care Gap Closure Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 54,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for care gap closure but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'FDA SaMD guidance', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13138',
    name: 'CMS Waiver Cohort Matching Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for cohort matching but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'NIST AI RMF', 'AWS HealthLake', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13139',
    name: 'Care Escalation Contract Analysis Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for contract analysis but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'ONC HTI-1', 'Azure Health Data Services', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13140',
    name: 'RPM Agentic Orchestration Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for agentic orchestration but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'TEFCA participation', 'Snowflake Healthcare', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13141',
    name: 'Hospital At Home Coding Suggestion Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for coding suggestion but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'FHIR R4 mapping', 'Databricks Lakehouse', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13142',
    name: 'Device Telemetry Documentation Review Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for documentation review but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'HL7 v2 ADT reconciliation', 'ServiceNow workflow', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13143',
    name: 'CMS Waiver Vendor Comparison Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 83,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for vendor comparison but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is Epic change control: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'Epic change control', 'Salesforce Health Cloud', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13144',
    name: 'Care Escalation Capacity Forecasting Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for capacity forecasting but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is model registry: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'model registry', 'startup maturity evidence', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13145',
    name: 'RPM Staffing Optimization Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when RPM is used for staffing optimization but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when device telemetry is not proven in production.`,
    keywords: ['RPM', 'device telemetry', 'deployment-site validation', 'SOC 2 Type II', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13146',
    name: 'Hospital At Home Quality Abstraction Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when hospital-at-home is used for quality abstraction but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when CMS waiver is not proven in production.`,
    keywords: ['hospital-at-home', 'CMS waiver', 'MLOps monitoring', 'HITRUST roadmap', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13147',
    name: 'Device Telemetry Patient Outreach Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when device telemetry is used for patient outreach but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is clinical safety review: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when care escalation is not proven in production.`,
    keywords: ['device telemetry', 'care escalation', 'clinical safety review', 'Series B burn rate', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13148',
    name: 'CMS Waiver Triage Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when CMS waiver is used for triage but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when RPM is not proven in production.`,
    keywords: ['CMS waiver', 'RPM', 'procurement RFP scoring', 'implementation partner capacity', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  },
  {
    code: 'H13149',
    name: 'Care Escalation Drafting Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `Remote Patient Monitoring & Hospital-at-Home initiatives fail when care escalation is used for drafting but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when hospital-at-home is not proven in production.`,
    keywords: ['care escalation', 'hospital-at-home', 'BAFO contract clause', 'referenceable health-system customer', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Remote Patient Monitoring & Hospital-at-Home',
  }
];
