/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 65: Startup Ecosystem: Cyber, Identity & Trust Diligence
// Part 1: H16800-H16849
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM65_PART1_PATTERNS = [
  {
    code: 'H16800',
    name: 'Claroty Cohort Matching Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for cohort matching but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'clinical safety review', 'HITRUST roadmap', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16801',
    name: 'Wiz Contract Analysis Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for contract analysis but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'procurement RFP scoring', 'Series B burn rate', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16802',
    name: 'Ordr Agentic Orchestration Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for agentic orchestration but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'BAFO contract clause', 'implementation partner capacity', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16803',
    name: 'Identity Startup Coding Suggestion Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for coding suggestion but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'HIPAA BAA', 'referenceable health-system customer', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16804',
    name: 'HITRUST Documentation Review Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for documentation review but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'minimum necessary policy', 'clinical advisory board', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16805',
    name: 'Claroty Vendor Comparison Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for vendor comparison but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'TJC survey evidence', 'FDA submission posture', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16806',
    name: 'Wiz Capacity Forecasting Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for capacity forecasting but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'CMS CoP', 'KLAS commentary', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16807',
    name: 'Ordr Staffing Optimization Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for staffing optimization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'NCQA HEDIS audit', 'Epic App Orchard integration', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16808',
    name: 'Identity Startup Quality Abstraction Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for quality abstraction but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'FDA SaMD guidance', 'Microsoft Cloud for Healthcare', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16809',
    name: 'HITRUST Patient Outreach Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for patient outreach but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'NIST AI RMF', 'AWS HealthLake', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16810',
    name: 'Claroty Triage Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for triage but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'ONC HTI-1', 'Azure Health Data Services', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16811',
    name: 'Wiz Drafting Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for drafting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'TEFCA participation', 'Snowflake Healthcare', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16812',
    name: 'Ordr Summarization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for summarization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'FHIR R4 mapping', 'Databricks Lakehouse', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16813',
    name: 'Identity Startup Risk Scoring Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for risk scoring but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'HL7 v2 ADT reconciliation', 'ServiceNow workflow', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16814',
    name: 'HITRUST Worklist Prioritization Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for worklist prioritization but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'Epic change control', 'Salesforce Health Cloud', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16815',
    name: 'Claroty Appeal Generation Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for appeal generation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'model registry', 'startup maturity evidence', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16816',
    name: 'Wiz Order Recommendation Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for order recommendation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'deployment-site validation', 'SOC 2 Type II', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16817',
    name: 'Ordr Benefit Verification Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for benefit verification but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'MLOps monitoring', 'HITRUST roadmap', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16818',
    name: 'Identity Startup Eligibility Prediction Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for eligibility prediction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'clinical safety review', 'Series B burn rate', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16819',
    name: 'HITRUST Care Gap Closure Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for care gap closure but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'procurement RFP scoring', 'implementation partner capacity', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16820',
    name: 'Claroty Cohort Matching Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for cohort matching but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'BAFO contract clause', 'referenceable health-system customer', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16821',
    name: 'Wiz Contract Analysis Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for contract analysis but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'HIPAA BAA', 'clinical advisory board', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16822',
    name: 'Ordr Agentic Orchestration Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for agentic orchestration but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'minimum necessary policy', 'FDA submission posture', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16823',
    name: 'Identity Startup Coding Suggestion Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for coding suggestion but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'TJC survey evidence', 'KLAS commentary', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16824',
    name: 'HITRUST Documentation Review Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for documentation review but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'CMS CoP', 'Epic App Orchard integration', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16825',
    name: 'Claroty Vendor Comparison Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for vendor comparison but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'NCQA HEDIS audit', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16826',
    name: 'Wiz Capacity Forecasting Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for capacity forecasting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'FDA SaMD guidance', 'AWS HealthLake', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16827',
    name: 'Ordr Staffing Optimization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for staffing optimization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'NIST AI RMF', 'Azure Health Data Services', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16828',
    name: 'Identity Startup Quality Abstraction Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for quality abstraction but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'ONC HTI-1', 'Snowflake Healthcare', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16829',
    name: 'HITRUST Patient Outreach Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for patient outreach but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'TEFCA participation', 'Databricks Lakehouse', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16830',
    name: 'Claroty Triage Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for triage but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'FHIR R4 mapping', 'ServiceNow workflow', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16831',
    name: 'Wiz Drafting Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for drafting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'HL7 v2 ADT reconciliation', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16832',
    name: 'Ordr Summarization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for summarization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is Epic change control: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'Epic change control', 'startup maturity evidence', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16833',
    name: 'Identity Startup Risk Scoring Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for risk scoring but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is model registry: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'model registry', 'SOC 2 Type II', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16834',
    name: 'HITRUST Worklist Prioritization Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for worklist prioritization but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'deployment-site validation', 'HITRUST roadmap', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16835',
    name: 'Claroty Appeal Generation Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for appeal generation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'MLOps monitoring', 'Series B burn rate', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16836',
    name: 'Wiz Order Recommendation Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for order recommendation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'clinical safety review', 'implementation partner capacity', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16837',
    name: 'Ordr Benefit Verification Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for benefit verification but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'procurement RFP scoring', 'referenceable health-system customer', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16838',
    name: 'Identity Startup Eligibility Prediction Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for eligibility prediction but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'BAFO contract clause', 'clinical advisory board', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16839',
    name: 'HITRUST Care Gap Closure Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for care gap closure but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'HIPAA BAA', 'FDA submission posture', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16840',
    name: 'Claroty Cohort Matching Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for cohort matching but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'minimum necessary policy', 'KLAS commentary', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16841',
    name: 'Wiz Contract Analysis Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for contract analysis but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves value realization ledger and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'TJC survey evidence', 'Epic App Orchard integration', 'value realization ledger', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16842',
    name: 'Ordr Agentic Orchestration Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for agentic orchestration but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is CMS CoP: AbarVa should turn this into a Moves pilot success metric and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'CMS CoP', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16843',
    name: 'Identity Startup Coding Suggestion Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for coding suggestion but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves clinical governance checklist and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'NCQA HEDIS audit', 'AWS HealthLake', 'clinical governance checklist', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16844',
    name: 'HITRUST Documentation Review Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for documentation review but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves adoption plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'FDA SaMD guidance', 'Azure Health Data Services', 'adoption plan', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16845',
    name: 'Claroty Vendor Comparison Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Claroty is used for vendor comparison but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pre-mortem risk and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when Ordr is not proven in production.`,
    keywords: ['Claroty', 'Ordr', 'NIST AI RMF', 'Snowflake Healthcare', 'pre-mortem risk', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16846',
    name: 'Wiz Capacity Forecasting Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Wiz is used for capacity forecasting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves dependency map and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when identity startup is not proven in production.`,
    keywords: ['Wiz', 'identity startup', 'ONC HTI-1', 'Databricks Lakehouse', 'dependency map', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16847',
    name: 'Ordr Staffing Optimization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when Ordr is used for staffing optimization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves approval gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when HITRUST is not proven in production.`,
    keywords: ['Ordr', 'HITRUST', 'TEFCA participation', 'ServiceNow workflow', 'approval gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16848',
    name: 'Identity Startup Quality Abstraction Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when identity startup is used for quality abstraction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves benefit validation plan and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when Claroty is not proven in production.`,
    keywords: ['identity startup', 'Claroty', 'FHIR R4 mapping', 'Salesforce Health Cloud', 'benefit validation plan', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  },
  {
    code: 'H16849',
    name: 'HITRUST Patient Outreach Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Startup Ecosystem: Cyber, Identity & Trust Diligence initiatives fail when HITRUST is used for patient outreach but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when Wiz is not proven in production.`,
    keywords: ['HITRUST', 'Wiz', 'HL7 v2 ADT reconciliation', 'startup maturity evidence', 'unsafe-to-fund gate', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Startup Ecosystem: Cyber, Identity & Trust Diligence',
  }
];
