// seed-cross-industry-part4.ts
// Cross-industry genome patterns — ESG Reporting, Workforce Transformation & Change Management
// Code range: X250–X299  (50 patterns)
// Loaded by: scripts/corpus/load-authored-genome-seeds.ts

type OfficeCategory = 'front_office' | 'middle_office' | 'back_office';

interface PatternSeed {
  code: string;
  name: string;
  officeCategory: OfficeCategory;
  failureRatePct: number;
  description: string;
  keywords: string[];
  demoRelevant?: boolean;
  subTopic?: string;
  verticals?: string[];
}

export const CROSS_INDUSTRY_PART4_PATTERNS: PatternSeed[] = [
  // ── ESG Reporting ────────────────────────────────────────────────────────────
  {
    code: 'X250',
    name: 'SEC Climate Disclosure Rule Compliance Without Board-Level Review',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Organizations subject to SEC Release 33-11275 are building climate disclosure workflows in finance and sustainability teams without establishing the board-level oversight and internal controls attestation that the rule requires, creating a controls gap that external auditors will flag at first examination. The specific mechanism is that Scope 1 and Scope 2 emissions data is being collected and reported by sustainability staff operating outside the financial reporting control environment, so the disclosure is not subject to the same SOX Section 302 and 906 certifications that govern financial statements. This misalignment means the CEO and CFO certify financial reports they have not reviewed for climate disclosure accuracy, exposing them to personal enforcement liability under the rule.`,
    keywords: ['SEC 33-11275', 'climate disclosure', 'board oversight', 'Scope 1 emissions', 'GRI'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'airline', 'manufacturing', 'retail', 'insurance'],
  },
  {
    code: 'X251',
    name: 'CSRD Double Materiality Assessment With Uncertified Data Sources',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `EU CSRD double materiality assessments that map both financial materiality and impact materiality rely on supply chain emissions data, biodiversity impact estimates, and workforce wage data collected from vendors without independent verification, violating CSRD's assurance requirements under European Sustainability Reporting Standards (ESRS). The failure mechanism is that companies confuse a stakeholder engagement process — conducting surveys and interviews — with the evidence-based data collection that ESRS requires, producing an assessment that satisfies the narrative but not the evidentiary standard. First-year limited assurance opinions under CSRD are being denied when auditors discover that material topics lack quantified data trails.`,
    keywords: ['CSRD', 'double materiality', 'ESRS', 'GRI', 'sustainability assurance'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'manufacturing', 'retail', 'healthcare_provider', 'insurance'],
  },
  {
    code: 'X252',
    name: 'Scope 3 Emissions Data Quality Insufficient for Category 11 and 15 Disclosure',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Companies disclosing Scope 3 emissions under GHG Protocol Category 11 (use of sold products) and Category 15 (investments) rely on spend-based proxy data from economic input-output models rather than activity data from value chain partners, producing emissions estimates with uncertainty ranges of 50–300% that undermine both investor decision-making and TCFD scenario analysis. The proximate mechanism is that supplier engagement programmes have not progressed beyond Tier 1, so Tier 2 and Tier 3 suppliers — which often contribute 60–80% of value chain emissions — are estimated using industry averages that do not reflect the supplier's actual energy mix or production efficiency. Whether in a bank's financed emissions under PCAF methodology or a manufacturer's product carbon footprint program, this data quality gap is the primary reason Scope 3 disclosures receive adverse assurance opinions.`,
    keywords: ['Scope 3 emissions', 'GHG Protocol', 'TCFD', 'PCAF', 'CSRD'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'manufacturing', 'airline', 'retail', 'insurance'],
  },
  {
    code: 'X253',
    name: 'TCFD Scenario Analysis Published Without Board Review Sign-Off',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `TCFD-aligned climate scenario analyses included in annual reports and investor presentations are produced by sustainability or risk teams but reviewed only by the CFO or sustainability officer, bypassing the board-level climate risk oversight that TCFD governance pillar recommendations require. This procedural gap is specifically identified in the TCFD 2023 Status Report as one of the most common compliance deficiencies — companies satisfy the disclosure requirement on paper but cannot demonstrate that the board received, debated, and approved the scenario assumptions and risk thresholds. Institutional investors and proxy advisors are increasingly treating unsigned TCFD governance disclosures as a basis for withholding director votes.`,
    keywords: ['TCFD', 'climate risk', 'board governance', 'scenario analysis', 'SASB'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'insurance', 'airline', 'manufacturing', 'healthcare_provider'],
  },
  {
    code: 'X254',
    name: 'ESG AI Reporting Tool Generates Greenwashing-Prone Narrative',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Generative AI tools deployed to draft ESG reports, sustainability narratives, and investor presentations produce qualitatively accurate but selectively optimistic descriptions of ESG performance that omit mandatory negative disclosures required under CSRD, SEC 33-11275, and GRI 2021 standards — creating greenwashing exposure even when the underlying data is accurate. The mechanism is that LLM-generated sustainability narratives are trained on prior ESG reports and marketing materials that reflect aspirational framing, not regulatory disclosure standards, so the model selectively surfaces positive indicators while understating controversies, enforcement actions, and underperformance against targets. SEC staff have issued comment letters to public companies whose AI-assisted sustainability disclosures lacked the balanced presentation required under Regulation S-K.`,
    keywords: ['greenwashing', 'CSRD', 'SEC 33-11275', 'LLM', 'GRI'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'retail', 'airline', 'manufacturing', 'insurance'],
  },
  {
    code: 'X255',
    name: 'ESG Metrics Tracked in Spreadsheets Outside Financial Control Environment',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Energy consumption, water usage, waste diversion, and employee safety data used for SASB and GRI sustainability reporting are collected in departmental spreadsheets with no version control, audit trail, or access governance — creating a data integrity gap that external assurance providers flag as a material weakness in the reporting process. Whether in a health system's energy management program, a bank's operational emissions tracking, or a manufacturer's EHS data collection, the transition from sustainability reporting as a communication exercise to a financially audited disclosure requires migrating these controls into systems that satisfy the same data integrity standards as financial reporting. Companies that fail this transition under CSRD mandatory assurance face disclaimer opinions in their first year of reporting.`,
    keywords: ['ESG reporting', 'SASB', 'GRI', 'data governance', 'sustainability assurance'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'healthcare_provider', 'manufacturing', 'retail', 'airline'],
  },
  {
    code: 'X256',
    name: 'Climate Physical Risk Not Mapped to Asset-Level Operational Dependencies',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Organizations disclose climate physical risk at the enterprise or regional level without mapping acute and chronic climate hazards to specific operational assets — data centers, hospital facilities, manufacturing plants, airport terminals, retail locations — that are exposed to flood, heat stress, or wildfire scenarios, leaving risk quantification meaningless for capital planning and insurance adequacy assessments. TCFD recommends asset-level physical risk assessment as the standard for credible disclosure, and CSRD ESRS E1 requires it for material climate-related impacts, but most organizations use portfolio-level exposure maps that cannot identify which facilities face material risk of disruption within the planning horizon.`,
    keywords: ['TCFD', 'physical climate risk', 'ESRS', 'CSRD', 'asset-level risk'],
    demoRelevant: false,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'insurance'],
  },
  {
    code: 'X257',
    name: 'ESG Rating Agency Divergence Creates Conflicting Stakeholder Signals',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Organizations receive materially different ESG ratings from MSCI, Sustainalytics, ISS ESG, and CDP due to differences in methodology, data sources, and materiality weighting — with score divergence of up to 60 percentage points reported for the same company — causing investor relations teams to field contradictory questions without an authoritative ESG position to defend. The root cause is that each rating agency applies its own GRI-SASB-TCFD interpretation rather than a standardized framework, and companies that do not proactively manage data submissions, dispute incorrect inputs, and publish a reconciliation narrative are subject to rating drift that reflects agency assumptions rather than actual performance.`,
    keywords: ['ESG ratings', 'SASB', 'GRI', 'TCFD', 'sustainability disclosure'],
    demoRelevant: false,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'manufacturing', 'retail', 'airline', 'insurance'],
  },

  // ── Workforce AI ─────────────────────────────────────────────────────────────
  {
    code: 'X258',
    name: 'AI-Driven Workforce Reduction Without WARN Act Triggering Analysis',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Organizations implementing AI automation programs that eliminate roles over a 6–12 month period through attrition, restructuring, and position elimination fail to conduct WARN Act triggering analysis at the program level, treating each departmental reduction as independent when the aggregate meets the 50-employee threshold that requires 60-day advance notice to employees. The failure mechanism is that workforce planning for AI-enabled automation is managed in business units by operations sponsors rather than HR legal, so the enterprise headcount impact is never aggregated against a WARN Act trigger threshold — a gap that creates liability for employers in the healthcare, airline, and manufacturing sectors where AI automation programs are eliminating 5–15% of mid-tier roles. Employment law attorneys report that 2025–2026 AI automation rollouts are generating the first wave of WARN Act class action litigation under this theory.`,
    keywords: ['WARN Act', 'workforce reduction', 'AI automation', 'employment law', 'headcount planning'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['healthcare_provider', 'airline', 'banking', 'manufacturing', 'retail'],
  },
  {
    code: 'X259',
    name: 'Algorithmic Performance Management Without Employment Law Review',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `AI-powered performance management systems that score employees on productivity metrics — keystrokes, call resolution rates, claim processing throughput, patient throughput per shift — and generate automated performance improvement plan recommendations or termination flags are deployed without employment law review for algorithmic bias, disparate impact, and NLRA Section 7 rights implications. The mechanism is that HR technology purchases are approved in a technology procurement process that does not include employment law counsel review, so the vendor's accuracy and productivity claims are accepted without assessing whether the system's outputs meet the legal standard for a documented, bias-free performance basis for adverse employment actions. EEOC has issued AI hiring and performance guidance specifically citing algorithmic management tools as high-risk AI systems requiring disparate impact testing under Title VII.`,
    keywords: ['algorithmic management', 'EEOC', 'Title VII', 'ISO 30414', 'employment law'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['healthcare_provider', 'retail', 'banking', 'manufacturing', 'airline'],
  },
  {
    code: 'X260',
    name: 'AI Scheduling System Deployed Without Labor Contract Compliance Review',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Automated AI scheduling tools deployed to optimize shift coverage, minimize overtime, and improve patient-to-nurse ratios or store staffing levels are deployed without a labor contract compliance review that maps scheduling algorithm outputs to CBA rest period provisions, seniority bid rights, and minimum call-in notice requirements, generating grievances at a rate 3–5 times higher than manual scheduling. Whether in airline crew pairing, hospital nursing float scheduling, or retail labor optimization, the AI algorithm optimizes for operational efficiency and cost while the collective bargaining agreement requires the scheduler to prioritize seniority rights and prescribed rest cycles — a conflict that causes union grievances, arbitration, and in healthcare, potential CMS Conditions of Participation violations when nurse-to-patient ratios are breached.`,
    keywords: ['AI scheduling', 'collective bargaining', 'CBA compliance', 'ISO 30414', 'labor contract'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['airline', 'healthcare_provider', 'retail', 'manufacturing', 'banking'],
  },
  {
    code: 'X261',
    name: 'AI Upskilling Program ROI Not Measured Against Pre-Training Baseline',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Enterprise AI upskilling programs — generative AI literacy courses, prompt engineering training, data science academies, low-code automation certifications — deploy training content and report completion rates without measuring change in job performance, output quality, or business metric impact against a pre-training baseline, producing no evidence that $5–15M upskilling investments changed how employees actually work. The failure mechanism is that learning and development programs measure inputs (course completions, satisfaction scores, certification passes) rather than outputs (task completion time, error rates, decision quality), violating the ISO 30414 human capital reporting framework's requirement that workforce development investments be measured by outcome, not activity.`,
    keywords: ['AI upskilling', 'ISO 30414', 'workforce development', 'ROI measurement', 'human capital'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['banking', 'healthcare_provider', 'retail', 'manufacturing', 'insurance'],
  },
  {
    code: 'X262',
    name: 'Generative AI Copilot Deployed Without Role-Specific Accuracy Threshold',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `LLM copilot tools deployed to assist clinicians with documentation, analysts with credit memo drafting, or engineers with code review operate without role-specific accuracy thresholds below which the tool should be disabled or escalated — allowing tools with 20–30% error rates to remain in production use because the overall satisfaction score is positive. The mechanism is that AI procurement and deployment decisions measure aggregate user satisfaction while ignoring role-specific quality thresholds: a 15% hallucination rate in marketing copy may be acceptable while the same rate in a clinical discharge summary is clinically unsafe and a HIPAA liability, but enterprise AI deployment frameworks do not differentiate.`,
    keywords: ['LLM copilot', 'accuracy threshold', 'AI governance', 'HIPAA', 'hallucination rate'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['healthcare_provider', 'banking', 'insurance', 'manufacturing', 'retail'],
  },
  {
    code: 'X263',
    name: 'Workforce Displacement Communication Delegated to Middle Management Without Script',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `When AI automation programs eliminate roles, communications about role changes, transition options, and reskilling pathways are delegated to line managers who lack training, talking points, or authority to answer key employee questions about timelines and severance, producing rumor-driven attrition that loses the employees the organization planned to redeploy and retains those it did not. ISO 30414 guidance on workforce restructuring communications requires that organizations prepare a structured communication plan with role clarity for line managers, Q&A scripts, and escalation paths to HR before announcing restructuring — a discipline that transformation programs consistently under-resource relative to the technical implementation.`,
    keywords: ['workforce transformation', 'ISO 30414', 'change communication', 'WARN Act', 'change management'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['banking', 'retail', 'healthcare_provider', 'manufacturing', 'airline'],
  },

  // ── Change Management ────────────────────────────────────────────────────────
  {
    code: 'X264',
    name: 'Digital Transformation Change Fatigue Caused by Sequential Initiative Waves',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `Organizations that launch ERP migrations, AI deployments, operating model redesigns, and workforce restructuring programs in sequential 12–18 month waves without allowing recovery time between initiatives produce measurable change fatigue — declining engagement scores, rising voluntary turnover among change champions, and increasing passive resistance to the next initiative from managers who survived the previous one. The mechanism is that transformation program offices sequence initiatives based on project dependency logic rather than organizational absorption capacity, so each successive wave arrives before the last one has been embedded in routine practice, producing a workforce that instinctively treats new initiatives as temporary disruptions rather than permanent operating model changes.`,
    keywords: ['change fatigue', 'organizational change management', 'OCM', 'change adoption', 'digital transformation'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },
  {
    code: 'X265',
    name: 'Adoption Rate Measurement Stops At Go-Live — Post-Launch Decay Invisible',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `Digital transformation programs measure adoption at go-live — logins, completions, and satisfaction scores in the first 90 days — but stop measuring at the point where sustained behavior change is most at risk, missing the post-90-day adoption decay that occurs when change management support is withdrawn and pre-existing workarounds reassert themselves. Whether in a bank's CRM deployment, a hospital's Epic optimization, or a manufacturer's ERP rollout, Prosci ADKAR research consistently shows that adoption rates at 30 days do not predict adoption at 12 months, and programs that measure only go-live adoption systematically overstate benefit realization because the productivity gains they forecast assume sustained behavior change that is never verified.`,
    keywords: ['adoption measurement', 'Prosci ADKAR', 'change management', 'OCM', 'benefit realization'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },
  {
    code: 'X266',
    name: 'OCM Framework Deployed Without Identified Executive Sponsor',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Organizational change management programs deploy Prosci or Kotter-based frameworks — stakeholder assessments, impact analyses, communication plans, and training curricula — without a named executive sponsor who attends steering committee meetings, visibly champions the change, and removes organizational blockers, producing a structurally complete OCM program that stalls when it encounters middle management resistance. Prosci benchmarking consistently identifies executive sponsorship as the single most important factor in change success, and the specific failure mode is confusing a nominal executive sponsor (a name on the charter) with an active one (an executive who sends program communications, attends employee forums, and escalates resistance to the leadership team).`,
    keywords: ['OCM', 'Prosci ADKAR', 'executive sponsorship', 'change management', 'organizational change'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },
  {
    code: 'X267',
    name: 'Benefits Realization Measured Without Pre-Program Baseline',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Transformation programs publish post-implementation benefit claims — 20% reduction in cycle time, $15M in productivity savings, 30% improvement in first-call resolution — without having measured the pre-program baseline against which these improvements are claimed, making it impossible to attribute changes to the program versus market conditions, seasonal effects, or concurrent initiatives. The mechanism is that program business cases are built on aspirational targets rather than measured baselines, so the benefits tracking framework inherits the assumption rather than the measurement, and benefit realization reviews become narrative exercises rather than evidence-based assessments that satisfy a board audit committee or justify the next phase of investment.`,
    keywords: ['benefits realization', 'OCM', 'change management', 'Prosci ADKAR', 'baseline measurement'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },
  {
    code: 'X268',
    name: 'Super-User Network Built for Go-Live But Not Sustained Post-Launch',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Digital transformation programs invest in super-user networks — frontline champions trained to provide peer support, absorb escalations, and sustain adoption — but backfill these champions' day-job workload only during the go-live period, so super-users revert to their operational roles within 60–90 days and the peer support network dissolves before sustained behavior change has been achieved. Without a formal post-go-live super-user role definition, protected time allocation, and performance recognition, the network that was critical for go-live becomes unavailable for the 6–18 month period when adoption reinforcement is most needed.`,
    keywords: ['super-user network', 'OCM', 'change adoption', 'Prosci ADKAR', 'change management'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['banking', 'healthcare_provider', 'retail', 'airline', 'manufacturing'],
  },
  {
    code: 'X269',
    name: 'Resistance to AI Tools Misdiagnosed as Training Gap Rather Than Trust Gap',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `When frontline employees resist adopting AI tools — clinical decision support, AI-assisted underwriting, predictive maintenance alerts — program teams respond with additional training and job aids when the actual barrier is distrust of the AI output quality, concerns about accountability when the AI recommendation is wrong, or anxiety about job displacement, none of which are resolved by more training. Prosci ADKAR diagnosis distinguishes between resistance rooted in knowledge gaps (addressed by training) and resistance rooted in reinforcement, desire, or awareness gaps (addressed by sponsorship, incentive alignment, and communication), and programs that consistently deploy training solutions for non-training resistance achieve adoption ceilings of 40–60% regardless of training investment.`,
    keywords: ['AI adoption', 'change management', 'Prosci ADKAR', 'OCM', 'digital transformation'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['healthcare_provider', 'banking', 'insurance', 'retail', 'airline'],
  },
  {
    code: 'X270',
    name: 'Training Theatre Deployed Without Workflow-Embedded Performance Support',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Organizations invest in classroom and eLearning training for new systems and processes but do not provide workflow-embedded performance support — in-application guidance, digital adoption platforms, contextual help, or decision trees available at the moment of need — so knowledge acquired in training degrades rapidly when employees return to high-volume operational environments without access to just-in-time assistance. Research by Gartner on digital adoption platforms consistently shows that 70% of knowledge from instructor-led training is forgotten within a week when not reinforced by performance support at the point of application, yet most transformation programs allocate over 80% of the training budget to pre-go-live instruction and under 20% to post-go-live reinforcement.`,
    keywords: ['training theatre', 'digital adoption platform', 'OCM', 'change management', 'performance support'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['healthcare_provider', 'banking', 'retail', 'airline', 'manufacturing'],
  },

  // ── Organizational Design ────────────────────────────────────────────────────
  {
    code: 'X271',
    name: 'Matrix Accountability Gaps Delay AI Initiative Decision-Making',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Matrix organizations running digital and AI transformation programs produce accountability gaps when the AI program owner sits in IT, the budget owner sits in Finance, the data owner sits in Analytics, and the outcome owner sits in Operations — creating a four-party approval chain for every material decision that slows initiative velocity and produces decisions by exhaustion rather than authority. Whether in a health system's clinical AI governance or a bank's digital transformation program, RACI matrices that assign responsibility but not unilateral decision authority create structures where every significant choice requires consensus among parties with competing functional interests, and the transformations that succeed are those where a single empowered role has authority to resolve the inevitable data-process-technology tradeoffs.`,
    keywords: ['matrix organization', 'RACI', 'decision rights', 'AI governance', 'organizational design'],
    demoRelevant: true,
    subTopic: 'organizational-design',
    verticals: ['banking', 'healthcare_provider', 'manufacturing', 'airline', 'insurance'],
  },
  {
    code: 'X272',
    name: 'Role Clarity in AI-Augmented Workflows Not Redefined at Deployment',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `When AI tools are deployed to augment human decision-making — clinical documentation AI, AI-assisted underwriting, predictive maintenance alerts — organizations do not redefine job roles, performance expectations, or accountability frameworks to reflect the AI-human workflow, leaving employees uncertain about when to follow, override, or escalate AI recommendations and managers unable to evaluate performance in the new model. The specific mechanism is that job descriptions, performance appraisal rubrics, and training curricula are written for the pre-AI workflow and are not updated at go-live, so employees have no authoritative guidance on the skill shifts required — from information gathering to AI output evaluation — that the new workflow demands.`,
    keywords: ['role clarity', 'AI-augmented workflow', 'organizational design', 'ISO 30414', 'change management'],
    demoRelevant: true,
    subTopic: 'organizational-design',
    verticals: ['healthcare_provider', 'banking', 'insurance', 'manufacturing', 'retail'],
  },
  {
    code: 'X273',
    name: 'Center of Excellence vs Federated Model Tension Paralyzes AI Delivery',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Organizations oscillate between centralized AI Centers of Excellence that impose standards but cannot meet business unit delivery timelines, and federated AI models where business units move fast but produce inconsistent governance, duplicate capability, and incompatible data models — spending more energy managing the organizational model than building AI products. The failure is predictable because neither pure model works at enterprise scale without an explicit federated governance framework that defines which decisions are centralized (standards, risk tiering, vendor contracts) and which are decentralized (use case selection, deployment pace, domain customization), and most enterprises make the CoE-vs-federated choice without defining this framework first.`,
    keywords: ['center of excellence', 'federated AI', 'AI governance', 'organizational design', 'digital transformation'],
    demoRelevant: true,
    subTopic: 'organizational-design',
    verticals: ['banking', 'healthcare_provider', 'manufacturing', 'airline', 'retail'],
  },
  {
    code: 'X274',
    name: 'Governance Committee Chartered Without Decision Rights Defined',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Digital transformation governance committees — AI oversight boards, data councils, enterprise architecture review boards — are chartered with membership lists, meeting cadences, and reporting responsibilities but without explicit decision rights that define what questions the committee can resolve versus what it escalates to the executive team, producing governance bodies that generate discussion but cannot resolve disputes. Without a formal decision rights taxonomy that maps each governance domain to a decision type (inform, consult, approve, veto) and an escalation path for unresolved disputes, committees become forums where functional leaders defend their units' interests and transformation sponsors lose momentum waiting for decisions that never come.`,
    keywords: ['governance committee', 'decision rights', 'RACI', 'organizational design', 'digital transformation'],
    demoRelevant: true,
    subTopic: 'organizational-design',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },
  {
    code: 'X275',
    name: 'Transformation PMO Owns Delivery Schedule But Not Accountability for Outcomes',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Program management offices for digital transformations are structured to track delivery — on-time, on-budget, milestone completion — without accountability for business outcomes, so PMOs produce on-schedule programs that deliver minimal business value because outcome ownership remains diffuse across business units that were not required to commit to measurable goals in exchange for transformation investment. The organizational design failure is that PMO and business unit roles are separated by a boundary where the PMO owns delivery evidence and the business unit owns outcome evidence, but no governance body holds both parties jointly accountable for the value the program was designed to produce.`,
    keywords: ['PMO', 'benefits realization', 'organizational design', 'OCM', 'digital transformation'],
    demoRelevant: true,
    subTopic: 'organizational-design',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },

  // ── Talent Technology ────────────────────────────────────────────────────────
  {
    code: 'X276',
    name: 'Shadow IT Proliferation Accumulates Technical Debt Outside IT Governance',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Business units deploy departmental databases, SaaS subscriptions, cloud workloads, and API integrations outside IT governance review, creating a shadow IT portfolio that accumulates security vulnerabilities, data governance gaps, and unsustainable integration debt that is invisible in enterprise architecture reviews. The mechanism is that cloud self-service procurement — AWS credits, Microsoft 365 add-on licenses, low-code platform subscriptions — enables business users to create production systems without IT involvement, and the resulting portfolio is only discovered when a security incident, regulatory audit, or employee departure exposes the dependency on unmanaged systems.`,
    keywords: ['shadow IT', 'technical debt', 'IT governance', 'cloud governance', 'FinOps'],
    demoRelevant: true,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'manufacturing', 'retail', 'insurance'],
  },
  {
    code: 'X277',
    name: 'Citizen Developer Power Platform Sprawl Without Governance Framework',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Microsoft Power Platform, Salesforce Flow, and ServiceNow App Engine citizen developer programs produce hundreds of departmental applications, automated workflows, and AI-integrated tools that bypass enterprise architecture review, security assessment, and data governance registration — creating a long-tail of unmanaged business logic embedded in citizen-built tools that cannot be discovered, audited, or maintained when their creators leave. Microsoft's own Power Platform adoption guidance recommends a Center of Excellence toolkit with environment strategy, DLP policies, and connector governance before citizen developer programs exceed 50 active makers, a governance prerequisite that most organizations skip in the enthusiasm of the initial adoption wave.`,
    keywords: ['citizen developer', 'Power Platform', 'low-code governance', 'shadow IT', 'IT governance'],
    demoRelevant: true,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'retail', 'manufacturing', 'insurance'],
  },
  {
    code: 'X278',
    name: 'FinOps Cloud Cost Governance Without Engineering Accountability',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Cloud FinOps programs that centralize cost reporting in a finance or platform team without embedding cost accountability in engineering teams produce accurate cost reports that do not drive cost optimization behavior, because the engineers making resource allocation decisions see utilization metrics but not the financial implications of their choices. FinOps Foundation best practices explicitly require "Inform" stage cost visibility to be followed by "Optimize" stage unit economics that tie engineering decisions — instance size, data retention, idle resource cleanup — to financial outcomes at the team or service level, a structural requirement that programs limited to centralized reporting cannot fulfill.`,
    keywords: ['FinOps', 'cloud cost governance', 'cloud governance', 'IT governance', 'FinOps Foundation'],
    demoRelevant: true,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'retail', 'airline', 'manufacturing'],
  },
  {
    code: 'X279',
    name: 'AI Code Assistant Deployment Without Secure Code Review Policy',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Organizations deploy GitHub Copilot, Amazon CodeWhisperer, or similar AI code assistants to engineering teams without establishing policies for AI-generated code review, prohibited code suggestion acceptance patterns, and security scanning before AI-generated code is merged — introducing vulnerabilities, license-incompatible open source inclusions, and data handling patterns that bypass standard code review governance. The specific risk for financial services, healthcare, and regulated manufacturers is that AI code assistants suggest code patterns trained on public repositories that do not reflect the organization's secure coding standards, and engineers who accept suggestions without security review introduce CWE-listed vulnerabilities that static analysis tools later flag as production findings after deployment.`,
    keywords: ['AI code assistant', 'GitHub Copilot', 'secure code review', 'IT governance', 'shadow IT'],
    demoRelevant: true,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'medtech', 'manufacturing', 'insurance'],
  },
  {
    code: 'X280',
    name: 'SaaS Renewal Concentration Risk From Auto-Renewal Proliferation',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Organizations that allow SaaS subscriptions to auto-renew without centralized tracking accumulate renewal concentration risk in Q1 and Q4, when the majority of enterprise SaaS contracts renew simultaneously — limiting procurement leverage because each renewal is addressed reactively rather than as part of a portfolio negotiation strategy. The compounding failure is that auto-renewing SaaS contracts often include evergreen CPI escalation clauses of 5–8% annually, meaning a $10M SaaS portfolio auto-renewing for five years without negotiation reaches $13–14M without any additional capability being delivered.`,
    keywords: ['SaaS renewal', 'auto-renewal', 'TPRM', 'vendor contract', 'FinOps'],
    demoRelevant: false,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'retail', 'airline', 'manufacturing'],
  },
  {
    code: 'X281',
    name: 'AI-Assisted Talent Acquisition Tool Creates EEOC Adverse Impact',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `AI resume screening, candidate scoring, and interview scheduling tools deployed without adverse impact testing under the Uniform Guidelines on Employee Selection Procedures produce selection rates that create statistically significant disparities against protected demographic classes, creating EEOC Title VII liability and state-level algorithmic hiring law exposure in jurisdictions including New York City Local Law 144 and Illinois AEIA. The mechanism is that AI hiring tools trained on historical hiring decisions inherit the demographic composition of past accepted candidates as a proxy for "success," reinforcing the same demographic selection patterns the organization may have been working to change through diversity hiring programs.`,
    keywords: ['AI hiring', 'EEOC', 'Title VII', 'adverse impact', 'algorithmic hiring'],
    demoRelevant: true,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'retail', 'airline', 'manufacturing'],
  },
  {
    code: 'X282',
    name: 'Technical Debt Quantification Absent From Architecture Review',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Enterprise architecture review boards evaluate proposed technology investments for strategic alignment, integration risk, and vendor viability but do not produce or consume a quantified technical debt register that tracks the cost of maintaining legacy systems, the risk of deferred modernization, and the compounding interest of workarounds and manual interventions — leaving budget decisions without the financial framing needed to compete with new capability investment. Without a technical debt register quantified in developer hours, operational risk, and opportunity cost, architecture governance defaults to a qualitative scoring of strategic fit that systematically underweights the true cost of carrying legacy platform dependencies.`,
    keywords: ['technical debt', 'IT governance', 'shadow IT', 'architecture review', 'cloud governance'],
    demoRelevant: false,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },

  // ── Culture Risk ─────────────────────────────────────────────────────────────
  {
    code: 'X283',
    name: 'Psychological Safety Survey Results Not Actioned Within 90 Days',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Employee engagement and psychological safety surveys that surface concerns about speaking up, reporting errors, and challenging leadership decisions are published to managers with scores but without funded action plans, response timelines, or follow-up measurement — creating a survey-to-silence pattern where employees who invested effort in providing candid feedback observe no visible change, causing response rates and candor to decline in successive survey cycles. The harm is compounded in regulated environments where psychological safety is a direct patient safety, credit risk, or operational resilience risk factor: Edmondson's research and The Joint Commission's safety culture frameworks both establish that teams with low psychological safety report fewer safety events, not because fewer events occur, but because under-reporting norms suppress the organizational learning that prevents recurrence.`,
    keywords: ['psychological safety', 'organizational culture', 'employee engagement', 'change management', 'ISO 30414'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['healthcare_provider', 'banking', 'airline', 'manufacturing', 'insurance'],
  },
  {
    code: 'X284',
    name: 'DEI Metric Gaming Through Proxy Indicator Selection',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Organizations respond to DEI reporting requirements and investor ESG questionnaires by selecting metrics that are achievable with existing data and favorable to the organization — representation at the total workforce level rather than senior leadership, pay equity for roles with narrow job families, and hiring parity without measuring retention or promotion equity — producing disclosures that satisfy formal compliance without addressing the structural inequities that DEI programs are designed to correct. SASB and GRI 401 workforce standards require disclosure of pay equity by gender and race at the same level of analysis used for performance management, a requirement that proxy indicator selection systematically avoids because the within-level analysis exposes disparities that headline representation statistics obscure.`,
    keywords: ['DEI metrics', 'GRI', 'SASB', 'pay equity', 'ISO 30414'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'retail', 'manufacturing', 'insurance'],
  },
  {
    code: 'X285',
    name: 'Innovation Incentive Structure Rewards Velocity Over Quality',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `Innovation labs, digital accelerators, and startup studios embedded in large enterprises create incentive structures that reward speed to prototype and volume of ideas submitted while penalizing the rigorous evaluation and scaling discipline that converts pilots into business value — producing high prototype-to-production ratios where 90–95% of pilots never scale, and a culture where ideation is celebrated and execution is invisible. Whether in a bank's fintech incubator, a health system's digital health accelerator, or a manufacturer's Industry 4.0 lab, the organizational failure is separating the incentive structure of the innovation unit from the business units that must absorb, operate, and gain value from the innovations it produces, making the innovation portfolio a cost center rather than a value generator.`,
    keywords: ['innovation culture', 'organizational design', 'change management', 'digital transformation', 'OCM'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'manufacturing', 'retail', 'insurance'],
  },
  {
    code: 'X286',
    name: 'Post-Merger Culture Integration Failure Drives AI Program Abandonment',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Post-merger organizations that launch shared AI, data, and digital transformation programs before cultural integration has occurred experience program abandonment rates 2–3 times higher than organic transformations, because employees and managers from the acquired entity treat enterprise programs as instruments of cultural assimilation rather than shared investment, generating passive resistance that delays adoption beyond the point where program economics can be justified. The failure mechanism is that M&A integration teams treat technology stack rationalization and workforce headcount planning as the integration deliverables, while culture — shared operating norms, decision-making styles, and psychological safety — is treated as a soft dimension that resolves over time without deliberate investment.`,
    keywords: ['post-merger integration', 'culture integration', 'change management', 'OCM', 'organizational design'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'manufacturing', 'retail', 'insurance'],
  },
  {
    code: 'X287',
    name: 'Accountability Vacuum When AI Makes Wrong Decision',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `When AI-assisted decisions produce adverse outcomes — a credit denial that causes regulatory complaint, a clinical recommendation that contributes to a patient harm event, or a pricing decision that draws DOT scrutiny — organizations discover that no governance document assigns accountability for AI-related adverse outcomes to a named individual or role, creating a diffusion of responsibility that prevents learning from error and creates regulatory exposure. The EU AI Act's operator accountability requirements and the OCC's model risk management guidance both require that high-risk AI systems have a named accountable owner for model outcomes, but in practice AI accountability is assigned at the program level to a sponsor who left, a vendor who disclaims liability, and an IT team that built the integration but not the model.`,
    keywords: ['AI accountability', 'AI governance', 'organizational design', 'EU AI Act', 'SR 11-7'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'insurance', 'manufacturing', 'retail'],
  },
  {
    code: 'X288',
    name: 'Middle Management Veto Power Blocks AI Adoption Without Formal Escalation Path',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Middle managers who perceive AI tools as threats to their decision-making authority, headcount justification, or operational control informally block adoption by withholding user access, undermining training, and creating narratives of system unreliability — without triggering any formal escalation path in the transformation governance structure that would surface the resistance to executive sponsors. Prosci benchmarking of change programs identifies middle management resistance as the second most common reason for AI and digital transformation program failure, and the specific governance gap is that transformation programs define a change leadership coalition at the executive and frontline levels while treating middle management as a relay layer rather than a change constituency requiring its own engagement strategy.`,
    keywords: ['middle management resistance', 'change management', 'Prosci ADKAR', 'OCM', 'AI adoption'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'airline', 'manufacturing', 'retail'],
  },

  // ── Additional cross-cutting ESG, workforce, and culture patterns ─────────────
  {
    code: 'X289',
    name: 'ESG Data Aggregation AI Tool Creates Disclosure Inconsistency Across Frameworks',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `AI tools deployed to aggregate and normalize ESG data across GRI, SASB, TCFD, and CSRD reporting frameworks produce framework-specific reports that use the same underlying metric with different boundary definitions, calculation methodologies, and temporal scopes — creating numerical inconsistencies between concurrent disclosures that external assurance providers flag as material discrepancies. The mechanism is that AI aggregation tools apply framework mapping rules at the output layer rather than governing data boundary definitions, scope, and calculation methodology at the data model layer, so the same energy consumption metric reports differently in a GRI 302 disclosure versus a CSRD ESRS E1 disclosure because the organizational boundary assumptions differ.`,
    keywords: ['ESG reporting', 'GRI', 'CSRD', 'TCFD', 'SASB'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['banking', 'manufacturing', 'retail', 'airline', 'insurance'],
  },
  {
    code: 'X290',
    name: 'Workforce Reskilling Program Targets Wrong Roles for AI Displacement',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Workforce transformation programs invest reskilling budgets in roles identified by job title analysis as most exposed to AI displacement, while the actual displacement risk — determined by task composition, not job title — falls on roles spread across multiple titles where a subset of tasks are automatable but the overall role is not, wasting reskilling investment on roles that are structurally safe while leaving genuinely at-risk task clusters without transition support. McKinsey's task-based AI displacement methodology, which maps automation probability at the task level rather than the job level, consistently identifies that headline job displacement numbers are overstated for role-based analyses and understated for task-based analyses, meaning organizations targeting "at-risk roles" are solving the wrong problem.`,
    keywords: ['workforce transformation', 'reskilling', 'ISO 30414', 'AI displacement', 'change management'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['banking', 'retail', 'healthcare_provider', 'manufacturing', 'insurance'],
  },
  {
    code: 'X291',
    name: 'Transformation Governance Board Meets Too Infrequently to Unblock Dependencies',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Transformation steering committees that meet monthly or quarterly cannot unblock the cross-functional dependencies — data access approvals, vendor contract modifications, headcount reallocation decisions, process exception requests — that accumulate between meeting cycles and slow initiative delivery by 4–8 weeks per dependency cycle. The organizational design failure is scoping the governance board as a reporting and approval body rather than a dependency resolution mechanism, which requires operating cadences (weekly operating reviews for material dependencies, daily standups for blockers) that are lighter than a steering committee but faster than a monthly reporting cycle.`,
    keywords: ['transformation governance', 'organizational design', 'digital transformation', 'OCM', 'PMO'],
    demoRelevant: true,
    subTopic: 'organizational-design',
    verticals: ['banking', 'healthcare_provider', 'airline', 'manufacturing', 'retail'],
  },
  {
    code: 'X292',
    name: 'FinOps AI Cost Monitoring Not Extended to LLM API Spend',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `FinOps cloud cost governance frameworks that cover compute, storage, and data transfer do not extend cost monitoring, budget guardrails, or unit economics analysis to LLM API usage — OpenAI, Anthropic, Azure OpenAI, Amazon Bedrock — producing budget surprises when AI-powered features scale to production volumes that were not modeled in the proof-of-concept cost estimate. LLM API costs are consumption-based and highly sensitive to prompt length, model version, context window size, and user volume, making them structurally different from fixed-rate IaaS costs and requiring FinOps disciplines — tagging, showback, forecasting, optimization levers — specifically adapted for token-based pricing models.`,
    keywords: ['FinOps', 'LLM API', 'cloud cost governance', 'AI cost management', 'FinOps Foundation'],
    demoRelevant: true,
    subTopic: 'talent-technology',
    verticals: ['banking', 'healthcare_provider', 'retail', 'airline', 'insurance'],
  },
  {
    code: 'X293',
    name: 'ESG Supplier Engagement Program Covers Tier 1 But Not Tier 2 Emissions',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `ESG supply chain due diligence programs that engage Tier 1 suppliers to collect emissions data, labor practice disclosures, and deforestation commitments do not extend supplier engagement to Tier 2 and Tier 3 suppliers — who often represent the majority of scope 3 Purchased Goods and Services emissions and the highest concentration of labor and environmental risk — leaving CSRD and GHG Protocol Category 1 disclosures reliant on Tier 1 assertions about supply chains they do not themselves fully control. Whether in a bank's financed emissions program, a retailer's private label sourcing disclosure, or a manufacturer's product footprint certification, the inability to trace Tier 2+ supply chain data is the primary reason Scope 3 Category 1 disclosures receive qualified assurance opinions.`,
    keywords: ['Scope 3 emissions', 'supply chain ESG', 'CSRD', 'GHG Protocol', 'GRI'],
    demoRelevant: false,
    subTopic: 'esg-reporting',
    verticals: ['retail', 'manufacturing', 'banking', 'healthcare_provider', 'airline'],
  },
  {
    code: 'X294',
    name: 'Culture Transformation Program Without Behavioral Metric Baseline',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Culture transformation programs that declare aspirational values — customer centricity, innovation, accountability, psychological safety — without defining measurable behavioral indicators or establishing a pre-program baseline produce culture change narratives that cannot be validated, leaving boards and executives unable to assess whether the culture investment produced the behavioral shifts that strategy execution requires. The ISO 30414 human capital framework and Deloitte Culture Change research consistently show that culture programs without behavioral metrics default to measuring inputs (town halls delivered, posters displayed, values training completed) rather than outcomes (cross-functional collaboration rates, error reporting frequency, escalation behavior), making it impossible to distinguish culture change from culture theatre.`,
    keywords: ['culture transformation', 'ISO 30414', 'organizational change', 'behavioral metrics', 'change management'],
    demoRelevant: true,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'airline', 'manufacturing', 'insurance'],
  },
  {
    code: 'X295',
    name: 'Hybrid Work Policy Creates Two-Tier Visibility in Performance Management',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Hybrid work arrangements that allow some employees to work in-office and others remotely produce proximity bias in performance evaluations, promotion decisions, and project assignments — with in-office employees receiving disproportionate visibility, sponsorship, and access to informal decision-making — creating a two-tier workforce structure that ISO 30414 and EEOC fair employment principles require organizations to monitor and mitigate. The failure is that hybrid work policies are treated as scheduling decisions rather than organizational design decisions, so performance management frameworks, calibration processes, and promotion criteria are not updated to account for the differential visibility advantage that in-office presence creates.`,
    keywords: ['hybrid work', 'performance management', 'ISO 30414', 'EEOC', 'organizational design'],
    demoRelevant: false,
    subTopic: 'culture-risk',
    verticals: ['banking', 'healthcare_provider', 'retail', 'insurance', 'manufacturing'],
  },
  {
    code: 'X296',
    name: 'Vendor AI ESG Score Tool Not Validated Against Underlying Data',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Procurement and sustainability teams deploy AI-powered vendor ESG scoring tools — Ecovadis, Sustainalytics vendor ratings, supply chain AI platforms — without validating that scores correlate with the underlying sustainability performance the tool claims to measure, accepting proprietary algorithmic scores as proxies for actual supplier compliance without independent verification. The failure is that ESG procurement decisions made on the basis of opaque vendor AI scores cannot be defended under CSRD supply chain due diligence requirements or the German LkSG Supply Chain Act if the methodology is not traceable and the scores are not externally validated, creating regulatory exposure when a high-scoring supplier is subsequently found to have material labor or environmental violations.`,
    keywords: ['ESG procurement', 'CSRD', 'GRI', 'AI vendor scoring', 'supply chain due diligence'],
    demoRelevant: true,
    subTopic: 'esg-reporting',
    verticals: ['manufacturing', 'retail', 'banking', 'healthcare_provider', 'airline'],
  },
  {
    code: 'X297',
    name: 'AI Performance Monitoring Cadence Misaligned With Union Contract Review Cycle',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Organizations that deploy AI scheduling, productivity monitoring, and performance scoring tools in unionized environments do not align the AI model monitoring and recalibration cadence with the collective bargaining agreement review cycle, so model updates that change algorithmic treatment of employees — new scoring weights, adjusted productivity thresholds, modified scheduling priority rules — take effect without the notice and bargaining obligations that most CBAs require for changes to performance standards and work rules. In healthcare, airline, and manufacturing environments with active union agreements, deploying an AI model update without CBA notice and bargaining review creates unfair labor practice exposure under NLRA Section 8(a)(5) that is separate from and additive to any disparate impact claims.`,
    keywords: ['AI monitoring', 'collective bargaining', 'NLRA', 'ISO 30414', 'labor contract'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['airline', 'healthcare_provider', 'manufacturing', 'retail', 'banking'],
  },
  {
    code: 'X298',
    name: 'Digital Transformation Benefits Leak Through Unmanaged Process Reversion',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `Transformation programs that achieve measurable productivity and cycle time improvements at go-live lose 40–60% of those gains within 12 months as employees revert to pre-transformation workarounds, manual overrides accumulate, and exception-handling processes that were designed as temporary accommodations become the new standard operating procedure without triggering a governance review. The Prosci benefits realization framework identifies process reversion as the leading cause of benefit leakage post-implementation, with the root cause being that transformation programs close their governance structures at go-live, withdrawing the oversight that would detect and address the gradual normalization of non-standard practices before they permanently erode the efficiency gains.`,
    keywords: ['benefits realization', 'process reversion', 'OCM', 'Prosci ADKAR', 'change management'],
    demoRelevant: true,
    subTopic: 'change-management',
    verticals: ['banking', 'healthcare_provider', 'airline', 'retail', 'manufacturing'],
  },
  {
    code: 'X299',
    name: 'AI Accountability Gap Between HR Policy and Technology Governance',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Organizations maintain separate governance tracks for HR policy — covering employee rights, performance management, and workplace fairness — and technology governance — covering AI model deployment, algorithmic decision systems, and data use — with no formal integration point that ensures HR employment law obligations are applied to AI tools that make or inform employment decisions. The result is that AI performance scoring, attendance monitoring, and productivity tracking tools pass technology governance review for accuracy and security without being evaluated against the employment law standards that HR policy applies to human supervisor decisions, creating a compliance gap that EEOC guidance on AI and Title VII, and NYC Local Law 144 on automated employment decisions, specifically target.`,
    keywords: ['AI employment law', 'EEOC', 'AI governance', 'ISO 30414', 'algorithmic management'],
    demoRelevant: true,
    subTopic: 'workforce-ai',
    verticals: ['banking', 'healthcare_provider', 'retail', 'manufacturing', 'insurance'],
  },
];
