/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 80: Board Strategy, Innovation Portfolio & Venture Partnerships
// Part 4: H19950-H19999
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM80_PART4_PATTERNS = [
  {
    code: 'H19950',
    name: 'Innovation Portfolio Cohort Matching Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for cohort matching but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is model registry: AbarVa should turn this into a Moves benefit validation plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'model registry', 'clinical advisory board', 'benefit validation plan', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19951',
    name: 'Venture Partnership Contract Analysis Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for contract analysis but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'deployment-site validation', 'FDA submission posture', 'unsafe-to-fund gate', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19952',
    name: 'AI Strategy Agentic Orchestration Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for agentic orchestration but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves value realization ledger and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'MLOps monitoring', 'KLAS commentary', 'value realization ledger', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19953',
    name: 'Board Governance Coding Suggestion Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for coding suggestion but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pilot success metric and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'clinical safety review', 'Epic App Orchard integration', 'pilot success metric', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19954',
    name: 'Portfolio Value Documentation Review Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for documentation review but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves clinical governance checklist and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'procurement RFP scoring', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19955',
    name: 'Innovation Portfolio Vendor Comparison Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for vendor comparison but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves adoption plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'BAFO contract clause', 'AWS HealthLake', 'adoption plan', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19956',
    name: 'Venture Partnership Capacity Forecasting Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for capacity forecasting but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves pre-mortem risk and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'HIPAA BAA', 'Azure Health Data Services', 'pre-mortem risk', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19957',
    name: 'AI Strategy Staffing Optimization Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for staffing optimization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves dependency map and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'minimum necessary policy', 'Snowflake Healthcare', 'dependency map', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19958',
    name: 'Board Governance Quality Abstraction Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for quality abstraction but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves approval gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'TJC survey evidence', 'Databricks Lakehouse', 'approval gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19959',
    name: 'Portfolio Value Patient Outreach Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for patient outreach but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is CMS CoP: AbarVa should turn this into a Moves benefit validation plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'CMS CoP', 'ServiceNow workflow', 'benefit validation plan', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19960',
    name: 'Innovation Portfolio Triage Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for triage but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'NCQA HEDIS audit', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19961',
    name: 'Venture Partnership Drafting Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for drafting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves value realization ledger and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'FDA SaMD guidance', 'startup maturity evidence', 'value realization ledger', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19962',
    name: 'AI Strategy Summarization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for summarization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pilot success metric and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'NIST AI RMF', 'SOC 2 Type II', 'pilot success metric', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19963',
    name: 'Board Governance Risk Scoring Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for risk scoring but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves clinical governance checklist and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'ONC HTI-1', 'HITRUST roadmap', 'clinical governance checklist', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19964',
    name: 'Portfolio Value Worklist Prioritization Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for worklist prioritization but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves adoption plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'TEFCA participation', 'Series B burn rate', 'adoption plan', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19965',
    name: 'Innovation Portfolio Appeal Generation Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for appeal generation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves pre-mortem risk and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'FHIR R4 mapping', 'implementation partner capacity', 'pre-mortem risk', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19966',
    name: 'Venture Partnership Order Recommendation Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for order recommendation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves dependency map and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'HL7 v2 ADT reconciliation', 'referenceable health-system customer', 'dependency map', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19967',
    name: 'AI Strategy Benefit Verification Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for benefit verification but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is Epic change control: AbarVa should turn this into a Moves approval gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'Epic change control', 'clinical advisory board', 'approval gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19968',
    name: 'Board Governance Eligibility Prediction Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for eligibility prediction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is model registry: AbarVa should turn this into a Moves benefit validation plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'model registry', 'FDA submission posture', 'benefit validation plan', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19969',
    name: 'Portfolio Value Care Gap Closure Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for care gap closure but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'deployment-site validation', 'KLAS commentary', 'unsafe-to-fund gate', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19970',
    name: 'Innovation Portfolio Cohort Matching Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for cohort matching but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves value realization ledger and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'MLOps monitoring', 'Epic App Orchard integration', 'value realization ledger', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19971',
    name: 'Venture Partnership Contract Analysis Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for contract analysis but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pilot success metric and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'clinical safety review', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19972',
    name: 'AI Strategy Agentic Orchestration Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for agentic orchestration but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves clinical governance checklist and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'procurement RFP scoring', 'AWS HealthLake', 'clinical governance checklist', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19973',
    name: 'Board Governance Coding Suggestion Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for coding suggestion but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves adoption plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'BAFO contract clause', 'Azure Health Data Services', 'adoption plan', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19974',
    name: 'Portfolio Value Documentation Review Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for documentation review but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves pre-mortem risk and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'HIPAA BAA', 'Snowflake Healthcare', 'pre-mortem risk', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19975',
    name: 'Innovation Portfolio Vendor Comparison Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for vendor comparison but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves dependency map and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'minimum necessary policy', 'Databricks Lakehouse', 'dependency map', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19976',
    name: 'Venture Partnership Capacity Forecasting Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for capacity forecasting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves approval gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'TJC survey evidence', 'ServiceNow workflow', 'approval gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19977',
    name: 'AI Strategy Staffing Optimization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for staffing optimization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is CMS CoP: AbarVa should turn this into a Moves benefit validation plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'CMS CoP', 'Salesforce Health Cloud', 'benefit validation plan', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19978',
    name: 'Board Governance Quality Abstraction Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for quality abstraction but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'NCQA HEDIS audit', 'startup maturity evidence', 'unsafe-to-fund gate', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19979',
    name: 'Portfolio Value Patient Outreach Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for patient outreach but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves value realization ledger and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'FDA SaMD guidance', 'SOC 2 Type II', 'value realization ledger', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19980',
    name: 'Innovation Portfolio Triage Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for triage but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pilot success metric and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'NIST AI RMF', 'HITRUST roadmap', 'pilot success metric', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19981',
    name: 'Venture Partnership Drafting Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for drafting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves clinical governance checklist and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'ONC HTI-1', 'Series B burn rate', 'clinical governance checklist', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19982',
    name: 'AI Strategy Summarization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for summarization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves adoption plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'TEFCA participation', 'implementation partner capacity', 'adoption plan', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19983',
    name: 'Board Governance Risk Scoring Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for risk scoring but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves pre-mortem risk and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'FHIR R4 mapping', 'referenceable health-system customer', 'pre-mortem risk', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19984',
    name: 'Portfolio Value Worklist Prioritization Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for worklist prioritization but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves dependency map and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'HL7 v2 ADT reconciliation', 'clinical advisory board', 'dependency map', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19985',
    name: 'Innovation Portfolio Appeal Generation Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for appeal generation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is Epic change control: AbarVa should turn this into a Moves approval gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'Epic change control', 'FDA submission posture', 'approval gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19986',
    name: 'Venture Partnership Order Recommendation Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for order recommendation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is model registry: AbarVa should turn this into a Moves benefit validation plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'model registry', 'KLAS commentary', 'benefit validation plan', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19987',
    name: 'AI Strategy Benefit Verification Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for benefit verification but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'deployment-site validation', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19988',
    name: 'Board Governance Eligibility Prediction Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for eligibility prediction but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves value realization ledger and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'MLOps monitoring', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19989',
    name: 'Portfolio Value Care Gap Closure Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for care gap closure but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is clinical safety review: AbarVa should turn this into a Moves pilot success metric and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'clinical safety review', 'AWS HealthLake', 'pilot success metric', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19990',
    name: 'Innovation Portfolio Cohort Matching Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for cohort matching but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves clinical governance checklist and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'procurement RFP scoring', 'Azure Health Data Services', 'clinical governance checklist', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19991',
    name: 'Venture Partnership Contract Analysis Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for contract analysis but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves adoption plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'BAFO contract clause', 'Snowflake Healthcare', 'adoption plan', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19992',
    name: 'AI Strategy Agentic Orchestration Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for agentic orchestration but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves pre-mortem risk and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'HIPAA BAA', 'Databricks Lakehouse', 'pre-mortem risk', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19993',
    name: 'Board Governance Coding Suggestion Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for coding suggestion but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves dependency map and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'minimum necessary policy', 'ServiceNow workflow', 'dependency map', 'BAA clause'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19994',
    name: 'Portfolio Value Documentation Review Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for documentation review but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves approval gate and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'TJC survey evidence', 'Salesforce Health Cloud', 'approval gate', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19995',
    name: 'Innovation Portfolio Vendor Comparison Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when innovation portfolio is used for vendor comparison but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is CMS CoP: AbarVa should turn this into a Moves benefit validation plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when AI strategy is not proven in production.`,
    keywords: ['innovation portfolio', 'AI strategy', 'CMS CoP', 'startup maturity evidence', 'benefit validation plan', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19996',
    name: 'Venture Partnership Capacity Forecasting Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when venture partnership is used for capacity forecasting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when board governance is not proven in production.`,
    keywords: ['venture partnership', 'board governance', 'NCQA HEDIS audit', 'SOC 2 Type II', 'unsafe-to-fund gate', 'deployment-site validation SLA'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19997',
    name: 'AI Strategy Staffing Optimization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when AI strategy is used for staffing optimization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves value realization ledger and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when portfolio value is not proven in production.`,
    keywords: ['AI strategy', 'portfolio value', 'FDA SaMD guidance', 'HITRUST roadmap', 'value realization ledger', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19998',
    name: 'Board Governance Quality Abstraction Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when board governance is used for quality abstraction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves pilot success metric and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when innovation portfolio is not proven in production.`,
    keywords: ['board governance', 'innovation portfolio', 'NIST AI RMF', 'Series B burn rate', 'pilot success metric', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  },
  {
    code: 'H19999',
    name: 'Portfolio Value Patient Outreach Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Board Strategy, Innovation Portfolio & Venture Partnerships initiatives fail when portfolio value is used for patient outreach but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves clinical governance checklist and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when venture partnership is not proven in production.`,
    keywords: ['portfolio value', 'venture partnership', 'ONC HTI-1', 'implementation partner capacity', 'clinical governance checklist', 'BAFO counter'],
    demoRelevant: false,
    subTopic: 'Board Strategy, Innovation Portfolio & Venture Partnerships',
  }
];
