// seed-banking-dom10-kyc-onboarding-part2.ts
// Banking genome patterns — Customer Onboarding & KYC (Part 2)
// Code range: B2860–B2919  (60 patterns)
// Loaded by: scripts/corpus/load-authored-genome-seeds.ts

type OfficeCategory = 'front_office' | 'middle_office' | 'back_office';

interface PatternSeed {
  code: string;
  name: string;
  officeCategory: OfficeCategory;
  failureRatePct: number;
  description: string;
  keywords: string[];
  demoRelevant?: boolean;
  subTopic?: string;
}

export const KYC_ONBOARDING_PART2_PATTERNS: PatternSeed[] = [

  // ── Beneficial Ownership ───────────────────────────────────────────────────
  {
    code: 'B2860',
    name: 'CTA 2024 BOI Reporting Compliance Gap — Bank Customers Not Advised of Filing Obligations',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `First Capital's commercial onboarding process does not include a disclosure to legal entity customers of their obligations to file Beneficial Ownership Information reports with FinCEN under the Corporate Transparency Act 2024, even though FinCEN's BOI access rule and OCC supervisory expectations create a de facto expectation that financial institutions facilitate their commercial customers' awareness of the new BOI filing requirement. When OCC examiners review First Capital's commercial onboarding materials, they find no CTA disclosure, no FAQ for business customers, and no training for relationship managers on identifying customers likely to be reporting companies under the CTA — creating a BSA/AML program awareness gap at exactly the moment FinCEN is relying on bank touchpoints to drive BOI compliance across small-business customers. The gap also means the bank's CDD files do not capture whether the commercial customer is a CTA reporting company, an exempt entity, or a foreign entity not subject to BOI reporting, an omission that complicates the bank's ability to verify beneficial ownership certifications against FinCEN's BOI registry.`,
    keywords: ['CTA 2024', 'BOI reporting', 'FinCEN CDD Rule', 'BSA/AML', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2861',
    name: 'Multi-Tier Entity Beneficial Ownership Tracing Stops at Two Holding Layers',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `First Capital's beneficial ownership tracing tool is configured to trace ownership only through two layers of intermediate holding entities, stopping at the second-layer entity rather than continuing to the natural person beneficial owners when private equity–backed commercial borrowers use three-to-five-layer holding structures common in leveraged buyout portfolios. FinCEN's CDD Rule §1010.230 and OCC BSA examination guidance require identification of all natural persons owning 25% or more of the ultimate operating entity regardless of the number of holding layers; the two-layer cut-off means that beneficial owners insulated by deep holding structures — a documented structure in commercial real estate and PE-backed borrowers — are systematically excluded from the CDD file. When FinCEN issues a geographic targeting order covering three of First Capital's commercial real estate customers whose true UBOs were beyond the two-layer trace limit, the bank cannot produce complete beneficial ownership documentation for the GTOs within the 72-hour response window.`,
    keywords: ['beneficial ownership', 'FinCEN CDD Rule', 'multi-tier entity', 'BSA/AML', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2862',
    name: 'Trust Ownership Documentation Insufficient — Trustee Named but Grantor and Beneficiaries Absent',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `First Capital's beneficial ownership certification form for legal entity customers with trust ownership accepts the name of the trustee as the beneficial owner without requiring documentation of the grantor, settlor, or the trust beneficiaries who are the ultimate economic beneficiaries of the entity, creating a CDD file that identifies the legal controller but not the parties with the economic interest that FinCEN's beneficial ownership rule is designed to capture. FinCEN's CDD Rule FAQ guidance and the OCC's BSA/AML examination manual both clarify that for revocable trusts, the grantor retains beneficial ownership and should be identified alongside the trustee; for irrevocable trusts, beneficiaries with a present economic interest must be documented. First Capital's form has been flagged in two OCC examination cycles as insufficient for trust-owned entities, yet the bank has not updated the certification form or trained relationship managers on the additional trust documentation requirements, resulting in 14% of trust-owned commercial CDD files that remain deficient.`,
    keywords: ['beneficial ownership', 'trust ownership', 'FinCEN CDD Rule', 'BSA/AML', 'OCC BSA handbook'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2863',
    name: 'Foreign Entity BOI Exemption Misapplication — Large Foreign Pool Vehicles Incorrectly Exempt',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `First Capital's commercial onboarding team applies the CTA 2024 BOI reporting exemption for "large operating companies" to foreign-domiciled investment vehicles and special-purpose entities that do not meet the exemption criteria — specifically the requirements of having more than 20 full-time US employees, a physical US office, and more than $5M in US gross receipts. The misapplication of the large operating company exemption to foreign pool vehicles and SPEs means that commercial accounts for entities that should be filing BOI reports are opened without any BOI verification or FinCEN registry check, creating a systemic CDD Rule compliance gap for the bank's international commercial customer segment. FinCEN's BOI exemption guidance explicitly warns financial institutions that the large operating company exemption should not be extended to holding companies, investment vehicles, or entities that do not meet all three statutory criteria simultaneously; the bank's compliance training does not address this guidance.`,
    keywords: ['CTA 2024', 'BOI exemption', 'FinCEN CDD Rule', 'BSA/AML', 'commercial onboarding'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2864',
    name: 'FinCEN BOI Database Integration Not Implemented — Registry Access Not Used for Verification',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `First Capital has not integrated access to FinCEN's Beneficial Ownership Information database — available to financial institutions under the BOI access rule since early 2024 — into its commercial onboarding or periodic CDD review workflows, despite FinCEN's explicit guidance that financial institutions may use the registry to verify customer-provided beneficial ownership information and detect discrepancies. The absence of BOI registry integration means First Capital's CDD program forgoes the primary government verification resource for beneficial ownership accuracy, relying entirely on customer self-certification and manual cross-referencing of public sources. OCC BSA examiners reviewing the bank's CDD program note that peer institutions have implemented BOI registry access for high-risk commercial onboarding cases and that First Capital's failure to leverage the registry is inconsistent with a best-practice risk-based CDD program — particularly given the bank's ongoing MRM consent order and heightened scrutiny of its BSA/AML controls.`,
    keywords: ['FinCEN BOI database', 'beneficial ownership', 'FinCEN CDD Rule', 'BSA/AML', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2865',
    name: 'Nominee Shareholder Structures Not Flagged as High-Risk — CDD Treats Nominee as UBO',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `First Capital's beneficial ownership documentation process does not include a systematic check for nominee shareholder indicators — corporate service providers listed as shareholders, professional nominee directors with no operational connection to the business, or shareholder agreements with nominee provisions — that are red flags for concealed beneficial ownership under FinCEN typology guidance. When a commercial customer registers a nominee individual as the 51% shareholder on the beneficial ownership certification, First Capital's CDD process accepts the certification at face value without requiring the customer to affirm whether the listed owner is a nominee acting on behalf of an undisclosed third party. FinCEN's beneficial ownership FAQ and the FATF guidance on nominee structures both require banks to identify when named beneficial owners are nominees and to trace the actual economic beneficiary behind the nominee arrangement; the bank's failure to screen for nominee indicators means that complex ownership concealment structures can be successfully documented through the standard CDD process.`,
    keywords: ['beneficial ownership', 'nominee shareholder', 'FinCEN CDD Rule', 'BSA/AML', 'FATF'],
    demoRelevant: false,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2866',
    name: 'Beneficial Ownership Update Not Triggered by Corporate Event Filings — 30-Day Window Missed',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `First Capital's commercial CDD program requires customers to notify the bank within 30 days of any change in beneficial ownership, but the bank does not monitor secretary of state corporate event filings — ownership transfers, merger registrations, dissolution filings, or officer changes — that would indicate a beneficial ownership change has occurred, relying entirely on voluntary customer disclosure. FinCEN's CDD Rule ongoing monitoring requirement and OCC BSA examination guidance both anticipate that banks use publicly available data sources to corroborate customer-provided beneficial ownership information and detect undisclosed changes; a CDD program that relies solely on customer notification to detect ownership changes will systematically fail to capture changes where the new beneficial owner has an incentive not to disclose — precisely the scenario where beneficial ownership concealment is most likely. Over an 18-month review period, 8% of First Capital's commercial accounts show secretary of state filings indicating ownership changes that were not reflected in the bank's CDD records.`,
    keywords: ['beneficial ownership', 'FinCEN CDD Rule', 'BSA/AML', 'corporate events', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },
  {
    code: 'B2867',
    name: 'GenAI BOI Extraction From Complex Entity Documents Without Legal Review — Accuracy Unverified',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `First Capital's commercial onboarding team uses a GenAI tool to extract beneficial ownership percentages and controlling person identities from complex entity formation documents — limited partnership agreements, operating agreements with waterfall provisions, and shareholder agreements with class-specific voting rights — and populates the FinCEN CDD beneficial ownership certification without a legal review of whether the AI-extracted percentages correctly reflect the economic ownership under the applicable governing law. FinCEN's CDD Rule §1010.230 requires that beneficial ownership identification be based on a legally defensible analysis of ownership structure; GenAI-extracted beneficial ownership percentages that misinterpret waterfall economics, preferred return provisions, or class-specific voting rights will produce a CDD file that is inaccurate as a matter of law. SR 11-7 and OCC 2011-12 require that AI tools used in compliance decisions be validated for accuracy; the GenAI extraction tool has not been registered in the bank's model inventory or validated against a sample of complex entity documents reviewed by outside counsel, creating a compliance risk that compounds the bank's existing MRM consent order deficiencies.`,
    keywords: ['GenAI BOI extraction', 'FinCEN CDD Rule', 'SR 11-7', 'BSA/AML', 'legal validation'],
    demoRelevant: true,
    subTopic: 'beneficial-ownership',
  },

  // ── Digital Onboarding ─────────────────────────────────────────────────────
  {
    code: 'B2868',
    name: 'eKYC Document Verification Failure Rate Spikes on Non-US ID Documents — CIP Gap',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `First Capital's eKYC document verification vendor achieves a 97% automated acceptance rate for US driver's licenses and passports but has an acceptance rate of only 71% for foreign government-issued identification documents — including international passports with machine-readable zones in non-Roman script — causing a disproportionate rejection rate for immigrant and non-resident customer segments that triggers an in-person verification fallback the bank's digital channel has not fully operationalized. NIST SP 800-63A identity proofing guidance requires that automated identity verification systems perform equitably across the document types they claim to support; a 26-percentage-point accuracy gap between domestic and foreign ID documents means the digital onboarding channel effectively bars 29% of foreign ID holders from completing eKYC. OCC fair lending examination guidance treats digital channel access disparities that fall along demographic or national-origin lines as potential Reg B and ECOA concerns warranting remediation.`,
    keywords: ['eKYC', 'NIST 800-63', 'CIP', 'USA PATRIOT Act', 'ECOA'],
    demoRelevant: true,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2869',
    name: 'Video-Based Liveness Detection Bypass via Printed Mask — eKYC System Not Updated',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `First Capital's eKYC liveness detection system uses a passive liveness check that analyzes facial texture and movement to detect pre-recorded video replay but does not detect three-dimensional printed mask attacks, which can now be produced cost-effectively using consumer 3D printers and have been demonstrated to bypass the specific passive liveness algorithm used by the bank's vendor. NIST SP 800-63B identity assurance level guidance and the vendor's own security advisories — issued in Q3 2024 — describe 3D mask attacks as a known IAL2 vulnerability requiring active liveness countermeasures; First Capital has not deployed the vendor's updated active liveness module because the upgrade requires a new vendor contract amendment that legal has not finalized. The delay in patching a documented liveness bypass creates a CIP compliance gap and a potential OCC BSA examination finding that the bank knowingly operated an identity proofing system with a publicly disclosed vulnerability.`,
    keywords: ['eKYC', 'NIST 800-63', 'liveness detection', 'CIP', 'USA PATRIOT Act'],
    demoRelevant: false,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2870',
    name: 'Remote Notarization ESIGN Compliance Gap — Electronic Signature Not UETA-Compliant',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `First Capital's digital commercial account opening platform uses electronic signatures for beneficial ownership certifications and account agreements, but the bank's ESIGN and UETA compliance review was last completed in 2020 and does not address the bank's current mobile-native signature capture workflow, which does not provide the pre-signature consumer disclosure and consent record required by the Electronic Signatures in Global and National Commerce Act 15 U.S.C. §7001(c)(1). OCC guidance on digital banking and e-signature enforceability requires that the bank's electronic consent workflow satisfy ESIGN's affirmative consent requirements before the first electronic signature is obtained; the absence of a UETA-compliant consent record for mobile-captured beneficial ownership certifications means the certifications may not be legally enforceable in the event of a disputed CDD record, undermining the bank's ability to hold customers to the accuracy representations in their FinCEN CDD filings.`,
    keywords: ['ESIGN', 'UETA', 'eKYC', 'FinCEN CDD Rule', 'OCC guidance'],
    demoRelevant: false,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2871',
    name: 'Mobile Onboarding Accessibility Failure — ADA Title III Noncompliance in Digital KYC Flow',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `First Capital's mobile account opening application fails multiple WCAG 2.1 Level AA accessibility criteria in the eKYC identity proofing flow — including insufficient color contrast on document capture instructions, absent alt-text on liveness detection prompts, and a camera-orientation requirement with no assistive-technology alternative — creating an ADA Title III barrier for customers with visual impairments or motor disabilities seeking to open accounts through the digital channel. DOJ guidance on web accessibility for financial institutions and OCC consumer protection supervision guidance both expect that digital banking channels comply with WCAG 2.1 AA standards, particularly for functions as critical as account opening and identity verification; the accessibility failure generates a 34% abandonment rate for screen-reader users in usability testing that the bank's digital product team identified but has not remediated, creating both a CFPB unfair practices exposure and a litigation risk under ADA Title III.`,
    keywords: ['ADA Title III', 'WCAG 2.1', 'eKYC', 'OCC guidance', 'CFPB'],
    demoRelevant: false,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2872',
    name: 'Digital Identity Proofing Does Not Achieve NIST 800-63 IAL2 for High-Value Account Opening',
    officeCategory: 'front_office',
    failureRatePct: 63,
    description: `First Capital's digital onboarding process for commercial accounts with initial deposit thresholds above $100K applies the same eKYC identity proofing flow as standard retail accounts, which achieves NIST SP 800-63A Identity Assurance Level 1 (self-asserted identity with no proofing) rather than the IAL2 standard that OCC guidance and First Capital's own written CIP risk calibration require for high-value business accounts. NIST SP 800-63A IAL2 requires remote, supervised identity proofing with validated identity evidence — government-issued ID plus a live biometric comparison — performed by a trained operator; the bank's automated eKYC flow substitutes algorithmic processing for trained-operator supervision, producing an assurance level that does not satisfy the bank's own risk-based CIP calibration for the account type. OCC model risk examiners reviewing the digital onboarding channel find the IAL mismatch and require the bank to document its risk acceptance rationale or remediate to IAL2 for commercial accounts above the $100K threshold.`,
    keywords: ['NIST 800-63', 'IAL2', 'eKYC', 'CIP', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2873',
    name: 'eKYC Session Timeout Allows Document Image Re-Use — Same ID Submitted Across Multiple Applications',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `First Capital's digital onboarding platform caches uploaded identity document images in a browser session that persists for 24 hours without re-authentication, allowing a fraudster who gains access to the session to submit a previously captured ID image for a new account application without repeating the liveness check — a replay vulnerability that the bank's penetration test team identified in Q1 2025 but has not remediated pending a frontend architecture update. NIST SP 800-63B session management requirements and OCC cybersecurity examination guidance both require that identity proofing sessions be bound to a specific authentication event and expire upon session close; a 24-hour unconstrained session cache for identity documents is inconsistent with the session binding requirements for IAL2 identity proofing. The vulnerability was exploited in a documented synthetic identity fraud incident that used the same ID image to open three commercial accounts before the fraud was detected through transaction monitoring.`,
    keywords: ['eKYC', 'NIST 800-63', 'CIP', 'session security', 'USA PATRIOT Act'],
    demoRelevant: true,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2874',
    name: 'AI Deepfake Detection for Video eKYC Not Tested Against 2025 Generation Models',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `First Capital's video-based eKYC platform includes an AI deepfake detection component that the vendor last validated against synthetic media generation models available in 2023; the detection model has not been retested against the 2025 generation of real-time deepfake synthesis tools that can produce identity-consistent facial video with sub-100ms latency using commercially available APIs. NIST SP 800-63B technical guidance and FinCEN's advisories on synthetic identity fraud both require that liveness and presentation attack detection systems be evaluated against current-generation adversarial techniques; a deepfake detection model that is two generations behind the adversarial tools available to fraudsters does not provide the security assurance the bank relies on for CIP compliance. SR 11-7 model validation requirements apply to the deepfake detection AI as a model used in a compliance decision; the absence of adversarial testing documentation in the model file creates a gap in the bank's MRM consent order model validation evidence.`,
    keywords: ['AI deepfake detection', 'NIST 800-63', 'SR 11-7', 'eKYC', 'FinCEN'],
    demoRelevant: true,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2875',
    name: 'Digital Onboarding Abandonment Analytics Not Used to Identify CIP Friction Disparities',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `First Capital collects digital onboarding abandonment data at the step level but does not segment abandonment rates by customer demographic group, device type, or ID document category, making it impossible to determine whether the bank's eKYC friction produces disparate completion rates across protected class dimensions that would constitute a CFPB unfair, deceptive, or abusive practices finding or trigger OCC fair lending scrutiny. OCC supervisory guidance on digital product design and CFPB examination procedures for digital onboarding both indicate that lenders using digital identity verification should monitor abandonment rates for disparate impacts along demographic lines; the absence of segmented abandonment analytics means First Capital has no visibility into whether its eKYC step produces the demographic disparity that its usability research team has flagged as a risk. When CFPB examiners request segmented digital onboarding data during a fair lending examination, the bank cannot produce the analytics and must reconstruct the data from raw logs on a compressed timeline.`,
    keywords: ['eKYC', 'CFPB', 'ECOA', 'OCC guidance', 'NIST 800-63'],
    demoRelevant: false,
    subTopic: 'digital-onboarding',
  },

  // ── High-Risk Customers ────────────────────────────────────────────────────
  {
    code: 'B2876',
    name: 'VASP Correspondent Due Diligence Does Not Cover Exchange Regulatory Status in Jurisdiction of Incorporation',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `First Capital's EDD program for virtual asset service provider correspondents collects basic entity identification and ownership information but does not require documentation of the VASP's regulatory registration or licensing status in its jurisdiction of incorporation — an omission that FinCEN's guidance on VASPs and the FATF's Recommendation 16 travel rule framework both identify as a foundational element of VASP correspondent due diligence. VASPs operating in jurisdictions with no VASP registration requirement, or with lapsed or conditional licenses, present materially different ML risk profiles than regulated exchanges; failing to document regulatory status means First Capital may maintain correspondent relationships with unregulated VASPs that process transactions on behalf of sanctioned jurisdictions or high-risk customer segments without the enhanced oversight that FinCEN's VASP guidance requires. OCC BSA examiners reviewing First Capital's VASP correspondent files note that three of the bank's five VASP correspondents have no documentation of their regulatory licensing status, and one operates from a jurisdiction that FATF has identified as having deficient VASP supervision.`,
    keywords: ['VASP due diligence', 'FinCEN', 'FATF', 'BSA/AML', 'EDD'],
    demoRelevant: true,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2877',
    name: 'Foreign Correspondent Bank EDD Documentation Does Not Include CAML Certification',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `First Capital's EDD program for foreign correspondent banking relationships collects entity identification and ownership information for the correspondent bank's principal shareholders but does not obtain a Certified Anti-Money Laundering Specialist certification or equivalent anti-money laundering program attestation from the correspondent bank's compliance officer — a documentation element that FinCEN's Section 312 special due diligence guidance identifies as a best practice for US banks assessing the quality of a foreign correspondent's AML program. OCC BSA examination guidance on correspondent banking due diligence requires that US banks form a reasonable judgment about the adequacy of a foreign correspondent's AML program; the absence of a compliance officer attestation or equivalent AML program certification means that First Capital's EDD files do not document the basis for the bank's judgment that the foreign correspondent's AML program meets US standards, a defensibility gap OCC examiners identify when reviewing three of the bank's foreign correspondent relationships in higher-risk jurisdictions.`,
    keywords: ['EDD', 'foreign correspondent banking', 'FinCEN Section 312', 'BSA/AML', 'OCC BSA handbook'],
    demoRelevant: false,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2878',
    name: 'Cannabis-Adjacent Business CRB Onboarding Framework Absent — FinCEN 2014 Guidance Not Implemented',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `First Capital does not have a written cannabis-related business onboarding framework aligned to FinCEN's 2014 guidance on providing financial services to hemp-related and marijuana-related businesses, yet relationship managers have accepted a number of commercial accounts from businesses with supply chain relationships with licensed cannabis dispensaries — hemp seed suppliers, packaging vendors, landlords of dispensary properties — without the enhanced due diligence and SAR-filing obligations FinCEN's CRB guidance requires for marijuana-related businesses and their indirect-service providers. FinCEN's 2014 CRB guidance and its 2019 hemp clarification guidance both create a specific documentation and SAR-filing framework for financial institutions serving cannabis-adjacent businesses, including the requirement to file Marijuana Limited SARs for cannabis business customers even in states where marijuana is legal; the absence of a written CRB framework means First Capital is neither applying the enhanced diligence nor filing the required SAR type. OCC BSA examiners find four commercially onboarded accounts that meet FinCEN's definition of marijuana-affiliated businesses with no CRB designation, no enhanced diligence, and no Marijuana Limited SARs filed.`,
    keywords: ['cannabis CRB', 'FinCEN 2014 guidance', 'BSA/AML', 'EDD', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2879',
    name: 'Money Services Business MSB Program Oversight Relies on Customer Self-Identification Only',
    officeCategory: 'middle_office',
    failureRatePct: 73,
    description: `First Capital's BSA/AML program identifies money services businesses in its commercial customer portfolio based solely on the customer's self-identification on the account opening form, without independent verification through FinCEN's MSB registrant list, state money transmission license registries, or transaction activity pattern analysis to identify customers transacting as de facto MSBs without the required FinCEN registration. FinCEN's MSB registration requirements under 31 CFR 1022.380 and OCC BSA examination guidance require that banks identify all MSBs in their customer portfolio and apply the MSB-specific EDD, customer due diligence, and SAR-filing framework; a CDD program that relies on customer self-declaration without independent MSB registry verification misses unregistered MSBs and customers conducting unlicensed money transmission through their commercial accounts. A review of First Capital's high-volume wire origination customers finds six businesses with transaction profiles consistent with money transmission activity that are not designated as MSBs in the bank's CDD system and have not been registered with FinCEN.`,
    keywords: ['MSB due diligence', 'FinCEN', 'BSA/AML', 'EDD', 'OCC BSA handbook'],
    demoRelevant: true,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2880',
    name: 'High-Risk Customer Concentration in Specific Relationship Manager Portfolio Not Monitored',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `First Capital's BSA supervisory controls do not include portfolio-level concentration analysis that would identify when a single relationship manager is managing a disproportionate share of the bank's high-risk commercial accounts — a red flag pattern for internal facilitation of money laundering that FinCEN enforcement actions against financial institutions have documented. FinCEN guidance on insider threats and OCC BSA examination handbook guidance on BSA program governance both identify relationship manager–level concentration of high-risk accounts as a supervisory risk indicator requiring periodic assessment; the absence of portfolio concentration analytics means the BSA officer cannot detect whether a specific relationship manager's book has been targeted by money laundering networks seeking to establish multiple accounts through a single complicit or compromised employee. Internal audit's review of First Capital's EDD portfolio finds that 34% of all EDD-designated commercial accounts are managed by three of the bank's 140 commercial relationship managers.`,
    keywords: ['BSA/AML', 'EDD', 'FinCEN', 'OCC BSA handbook', 'insider threat'],
    demoRelevant: false,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2881',
    name: 'AI High-Risk Customer Identification Model Not Tested for Small Business Disparate Impact',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `First Capital uses an ML model to flag commercial customers as high-risk for EDD at onboarding, with features including industry SIC code, geographic market, transaction volume profile, and beneficial ownership structure; the model has not been tested for disparate impact on minority-owned small businesses, which share several features — cash-intensive industry codes, specific metropolitan markets, and informal governance structures — that the model uses as high-risk proxies. OCC fair lending supervisory guidance, CFPB examination procedures, and ECOA Reg B all apply to automated decision-making tools that determine access to banking services, including EDD-triggered additional burdens that may effectively exclude certain demographic groups from commercial banking; a disparate impact analysis of the high-risk EDD model is required as part of the bank's fair lending program. The bank's compliance team has not conducted a disparate impact analysis for the ML EDD flag model since its deployment 18 months ago, despite fair lending examination guidance that requires periodic review of automated credit and access models.`,
    keywords: ['AI high-risk classification', 'ECOA', 'FinCEN CDD Rule', 'BSA/AML', 'SR 11-7'],
    demoRelevant: true,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2882',
    name: 'Cryptocurrency Custodian Correspondent Relationship Lacks Blockchain Analytics Integration',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `First Capital maintains a correspondent banking relationship with a cryptocurrency custodian that settles fiat-to-crypto transactions through the bank's payment infrastructure; the bank does not require the custodian to provide blockchain transaction analytics data that would allow First Capital to assess the ultimate source and destination of funds underlying the fiat transactions, relying solely on the custodian's self-reported transaction summaries for ongoing monitoring. FinCEN's guidance on virtual currency businesses and OCC supervisory expectations for correspondent banking due diligence require that financial institutions obtain sufficient information to assess the AML risk of the correspondent's underlying customer transactions; a cryptocurrency correspondent relationship where the bank cannot see behind the custodian's omnibus accounts to assess blockchain-level fund flows is equivalent to a shell bank relationship that FinCEN's Section 312 guidance prohibits. The absence of blockchain analytics creates a transaction monitoring blind spot for a correspondent channel that has grown to $80M per month in fiat settlement volume.`,
    keywords: ['cryptocurrency correspondent', 'FinCEN Section 312', 'BSA/AML', 'blockchain analytics', 'OCC examination'],
    demoRelevant: false,
    subTopic: 'high-risk-customers',
  },
  {
    code: 'B2883',
    name: 'Fintech BaaS Partnership Customer KYC Delegated Without Bank Oversight of eKYC Quality',
    officeCategory: 'middle_office',
    failureRatePct: 76,
    description: `First Capital partners with a fintech banking-as-a-service provider that deploys the bank's charter to issue consumer and small business deposit accounts; the bank delegates CIP and KYC to the fintech partner under a program services agreement but does not conduct periodic sampling audits of the partner's eKYC completions to verify that the partner's automated CIP meets First Capital's written CIP program requirements and FinCEN's CDD Rule standards. OCC guidance on third-party fintech partnerships and FinCEN's CDD Rule both make clear that a bank cannot delegate its BSA/AML compliance obligations to a third party; the bank retains full regulatory responsibility for the quality of CIP performed on its behalf, and failing to audit the fintech partner's eKYC output means the bank has no basis for representing to OCC examiners that the 45,000 accounts opened through the BaaS channel comply with the bank's CIP program. A sampling review prompted by an OCC inquiry finds that 18% of BaaS-channel accounts have CIP deficiencies that would have failed First Capital's standard branch-based CIP quality controls.`,
    keywords: ['BaaS partnership', 'FinCEN CDD Rule', 'CIP', 'BSA/AML', 'OCC 2013-29'],
    demoRelevant: true,
    subTopic: 'high-risk-customers',
  },

  // ── Periodic Review ────────────────────────────────────────────────────────
  {
    code: 'B2884',
    name: 'CDD Periodic Review Cadence Not Aligned to Customer Risk Rating — All Tiers on Same Schedule',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `First Capital's CDD periodic review program schedules all commercial accounts for review on a fixed annual cycle regardless of their BSA risk rating, treating high-risk EDD customers with the same review frequency as low-risk Tier 1 accounts — in direct contradiction of FinCEN's risk-based CDD framework, which requires that review frequency be calibrated to risk tier. The flat review schedule means the bank is both over-investing in annual reviews for low-risk dormant accounts and under-serving the ongoing monitoring requirement for high-risk EDD customers who FinCEN guidance and OCC examination standards would expect to be re-reviewed semi-annually or quarterly based on their activity profile and risk factors. OCC examiners reviewing the bank's periodic review program find that 23 EDD customers with transaction volumes exceeding $5M per month are on annual review cycles that have not been accelerated despite activity-based escalation flags, a deficiency the OCC documents as inconsistent with a risk-calibrated CDD program.`,
    keywords: ['FinCEN CDD Rule', 'periodic KYC review', 'BSA/AML', 'OCC examination', 'EDD'],
    demoRelevant: true,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2885',
    name: 'Materially Changed Customer Event Triggers Absent — Ownership Change Undetected Until Annual Review',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `First Capital's CDD refresh program does not include automated triggers for event-driven re-review when a commercial customer experiences a material change in business structure, ownership, or activity profile — such as a new UBO crossing the 25% threshold, a change in the customer's primary business activity, or a 200% increase in monthly wire origination volume. FinCEN's CDD Rule ongoing monitoring requirement and OCC BSA examination guidance both contemplate that banks maintain current customer information not only through periodic reviews but through event-driven updates when materially changed circumstances indicate that the existing CDD record no longer accurately reflects the customer's risk profile. A commercial customer that enters a new line of business in a high-risk industry sector three months after onboarding should not wait 10 months for its annual review before the CDD program reassesses its risk rating; the absence of event-triggered re-review means high-risk changes are systematically detected on a 10-to-14-month lag.`,
    keywords: ['FinCEN CDD Rule', 'periodic KYC review', 'BSA/AML', 'event triggers', 'OCC BSA handbook'],
    demoRelevant: true,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2886',
    name: 'Watchlist Screening Refresh Frequency Below FinCEN Expectation — SDN Rescreening on 30-Day Cycle',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `First Capital rescreens its entire commercial and retail customer portfolio against OFAC's SDN list and FinCEN's 314(a) list on a monthly 30-day cycle, meaning customers added to the SDN list after the most recent screening can conduct transactions for up to 30 days before the bank detects the match. OFAC compliance guidance states that financial institutions should screen all customers whenever the SDN list is updated — which occurs on average weekly — and that a 30-day rescreening cycle is insufficient for the commercial customer population given the documented consequence of OFAC violations; OCC BSA examination guidance aligns with OFAC's expectation that transaction-blocking obligations apply to all transactions regardless of when the customer was last screened, not only to transactions processed after the 30-day batch screen is completed. The monthly cycle also misses intra-month FinCEN 314(a) list updates, which carry a 14-day mandatory response requirement that a 30-day screening cycle systematically violates.`,
    keywords: ['OFAC SDN screening', 'FinCEN 314(a)', 'BSA/AML', 'watchlist screening', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2887',
    name: 'PEP Status Change Detection Absent — Customers Who Become PEPs After Onboarding Not Identified',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `First Capital screens commercial and high-net-worth retail customers for PEP status at onboarding but does not have a continuous or periodic PEP status re-screening process to detect customers who became politically exposed persons after their account was opened — through appointment to a government position, election to public office, or appointment to the board of a state-owned enterprise. FinCEN's risk-based EDD framework and FATF Recommendation 12 both require that financial institutions apply enhanced due diligence to PEPs including existing customers who become PEPs after account opening; an onboarding-only PEP screen that is never repeated fails to detect the customer lifecycle event that creates the PEP risk. A sample of First Capital's commercial customer base cross-referenced against publicly available government appointment records identifies six customers who assumed senior government roles in the 24 months after account opening and who have not been reclassified as PEPs or subjected to EDD in the bank's CDD system.`,
    keywords: ['PEP screening', 'FinCEN CDD Rule', 'FATF', 'EDD', 'BSA/AML'],
    demoRelevant: true,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2888',
    name: 'Periodic Review Completion Rate Below 80% — Backlog Accepted Without Remediation Plan',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `First Capital's BSA compliance team completes approximately 72% of scheduled annual CDD reviews within the review window, with 28% of scheduled reviews — approximately 2,400 commercial accounts — rolling into the next calendar year due to analyst capacity constraints and a prioritization queue that deprioritizes lower-volume commercial accounts in favor of EDD-designated high-risk customers. FinCEN's CDD Rule requires that periodic review completion rates reflect a functioning program, not a program that systematically defers a quarter of its scheduled population; OCC examination guidance and the bank's prior consent order findings identify the periodic review backlog as a chronic BSA program deficiency that has persisted across three examination cycles without a funded remediation plan that addresses the underlying capacity gap. The BSA compliance officer has documented the backlog risk in annual BSA program assessments but has not obtained board approval for the additional headcount or technology investment needed to achieve a 95% completion rate.`,
    keywords: ['FinCEN CDD Rule', 'BSA/AML', 'periodic review backlog', 'OCC examination', 'consent order'],
    demoRelevant: true,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2889',
    name: 'Annual Certification Return Rate Not Tracked — Uncompleted Certifications Not Escalated',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `First Capital's commercial CDD annual certification process mails and emails certification forms to all commercial account holders but does not track the return rate by account type, relationship manager, or customer risk tier, making it impossible for the BSA officer to know what percentage of the certification program has been completed or to identify relationship managers whose portfolios have systemic non-response patterns. FinCEN's CDD Rule ongoing monitoring requirement and OCC BSA program governance guidance require that the bank be able to demonstrate that its CDD refresh program is functioning, which includes documenting completion rates and taking appropriate action for non-responsive customers; the absence of return rate tracking means the bank cannot represent to OCC examiners that its certification refresh program achieves meaningful coverage. A manual sampling of commercial accounts on the most recent certification cycle finds that 31% of sent certifications are unacknowledged more than 90 days after dispatch.`,
    keywords: ['FinCEN CDD Rule', 'BSA/AML', 'annual certification', 'OCC examination', 'EDD'],
    demoRelevant: false,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2890',
    name: 'AI-Assisted Periodic Review Prioritization Deprioritizes Dormant Accounts Before Reactivation',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `First Capital's AI periodic review prioritization tool assigns review urgency scores based on recent transaction activity, adverse media hits, and risk rating changes — a model that systematically deprioritizes dormant commercial accounts with no recent activity, pushing them to the lowest priority tier even though FinCEN money laundering typology guidance identifies dormant account reactivation as a common layering technique. When a dormant account deprioritized by the AI is reactivated and receives $2.4M in wire inflows over a 10-day period, the stale CDD file — last reviewed 26 months prior — provides no current expected activity baseline for transaction monitoring and no current beneficial ownership documentation, creating a monitoring gap at exactly the moment when the account's activity warrants the highest scrutiny. SR 11-7 model risk governance requires that models be validated against the specific risk scenarios they are designed to address; the AI prioritization model was not tested against dormant-account reactivation scenarios, a gap that the bank's model validator identifies in a retrospective model review.`,
    keywords: ['AI KYC prioritization', 'SR 11-7', 'FinCEN CDD Rule', 'BSA/AML', 'dormant account'],
    demoRelevant: true,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2891',
    name: 'Periodic Review Does Not Re-Evaluate Correspondent Banking Risk After FATF List Update',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `First Capital does not trigger accelerated periodic reviews for foreign correspondent banking relationships when FATF updates its grey or black lists to add the jurisdiction in which the correspondent operates, relying instead on the standard annual review cycle even when a correspondent's operating environment changes materially due to a new FATF designation. FinCEN guidance on FATF-designation risk and OCC BSA examination guidance on correspondent banking due diligence require that financial institutions reassess existing correspondent relationships when the risk context changes materially; a FATF grey list designation is precisely the kind of material risk change that should trigger an out-of-cycle EDD review rather than waiting for the next annual cycle. Three of First Capital's correspondent banking relationships are with institutions in jurisdictions added to the FATF grey list in the 18 months prior to the bank's most recent OCC BSA examination, none of which received accelerated re-review following the designations.`,
    keywords: ['correspondent banking EDD', 'FATF', 'FinCEN', 'BSA/AML', 'OCC BSA handbook'],
    demoRelevant: false,
    subTopic: 'periodic-review',
  },

  // ── AI / KYC AI Patterns (≥ 12 required) ─────────────────────────────────
  {
    code: 'B2892',
    name: 'LLM Adverse News Screening Generating False Positives That Exhaust Compliance Analyst Capacity',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `First Capital deploys an LLM-powered adverse news screening tool that generates natural-language summaries of web-sourced negative information for all commercial onboarding candidates; the LLM produces a false-positive rate of 58% — flagging legitimate news articles about customers' industry sectors, unrelated namesakes, and satirical media coverage as adverse news requiring analyst review — consuming the equivalent of 1.8 FTE BSA analyst hours daily on low-value alert dispositions. FinCEN's AML program effectiveness guidance and OCC BSA examination standards require that automated screening tools enhance rather than degrade analyst productivity; an LLM adverse news tool that generates more false-positive alerts than the team can review with adequate investigative depth creates the same systemic BSA program deficiency as no screening at all — high-risk adverse information is missed because it is buried in a queue of low-quality LLM-flagged content. The LLM tool is not in the bank's SR 11-7 model inventory and has not been validated for screening accuracy, a compound governance failure that OCC examiners flag during their review of the bank's BSA technology stack.`,
    keywords: ['LLM adverse news screening', 'SR 11-7', 'FinCEN CDD Rule', 'BSA/AML', 'false positive fatigue'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2893',
    name: 'AI Customer Risk Rating Model Not in SR 11-7 Model Inventory — Consent Order Milestone Breach',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `First Capital's BSA/AML program relies on a vendor-supplied ML customer risk rating model to assign low, medium, or high risk tiers to all new and existing commercial customers; the model is not registered in the bank's SR 11-7 model inventory on the grounds that it is a "vendor tool" and not a bank-developed model, despite OCC 2011-12 guidance that the SR 11-7 model governance framework applies to all models used in bank decision-making regardless of whether they are internally developed or vendor-sourced. The bank's MRM consent order specifically requires that all AI and ML models used in compliance decisions — including BSA/AML risk rating tools — be registered, validated, and subject to ongoing performance monitoring by the bank's independent validation unit within 18 months of the consent order effective date; the unregistered customer risk rating model is a direct consent order milestone breach that OCC examiners cite when assessing the bank's remediation progress, triggering a formal action to suspend the bank's consent order compliance clock pending remediation.`,
    keywords: ['AI customer risk rating', 'SR 11-7', 'OCC 2011-12', 'consent order', 'BSA/AML'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2894',
    name: 'GenAI BOI Extraction From Entity Documents Not Legally Validated — Ownership Percentage Errors',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `First Capital uses a GenAI document intelligence platform to extract beneficial ownership percentages from complex entity documents — limited partnership agreements with preferred return waterfalls, operating agreements with special allocation provisions, and shareholder agreements with anti-dilution ratchets — and populates the FinCEN CDD beneficial ownership certification without attorney review of whether the extracted percentages correctly represent the legal ownership under applicable corporate law. FinCEN's BOI reporting rule and CDD Rule §1010.230 require that beneficial ownership calculations be legally accurate; GenAI extraction from documents with complex economic provisions routinely misinterprets waterfall-adjusted ownership by treating nominal percentage interests as economic interests, producing UBO certifications that are factually incorrect as a matter of law. The GenAI tool is not registered as a SR 11-7 model despite producing quantitative outputs used in compliance decisions, and no attorney review step is documented in the onboarding workflow — a compound governance failure that the bank's internal audit identifies but has not yet remediated.`,
    keywords: ['GenAI BOI extraction', 'FinCEN CDD Rule', 'SR 11-7', 'BSA/AML', 'legal validation'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2895',
    name: 'AI Identity Verification Model Not Tested for Demographic Bias — ECOA Disparate Impact Risk',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `First Capital's AI-powered eKYC facial recognition model for selfie-to-ID matching was procured based on the vendor's aggregate accuracy benchmarks without requiring a demographic bias evaluation disaggregated by age, gender, and race — a gap that NIST's FRVT evaluations have documented as a systematic issue in commercial facial recognition systems, where error rates are substantially higher for darker-skinned faces and older individuals. ECOA Reg B and OCC fair lending supervisory guidance require that AI models used in banking access decisions be evaluated for disparate impact on protected classes; a facial recognition model with elevated false-rejection rates for minority demographic groups creates a discriminatory barrier to digital account opening that the bank's annual fair lending analysis would identify if the eKYC completion data were segmented by demographic group. First Capital's demographic performance evaluation for the eKYC model has never been conducted; the model has been in production for 22 months generating differential rejection rates that the bank cannot quantify.`,
    keywords: ['AI identity verification', 'ECOA', 'NIST 800-63', 'SR 11-7', 'fair lending'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2896',
    name: 'ML Customer Risk Tier Model Creates Disparate Impact on Minority-Owned Small Businesses',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `First Capital's ML-based BSA customer risk tier model uses SIC industry codes, geographic ZIP codes, cash deposit intensity, and business entity age as risk features; several of these features function as demographic proxies — specific industry codes and ZIP codes correlate strongly with minority business ownership — causing the model to generate disproportionately high risk ratings for minority-owned small businesses relative to similarly-situated white-owned businesses in the same industry. ECOA Reg B and OCC fair lending supervisory guidance apply to any automated model that influences a customer's access to banking services or subjects them to additional compliance burdens; an ML risk tier model that produces disparate EDD trigger rates for minority-owned businesses creates a CFPB fair banking enforcement risk. The bank's fair lending team has not reviewed the ML risk tier model for disparate impact despite the CFPB's 2024 supervisory guidance indicating that BSA/AML risk tiering models are within scope for fair lending review.`,
    keywords: ['ML risk tier model', 'ECOA', 'SR 11-7', 'FinCEN CDD Rule', 'fair lending'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2897',
    name: 'AI Onboarding Chatbot Providing Regulatory Guidance Without Compliance Officer Oversight',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `First Capital deploys an LLM-powered onboarding chatbot that answers commercial customer questions during the digital account opening flow; the chatbot has been prompted with general BSA and CDD compliance information and has been observed providing responses that characterize specific transaction structures as "not requiring SAR reporting" or "not triggering OFAC screening" based on the customer's description of their business activity — regulatory determinations that require human compliance officer judgment, not automated LLM responses. OCC guidance on AI use in customer-facing workflows and FinCEN's SAR guidance both make clear that filing determinations and compliance assessments require qualified human judgment and cannot be delegated to automated tools; an onboarding chatbot that makes SAR-filing and OFAC-compliance representations to customers during onboarding creates a regulatory guidance liability, and any customer who relies on the chatbot's guidance to structure around BSA reporting thresholds has been effectively coached by the bank's AI. The chatbot is not registered as a SR 11-7 model and has no compliance officer review process for its response templates.`,
    keywords: ['AI onboarding chatbot', 'FinCEN', 'BSA/AML', 'SR 11-7', 'OCC guidance'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2898',
    name: 'AI Transaction Monitoring Model Alert Suppression Rate Not Disclosed to BSA Officer',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `First Capital's AI-enhanced transaction monitoring system uses an ML pre-filter to suppress alerts before they reach BSA analyst queues; the vendor does not expose the suppression rate metric in the BSA officer's management dashboard, and the bank's technology team has not independently computed the suppression rate from raw alert generation logs. FinCEN's AML program effectiveness guidance and OCC BSA examination guidance both require that the BSA officer have visibility into the transaction monitoring system's alert generation and suppression behavior; a BSA officer who cannot quantify the percentage of AI-suppressed alerts cannot assess whether the suppression rate is within program tolerance or has drifted beyond the threshold established in the model's validation documentation. SR 11-7 model monitoring requirements mandate that model performance metrics — including pre-filter suppression rates — be tracked and reported to the BSA officer as part of the model's ongoing monitoring plan; the absence of suppression rate reporting creates a SR 11-7 monitoring deficiency documented in the bank's consent order remediation assessment.`,
    keywords: ['AI transaction monitoring', 'SR 11-7', 'FinCEN', 'BSA/AML', 'model monitoring'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2899',
    name: 'GenAI Adverse News Summarization Omitting Regulatory Enforcement Content — Coverage Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `First Capital's commercial onboarding adverse media process uses a GenAI summarization tool to condense search results into actionable alerts; the tool's summarization prompt weights recent and high-engagement content, causing it to systematically truncate or exclude FinCEN enforcement action summaries, OCC consent order documents, and SEC enforcement releases — which are authoritative, high-relevance adverse information sources but are expressed in dense regulatory prose that the GenAI model ranks as lower-engagement than narrative news articles. OCC BSA examination guidance and FinCEN's AML program effectiveness framework require that adverse media programs capture regulatory enforcement content as a priority source; a GenAI summarization layer that effectively hides enforcement actions from BSA analysts by truncating them from the summary output fails to meet the program quality standard. The summarization blind spot was identified when a commercial customer cleared through the GenAI adverse media process was subsequently found to be named in a 2023 FinCEN enforcement action that had appeared in search results but been truncated in the GenAI summary.`,
    keywords: ['GenAI adverse media', 'FinCEN CDD Rule', 'BSA/AML', 'SR 11-7', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2900',
    name: 'AI KYC Vendor Contract Lacks Model Drift Monitoring SLA — Performance Degradation Undetected',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `First Capital's contract with its AI KYC identity verification vendor does not include a model performance monitoring SLA — no requirement for the vendor to report monthly accuracy metrics, alert the bank if the model's false-accept or false-reject rate exceeds defined thresholds, or provide access to audit-grade model performance logs that the bank's independent validation unit would need to fulfill SR 11-7 ongoing monitoring requirements. OCC's third-party risk management guidance (OCC 2023-17) and SR 11-7 both require that financial institutions establish performance monitoring obligations in vendor contracts for AI models used in risk management decisions; a vendor contract that is silent on model drift monitoring means that performance degradation in the eKYC AI — driven by evolving fraud typologies, demographic distribution shifts, or training data staleness — will go undetected until a fraud event or OCC examination triggers a retrospective review. The bank's IVU cannot complete its SR 11-7 ongoing monitoring plan for the eKYC AI because the vendor contract provides no contractual access to the model performance data the plan requires.`,
    keywords: ['AI KYC vendor contract', 'SR 11-7', 'OCC 2023-17', 'model drift', 'eKYC'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2901',
    name: 'AI Beneficial Ownership Graph Tool Misclassifies Voting Trust Interests — UBO Count Error',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `First Capital's AI beneficial ownership mapping platform cannot correctly process voting trust agreements — a common governance structure in family-owned commercial businesses — treating the voting trustee as the beneficial owner based on the voting rights assignment rather than identifying the trust beneficiaries as the economic beneficial owners under FinCEN's CDD Rule definition. FinCEN's CDD Rule §1010.230 defines beneficial ownership by economic ownership percentage, not by voting rights; an AI that maps beneficial ownership based on voting control rather than economic ownership will systematically misidentify the beneficial owners of voting-trust-structured entities, producing a CDD file that lists the trustee rather than the economic beneficiaries. SR 11-7 model validation requirements demand that the AI ownership mapping tool be tested against the specific entity structure types in the bank's commercial customer population, including voting trusts; the validation documentation does not include voting trust test cases, a gap that the bank's IVU identifies in its retrospective model review.`,
    keywords: ['AI beneficial ownership', 'FinCEN CDD Rule', 'SR 11-7', 'BSA/AML', 'voting trust'],
    demoRelevant: false,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2902',
    name: 'ML Onboarding Risk Score Audit Trail Insufficient for Adverse Action Notice',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `First Capital uses an ML onboarding risk score to decline commercial account applications below a minimum risk threshold; the score is a composite of identity verification confidence, beneficial ownership completeness, adverse media flags, and behavioral risk indicators. When the bank declines an account application based on the ML score, the adverse action notice does not describe the specific factors driving the score — it cites only "risk scoring" as the basis for the decision — which CFPB examination guidance and OCC fair lending supervisory expectations indicate does not satisfy ECOA Reg B's adverse action notice requirements for decisions driven by algorithmic risk scoring. The adverse action notice deficiency is compounded by the bank's inability to produce factor-level score explanations from the ML model, which uses a gradient boosting architecture whose top-contributing features cannot be easily extracted for customer-facing disclosure without a SHAP value or LIME explanation layer that the vendor has not deployed.`,
    keywords: ['ML onboarding risk score', 'ECOA', 'SR 11-7', 'adverse action notice', 'Reg B'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2903',
    name: 'AI Name Screening Model Not Retrained After OFAC SDN List Format Change — Match Quality Declines',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `First Capital's AI name screening model for OFAC and FinCEN watchlist matching was trained on SDN list data formatted under OFAC's legacy XML schema; following OFAC's 2024 migration to its new structured data format with expanded alias coverage and entity relationship fields, the AI model's matching accuracy has degraded because its feature engineering pipeline was built for the legacy format and does not correctly parse the new alias structure. OFAC compliance guidance requires financial institutions to maintain blocking procedures that effectively detect SDN matches; an AI screening model whose accuracy degrades following a list format change creates a transaction-blocking gap that OCC and OFAC examiners would treat as a systemic OFAC compliance deficiency. The bank's technology team identified the format compatibility issue in Q2 2024 but vendor retraining has been deprioritized, leaving the degraded model in production with an estimated 12% reduction in alias match recall that the bank's compliance team has not quantified.`,
    keywords: ['AI name screening', 'OFAC', 'SR 11-7', 'BSA/AML', 'SDN matching'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },

  // ── Additional KYC / Onboarding Operational Patterns ─────────────────────
  {
    code: 'B2904',
    name: 'New Account Fraud Detection AI Not Integrated with CIP — Fraud and BSA Systems Siloed',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `First Capital operates a first-party fraud detection AI for new account applications in a separate technology stack from its BSA/AML CIP system, with no data-sharing integration between the two platforms — meaning that a fraud pattern detected by the fraud AI (such as device fingerprint re-use across multiple applications, velocity clustering, or email domain fraud scoring) is not surfaced to the BSA CIP team to inform the identity verification outcome. OCC guidance on fraud-BSA integration and FinCEN's 2022 joint advisory on Bank Secrecy Act and fraud alignment both recommend that financial institutions share data signals between fraud and BSA platforms to improve both identification and suspicious activity reporting; the siloed architecture means that the bank's most powerful identity fraud signal — the real-time fraud AI score — is invisible to the CIP process, allowing synthetic identity applicants who score poorly on the fraud model to complete automated CIP successfully because the fraud signal never reaches the CIP decision engine.`,
    keywords: ['fraud-BSA integration', 'FinCEN', 'CIP', 'BSA/AML', 'OCC guidance'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2905',
    name: 'KYC Refresh Automation Does Not Re-Verify Controlling Person Identity Documents',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `First Capital's automated CDD periodic review workflow refreshes transaction monitoring parameters and risk scores for existing commercial customers but does not re-verify the identity documents of the controlling person named in the original beneficial ownership certification — meaning that a beneficial owner who presents fraudulent identity documents at onboarding can maintain accounts indefinitely without the bank re-verifying the underlying identity claim. FinCEN's CDD Rule ongoing monitoring provisions and OCC BSA examination guidance both contemplate that periodic reviews provide the opportunity to refresh and corroborate the original identity verification; a periodic review workflow that updates risk parameters without re-verifying controlling person identity provides no backstop against original CIP fraud. The gap was identified when a beneficial owner whose fraudulent passport was accepted at onboarding in 2022 was not re-verified in two subsequent annual CDD reviews, despite the bank's written CDD program stating that periodic reviews should include refreshed identity verification for high-risk accounts.`,
    keywords: ['FinCEN CDD Rule', 'CIP', 'BSA/AML', 'periodic review', 'OCC BSA handbook'],
    demoRelevant: false,
    subTopic: 'periodic-review',
  },
  {
    code: 'B2906',
    name: 'Customer Risk Profile Not Updated After Negative SAR Outcome — Risk Rating Remains Low',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `First Capital files a suspicious activity report on a commercial customer following a transaction monitoring alert but does not automatically escalate the customer's BSA risk rating in response to the SAR filing event, leaving the customer classified as low-risk in the CDD system despite the documented suspicious activity finding. FinCEN's CDD Rule ongoing monitoring guidance and OCC BSA examination expectations both anticipate that SAR filings trigger a review of the customer's CDD risk rating; a customer for whom the bank has already identified suspicious activity sufficient to file a SAR should be reclassified as high-risk and subjected to enhanced monitoring and the EDD cadence, not left on a low-risk annual review cycle. The absence of a SAR-to-risk-rating feedback loop means that First Capital maintains 34 customers in its commercial portfolio who have been the subject of SAR filings within the past 24 months but are rated low-risk, receiving less monitoring attention than their documented suspicious activity history warrants.`,
    keywords: ['FinCEN CDD Rule', 'SAR filing', 'BSA/AML', 'customer risk rating', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'ongoing-monitoring',
  },
  {
    code: 'B2907',
    name: 'Digital Onboarding Channel Lacks Re-Authentication Before Beneficial Ownership Certification',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `First Capital's digital commercial account opening flow completes the eKYC identity verification step and then allows the customer to proceed through the beneficial ownership certification and account agreement signing without a re-authentication checkpoint, meaning that if a session is hijacked between the eKYC step and the certification signing, a third party can complete the beneficial ownership certification with false information using the authenticated session. NIST SP 800-63B session assurance level requirements and OCC cybersecurity guidance recommend step-up authentication before high-risk transaction steps — including digital execution of regulatory compliance documents such as beneficial ownership certifications; the absence of re-authentication before the certification step means the identity proofing event and the regulatory document signing are not cryptographically bound to the same authentication session. The architecture gap was identified in a penetration test but deprioritized in the remediation roadmap as a "medium" finding, despite the regulatory consequence of a beneficial ownership certification executed by an unauthorized party.`,
    keywords: ['eKYC', 'NIST 800-63', 'FinCEN CDD Rule', 'session security', 'OCC guidance'],
    demoRelevant: false,
    subTopic: 'digital-onboarding',
  },
  {
    code: 'B2908',
    name: 'Commercial KYC Data Not Centralized — Siloed Across Four Business Lines With No Golden Record',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `First Capital maintains separate commercial customer KYC records in four distinct systems — the commercial deposit platform, the commercial lending origination system, the treasury management platform, and the international wire system — with no entity resolution layer to create a unified golden CDD record that the BSA officer can query across all commercial relationships for a single legal entity. FinCEN's CDD Rule and BCBS 239 data quality principles both require that financial institutions be able to aggregate customer-level risk information across all business lines; siloed KYC records mean the BSA officer cannot determine the aggregate transaction volume, product mix, and risk profile for a commercial customer that maintains relationships across all four systems, creating a fundamental ongoing monitoring gap. When OCC examiners ask for a complete transaction history and CDD record for three commercial customers designated as high-risk, the bank requires a five-day manual data compilation process across four systems — evidence of the data aggregation failure that BCBS 239 Principle 6 specifically addresses.`,
    keywords: ['FinCEN CDD Rule', 'BCBS 239', 'BSA/AML', 'KYC data quality', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'commercial-onboarding',
  },
  {
    code: 'B2909',
    name: 'High-Risk Jurisdiction Onboarding Approval Not Documented at Senior Management Level',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `First Capital's written EDD program requires senior management approval before onboarding commercial customers from FATF grey-list or OFAC-monitored jurisdictions, but the approval process is documented only through email chains retained in relationship managers' personal email folders — not in the centralized CDD system — making it impossible for OCC examiners to verify that the required approvals were obtained for specific customers or to audit the quality of the approval rationale. FinCEN's correspondent banking guidance and OCC BSA examination standards both require that senior management approvals for high-risk relationship decisions be formally documented, dated, and retained in the customer's CDD file; approval documentation retained in personal email chains rather than the CDD system fails the documentation standard and cannot be produced under the OCC's examination record request timelines. When the BSA officer departs the bank, three years of high-risk jurisdiction approval history becomes inaccessible because it existed only in personal email.`,
    keywords: ['EDD', 'FinCEN CDD Rule', 'FATF', 'BSA/AML', 'OCC BSA handbook'],
    demoRelevant: false,
    subTopic: 'enhanced-due-diligence',
  },
  {
    code: 'B2910',
    name: 'Account Opening Queue Back-Pressure Drives Relationship Managers to Bypass CDD Completeness Check',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `First Capital's commercial account opening workflow includes an automated CDD completeness gate that prevents account funding until all required documentation is in the CDD file; during peak onboarding periods, relationship managers have learned to use an internal override code — originally intended for time-sensitive treasury management clients — to bypass the completeness gate and open accounts with incomplete CDD, with the expectation of completing the documentation within 30 days. FinCEN's CDD Rule requires that the bank collect and verify customer information before account opening; using an emergency override code as a routine workaround to bypass the completeness gate has converted a process control into dead letter, with the bank's compliance team finding that 41% of commercially onboarded accounts in the prior quarter used the override code, the majority of which were for standard commercial deposit accounts with no documented emergency justification.`,
    keywords: ['FinCEN CDD Rule', 'CIP', 'BSA/AML', 'commercial onboarding', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'commercial-onboarding',
  },
  {
    code: 'B2911',
    name: 'Third-Party KYC Utility Data Freshness Not Contractually Guaranteed — Stale Identity Data Used',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `First Capital subscribes to a third-party KYC utility that aggregates identity verification data from credit bureaus, public records, and government databases; the utility's contract does not guarantee minimum data freshness standards — the bank cannot determine from the contract whether the identity data used to verify a customer was current at the time of query or could have been cached from a prior retrieval as many as 90 days earlier. FinCEN's CDD Rule and OCC BSA program quality expectations both require that identity verification data be current and accurate; a KYC utility that does not contractually warrant data freshness does not provide the accuracy guarantee that the bank's written CIP program relies on when accepting the utility's output as non-documentary identity verification. OCC third-party risk management guidance (OCC 2023-17) requires that financial institutions include data quality and freshness standards in vendor contracts for tools used in compliance decisions; the KYC utility contract's absence of data freshness terms is a TPRM gap identified in the bank's annual vendor risk assessment.`,
    keywords: ['KYC utility data', 'FinCEN CDD Rule', 'OCC 2023-17', 'CIP', 'BSA/AML'],
    demoRelevant: true,
    subTopic: 'cip-kyc',
  },
  {
    code: 'B2912',
    name: 'CDD Training Program Not Updated for CTA 2024 BOI Requirements — Analyst Knowledge Gap',
    officeCategory: 'back_office',
    failureRatePct: 68,
    description: `First Capital's BSA compliance training curriculum for commercial account officers and CDD analysts was last updated in 2022 and does not include instruction on the Corporate Transparency Act 2024 BOI reporting requirements, the FinCEN BOI access rule for financial institutions, or the updated beneficial ownership documentation standards that the CTA introduces for reporting companies versus exempt entities. FinCEN's CDD Rule and OCC BSA program quality requirements both expect that BSA training reflect current regulatory requirements; analysts trained on the 2022 curriculum are not equipped to identify CTA reporting company indicators, apply BOI exemption criteria correctly, or use the FinCEN BOI registry as a verification source for commercial onboarding. A quiz administered during the bank's annual BSA training assessment finds that only 38% of commercial account officers can correctly identify whether a specific entity type is a CTA reporting company or qualifies for one of the enumerated exemptions.`,
    keywords: ['CTA 2024', 'FinCEN CDD Rule', 'BSA/AML', 'compliance training', 'OCC examination'],
    demoRelevant: true,
    subTopic: 'cip-kyc',
  },
  {
    code: 'B2913',
    name: 'AI Sanctions Screening Bypass During System Failover — Transactions Processed Unscreened',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `First Capital's AI-powered real-time sanctions screening system for wire and ACH transactions has a failover mode that bypasses screening and processes transactions when the AI screening platform is unavailable, with the intent of preventing transaction processing outages — but the bank has no automated compensating control to retrospectively screen all transactions processed during failover periods once the system recovers. OFAC compliance guidance requires that financial institutions block or reject transactions with SDN-listed parties in real time; a failover mode that bypasses sanctions screening without a retrospective remediation process means that SDN-listed transactions processed during system downtime — which has occurred four times in the prior 12 months for periods ranging from 12 to 90 minutes — are never screened or reported to OFAC as potential blocking events. OCC operational resilience guidance and OFAC compliance program expectations both require that institutions have documented procedures for handling unscreened transactions during system outages, including retrospective review — procedures First Capital has not implemented.`,
    keywords: ['AI sanctions screening', 'OFAC', 'BSA/AML', 'system failover', 'OCC guidance'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2914',
    name: 'AI-Generated CDD Risk Narratives Accepted Without Analyst Attestation — Documentation Integrity Risk',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `First Capital's EDD workflow uses an AI tool to draft the risk narrative summary for the customer's CDD file — synthesizing adverse media findings, beneficial ownership complexity, and transaction profile characteristics into a one-page compliance summary that the BSA analyst reviews at the end of the EDD process. The AI-drafted risk narrative is saved to the CDD file with the analyst's digital signature upon review completion, but the workflow does not require the analyst to explicitly attest that they have reviewed the AI-drafted content for accuracy and completeness before signing, meaning the analyst's signature does not distinguish between a carefully reviewed narrative and a clicked-through auto-approval. FinCEN's CDD Rule and OCC BSA documentation standards require that CDD files reflect genuine analyst judgment; an AI-drafted risk narrative that is accepted without a documented attestation step does not establish that the analyst — rather than the AI — made the risk assessment that the signature represents, creating a documentation integrity and BSA program quality deficiency.`,
    keywords: ['AI CDD risk narrative', 'FinCEN CDD Rule', 'SR 11-7', 'BSA/AML', 'OCC BSA handbook'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2915',
    name: 'Generative AI KYC Platform Hallucinating Adverse News That Does Not Exist — False EDD Triggers',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `First Capital deploys a GenAI tool to surface adverse news summaries for commercial onboarding candidates; the tool has been found to occasionally generate plausible-sounding adverse news summaries — including fabricated enforcement action references and fictitious litigation claims — for customers against whom no actual adverse news exists, triggering unnecessary EDD workflows that consume BSA analyst time and delay account opening for customers with legitimate business profiles. FinCEN's BSA program quality standards and OCC BSA examination guidance require that EDD triggers be based on credible, verifiable adverse information; AI-hallucinated adverse news that cannot be verified against any actual source does not satisfy this standard and creates a potential UDAAP concern if the fabricated adverse information delays or prevents a legitimate customer from opening an account. The hallucination rate has been estimated at 3–4% of adverse news summaries generated by the tool, but the bank has no quality control process to verify GenAI adverse news outputs against underlying source documents before triggering EDD.`,
    keywords: ['GenAI adverse news', 'SR 11-7', 'FinCEN CDD Rule', 'BSA/AML', 'hallucination risk'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2916',
    name: 'AI Onboarding Risk Engine Output Not Auditable by OCC — Inference Log Not Retained',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `First Capital's AI onboarding risk engine generates a composite risk score at account opening that determines CDD tier and EDD eligibility; the bank does not retain inference-time logs showing the input feature values and intermediate score components that produced each risk score, making it impossible for the bank's IVU or OCC examiners to reconstruct the model's reasoning for a specific onboarding decision. SR 11-7 model risk governance requires that model outputs be traceable through a documented inference process including input data, feature derivation, and output generation; the absence of inference log retention means the AI risk engine operates as a production black box whose past decisions cannot be audited for accuracy, fairness, or consistency with the bank's BSA risk appetite. When OCC examiners request the risk score rationale for 20 specific commercial onboarding decisions as part of the bank's consent order examination, the bank cannot provide the inference-time documentation, triggering a new Matters Requiring Immediate Attention for model governance record-keeping.`,
    keywords: ['AI onboarding risk engine', 'SR 11-7', 'OCC examination', 'BSA/AML', 'model audit trail'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2917',
    name: 'AI Entity Screening Underperforms on Transliterated Name Variants — Matching Coverage Gap',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `First Capital's AI name matching model for OFAC SDN and FinCEN watchlist screening was trained predominantly on English-language name variants and has documented accuracy limitations for transliterated Arabic, Cyrillic, and Chinese names — precisely the name formats most common for entities associated with OFAC designated programs targeting Iran, Russia, and North Korea. OFAC compliance guidance specifically addresses the need for phonetic and transliteration-aware matching for screening against SDN entries with non-Roman script aliases; an AI screening model that underperforms on transliterated name variants creates a systematic match-recall gap for exactly the SDN population that OFAC's highest-priority sanction programs target. The bank's annual OFAC compliance program review, conducted by outside counsel, identifies the transliteration accuracy gap and rates it as a medium-high risk finding; remediation has been deferred pending a vendor contract renewal that has been in negotiation for nine months.`,
    keywords: ['AI name screening', 'OFAC', 'SR 11-7', 'BSA/AML', 'transliteration matching'],
    demoRelevant: false,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2918',
    name: 'AI-Powered KYC Document Authenticity Check Has No Version Control — Prior Fraud Patterns Not Retained',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `First Capital's AI document authenticity verification tool is updated by the vendor in rolling releases that overwrite prior model versions without archiving previous model states; when the bank needs to investigate a retrospective CIP failure — where a fraudulent document was accepted by the AI during onboarding — it cannot determine which model version performed the verification at the time of the acceptance decision and therefore cannot determine whether the error was within the model's documented tolerance at the time or represents a model failure. OCC BSA examination guidance and SR 11-7 model record-keeping requirements both expect that model outputs at the time of a compliance decision be reconstructible from documented model versions; a vendor deployment practice that overwrites prior model versions without retention makes the bank's eKYC AI decisions permanently irrecoverable, preventing post-hoc accuracy assessment and undermining the bank's ability to respond to OCC inquiries about specific CIP decisions.`,
    keywords: ['AI document authenticity', 'SR 11-7', 'eKYC', 'CIP', 'OCC 2023-17'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
  {
    code: 'B2919',
    name: 'AI KYC Platform Vendor Exit Rights Not Established — Model and Data Locked at Vendor',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `First Capital's contract with its AI KYC platform vendor does not include exit rights for the bank's model validation documentation, training data contributions, inference log exports, or transition assistance — meaning that if the vendor relationship terminates, the bank loses access to the CIP decision history stored in the vendor's cloud environment along with the model performance data required for SR 11-7 ongoing monitoring and OCC consent order evidence. OCC 2023-17 third-party risk management guidance and SR 11-7 model governance both require that financial institutions establish contractual rights to model documentation, performance data, and customer record portability before deploying vendor AI in compliance decisions; a contract silent on exit rights creates a third-party concentration risk for a compliance-critical AI system. When the vendor announces a pricing restructuring that First Capital determines is unacceptable, the absence of exit rights forces the bank to accept the new pricing rather than migrate — a vendor lock-in that OCC examiners flag as inconsistent with the bank's TPRM consent order milestone requiring exit plan documentation for all critical compliance technology vendors.`,
    keywords: ['AI KYC vendor lock-in', 'OCC 2023-17', 'SR 11-7', 'TPRM', 'BSA/AML'],
    demoRelevant: true,
    subTopic: 'ai-kyc',
  },
];
