/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 45: Perioperative, OR Robotics & Surgical AI
// Part 1: H12800-H12849
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM45_PART1_PATTERNS = [
  {
    code: 'H12800',
    name: 'OR Scheduling AI Cohort Matching Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 81,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for cohort matching but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'FHIR R4 mapping', 'implementation partner capacity', 'unsafe-to-fund gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12801',
    name: 'Robotics Contract Analysis Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for contract analysis but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves value realization ledger and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'HL7 v2 ADT reconciliation', 'referenceable health-system customer', 'value realization ledger', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12802',
    name: 'Preference Cards Agentic Orchestration Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for agentic orchestration but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is Epic change control: AbarVa should turn this into a Moves pilot success metric and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'Epic change control', 'clinical advisory board', 'pilot success metric', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12803',
    name: 'Block Utilization Coding Suggestion Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for coding suggestion but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is model registry: AbarVa should turn this into a Moves clinical governance checklist and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'model registry', 'FDA submission posture', 'clinical governance checklist', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12804',
    name: 'TJC Documentation Review Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for documentation review but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves adoption plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'deployment-site validation', 'KLAS commentary', 'adoption plan', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12805',
    name: 'OR Scheduling AI Vendor Comparison Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for vendor comparison but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pre-mortem risk and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'MLOps monitoring', 'Epic App Orchard integration', 'pre-mortem risk', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12806',
    name: 'Robotics Capacity Forecasting Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for capacity forecasting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is clinical safety review: AbarVa should turn this into a Moves dependency map and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'clinical safety review', 'Microsoft Cloud for Healthcare', 'dependency map', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12807',
    name: 'Preference Cards Staffing Optimization Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for staffing optimization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves approval gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'procurement RFP scoring', 'AWS HealthLake', 'approval gate', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12808',
    name: 'Block Utilization Quality Abstraction Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for quality abstraction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves benefit validation plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'BAFO contract clause', 'Azure Health Data Services', 'benefit validation plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12809',
    name: 'TJC Patient Outreach Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for patient outreach but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'HIPAA BAA', 'Snowflake Healthcare', 'unsafe-to-fund gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12810',
    name: 'OR Scheduling AI Triage Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for triage but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves value realization ledger and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'minimum necessary policy', 'Databricks Lakehouse', 'value realization ledger', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12811',
    name: 'Robotics Drafting Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for drafting but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves pilot success metric and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'TJC survey evidence', 'ServiceNow workflow', 'pilot success metric', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12812',
    name: 'Preference Cards Summarization Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for summarization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is CMS CoP: AbarVa should turn this into a Moves clinical governance checklist and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'CMS CoP', 'Salesforce Health Cloud', 'clinical governance checklist', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12813',
    name: 'Block Utilization Risk Scoring Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for risk scoring but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves adoption plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'NCQA HEDIS audit', 'startup maturity evidence', 'adoption plan', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12814',
    name: 'TJC Worklist Prioritization Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for worklist prioritization but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pre-mortem risk and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'FDA SaMD guidance', 'SOC 2 Type II', 'pre-mortem risk', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12815',
    name: 'OR Scheduling AI Appeal Generation Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 55,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for appeal generation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves dependency map and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'NIST AI RMF', 'HITRUST roadmap', 'dependency map', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12816',
    name: 'Robotics Order Recommendation Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for order recommendation but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves approval gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'ONC HTI-1', 'Series B burn rate', 'approval gate', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12817',
    name: 'Preference Cards Benefit Verification Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for benefit verification but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves benefit validation plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'TEFCA participation', 'implementation partner capacity', 'benefit validation plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12818',
    name: 'Block Utilization Eligibility Prediction Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for eligibility prediction but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'FHIR R4 mapping', 'referenceable health-system customer', 'unsafe-to-fund gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12819',
    name: 'TJC Care Gap Closure Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for care gap closure but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves value realization ledger and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'HL7 v2 ADT reconciliation', 'clinical advisory board', 'value realization ledger', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12820',
    name: 'OR Scheduling AI Cohort Matching Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for cohort matching but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is Epic change control: AbarVa should turn this into a Moves pilot success metric and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'Epic change control', 'FDA submission posture', 'pilot success metric', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12821',
    name: 'Robotics Contract Analysis Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 75,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for contract analysis but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is model registry: AbarVa should turn this into a Moves clinical governance checklist and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'model registry', 'KLAS commentary', 'clinical governance checklist', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12822',
    name: 'Preference Cards Agentic Orchestration Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for agentic orchestration but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves adoption plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'deployment-site validation', 'Epic App Orchard integration', 'adoption plan', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12823',
    name: 'Block Utilization Coding Suggestion Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for coding suggestion but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pre-mortem risk and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'MLOps monitoring', 'Microsoft Cloud for Healthcare', 'pre-mortem risk', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12824',
    name: 'TJC Documentation Review Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 74,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for documentation review but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is clinical safety review: AbarVa should turn this into a Moves dependency map and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'clinical safety review', 'AWS HealthLake', 'dependency map', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12825',
    name: 'OR Scheduling AI Vendor Comparison Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for vendor comparison but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves approval gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'procurement RFP scoring', 'Azure Health Data Services', 'approval gate', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12826',
    name: 'Robotics Capacity Forecasting Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for capacity forecasting but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves benefit validation plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'BAFO contract clause', 'Snowflake Healthcare', 'benefit validation plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12827',
    name: 'Preference Cards Staffing Optimization Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 72,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for staffing optimization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'HIPAA BAA', 'Databricks Lakehouse', 'unsafe-to-fund gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12828',
    name: 'Block Utilization Quality Abstraction Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for quality abstraction but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves value realization ledger and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'minimum necessary policy', 'ServiceNow workflow', 'value realization ledger', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12829',
    name: 'TJC Patient Outreach Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for patient outreach but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves pilot success metric and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'TJC survey evidence', 'Salesforce Health Cloud', 'pilot success metric', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12830',
    name: 'OR Scheduling AI Triage Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for triage but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is CMS CoP: AbarVa should turn this into a Moves clinical governance checklist and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'CMS CoP', 'startup maturity evidence', 'clinical governance checklist', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12831',
    name: 'Robotics Drafting Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for drafting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves adoption plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'NCQA HEDIS audit', 'SOC 2 Type II', 'adoption plan', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12832',
    name: 'Preference Cards Summarization Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for summarization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pre-mortem risk and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'FDA SaMD guidance', 'HITRUST roadmap', 'pre-mortem risk', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12833',
    name: 'Block Utilization Risk Scoring Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 83,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for risk scoring but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves dependency map and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'NIST AI RMF', 'Series B burn rate', 'dependency map', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12834',
    name: 'TJC Worklist Prioritization Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 82,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for worklist prioritization but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves approval gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'ONC HTI-1', 'implementation partner capacity', 'approval gate', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12835',
    name: 'OR Scheduling AI Appeal Generation Human Override Ambiguity',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for appeal generation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves benefit validation plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'TEFCA participation', 'referenceable health-system customer', 'benefit validation plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12836',
    name: 'Robotics Order Recommendation Integration Surface Fragmentation',
    officeCategory: 'middle_office',
    failureRatePct: 78,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for order recommendation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'FHIR R4 mapping', 'clinical advisory board', 'unsafe-to-fund gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12837',
    name: 'Preference Cards Benefit Verification Liability Handoff Gap',
    officeCategory: 'middle_office',
    failureRatePct: 53,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for benefit verification but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves value realization ledger and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'HL7 v2 ADT reconciliation', 'FDA submission posture', 'value realization ledger', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12838',
    name: 'Block Utilization Eligibility Prediction Equity Guardrail Drift',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for eligibility prediction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is Epic change control: AbarVa should turn this into a Moves pilot success metric and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'Epic change control', 'KLAS commentary', 'pilot success metric', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12839',
    name: 'TJC Care Gap Closure Value Ledger Overstatement',
    officeCategory: 'middle_office',
    failureRatePct: 71,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for care gap closure but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is model registry: AbarVa should turn this into a Moves clinical governance checklist and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'model registry', 'Epic App Orchard integration', 'clinical governance checklist', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12840',
    name: 'OR Scheduling AI Cohort Matching Agent Tool Boundary Failure',
    officeCategory: 'middle_office',
    failureRatePct: 79,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for cohort matching but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves adoption plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'deployment-site validation', 'Microsoft Cloud for Healthcare', 'adoption plan', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12841',
    name: 'Robotics Contract Analysis Startup Roadmap Dependency',
    officeCategory: 'middle_office',
    failureRatePct: 60,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for contract analysis but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pre-mortem risk and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'MLOps monitoring', 'AWS HealthLake', 'pre-mortem risk', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12842',
    name: 'Preference Cards Agentic Orchestration Alert Fatigue Inflection',
    officeCategory: 'middle_office',
    failureRatePct: 77,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for agentic orchestration but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is clinical safety review: AbarVa should turn this into a Moves dependency map and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'clinical safety review', 'Azure Health Data Services', 'dependency map', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12843',
    name: 'Block Utilization Coding Suggestion Revenue Integrity Leakage',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for coding suggestion but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves approval gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'procurement RFP scoring', 'Snowflake Healthcare', 'approval gate', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12844',
    name: 'TJC Documentation Review Audit Evidence Thinness',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for documentation review but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves benefit validation plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'BAFO contract clause', 'Databricks Lakehouse', 'benefit validation plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12845',
    name: 'OR Scheduling AI Vendor Comparison Criteria Drift',
    officeCategory: 'middle_office',
    failureRatePct: 80,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when OR scheduling AI is used for vendor comparison but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when preference cards is not proven in production.`,
    keywords: ['OR scheduling AI', 'preference cards', 'HIPAA BAA', 'ServiceNow workflow', 'unsafe-to-fund gate', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12846',
    name: 'Robotics Capacity Forecasting Workflow Authority Gap',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when robotics is used for capacity forecasting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves value realization ledger and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when block utilization is not proven in production.`,
    keywords: ['robotics', 'block utilization', 'minimum necessary policy', 'Salesforce Health Cloud', 'value realization ledger', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12847',
    name: 'Preference Cards Staffing Optimization Subprocessor Blind Spot',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when preference cards is used for staffing optimization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves pilot success metric and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when TJC is not proven in production.`,
    keywords: ['preference cards', 'TJC', 'TJC survey evidence', 'startup maturity evidence', 'pilot success metric', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12848',
    name: 'Block Utilization Quality Abstraction Validation Cohort Mismatch',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when block utilization is used for quality abstraction but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is CMS CoP: AbarVa should turn this into a Moves clinical governance checklist and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when OR scheduling AI is not proven in production.`,
    keywords: ['block utilization', 'OR scheduling AI', 'CMS CoP', 'SOC 2 Type II', 'clinical governance checklist', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  },
  {
    code: 'H12849',
    name: 'TJC Patient Outreach Adoption Telemetry Missing',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Perioperative, OR Robotics & Surgical AI initiatives fail when TJC is used for patient outreach but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves adoption plan and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when robotics is not proven in production.`,
    keywords: ['TJC', 'robotics', 'NCQA HEDIS audit', 'HITRUST roadmap', 'adoption plan', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Perioperative, OR Robotics & Surgical AI',
  }
];
