/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 37: Agentic Care Navigation & Transitions
// Part 4: H11350-H11399
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM37_PART4_PATTERNS = [
  {
    code: 'H11350',
    name: 'Care Navigation Agent Worklist Prioritization Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for worklist prioritization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'FHIR R4 mapping', 'Azure Health Data Services', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11351',
    name: 'ADT Feed Appeal Generation Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for appeal generation but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'HL7 v2 ADT reconciliation', 'Snowflake Healthcare', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11352',
    name: 'Discharge Follow Up Order Recommendation Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 80,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for order recommendation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is Epic change control: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'Epic change control', 'Databricks Lakehouse', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11353',
    name: 'FHIR Tasks Benefit Verification Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for benefit verification but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is model registry: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'model registry', 'ServiceNow workflow', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11354',
    name: 'Readmission Risk Eligibility Prediction Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for eligibility prediction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'deployment-site validation', 'Salesforce Health Cloud', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11355',
    name: 'Care Navigation Agent Care Gap Closure Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for care gap closure but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'MLOps monitoring', 'startup maturity evidence', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11356',
    name: 'ADT Feed Cohort Matching Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for cohort matching but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is clinical safety review: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'clinical safety review', 'SOC 2 Type II', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11357',
    name: 'Discharge Follow Up Contract Analysis Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for contract analysis but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'procurement RFP scoring', 'HITRUST roadmap', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11358',
    name: 'FHIR Tasks Agentic Orchestration Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for agentic orchestration but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'BAFO contract clause', 'Series B burn rate', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11359',
    name: 'Readmission Risk Coding Suggestion Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for coding suggestion but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'HIPAA BAA', 'implementation partner capacity', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11360',
    name: 'Care Navigation Agent Documentation Review Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for documentation review but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'minimum necessary policy', 'referenceable health-system customer', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11361',
    name: 'ADT Feed Vendor Comparison Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 77,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for vendor comparison but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'TJC survey evidence', 'clinical advisory board', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11362',
    name: 'Discharge Follow Up Capacity Forecasting Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 83,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for capacity forecasting but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is CMS CoP: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'CMS CoP', 'FDA submission posture', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11363',
    name: 'FHIR Tasks Staffing Optimization Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for staffing optimization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'NCQA HEDIS audit', 'KLAS commentary', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11364',
    name: 'Readmission Risk Quality Abstraction Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for quality abstraction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'FDA SaMD guidance', 'Epic App Orchard integration', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11365',
    name: 'Care Navigation Agent Patient Outreach Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 72,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for patient outreach but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'NIST AI RMF', 'Microsoft Cloud for Healthcare', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11366',
    name: 'ADT Feed Triage Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for triage but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'ONC HTI-1', 'AWS HealthLake', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11367',
    name: 'Discharge Follow Up Drafting Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for drafting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'TEFCA participation', 'Azure Health Data Services', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11368',
    name: 'FHIR Tasks Summarization Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for summarization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'FHIR R4 mapping', 'Snowflake Healthcare', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11369',
    name: 'Readmission Risk Risk Scoring Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for risk scoring but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'HL7 v2 ADT reconciliation', 'Databricks Lakehouse', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11370',
    name: 'Care Navigation Agent Worklist Prioritization Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for worklist prioritization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is Epic change control: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'Epic change control', 'ServiceNow workflow', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11371',
    name: 'ADT Feed Appeal Generation Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for appeal generation but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is model registry: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'model registry', 'Salesforce Health Cloud', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11372',
    name: 'Discharge Follow Up Order Recommendation Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for order recommendation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'deployment-site validation', 'startup maturity evidence', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11373',
    name: 'FHIR Tasks Benefit Verification Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 58,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for benefit verification but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'MLOps monitoring', 'SOC 2 Type II', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11374',
    name: 'Readmission Risk Eligibility Prediction Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 54,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for eligibility prediction but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'clinical safety review', 'HITRUST roadmap', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11375',
    name: 'Care Navigation Agent Care Gap Closure Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for care gap closure but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'procurement RFP scoring', 'Series B burn rate', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11376',
    name: 'ADT Feed Cohort Matching Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for cohort matching but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'BAFO contract clause', 'implementation partner capacity', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11377',
    name: 'Discharge Follow Up Contract Analysis Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 81,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for contract analysis but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'HIPAA BAA', 'referenceable health-system customer', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11378',
    name: 'FHIR Tasks Agentic Orchestration Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for agentic orchestration but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'minimum necessary policy', 'clinical advisory board', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11379',
    name: 'Readmission Risk Coding Suggestion Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for coding suggestion but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'TJC survey evidence', 'FDA submission posture', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11380',
    name: 'Care Navigation Agent Documentation Review Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for documentation review but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'CMS CoP', 'KLAS commentary', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11381',
    name: 'ADT Feed Vendor Comparison Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for vendor comparison but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'NCQA HEDIS audit', 'Epic App Orchard integration', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11382',
    name: 'Discharge Follow Up Capacity Forecasting Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for capacity forecasting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'FDA SaMD guidance', 'Microsoft Cloud for Healthcare', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11383',
    name: 'FHIR Tasks Staffing Optimization Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for staffing optimization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'NIST AI RMF', 'AWS HealthLake', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11384',
    name: 'Readmission Risk Quality Abstraction Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for quality abstraction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'ONC HTI-1', 'Azure Health Data Services', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11385',
    name: 'Care Navigation Agent Patient Outreach Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 72,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for patient outreach but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'TEFCA participation', 'Snowflake Healthcare', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11386',
    name: 'ADT Feed Triage Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for triage but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'FHIR R4 mapping', 'Databricks Lakehouse', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11387',
    name: 'Discharge Follow Up Drafting Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for drafting but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'HL7 v2 ADT reconciliation', 'ServiceNow workflow', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11388',
    name: 'FHIR Tasks Summarization Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for summarization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'Epic change control', 'Salesforce Health Cloud', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11389',
    name: 'Readmission Risk Risk Scoring Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for risk scoring but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'model registry', 'startup maturity evidence', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11390',
    name: 'Care Navigation Agent Worklist Prioritization Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for worklist prioritization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'deployment-site validation', 'SOC 2 Type II', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11391',
    name: 'ADT Feed Appeal Generation Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for appeal generation but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'MLOps monitoring', 'HITRUST roadmap', 'unsafe-to-fund gate', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11392',
    name: 'Discharge Follow Up Order Recommendation Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 83,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for order recommendation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves value realization ledger and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'clinical safety review', 'Series B burn rate', 'value realization ledger', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11393',
    name: 'FHIR Tasks Benefit Verification Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for benefit verification but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pilot success metric and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'procurement RFP scoring', 'implementation partner capacity', 'pilot success metric', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11394',
    name: 'Readmission Risk Eligibility Prediction Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for eligibility prediction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves clinical governance checklist and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'BAFO contract clause', 'referenceable health-system customer', 'clinical governance checklist', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11395',
    name: 'Care Navigation Agent Care Gap Closure Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Agentic Care Navigation & Transitions initiatives fail when care navigation agent is used for care gap closure but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves adoption plan and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when discharge follow-up is not proven in production.`,
    keywords: ['care navigation agent', 'discharge follow-up', 'HIPAA BAA', 'clinical advisory board', 'adoption plan', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11396',
    name: 'ADT Feed Cohort Matching Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Agentic Care Navigation & Transitions initiatives fail when ADT feed is used for cohort matching but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pre-mortem risk and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when FHIR Tasks is not proven in production.`,
    keywords: ['ADT feed', 'FHIR Tasks', 'minimum necessary policy', 'FDA submission posture', 'pre-mortem risk', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11397',
    name: 'Discharge Follow Up Contract Analysis Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Agentic Care Navigation & Transitions initiatives fail when discharge follow-up is used for contract analysis but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves dependency map and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when readmission risk is not proven in production.`,
    keywords: ['discharge follow-up', 'readmission risk', 'TJC survey evidence', 'KLAS commentary', 'dependency map', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11398',
    name: 'FHIR Tasks Agentic Orchestration Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Agentic Care Navigation & Transitions initiatives fail when FHIR Tasks is used for agentic orchestration but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves approval gate and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when care navigation agent is not proven in production.`,
    keywords: ['FHIR Tasks', 'care navigation agent', 'CMS CoP', 'Epic App Orchard integration', 'approval gate', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic Care Navigation & Transitions',
  },
  {
    code: 'H11399',
    name: 'Readmission Risk Coding Suggestion Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Agentic Care Navigation & Transitions initiatives fail when readmission risk is used for coding suggestion but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves benefit validation plan and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when ADT feed is not proven in production.`,
    keywords: ['readmission risk', 'ADT feed', 'NCQA HEDIS audit', 'Microsoft Cloud for Healthcare', 'benefit validation plan', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic Care Navigation & Transitions',
  }
];
