/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 60: Supply Chain, Procurement & Purchased Services AI
// Part 1: H15800-H15849
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM60_PART1_PATTERNS = [
  {
    code: 'H15800',
    name: 'Healthcare Supply Chain Triage Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for triage but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'HIPAA BAA', 'AWS HealthLake', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15801',
    name: 'GHX Drafting Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for drafting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'minimum necessary policy', 'Azure Health Data Services', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15802',
    name: 'Vizient Summarization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for summarization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'TJC survey evidence', 'Snowflake Healthcare', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15803',
    name: 'Contract Compliance Risk Scoring Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for risk scoring but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is CMS CoP: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'CMS CoP', 'Databricks Lakehouse', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15804',
    name: 'AI Sourcing Worklist Prioritization Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for worklist prioritization but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'NCQA HEDIS audit', 'ServiceNow workflow', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15805',
    name: 'Healthcare Supply Chain Appeal Generation Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for appeal generation but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'FDA SaMD guidance', 'Salesforce Health Cloud', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15806',
    name: 'GHX Order Recommendation Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for order recommendation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'NIST AI RMF', 'startup maturity evidence', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15807',
    name: 'Vizient Benefit Verification Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for benefit verification but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'ONC HTI-1', 'SOC 2 Type II', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15808',
    name: 'Contract Compliance Eligibility Prediction Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for eligibility prediction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'TEFCA participation', 'HITRUST roadmap', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15809',
    name: 'AI Sourcing Care Gap Closure Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for care gap closure but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'FHIR R4 mapping', 'Series B burn rate', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15810',
    name: 'Healthcare Supply Chain Cohort Matching Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for cohort matching but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'HL7 v2 ADT reconciliation', 'implementation partner capacity', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15811',
    name: 'GHX Contract Analysis Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for contract analysis but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is Epic change control: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'Epic change control', 'referenceable health-system customer', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15812',
    name: 'Vizient Agentic Orchestration Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for agentic orchestration but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is model registry: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'model registry', 'clinical advisory board', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15813',
    name: 'Contract Compliance Coding Suggestion Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for coding suggestion but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'deployment-site validation', 'FDA submission posture', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15814',
    name: 'AI Sourcing Documentation Review Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for documentation review but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'MLOps monitoring', 'KLAS commentary', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15815',
    name: 'Healthcare Supply Chain Vendor Comparison Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for vendor comparison but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is clinical safety review: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'clinical safety review', 'Epic App Orchard integration', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15816',
    name: 'GHX Capacity Forecasting Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for capacity forecasting but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'procurement RFP scoring', 'Microsoft Cloud for Healthcare', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15817',
    name: 'Vizient Staffing Optimization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for staffing optimization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'BAFO contract clause', 'AWS HealthLake', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15818',
    name: 'Contract Compliance Quality Abstraction Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for quality abstraction but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'HIPAA BAA', 'Azure Health Data Services', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15819',
    name: 'AI Sourcing Patient Outreach Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for patient outreach but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'minimum necessary policy', 'Snowflake Healthcare', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15820',
    name: 'Healthcare Supply Chain Triage Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for triage but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'TJC survey evidence', 'Databricks Lakehouse', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15821',
    name: 'GHX Drafting Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for drafting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is CMS CoP: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'CMS CoP', 'ServiceNow workflow', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15822',
    name: 'Vizient Summarization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for summarization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'NCQA HEDIS audit', 'Salesforce Health Cloud', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15823',
    name: 'Contract Compliance Risk Scoring Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for risk scoring but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'FDA SaMD guidance', 'startup maturity evidence', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15824',
    name: 'AI Sourcing Worklist Prioritization Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for worklist prioritization but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'NIST AI RMF', 'SOC 2 Type II', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15825',
    name: 'Healthcare Supply Chain Appeal Generation Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for appeal generation but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'ONC HTI-1', 'HITRUST roadmap', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15826',
    name: 'GHX Order Recommendation Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for order recommendation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'TEFCA participation', 'Series B burn rate', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15827',
    name: 'Vizient Benefit Verification Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for benefit verification but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'FHIR R4 mapping', 'implementation partner capacity', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15828',
    name: 'Contract Compliance Eligibility Prediction Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for eligibility prediction but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'HL7 v2 ADT reconciliation', 'referenceable health-system customer', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15829',
    name: 'AI Sourcing Care Gap Closure Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for care gap closure but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is Epic change control: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'Epic change control', 'clinical advisory board', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15830',
    name: 'Healthcare Supply Chain Cohort Matching Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for cohort matching but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is model registry: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'model registry', 'FDA submission posture', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15831',
    name: 'GHX Contract Analysis Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for contract analysis but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'deployment-site validation', 'KLAS commentary', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15832',
    name: 'Vizient Agentic Orchestration Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for agentic orchestration but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'MLOps monitoring', 'Epic App Orchard integration', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15833',
    name: 'Contract Compliance Coding Suggestion Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for coding suggestion but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is clinical safety review: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'clinical safety review', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15834',
    name: 'AI Sourcing Documentation Review Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for documentation review but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'procurement RFP scoring', 'AWS HealthLake', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15835',
    name: 'Healthcare Supply Chain Vendor Comparison Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for vendor comparison but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'BAFO contract clause', 'Azure Health Data Services', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15836',
    name: 'GHX Capacity Forecasting Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for capacity forecasting but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'HIPAA BAA', 'Snowflake Healthcare', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15837',
    name: 'Vizient Staffing Optimization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for staffing optimization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'minimum necessary policy', 'Databricks Lakehouse', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15838',
    name: 'Contract Compliance Quality Abstraction Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for quality abstraction but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'TJC survey evidence', 'ServiceNow workflow', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15839',
    name: 'AI Sourcing Patient Outreach Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 70,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for patient outreach but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is CMS CoP: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'CMS CoP', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15840',
    name: 'Healthcare Supply Chain Triage Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for triage but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'NCQA HEDIS audit', 'startup maturity evidence', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15841',
    name: 'GHX Drafting Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for drafting but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves pilot success metric and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'FDA SaMD guidance', 'SOC 2 Type II', 'pilot success metric', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15842',
    name: 'Vizient Summarization Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for summarization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves clinical governance checklist and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'NIST AI RMF', 'HITRUST roadmap', 'clinical governance checklist', 'RFI question'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15843',
    name: 'Contract Compliance Risk Scoring Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 72,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for risk scoring but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves adoption plan and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'ONC HTI-1', 'Series B burn rate', 'adoption plan', 'RFP scoring criterion'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15844',
    name: 'AI Sourcing Worklist Prioritization Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for worklist prioritization but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves pre-mortem risk and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'TEFCA participation', 'implementation partner capacity', 'pre-mortem risk', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15845',
    name: 'Healthcare Supply Chain Appeal Generation Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 80,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when healthcare supply chain is used for appeal generation but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves dependency map and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when Vizient is not proven in production.`,
    keywords: ['healthcare supply chain', 'Vizient', 'FHIR R4 mapping', 'referenceable health-system customer', 'dependency map', 'subprocessor schedule'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15846',
    name: 'GHX Order Recommendation Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when GHX is used for order recommendation but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves approval gate and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when contract compliance is not proven in production.`,
    keywords: ['GHX', 'contract compliance', 'HL7 v2 ADT reconciliation', 'clinical advisory board', 'approval gate', 'model audit right'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15847',
    name: 'Vizient Benefit Verification Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when Vizient is used for benefit verification but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is Epic change control: AbarVa should turn this into a Moves benefit validation plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when AI sourcing is not proven in production.`,
    keywords: ['Vizient', 'AI sourcing', 'Epic change control', 'FDA submission posture', 'benefit validation plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15848',
    name: 'Contract Compliance Eligibility Prediction Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 76,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when contract compliance is used for eligibility prediction but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is model registry: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when healthcare supply chain is not proven in production.`,
    keywords: ['contract compliance', 'healthcare supply chain', 'model registry', 'KLAS commentary', 'unsafe-to-fund gate', 'adoption telemetry clause'],
    demoRelevant: true,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  },
  {
    code: 'H15849',
    name: 'AI Sourcing Care Gap Closure Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Supply Chain, Procurement & Purchased Services AI initiatives fail when AI sourcing is used for care gap closure but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves value realization ledger and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when GHX is not proven in production.`,
    keywords: ['AI sourcing', 'GHX', 'deployment-site validation', 'Epic App Orchard integration', 'value realization ledger', 'exit-rights clause'],
    demoRelevant: false,
    subTopic: 'Supply Chain, Procurement & Purchased Services AI',
  }
];
