interface PatternSeed {
  code: string;
  name: string;
  description: string;
  vertical: string;
  office_category: string;
  keywords: string[];
  failure_rate_pct: number;
  is_active: boolean;
  demoRelevant: boolean;
  subTopic: string;
  data: Record<string, string | number | boolean>;
}

export const MEDTECH_DOM03_QMS_PART5_PATTERNS: PatternSeed[] = [

  // ── CAPA Effectiveness (M640–M651) ────────────────────────────────────────

  {
    code: 'M640',
    name: 'CAPA Root Cause Analysis Limited to Symptom Correction Without Systemic Investigation',
    description: 'NorthStar Clinical closes CAPA records after addressing the immediate symptom without performing a systemic root cause investigation, resulting in recurring nonconformances and repeat FDA observations during 21 CFR Part 820 inspections.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa', 'root-cause-analysis', 'iso-13485', 'fda-820', 'systemic-investigation'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA root cause shallow analysis limited to immediate symptom without systemic investigation',
      regulatoryHook: 'ISO 13485:2016 §8.5.2; FDA 21 CFR 820.100(a)(1); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'CAPA trend analysis comparing initial root cause to recurrence rate within 12-month window',
      remediationPath: 'Mandate structured RCA tool (5-Why, fishbone) with documented evidence; require QA director sign-off before closure',
      estimatedCost: '$80K–$250K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '68% of FDA 483 observations cite CAPA root cause inadequacy as a primary finding',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M641',
    name: 'CAPA Effectiveness Verification Skipped After Implementation',
    description: 'NorthStar Clinical marks CAPAs complete upon implementation of the corrective action without conducting a post-implementation effectiveness check, leaving the quality system blind to whether the corrective action actually eliminated the root cause.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-effectiveness', 'verification', 'iso-13485', 'fda-820', 'post-implementation'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'Effectiveness verification step absent from CAPA workflow; closure criteria do not require demonstrated recurrence prevention',
      regulatoryHook: 'ISO 13485:2016 §8.5.2(f); FDA 21 CFR 820.100(b); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'CAPA record audit checking for effectiveness check dates and objective evidence of non-recurrence',
      remediationPath: 'Add mandatory effectiveness verification milestone to CAPA SOP with minimum 90-day post-closure monitoring period',
      estimatedCost: '$50K–$180K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '59% of medtech companies lack documented effectiveness verification in over half of closed CAPAs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M642',
    name: 'CAPA Timeliness Breach — Open CAPAs Exceeding 180-Day Target Without Justified Extension',
    description: 'NorthStar Clinical has a backlog of CAPAs open beyond 180 days without documented justification or management review escalation, a condition that signals systemic quality system dysfunction to MDSAP auditors and FDA investigators.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-timeliness', 'backlog', 'mdsap', 'fda-820', 'management-review'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'Open CAPA backlog exceeds 180 days without documented management-approved extension justification',
      regulatoryHook: 'ISO 13485:2016 §8.5.2; FDA 21 CFR 820.100; MDSAP Audit Approach Chapter 7 timeliness criteria',
      detectionMethod: 'CAPA aging report filtered for records open greater than 180 days; cross-check management review minutes',
      remediationPath: 'Implement CAPA age dashboard with automatic escalation at 90 and 150 days; require VP Quality sign-off for extensions',
      estimatedCost: '$40K–$150K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '44% of ISO 13485-certified sites carry CAPAs open beyond 6 months at any given time',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M643',
    name: 'CAPA Source Data Excludes Complaint Trend Signals from Triggering Corrective Actions',
    description: 'NorthStar Clinical CAPA process relies on individual complaint records rather than complaint trend analysis, causing systemic product failure modes to go undetected until they rise to MDR threshold rather than being captured by proactive CAPA.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-sources', 'complaint-trends', 'iso-13485', 'mdr', 'proactive-quality'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA inputs do not include periodic complaint trend analysis; systemic signals missed until MDR threshold reached',
      regulatoryHook: 'ISO 13485:2016 §8.5.1, §8.5.2; FDA 21 CFR 820.100(a); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Map CAPA source codes against complaint database; identify CAPAs opened reactively after MDR vs proactively from trends',
      remediationPath: 'Establish monthly complaint trend review as mandatory CAPA input; define statistical signal thresholds for auto-trigger',
      estimatedCost: '$60K–$200K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '52% of medtech firms lack a formal complaint-to-CAPA trending trigger in their QMS procedures',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-generated complaint summaries may mask trend signals if individual records are aggregated without preserving failure mode granularity',
    },
  },
  {
    code: 'M644',
    name: 'CAPA Scope Insufficiently Broad — Single-Site Fix Applied Where Multi-Site Risk Exists',
    description: 'NorthStar Clinical issues CAPAs scoped to the manufacturing site where a nonconformance was discovered without evaluating whether the root cause and corrective action apply to other manufacturing sites, creating uncorrected risk across the product line.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-scope', 'multi-site', 'iso-13485', 'risk-extension', 'fda-820'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA remediation applied only to originating site; no lateral risk assessment for identical processes at other sites',
      regulatoryHook: 'ISO 13485:2016 §8.5.2; FDA 21 CFR 820.100; MDSAP Audit Approach Chapter 7 lateral extension requirement',
      detectionMethod: 'CAPA records audit for multi-site scope field; compare against manufacturing site list for same device family',
      remediationPath: 'Add mandatory lateral risk assessment step to CAPA procedure; require quality manager sign-off for single-site scope justification',
      estimatedCost: '$70K–$220K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '38% of FDA warning letters cite failure to extend CAPA scope to all applicable sites and products',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M645',
    name: 'Preventive Action Programme Absent — CAPA System Operates Purely Correctively',
    description: 'NorthStar Clinical quality system records show near-zero preventive actions initiated, indicating the PA component of the CAPA process is non-functional and the organisation is managing quality entirely reactively in violation of ISO 13485 §8.5.3.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['preventive-action', 'capa', 'iso-13485-8-5-3', 'proactive-quality', 'fda-820'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'Preventive action initiation rate near zero; quality system reactive only with no proactive risk-based PA programme',
      regulatoryHook: 'ISO 13485:2016 §8.5.3; FDA 21 CFR 820.100(a)(6); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'PA-to-CA ratio audit over 24 months; review sources feeding preventive action programme',
      remediationPath: 'Establish PA trigger criteria from risk reviews, audit trends, and process capability data; set minimum PA initiation KPI',
      estimatedCost: '$45K–$170K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '71% of ISO 13485 surveillance audits cite inadequate preventive action programmes',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M646',
    name: 'CAPA Verification of Implementation Not Distinguished from Effectiveness Verification',
    description: 'NorthStar Clinical CAPA records conflate implementation verification (was the action taken?) with effectiveness verification (did it work?), causing premature closure and repeat nonconformances that attract regulatory scrutiny.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-closure', 'implementation-verification', 'effectiveness-check', 'iso-13485', 'fda-820'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA closure conflates implementation confirmation with effectiveness evidence; recurrence data not gathered',
      regulatoryHook: 'ISO 13485:2016 §8.5.2(e)(f); FDA 21 CFR 820.100(b); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Closed CAPA sample review distinguishing implementation date from effectiveness check date and evidence type',
      remediationPath: 'Revise CAPA form to require separate sections for implementation evidence and effectiveness evidence with distinct timestamps',
      estimatedCost: '$30K–$100K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '46% of medtech CAPA closures lack distinct effectiveness evidence separate from implementation confirmation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M647',
    name: 'CAPA Risk Assessment Not Updated When Root Cause Reveals Broader Design Risk',
    description: 'NorthStar Clinical CAPA investigations that uncover design-level root causes do not trigger a design risk file update or Design FMEA revision, leaving the risk management file out of sync with known failure modes.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-risk-linkage', 'dfmea', 'iso-14971', 'iso-13485', 'risk-file'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA root causes implicating design not propagated to risk management file or DFMEA; risk file stale',
      regulatoryHook: 'ISO 13485:2016 §8.5.2; ISO 14971:2019 §10; FDA 21 CFR 820.30(g)',
      detectionMethod: 'Cross-reference CAPA root cause codes tagged as design-related against risk file revision history',
      remediationPath: 'Add risk file impact assessment to CAPA workflow; require risk manager review when design root cause identified',
      estimatedCost: '$55K–$190K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '43% of medtech CAPAs with design root causes show no corresponding risk file update within 6 months',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M648',
    name: 'CAPA Training Records Absent — Corrective Actions Requiring Procedural Change Lack Implementation Evidence',
    description: 'NorthStar Clinical CAPAs that mandate SOP revisions have no linked training records confirming affected personnel were retrained before the corrective action was considered implemented, violating ISO 13485 training requirements.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-training', 'sop-revision', 'iso-13485', 'training-records', 'fda-820'],
    failure_rate_pct: 52.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA-driven SOP revisions lack training completion records; personnel continue using pre-corrective-action practices',
      regulatoryHook: 'ISO 13485:2016 §6.2, §8.5.2; FDA 21 CFR 820.25, 820.100',
      detectionMethod: 'Link CAPA records requiring procedure changes to training completion LMS data; identify gaps in retraining evidence',
      remediationPath: 'Integrate training management system with CAPA workflow; block CAPA closure until training compliance verified',
      estimatedCost: '$35K–$130K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '41% of medtech CAPA closures involving SOP changes lack documented retraining evidence',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M649',
    name: 'CAPA Management Review Input Absent — Recurring Quality Issues Not Escalated to Leadership',
    description: 'NorthStar Clinical management review agenda does not include CAPA performance metrics or trend summaries, depriving leadership of the quality signals needed to allocate resources and make strategic corrections.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['management-review', 'capa-metrics', 'iso-13485-5-6', 'quality-kpis', 'leadership'],
    failure_rate_pct: 49.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'Management review inputs omit CAPA aging, recurrence rates, and effectiveness metrics; leadership uninformed',
      regulatoryHook: 'ISO 13485:2016 §5.6.2(b); FDA 21 CFR 820.20(c); MDSAP Audit Approach Chapter 2',
      detectionMethod: 'Review management review minutes over 24 months for CAPA performance section; compare against CAPA system data',
      remediationPath: 'Add CAPA performance dashboard as mandatory management review agenda item with defined KPIs and trend charts',
      estimatedCost: '$25K–$90K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '37% of ISO 13485 surveillance audits note CAPA metrics absent from management review inputs',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M650',
    name: 'CAPA Initiated Without Documented Problem Statement Using Objective Quality Data',
    description: 'NorthStar Clinical CAPA records show problem statements based on verbal descriptions or informal observations rather than objective quality data, undermining the defensibility of root cause analysis during regulatory inspections.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-problem-statement', 'objective-evidence', 'iso-13485', 'fda-820', 'data-driven'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA problem statements anecdotal; lack quantified defect data, lot numbers, or objective quality records',
      regulatoryHook: 'ISO 13485:2016 §8.5.2(a); FDA 21 CFR 820.100(a)(1); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'CAPA problem statement quality audit scoring objectivity, data linkage, and specificity on a defined rubric',
      remediationPath: 'Mandate problem statement template requiring data source, defect quantity, affected product/lot, and detection method',
      estimatedCost: '$20K–$75K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '49% of CAPA problem statements reviewed in FDA inspections lack objective quantified data',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-drafted CAPA problem statements may paraphrase complaint text without pulling objective defect data from QMS database',
    },
  },
  {
    code: 'M651',
    name: 'CAPA Closure Approved by Initiating Party Rather Than Independent Quality Reviewer',
    description: 'NorthStar Clinical allows the same person who opened a CAPA to approve its closure, removing the independence check that ensures objective effectiveness assessment and creating a conflict of interest visible to MDSAP auditors.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['capa-independence', 'closure-approval', 'iso-13485', 'conflict-of-interest', 'mdsap'],
    failure_rate_pct: 48.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'capa-effectiveness',
    data: {
      failureMode: 'CAPA initiator and closure approver are the same individual; no independent quality review gate',
      regulatoryHook: 'ISO 13485:2016 §8.5.2; MDSAP Audit Approach Chapter 7; FDA 21 CFR 820.100',
      detectionMethod: 'CAPA records audit comparing opener ID to closure approver ID; flag same-person records',
      remediationPath: 'Enforce four-eyes CAPA closure rule in eQMS workflow; require QA reviewer different from initiator for all closures',
      estimatedCost: '$15K–$60K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '29% of medtech eQMS configurations lack an independent reviewer enforcement on CAPA closure',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── Internal Audit Program (M652–M663) ────────────────────────────────────

  {
    code: 'M652',
    name: 'Internal Audit Finding Closure Lacking Objective Evidence of Corrective Action Completion',
    description: 'NorthStar Clinical internal audit findings are closed based on auditee verbal confirmation rather than objective evidence of corrective action completion, leaving the audit programme unable to demonstrate effectiveness to MDSAP auditors.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['internal-audit', 'finding-closure', 'objective-evidence', 'iso-13485', 'mdsap'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Internal audit finding closure gaps — findings closed on verbal assurance without documented objective evidence',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; MDSAP Audit Approach Chapter 7; FDA 21 CFR 820.22',
      detectionMethod: 'Closed audit finding sample review checking for attached objective evidence vs. text-only closure notes',
      remediationPath: 'Require mandatory evidence attachment in audit management system before finding can transition to closed status',
      estimatedCost: '$35K–$130K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '57% of ISO 13485 surveillance audits identify internal audit finding closure without sufficient objective evidence',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M653',
    name: 'Internal Audit Schedule Does Not Cover All QMS Processes Within the Audit Cycle',
    description: 'NorthStar Clinical annual internal audit schedule repeatedly omits or delays specific QMS clauses such as design controls, purchasing controls, and servicing, leaving unaudited gaps that become MDSAP major nonconformities.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['audit-schedule', 'qms-coverage', 'iso-13485-8-2-4', 'mdsap', 'audit-programme'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Internal audit programme coverage gaps — QMS clauses unaudited for 2+ years',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; MDSAP Audit Approach Chapter 4; FDA 21 CFR 820.22',
      detectionMethod: 'Audit coverage matrix mapping QMS clauses against audit records for a rolling 3-year period',
      remediationPath: 'Build clause-coverage matrix into annual audit programme; flag any clause unaudited >18 months for immediate scheduling',
      estimatedCost: '$40K–$140K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '45% of medtech internal audit programmes show at least one ISO 13485 clause unaudited in any given 24-month period',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M654',
    name: 'Internal Auditor Independence Compromised — Personnel Audit Their Own Work Areas',
    description: 'NorthStar Clinical assigns auditors to conduct audits of processes they directly own or manage, violating the ISO 13485 independence requirement and producing audit reports that understate real nonconformance rates.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['auditor-independence', 'iso-13485-8-2-4', 'conflict-of-interest', 'audit-programme'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Auditors assigned to own work areas; independence requirement violated; audit finding rate artificially suppressed',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; MDSAP Audit Approach Chapter 4; FDA 21 CFR 820.22',
      detectionMethod: 'Cross-reference auditor department assignments with auditee area records across 3 years of audit reports',
      remediationPath: 'Enforce cross-functional auditor assignment policy; use rotation matrix to prevent self-auditing; document independence attestation',
      estimatedCost: '$25K–$90K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '33% of small medtech companies assign department managers as primary auditors for their own departments',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M655',
    name: 'Audit Finding Severity Classification Inconsistent — Minor and Major Not Distinguished by Defined Criteria',
    description: 'NorthStar Clinical internal audit findings are classified as minor or major based on auditor judgment without defined criteria, producing inconsistent severity ratings that make trend analysis unreliable and CAPA prioritisation arbitrary.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['finding-classification', 'severity-criteria', 'iso-13485', 'audit-programme', 'consistency'],
    failure_rate_pct: 51.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Audit finding severity classification lacks defined criteria; auditor-to-auditor variance undermines trend analysis',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; MDSAP Audit Approach Chapter 4; FDA 21 CFR 820.22',
      detectionMethod: 'Inter-rater reliability study using sample findings classified independently by multiple auditors against defined criteria',
      remediationPath: 'Publish severity classification matrix with examples; conduct auditor calibration exercises annually',
      estimatedCost: '$20K–$75K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '39% of medtech audit programmes lack documented severity classification criteria for internal findings',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M656',
    name: 'Internal Audit Programme Not Risk-Based — High-Risk Processes Not Audited More Frequently',
    description: 'NorthStar Clinical internal audit schedule allocates equal frequency to all QMS processes regardless of risk level, failing to concentrate audit resources on sterilisation, cleanroom operations, and software validation where failures have the greatest patient safety impact.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['risk-based-audit', 'audit-frequency', 'iso-13485', 'patient-safety', 'mdsap'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Audit schedule not risk-stratified; high-risk processes audited at same frequency as low-risk administrative processes',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; MDSAP Audit Approach Chapter 4; ISO 19011:2018 risk-based approach',
      detectionMethod: 'Map audit frequency by process against process risk classification from risk management file',
      remediationPath: 'Stratify audit schedule by process risk; mandate semi-annual audits for critical processes; annual for standard processes',
      estimatedCost: '$30K–$110K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '48% of medtech audit programmes apply uniform frequency regardless of process risk level',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M657',
    name: 'Internal Audit Reports Not Communicated to Process Owners Within Defined Timeframe',
    description: 'NorthStar Clinical internal audit reports are issued to process owners weeks after audit completion, delaying corrective action initiation and creating a compliance gap between audit conduct and the response timeline expected under ISO 13485.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['audit-report-issuance', 'timeliness', 'iso-13485', 'process-owners', 'corrective-action'],
    failure_rate_pct: 44.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Audit report issuance delayed beyond defined SLA; process owners unable to initiate timely corrective actions',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; FDA 21 CFR 820.22; MDSAP Audit Approach Chapter 4',
      detectionMethod: 'Audit completion date vs. report issuance date comparison across last 24 months of audit programme records',
      remediationPath: 'Enforce 5-business-day report issuance SLA in audit SOP; automate report distribution via audit management system',
      estimatedCost: '$15K–$55K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '31% of medtech audit programmes have no defined report issuance timeline in their audit procedure',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M658',
    name: 'Supplier Audit Programme Absent Despite Critical Component Suppliers Identified',
    description: 'NorthStar Clinical has classified several component suppliers as critical but has not conducted supplier audits within the past 3 years, relying solely on incoming inspection to manage supplier quality risk.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['supplier-audit', 'critical-suppliers', 'iso-13485-7-4', 'purchasing-controls', 'mdsap'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Supplier audit programme absent for critical suppliers; quality oversight limited to incoming inspection',
      regulatoryHook: 'ISO 13485:2016 §7.4.1; FDA 21 CFR 820.50; MDSAP Audit Approach Chapter 6',
      detectionMethod: 'Approved supplier list audit cross-referenced with supplier audit records; identify critical suppliers with no audit in 36 months',
      remediationPath: 'Establish risk-based supplier audit programme; schedule critical supplier audits within 6 months; define audit frequency by risk tier',
      estimatedCost: '$70K–$230K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '53% of FDA warning letters cite inadequate supplier controls including absence of on-site supplier audits',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M659',
    name: 'Internal Audit Checklist Not Updated to Reflect Current Regulatory Requirements',
    description: 'NorthStar Clinical internal audit checklists have not been revised since original ISO 13485:2016 transition and do not reflect MDSAP Audit Approach updates, recent FDA guidance, or MDR/IVDR regulatory changes affecting the company\'s registered devices.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['audit-checklist', 'regulatory-updates', 'mdsap', 'iso-13485', 'mdr'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Audit checklists stale; MDSAP Audit Approach and regulatory updates not incorporated; emerging requirements missed',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; MDSAP Audit Approach (current revision); EU MDR 2017/745 Article 10',
      detectionMethod: 'Checklist version date audit compared against regulatory guidance publication dates for applicable requirements',
      remediationPath: 'Establish annual checklist review process aligned to MDSAP Audit Approach revision cycle; assign owner for each checklist section',
      estimatedCost: '$25K–$85K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '42% of medtech internal audit checklists are more than 2 years old at time of surveillance audit',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-assisted checklist generation may reproduce outdated regulatory references if training data predates current MDSAP revision',
    },
  },
  {
    code: 'M660',
    name: 'Internal Audit Results Not Aggregated for Management Review Quality Trend Analysis',
    description: 'NorthStar Clinical distributes individual audit reports to process owners but does not aggregate findings into a quality trend summary for management review, preventing the leadership team from seeing systemic quality patterns.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['audit-aggregation', 'management-review', 'quality-trends', 'iso-13485-5-6', 'kpis'],
    failure_rate_pct: 47.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Audit findings reported in isolation; no cross-process aggregation or trend analysis for management review input',
      regulatoryHook: 'ISO 13485:2016 §5.6.2(a), §8.2.4; MDSAP Audit Approach Chapter 2; FDA 21 CFR 820.20(c)',
      detectionMethod: 'Management review minutes audit for presence of aggregated internal audit trend data vs individual report attachments',
      remediationPath: 'Implement quarterly audit trend dashboard aggregating findings by clause, process, and severity; include in management review package',
      estimatedCost: '$30K–$100K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '38% of ISO 13485-certified sites do not produce aggregated audit trend reports for management review',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M661',
    name: 'Audit Corrective Action Response Deadlines Not Tracked or Escalated When Missed',
    description: 'NorthStar Clinical internal audit findings assigned corrective action response deadlines are not systematically tracked, with overdue responses going unnoticed until the next audit cycle uncovers the same finding.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['audit-capa-tracking', 'response-deadlines', 'iso-13485', 'escalation', 'audit-programme'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Audit finding response deadlines untracked; overdue CAPAs remain open without escalation until repeat audit',
      regulatoryHook: 'ISO 13485:2016 §8.2.4; FDA 21 CFR 820.22; MDSAP Audit Approach Chapter 4',
      detectionMethod: 'Audit finding age analysis comparing assigned response due date to actual closure date across 24-month window',
      remediationPath: 'Implement automated deadline tracking in audit management system with escalation notifications at 75% and 100% of deadline',
      estimatedCost: '$20K–$80K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '45% of medtech audit programmes lack automated deadline tracking for finding corrective actions',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M662',
    name: 'Internal Auditor Qualification Records Incomplete — Training and Competency Not Documented',
    description: 'NorthStar Clinical does not maintain documented auditor qualification records demonstrating training, competency assessment, and relevant experience for personnel conducting internal QMS audits.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['auditor-qualification', 'competency', 'iso-13485-6-2', 'training-records', 'mdsap'],
    failure_rate_pct: 43.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Auditor qualification records absent; competency of internal auditors unverifiable during regulatory audit',
      regulatoryHook: 'ISO 13485:2016 §6.2, §8.2.4; MDSAP Audit Approach Chapter 4; FDA 21 CFR 820.25',
      detectionMethod: 'Auditor assignment records cross-referenced against training and qualification documentation in HR/LMS',
      remediationPath: 'Establish auditor qualification procedure with required training, experience, and annual competency assessment criteria',
      estimatedCost: '$15K–$55K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '34% of medtech companies cannot produce complete auditor qualification records when requested during FDA inspection',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M663',
    name: 'Internal Audit Programme Scope Excludes Software Validation and IT Systems Supporting QMS',
    description: 'NorthStar Clinical internal audit programme covers manufacturing and quality processes but consistently excludes software validation status and IT system controls for eQMS, LMS, and SCADA systems that support regulated activities.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['software-validation-audit', 'csv', 'it-systems', 'iso-13485', 'eqms'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'internal-audit-program',
    data: {
      failureMode: 'Internal audit scope excludes software validation and IT system controls; computerised system risk unaudited',
      regulatoryHook: 'ISO 13485:2016 §7.5.6, §8.2.4; FDA 21 CFR Part 11; GAMP 5 Second Edition',
      detectionMethod: 'Audit programme scope document review for explicit inclusion of computer system validation and IT system controls',
      remediationPath: 'Expand audit programme scope to include annual CSV/computerised systems audit; assign qualified IT systems auditor',
      estimatedCost: '$40K–$140K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '49% of medtech audit programmes exclude computerised systems and software validation from scope',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI tools used in eQMS or LMS may introduce unvalidated software risk outside existing audit scope',
    },
  },

  // ── Complaint Management QMS (M664–M675) ──────────────────────────────────

  {
    code: 'M664',
    name: 'Complaint MDR/Vigilance Linkage Not Consistently Performed — Reportable Events Missed',
    description: 'NorthStar Clinical complaint records do not systematically trigger an MDR/vigilance reportability assessment, resulting in missed 30-day and 5-day MDR submissions and delayed vigilance reports to EU competent authorities.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-mdr', 'vigilance', 'fda-803', 'eu-mdr', 'reportability'],
    failure_rate_pct: 76.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint MDR/vigilance linkage absent; reportable adverse events not identified at intake; submission deadlines missed',
      regulatoryHook: 'FDA 21 CFR Part 803; EU MDR 2017/745 Article 87; ISO 13485:2016 §8.2.2',
      detectionMethod: 'Complaint record audit cross-referencing reportability decisions against MDR database and EU vigilance report log',
      remediationPath: 'Embed mandatory MDR/vigilance reportability decision tree at complaint intake; require regulatory affairs sign-off within 24 hours',
      estimatedCost: '$120K–$400K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '71% of FDA warning letters in class II/III device category cite MDR reporting failures linked to complaint system gaps',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI complaint triage that auto-classifies reportability may produce incorrect MDR determination if trained on incomplete adverse event criteria',
    },
  },
  {
    code: 'M665',
    name: 'Complaint Investigation Not Completed Within Defined 30-Day Timeline',
    description: 'NorthStar Clinical complaint investigations routinely exceed the 30-day investigation completion target with no escalation mechanism, creating a backlog of unresolved complaints visible to FDA investigators during 21 CFR Part 820 inspections.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-investigation', 'timeliness', 'fda-820-198', 'iso-13485', 'backlog'],
    failure_rate_pct: 63.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint investigation exceeds 30-day target; no escalation mechanism; investigation backlog accumulates',
      regulatoryHook: 'FDA 21 CFR 820.198(c); ISO 13485:2016 §8.2.2; MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Complaint age report filtered for open investigations beyond 30 days; trend analysis over 12-month window',
      remediationPath: 'Implement complaint management system with automated aging alerts at 15 and 25 days; escalate to quality manager at 30 days',
      estimatedCost: '$55K–$180K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '58% of medtech complaint systems show investigation backlog exceeding 30-day target at any point in year',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M666',
    name: 'Complaint Intake Process Fails to Capture All Feedback Channels — Service Reports Excluded',
    description: 'NorthStar Clinical complaint procedure only captures complaints received through the formal complaint hotline and email, excluding field service reports, sales team feedback, and social media channels where reportable adverse events are routinely described.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-intake', 'feedback-channels', 'iso-13485-8-2-2', 'fda-820-198', 'field-service'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint intake limited to formal channels; field service, sales, and digital channels not monitored for adverse event signals',
      regulatoryHook: 'FDA 21 CFR 820.198(a); ISO 13485:2016 §8.2.1, §8.2.2; EU MDR Article 83',
      detectionMethod: 'Audit complaint intake procedure against actual feedback channel inventory; sample field service reports for unlogged events',
      remediationPath: 'Expand complaint procedure to cover all feedback channels; train field service and sales on complaint identification and reporting',
      estimatedCost: '$40K–$140K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '47% of FDA inspections identify feedback channels outside the formal complaint system capturing adverse events',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M667',
    name: 'Complaint Trend Analysis Not Performed — Signal Detection Relies on Individual Record Review',
    description: 'NorthStar Clinical complaint quality review examines individual records without performing statistical trend analysis, preventing early detection of emerging failure modes that would trigger CAPA or design change before reaching MDR threshold.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-trending', 'signal-detection', 'iso-13485', 'post-market-surveillance', 'fda-820'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint review limited to individual records; trend analysis absent; emerging failure modes missed until MDR threshold',
      regulatoryHook: 'ISO 13485:2016 §8.2.2, §8.5.1; FDA 21 CFR 820.100; EU MDR Article 83 PMSR requirements',
      detectionMethod: 'Complaint database query for trend analysis reports and signal detection records over past 24 months',
      remediationPath: 'Implement monthly complaint trending by failure mode, product family, and geography; define signal thresholds with CAPA trigger criteria',
      estimatedCost: '$50K–$170K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '52% of medtech post-market surveillance programmes lack formal complaint trend signal detection criteria',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-powered complaint clustering may group dissimilar failure modes together masking distinct safety signals requiring separate MDR evaluation',
    },
  },
  {
    code: 'M668',
    name: 'Returned Device Evaluation Not Consistently Linked to Originating Complaint Record',
    description: 'NorthStar Clinical processes returned devices through the service department without consistently linking returned device evaluation results back to the originating complaint record, creating a disconnect between field failure data and complaint investigation conclusions.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['returned-device', 'complaint-linkage', 'iso-13485', 'fda-820-198', 'root-cause'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Returned device evaluation results not linked to complaint records; root cause conclusions lack physical device evidence',
      regulatoryHook: 'FDA 21 CFR 820.198(d); ISO 13485:2016 §8.2.2; MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Sample complaint records where device return was initiated; verify link to returned device evaluation report in QMS',
      remediationPath: 'Require complaint-to-device return cross-reference in complaint management system; block complaint closure until return evaluation attached',
      estimatedCost: '$30K–$110K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '41% of complaint records where device return is indicated lack linked returned device evaluation reports',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M669',
    name: 'Complaint Closure Without Customer Notification of Investigation Outcome',
    description: 'NorthStar Clinical closes complaint records without documenting that the customer was notified of the investigation outcome, creating a gap in customer communication records that regulators and notified bodies expect to see.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-closure', 'customer-notification', 'iso-13485-8-2-2', 'fda-820', 'communication'],
    failure_rate_pct: 46.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint closed without documented customer notification of investigation outcome; communication gap in complaint record',
      regulatoryHook: 'FDA 21 CFR 820.198(e); ISO 13485:2016 §8.2.2; MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Closed complaint sample review checking for customer notification date and communication method documentation',
      remediationPath: 'Add mandatory customer notification field to complaint closure workflow; require date and communication method before closure',
      estimatedCost: '$15K–$55K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '35% of closed complaint records reviewed in FDA inspections lack documented customer notification',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M670',
    name: 'Complaint Handling SOP Not Aligned with EU MDR Post-Market Surveillance Requirements',
    description: 'NorthStar Clinical complaint handling procedure was written to FDA 21 CFR Part 820 standards and has not been updated to incorporate EU MDR 2017/745 post-market surveillance obligations including PSUR and PMSR reporting cycles.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-sop', 'eu-mdr', 'pmsr', 'psur', 'post-market-surveillance'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint SOP aligned to FDA 820 only; EU MDR PSUR/PMSR complaint data collection requirements not addressed',
      regulatoryHook: 'EU MDR 2017/745 Articles 83–86; ISO 13485:2016 §8.2.2; FDA 21 CFR 820.198',
      detectionMethod: 'Gap analysis of complaint SOP against EU MDR Article 83 and MDCG 2020-7 guidance document requirements',
      remediationPath: 'Update complaint SOP to capture EU MDR data fields; assign EU MDR post-market coordinator; align complaint data to PSUR/PMSR template',
      estimatedCost: '$60K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '49% of US-headquartered medtech companies selling in EU have not updated complaint SOPs for MDR post-market requirements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M671',
    name: 'Complaint Decision Records Lack Documented Rationale for Not-a-Complaint Determinations',
    description: 'NorthStar Clinical frequently reclassifies incoming adverse event reports as "not a complaint" without documenting the rationale, creating a risk that reportable events are being filtered out of the complaint system without regulatory justification.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['not-a-complaint', 'decision-rationale', 'fda-820-198', 'iso-13485', 'adverse-events'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Not-a-complaint determinations made without documented rationale; potential adverse events filtered without regulatory justification',
      regulatoryHook: 'FDA 21 CFR 820.198(a)(b); ISO 13485:2016 §8.2.2; FDA Complaint Guidance 2023',
      detectionMethod: 'Audit not-a-complaint database for documented decision rationale; sample review against complaint intake criteria',
      remediationPath: 'Require documented decision rationale for all not-a-complaint determinations; implement second-reviewer approval for rejections',
      estimatedCost: '$35K–$120K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '55% of FDA inspections reviewing complaint intake processes identify undocumented not-a-complaint determinations',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-powered complaint intake triage may automatically classify adverse events as not-a-complaint without auditable decision rationale',
    },
  },
  {
    code: 'M672',
    name: 'Complaint Records Inaccessible for 7-Year Retention Period Due to Legacy System Migration',
    description: 'NorthStar Clinical migrated complaint data to a new eQMS without validating the completeness and accessibility of migrated historical records, with a subset of complaints predating the migration inaccessible or corrupted.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-retention', 'data-migration', 'eqms', 'iso-13485-4-2-5', 'fda-820'],
    failure_rate_pct: 41.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Historical complaint records inaccessible post-eQMS migration; retention obligation breached for migrated records',
      regulatoryHook: 'ISO 13485:2016 §4.2.5; FDA 21 CFR 820.198(g), 820.180; EU MDR Article 10(8)',
      detectionMethod: 'Data migration validation report review; sample query of complaints predating migration date for record accessibility',
      remediationPath: 'Commission data migration validation; restore or archive inaccessible records; document migration qualification evidence',
      estimatedCost: '$80K–$260K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '28% of medtech eQMS migrations result in at least partial historical complaint record loss or inaccessibility',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M673',
    name: 'Complaint System Does Not Distinguish Complaints Requiring MDR from Those Not Requiring MDR',
    description: 'NorthStar Clinical complaint management system treats all complaints in a single workflow without a bifurcated process for MDR-required events, leading to MDR-reportable complaints proceeding through standard investigation timelines that exceed the 30-day MDR submission deadline.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdr-workflow', 'complaint-bifurcation', 'fda-803', 'iso-13485', 'adverse-event'],
    failure_rate_pct: 69.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'MDR-reportable complaints processed through standard workflow; 30-day MDR deadline not supported by accelerated pathway',
      regulatoryHook: 'FDA 21 CFR Part 803.50; ISO 13485:2016 §8.2.2; MDSAP Audit Approach Chapter 7',
      detectionMethod: 'MDR submission database cross-referenced with complaint records; compare complaint intake date to MDR submission date',
      remediationPath: 'Implement bifurcated complaint workflow with expedited MDR track; define MDR-suspect flag at intake with regulatory affairs escalation',
      estimatedCost: '$65K–$210K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '62% of FDA 483 observations on complaint handling cite failure to meet MDR reporting timelines for events in the complaint system',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M674',
    name: 'Complaint Investigation Conclusions Not Supported by Objective Physical or Test Evidence',
    description: 'NorthStar Clinical complaint investigation conclusions are written without supporting physical device inspection records, lab test results, or usage data, making root cause determinations unverifiable during FDA inspections and MDSAP audits.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-investigation-evidence', 'objective-evidence', 'fda-820-198', 'iso-13485', 'root-cause'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint conclusions lack linked objective evidence; root cause determinations unsupported by physical inspection or test data',
      regulatoryHook: 'FDA 21 CFR 820.198(d); ISO 13485:2016 §8.2.2; MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Complaint investigation record sample review scoring evidence quality and linkage to physical or test data',
      remediationPath: 'Define minimum evidence requirements for complaint investigation conclusions; require evidence checklist before investigation closure',
      estimatedCost: '$35K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '44% of complaint investigation conclusions reviewed in FDA inspections lack supporting objective evidence attachments',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M675',
    name: 'Complaint Rate Metrics Not Included in Management Review Quality KPI Dashboard',
    description: 'NorthStar Clinical management review does not include complaint rate by product family as a standing quality KPI, depriving leadership of the post-market signal data required for informed resource allocation and risk-based decisions.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['complaint-metrics', 'management-review', 'iso-13485-5-6', 'quality-kpis', 'post-market'],
    failure_rate_pct: 45.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'complaint-management-qms',
    data: {
      failureMode: 'Complaint rate KPIs absent from management review; leadership lacks post-market quality signal visibility',
      regulatoryHook: 'ISO 13485:2016 §5.6.2; MDSAP Audit Approach Chapter 2; FDA 21 CFR 820.20(c)',
      detectionMethod: 'Management review agendas and minutes audit for complaint rate KPI section over 24-month period',
      remediationPath: 'Add complaint rate by product family and complaint-to-MDR conversion rate as mandatory management review KPIs',
      estimatedCost: '$20K–$70K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '36% of ISO 13485-certified sites omit complaint rate data from management review quality KPI packages',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── Nonconforming Product (M676–M687) ─────────────────────────────────────

  {
    code: 'M676',
    name: 'Nonconforming Product Disposition Decisions Made Without Defined Review Authority',
    description: 'NorthStar Clinical nonconforming product disposition decisions are made ad hoc by production supervisors without a defined disposition authority matrix specifying who can approve use-as-is, rework, scrap, or return-to-supplier decisions.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['nonconforming-product', 'disposition-authority', 'iso-13485-8-3', 'fda-820-90', 'review-triggers'],
    failure_rate_pct: 66.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Nonconformance review triggers absent; disposition made by production without quality sign-off or defined authority matrix',
      regulatoryHook: 'ISO 13485:2016 §8.3.2; FDA 21 CFR 820.90(a)(b); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Nonconforming material record audit identifying disposition approver role and comparing against authority matrix',
      remediationPath: 'Define disposition authority matrix by nonconformance type and risk level; enforce QA approval for all use-as-is and rework decisions',
      estimatedCost: '$35K–$130K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '61% of FDA 21 CFR 820.90 observations cite absence of defined nonconforming product review and disposition authority',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M677',
    name: 'Nonconforming Product Segregation Controls Inadequate — Risk of Inadvertent Release to Distribution',
    description: 'NorthStar Clinical nonconforming product is placed on physical hold without reliable labelling and segregation controls, creating a risk that nonconforming devices are inadvertently picked for distribution when hold labels fall off or are removed.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['nonconforming-segregation', 'physical-controls', 'iso-13485-8-3', 'fda-820-90', 'distribution-risk'],
    failure_rate_pct: 59.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Physical segregation of nonconforming product relies on paper labels only; no system-level inventory hold to prevent inadvertent release',
      regulatoryHook: 'ISO 13485:2016 §8.3.2; FDA 21 CFR 820.90(a); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Warehouse walkthrough cross-referencing nonconforming lot numbers against ERP inventory hold status; label integrity observation',
      remediationPath: 'Implement ERP system hold codes as primary segregation control; physical labels as secondary; reconcile holds daily',
      estimatedCost: '$40K–$150K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '48% of FDA device inspection 483 observations on nonconforming product cite inadequate physical segregation controls',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M678',
    name: 'Concession (Use-As-Is) Disposition Used Without Customer or Regulatory Notification Where Required',
    description: 'NorthStar Clinical approves use-as-is dispositions for nonconforming components incorporated into Class II devices without evaluating whether the concession requires customer notification or regulatory reporting under applicable standards.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['concession', 'use-as-is', 'iso-13485-8-3-3', 'customer-notification', 'regulatory-reporting'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Concession dispositions approved without evaluation of customer or competent authority notification requirements',
      regulatoryHook: 'ISO 13485:2016 §8.3.3; FDA 21 CFR 820.90(b); EU MDR Article 15',
      detectionMethod: 'Use-as-is disposition records audit for customer and regulatory notification evaluation documentation',
      remediationPath: 'Add notification requirement evaluation step to concession disposition procedure; require regulatory affairs review for Class II/III devices',
      estimatedCost: '$30K–$100K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '37% of concession disposition records lack documented evaluation of customer notification requirements',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M679',
    name: 'Reworked Product Not Re-Inspected Against Original Acceptance Criteria After Rework',
    description: 'NorthStar Clinical rework procedures do not consistently require re-inspection against the original specification acceptance criteria after rework is completed, allowing reworked product to proceed to finished goods without verified conformance.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['rework-reinspection', 'acceptance-criteria', 'iso-13485-8-3-4', 'fda-820-90', 'product-quality'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Rework completed without mandatory re-inspection against original acceptance criteria; nonconforming reworked product may release',
      regulatoryHook: 'ISO 13485:2016 §8.3.4; FDA 21 CFR 820.90(b); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Rework records audit checking for re-inspection result documented post-rework; compare acceptance status to original specification',
      remediationPath: 'Mandate documented re-inspection against original acceptance criteria as final rework step; add QA sign-off before return to stock',
      estimatedCost: '$25K–$90K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '43% of rework records reviewed in FDA inspections lack documented re-inspection against original acceptance criteria',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M680',
    name: 'Nonconforming Product Records Lack Traceability to Specific Lot Numbers and Device History Records',
    description: 'NorthStar Clinical nonconforming product records reference general process failures without traceability to specific lot numbers, serial numbers, or device history records, making it impossible to assess distribution scope during a field safety action.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['nonconforming-traceability', 'lot-traceability', 'dhr', 'iso-13485', 'field-safety'],
    failure_rate_pct: 56.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Nonconforming records lack lot/serial traceability; distribution scope assessment impossible during field safety action',
      regulatoryHook: 'ISO 13485:2016 §8.3.2, §7.5.9; FDA 21 CFR 820.90, 820.184; EU MDR Article 10(9)',
      detectionMethod: 'Nonconforming material records audit for presence of specific lot/serial number and DHR cross-reference',
      remediationPath: 'Mandate lot and serial number fields in nonconforming product record; link to DHR in eQMS; validate traceability chain quarterly',
      estimatedCost: '$45K–$160K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '39% of medtech nonconforming product records lack complete lot traceability to device history records',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M681',
    name: 'Nonconforming Product Trend Analysis Not Performed to Identify Systemic Process Failures',
    description: 'NorthStar Clinical reviews nonconforming products on a case-by-case basis without periodic trend analysis, missing the recurring process defect patterns that should be triggering CAPAs before they escalate to product escapes or field complaints.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['nonconforming-trends', 'capa-trigger', 'iso-13485-8-5-1', 'process-quality', 'statistical-analysis'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Nonconforming product reviewed case-by-case; trend analysis absent; systemic process failures not triggering CAPA',
      regulatoryHook: 'ISO 13485:2016 §8.3.2, §8.5.1; FDA 21 CFR 820.100(a); MDSAP Audit Approach Chapter 7',
      detectionMethod: 'Query nonconforming records for trend analysis reports; assess CAPA trigger rate from nonconforming product source',
      remediationPath: 'Implement monthly nonconforming product trend review by defect code and process step; define CAPA trigger thresholds',
      estimatedCost: '$35K–$130K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '51% of medtech quality systems lack a documented nonconforming product trend analysis feeding the CAPA system',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M682',
    name: 'Scrap Disposition Not Verified — Nonconforming Product Destroyed Without Destruction Witness Record',
    description: 'NorthStar Clinical scrap dispositions for nonconforming sterile devices are processed without a destruction witness record, creating an unverifiable gap in the nonconforming product lifecycle that could indicate product diversion.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['scrap-disposition', 'destruction-verification', 'iso-13485', 'fda-820-90', 'product-diversion'],
    failure_rate_pct: 40.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Scrap disposition for nonconforming product lacks destruction witness record; product accountability gap',
      regulatoryHook: 'ISO 13485:2016 §8.3.2; FDA 21 CFR 820.90(b); US Pharmacopeia device destruction verification guidelines',
      detectionMethod: 'Scrap disposition records audit for destruction witness signature and method documentation',
      remediationPath: 'Require witnessed destruction record with method, quantity, and two-signature attestation for all nonconforming device scrap',
      estimatedCost: '$15K–$55K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '27% of medtech scrap disposition records lack destruction witness documentation',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M683',
    name: 'Nonconforming Product Found After Distribution — Field Safety Corrective Action Evaluation Not Triggered',
    description: 'NorthStar Clinical process for discovering nonconformances in distributed product does not automatically trigger a field safety corrective action risk assessment, resulting in recall-level events being managed as quality records without regulatory notification.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['post-distribution-nonconformance', 'fsca', 'iso-13485-8-3', 'fda-820-90', 'recall'],
    failure_rate_pct: 72.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Post-distribution nonconformances processed as internal quality records without FSCA evaluation; recall risk unassessed',
      regulatoryHook: 'ISO 13485:2016 §8.3.5; FDA 21 CFR 820.90, Part 806; EU MDR Article 83, 2017/745',
      detectionMethod: 'Nonconforming product records for distributed lots; verify presence of FSCA evaluation for each post-distribution finding',
      remediationPath: 'Add mandatory FSCA evaluation step to post-distribution nonconformance workflow; require regulatory affairs review within 24 hours',
      estimatedCost: '$90K–$300K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '64% of FDA Part 806 recall enforcement actions involve nonconformances that were known but not evaluated for field safety impact',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M684',
    name: 'Nonconformance Report Closure Without Verification That Rework or Disposition Was Completed',
    description: 'NorthStar Clinical nonconformance reports are closed in the eQMS when disposition is approved rather than when disposition is verified as completed, allowing open material to remain in inventory under nominally closed NCRs.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['ncr-closure', 'disposition-verification', 'iso-13485', 'fda-820-90', 'eqms'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'NCR closed at disposition approval not disposition completion; material may remain open under closed NCR',
      regulatoryHook: 'ISO 13485:2016 §8.3.2; FDA 21 CFR 820.90; MDSAP Audit Approach Chapter 7',
      detectionMethod: 'NCR closure date vs. ERP disposition completion date comparison; identify NCRs closed before material disposition recorded',
      remediationPath: 'Modify NCR closure workflow to require disposition completion confirmation and inventory record reconciliation',
      estimatedCost: '$20K–$75K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '38% of eQMS configurations allow NCR closure before physical disposition completion is verified',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M685',
    name: 'Supplier-Caused Nonconformances Not Fed Back to Supplier Quality System',
    description: 'NorthStar Clinical records nonconformances caused by supplier material but does not systematically issue supplier corrective action requests, allowing chronic supplier quality issues to persist without formal remediation demand.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['supplier-nonconformance', 'scar', 'iso-13485-7-4', 'fda-820-50', 'supplier-quality'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Supplier-caused nonconformances not consistently converted to SCARs; supplier quality improvement cycle broken',
      regulatoryHook: 'ISO 13485:2016 §7.4.3, §8.3.2; FDA 21 CFR 820.50, 820.90; MDSAP Audit Approach Chapter 6',
      detectionMethod: 'Supplier-tagged NCR records vs. SCAR database; calculate SCAR conversion rate for supplier-origin defects',
      remediationPath: 'Define SCAR threshold criteria; automate SCAR generation for supplier-tagged NCRs exceeding threshold; track to closure',
      estimatedCost: '$35K–$120K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '46% of supplier-tagged nonconformances in medtech QMS do not result in a documented supplier corrective action request',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M686',
    name: 'Nonconforming Product Data Not Used as Input to Design Risk Management Updates',
    description: 'NorthStar Clinical design risk files are not updated when nonconforming product data reveals failure modes not previously identified in the risk management file, leaving the risk file out of sync with manufacturing reality.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['nonconforming-risk-linkage', 'iso-14971', 'risk-file', 'iso-13485', 'dfmea'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Manufacturing nonconformance data not propagated to design risk file; new failure modes unaddressed in risk management',
      regulatoryHook: 'ISO 14971:2019 §10; ISO 13485:2016 §8.3.2; FDA 21 CFR 820.30(g)',
      detectionMethod: 'Cross-reference nonconforming product failure codes against risk file hazard list; identify unmatched failure modes',
      remediationPath: 'Establish quarterly nonconforming product to risk file review; require risk manager sign-off when new failure modes identified',
      estimatedCost: '$40K–$140K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '44% of medtech risk files have not been updated to reflect failure modes identified in manufacturing nonconformance records',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M687',
    name: 'Nonconforming Product Rate KPI Absent from Quality Dashboard — Leadership Blind to Yield Trends',
    description: 'NorthStar Clinical does not track nonconforming product rate as a standing quality KPI in the management review dashboard, depriving leadership of the manufacturing quality signal needed to identify deteriorating process capability.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['ncr-kpi', 'quality-dashboard', 'management-review', 'iso-13485-5-6', 'process-capability'],
    failure_rate_pct: 42.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'nonconforming-product',
    data: {
      failureMode: 'Nonconforming product rate absent from quality KPI dashboard; leadership blind to manufacturing yield trend deterioration',
      regulatoryHook: 'ISO 13485:2016 §5.6.2; MDSAP Audit Approach Chapter 2; FDA 21 CFR 820.20(c)',
      detectionMethod: 'Management review minutes audit for NCR rate KPI over 24-month period',
      remediationPath: 'Add nonconforming product rate by product family and process step as mandatory management review KPI; set alert thresholds',
      estimatedCost: '$15K–$55K',
      timeToRemediate: '1–2 months',
      industryBenchmark: '35% of ISO 13485-certified manufacturers omit nonconforming product rate from management review quality KPI sets',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

  // ── MDSAP Audit Readiness (M688–M699) ─────────────────────────────────────

  {
    code: 'M688',
    name: 'MDSAP Audit Approach Gap — Management Responsibility Chapter 2 Evidence Insufficient',
    description: 'NorthStar Clinical MDSAP readiness assessment reveals insufficient objective evidence for Chapter 2 management responsibility tasks including quality policy deployment, resource adequacy decisions, and management review output records.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-chapter2', 'management-responsibility', 'audit-readiness', 'iso-13485', 'quality-policy'],
    failure_rate_pct: 65.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP audit approach gaps — Chapter 2 management responsibility evidence insufficient for auditor review',
      regulatoryHook: 'MDSAP Audit Approach Chapter 2; ISO 13485:2016 §5; FDA 21 CFR 820.20; Health Canada CMDR',
      detectionMethod: 'MDSAP Chapter 2 pre-audit gap assessment against published task list using objective evidence checklist',
      remediationPath: 'Conduct MDSAP Chapter 2 mock audit; remediate evidence gaps; document quality policy deployment records before audit',
      estimatedCost: '$60K–$200K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '58% of first-time MDSAP auditees receive a Grade 3 or higher on Chapter 2 management responsibility tasks',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M689',
    name: 'MDSAP Chapter 6 Purchasing Controls Evidence Gap — Supplier Evaluation Records Incomplete',
    description: 'NorthStar Clinical MDSAP readiness review identifies incomplete supplier evaluation and re-evaluation records required for Chapter 6 purchasing controls, with approved supplier list missing risk classification and evaluation frequency documentation.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-chapter6', 'purchasing-controls', 'supplier-evaluation', 'audit-readiness', 'iso-13485-7-4'],
    failure_rate_pct: 62.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP Chapter 6 purchasing controls gap — supplier evaluation records and risk classification documentation incomplete',
      regulatoryHook: 'MDSAP Audit Approach Chapter 6; ISO 13485:2016 §7.4.1; FDA 21 CFR 820.50; Health Canada CMDR',
      detectionMethod: 'Approved supplier list audit against Chapter 6 task requirements; gap analysis for risk classification and evaluation records',
      remediationPath: 'Complete supplier risk classification for all approved suppliers; update evaluation records; document re-evaluation schedule',
      estimatedCost: '$50K–$170K',
      timeToRemediate: '3–5 months',
      industryBenchmark: '54% of MDSAP audits identify Chapter 6 purchasing controls as a nonconformity source in the first audit cycle',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M690',
    name: 'MDSAP Grading Misunderstood — Grade 3 Nonconformity Treated as Minor When It Requires 30-Day Response',
    description: 'NorthStar Clinical quality team is not aware that MDSAP Grade 3 nonconformities require a 30-day corrective action response submitted to all participating regulatory authorities, treating Grade 3 findings with the same response urgency as Grade 2.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-grading', 'grade-3', 'corrective-action-response', 'audit-readiness', 'regulatory-authorities'],
    failure_rate_pct: 57.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP audit approach gaps — Grade 3 grading and 30-day multi-authority response requirement not understood by QA team',
      regulatoryHook: 'MDSAP Audit Approach grading model; FDA MDSAP participation requirements; Health Canada MDSAP guidance',
      detectionMethod: 'QA team knowledge assessment on MDSAP grading model and corrective action response timelines by grade',
      remediationPath: 'Conduct MDSAP grading model training for QA leadership; develop response templates for Grade 3 and Grade 4 scenarios',
      estimatedCost: '$20K–$75K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '43% of MDSAP first-time auditees misclassify their internal response urgency for Grade 3 nonconformities',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M691',
    name: 'MDSAP Audit Approach Chapter 5 Device Realisation Evidence Gap — Design Control Records Incomplete',
    description: 'NorthStar Clinical design control records required for MDSAP Chapter 5 device realisation tasks are scattered across multiple systems without an integrated design history file, making evidence assembly for MDSAP auditors time-consuming and incomplete.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-chapter5', 'design-controls', 'dhf', 'audit-readiness', 'iso-13485-7-3'],
    failure_rate_pct: 60.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP Chapter 5 device realisation gap — design history file fragmented; evidence assembly for auditors difficult',
      regulatoryHook: 'MDSAP Audit Approach Chapter 5; ISO 13485:2016 §7.3; FDA 21 CFR 820.30; Health Canada CMDR',
      detectionMethod: 'Design history file completeness audit against MDSAP Chapter 5 task list for each design phase',
      remediationPath: 'Consolidate design history file into single system of record; index records against MDSAP Chapter 5 tasks; conduct pre-audit review',
      estimatedCost: '$70K–$230K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '55% of MDSAP Chapter 5 nonconformities relate to fragmented or incomplete design control records',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M692',
    name: 'MDSAP Multi-Jurisdictional Regulatory Requirements Not Mapped to QMS Procedures',
    description: 'NorthStar Clinical QMS procedures reference ISO 13485 and FDA 21 CFR Part 820 but do not explicitly map to Health Canada CMDR, ANVISA RDC 16, or TGA requirements, creating jurisdictional compliance gaps visible during MDSAP multi-authority review.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-multi-jurisdiction', 'cmdr', 'anvisa', 'tga', 'audit-readiness'],
    failure_rate_pct: 64.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'QMS procedures not mapped to all MDSAP-participating jurisdictions; Health Canada CMDR and ANVISA gaps identified',
      regulatoryHook: 'MDSAP Audit Approach; Health Canada CMDR SOR/98-282; ANVISA RDC 16/2013; TGA therapeutic goods requirements',
      detectionMethod: 'QMS procedure regulatory reference audit against all MDSAP-participating jurisdictions\' requirements',
      remediationPath: 'Conduct multi-jurisdictional gap analysis; add jurisdiction-specific requirements to relevant SOPs; document compliance matrix',
      estimatedCost: '$80K–$270K',
      timeToRemediate: '4–8 months',
      industryBenchmark: '61% of MDSAP initial audits identify at least one jurisdiction-specific requirement not addressed in QMS procedures',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M693',
    name: 'MDSAP Audit Approach Chapter 4 Measurement Analysis Improvement Gap — Statistical Tools Not Applied',
    description: 'NorthStar Clinical measurement analysis and improvement activities required for MDSAP Chapter 4 do not employ appropriate statistical tools for process monitoring, with control chart and capability analysis conspicuously absent from quality records.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-chapter4', 'statistical-tools', 'process-capability', 'audit-readiness', 'iso-13485-8-1'],
    failure_rate_pct: 55.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP Chapter 4 gap — statistical analysis methods absent; process capability and control chart evidence not available',
      regulatoryHook: 'MDSAP Audit Approach Chapter 4; ISO 13485:2016 §8.1; FDA 21 CFR 820.250; ISO 21748',
      detectionMethod: 'Quality records audit for statistical process control evidence; assess measurement system analysis documentation',
      remediationPath: 'Implement SPC for key process parameters; document capability studies; include statistical evidence in MDSAP audit package',
      estimatedCost: '$55K–$180K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '47% of MDSAP Chapter 4 findings relate to absence of appropriate statistical methods in measurement and analysis activities',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M694',
    name: 'MDSAP Mock Audit Not Conducted Within 12 Months of Initial Certification Audit',
    description: 'NorthStar Clinical has not conducted an internal MDSAP mock audit within 12 months of the scheduled certification audit, reducing the organisation\'s ability to identify evidence gaps and prepare witnesses for the structured task-based audit approach.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-mock-audit', 'audit-readiness', 'certification-prep', 'iso-13485', 'pre-audit'],
    failure_rate_pct: 58.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP mock audit not conducted; organisation unprepared for task-based audit approach; witness readiness unknown',
      regulatoryHook: 'MDSAP Audit Approach (general); ISO 13485:2016 §8.2.4; FDA MDSAP participation FAQ',
      detectionMethod: 'Audit programme records review for MDSAP-format mock audit within 12 months of certification audit date',
      remediationPath: 'Schedule MDSAP mock audit 6 months before certification; conduct witness preparation workshops; remediate gaps before actual audit',
      estimatedCost: '$40K–$140K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '52% of MDSAP first-time auditees did not conduct a structured mock audit in the preceding 12 months',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M695',
    name: 'MDSAP Audit Approach Chapter 3 Resource Management Evidence Incomplete',
    description: 'NorthStar Clinical resource management evidence for MDSAP Chapter 3 is incomplete, with infrastructure maintenance records, work environment monitoring data, and competency records not consolidated for auditor review.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-chapter3', 'resource-management', 'competency-records', 'infrastructure', 'audit-readiness'],
    failure_rate_pct: 50.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP Chapter 3 resource management evidence not consolidated; infrastructure and competency records fragmented across systems',
      regulatoryHook: 'MDSAP Audit Approach Chapter 3; ISO 13485:2016 §6; FDA 21 CFR 820.25, 820.70',
      detectionMethod: 'MDSAP Chapter 3 pre-audit evidence assembly exercise; identify systems and record locations for each task',
      remediationPath: 'Consolidate Chapter 3 evidence into MDSAP audit binder; reconcile infrastructure maintenance and competency records',
      estimatedCost: '$30K–$100K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '41% of MDSAP Chapter 3 findings relate to inability to locate or produce competency and infrastructure records during audit',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M696',
    name: 'MDSAP Audit Approach Chapter 7 Corrective Action Response Not Structured to Auditor Grade Requirements',
    description: 'NorthStar Clinical corrective action responses submitted after MDSAP Chapter 7 nonconformities do not follow the structured format expected by the MDSAP grading model, resulting in auditor requests for resubmission and delayed audit closure.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-chapter7', 'corrective-action-response', 'audit-closure', 'grading-model', 'audit-readiness'],
    failure_rate_pct: 53.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP corrective action responses unstructured; do not address root cause, containment, and systemic prevention in required format',
      regulatoryHook: 'MDSAP Audit Approach Chapter 7 corrective action requirements; MDSAP grading model; ISO 13485:2016 §8.5.2',
      detectionMethod: 'Previous MDSAP corrective action response review against MDSAP response format requirements',
      remediationPath: 'Develop MDSAP-specific corrective action response template; train QA team on grading model response structure; conduct response drafting exercises',
      estimatedCost: '$25K–$85K',
      timeToRemediate: '1–3 months',
      industryBenchmark: '46% of MDSAP corrective action responses require at least one resubmission due to format or content deficiencies',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI-drafted MDSAP corrective action responses may miss jurisdiction-specific evidence requirements if not trained on current MDSAP grading guidance',
    },
  },
  {
    code: 'M697',
    name: 'MDSAP Participating Jurisdiction Regulatory Changes Not Monitored for QMS Impact',
    description: 'NorthStar Clinical has no systematic process for monitoring regulatory changes from MDSAP-participating jurisdictions (FDA, Health Canada, ANVISA, TGA, PMDA) and assessing their impact on QMS procedures and product compliance.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['regulatory-monitoring', 'mdsap-jurisdictions', 'pmda', 'health-canada', 'audit-readiness'],
    failure_rate_pct: 61.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'No systematic regulatory change monitoring for MDSAP jurisdictions; QMS changes lag regulatory updates',
      regulatoryHook: 'MDSAP Audit Approach; FDA 21 CFR 820; Health Canada CMDR; ANVISA RDC 16; TGA TGO; PMDA QMSME',
      detectionMethod: 'Regulatory affairs process audit for jurisdiction monitoring subscriptions and impact assessment records over 24 months',
      remediationPath: 'Establish regulatory change monitoring programme for all 5 MDSAP jurisdictions; assign owners; define QMS impact assessment trigger',
      estimatedCost: '$45K–$150K',
      timeToRemediate: '2–4 months',
      industryBenchmark: '55% of MDSAP-certified sites have no formal programme for monitoring regulatory changes across all five participating jurisdictions',
      aiInsertionRisk: true,
      aiRiskDescription: 'AI regulatory monitoring tools may not capture jurisdiction-specific guidance documents or provide timely alerts for MDSAP-relevant changes',
    },
  },
  {
    code: 'M698',
    name: 'MDSAP Audit Readiness Documentation Package Not Assembled — Evidence Fragmented Across Systems',
    description: 'NorthStar Clinical has not assembled an MDSAP audit readiness documentation package, meaning objective evidence for all seven audit approach chapters is dispersed across eQMS, ERP, LMS, and shared drives without an index or document control framework for auditor access.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-documentation-package', 'audit-readiness', 'evidence-assembly', 'eqms', 'audit-preparation'],
    failure_rate_pct: 67.0,
    is_active: true,
    demoRelevant: true,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP audit readiness package absent; evidence fragmented; auditor review time wasted on document retrieval',
      regulatoryHook: 'MDSAP Audit Approach (all chapters); ISO 13485:2016 §4.2; FDA 21 CFR 820.180',
      detectionMethod: 'Pre-audit simulation requiring all chapter evidence to be produced within 30 minutes; measure gaps and retrieval time',
      remediationPath: 'Assemble chapter-indexed MDSAP audit binder; validate completeness against chapter task lists; update quarterly',
      estimatedCost: '$50K–$170K',
      timeToRemediate: '3–6 months',
      industryBenchmark: '63% of first-time MDSAP auditees experience significant audit time lost to document retrieval and evidence assembly',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },
  {
    code: 'M699',
    name: 'MDSAP Surveillance Audit Preparation Not Included in Annual Quality Plan',
    description: 'NorthStar Clinical annual quality plan does not include dedicated MDSAP surveillance audit preparation activities, meaning pre-audit gap assessments, mock audits, and evidence updates are not resourced or scheduled until weeks before the audit.',
    vertical: 'medtech',
    office_category: 'Quality Management',
    keywords: ['mdsap-surveillance', 'annual-quality-plan', 'audit-preparation', 'iso-13485', 'resource-planning'],
    failure_rate_pct: 54.0,
    is_active: true,
    demoRelevant: false,
    subTopic: 'mdsap-audit-readiness',
    data: {
      failureMode: 'MDSAP surveillance audit preparation absent from annual quality plan; readiness activities reactive and under-resourced',
      regulatoryHook: 'MDSAP Audit Approach surveillance requirements; ISO 13485:2016 §5.4.2, §8.2.4; FDA MDSAP participation terms',
      detectionMethod: 'Annual quality plan review for MDSAP surveillance preparation milestones and resource allocations',
      remediationPath: 'Embed MDSAP surveillance preparation timeline into annual quality plan starting 6 months before audit; assign preparation owner',
      estimatedCost: '$30K–$100K',
      timeToRemediate: '2–3 months',
      industryBenchmark: '48% of MDSAP-certified companies do not formally plan surveillance audit preparation activities in their annual quality schedule',
      aiInsertionRisk: false,
      aiRiskDescription: '',
    },
  },

];
