/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 79: Rural Health & Access Innovation AI
// Part 3: H19700-H19749
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM79_PART3_PATTERNS = [
  {
    code: 'H19700',
    name: 'Rural Health Quality Abstraction Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for quality abstraction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'deployment-site validation', 'HITRUST roadmap', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19701',
    name: 'Telehealth Patient Outreach Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for patient outreach but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'MLOps monitoring', 'Series B burn rate', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19702',
    name: 'Provider Shortage Triage Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for triage but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'clinical safety review', 'implementation partner capacity', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19703',
    name: 'CAH Drafting Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 54,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for drafting but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'procurement RFP scoring', 'referenceable health-system customer', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19704',
    name: 'Broadband Summarization Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for summarization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'BAFO contract clause', 'clinical advisory board', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19705',
    name: 'Rural Health Risk Scoring Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for risk scoring but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'HIPAA BAA', 'FDA submission posture', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19706',
    name: 'Telehealth Worklist Prioritization Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for worklist prioritization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'minimum necessary policy', 'KLAS commentary', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19707',
    name: 'Provider Shortage Appeal Generation Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 75,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for appeal generation but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'TJC survey evidence', 'Epic App Orchard integration', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19708',
    name: 'CAH Order Recommendation Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for order recommendation but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'CMS CoP', 'Microsoft Cloud for Healthcare', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19709',
    name: 'Broadband Benefit Verification Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for benefit verification but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'NCQA HEDIS audit', 'AWS HealthLake', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19710',
    name: 'Rural Health Eligibility Prediction Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for eligibility prediction but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'FDA SaMD guidance', 'Azure Health Data Services', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19711',
    name: 'Telehealth Care Gap Closure Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 53,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for care gap closure but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'NIST AI RMF', 'Snowflake Healthcare', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19712',
    name: 'Provider Shortage Cohort Matching Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for cohort matching but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'ONC HTI-1', 'Databricks Lakehouse', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19713',
    name: 'CAH Contract Analysis Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for contract analysis but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'TEFCA participation', 'ServiceNow workflow', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19714',
    name: 'Broadband Agentic Orchestration Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 57,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for agentic orchestration but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'FHIR R4 mapping', 'Salesforce Health Cloud', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19715',
    name: 'Rural Health Coding Suggestion Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for coding suggestion but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'HL7 v2 ADT reconciliation', 'startup maturity evidence', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19716',
    name: 'Telehealth Documentation Review Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for documentation review but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'Epic change control', 'SOC 2 Type II', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19717',
    name: 'Provider Shortage Vendor Comparison Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for vendor comparison but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'model registry', 'HITRUST roadmap', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19718',
    name: 'CAH Capacity Forecasting Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 80,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for capacity forecasting but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'deployment-site validation', 'Series B burn rate', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19719',
    name: 'Broadband Staffing Optimization Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for staffing optimization but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'MLOps monitoring', 'implementation partner capacity', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19720',
    name: 'Rural Health Quality Abstraction Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for quality abstraction but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'clinical safety review', 'referenceable health-system customer', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19721',
    name: 'Telehealth Patient Outreach Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for patient outreach but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'procurement RFP scoring', 'clinical advisory board', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19722',
    name: 'Provider Shortage Triage Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for triage but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'BAFO contract clause', 'FDA submission posture', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19723',
    name: 'CAH Drafting Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for drafting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'HIPAA BAA', 'KLAS commentary', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19724',
    name: 'Broadband Summarization Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for summarization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'minimum necessary policy', 'Epic App Orchard integration', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19725',
    name: 'Rural Health Risk Scoring Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for risk scoring but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'TJC survey evidence', 'Microsoft Cloud for Healthcare', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19726',
    name: 'Telehealth Worklist Prioritization Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for worklist prioritization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'CMS CoP', 'AWS HealthLake', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19727',
    name: 'Provider Shortage Appeal Generation Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 79,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for appeal generation but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'NCQA HEDIS audit', 'Azure Health Data Services', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19728',
    name: 'CAH Order Recommendation Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 59,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for order recommendation but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'FDA SaMD guidance', 'Snowflake Healthcare', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19729',
    name: 'Broadband Benefit Verification Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for benefit verification but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'NIST AI RMF', 'Databricks Lakehouse', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19730',
    name: 'Rural Health Eligibility Prediction Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 80,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for eligibility prediction but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'ONC HTI-1', 'ServiceNow workflow', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19731',
    name: 'Telehealth Care Gap Closure Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for care gap closure but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'TEFCA participation', 'Salesforce Health Cloud', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19732',
    name: 'Provider Shortage Cohort Matching Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for cohort matching but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'FHIR R4 mapping', 'startup maturity evidence', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19733',
    name: 'CAH Contract Analysis Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for contract analysis but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'HL7 v2 ADT reconciliation', 'SOC 2 Type II', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19734',
    name: 'Broadband Agentic Orchestration Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for agentic orchestration but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is Epic change control: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'Epic change control', 'HITRUST roadmap', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19735',
    name: 'Rural Health Coding Suggestion Adoption Telemetry Missing',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for coding suggestion but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is model registry: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'model registry', 'Series B burn rate', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19736',
    name: 'Telehealth Documentation Review Human Override Ambiguity',
    officeCategory: 'front_office',
    failureRatePct: 72,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for documentation review but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'deployment-site validation', 'implementation partner capacity', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19737',
    name: 'Provider Shortage Vendor Comparison Integration Surface Fragmentation',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for vendor comparison but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'MLOps monitoring', 'referenceable health-system customer', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19738',
    name: 'CAH Capacity Forecasting Liability Handoff Gap',
    officeCategory: 'front_office',
    failureRatePct: 55,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for capacity forecasting but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is clinical safety review: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'clinical safety review', 'clinical advisory board', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19739',
    name: 'Broadband Staffing Optimization Equity Guardrail Drift',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for staffing optimization but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'procurement RFP scoring', 'FDA submission posture', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19740',
    name: 'Rural Health Quality Abstraction Value Ledger Overstatement',
    officeCategory: 'front_office',
    failureRatePct: 82,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for quality abstraction but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'BAFO contract clause', 'KLAS commentary', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19741',
    name: 'Telehealth Patient Outreach Agent Tool Boundary Failure',
    officeCategory: 'front_office',
    failureRatePct: 61,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for patient outreach but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves value realization ledger and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'HIPAA BAA', 'Epic App Orchard integration', 'value realization ledger', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19742',
    name: 'Provider Shortage Triage Startup Roadmap Dependency',
    officeCategory: 'front_office',
    failureRatePct: 54,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for triage but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves pilot success metric and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'minimum necessary policy', 'Microsoft Cloud for Healthcare', 'pilot success metric', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19743',
    name: 'CAH Drafting Alert Fatigue Inflection',
    officeCategory: 'front_office',
    failureRatePct: 84,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for drafting but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves clinical governance checklist and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'TJC survey evidence', 'AWS HealthLake', 'clinical governance checklist', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19744',
    name: 'Broadband Summarization Revenue Integrity Leakage',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for summarization but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is CMS CoP: AbarVa should turn this into a Moves adoption plan and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'CMS CoP', 'Azure Health Data Services', 'adoption plan', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19745',
    name: 'Rural Health Risk Scoring Audit Evidence Thinness',
    officeCategory: 'front_office',
    failureRatePct: 54,
    description: `Rural Health & Access Innovation AI initiatives fail when rural health is used for risk scoring but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pre-mortem risk and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when provider shortage is not proven in production.`,
    keywords: ['rural health', 'provider shortage', 'NCQA HEDIS audit', 'Snowflake Healthcare', 'pre-mortem risk', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19746',
    name: 'Telehealth Worklist Prioritization Criteria Drift',
    officeCategory: 'front_office',
    failureRatePct: 78,
    description: `Rural Health & Access Innovation AI initiatives fail when telehealth is used for worklist prioritization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves dependency map and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when CAH is not proven in production.`,
    keywords: ['telehealth', 'CAH', 'FDA SaMD guidance', 'Databricks Lakehouse', 'dependency map', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19747',
    name: 'Provider Shortage Appeal Generation Workflow Authority Gap',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `Rural Health & Access Innovation AI initiatives fail when provider shortage is used for appeal generation but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves approval gate and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when broadband is not proven in production.`,
    keywords: ['provider shortage', 'broadband', 'NIST AI RMF', 'ServiceNow workflow', 'approval gate', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19748',
    name: 'CAH Order Recommendation Subprocessor Blind Spot',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `Rural Health & Access Innovation AI initiatives fail when CAH is used for order recommendation but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves benefit validation plan and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when rural health is not proven in production.`,
    keywords: ['CAH', 'rural health', 'ONC HTI-1', 'Salesforce Health Cloud', 'benefit validation plan', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Rural Health & Access Innovation AI',
  },
  {
    code: 'H19749',
    name: 'Broadband Benefit Verification Validation Cohort Mismatch',
    officeCategory: 'front_office',
    failureRatePct: 73,
    description: `Rural Health & Access Innovation AI initiatives fail when broadband is used for benefit verification but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when telehealth is not proven in production.`,
    keywords: ['broadband', 'telehealth', 'TEFCA participation', 'startup maturity evidence', 'unsafe-to-fund gate', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Rural Health & Access Innovation AI',
  }
];
