// seed-medtech-dom11-sales-hcp-part3.ts
// Medtech genome patterns — Sales & HCP Engagement (dom11)
// Code range: M1720–M1779  (60 patterns)
// Sub-topics: ai-hcp-engagement, physician-payment-transparency,
//             off-label-promotion-prevention, medical-education-compliance,
//             distribution-channel-compliance
// Loaded by: scripts/corpus/load-authored-genome-seeds.ts

type OfficeCategory = 'front_office' | 'middle_office' | 'back_office';

interface PatternSeed {
  code: string;
  name: string;
  officeCategory: OfficeCategory;
  failureRatePct: number;
  description: string;
  keywords: string[];
  demoRelevant?: boolean;
  subTopic?: string;
  aiInsertionRisk?: boolean;
}

export const MEDTECH_DOM11_SALES_HCP_PART3_PATTERNS: PatternSeed[] = [

  // ── AI HCP Engagement (M1720–M1737) ──────────────────────────────────────

  {
    code: 'M1720',
    name: 'GenAI Promotional Content Without Regulatory Review Flagged',
    officeCategory: 'front_office',
    failureRatePct: 74,
    description: `A generative AI platform deployed to accelerate HCP promotional content creation produces device claim language, clinical outcome assertions, and comparative efficacy statements without routing outputs through the medical-legal-regulatory review process required by 21 CFR Part 801 and FDA guidance on promotional labeling — causing field-deployed promotional assets to contain unsubstantiated claims and indication-broadening language that downstream MLR review would have rejected. The AI content pipeline's governance gap is structural: the tool integrates directly with the content management system and publishes to sales portals without a mandatory MLR checkpoint, meaning that the review process can only catch violations post-deployment when content has already been distributed to the sales force and potentially shared with HCPs.`,
    keywords: ['GenAI promotional content', 'FDA 21 CFR Part 801', 'MLR review', 'AdvaMed Code', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1721',
    name: 'LLM HCP Targeting Encodes Protected Characteristic Bias',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `A large language model deployed to score and rank HCPs for prioritised sales targeting infers specialty-level proxy variables — patient population demographics, geographic practice setting, and payor mix — that correlate with protected characteristics under civil rights statutes, causing the AI targeting model to systematically under-rank HCPs serving minority and underserved patient populations relative to HCPs serving commercially insured, higher-income patient segments. The protected characteristic proxy bias violates the AdvaMed Code's nondiscrimination principles and creates exposure under Section 1557 of the Affordable Care Act when the targeting model's output affects which patient populations receive early access to new device technologies — and an AI fairness audit that the company commissions post-deployment identifies the proxy bias through counterfactual analysis of targeting scores across practice demographic dimensions.`,
    keywords: ['GenAI HCP targeting', 'algorithmic bias', 'AdvaMed Code', 'AI fairness', 'HCP engagement'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1722',
    name: 'LLM Medical Affairs Query Response Bypasses MSL Scientific Review',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `An LLM-powered HCP inquiry response system deployed on the company's medical information portal generates scientific responses to HCP clinical questions — including questions about off-label applications, clinical study design, and adverse event management — without routing responses through Medical Science Liaison review or the medical information call centre's quality control process, producing AI-generated scientific communications that have not been verified for accuracy, completeness, or compliance with FDA guidance on responding to HCP unsolicited requests. The MSL bypass creates a scientific communication liability when the LLM generates plausible-sounding but factually inaccurate clinical guidance — a failure mode that is particularly dangerous for complex questions about device performance in non-cleared indications where MSL expertise is precisely the safeguard that AI cannot substitute.`,
    keywords: ['LLM medical affairs', 'MSL review', 'FDA medical information guidance', 'HCP scientific exchange', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1723',
    name: 'AI Sales Coaching Tool Lacks Off-Label Communication Guardrails',
    officeCategory: 'front_office',
    failureRatePct: 72,
    description: `An AI-powered sales coaching platform that analyses representative call recordings and provides real-time prompting guidance during HCP interactions suggests clinical talking points, question responses, and competitive comparison language without filtering for cleared indication boundaries — coaching representatives to elaborate on clinical applications, patient populations, and procedural scenarios that are outside the device's 510(k)-cleared indications in response to HCP questions. The real-time coaching AI's off-label boundary gap is a compounding risk multiplier: it operates at scale across all AI-coached sales calls simultaneously, meaning that a single failure in the coaching model's indication boundary logic propagates across the entire field force rather than being limited to individual representative training gaps that targeted coaching would address.`,
    keywords: ['AI sales coaching', 'FDA 21 CFR Part 801', 'off-label promotion', 'sales training', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1724',
    name: 'ML Speaker ROI Prediction Ignores Sunshine Act Prescription Correlation',
    officeCategory: 'middle_office',
    failureRatePct: 68,
    description: `A machine learning model that predicts speaker program return-on-investment uses post-program device adoption metrics as the primary target variable — training the model to identify speaker bureau participants whose programs produce measurable prescription volume increases — operationalising the prescription-ROI relationship that the OIG characterises as the defining indicator of an unlawful remuneration arrangement rather than a legitimate educational program. The ML speaker ROI model encodes the quid-pro-quo correlation between speaker bureau participation and device adoption at the ML architecture level, producing a commercial speaker selection system whose AI decision logic would be directly cited in an OIG investigation as evidence that the speaker program's primary purpose was remuneration rather than education — a structural compliance failure that cannot be remediated by adding compliance disclosures to the program.`,
    keywords: ['ML speaker program', 'Anti-Kickback Statute', 'Sunshine Act', 'OIG compliance guidance', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1725',
    name: 'GenAI HCP Email Personalisation Creates Unreviewed Promotional Claims',
    officeCategory: 'front_office',
    failureRatePct: 76,
    description: `A generative AI email personalisation platform that customises HCP outreach by incorporating the physician's specialty, clinical focus area, and recent publication activity generates personalised clinical context paragraphs that reference device performance in the HCP's specific patient population — producing individually tailored promotional claims that have not been reviewed by the MLR process and that may assert clinical performance in patient populations outside the device's cleared indications. The AI personalisation engine's compliance gap is that the volume of individually generated emails — thousands per day across the sales force — makes MLR review of each communication infeasible, and a sampling-based review approach that audits 5% of AI-generated emails has insufficient coverage to identify systematic off-label personalisation patterns that affect specific HCP specialty segments.`,
    keywords: ['GenAI email', 'FDA 21 CFR Part 801', 'MLR review', 'AdvaMed Code', 'off-label promotion'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1726',
    name: 'AI CRM Opportunity Scoring Drives Compliance-Uninformed Call Prioritisation',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `An AI opportunity scoring model integrated into the CRM system ranks HCPs for proactive outreach based on predicted adoption propensity — incorporating historical device utilisation, conference attendance, and competitor product usage — without integrating the company's compliance-required call documentation, training status, or exclusion list checks into the scoring model, resulting in the sales force prioritising AI-scored high-value physicians who have unresolved compliance flags or who have exceeded aggregate spending thresholds that trigger enhanced review requirements. The AI scoring system's compliance data integration gap means that commercial decisions driven by the AI opportunity score operate independently of the compliance controls that are supposed to govern which HCPs the sales force can prioritise — creating a two-system problem in which AI drives commercial activity and compliance controls operate reactively rather than as a pre-approval gate.`,
    keywords: ['AI CRM scoring', 'HCP engagement', 'AdvaMed Code', 'OIG compliance guidance', 'sales force compliance'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1727',
    name: 'LLM-Generated MSL Field Briefings Contain Pre-Publication Data',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `An LLM knowledge synthesis tool deployed to generate MSL field briefings draws on an internal document corpus that includes unpublished clinical study reports and investigational device performance data — producing MSL briefing documents that reference clinical performance figures from studies that have not been published or FDA-reviewed, creating scientific exchange materials that contain pre-publication data the MSL would not be permitted to proactively share with HCPs under FDA's guidance on the dissemination of scientific information. The pre-publication data contamination is invisible to MSLs who receive AI-generated briefings without metadata indicating the publication status of the underlying sources, meaning MSLs share scientifically detailed briefings in good faith without recognising that specific performance figures are derived from data that has not cleared the publication and regulatory review pathway required for use in HCP scientific exchange.`,
    keywords: ['LLM medical affairs', 'pre-publication data', 'FDA scientific exchange', 'MSL field briefing', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1728',
    name: 'AI Chatbot HCP Portal Lacks Regulated Medical Device Communication Disclosures',
    officeCategory: 'front_office',
    failureRatePct: 70,
    description: `An AI chatbot deployed on the company's HCP-facing product portal responds to clinical questions about device use, troubleshooting, and patient management without including the required promotional labeling disclosures — intended use statement, indications, contraindications, and risk information — that FDA requires for promotional communications about prescription medical devices, even when the chatbot's responses constitute promotional communications by describing device clinical benefits in response to HCP inquiries. The chatbot's promotional labeling gap is compounded by conversational AI's format: unlike static promotional materials where disclosures are routinely appended, conversational responses are formatted as natural dialogue and the system's response generation does not include a disclosure injection mechanism that appends required risk information to responses that constitute promotional claims.`,
    keywords: ['AI chatbot', 'FDA promotional labeling', 'FDA 21 CFR Part 801', 'HCP engagement', 'MLR review'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1729',
    name: 'ML Next-Best-Action Recommendations Lack Fair Market Value Validation',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `A machine learning next-best-action recommendation engine that suggests HCP engagement activities — advisory board invitations, consulting arrangements, speaker bureau placement, and educational event invitations — optimises engagement intensity for high-prescribing HCPs without integrating fair market value thresholds or aggregate spending limits that prevent the AI from recommending engagement patterns whose cumulative value would exceed the compensation levels justified by the HCP's independent scientific expertise. The ML recommendation system's fair market value gap operationalises remuneration optimisation for the company's highest-prescribing physicians at the AI architecture level — recommending maximum engagement activity for maximum prescribers — producing exactly the commercial-engagement correlation that Anti-Kickback Statute compliance frameworks are designed to prevent.`,
    keywords: ['ML next-best-action', 'Anti-Kickback Statute', 'fair market value', 'OIG compliance guidance', 'HCP engagement'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1730',
    name: 'AI Sentiment Analysis of HCP Calls Processes PHI Without BAA',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `An AI sentiment and conversation analytics platform that analyses recorded sales representative and MSL calls to extract HCP engagement quality metrics processes audio recordings containing protected health information — shared by HCPs when describing specific patient cases during clinical consultations — without a HIPAA Business Associate Agreement with the analytics vendor or a data governance policy restricting PHI extracted from call recordings to the compliance and training purposes for which the recordings were made. The call analytics AI creates dual HIPAA exposure because both the initial recording and the AI vendor's processing constitute disclosures of PHI to third parties: the representative's recording requires appropriate notice, and the AI analytics vendor's processing requires a BAA that covers the company's analytics use case — neither of which the commercial analytics deployment addressed before go-live.`,
    keywords: ['AI call analytics', 'HIPAA', 'PHI', 'Business Associate Agreement', 'AI commercial compliance'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1731',
    name: 'GenAI Congress Summary Tool Generates Unsubstantiated Comparative Claims',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `A generative AI tool that synthesises post-congress briefings from session summaries, abstract databases, and poster presentations creates competitive intelligence summaries for the sales force that selectively emphasise unfavourable competitor data while minimising comparable data for the company's device — producing AI-generated comparative content that constitutes unsubstantiated promotional comparisons without the medical affairs substantiation review required by FDA guidance on comparative advertising. Congress briefings distributed to field sales teams for use in HCP conversations are promotional communications when they contain clinical performance comparisons, and AI-generated briefings that encode commercial synthesis biases create a systematic source of comparative claims that the sales force deploys without recognising they have not been substantiated against the evidentiary standard FDA applies to comparative promotional materials.`,
    keywords: ['GenAI congress summary', 'FDA comparative advertising', 'AdvaMed Code', 'MLR review', 'off-label promotion'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1732',
    name: 'AI Contract Negotiation Tool Generates Below-FMV Terms Without AKS Review',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `An LLM contract assistant deployed to support GPO and IDN contract negotiations generates pricing concession options, service bundle recommendations, and discount level suggestions based on competitive intelligence and historical contract data without integrating the company's Anti-Kickback Statute fair market value guardrails — producing AI-recommended contract terms that include pricing structures and service bundles that do not reflect fair market value and that the compliance review process would reject if submitted through the standard contract approval workflow. The LLM contract assistant creates a compliance bypass risk at the contract negotiation stage — before compliance review — because commercial negotiators receive AI-generated term sheets that prime the negotiation within ranges that the AI optimised for competitive win rate rather than AKS compliance, and the subsequent compliance review must reject negotiated terms rather than preventing non-compliant negotiations from occurring.`,
    keywords: ['LLM contract negotiation', 'Anti-Kickback Statute', 'fair market value', 'GPO contract', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1733',
    name: 'AI Physician Segmentation Uses Unconsented Data for Commercial Targeting',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `An AI physician segmentation and targeting model that uses prescription claims data, specialty registry information, and digital engagement signals purchased from commercial data vendors does not verify that the underlying physician data was collected with consent for commercial targeting use — and several state medical practice acts and emerging physician data protection legislation require that physician data used for commercial targeting be collected with express consent or subject to an opt-out mechanism the AI targeting system does not provide. The physician data consent gap parallels the emerging consumer data rights landscape and is being enforced with increasing frequency by state medical boards and attorneys general receiving complaints from physicians targeted by device companies using data aggregation practices the physicians did not consent to when enrolling in specialty registries.`,
    keywords: ['AI physician segmentation', 'physician data consent', 'state privacy law', 'HCP targeting', 'AI commercial compliance'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1734',
    name: 'LLM Training on HCP Call Records Creates PHI Privacy Violation',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `An LLM fine-tuned on historical HCP consultation call records from the medical information call centre — to improve scientific response quality — was trained on records that were not de-identified before use as training data, creating a HIPAA violation when the training corpus included call records documenting HCP questions about specific patient cases with patient identifiers embedded in the clinical question. The use of identifiable HCP call records as LLM training data is a HIPAA Privacy Rule violation under 45 CFR §164.502 regardless of whether the resulting model output reveals identifiable information, because the training data use itself constitutes a disclosure of PHI to the AI vendor's model training infrastructure without the required authorisation or Business Associate Agreement covering the training use.`,
    keywords: ['LLM training data', 'HIPAA', 'PHI', 'privacy legal review', 'AI commercial compliance'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1735',
    name: 'AI Marketing Attribution Processes EU HCP Data Without GDPR DPA',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `An AI marketing attribution model that measures HCP touchpoint contributions — educational events, sales calls, digital content engagement, speaker bureau participation — to device adoption decisions processes NPI-linked EU physician engagement data through a third-party AI analytics vendor without a GDPR Article 28 data processing agreement specifying permitted data use, data retention limits, and sub-processor disclosure, creating supervisory authority notification risk in every EU market where the company operates. The attribution model's GDPR gap reflects a compliance scoping failure that treated physician professional engagement data as outside GDPR scope because it was not patient health data — missing that the GDPR's data subject definition encompasses natural persons regardless of professional role, and that commercial AI processing of EU physician engagement data requires the same processor agreement infrastructure as patient data processing.`,
    keywords: ['AI attribution model', 'GDPR', 'HCP data', 'data processing agreement', 'AI commercial compliance'],
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1736',
    name: 'AI Regulatory Drafting Tool Injects Pre-Clearance Data Into Commercial Content',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `An LLM regulatory response drafting tool shared between the regulatory affairs and commercial teams generates content that cites clinical evidence from the company's pending-publication study portfolio in commercial market access dossiers — because the tool's knowledge base includes internal clinical data without access controls distinguishing pre-clearance studies from published evidence — producing commercially deployed content that references pre-clearance clinical performance figures in contexts where their use constitutes off-label promotion. The regulatory-commercial access boundary failure is compounded by the LLM's design as a productivity tool that maximises content completeness: the model incorporates all available evidence to produce the strongest-possible clinical narrative regardless of whether the evidence meets the publication and FDA review threshold required for promotional use.`,
    keywords: ['LLM regulatory drafting', 'FDA 21 CFR Part 801', 'off-label promotion', 'data substantiation', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },
  {
    code: 'M1737',
    name: 'AI Proposal Writer Cites Internal Data Not Available in Published Literature',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `A generative AI proposal writing tool draws on an unstructured internal knowledge base that includes pre-publication clinical study reports, internal product development data, and conference presentation drafts — generating proposal content that cites clinical performance figures derived from data sources that have not been publicly published or FDA-reviewed, producing promotional claims that cannot be substantiated through publicly available evidence as required by 21 CFR Part 801's truthfulness and non-misleading standards. The data substantiation failure is created by the AI tool's knowledge base curation policy, which prioritises information completeness over promotional compliance — including all available internal clinical data without distinguishing between approved, published evidence and internal data that has not yet cleared the regulatory review and publication pathway required for use in promotional claims.`,
    keywords: ['GenAI proposal writing', 'FDA 21 CFR Part 801', 'data substantiation', 'AdvaMed Code', 'AI commercial compliance'],
    demoRelevant: true,
    subTopic: 'ai-hcp-engagement',
    aiInsertionRisk: true,
  },

  // ── Physician Payment Transparency (M1738–M1749) ──────────────────────────

  {
    code: 'M1738',
    name: 'Open Payments Dispute Window Missed — Corrections Not Submitted',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `The company's compliance team does not proactively notify covered recipients of their reported Open Payments records or monitor the CMS dispute portal for physician-initiated corrections during the 45-day review window, resulting in disputed records being published as final without the company's rebuttal and permanently attaching inaccurate transfer-of-value data to individual physicians' Open Payments profiles. The 45-day dispute window under 42 CFR §403.910 is a bounded opportunity to correct errors before publication as final data, and a passive dispute management approach that waits for physician-initiated challenges rather than proactively auditing high-value records creates a systematic missed-window pattern that accumulates inaccuracies across annual reporting cycles.`,
    keywords: ['Open Payments', 'Sunshine Act', 'CMS reporting', 'transfer of value', 'OIG compliance guidance'],
    demoRelevant: true,
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1739',
    name: 'Indirect Transfer of Value Through Third-Party Vendors Unreported',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `Transfers of value provided to HCPs through third-party intermediaries — promotional agencies, event management companies, and CME vendors — are not systematically captured in the Open Payments submission because payments flow through vendor accounts rather than directly from the manufacturer, creating a reporting gap in which the company's CMS submission understates the total commercial investment directed at individual covered recipients. The Sunshine Act's reporting obligation under 42 CFR §403.904 covers indirect transfers of value made through third-party intermediaries on behalf of the manufacturer, and a compliance programme that tracks only direct payments misses the full scope of reportable transfers whenever indirect channels are used for HCP engagement activities.`,
    keywords: ['Sunshine Act', 'Open Payments', 'indirect transfer of value', 'CMS reporting', 'AdvaMed Code'],
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1740',
    name: 'Aggregate Spend Threshold Monitoring Lacks Real-Time Alert Triggers',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `The company's HCP aggregate spend monitoring system calculates year-to-date transfer-of-value totals for individual physicians on a monthly batch schedule — rather than in real time at the point of each engagement transaction — creating a 30-day monitoring gap in which commercial activity can exceed annual aggregate spend thresholds before the compliance team receives an alert and initiates enhanced review. The lag between aggregate spend accrual and monitoring alert is a predictable compliance gap: when spending on a high-priority HCP accelerates in the final quarter — speaker fees, advisory board attendance, conference sponsorship — the batch monitoring system may not identify a threshold exceedance until after the engagement that triggered it has occurred and cannot be reversed.`,
    keywords: ['aggregate spend monitoring', 'Open Payments', 'Sunshine Act', 'OIG compliance guidance', 'transfer of value'],
    demoRelevant: true,
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1741',
    name: 'Research Payment Documentation Does Not Meet CMS Specificity Standards',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Research payments reported in the Open Payments research payment category lack the study protocol citation, IRB approval reference, and principal investigator documentation that CMS specifies for the research payment classification — causing CMS auditors to reclassify the payments as general payments with higher public scrutiny profiles and higher likelihood of OIG follow-on inquiry. CMS research payment classification under 42 CFR §403.908 requires that payments supporting bona fide clinical research be documented with the research protocol and IRB reference at the time of submission, and a compliance data collection process that gathers payment amounts without the required protocol documentation creates systematic misclassification that understates the company's general payment totals while inflating the research payment category.`,
    keywords: ['Open Payments', 'Sunshine Act', 'research payment', 'CMS reporting', 'OIG compliance guidance'],
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1742',
    name: 'Post-Acquisition Open Payments Integration Misses Pre-Close Records',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Following a device company acquisition, the acquirer's compliance team integrates the acquired entity's HCP engagement data without reconciling transfers of value made in the pre-close period — creating duplicate or missing attributions in the annual Open Payments report when both entities reported independently under different legal entity identifiers that CMS cannot automatically reconcile. CMS guidance requires acquiring entities to report all transfers of value made by the acquired entity as of the acquisition close date and coordinate with CMS on the legal entity transition, and the absence of a structured M&A Open Payments integration protocol creates a known reporting gap in every mid-year acquisition transaction.`,
    keywords: ['Open Payments', 'Sunshine Act', 'M&A integration', 'CMS reporting', 'transfer of value'],
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1743',
    name: 'Device Demonstration Loans Not Evaluated for Open Payments Reportability',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `Capital equipment loaned to hospital laboratories for extended evaluation periods — typically 60–180 days — is not evaluated for Open Payments reportability as a loan of product with demonstrable fair market value, despite CMS guidance that extended equipment loans with significant commercial value may qualify as reportable transfers of value when the primary purpose is commercial evaluation rather than bona fide research. The loan programme compliance gap reflects the absence of a legal review step in the commercial operations approval process, meaning that equipment valued at $50,000–$500,000 is placed in HCP accounts without a Sunshine Act reportability determination that CMS could review in an audit.`,
    keywords: ['Open Payments', 'Sunshine Act', 'device demonstration', 'transfer of value', 'CMS reporting'],
    demoRelevant: true,
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1744',
    name: 'International Affiliate Payments to US Physicians Not Consolidated',
    officeCategory: 'middle_office',
    failureRatePct: 65,
    description: `US-licensed physicians who participate in international medical education events sponsored by non-US affiliates receive transfers of value not consolidated into the US Open Payments submission, despite the physicians being covered recipients under the Sunshine Act regardless of which affiliate makes the payment. The Open Payments reporting obligation follows the covered recipient's NPI — not the geography of the paying entity — meaning that international affiliate-funded transfers to US physicians are reportable by the US manufacturer even when payment flows from a non-US subsidiary, and a compliance infrastructure that consolidates only domestic affiliate data misses the entire cross-border transfer-of-value stream.`,
    keywords: ['Open Payments', 'Sunshine Act', 'international affiliate', 'CMS reporting', 'transfer of value'],
    demoRelevant: true,
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1745',
    name: 'Nature of Payment Category Mapping Inconsistent Across Business Units',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Different business units apply different mapping rules for categorising transfers of value into CMS Open Payments nature-of-payment categories — one unit classifies advisory board honoraria as consulting fees while another classifies the same activity as speaker fees, and one unit categorises educational grants as general payments while another correctly classifies them as research payments — creating CMS audit exposure when the consolidated submission reveals implausible category distributions for activities that should be uniformly classified. CMS audit guidance focuses on nature-of-payment inconsistencies as indicators of systemic classification errors, and a multi-business-unit manufacturer without a centralised classification policy will accumulate category errors across reporting cycles that compound into material misstatements.`,
    keywords: ['Open Payments', 'Sunshine Act', 'CMS reporting', 'OIG compliance guidance', 'transfer of value'],
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1746',
    name: 'Clinical Fellowship Funding Misclassified as Charitable Donation',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Company-funded clinical fellowship programmes providing device training and procedural skills development to identified physicians are classified as charitable donations or educational grants rather than general payments in the Open Payments submission, understating the direct value transferred to individual fellows who receive stipends, travel funding, and device access during the fellowship period. CMS guidance requires that fellowship funding benefiting a specific identified covered recipient be classified as a general payment to that physician rather than an institutional grant, and a classification practice that categorises identified-recipient fellowship spending as institutional grants creates systematic misclassification in the annual filing.`,
    keywords: ['Open Payments', 'Sunshine Act', 'clinical fellowship', 'CMS reporting', 'transfer of value'],
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1747',
    name: 'Assumption-of-Ownership Device Transfer Not Assessed for FMV Reporting',
    officeCategory: 'middle_office',
    failureRatePct: 57,
    description: `Capital equipment transferred to health systems under end-of-lease or evaluation-period assumption-of-ownership provisions — where the customer retains the device at nominal or zero cost — is not evaluated for Open Payments reportability as a transfer of value equal to the device's fair market value at transfer, creating systematic under-reporting of high-value equipment transfers that the OIG and CMS have identified as a significant Sunshine Act compliance gap in device company reporting. The assumption-of-ownership transfer is structurally equivalent to a gift of device value, and the absence of a standard commercial transaction record that captures the transfer creates an opportunity to overlook what is in substance a reportable transfer of value whenever devices are retired from evaluation programmes through ownership assumption.`,
    keywords: ['Open Payments', 'Sunshine Act', 'transfer of value', 'fair market value', 'OIG compliance guidance'],
    demoRelevant: true,
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1748',
    name: 'Teaching Hospital Affiliation Lookup Uses Stale Annual Reference Data',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `The Open Payments submission process uses a static teaching hospital affiliation list that was last refreshed at system implementation, resulting in payments attributed to hospital affiliations that no longer reflect the physician's current institution — because CMS requires covered recipients to be associated with their current primary teaching hospital affiliation, not the affiliation when the original CRM record was created. CMS updates the teaching hospital list annually, and using a stale affiliation lookup creates systematic attribution errors in the annual submission that require dispute resolution and restatement, consuming compliance capacity with corrections avoidable by incorporating the CMS annual hospital list update into the Open Payments preparation workflow.`,
    keywords: ['Open Payments', 'Sunshine Act', 'teaching hospital', 'CMS reporting', 'NPI registry'],
    subTopic: 'physician-payment-transparency',
  },
  {
    code: 'M1749',
    name: 'Teaching Hospital Payments Not Separated From Physician Payment Records',
    officeCategory: 'middle_office',
    failureRatePct: 54,
    description: `Transfers of value made to teaching hospitals — device grants, unrestricted educational gifts, and infrastructure support payments — are aggregated with physician payment records in the compliance tracking system and only separated into the correct Open Payments entity category at submission time, creating attribution errors when the submission mapping logic incorrectly assigns teaching hospital payments to individual NPI-associated covered recipients rather than the hospital entity. CMS requires separate reporting streams for physician covered recipients and teaching hospital covered recipients under 42 CFR §403.902, and a tracking system that does not structurally separate these recipient categories produces annual submissions whose accuracy depends entirely on a last-minute mapping step rather than data integrity maintained throughout the reporting period.`,
    keywords: ['Open Payments', 'Sunshine Act', 'teaching hospital', 'CMS reporting', 'transfer of value'],
    subTopic: 'physician-payment-transparency',
  },

  // ── Off-Label Promotion Prevention (M1750–M1759) ─────────────────────────

  {
    code: 'M1750',
    name: 'Field Force Off-Label Communication Monitoring Lacks Structured Sampling',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `The company's field force off-label communication monitoring programme relies on self-reported representative compliance attestations and manager ride-along observations without a structured call recording analysis programme that samples a statistically meaningful percentage of HCP interactions for cleared indication boundary compliance — creating a monitoring gap in which off-label patterns in the sales force's HCP communication are only detected through escalated complaints rather than systematic surveillance. FDA enforcement investigations that identify a pattern of off-label promotion in a company's sales force consistently find that the company's compliance monitoring programme was insufficient to detect the pattern, and a monitoring approach that depends on self-reporting and opportunistic manager observation rather than systematic sampling of HCP interactions provides compliance assurance that does not withstand regulatory scrutiny.`,
    keywords: ['off-label promotion', 'field force monitoring', 'FDA 21 CFR Part 801', 'compliance monitoring', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1751',
    name: 'Digital Channel Content Not Reviewed for Off-Label Indication Drift',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `The company's digital marketing content — product microsites, email nurture campaigns, social media managed accounts, and HCP portal content — is not systematically reviewed for cleared indication boundary compliance after initial publication, allowing content that was approved at launch to drift toward off-label territory through incremental copy updates, search engine optimisation revisions, and personalisation layer additions that individually pass editorial review but collectively produce landing page content that describes clinical applications outside the cleared indications. The digital content compliance drift pattern is particularly difficult to detect with point-in-time MLR review because each individual content update appears compliant while the cumulative effect of sequential updates moves the content's clinical scope beyond the cleared indication.`,
    keywords: ['digital channel compliance', 'off-label promotion', 'FDA 21 CFR Part 801', 'MLR review', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1752',
    name: 'MSL-Commercial Boundary Violation — Scientific Exchange Disguises Promotion',
    officeCategory: 'front_office',
    failureRatePct: 66,
    description: `The company's MSL organisation operates without clear written protocols distinguishing permissible scientific exchange from promotional communication, allowing commercial managers to direct MSLs to proactively initiate HCP discussions about off-label clinical applications under the guise of scientific exchange — creating promotional activity that bypasses the cleared indication guardrails applied to commercial representatives. FDA's scientific exchange framework permits MSLs to discuss off-label applications in response to genuine unsolicited HCP inquiries but does not permit commercially directed proactive MSL engagement with HCPs about non-cleared applications, and the absence of a compliance protocol that operationalises the solicited-vs-proactive boundary creates a structural MSL-commercial boundary violation that is difficult to detect without call pattern analysis.`,
    keywords: ['MSL boundary', 'scientific exchange', 'off-label promotion', 'FDA 21 CFR Part 801', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1753',
    name: 'Product Training Curriculum Covers Non-Cleared Clinical Applications',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `The commercial product training curriculum delivered at national sales meetings includes clinical application modules covering patient populations, diagnostic scenarios, and procedural uses identified as future 510(k) submission targets — but not currently cleared — teaching representatives to discuss these applications with HCPs before clearance is obtained. The training curriculum misalignment is a structural off-label promotion factory: it trains the entire sales force to communicate with clinical fluency about applications outside cleared indications, and when FDA investigates off-label promotion complaints the curriculum documenting the company's explicit instruction to representatives is the most damaging evidence of systematic commercial intent.`,
    keywords: ['sales training curriculum', 'off-label promotion', 'FDA 21 CFR Part 801', 'cleared indications', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1754',
    name: 'Reprint Distribution Library Curated by Marketing Not Medical Affairs',
    officeCategory: 'front_office',
    failureRatePct: 64,
    description: `Sales representatives distribute peer-reviewed journal article reprints describing off-label device applications in response to unsolicited HCP requests, following a policy that classifies proactive reprint distribution as permissible scientific exchange — but the reprints are selected from a library curated by marketing rather than medical affairs, meaning the response mechanism is supplied with commercially motivated content rather than content selected for scientific completeness. FDA's guidance on scientific publication distribution allows manufacturers to respond to unsolicited HCP requests with truthful, non-misleading peer-reviewed publications, but requires that the publication library and selection criteria be controlled by medical affairs rather than commercial functions to preserve the scientific exchange character of the distribution.`,
    keywords: ['reprint distribution', 'off-label promotion', 'medical affairs', 'FDA scientific exchange', 'AdvaMed Code'],
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1755',
    name: 'Social Media Posts Reference Off-Label Applications Under Company Affiliation',
    officeCategory: 'front_office',
    failureRatePct: 71,
    description: `Sales representatives using LinkedIn and medical professional social platforms post content discussing clinical applications, outcomes in specific patient populations, and diagnostic scenarios beyond the device's cleared indications — framing the posts as personal clinical opinions while identifying their company affiliation and product expertise in a way that creates FDA attribution of the posts as company-sponsored promotional communications. FDA's guidance on online communication tools treats content posted by company employees who identify their affiliation as company-attributed communications subject to 21 CFR Part 801's truthfulness and off-label promotion requirements, and a social media policy that prohibits explicit product promotion without specifically training representatives on the indication boundary for clinical commentary creates systematic off-label promotion exposure.`,
    keywords: ['social media compliance', 'off-label promotion', 'FDA 21 CFR Part 801', 'AdvaMed Code', 'sales training'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1756',
    name: 'Advisory Board Meetings Cover Pipeline Indications With Promotional Character',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `HCP advisory board meetings convened as scientific advisory activity routinely include commercial presentations describing the company's pipeline indications and pre-submission device capabilities — creating sessions that function as commercial launch briefings for off-label applications rather than genuine scientific advisory activities for which HCPs can legitimately receive consulting compensation. OIG advisory opinion guidance and the AdvaMed Code Section 3 require that advisory board compensation be justified by genuine advisory services and that meeting content be scientific rather than promotional in character, and meetings where the primary agenda consists of commercial previews of non-cleared applications are characterised by OIG as arrangements in which the true purpose is familiarising high-prescribing HCPs with future commercial applications.`,
    keywords: ['advisory board', 'off-label promotion', 'Anti-Kickback Statute', 'FDA 21 CFR Part 801', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1757',
    name: 'Conference Abstract Submissions by Commercial Staff Bypass Medical Affairs Review',
    officeCategory: 'front_office',
    failureRatePct: 62,
    description: `Commercial team employees submit conference abstracts describing device performance in off-label clinical applications to professional society meetings under institutional affiliations implying independent investigator status — bypassing the medical affairs review required by the company's publication policy for any content describing device performance in non-cleared applications. FDA's off-label promotion guidance identifies conference abstract submissions by commercial employees as promotional communications when they describe non-cleared applications with a view to influencing clinical adoption, and abstracts submitted without medical affairs review and without disclosure of the author's commercial employment status create promotional compliance exposure that is difficult to remediate after the abstract has been published in conference proceedings.`,
    keywords: ['conference abstract', 'off-label promotion', 'medical affairs', 'FDA 21 CFR Part 801', 'AdvaMed Code'],
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1758',
    name: 'IND/IDE Misrepresentation in Sales Calls — Investigational Use Implied as Cleared',
    officeCategory: 'front_office',
    failureRatePct: 69,
    description: `Sales representatives describe clinical applications under IDE or investigational new device exemption using phrases like "approved for" or "cleared to use in" when the application is under an IDE that has not been converted to a cleared indication — misrepresenting the device's regulatory status to HCPs in a way that constitutes both off-label promotion under 21 CFR Part 801 and potential misbranding under 21 U.S.C. §352. The IDE/cleared boundary confusion is compounded when the investigational application is clinically adjacent to the cleared indication — for example, a diagnostic device cleared for a specific analyte range discussed for an extended range under IDE — because representative training may not distinguish the IDE boundary with the precision FDA requires in commercial communications.`,
    keywords: ['IDE misrepresentation', 'off-label promotion', 'FDA 21 CFR Part 801', 'cleared indications', 'sales training'],
    demoRelevant: true,
    subTopic: 'off-label-promotion-prevention',
  },
  {
    code: 'M1759',
    name: 'Commercial Rep Call Notes Document Off-Label Clinical Discussions',
    officeCategory: 'front_office',
    failureRatePct: 60,
    description: `Sales representative call notes entered in the company's CRM system document clinical discussions with HCPs that include explicit references to off-label device applications — detailing clinical scenarios, patient populations, and procedural uses outside the cleared indications — creating a contemporaneous record of systematic off-label promotion that is discoverable in regulatory investigations and litigation. The CRM call note off-label documentation pattern indicates that the sales force discusses off-label applications routinely enough to document the discussions as part of standard CRM activity, and the absence of a call note review programme that detects and flags off-label language means the compliance team is unaware of a documented pattern of off-label discussions that FDA or OIG investigators would treat as the most probative evidence of systematic off-label promotion.`,
    keywords: ['CRM call notes', 'off-label promotion', 'FDA 21 CFR Part 801', 'compliance monitoring', 'AdvaMed Code'],
    subTopic: 'off-label-promotion-prevention',
  },

  // ── Medical Education Compliance (M1760–M1769) ────────────────────────────

  {
    code: 'M1760',
    name: 'CME Programme Independence Documentation Inadequate for ACCME Standards',
    officeCategory: 'middle_office',
    failureRatePct: 62,
    description: `Company-supported continuing medical education programmes do not maintain documentation sufficient to demonstrate independence from commercial influence as required by the Accreditation Council for Continuing Medical Education's Standards for Integrity and Independence — including faculty conflict-of-interest disclosures, content review records demonstrating that commercial support did not influence educational content, and financial arrangement documentation showing that the CME provider controlled all educational decisions. The CME independence documentation gap creates an accreditation risk for the CME provider and an OIG compliance risk for the company: without documentation that the CME programme was structured and executed independent of commercial influence, the company's financial support for the programme may be characterised as remuneration for educational endorsement rather than legitimate educational grant-making under OIG's safe harbour analysis.`,
    keywords: ['CME independence', 'ACCME standards', 'OIG compliance guidance', 'medical education', 'Anti-Kickback Statute'],
    demoRelevant: true,
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1761',
    name: 'Advisory Board Compensation Exceeds Fair Market Value for Services Rendered',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `Advisory board honoraria rates are set at levels that exceed the fair market value of the advisory services provided — typically $2,500–$5,000 for half-day advisory meetings at which physicians attend product discussions rather than providing meaningful advisory input — creating Anti-Kickback Statute exposure when the compensation arrangement's true economic function is remuneration for device adoption influence rather than payment for genuine advisory services valued at the contracted rate. OIG advisory opinion guidance requires that consulting compensation reflect the actual fair market value of services provided in arm's-length transactions between unrelated parties, and advisory arrangements in which the hourly rate implied by the compensation is three to five times the physician's documented billing rate for clinical services fail the fair market value test that distinguishes legitimate consulting from unlawful remuneration.`,
    keywords: ['advisory board compensation', 'Anti-Kickback Statute', 'fair market value', 'OIG compliance guidance', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1762',
    name: 'Speaker Bureau Management Lacks Documentation of Educational Outcome Objectives',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `The company's speaker bureau programme does not require speaker programmes to document specific educational objectives, audience learning outcomes, or post-programme educational assessment — operating without the educational outcome framework that distinguishes genuine HCP education programmes from promotional dinner meetings at which speaker fees function as remuneration for attendance. OIG compliance programme guidance for medical device manufacturers requires that speaker bureau programmes demonstrate a genuine educational purpose through documented learning objectives, appropriate audience composition, and post-programme outcome assessment — and programmes that lack these elements are characterised by OIG as sham educational programmes in which the primary function is rewarding HCPs for device adoption through honorarium payments disguised as speaker fees.`,
    keywords: ['speaker bureau', 'Anti-Kickback Statute', 'OIG compliance guidance', 'medical education', 'AdvaMed Code'],
    demoRelevant: true,
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1763',
    name: 'Medical Education Grant Review Does Not Exclude Commercial Bias Indicators',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `The company's medical education grant review committee does not systematically evaluate grant applications for commercial bias indicators — programme content focused on the company's device vs. competitive alternatives, grant applicant relationships with commercial sales teams, and proposed faculty composition weighted toward the company's commercial KOLs — allowing commercial bias in medical education programme design to persist beneath a grant review process that evaluates educational merit without systematically excluding commercially motivated applications. OIG's 2003 compliance programme guidance for medical device manufacturers identifies the independence of commercially supported medical education from commercial bias as the defining characteristic of legitimate educational grant-making, and a grant review process that evaluates educational quality without screening for commercial bias indicators cannot demonstrate that the programme funding is genuinely educational.`,
    keywords: ['medical education grant', 'OIG compliance guidance', 'Anti-Kickback Statute', 'CME independence', 'AdvaMed Code'],
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1764',
    name: 'Preceptorship Programme HCP Compensation Not Evaluated for AKS Safe Harbour',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `Preceptorship programmes in which the company compensates experienced physicians to provide hands-on procedural training to other physicians using the company's devices do not undergo Anti-Kickback Statute safe harbour analysis before launch — operating under a generic consulting agreement framework that characterises the compensation as consulting fees without evaluating whether the compensation reflects fair market value for training services and whether the preceptor's compensation is unrelated to the volume or value of the company's products recommended by either the preceptor or the trainee. The preceptor compensation arrangement creates dual Anti-Kickback Statute exposure: the preceptor who receives compensation may be influenced toward recommending the device to trainees, and the trainee who receives free procedural training may be induced to adopt the device whose manufacturer provided the training.`,
    keywords: ['preceptorship programme', 'Anti-Kickback Statute', 'fair market value', 'OIG compliance guidance', 'medical education'],
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1765',
    name: 'KOL Development Programme Conflates Scientific Credibility With Commercial Value',
    officeCategory: 'front_office',
    failureRatePct: 67,
    description: `The company's key opinion leader development programme selects and invests in physician thought leaders using criteria that combine scientific expertise indicators — publication activity, clinical trial leadership, society committee membership — with commercial value indicators — prescribing volume, hospital system influence, and specialty peer network — without separating the KOL development programme from commercial targeting so that KOL investment is driven by genuine scientific credibility rather than commercial adoption influence. OIG enforcement guidance identifies KOL development programmes as a primary mechanism for disguising commercial remuneration as scientific recognition, and programmes that select KOLs using commercial value criteria alongside scientific criteria are characterised as arrangements in which the scientific recognition serves to legitimise what is in substance commercial influence cultivation.`,
    keywords: ['KOL development', 'Anti-Kickback Statute', 'OIG compliance guidance', 'AdvaMed Code', 'commercial remuneration'],
    demoRelevant: true,
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1766',
    name: 'Investigator-Initiated Study Funding Approval Does Not Screen for Commercial Quid Pro Quo',
    officeCategory: 'middle_office',
    failureRatePct: 56,
    description: `The company's investigator-initiated study funding approval process does not require applicants to disclose their current commercial relationship with the company's sales team — including aggregate spending received, speaker bureau participation, and advisory board membership — allowing investigators who are simultaneously engaged in high-value commercial relationships with the company to receive research funding that creates the appearance of independent research while the totality of the financial relationship is consistent with a quid pro quo arrangement. OIG guidance requires that investigator-initiated research grants be awarded on scientific merit through a process genuinely independent of commercial considerations, and a grant approval process that does not screen for the applicant's commercial relationship history cannot demonstrate the independence that distinguishes legitimate research funding from commercially motivated grant-making.`,
    keywords: ['investigator-initiated study', 'Anti-Kickback Statute', 'OIG compliance guidance', 'research funding', 'AdvaMed Code'],
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1767',
    name: 'CME Grant Documentation Retention Does Not Support OIG Audit',
    officeCategory: 'middle_office',
    failureRatePct: 58,
    description: `The company's CME grant documentation retention programme does not preserve the full grant application, content review documentation, independence certification, and post-programme assessment materials required to demonstrate the bona fide educational character of the programme in an OIG compliance audit — retaining only the grant agreement and payment records rather than the independence documentation that distinguishes legitimate CME funding from commercially motivated educational grant-making. An OIG audit of the company's CME grant programme that requests documentation demonstrating programme independence will find that the compliance team can produce financial records but cannot produce the independence documentation required to demonstrate compliance with OIG's CME grant guidance, creating a per-se compliance failure in the audit regardless of the programme's actual educational independence.`,
    keywords: ['CME grant documentation', 'OIG compliance guidance', 'Anti-Kickback Statute', 'medical education', 'ACCME standards'],
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1768',
    name: 'Dinner Programme Attendee List Analysis Shows High-Prescriber Concentration',
    officeCategory: 'middle_office',
    failureRatePct: 69,
    description: `Analysis of speaker programme attendee lists reveals that dinner educational programmes disproportionately recruit the highest-prescribing physicians in each sales territory — with the top 20% of prescribers accounting for 65% of programme attendees — indicating that the sales force is using speaker programme invitations as a commercial engagement tool to reward high-prescribing HCPs rather than to distribute educational content to the physicians most in need of clinical education. The prescriber concentration pattern in dinner programme attendance is the specific indicator that OIG's compliance guidance identifies as evidence that speaker programmes function as commercially motivated remuneration arrangements: genuine educational programmes recruit physicians based on educational need, while programmes that recruit disproportionately from the highest prescribers are functionally commercial reward mechanisms regardless of their stated educational purpose.`,
    keywords: ['speaker dinner programme', 'Anti-Kickback Statute', 'OIG compliance guidance', 'AdvaMed Code', 'prescriber concentration'],
    demoRelevant: true,
    subTopic: 'medical-education-compliance',
  },
  {
    code: 'M1769',
    name: 'Medical Affairs Budget Under Commercial Operational Control — Independence Compromised',
    officeCategory: 'middle_office',
    failureRatePct: 61,
    description: `The medical affairs organisation's budget for scientific exchange activities, MSL deployment, and investigator-initiated research funding is controlled by commercial leadership rather than independent medical leadership — creating structural pressure on medical affairs activities to serve commercial objectives, and creating OIG compliance exposure because medical affairs activities funded through a budget under commercial operational control cannot be demonstrated to be genuinely independent of commercial influence. OIG's compliance guidance for device manufacturers identifies the independence of medical affairs from commercial operations as a prerequisite for the scientific exchange safe harbour, and a medical affairs organisation whose budget, headcount, and activity priorities are determined by commercial leadership rather than independent medical leadership does not qualify for the scientific exchange protection regardless of how its activities are characterised internally.`,
    keywords: ['medical affairs independence', 'OIG compliance guidance', 'Anti-Kickback Statute', 'scientific exchange', 'AdvaMed Code'],
    subTopic: 'medical-education-compliance',
  },

  // ── Distribution Channel Compliance (M1770–M1779) ─────────────────────────

  {
    code: 'M1770',
    name: 'Distributor Promotional Compliance Oversight Programme Is Inadequate',
    officeCategory: 'middle_office',
    failureRatePct: 67,
    description: `The company's distributor agreements require compliance with FDA promotional regulations but do not implement a structured distributor promotional compliance oversight programme — including periodic audits of distributor promotional materials, distributor representative field ride-along observations, and distributor call recording sampling — creating a principal-agent compliance gap in which the company's legal responsibility for promotional compliance in distributor territories is not backed by operational monitoring sufficient to detect and remediate distributor off-label promotion or inaccurate device claims. FDA holds manufacturers responsible for promotional activities conducted by their authorised distributors, and a compliance programme that relies on contractual representations without operational monitoring of distributor promotional activity does not meet the oversight standard that FDA expects a manufacturer to apply to its authorised distribution partners.`,
    keywords: ['distributor compliance', 'FDA 21 CFR Part 801', 'promotional oversight', 'AdvaMed Code', 'distribution channel'],
    demoRelevant: true,
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1771',
    name: 'GPO Contract Compliance Monitoring Does Not Track Volume Tier Thresholds',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `The company's GPO contract compliance monitoring programme tracks revenue and volume against contract terms but does not monitor whether member hospitals are meeting the volume tier requirements that activate enhanced discount tiers — allowing hospitals to benefit from enhanced discount pricing without meeting the volume commitments that justify the discount under the GPO agreement's tiered pricing structure. The volume tier monitoring gap creates both a revenue leakage risk — hospitals receive discounts not justified by their actual purchase volume — and an Anti-Kickback Statute exposure risk if the discount structure effectively provides below-fair-market-value pricing to member hospitals in ways that were not structured to meet the personal services or discount safe harbour requirements.`,
    keywords: ['GPO contract compliance', 'Anti-Kickback Statute', 'discount safe harbour', 'volume tier', 'distribution channel'],
    demoRelevant: true,
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1772',
    name: 'Specialty Pharmacy Promotional Material Controls Not Extended to Distribution Partners',
    officeCategory: 'front_office',
    failureRatePct: 65,
    description: `Promotional materials distributed through specialty pharmacy partners — including patient assistance programme materials, copay support communications, and product information sheets — are not routed through the company's MLR review process before distribution by the specialty pharmacy, allowing specialty pharmacy promotional communications to reach patients and HCPs with unreviewed clinical claims and incomplete risk information that would not meet FDA's promotional labeling standards if reviewed through the company's standard MLR process. The specialty pharmacy promotional material gap reflects a distribution channel scoping failure in the MLR programme: the review workflow was designed for direct promotional materials and did not extend to materials distributed by specialty pharmacy partners despite the manufacturer's responsibility for accuracy and completeness of promotional information about its own products regardless of the distribution channel.`,
    keywords: ['specialty pharmacy', 'FDA promotional labeling', 'MLR review', 'patient assistance', 'distribution channel'],
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1773',
    name: 'International Distributor Off-Label Promotion Not Monitored in Regulated Markets',
    officeCategory: 'middle_office',
    failureRatePct: 70,
    description: `International distributors operating in regulated markets — EU CE Mark, Health Canada, TGA-regulated markets — promote the device for clinical applications that are within the cleared indications in the US market but that have not received regulatory clearance in the local market, creating off-label promotion violations under the local regulatory framework that are not detected by the manufacturer's compliance programme because the programme's off-label monitoring scope is defined by US cleared indications rather than by the local regulatory clearance status in each distributor's market. The international distributor off-label gap is a systematic compliance blind spot for US-centric compliance programmes: a device that has received 510(k) clearance for a broad indication set in the US may have received CE Mark or TGA clearance for a narrower indication set, and distributor promotion of the US-cleared indications in EU or Australian markets constitutes off-label promotion under the local framework even when the same promotion would be on-label in the US.`,
    keywords: ['international distributor', 'off-label promotion', 'CE Mark', 'TGA', 'distribution channel'],
    demoRelevant: true,
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1774',
    name: 'Distributor Representative Product Training Does Not Cover Off-Label Boundaries',
    officeCategory: 'front_office',
    failureRatePct: 68,
    description: `The company's product training programme for distributor sales representatives focuses on device operation, technical features, and competitive positioning without including explicit instruction on the cleared indication boundaries, off-label promotion prohibitions, and regulatory framework applicable to the distributor's promotional activities — creating a distributor field force that lacks the compliance foundation to distinguish cleared from non-cleared clinical applications when engaging with HCPs. Manufacturer product training for distributor representatives that omits off-label promotion training creates the same FDA compliance exposure as training gaps in the manufacturer's own field force, because the manufacturer's responsibility for promotional compliance in authorised distribution channels extends to ensuring that distributor representatives receive adequate training on the regulatory boundaries applicable to their HCP promotional activities.`,
    keywords: ['distributor training', 'off-label promotion', 'FDA 21 CFR Part 801', 'cleared indications', 'distribution channel'],
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1775',
    name: 'Consignment Inventory in Hospital Accounts Lacks Transfer-of-Value Tracking',
    officeCategory: 'middle_office',
    failureRatePct: 59,
    description: `Consignment inventory programmes that place device inventory in hospital catheterisation laboratories, operating rooms, and intervention suites without a transfer of ownership do not systematically track the fair market value of the inventory service provided to the hospital — including the capital equipment value in storage, the carrying cost of inventory, and the convenience benefit of on-demand access — creating a failure to assess whether the consignment programme's aggregate benefit to the hospital constitutes a reportable transfer of value or a pricing arrangement that does not meet fair market value standards under the Anti-Kickback Statute. Consignment inventory arrangements that provide hospitals with significant economic benefits through inventory financing, storage services, and availability guarantees require Anti-Kickback Statute analysis comparable to other service arrangements in which the manufacturer provides value to the purchasing institution.`,
    keywords: ['consignment inventory', 'Anti-Kickback Statute', 'fair market value', 'Open Payments', 'distribution channel'],
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1776',
    name: 'Reseller Channel Lacks Adequate Chargebacks Audit Trail for GPO Compliance',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `The company's reseller channel — where distributors purchase devices at list price and submit chargebacks to receive the difference between list price and the GPO contract price paid by end-customer hospitals — does not maintain an audit trail sufficient to verify that chargeback submissions correspond to actual sales to eligible GPO member hospitals at the GPO contract price, creating a GPO contract compliance exposure when chargebacks are submitted for sales to non-member hospitals or at prices that do not correspond to the applicable GPO contract tier. The chargeback audit trail gap is a standard GPO compliance vulnerability in multi-tier distribution arrangements, and a manufacturer that cannot reconcile chargeback submissions to verified end-customer GPO membership and purchase price data cannot demonstrate contract price compliance in a GPO audit.`,
    keywords: ['GPO chargeback', 'distribution channel', 'GPO contract compliance', 'audit trail', 'reseller channel'],
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1777',
    name: 'Distributor Field Inventory Audit Programme Does Not Cover Promotional Materials',
    officeCategory: 'middle_office',
    failureRatePct: 64,
    description: `The company's distributor field inventory audit programme — designed to verify physical inventory accuracy, product storage compliance, and lot traceability — does not include an audit component covering promotional materials held in distributor possession, allowing distributors to continue using superseded, unapproved, or off-label promotional materials that were distributed before an MLR revision without the manufacturer's knowledge or ability to enforce withdrawal of non-compliant materials. Manufacturer responsibility for the accuracy of promotional materials in distributor possession extends through the entire distribution chain, and a distributor field audit programme that verifies product inventory without auditing promotional materials creates a systematic promotional compliance gap proportional to the volume of promotional materials in distribution and the frequency with which materials are revised.`,
    keywords: ['distributor audit', 'promotional materials', 'FDA 21 CFR Part 801', 'MLR review', 'distribution channel'],
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1778',
    name: 'DME Distributor Referral Programme Creates Anti-Kickback Exposure',
    officeCategory: 'middle_office',
    failureRatePct: 66,
    description: `A durable medical equipment distributor referral programme that compensates distributors for referring patients to preferred DME suppliers — combining device distribution with referral fees for directing patients to the DME supplier network — is not evaluated against the Anti-Kickback Statute's referral fee safe harbour requirements, creating exposure when the referral compensation is not structured to meet either the personal services safe harbour or the discount safe harbour applicable to DME arrangements. The DME referral programme creates Anti-Kickback Statute exposure because it combines the distribution of a reimbursable medical device with financial inducements for patient referral to preferred suppliers — precisely the commercial structure that the AKS safe harbour framework for DME arrangements was designed to regulate and that OIG enforcement guidance identifies as a high-risk area for device manufacturers operating in the DME channel.`,
    keywords: ['DME referral programme', 'Anti-Kickback Statute', 'OIG compliance guidance', 'distribution channel', 'referral fee'],
    demoRelevant: true,
    subTopic: 'distribution-channel-compliance',
  },
  {
    code: 'M1779',
    name: 'Specialty Distributor Performance Incentives Tied to Device Utilisation Rates',
    officeCategory: 'middle_office',
    failureRatePct: 63,
    description: `Specialty distributor performance incentive programmes that pay distributors annual bonuses based on hospital account device utilisation rates — rather than on distribution activity metrics like inventory management efficiency, order fulfilment accuracy, and customer service performance — create Anti-Kickback Statute exposure by structuring distributor compensation to be correlated with the volume of the company's devices used by HCPs in the distributor's accounts. OIG compliance guidance requires that distribution incentive arrangements be structured so that distributor compensation reflects the value of distribution services rather than the volume or value of devices recommended or used by HCPs — and utilisation rate-based bonus programmes that reward distributors for influencing HCP usage are characterised as remuneration arrangements in which the true purpose is incentivising commercial influence over clinical device selection.`,
    keywords: ['distributor incentive', 'Anti-Kickback Statute', 'OIG compliance guidance', 'utilisation rate', 'distribution channel'],
    demoRelevant: true,
    subTopic: 'distribution-channel-compliance',
  },
];
