/* eslint-disable @typescript-eslint/no-unused-vars */
// Generated healthcare AI/startup ecosystem corpus.
// Domain 67: Agentic AI: Administrative Copilots
// Part 4: H17350-H17399
// Format: content-only *PATTERNS array consumed by scripts/corpus/load-authored-genome-seeds.ts.

const HEALTHCARE_DOM67_PART4_PATTERNS = [
  {
    code: 'H17350',
    name: 'Administrative Copilot Worklist Prioritization Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for worklist prioritization but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'FHIR R4 mapping', 'Epic App Orchard integration', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17351',
    name: 'Task Automation Appeal Generation Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 69,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for appeal generation but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'HL7 v2 ADT reconciliation', 'Microsoft Cloud for Healthcare', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17352',
    name: 'HR Service Delivery Order Recommendation Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 84,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for order recommendation but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'Epic change control', 'AWS HealthLake', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17353',
    name: 'Policy Retrieval Benefit Verification Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for benefit verification but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'model registry', 'Azure Health Data Services', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17354',
    name: 'Approval Workflow Eligibility Prediction Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for eligibility prediction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'deployment-site validation', 'Snowflake Healthcare', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17355',
    name: 'Administrative Copilot Care Gap Closure Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 59,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for care gap closure but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'MLOps monitoring', 'Databricks Lakehouse', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17356',
    name: 'Task Automation Cohort Matching Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for cohort matching but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'clinical safety review', 'ServiceNow workflow', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17357',
    name: 'HR Service Delivery Contract Analysis Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for contract analysis but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'procurement RFP scoring', 'Salesforce Health Cloud', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17358',
    name: 'Policy Retrieval Agentic Orchestration Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for agentic orchestration but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'BAFO contract clause', 'startup maturity evidence', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17359',
    name: 'Approval Workflow Coding Suggestion Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 73,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for coding suggestion but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'HIPAA BAA', 'SOC 2 Type II', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17360',
    name: 'Administrative Copilot Documentation Review Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for documentation review but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'minimum necessary policy', 'HITRUST roadmap', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17361',
    name: 'Task Automation Vendor Comparison Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 67,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for vendor comparison but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'TJC survey evidence', 'Series B burn rate', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17362',
    name: 'HR Service Delivery Capacity Forecasting Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for capacity forecasting but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'CMS CoP', 'implementation partner capacity', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17363',
    name: 'Policy Retrieval Staffing Optimization Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for staffing optimization but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'NCQA HEDIS audit', 'referenceable health-system customer', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17364',
    name: 'Approval Workflow Quality Abstraction Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for quality abstraction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'FDA SaMD guidance', 'clinical advisory board', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17365',
    name: 'Administrative Copilot Patient Outreach Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 71,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for patient outreach but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'NIST AI RMF', 'FDA submission posture', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17366',
    name: 'Task Automation Triage Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for triage but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'ONC HTI-1', 'KLAS commentary', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17367',
    name: 'HR Service Delivery Drafting Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 66,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for drafting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'TEFCA participation', 'Epic App Orchard integration', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17368',
    name: 'Policy Retrieval Summarization Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 79,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for summarization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'FHIR R4 mapping', 'Microsoft Cloud for Healthcare', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17369',
    name: 'Approval Workflow Risk Scoring Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 65,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for risk scoring but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'HL7 v2 ADT reconciliation', 'AWS HealthLake', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17370',
    name: 'Administrative Copilot Worklist Prioritization Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for worklist prioritization but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'Epic change control', 'Azure Health Data Services', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17371',
    name: 'Task Automation Appeal Generation Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for appeal generation but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'model registry', 'Snowflake Healthcare', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17372',
    name: 'HR Service Delivery Order Recommendation Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for order recommendation but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'deployment-site validation', 'Databricks Lakehouse', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17373',
    name: 'Policy Retrieval Benefit Verification Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for benefit verification but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'MLOps monitoring', 'ServiceNow workflow', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17374',
    name: 'Approval Workflow Eligibility Prediction Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for eligibility prediction but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'clinical safety review', 'Salesforce Health Cloud', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17375',
    name: 'Administrative Copilot Care Gap Closure Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for care gap closure but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'procurement RFP scoring', 'startup maturity evidence', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17376',
    name: 'Task Automation Cohort Matching Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for cohort matching but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'BAFO contract clause', 'SOC 2 Type II', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17377',
    name: 'HR Service Delivery Contract Analysis Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 55,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for contract analysis but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'HIPAA BAA', 'HITRUST roadmap', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17378',
    name: 'Policy Retrieval Agentic Orchestration Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 83,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for agentic orchestration but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'minimum necessary policy', 'Series B burn rate', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17379',
    name: 'Approval Workflow Coding Suggestion Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 56,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for coding suggestion but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'TJC survey evidence', 'implementation partner capacity', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17380',
    name: 'Administrative Copilot Documentation Review Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 62,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for documentation review but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'CMS CoP', 'referenceable health-system customer', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17381',
    name: 'Task Automation Vendor Comparison Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 75,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for vendor comparison but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'NCQA HEDIS audit', 'clinical advisory board', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17382',
    name: 'HR Service Delivery Capacity Forecasting Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for capacity forecasting but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is FDA SaMD guidance: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'FDA SaMD guidance', 'FDA submission posture', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17383',
    name: 'Policy Retrieval Staffing Optimization Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for staffing optimization but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is NIST AI RMF: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is KLAS commentary, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'NIST AI RMF', 'KLAS commentary', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17384',
    name: 'Approval Workflow Quality Abstraction Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 61,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for quality abstraction but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is ONC HTI-1: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Epic App Orchard integration, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'ONC HTI-1', 'Epic App Orchard integration', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17385',
    name: 'Administrative Copilot Patient Outreach Alert Fatigue Inflection',
    officeCategory: 'back_office',
    failureRatePct: 82,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for patient outreach but the AI increases detection volume without changing staffing, triage, or escalation rules, so users disable, ignore, or batch-process the alerts. The actionable break point is TEFCA participation: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Microsoft Cloud for Healthcare, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'TEFCA participation', 'Microsoft Cloud for Healthcare', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17386',
    name: 'Task Automation Triage Revenue Integrity Leakage',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for triage but automation improves throughput but misses the modifier, diagnosis specificity, charge trigger, or payer rule that defends reimbursement. The actionable break point is FHIR R4 mapping: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is AWS HealthLake, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'FHIR R4 mapping', 'AWS HealthLake', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17387',
    name: 'HR Service Delivery Drafting Audit Evidence Thinness',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for drafting but the AI recommendation cannot be reconstructed with input data, model version, user action, and policy context during compliance review. The actionable break point is HL7 v2 ADT reconciliation: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Azure Health Data Services, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'HL7 v2 ADT reconciliation', 'Azure Health Data Services', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17388',
    name: 'Policy Retrieval Summarization Criteria Drift',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for summarization but the evidence source changes faster than the workflow, so the AI keeps recommending the previous rule set until denials, audit exceptions, or missed measures surface downstream. The actionable break point is Epic change control: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Snowflake Healthcare, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'Epic change control', 'Snowflake Healthcare', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17389',
    name: 'Approval Workflow Risk Scoring Workflow Authority Gap',
    officeCategory: 'back_office',
    failureRatePct: 53,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for risk scoring but the model can draft or rank work but cannot safely take the EHR, payer, supply, or finance action that creates the intended operational value. The actionable break point is model registry: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Databricks Lakehouse, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'model registry', 'Databricks Lakehouse', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17390',
    name: 'Administrative Copilot Worklist Prioritization Subprocessor Blind Spot',
    officeCategory: 'back_office',
    failureRatePct: 77,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for worklist prioritization but the vendor routes PHI, audio, images, or derived features through a subcontractor that is not covered by the reviewed BAA, DPA, or security evidence package. The actionable break point is deployment-site validation: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is ServiceNow workflow, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'deployment-site validation', 'ServiceNow workflow', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17391',
    name: 'Task Automation Appeal Generation Validation Cohort Mismatch',
    officeCategory: 'back_office',
    failureRatePct: 81,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for appeal generation but the proof-of-concept succeeds on a clean validation slice but fails on community-hospital, Medicaid, specialty, or high-acuity populations. The actionable break point is MLOps monitoring: AbarVa should turn this into a Moves clinical governance checklist and a Source RFP scoring criterion before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Salesforce Health Cloud, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'MLOps monitoring', 'Salesforce Health Cloud', 'clinical governance checklist', 'RFP scoring criterion'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17392',
    name: 'HR Service Delivery Order Recommendation Adoption Telemetry Missing',
    officeCategory: 'back_office',
    failureRatePct: 57,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for order recommendation but the contract measures licenses and messages instead of accepted recommendations, corrected outputs, physician overrides, or realized value. The actionable break point is clinical safety review: AbarVa should turn this into a Moves adoption plan and a Source BAA clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is startup maturity evidence, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'clinical safety review', 'startup maturity evidence', 'adoption plan', 'BAA clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17393',
    name: 'Policy Retrieval Benefit Verification Human Override Ambiguity',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for benefit verification but clinical or administrative users cannot tell whether they are expected to accept, reject, document, or escalate an AI recommendation. The actionable break point is procurement RFP scoring: AbarVa should turn this into a Moves pre-mortem risk and a Source subprocessor schedule before scale funding. For Meridian-style regional systems, the ecosystem signal to test is SOC 2 Type II, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'procurement RFP scoring', 'SOC 2 Type II', 'pre-mortem risk', 'subprocessor schedule'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17394',
    name: 'Approval Workflow Eligibility Prediction Integration Surface Fragmentation',
    officeCategory: 'back_office',
    failureRatePct: 78,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for eligibility prediction but FHIR, HL7 v2, flat-file, API, and portal workflows are stitched together without a single source of truth for the decision state. The actionable break point is BAFO contract clause: AbarVa should turn this into a Moves dependency map and a Source model audit right before scale funding. For Meridian-style regional systems, the ecosystem signal to test is HITRUST roadmap, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'BAFO contract clause', 'HITRUST roadmap', 'dependency map', 'model audit right'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17395',
    name: 'Administrative Copilot Care Gap Closure Liability Handoff Gap',
    officeCategory: 'back_office',
    failureRatePct: 74,
    description: `Agentic AI: Administrative Copilots initiatives fail when administrative copilot is used for care gap closure but the AI output crosses from recommendation into attestation, order, appeal, documentation, or patient communication without accountable sign-off. The actionable break point is HIPAA BAA: AbarVa should turn this into a Moves approval gate and a Source deployment-site validation SLA before scale funding. For Meridian-style regional systems, the ecosystem signal to test is Series B burn rate, because a promising startup demo can still collapse when HR service delivery is not proven in production.`,
    keywords: ['administrative copilot', 'HR service delivery', 'HIPAA BAA', 'Series B burn rate', 'approval gate', 'deployment-site validation SLA'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17396',
    name: 'Task Automation Cohort Matching Equity Guardrail Drift',
    officeCategory: 'back_office',
    failureRatePct: 58,
    description: `Agentic AI: Administrative Copilots initiatives fail when task automation is used for cohort matching but the model performs acceptably in aggregate while underperforming for language, payer, race, rural access, disability, or complex-comorbidity cohorts. The actionable break point is minimum necessary policy: AbarVa should turn this into a Moves benefit validation plan and a Source adoption telemetry clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is implementation partner capacity, because a promising startup demo can still collapse when policy retrieval is not proven in production.`,
    keywords: ['task automation', 'policy retrieval', 'minimum necessary policy', 'implementation partner capacity', 'benefit validation plan', 'adoption telemetry clause'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17397',
    name: 'HR Service Delivery Contract Analysis Value Ledger Overstatement',
    officeCategory: 'back_office',
    failureRatePct: 54,
    description: `Agentic AI: Administrative Copilots initiatives fail when HR service delivery is used for contract analysis but finance books projected savings before adoption, payer response, clinician capacity, and downstream rework are measured in production. The actionable break point is TJC survey evidence: AbarVa should turn this into a Moves unsafe-to-fund gate and a Source exit-rights clause before scale funding. For Meridian-style regional systems, the ecosystem signal to test is referenceable health-system customer, because a promising startup demo can still collapse when approval workflow is not proven in production.`,
    keywords: ['HR service delivery', 'approval workflow', 'TJC survey evidence', 'referenceable health-system customer', 'unsafe-to-fund gate', 'exit-rights clause'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17398',
    name: 'Policy Retrieval Agentic Orchestration Agent Tool Boundary Failure',
    officeCategory: 'back_office',
    failureRatePct: 63,
    description: `Agentic AI: Administrative Copilots initiatives fail when policy retrieval is used for agentic orchestration but an agent has retrieval access but not the scoped action permissions, transaction logs, and rollback controls needed for safe autonomy. The actionable break point is CMS CoP: AbarVa should turn this into a Moves value realization ledger and a Source BAFO counter before scale funding. For Meridian-style regional systems, the ecosystem signal to test is clinical advisory board, because a promising startup demo can still collapse when administrative copilot is not proven in production.`,
    keywords: ['policy retrieval', 'administrative copilot', 'CMS CoP', 'clinical advisory board', 'value realization ledger', 'BAFO counter'],
    demoRelevant: true,
    subTopic: 'Agentic AI: Administrative Copilots',
  },
  {
    code: 'H17399',
    name: 'Approval Workflow Coding Suggestion Startup Roadmap Dependency',
    officeCategory: 'back_office',
    failureRatePct: 64,
    description: `Agentic AI: Administrative Copilots initiatives fail when approval workflow is used for coding suggestion but the health system commits to a product roadmap feature that is not generally available, validated, or contractually committed by the vendor. The actionable break point is NCQA HEDIS audit: AbarVa should turn this into a Moves pilot success metric and a Source RFI question before scale funding. For Meridian-style regional systems, the ecosystem signal to test is FDA submission posture, because a promising startup demo can still collapse when task automation is not proven in production.`,
    keywords: ['approval workflow', 'task automation', 'NCQA HEDIS audit', 'FDA submission posture', 'pilot success metric', 'RFI question'],
    demoRelevant: false,
    subTopic: 'Agentic AI: Administrative Copilots',
  }
];
